/**
 * traducciones-ui.js - Textos de interfaz traducidos a los 12 idiomas
 *
 * Centraliza bloques de traducción que antes estaban duplicados/dispersos
 * como constantes inline en codigo-padre.html, retos-hijo4.html,
 * chat-hijo6.html, En-busca-del-tesoro.html y video-intro.html.
 */

export const TRADUCCIONES_REANUDACION = {
    es: {
        titulo: '¡Aventura en curso!',
        info: 'Tienes una aventura activa:',
        idioma: 'Idioma',
        progreso: 'Progreso',
        parada: 'parada',
        de: 'de',
        continuar: 'Continuar mi aventura',
        elegirOtra: 'Elegir otra aventura',
        autoContinuar: 'Continuando automáticamente en',
        segundos: 's',
        advertenciaTitulo: '⚠️ Atención',
        advertenciaTexto1: 'Perderás todo el progreso de tu aventura actual:',
        advertenciaTexto2: 'Además, necesitarás adquirir una nueva aventura.',
        volver: 'Volver a mi aventura',
        confirmarOtra: 'Sí, elegir otra aventura'
    },
    en: {
        titulo: 'Adventure in progress!',
        info: 'You have an active adventure:',
        idioma: 'Language',
        progreso: 'Progress',
        parada: 'stop',
        de: 'of',
        continuar: 'Continue my adventure',
        elegirOtra: 'Choose another adventure',
        autoContinuar: 'Auto-continuing in',
        segundos: 's',
        advertenciaTitulo: '⚠️ Warning',
        advertenciaTexto1: 'You will lose all progress in your current adventure:',
        advertenciaTexto2: 'You will also need to purchase a new adventure.',
        volver: 'Return to my adventure',
        confirmarOtra: 'Yes, choose another adventure'
    },
    fr: {
        titulo: 'Aventure en cours !',
        info: 'Vous avez une aventure active :',
        idioma: 'Langue',
        progreso: 'Progression',
        parada: 'arrêt',
        de: 'sur',
        continuar: 'Continuer mon aventure',
        elegirOtra: 'Choisir une autre aventure',
        autoContinuar: 'Continuation automatique dans',
        segundos: 's',
        advertenciaTitulo: '⚠️ Attention',
        advertenciaTexto1: 'Vous perdrez toute la progression de votre aventure actuelle :',
        advertenciaTexto2: 'De plus, vous devrez acheter une nouvelle aventure.',
        volver: 'Retourner à mon aventure',
        confirmarOtra: 'Oui, choisir une autre aventure'
    },
    it: {
        titulo: 'Avventura in corso!',
        info: 'Hai un\'avventura attiva:',
        idioma: 'Lingua',
        progreso: 'Progresso',
        parada: 'tappa',
        de: 'di',
        continuar: 'Continua la mia avventura',
        elegirOtra: 'Scegli un\'altra avventura',
        autoContinuar: 'Continuazione automatica tra',
        segundos: 's',
        advertenciaTitulo: '⚠️ Attenzione',
        advertenciaTexto1: 'Perderai tutto il progresso della tua avventura attuale:',
        advertenciaTexto2: 'Inoltre, dovrai acquistare una nuova avventura.',
        volver: 'Torna alla mia avventura',
        confirmarOtra: 'Sì, scegli un\'altra avventura'
    },
    nl: {
        titulo: 'Avontuur bezig!',
        info: 'Je hebt een actief avontuur:',
        idioma: 'Taal',
        progreso: 'Voortgang',
        parada: 'halte',
        de: 'van',
        continuar: 'Mijn avontuur voortzetten',
        elegirOtra: 'Kies een ander avontuur',
        autoContinuar: 'Automatisch verder over',
        segundos: 's',
        advertenciaTitulo: '⚠️ Let op',
        advertenciaTexto1: 'Je verliest alle voortgang van je huidige avontuur:',
        advertenciaTexto2: 'Bovendien moet je een nieuw avontuur aanschaffen.',
        volver: 'Terug naar mijn avontuur',
        confirmarOtra: 'Ja, kies een ander avontuur'
    },
    ja: {
        titulo: '冒険が進行中です！',
        info: 'アクティブな冒険があります：',
        idioma: '言語',
        progreso: '進捗',
        parada: 'ストップ',
        de: '/',
        continuar: '冒険を続ける',
        elegirOtra: '別の冒険を選ぶ',
        autoContinuar: '自動的に続行します',
        segundos: '秒',
        advertenciaTitulo: '⚠️ 注意',
        advertenciaTexto1: '現在の冒険のすべての進捗を失います：',
        advertenciaTexto2: 'また、新しい冒険を購入する必要があります。',
        volver: '冒険に戻る',
        confirmarOtra: 'はい、別の冒険を選びます'
    },
    ru: {
        titulo: 'Приключение в процессе!',
        info: 'У вас есть активное приключение:',
        idioma: 'Язык',
        progreso: 'Прогресс',
        parada: 'остановка',
        de: 'из',
        continuar: 'Продолжить приключение',
        elegirOtra: 'Выбрать другое приключение',
        autoContinuar: 'Автоматическое продолжение через',
        segundos: 'с',
        advertenciaTitulo: '⚠️ Внимание',
        advertenciaTexto1: 'Вы потеряете весь прогресс текущего приключения:',
        advertenciaTexto2: 'Кроме того, вам нужно будет приобрести новое приключение.',
        volver: 'Вернуться к приключению',
        confirmarOtra: 'Да, выбрать другое приключение'
    },
    zh: {
        titulo: '冒险进行中！',
        info: '您有一个进行中的冒险：',
        idioma: '语言',
        progreso: '进度',
        parada: '站点',
        de: '/',
        continuar: '继续我的冒险',
        elegirOtra: '选择其他冒险',
        autoContinuar: '自动继续，倒计时',
        segundos: '秒',
        advertenciaTitulo: '⚠️ 注意',
        advertenciaTexto1: '您将失去当前冒险的所有进度：',
        advertenciaTexto2: '此外，您还需要购买新的冒险。',
        volver: '返回我的冒险',
        confirmarOtra: '是，选择其他冒险'
    },
    pl: {
        titulo: 'Przygoda w toku!',
        info: 'Masz aktywną przygodę:',
        idioma: 'Język',
        progreso: 'Postęp',
        parada: 'przystanek',
        de: 'z',
        continuar: 'Kontynuuj moją przygodę',
        elegirOtra: 'Wybierz inną przygodę',
        autoContinuar: 'Automatyczne kontynuowanie za',
        segundos: 's',
        advertenciaTitulo: '⚠️ Uwaga',
        advertenciaTexto1: 'Stracisz cały postęp swojej obecnej przygody:',
        advertenciaTexto2: 'Ponadto będziesz musiał zakupić nową przygodę.',
        volver: 'Wróć do mojej przygody',
        confirmarOtra: 'Tak, wybierz inną przygodę'
    },
    uk: {
        titulo: 'Пригода в процесі!',
        info: 'У вас є активна пригода:',
        idioma: 'Мова',
        progreso: 'Прогрес',
        parada: 'зупинка',
        de: 'з',
        continuar: 'Продовжити пригоду',
        elegirOtra: 'Вибрати іншу пригоду',
        autoContinuar: 'Автоматичне продовження через',
        segundos: 'с',
        advertenciaTitulo: '⚠️ Увага',
        advertenciaTexto1: 'Ви втратите весь прогрес поточної пригоди:',
        advertenciaTexto2: 'Крім того, вам потрібно буде придбати нову пригоду.',
        volver: 'Повернутися до пригоди',
        confirmarOtra: 'Так, вибрати іншу пригоду'
    },
    pt: {
        titulo: 'Aventura em curso!',
        info: 'Tem uma aventura ativa:',
        idioma: 'Idioma',
        progreso: 'Progresso',
        parada: 'paragem',
        de: 'de',
        continuar: 'Continuar a minha aventura',
        elegirOtra: 'Escolher outra aventura',
        autoContinuar: 'Continuação automática em',
        segundos: 's',
        advertenciaTitulo: '⚠️ Atenção',
        advertenciaTexto1: 'Perderá todo o progresso da sua aventura atual:',
        advertenciaTexto2: 'Além disso, precisará adquirir uma nova aventura.',
        volver: 'Voltar à minha aventura',
        confirmarOtra: 'Sim, escolher outra aventura'
    },
    de: {
        titulo: 'Abenteuer läuft!',
        info: 'Sie haben ein aktives Abenteuer:',
        idioma: 'Sprache',
        progreso: 'Fortschritt',
        parada: 'Halt',
        de: 'von',
        continuar: 'Mein Abenteuer fortsetzen',
        elegirOtra: 'Ein anderes Abenteuer wählen',
        autoContinuar: 'Automatische Fortsetzung in',
        segundos: 's',
        advertenciaTitulo: '⚠️ Achtung',
        advertenciaTexto1: 'Sie verlieren den gesamten Fortschritt Ihres aktuellen Abenteuers:',
        advertenciaTexto2: 'Außerdem müssen Sie ein neues Abenteuer erwerben.',
        volver: 'Zurück zu meinem Abenteuer',
        confirmarOtra: 'Ja, ein anderes Abenteuer wählen'
    }
};

export const TRADUCCIONES_FINALIZACION = {
    es: { titulo: '¡Felicidades!', completado: 'Has completado', pregunta: '¿Qué deseas hacer ahora?', btn_otra: 'Hacer otra aventura', btn_terminar: 'Terminar esta experiencia' },
    en: { titulo: 'Congratulations!', completado: 'You have completed', pregunta: 'What would you like to do now?', btn_otra: 'Start another adventure', btn_terminar: 'End this experience' },
    fr: { titulo: 'Félicitations !', completado: 'Vous avez terminé', pregunta: 'Que souhaitez-vous faire maintenant ?', btn_otra: 'Faire une autre aventure', btn_terminar: 'Terminer cette expérience' },
    it: { titulo: 'Congratulazioni!', completado: 'Hai completato', pregunta: 'Cosa desideri fare adesso?', btn_otra: "Fare un'altra avventura", btn_terminar: 'Terminare questa esperienza' },
    nl: { titulo: 'Gefeliciteerd!', completado: 'Je hebt voltooid', pregunta: 'Wat wil je nu doen?', btn_otra: 'Een ander avontuur beginnen', btn_terminar: 'Deze ervaring beëindigen' },
    de: { titulo: 'Herzlichen Glückwunsch!', completado: 'Sie haben abgeschlossen', pregunta: 'Was möchten Sie jetzt tun?', btn_otra: 'Ein anderes Abenteuer beginnen', btn_terminar: 'Dieses Erlebnis beenden' },
    ja: { titulo: 'おめでとうございます！', completado: '完了しました', pregunta: '次に何をしますか？', btn_otra: '別のアドベンチャーを始める', btn_terminar: 'この体験を終了する' },
    zh: { titulo: '恭喜！', completado: '您已完成', pregunta: '您现在想做什么？', btn_otra: '开始另一个冒险', btn_terminar: '结束此体验' },
    pl: { titulo: 'Gratulacje!', completado: 'Ukończyłeś', pregunta: 'Co chcesz teraz zrobić?', btn_otra: 'Rozpocząć inną przygodę', btn_terminar: 'Zakończyć to doświadczenie' },
    pt: { titulo: 'Parabéns!', completado: 'Você completou', pregunta: 'O que deseja fazer agora?', btn_otra: 'Fazer outra aventura', btn_terminar: 'Terminar esta experiência' },
    ru: { titulo: 'Поздравляем!', completado: 'Вы завершили', pregunta: 'Что вы хотите сделать сейчас?', btn_otra: 'Начать другое приключение', btn_terminar: 'Завершить этот опыт' },
    uk: { titulo: 'Вітаємо!', completado: 'Ви завершили', pregunta: 'Що ви хочете зробити тепер?', btn_otra: 'Розпочати іншу пригоду', btn_terminar: 'Завершити цей досвід' }
};

export const TRADUCCIONES_TIEMPO_AGOTADO = {
    es: { titulo: '¡Tiempo agotado!', cuerpo: 'El tiempo máximo para completar esta aventura ha terminado. Gracias por participar.' },
    en: { titulo: "Time's up!", cuerpo: 'The maximum time to complete this adventure has ended. Thank you for participating.' },
    fr: { titulo: 'Temps écoulé !', cuerpo: 'Le temps maximum pour terminer cette aventure est terminé. Merci d\'avoir participé.' },
    it: { titulo: 'Tempo scaduto!', cuerpo: 'Il tempo massimo per completare questa avventura è terminato. Grazie per aver partecipato.' },
    nl: { titulo: 'Tijd verstreken!', cuerpo: 'De maximale tijd om dit avontuur te voltooien is verstreken. Bedankt voor je deelname.' },
    de: { titulo: 'Zeit abgelaufen!', cuerpo: 'Die maximale Zeit für dieses Abenteuer ist abgelaufen. Danke fürs Mitmachen.' },
    ja: { titulo: '時間切れです！', cuerpo: 'この冒険を完了するための制限時間が終了しました。ご参加ありがとうございました。' },
    zh: { titulo: '时间到！', cuerpo: '完成此冒险的最长时间已结束。感谢您的参与。' },
    pl: { titulo: 'Czas minął!', cuerpo: 'Maksymalny czas na ukończenie tej przygody dobiegł końca. Dziękujemy za udział.' },
    pt: { titulo: 'Tempo esgotado!', cuerpo: 'O tempo máximo para completar esta aventura terminou. Obrigado por participar.' },
    ru: { titulo: 'Время истекло!', cuerpo: 'Максимальное время для прохождения этого приключения истекло. Спасибо за участие.' },
    uk: { titulo: 'Час вийшов!', cuerpo: 'Максимальний час для проходження цієї пригоди закінчився. Дякуємо за участь.' }
};

export const TRADUCCIONES_DESPEDIDA = {
    es: '¡Hasta pronto! Gracias por explorar Valencia con nosotros.',
    en: 'Goodbye! Thank you for exploring Valencia with us.',
    fr: 'Au revoir ! Merci d\'avoir exploré Valence avec nous.',
    it: 'Arrivederci! Grazie per aver esplorato Valencia con noi.',
    nl: 'Tot ziens! Bedankt voor het verkennen van Valencia met ons.',
    de: 'Auf Wiedersehen! Danke, dass Sie Valencia mit uns erkundet haben.',
    ja: 'またね！バレンシアを一緒に探検してくれてありがとう。',
    zh: '再见！感谢您与我们一起探索瓦伦西亚。',
    pl: 'Do widzenia! Dziękujemy za eksplorację Walencji z nami.',
    pt: 'Até logo! Obrigado por explorar Valência connosco.',
    ru: 'До свидания! Спасибо, что исследовали Валенсию вместе с нами.',
    uk: 'До побачення! Дякуємо, що досліджували Валенсію разом з нами.'
};

export const MSG_RETOS_COMPLETOS = {
    es: '¡Has completado todos los retos!',
    en: "You've completed all the challenges!",
    fr: 'Vous avez terminé tous les défis !',
    it: 'Hai completato tutte le sfide!',
    nl: 'Je hebt alle uitdagingen voltooid!',
    ja: 'すべてのチャレンジをクリアしました！',
    de: 'Du hast alle Aufgaben abgeschlossen!',
    zh: '你已完成所有挑战！',
    pl: 'Ukończono wszystkie wyzwania!',
    pt: 'Completaste todos os desafios!',
    ru: 'Вы завершили все задания!',
    uk: 'Ви завершили всі завдання!'
};

export const TITULOS_CHAT = {
    es: 'Soporte', en: 'Support', fr: 'Assistance',
    it: 'Supporto', nl: 'Ondersteuning', ja: 'サポート',
    de: 'Hilfe', zh: '帮助', pl: 'Pomoc',
    pt: 'Suporte', ru: 'Помощь', uk: 'Допомога'
};

// Un objeto por pantalla de video-intro.html, en el mismo orden que run().
// El índice 15 es null (escena visual sin bocadillo).
export const JAIME_SCENES = [
    // 0 — Logos / bienvenida
    {
        es: '¡Saludos! ¡Le damos la bienvenida a esta nueva aventura! Somos Jaime I y María de Castilla. Permítanos acompañarle durante los primeros pasos de su búsqueda del tesoro.',
        en: 'Welcome to your new adventure! We are James the First of Aragon and María of Castile — delighted to be your guides on this treasure hunt through Valencia.',
        fr: 'Bienvenue dans cette nouvelle aventure ! Nous sommes Jacques Ier d\'Aragon et Marie de Castille — ravis d\'être vos guides pour cette chasse au trésor à travers Valence.',
        it: 'Benvenuti in questa nuova avventura! Siamo Giacomo I d\'Aragona e María di Castiglia — felici di essere le vostre guide in questa caccia al tesoro attraverso Valencia.',
        nl: 'Welkom bij dit nieuwe avontuur! Wij zijn Jacobus I van Aragón en María van Castilië — verheugd om uw gidsen te zijn op deze schattenjacht door Valencia.',
        ja: 'ご挨拶申し上げます！この新しい冒険へようこそ！私たちはハイメ1世とカスティーリャのマリアです。宝探しの最初の一歩をご一緒させてください。',
        de: 'Willkommen zu diesem neuen Abenteuer! Wir sind Jakob I. von Aragón und María von Kastilien — und freuen uns sehr, Ihre Guides bei dieser Schatzsuche durch Valencia zu sein.',
        zh: '您好！欢迎来到这次新的冒险！我们是哈梅一世和卡斯蒂利亚的玛丽亚。请允许我们陪伴您踏上寻宝之旅的第一步。',
        pl: 'Pozdrowienia! Witamy w tej nowej przygodzie! Jesteśmy Jakubem I i Marią z Kastylii. Pozwólcie, że towarzyszymy wam podczas pierwszych kroków poszukiwania skarbu.',
        pt: 'Bem-vindos a esta nova aventura! Somos Jaime I de Aragão e Maria de Castela — encantados por ser os vossos guias nesta caça ao tesouro por Valência.',
        ru: 'Приветствуем! Добро пожаловать в это новое приключение! Мы — Хайме I и Мария Кастильская. Позвольте нам сопровождать вас в первых шагах вашей охоты за сокровищами.',
        uk: 'Вітаємо! Ласкаво просимо до цієї нової пригоди! Ми — Хайме I та Марія Кастильська. Дозвольте нам супроводжувати вас під час перших кроків пошуку скарбу.',
    },
    // 1 — GPS / internet (reubicada como segunda pantalla)
    {
        es: 'Una pequeña cosa antes de partir: active el GPS, asegúrese de tener conexión a internet y conceda los permisos que le solicite su dispositivo.',
        en: 'One small thing before you set off: make sure GPS and internet are switched on, and grant any permissions your device asks for.',
        fr: 'Avant de partir, une petite chose : vérifiez que le GPS et internet sont bien activés, et accordez les autorisations que votre appareil vous demande.',
        it: 'Prima di partire, una piccola cosa: assicuratevi che GPS e internet siano attivi e concedete i permessi che il vostro dispositivo vi chiede.',
        nl: 'Eén dingetje voor u vertrekt: zorg dat GPS en internet aanstaan en geef de toestemmingen die uw apparaat vraagt.',
        ja: '出発前にひとつ：GPSを有効にし、インターネット接続を確認し、デバイスが要求する権限を許可してください。',
        de: 'Noch kurz vor dem Start: Stellen Sie sicher, dass GPS und Internet aktiviert sind, und erteilen Sie die Berechtigungen, die Ihr Gerät anfordert.',
        zh: '出发前的小事：请开启GPS，确保有网络连接，并授予设备所需的权限。',
        pl: 'Jedna mała rzecz przed wyruszeniem: włączcie GPS, upewnijcie się, że macie połączenie z internetem i przyznajcie uprawnienia, których wymaga urządzenie.',
        pt: 'Antes de partir, uma pequena coisa: certifique-se de que o GPS e a internet estão ativos e conceda as permissões que o seu dispositivo pedir.',
        ru: 'Одна небольшая вещь перед отправлением: включите GPS, убедитесь в наличии интернет-соединения и предоставьте разрешения, которые запрашивает ваше устройство.',
        uk: 'Одна невелика річ перед відправленням: увімкніть GPS, переконайтеся, що є підключення до інтернету, та надайте дозволи, які запитує ваш пристрій.',
    },
    // 2 — Selección de aventura
    {
        es: 'Tenemos el gusto de poder ofrecerle varias aventuras. Cada una tiene su distancia y duración determinada y también un tipo de transporte recomendado. Elija la que más le guste o se adapte a sus necesidades.',
        en: 'We have several adventures lined up for you. Each one has its own distance, duration and a suggested way to get around. Pick the one that suits you best.',
        fr: 'Nous vous proposons plusieurs aventures. Chacune a sa distance, sa durée et un moyen de transport conseillé. Choisissez celle qui vous convient le mieux.',
        it: 'Vi proponiamo diverse avventure. Ognuna ha la sua distanza, la sua durata e un mezzo di trasporto consigliato. Scegliete quella che fa più al caso vostro.',
        nl: 'We hebben verschillende avonturen voor u klaarstaan. Elk heeft zijn eigen afstand, duur en een aangeraden vervoersmiddel. Kies degene die het beste bij u past.',
        ja: 'いくつかの冒険をご用意しております。それぞれ決まった距離と所要時間、おすすめの交通手段があります。お好みや、ご自身のニーズに合ったものをお選びください。',
        de: 'Wir haben mehrere Abenteuer für Sie im Angebot. Jedes hat seine eigene Strecke, Dauer und ein empfohlenes Verkehrsmittel. Wählen Sie das, das am besten zu Ihnen passt.',
        zh: '我们荣幸地为您提供多种冒险选择。每项冒险都有确定的距离和时长，以及推荐的交通方式。请选择您最喜欢或最适合您需求的一项。',
        pl: 'Mamy przyjemność zaoferować wam kilka przygód. Każda ma określoną odległość i czas trwania, a także zalecany środek transportu. Wybierzcie tę, która najbardziej wam odpowiada lub najlepiej pasuje do waszych potrzeb.',
        pt: 'Temos várias aventuras à sua espera. Cada uma tem a sua distância, duração e um meio de transporte sugerido. Escolha a que melhor lhe convém.',
        ru: 'Мы рады предложить вам несколько приключений. Каждое имеет заданную дистанцию и продолжительность, а также рекомендуемый вид транспорта. Выберите то, что вам больше всего нравится или лучше всего соответствует вашим потребностям.',
        uk: 'Ми раді запропонувати вам кілька пригод. Кожна має визначену відстань і тривалість, а також рекомендований вид транспорту. Оберіть ту, яка вам найбільше подобається або найкраще відповідає вашим потребам.',
    },
    // 3 — Mapa vintage de la aventura
    {
        es: 'Un vistazo a su aventura al completo: paradas numeradas, ruta trazada. La ciudad entera, esperándole.',
        en: 'Your full adventure at a glance: numbered stops, a mapped-out route — and the whole city waiting to be explored.',
        fr: 'Votre aventure en un coup d\'œil : arrêts numérotés, itinéraire tracé — et toute la ville qui n\'attend que vous.',
        it: 'La vostra avventura tutta d\'un colpo: tappe numerate, percorso tracciato — e l\'intera città pronta ad accogliervi.',
        nl: 'Uw avontuur in één oogopslag: genummerde haltes, uitgestippelde route — en de hele stad die op u wacht.',
        ja: 'あなたの冒険を一望できます：番号付きの停車地、描かれたルート。街全体があなたを待っています。',
        de: 'Ihr gesamtes Abenteuer auf einen Blick: nummerierte Stopps, eingezeichnete Route — und die ganze Stadt, die auf Sie wartet.',
        zh: '纵览您的完整冒险：编号停靠点、绘制路线。整座城市，静候您的到来。',
        pl: 'Rzut oka na całą przygodę: ponumerowane przystanki, wytyczona trasa. Całe miasto czeka na was.',
        pt: 'A sua aventura toda de relance: paragens numeradas, rota traçada — e a cidade inteira à sua espera.',
        ru: 'Взгляд на всё ваше приключение: пронумерованные остановки, проложенный маршрут. Весь город ждёт вас.',
        uk: 'Погляд на всю вашу пригоду: пронумеровані зупинки, прокладений маршрут. Усе місто чекає на вас.',
    },
    // 4 — Grid de todos los botones
    {
        es: 'Estos son los botones que harán posible su aventura. Los iremos descubriendo uno a uno.',
        en: 'Here are the buttons that will power your adventure. Let\'s go through them one by one.',
        fr: 'Voici les boutons qui vont animer votre aventure. Découvrons-les ensemble, un par un.',
        it: 'Ecco i pulsanti che daranno vita alla vostra avventura. Scopriamoli insieme, uno per uno.',
        nl: 'Dit zijn de knoppen die uw avontuur tot leven brengen. We lopen ze samen één voor één door.',
        ja: 'これらのボタンがあなたの冒険を可能にします。一つずつご確認いきましょう。',
        de: 'Das sind die Buttons, die Ihr Abenteuer zum Leben erwecken. Schauen wir sie gemeinsam einen nach dem anderen an.',
        zh: '这些按钮将使您的冒险成为可能。我们将逐一了解它们。',
        pl: 'To są przyciski, które umożliwią waszą przygodę. Będziemy je odkrywać jeden po drugim.',
        pt: 'Estes são os botões que vão dar vida à sua aventura. Vamos percorrê-los juntos, um a um.',
        ru: 'Это кнопки, которые сделают ваше приключение возможным. Мы будем открывать их одну за другой.',
        uk: 'Це кнопки, які зроблять вашу пригоду можливою. Ми відкриватимемо їх одну за одною.',
    },
    // 5 — Botón mapa digital completo (b1)
    {
        es: 'Este botón le mostrará el trazado completo de su aventura, así como los puntos relevantes a visitar.',
        en: 'This button shows you the full route of your adventure and all the key stops along the way.',
        fr: 'Ce bouton affiche le tracé complet de votre aventure ainsi que tous les points clés à visiter.',
        it: 'Questo pulsante mostra il percorso completo della vostra avventura e tutte le tappe da non perdere.',
        nl: 'Deze knop toont u de volledige route van uw avontuur en alle belangrijke punten om te bezoeken.',
        ja: 'このボタンを押すと、冒険の完全なルートと訪問すべき重要なポイントが表示されます。',
        de: 'Dieser Button zeigt Ihnen den vollständigen Streckenverlauf Ihres Abenteuers und alle wichtigen Anlaufpunkte.',
        zh: '此按钮将为您显示冒险的完整路线以及需要参观的相关地点。',
        pl: 'Ten przycisk pokaże wam pełny przebieg trasy waszej przygody, a także istotne punkty do odwiedzenia.',
        pt: 'Este botão mostra o traçado completo da sua aventura e todos os pontos-chave a visitar.',
        ru: 'Эта кнопка покажет вам полный маршрут вашего приключения, а также важные точки для посещения.',
        uk: 'Ця кнопка покаже вам повний маршрут вашої пригоди, а також відповідні місця для відвідування.',
    },
    // 6 — Botón mapa vintage (b2)
    {
        es: 'Este botón le mostrará el mismo mapa, pero con alma de época. Un estilo vintage que le transportará siglos atrás. ¿cuál prefiere?',
        en: 'The same map — but with a soul all of its own. A vintage style that takes you centuries back in time. Which do you prefer?',
        fr: 'La même carte — mais avec tout le charme d\'une autre époque. Un style vintage qui vous replonge plusieurs siècles en arrière. Laquelle préférez-vous ?',
        it: 'La stessa mappa — ma con tutto il fascino di un\'altra epoca. Uno stile vintage che vi riporta indietro di secoli. Quale preferite?',
        nl: 'Dezelfde kaart — maar met de charme van een ander tijdperk. Een vintage stijl die u eeuwen terugvoert in de tijd. Welke heeft uw voorkeur?',
        ja: 'このボタンを押すと同じ地図が表示されますが、時代の魂を宿しています。ヴィンテージスタイルが何世紀も前へとあなたを誘います。どちらがお好みですか？',
        de: 'Dieselbe Karte — aber mit dem Charme einer längst vergangenen Epoche. Ein Vintage-Stil, der Sie Jahrhunderte zurückversetzt. Welche gefällt Ihnen besser?',
        zh: '此按钮将为您显示同样的地图，却有着岁月的灵魂。复古风格将带您穿越数百年。您更喜欢哪一个？',
        pl: 'Ten przycisk pokaże wam tę samą mapę, ale z duszą epoki. Styl vintage, który przeniesie was o wieki wstecz. Który wolelibyście?',
        pt: 'O mesmo mapa — mas com todo o charme de outra época. Um estilo vintage que o leva de volta séculos no tempo. Qual prefere?',
        ru: 'Эта кнопка покажет вам ту же карту, но с душой эпохи. Винтажный стиль перенесёт вас на несколько веков назад. Что вы предпочитаете?',
        uk: 'Ця кнопка покаже вам ту саму карту, але з душею епохи. Вінтажний стиль перенесе вас на кілька століть назад. Що ви надаєте перевагу?',
    },
    // 7 — Botón avanzar (b-av)
    {
        es: 'De parada en parada irá descubriendo maravillosos tesoros que le ofrece la ciudad, la aventura avanza con usted. Este botón se activa o desactiva automáticamente, siempre al ritmo que necesite.',
        en: 'Stop by stop, the city reveals its wonderful treasures as the adventure unfolds around you. This button switches on and off automatically — always keeping pace with you.',
        fr: 'Arrêt après arrêt, la ville vous dévoile ses merveilleux trésors tandis que l\'aventure avance à votre rythme. Ce bouton s\'active et se désactive automatiquement — toujours au bon moment.',
        it: 'Tappa dopo tappa, la città vi svela i suoi meravigliosi tesori mentre l\'avventura procede al vostro ritmo. Questo pulsante si attiva e si disattiva da solo — sempre al momento giusto.',
        nl: 'Halte na halte onthult de stad haar prachtige schatten terwijl het avontuur in uw tempo voortgaat. Deze knop schakelt automatisch in en uit — altijd precies op het juiste moment.',
        ja: '停車地から停車地へと、街が誇る素晴らしい宝を発見しながら、冒険はあなたと共に進みます。このボタンは自動的に有効または無効になり、常に必要なペースに合わせてくれます。',
        de: 'Stopp für Stopp enthüllt die Stadt ihre wunderbaren Schätze, während das Abenteuer in Ihrem Tempo vorangeht. Dieser Button schaltet sich automatisch ein und aus — immer genau dann, wenn es nötig ist.',
        zh: '一站接一站，您将发现这座城市所提供的美妙宝藏，冒险与您同行。此按钮会自动启用或禁用，始终按您所需的节奏。',
        pl: 'Przystanek po przystanku będziecie odkrywać wspaniałe skarby, które oferuje miasto, a przygoda postępuje razem z wami. Ten przycisk aktywuje się lub dezaktywuje automatycznie, zawsze we właściwym rytmie.',
        pt: 'Paragem a paragem, a cidade revela os seus maravilhosos tesouros enquanto a aventura avança ao seu ritmo. Este botão ativa-se e desativa-se automaticamente — sempre na hora certa.',
        ru: 'Остановка за остановкой вы будете открывать для себя удивительные сокровища, которые предлагает город, а приключение движется вместе с вами. Эта кнопка включается или выключается автоматически, всегда в нужном вам темпе.',
        uk: 'Зупинка за зупинкою ви відкриватимете чудові скарби, які пропонує місто, а пригода рухається разом з вами. Ця кнопка вмикається або вимикається автоматично, завжди в потрібному вам темпі.',
    },
    // 8 — Botón imagen próxima parada (b4)
    {
        es: '¿Llegando a una nueva parada? Pulse este botón y un vistazo a la imagen de su próxima parada le ayudará a reconocer el lugar al instante.',
        en: 'Coming up on a new stop? Tap this button for a quick look at the photo so you can spot the place straight away.',
        fr: 'Vous approchez d\'un nouvel arrêt ? Appuyez sur ce bouton pour voir la photo et repérer l\'endroit d\'un seul coup d\'œil.',
        it: 'Siete vicini a una nuova tappa? Premete questo pulsante per vedere la foto e riconoscere il posto in un colpo d\'occhio.',
        nl: 'Nadert u een nieuwe halte? Tik op deze knop voor een snelle blik op de foto en herken de plek meteen.',
        ja: '新しい停車地に近づいていますか？このボタンを押すと、次の停車地の画像をひと目見るだけで、その場所をすぐに認識できます。',
        de: 'Nähern Sie sich der nächsten Haltestelle? Drücken Sie diesen Button für einen schnellen Blick auf das Foto und erkennen Sie den Ort auf Anhieb.',
        zh: '即将到达新的停靠点？点击此按钮，看一眼您下一个停靠点的图片，便能立即认出那个地方。',
        pl: 'Zbliżacie się do nowego przystanku? Naciśnijcie ten przycisk, a jedno spojrzenie na zdjęcie waszego następnego przystanku pomoże natychmiast rozpoznać miejsce.',
        pt: 'A aproximar-se de uma nova paragem? Prima este botão para ver a foto e reconhecer o local de imediato.',
        ru: 'Подъезжаете к новой остановке? Нажмите эту кнопку, и один взгляд на изображение следующей остановки поможет вам мгновенно узнать место.',
        uk: 'Наближаєтеся до нової зупинки? Натисніть цю кнопку, і один погляд на зображення вашої наступної зупинки допоможе миттєво впізнати місце.',
    },
    // 9 — Botón vídeo / dron (b3)
    {
        es: 'Para quienes prefieran anticiparse antes de llegar: pulsando este botón, un vídeo le guiará hasta la siguiente parada, sin perderse nada. Puede volver a ver el vídeo si lo necesita para no desviarse de la ruta designada.',
        en: 'Rather see where you\'re heading before you get there? Tap this button for a short video guide to the next stop. You can watch it again any time to stay on track.',
        fr: 'Vous préférez voir où vous allez avant d\'y arriver ? Ce bouton lance une courte vidéo qui vous guide jusqu\'au prochain arrêt. Regardez-la autant de fois qu\'il le faut pour rester sur le bon chemin.',
        it: 'Preferite sapere dove state andando prima di arrivarci? Premete questo pulsante per un breve video che vi guida fino alla prossima tappa. Rivedetelo quando volete per restare sul percorso giusto.',
        nl: 'Wilt u al weten waar u naartoe gaat? Druk op deze knop voor een korte video die u naar de volgende halte begeleidt. Bekijk hem opnieuw wanneer u dat nodig heeft om op de route te blijven.',
        ja: '到着前に先を知りたい方へ：このボタンを押すと、次の停車地まで何も見逃さずにビデオが案内します。指定されたルートから外れないよう、必要であれば再度ビデオをご覧になれます。',
        de: 'Möchten Sie schon wissen, wo es als Nächstes hingeht? Drücken Sie diesen Button für ein kurzes Video, das Sie zur nächsten Haltestelle führt. Schauen Sie es so oft wie nötig, um auf Kurs zu bleiben.',
        zh: '对于喜欢提前了解的您：按下此按钮，一段视频将引导您前往下一个停靠点，不遗漏任何细节。如果需要，您可以重新观看视频，以便不偏离指定路线。',
        pl: 'Dla tych, którzy wolą przygotować się przed dotarciem: naciskając ten przycisk, film poprowadzi was do następnego przystanku, bez pominięcia czegokolwiek. Możecie obejrzeć film ponownie, jeśli potrzebujecie, aby nie zbaczać z wyznaczonej trasy.',
        pt: 'Prefere saber para onde vai antes de lá chegar? Prima este botão para um breve vídeo que o guia até à próxima paragem. Reveja-o sempre que precisar para manter a rota certa.',
        ru: 'Для тех, кто предпочитает подготовиться заранее: нажав эту кнопку, видео проведёт вас к следующей остановке, не упустив ничего. Вы можете просмотреть видео повторно, если нужно, чтобы не отклоняться от указанного маршрута.',
        uk: 'Для тих, хто вважає за краще підготуватися наперед: натиснувши цю кнопку, відео проведе вас до наступної зупинки, не пропустивши нічого. Ви можете переглянути відео ще раз, якщо потрібно, щоб не відхилятися від вказаного маршруту.',
    },
    // 10 — Botón audio principal
    {
        es: 'En Busca del Tesoro es una experiencia audioguiada, interactiva y didáctica, ideal para descubrir la ciudad mientras juega. Este botón le permitirá escuchar las narraciones en el idioma que elija.',
        en: 'En Busca del Tesoro is an audio-guided, interactive experience designed to help you discover the city while you play. Use this button to listen to the commentary in the language of your choice.',
        fr: 'En Busca del Tesoro est une expérience interactive avec audioguide, idéale pour découvrir la ville en s\'amusant. Ce bouton vous permet d\'écouter les commentaires dans la langue de votre choix.',
        it: 'En Busca del Tesoro è un\'esperienza interattiva con audioguida, pensata per scoprire la città divertendosi. Con questo pulsante ascoltate i commenti nella lingua che preferite.',
        nl: 'En Busca del Tesoro is een interactieve ervaring met audiobegeleiding, ideaal om de stad te ontdekken terwijl u speelt. Gebruik deze knop om het commentaar te beluisteren in de taal van uw keuze.',
        ja: '「En Busca del Tesoro」は、遊びながら街を発見するのに理想的な、音声ガイド付きのインタラクティブで教育的な体験です。このボタンで、お好みの言語でナレーションをお聴きいただけます。',
        de: 'En Busca del Tesoro ist ein interaktives Erlebnis mit Audioführung, das Ihnen hilft, die Stadt spielerisch zu entdecken. Mit diesem Button hören Sie den Kommentar in der Sprache Ihrer Wahl.',
        zh: '《En Busca del Tesoro》是一项有声导览的互动教育体验，非常适合在游戏中发现这座城市。此按钮让您可以用自己选择的语言收听旁白。',
        pl: 'En Busca del Tesoro to interaktywne i dydaktyczne doświadczenie z przewodnikiem audio, idealne do odkrywania miasta podczas zabawy. Ten przycisk pozwoli wam słuchać narracji w wybranym języku.',
        pt: 'En Busca del Tesoro é uma experiência interativa com audioguia, pensada para descobrir a cidade a jogar. Use este botão para ouvir os comentários no idioma da sua escolha.',
        ru: 'En Busca del Tesoro — это аудиогид, интерактивный и познавательный опыт, идеальный для открытия города во время игры. Эта кнопка позволит вам слушать рассказы на выбранном языке.',
        uk: 'En Busca del Tesoro — це аудіогід, інтерактивний та навчальний досвід, ідеальний для відкриття міста під час гри. Ця кнопка дозволить вам слухати розповіді обраною мовою.',
    },
    // 11 — Reto puzzle
    {
        es: 'Cuando este botón se habilite, la diversión irá un paso más allá. Puzles, acertijos y pruebas le esperan.',
        en: 'When this button lights up, the fun takes it up a notch. Puzzles, riddles and challenges are waiting for you.',
        fr: 'Quand ce bouton s\'allume, le plaisir monte d\'un cran. Puzzles, énigmes et défis vous attendent.',
        it: 'Quando questo pulsante si accende, il divertimento sale di livello. Puzzle, enigmi e sfide vi aspettano.',
        nl: 'Zodra deze knop oplicht, gaat het plezier een flinke stap verder. Puzzels, raadsels en uitdagingen wachten op u.',
        ja: 'このボタンが使えるようになると、楽しさがもう一段上がります。パズル、なぞなぞ、そして試練があなたを待っています。',
        de: 'Sobald dieser Button aufleuchtet, steigt der Spaß auf das nächste Level. Puzzles, Rätsel und Aufgaben warten auf Sie.',
        zh: '当此按钮可用时，乐趣将更进一步。拼图、谜语和挑战等待着您。',
        pl: 'Gdy ten przycisk stanie się dostępny, zabawa pójdzie o krok dalej. Puzzle, zagadki i próby czekają na was.',
        pt: 'Quando este botão se acender, a diversão sobe de nível. Puzzles, enigmas e desafios esperam por si.',
        ru: 'Когда эта кнопка станет доступна, веселье выйдет на новый уровень. Головоломки, загадки и испытания ждут вас.',
        uk: 'Коли ця кнопка стане доступною, розваги підуть на крок далі. Пазли, загадки та випробування чекають на вас.',
    },
    // 12 — Reto preguntas MCQ
    {
        es: '¿Y si las preguntas no fueran tan simples? Algunas son de opción múltiple y pueden tener más de una respuesta correcta. ¡Lea con atención antes de responder y observe su entorno!',
        en: 'Not all questions are as simple as they look. Some are multiple choice — and more than one answer may be correct. Read carefully, look around you and think before you tap!',
        fr: 'Les questions ne sont pas toujours aussi simples qu\'elles en ont l\'air. Certaines sont à choix multiples — et il peut y avoir plus d\'une bonne réponse. Lisez bien, regardez autour de vous et réfléchissez avant de répondre !',
        it: 'Non tutte le domande sono semplici come sembrano. Alcune sono a risposta multipla — e ci può essere più di una risposta giusta. Leggete con attenzione, guardate intorno a voi e ragionate prima di rispondere!',
        nl: 'Niet alle vragen zijn zo eenvoudig als ze lijken. Sommige zijn meerkeuzevragen — en er kan meer dan één juist antwoord zijn. Lees goed, kijk om u heen en denk na voor u tikt!',
        ja: 'もし質問がそれほど簡単でなかったら？複数選択式で、正しい答えが複数ある場合もあります。答える前によく読み、周囲をよく観察しましょう！',
        de: 'Nicht alle Fragen sind so einfach, wie sie aussehen. Manche sind Multiple-Choice — und es kann mehr als eine richtige Antwort geben. Lesen Sie genau, schauen Sie sich um und denken Sie nach, bevor Sie tippen!',
        zh: '如果问题没那么简单呢？有些是多选题，可能有不止一个正确答案。回答前请仔细阅读，并观察周围环境！',
        pl: 'A gdyby pytania nie były takie proste? Niektóre są wielokrotnego wyboru i mogą mieć więcej niż jedną poprawną odpowiedź. Czytajcie uważnie przed odpowiedzią i obserwujcie otoczenie!',
        pt: 'Nem todas as perguntas são tão simples como parecem. Algumas são de escolha múltipla — e pode haver mais do que uma resposta certa. Leia com atenção, olhe à sua volta e pense antes de responder!',
        ru: 'А что, если вопросы окажутся не такими простыми? Некоторые из них с множественным выбором и могут иметь несколько правильных ответов. Читайте внимательно перед ответом и наблюдайте за своим окружением!',
        uk: 'А що, якщо запитання виявляться не такими простими? Деякі є множинним вибором і можуть мати більше однієї правильної відповіді. Читайте уважно перед відповіддю та спостерігайте за своїм оточенням!',
    },
    // 13 — Pausa / cámara / lugar recomendado
    {
        es: 'Valencia merece ser saboreada. Fotografíe, descanse, explore el lugar recomendado… Su aventura no tiene prisa. Tampoco usted. Le invitamos a recorrer sus calles, resolver enigmas y descubrir su patrimonio de una forma amena. Hagamos de la historia una experiencia divertida.',
        en: 'Valencia deserves to be savoured. Stop for a photo, take a rest, explore the recommended spot… There\'s no rush. Wander the streets, unravel the mysteries and discover the city\'s heritage at your own pace. Let\'s make history an experience worth remembering.',
        fr: 'Valence mérite d\'être savourée. Prenez des photos, faites une pause, explorez l\'endroit recommandé… Rien ne presse. Flânez dans ses rues, percez ses mystères et découvrez son patrimoine à votre rythme. Faisons ensemble de l\'histoire une expérience mémorable.',
        it: 'Valencia merita di essere assaporata. Scattate foto, riposatevi, esplorate il posto consigliato… Non c\'è fretta. Passeggiate per le sue strade, svelate i suoi misteri e scoprite il patrimonio della città al vostro ritmo. Facciamo insieme della storia un\'esperienza da ricordare.',
        nl: 'Valencia verdient het om te worden geproefd. Maak foto\'s, neem een pauze, verken de aanbevolen plek… Er is geen haast. Slenter door de straten, los de raadsels op en ontdek het erfgoed van de stad op uw eigen tempo. Laten we er samen een onvergetelijke ervaring van maken.',
        ja: 'バレンシアは味わう価値があります。写真を撮り、休息し、おすすめの場所を探索してください…あなたの冒険は急ぎません。あなたも同じです。街の通りを歩き、謎を解き、その文化遺産を楽しく発見されることをお勧めします。歴史を楽しい体験にしましょう。',
        de: 'Valencia verdient es, ausgekostet zu werden. Machen Sie Fotos, ruhen Sie sich aus, erkunden Sie den empfohlenen Ort… Es gibt keine Eile. Schlendern Sie durch die Straßen, lösen Sie Rätsel und entdecken Sie das Kulturerbe der Stadt in Ihrem eigenen Tempo. Machen wir gemeinsam aus der Geschichte ein unvergessliches Erlebnis.',
        zh: '瓦伦西亚值得细细品味。拍照、休息、探索推荐的地方……您的冒险不着急，您也不必着急。我们邀请您漫步于街道之间，解开谜题，以轻松愉快的方式发现这座城市的文化遗产。让我们把历史变成一次有趣的体验。',
        pl: 'Walencja zasługuje na to, żeby ją smakować. Fotografujcie, odpoczywajcie, odkrywajcie polecane miejsce… Wasza przygoda się nie spieszy. Wy też nie. Zapraszamy do spacerowania jej ulicami, rozwiązywania zagadek i odkrywania jej dziedzictwa w przyjemny sposób. Sprawmy, żeby historia stała się zabawnym przeżyciem.',
        pt: 'Valência merece ser saboreada. Tire fotos, descanse, explore o local recomendado… Não há pressa. Passeie pelas ruas, desvende os enigmas e descubra o património da cidade ao seu ritmo. Façamos juntos da história uma experiência inesquecível.',
        ru: 'Валенсия заслуживает того, чтобы её смаковали. Фотографируйте, отдыхайте, исследуйте рекомендованное место… Ваше приключение не торопится. И вы тоже. Приглашаем вас прогуляться по её улицам, разгадать загадки и открыть её наследие увлекательным образом. Давайте сделаем историю интересным опытом.',
        uk: 'Валенсія заслуговує на те, щоб нею насолоджуватися. Фотографуйте, відпочивайте, досліджуйте рекомендоване місце… Ваша пригода не поспішає. І ви теж. Запрошуємо вас прогулятися її вулицями, розгадати загадки та відкрити її спадщину в приємний спосіб. Зробімо з історії веселий досвід.',
    },
    // 14 — Fuera de ruta / botón ubicación (b6)
    {
        es: '¿Se ha despistado? ¿Está lejos de la ruta predefinida? No se preocupe, este botón se activará automáticamente para mostrarle cómo volver a su aventura, simplemente púlselo cuando se active.',
        en: 'Lost your way? Wandered too far from the planned route? Don\'t worry — this button will activate automatically to show you how to get back on track. Just tap it when it lights up.',
        fr: 'Vous vous êtes égaré ? Trop loin de l\'itinéraire prévu ? Pas d\'inquiétude — ce bouton s\'activera automatiquement pour vous montrer comment rejoindre votre aventure. Il vous suffit d\'appuyer dessus quand il s\'allume.',
        it: 'Vi siete persi? Troppo lontani dall\'itinerario previsto? Niente paura — questo pulsante si attiverà automaticamente per mostrarvi come tornare all\'avventura. Premetelo quando si accende.',
        nl: 'De weg kwijt? Te ver afgedwaald van de geplande route? Geen zorgen — deze knop activeert zich automatisch om u te laten zien hoe u terug kunt keren naar uw avontuur. Druk er gewoon op zodra hij oplicht.',
        ja: '道に迷いましたか？予定ルートから遠く離れてしまいましたか？ご心配なく――このボタンが自動的に有効になり、冒険に戻る道をご案内します。点灯したらタップするだけです。',
        de: 'Haben Sie sich verirrt? Zu weit von der vorgesehenen Route entfernt? Kein Problem — dieser Button aktiviert sich automatisch und zeigt Ihnen, wie Sie zu Ihrem Abenteuer zurückfinden. Drücken Sie ihn, wenn er aufleuchtet.',
        zh: '迷路了？走得离预定路线太远了？别担心——这个按钮会自动启动，指引您回到冒险旅程。当它亮起时，轻触一下即可。',
        pl: 'Zgubiliście się? Odeszliście za daleko od zaplanowanej trasy? Spokojnie — ten przycisk aktywuje się automatycznie, żeby pokazać wam, jak wrócić do przygody. Wystarczy go nacisnąć, gdy się włączy.',
        pt: 'Perdeu-se? Ficou longe demais da rota planeada? Não se preocupe — este botão ativar-se-á automaticamente para mostrar-lhe como regressar à sua aventura. Basta premi-lo quando acender.',
        ru: 'Заблудились? Отошли слишком далеко от маршрута? Не беспокойтесь — эта кнопка автоматически активируется и покажет вам, как вернуться к приключению. Просто нажмите её, когда она загорится.',
        uk: 'Загубилися? Відійшли занадто далеко від маршруту? Не хвилюйтеся — ця кнопка автоматично активується і покаже вам, як повернутися до пригоди. Просто натисніть її, коли вона засвітиться.',
    },
    // 15 — Caballero regresa caminando (escena visual, sin bocadillo)
    null,
    // 16 — GPS error / caballero durmiendo / descanso largo
    {
        es: 'Las grandes aventuras también necesitan una merecida pausa. Si necesita descansar y continuar más tarde, este botón se activará automáticamente para mostrarle cómo volver a su aventura al punto exacto donde lo dejó, simplemente púlselo cuando sienta que es el momento adecuado.',
        en: 'Even the greatest adventures deserve a well-earned rest. If you need to take a break and come back later, this button will activate automatically to show you how to return right where you left off. Tap it whenever you feel ready.',
        fr: 'Même les plus grandes aventures méritent une bonne pause. Si vous avez besoin de vous reposer et de reprendre plus tard, ce bouton s\'activera automatiquement pour vous montrer comment retrouver votre aventure exactement là où vous l\'avez laissée. Appuyez dessus quand vous vous sentirez prêt.',
        it: 'Anche le grandi avventure meritano una pausa ben guadagnata. Se avete bisogno di riposarvi e di riprendere in un secondo momento, questo pulsante si attiverà automaticamente per mostrarvi come tornare all\'avventura esattamente dove l\'avete lasciata. Premetelo quando vi sentite pronti.',
        nl: 'Zelfs de grootste avonturen verdienen een welverdiende pauze. Als u wilt rusten en later verder wilt gaan, activeert deze knop zich automatisch om u te laten zien hoe u uw avontuur hervat precies waar u was gebleven. Druk er op wanneer het u uitkomt.',
        ja: 'どんな大冒険にも、充分な休憩が必要です。休んで後で再開したいときは、このボタンが自動的に有効になり、やめたその地点から戻る方法をご案内します。準備ができたときにタップしてください。',
        de: 'Selbst die größten Abenteuer brauchen eine wohlverdiente Pause. Wenn Sie sich ausruhen und später weitermachen möchten, aktiviert sich dieser Button automatisch und zeigt Ihnen, wie Sie genau dort weitermachen können, wo Sie aufgehört haben. Drücken Sie ihn, wenn Sie bereit sind.',
        zh: '再伟大的冒险也需要一次应得的休息。如果您需要暂停并稍后继续，此按钮将自动启动，为您显示如何从离开的确切位置返回冒险旅程。当您准备好时，轻触它即可。',
        pl: 'Nawet największe przygody potrzebują zasłużonego odpoczynku. Jeśli chcecie się zatrzymać i wrócić później, ten przycisk aktywuje się automatycznie, żeby pokazać wam, jak wrócić do przygody dokładnie w miejscu, gdzie skończyliście. Naciśnijcie go, gdy poczujecie się gotowi.',
        pt: 'Até as maiores aventuras precisam de uma pausa bem merecida. Se precisar de descansar e regressar mais tarde, este botão ativar-se-á automaticamente para mostrar-lhe como voltar à sua aventura exatamente onde a deixou. Prima-o quando sentir que está preparado.',
        ru: 'Даже самые великие приключения нуждаются в заслуженном отдыхе. Если вам нужно остановиться и вернуться позже, эта кнопка автоматически активируется и покажет, как вернуться к приключению именно там, где вы остановились. Нажмите её, когда будете готовы.',
        uk: 'Навіть найбільші пригоди потребують заслуженого відпочинку. Якщо вам потрібно зупинитися і повернутися пізніше, ця кнопка автоматично активується і покаже, як повернутися до пригоди саме там, де ви зупинилися. Натисніть її, коли будете готові.',
    },
    // 17 — Botón temporizador
    {
        es: 'Cada aventura tiene un tiempo estimado de finalización. Aquí puede controlar el tiempo transcurrido en todo momento.',
        en: 'Every adventure has an estimated finish time. Check how much time has passed here whenever you like.',
        fr: 'Chaque aventure a une durée estimée. Consultez ici le temps écoulé quand vous le souhaitez.',
        it: 'Ogni avventura ha una durata stimata. Controllate qui il tempo trascorso ogni volta che volete.',
        nl: 'Elk avontuur heeft een geschatte duur. Controleer hier hoeveel tijd er verstreken is, wanneer u maar wilt.',
        ja: '各冒険には推定完了時間があります。ここでいつでも経過時間を確認できます。',
        de: 'Jedes Abenteuer hat eine geschätzte Dauer. Sehen Sie hier jederzeit nach, wie viel Zeit bereits vergangen ist.',
        zh: '每项冒险都有预计完成时间。您可以随时在这里查看已用时间。',
        pl: 'Każda przygoda ma szacowany czas ukończenia. Tutaj możecie sprawdzić upłynięty czas, kiedy tylko chcecie.',
        pt: 'Cada aventura tem uma duração estimada. Consulte aqui o tempo decorrido sempre que quiser.',
        ru: 'Каждое приключение имеет расчётное время завершения. Здесь вы можете проверить прошедшее время в любой момент.',
        uk: 'Кожна пригода має розрахунковий час завершення. Тут ви можете перевірити минулий час будь-коли.',
    },
    // 18 — Asistente / preguntas frecuentes
    {
        es: '¿Alguna pregunta? Tenemos respuestas. Pulse aquí para acceder a nuestro listado de preguntas frecuentes.',
        en: 'Got a question? We have answers. Tap here to browse our frequently asked questions.',
        fr: 'Des questions ? Nous avons des réponses. Appuyez ici pour consulter notre liste de questions fréquentes.',
        it: 'Avete domande? Abbiamo le risposte. Premete qui per consultare le nostre domande frequenti.',
        nl: 'Vragen? Wij hebben antwoorden. Druk hier om onze veelgestelde vragen te raadplegen.',
        ja: 'ご質問はありますか？回答があります。こちらをタップして、よくある質問の一覧にアクセスしてください。',
        de: 'Fragen? Wir haben Antworten. Drücken Sie hier, um unsere häufig gestellten Fragen aufzurufen.',
        zh: '有任何问题？我们有答案。点击此处访问我们的常见问题列表。',
        pl: 'Macie pytania? Mamy odpowiedzi. Naciśnijcie tutaj, aby uzyskać dostęp do naszej listy często zadawanych pytań.',
        pt: 'Alguma dúvida? Temos respostas. Prima aqui para consultar as nossas perguntas frequentes.',
        ru: 'Есть вопросы? У нас есть ответы. Нажмите здесь для доступа к списку часто задаваемых вопросов.',
        uk: 'Є запитання? Ми маємо відповіді. Натисніть тут, щоб отримати доступ до списку поширених запитань.',
    },
    // 19 — Pantalla final
    {
        es: 'Todo preparado. Valencia le espera con sus monumentos, sus secretos y sus retos. ¡Que comience la aventura!',
        en: 'All set. Valencia is waiting — with its monuments, its secrets and its challenges. Let the adventure begin!',
        fr: 'Tout est prêt. Valence vous attend — ses monuments, ses secrets, ses défis. Que l\'aventure commence !',
        it: 'Tutto pronto. Valencia vi aspetta — con i suoi monumenti, i suoi segreti e le sue sfide. Che l\'avventura abbia inizio!',
        nl: 'Alles klaar. Valencia wacht op u — met zijn monumenten, zijn geheimen en zijn uitdagingen. Laat het avontuur beginnen!',
        ja: '準備完了です。バレンシアがその名所、秘密、そして挑戦とともにあなたを待っています。冒険を始めましょう！',
        de: 'Alles bereit. Valencia wartet auf Sie — mit seinen Denkmälern, Geheimnissen und Herausforderungen. Das Abenteuer beginnt!',
        zh: '一切就绪。瓦伦西亚以其名胜古迹、秘密与挑战等待着您。让冒险开始吧！',
        pl: 'Wszystko gotowe. Walencja czeka na was ze swoimi zabytkami, tajemnicami i wyzwaniami. Niech przygoda się rozpocznie!',
        pt: 'Tudo pronto. Valência aguarda-o — com os seus monumentos, os seus segredos e os seus desafios. Que a aventura comece!',
        ru: 'Всё готово. Валенсия ждёт вас со своими памятниками, секретами и испытаниями. Пусть приключение начнётся!',
        uk: 'Все готово. Валенсія чекає на вас зі своїми пам\'ятками, таємницями та випробуваннями. Нехай пригода розпочнеться!',
    },
];

export const TRADUCCIONES_SW_UPDATE = {
    es: { label: '🔄 Nueva versión disponible', boton: 'Actualizar' },
    en: { label: '🔄 New version available',    boton: 'Update' },
    fr: { label: '🔄 Nouvelle version disponible', boton: 'Mettre à jour' },
    it: { label: '🔄 Nuova versione disponibile',   boton: 'Aggiorna' },
    nl: { label: '🔄 Nieuwe versie beschikbaar',    boton: 'Bijwerken' },
    de: { label: '🔄 Neue Version verfügbar',       boton: 'Aktualisieren' },
    ja: { label: '🔄 新しいバージョンが利用可能です', boton: '更新' },
    zh: { label: '🔄 新版本可用',                   boton: '更新' },
    pl: { label: '🔄 Nowa wersja dostępna',         boton: 'Zaktualizuj' },
    pt: { label: '🔄 Nova versão disponível',       boton: 'Atualizar' },
    ru: { label: '🔄 Доступна новая версия',        boton: 'Обновить' },
    uk: { label: '🔄 Доступна нова версія',         boton: 'Оновити' },
};

export const PLACEHOLDER_RESPUESTA_TEXTO = {
    es: 'Escriba su respuesta aquí...',
    en: 'Write your answer here...',
    fr: 'Écrivez votre réponse ici...',
    it: 'Scrivi qui la tua risposta...',
    nl: 'Schrijf hier je antwoord...',
    de: 'Schreiben Sie hier Ihre Antwort...',
    ja: 'ここに回答を入力してください...',
    zh: '请在此输入您的答案...',
    pl: 'Wpisz tutaj swoją odpowiedź...',
    pt: 'Escreva a sua resposta aqui...',
    ru: 'Напишите ваш ответ здесь...',
    uk: 'Напишіть свою відповідь тут...'
};
