/**
 * traducciones-ui.js - Textos de interfaz traducidos a los 12 idiomas
 *
 * Centraliza bloques de traducción que antes estaban duplicados/dispersos
 * como constantes inline en codigo-padre.html, retos-hijo4.html,
 * chat-hijo6.html, En-busca-del-tesoro.html y video-intro.html.
 */

export const TRADUCCIONES_REANUDACION = {
    es: {
        titulo: '¡Aventura en curso!',
        info: 'Tienes una aventura activa:',
        idioma: 'Idioma',
        progreso: 'Progreso',
        parada: 'parada',
        de: 'de',
        continuar: 'Continuar mi aventura',
        elegirOtra: 'Elegir otra aventura',
        autoContinuar: 'Continuando automáticamente en',
        segundos: 's',
        advertenciaTitulo: '⚠️ Atención',
        advertenciaTexto1: 'Perderás todo el progreso de tu aventura actual:',
        advertenciaTexto2: 'Además, necesitarás adquirir una nueva aventura.',
        volver: 'Volver a mi aventura',
        confirmarOtra: 'Sí, elegir otra aventura'
    },
    en: {
        titulo: 'Adventure in progress!',
        info: 'You have an active adventure:',
        idioma: 'Language',
        progreso: 'Progress',
        parada: 'stop',
        de: 'of',
        continuar: 'Continue my adventure',
        elegirOtra: 'Choose another adventure',
        autoContinuar: 'Auto-continuing in',
        segundos: 's',
        advertenciaTitulo: '⚠️ Warning',
        advertenciaTexto1: 'You will lose all progress in your current adventure:',
        advertenciaTexto2: 'You will also need to purchase a new adventure.',
        volver: 'Return to my adventure',
        confirmarOtra: 'Yes, choose another adventure'
    },
    fr: {
        titulo: 'Aventure en cours !',
        info: 'Vous avez une aventure active :',
        idioma: 'Langue',
        progreso: 'Progression',
        parada: 'arrêt',
        de: 'sur',
        continuar: 'Continuer mon aventure',
        elegirOtra: 'Choisir une autre aventure',
        autoContinuar: 'Continuation automatique dans',
        segundos: 's',
        advertenciaTitulo: '⚠️ Attention',
        advertenciaTexto1: 'Vous perdrez toute la progression de votre aventure actuelle :',
        advertenciaTexto2: 'De plus, vous devrez acheter une nouvelle aventure.',
        volver: 'Retourner à mon aventure',
        confirmarOtra: 'Oui, choisir une autre aventure'
    },
    it: {
        titulo: 'Avventura in corso!',
        info: 'Hai un\'avventura attiva:',
        idioma: 'Lingua',
        progreso: 'Progresso',
        parada: 'tappa',
        de: 'di',
        continuar: 'Continua la mia avventura',
        elegirOtra: 'Scegli un\'altra avventura',
        autoContinuar: 'Continuazione automatica tra',
        segundos: 's',
        advertenciaTitulo: '⚠️ Attenzione',
        advertenciaTexto1: 'Perderai tutto il progresso della tua avventura attuale:',
        advertenciaTexto2: 'Inoltre, dovrai acquistare una nuova avventura.',
        volver: 'Torna alla mia avventura',
        confirmarOtra: 'Sì, scegli un\'altra avventura'
    },
    nl: {
        titulo: 'Avontuur bezig!',
        info: 'Je hebt een actief avontuur:',
        idioma: 'Taal',
        progreso: 'Voortgang',
        parada: 'halte',
        de: 'van',
        continuar: 'Mijn avontuur voortzetten',
        elegirOtra: 'Kies een ander avontuur',
        autoContinuar: 'Automatisch verder over',
        segundos: 's',
        advertenciaTitulo: '⚠️ Let op',
        advertenciaTexto1: 'Je verliest alle voortgang van je huidige avontuur:',
        advertenciaTexto2: 'Bovendien moet je een nieuw avontuur aanschaffen.',
        volver: 'Terug naar mijn avontuur',
        confirmarOtra: 'Ja, kies een ander avontuur'
    },
    ja: {
        titulo: '冒険が進行中です！',
        info: 'アクティブな冒険があります：',
        idioma: '言語',
        progreso: '進捗',
        parada: 'ストップ',
        de: '/',
        continuar: '冒険を続ける',
        elegirOtra: '別の冒険を選ぶ',
        autoContinuar: '自動的に続行します',
        segundos: '秒',
        advertenciaTitulo: '⚠️ 注意',
        advertenciaTexto1: '現在の冒険のすべての進捗を失います：',
        advertenciaTexto2: 'また、新しい冒険を購入する必要があります。',
        volver: '冒険に戻る',
        confirmarOtra: 'はい、別の冒険を選びます'
    },
    ru: {
        titulo: 'Приключение в процессе!',
        info: 'У вас есть активное приключение:',
        idioma: 'Язык',
        progreso: 'Прогресс',
        parada: 'остановка',
        de: 'из',
        continuar: 'Продолжить приключение',
        elegirOtra: 'Выбрать другое приключение',
        autoContinuar: 'Автоматическое продолжение через',
        segundos: 'с',
        advertenciaTitulo: '⚠️ Внимание',
        advertenciaTexto1: 'Вы потеряете весь прогресс текущего приключения:',
        advertenciaTexto2: 'Кроме того, вам нужно будет приобрести новое приключение.',
        volver: 'Вернуться к приключению',
        confirmarOtra: 'Да, выбрать другое приключение'
    },
    zh: {
        titulo: '冒险进行中！',
        info: '您有一个进行中的冒险：',
        idioma: '语言',
        progreso: '进度',
        parada: '站点',
        de: '/',
        continuar: '继续我的冒险',
        elegirOtra: '选择其他冒险',
        autoContinuar: '自动继续，倒计时',
        segundos: '秒',
        advertenciaTitulo: '⚠️ 注意',
        advertenciaTexto1: '您将失去当前冒险的所有进度：',
        advertenciaTexto2: '此外，您还需要购买新的冒险。',
        volver: '返回我的冒险',
        confirmarOtra: '是，选择其他冒险'
    },
    pl: {
        titulo: 'Przygoda w toku!',
        info: 'Masz aktywną przygodę:',
        idioma: 'Język',
        progreso: 'Postęp',
        parada: 'przystanek',
        de: 'z',
        continuar: 'Kontynuuj moją przygodę',
        elegirOtra: 'Wybierz inną przygodę',
        autoContinuar: 'Automatyczne kontynuowanie za',
        segundos: 's',
        advertenciaTitulo: '⚠️ Uwaga',
        advertenciaTexto1: 'Stracisz cały postęp swojej obecnej przygody:',
        advertenciaTexto2: 'Ponadto będziesz musiał zakupić nową przygodę.',
        volver: 'Wróć do mojej przygody',
        confirmarOtra: 'Tak, wybierz inną przygodę'
    },
    uk: {
        titulo: 'Пригода в процесі!',
        info: 'У вас є активна пригода:',
        idioma: 'Мова',
        progreso: 'Прогрес',
        parada: 'зупинка',
        de: 'з',
        continuar: 'Продовжити пригоду',
        elegirOtra: 'Вибрати іншу пригоду',
        autoContinuar: 'Автоматичне продовження через',
        segundos: 'с',
        advertenciaTitulo: '⚠️ Увага',
        advertenciaTexto1: 'Ви втратите весь прогрес поточної пригоди:',
        advertenciaTexto2: 'Крім того, вам потрібно буде придбати нову пригоду.',
        volver: 'Повернутися до пригоди',
        confirmarOtra: 'Так, вибрати іншу пригоду'
    },
    pt: {
        titulo: 'Aventura em curso!',
        info: 'Tem uma aventura ativa:',
        idioma: 'Idioma',
        progreso: 'Progresso',
        parada: 'paragem',
        de: 'de',
        continuar: 'Continuar a minha aventura',
        elegirOtra: 'Escolher outra aventura',
        autoContinuar: 'Continuação automática em',
        segundos: 's',
        advertenciaTitulo: '⚠️ Atenção',
        advertenciaTexto1: 'Perderá todo o progresso da sua aventura atual:',
        advertenciaTexto2: 'Além disso, precisará adquirir uma nova aventura.',
        volver: 'Voltar à minha aventura',
        confirmarOtra: 'Sim, escolher outra aventura'
    },
    de: {
        titulo: 'Abenteuer läuft!',
        info: 'Sie haben ein aktives Abenteuer:',
        idioma: 'Sprache',
        progreso: 'Fortschritt',
        parada: 'Halt',
        de: 'von',
        continuar: 'Mein Abenteuer fortsetzen',
        elegirOtra: 'Ein anderes Abenteuer wählen',
        autoContinuar: 'Automatische Fortsetzung in',
        segundos: 's',
        advertenciaTitulo: '⚠️ Achtung',
        advertenciaTexto1: 'Sie verlieren den gesamten Fortschritt Ihres aktuellen Abenteuers:',
        advertenciaTexto2: 'Außerdem müssen Sie ein neues Abenteuer erwerben.',
        volver: 'Zurück zu meinem Abenteuer',
        confirmarOtra: 'Ja, ein anderes Abenteuer wählen'
    }
};

export const TRADUCCIONES_FINALIZACION = {
    es: { titulo: '¡Felicidades!', completado: 'Has completado', pregunta: '¿Qué deseas hacer ahora?', btn_otra: 'Hacer otra aventura', btn_terminar: 'Terminar esta experiencia' },
    en: { titulo: 'Congratulations!', completado: 'You have completed', pregunta: 'What would you like to do now?', btn_otra: 'Start another adventure', btn_terminar: 'End this experience' },
    fr: { titulo: 'Félicitations !', completado: 'Vous avez terminé', pregunta: 'Que souhaitez-vous faire maintenant ?', btn_otra: 'Faire une autre aventure', btn_terminar: 'Terminer cette expérience' },
    it: { titulo: 'Congratulazioni!', completado: 'Hai completato', pregunta: 'Cosa desideri fare adesso?', btn_otra: "Fare un'altra avventura", btn_terminar: 'Terminare questa esperienza' },
    nl: { titulo: 'Gefeliciteerd!', completado: 'Je hebt voltooid', pregunta: 'Wat wil je nu doen?', btn_otra: 'Een ander avontuur beginnen', btn_terminar: 'Deze ervaring beëindigen' },
    de: { titulo: 'Herzlichen Glückwunsch!', completado: 'Sie haben abgeschlossen', pregunta: 'Was möchten Sie jetzt tun?', btn_otra: 'Ein anderes Abenteuer beginnen', btn_terminar: 'Dieses Erlebnis beenden' },
    ja: { titulo: 'おめでとうございます！', completado: '完了しました', pregunta: '次に何をしますか？', btn_otra: '別のアドベンチャーを始める', btn_terminar: 'この体験を終了する' },
    zh: { titulo: '恭喜！', completado: '您已完成', pregunta: '您现在想做什么？', btn_otra: '开始另一个冒险', btn_terminar: '结束此体验' },
    pl: { titulo: 'Gratulacje!', completado: 'Ukończyłeś', pregunta: 'Co chcesz teraz zrobić?', btn_otra: 'Rozpocząć inną przygodę', btn_terminar: 'Zakończyć to doświadczenie' },
    pt: { titulo: 'Parabéns!', completado: 'Você completou', pregunta: 'O que deseja fazer agora?', btn_otra: 'Fazer outra aventura', btn_terminar: 'Terminar esta experiência' },
    ru: { titulo: 'Поздравляем!', completado: 'Вы завершили', pregunta: 'Что вы хотите сделать сейчас?', btn_otra: 'Начать другое приключение', btn_terminar: 'Завершить этот опыт' },
    uk: { titulo: 'Вітаємо!', completado: 'Ви завершили', pregunta: 'Що ви хочете зробити тепер?', btn_otra: 'Розпочати іншу пригоду', btn_terminar: 'Завершити цей досвід' }
};

export const TRADUCCIONES_TIEMPO_AGOTADO = {
    es: { titulo: '¡Tiempo agotado!', cuerpo: 'El tiempo máximo para completar esta aventura ha terminado. Gracias por participar.' },
    en: { titulo: "Time's up!", cuerpo: 'The maximum time to complete this adventure has ended. Thank you for participating.' },
    fr: { titulo: 'Temps écoulé !', cuerpo: 'Le temps maximum pour terminer cette aventure est terminé. Merci d\'avoir participé.' },
    it: { titulo: 'Tempo scaduto!', cuerpo: 'Il tempo massimo per completare questa avventura è terminato. Grazie per aver partecipato.' },
    nl: { titulo: 'Tijd verstreken!', cuerpo: 'De maximale tijd om dit avontuur te voltooien is verstreken. Bedankt voor je deelname.' },
    de: { titulo: 'Zeit abgelaufen!', cuerpo: 'Die maximale Zeit für dieses Abenteuer ist abgelaufen. Danke fürs Mitmachen.' },
    ja: { titulo: '時間切れです！', cuerpo: 'この冒険を完了するための制限時間が終了しました。ご参加ありがとうございました。' },
    zh: { titulo: '时间到！', cuerpo: '完成此冒险的最长时间已结束。感谢您的参与。' },
    pl: { titulo: 'Czas minął!', cuerpo: 'Maksymalny czas na ukończenie tej przygody dobiegł końca. Dziękujemy za udział.' },
    pt: { titulo: 'Tempo esgotado!', cuerpo: 'O tempo máximo para completar esta aventura terminou. Obrigado por participar.' },
    ru: { titulo: 'Время истекло!', cuerpo: 'Максимальное время для прохождения этого приключения истекло. Спасибо за участие.' },
    uk: { titulo: 'Час вийшов!', cuerpo: 'Максимальний час для проходження цієї пригоди закінчився. Дякуємо за участь.' }
};

export const TRADUCCIONES_DESPEDIDA = {
    es: '¡Hasta pronto! Gracias por explorar Valencia con nosotros.',
    en: 'Goodbye! Thank you for exploring Valencia with us.',
    fr: 'Au revoir ! Merci d\'avoir exploré Valence avec nous.',
    it: 'Arrivederci! Grazie per aver esplorato Valencia con noi.',
    nl: 'Tot ziens! Bedankt voor het verkennen van Valencia met ons.',
    de: 'Auf Wiedersehen! Danke, dass Sie Valencia mit uns erkundet haben.',
    ja: 'またね！バレンシアを一緒に探検してくれてありがとう。',
    zh: '再见！感谢您与我们一起探索瓦伦西亚。',
    pl: 'Do widzenia! Dziękujemy za eksplorację Walencji z nami.',
    pt: 'Até logo! Obrigado por explorar Valência connosco.',
    ru: 'До свидания! Спасибо, что исследовали Валенсию вместе с нами.',
    uk: 'До побачення! Дякуємо, що досліджували Валенсію разом з нами.'
};

export const MSG_RETOS_COMPLETOS = {
    es: '¡Has completado todos los retos!',
    en: "You've completed all the challenges!",
    fr: 'Vous avez terminé tous les défis !',
    it: 'Hai completato tutte le sfide!',
    nl: 'Je hebt alle uitdagingen voltooid!',
    ja: 'すべてのチャレンジをクリアしました！',
    de: 'Du hast alle Aufgaben abgeschlossen!',
    zh: '你已完成所有挑战！',
    pl: 'Ukończono wszystkie wyzwania!',
    pt: 'Completaste todos os desafios!',
    ru: 'Вы завершили все задания!',
    uk: 'Ви завершили всі завдання!'
};

export const TITULOS_CHAT = {
    es: 'Soporte', en: 'Support', fr: 'Assistance',
    it: 'Supporto', nl: 'Ondersteuning', ja: 'サポート',
    de: 'Hilfe', zh: '帮助', pl: 'Pomoc',
    pt: 'Suporte', ru: 'Помощь', uk: 'Допомога'
};

// Un objeto por pantalla de video-intro.html, en el mismo orden que run().
// El índice 15 es null (escena visual sin bocadillo).
export const JAIME_SCENES = [
    // 0 — Logos / bienvenida
    {
        es: '¡Saludos! ¡Le damos la bienvenida a esta nueva aventura! Somos Jaime I y María de Castilla. Permítanos acompañarle durante los primeros pasos de su búsqueda del tesoro.',
        en: 'Greetings! Welcome to this new adventure! We are James I and María of Castile. Allow us to accompany you during the first steps of your treasure hunt.',
        fr: 'Salutations ! Bienvenue dans cette nouvelle aventure ! Nous sommes Jacques Ier et Marie de Castille. Permettez-nous de vous accompagner lors des premiers pas de votre chasse au trésor.',
        it: 'Saluti! Benvenuti in questa nuova avventura! Siamo Giacomo I e María di Castiglia. Permetteteci di accompagnarvi durante i primi passi della vostra caccia al tesoro.',
        nl: 'Groeten! Welkom bij dit nieuwe avontuur! Wij zijn Jacobus I en María van Castilië. Sta ons toe u te begeleiden tijdens de eerste stappen van uw schattenjacht.',
        ja: 'ご挨拶申し上げます！この新しい冒険へようこそ！私たちはハイメ1世とカスティーリャのマリアです。宝探しの最初の一歩をご一緒させてください。',
        de: 'Seid gegrüßt! Willkommen bei diesem neuen Abenteuer! Wir sind Jakob I. und María von Kastilien. Gestatten Sie uns, Sie bei den ersten Schritten Ihrer Schatzsuche zu begleiten.',
        zh: '您好！欢迎来到这次新的冒险！我们是哈梅一世和卡斯蒂利亚的玛丽亚。请允许我们陪伴您踏上寻宝之旅的第一步。',
        pl: 'Pozdrowienia! Witamy w tej nowej przygodzie! Jesteśmy Jakubem I i Marią z Kastylii. Pozwólcie, że towarzyszymy wam podczas pierwszych kroków poszukiwania skarbu.',
        pt: 'Saudações! Bem-vindos a esta nova aventura! Somos Jaime I e Maria de Castela. Permitam-nos acompanhá-los durante os primeiros passos da vossa caça ao tesouro.',
        ru: 'Приветствуем! Добро пожаловать в это новое приключение! Мы — Хайме I и Мария Кастильская. Позвольте нам сопровождать вас в первых шагах вашей охоты за сокровищами.',
        uk: 'Вітаємо! Ласкаво просимо до цієї нової пригоди! Ми — Хайме I та Марія Кастильська. Дозвольте нам супроводжувати вас під час перших кроків пошуку скарбу.',
    },
    // 1 — GPS / internet (reubicada como segunda pantalla)
    {
        es: 'Una pequeña cosa antes de partir: active el GPS, asegúrese de tener conexión a internet y conceda los permisos que le solicite su dispositivo.',
        en: 'One small thing before you set off: enable GPS, make sure you have an internet connection and grant the permissions your device requests.',
        fr: 'Une petite chose avant de partir : activez le GPS, assurez-vous d\'avoir une connexion internet et accordez les autorisations demandées par votre appareil.',
        it: 'Una piccola cosa prima di partire: attivate il GPS, assicuratevi di avere una connessione internet e concedete i permessi richiesti dal vostro dispositivo.',
        nl: 'Eén ding voor het vertrek: schakel GPS in, zorg voor een internetverbinding en verleen de toestemmingen die uw apparaat vraagt.',
        ja: '出発前にひとつ：GPSを有効にし、インターネット接続を確認し、デバイスが要求する権限を許可してください。',
        de: 'Eine kurze Sache vor dem Aufbruch: Aktivieren Sie das GPS, stellen Sie sicher, dass Sie eine Internetverbindung haben, und gewähren Sie die Berechtigungen, die Ihr Gerät anfordert.',
        zh: '出发前的小事：请开启GPS，确保有网络连接，并授予设备所需的权限。',
        pl: 'Jedna mała rzecz przed wyruszeniem: włączcie GPS, upewnijcie się, że macie połączenie z internetem i przyznajcie uprawnienia, których wymaga urządzenie.',
        pt: 'Uma pequena coisa antes de partir: ative o GPS, certifique-se de ter ligação à internet e conceda as permissões que o seu dispositivo solicitar.',
        ru: 'Одна небольшая вещь перед отправлением: включите GPS, убедитесь в наличии интернет-соединения и предоставьте разрешения, которые запрашивает ваше устройство.',
        uk: 'Одна невелика річ перед відправленням: увімкніть GPS, переконайтеся, що є підключення до інтернету, та надайте дозволи, які запитує ваш пристрій.',
    },
    // 2 — Selección de aventura
    {
        es: 'Tenemos el gusto de poder ofrecerle varias aventuras. Cada una tiene su distancia y duración determinada y también un tipo de transporte recomendado. Elija la que más le guste o se adapte a sus necesidades.',
        en: 'We are delighted to offer you several adventures. Each one has a set distance and duration, as well as a recommended mode of transport. Choose the one you like most or that best suits your needs.',
        fr: 'Nous avons le plaisir de vous proposer plusieurs aventures. Chacune a une distance et une durée déterminées ainsi qu\'un mode de transport recommandé. Choisissez celle qui vous plaît le plus ou qui correspond le mieux à vos besoins.',
        it: 'Abbiamo il piacere di offrirvi diverse avventure. Ognuna ha una distanza e una durata determinate, nonché un tipo di trasporto consigliato. Scegliete quella che preferite o che meglio si adatta alle vostre esigenze.',
        nl: 'Het is ons een genoegen u verschillende avonturen aan te bieden. Elk heeft een vaste afstand en duur, evenals een aanbevolen vervoersmiddel. Kies het avontuur dat u het meest aanspreekt of het beste bij uw behoeften past.',
        ja: 'いくつかの冒険をご用意しております。それぞれ決まった距離と所要時間、おすすめの交通手段があります。お好みや、ご自身のニーズに合ったものをお選びください。',
        de: 'Wir freuen uns, Ihnen mehrere Abenteuer anbieten zu können. Jedes hat eine festgelegte Distanz und Dauer sowie ein empfohlenes Verkehrsmittel. Wählen Sie das, was Ihnen am besten gefällt oder Ihren Bedürfnissen am besten entspricht.',
        zh: '我们荣幸地为您提供多种冒险选择。每项冒险都有确定的距离和时长，以及推荐的交通方式。请选择您最喜欢或最适合您需求的一项。',
        pl: 'Mamy przyjemność zaoferować wam kilka przygód. Każda ma określoną odległość i czas trwania, a także zalecany środek transportu. Wybierzcie tę, która najbardziej wam odpowiada lub najlepiej pasuje do waszych potrzeb.',
        pt: 'Temos o prazer de lhe oferecer várias aventuras. Cada uma tem uma distância e duração determinadas, bem como um tipo de transporte recomendado. Escolha a que mais lhe agradar ou que melhor se adapte às suas necessidades.',
        ru: 'Мы рады предложить вам несколько приключений. Каждое имеет заданную дистанцию и продолжительность, а также рекомендуемый вид транспорта. Выберите то, что вам больше всего нравится или лучше всего соответствует вашим потребностям.',
        uk: 'Ми раді запропонувати вам кілька пригод. Кожна має визначену відстань і тривалість, а також рекомендований вид транспорту. Оберіть ту, яка вам найбільше подобається або найкраще відповідає вашим потребам.',
    },
    // 3 — Mapa vintage de la aventura
    {
        es: 'Un vistazo a su aventura al completo: paradas numeradas, ruta trazada. La ciudad entera, esperándole.',
        en: 'A glimpse of your full adventure: numbered stops, mapped route. The whole city, waiting for you.',
        fr: 'Un aperçu complet de votre aventure : arrêts numérotés, itinéraire tracé. La ville entière vous attend.',
        it: 'Uno sguardo alla vostra avventura completa: tappe numerate, percorso tracciato. L\'intera città vi aspetta.',
        nl: 'Een blik op uw volledige avontuur: genummerde haltes, uitgestippelde route. De hele stad wacht op u.',
        ja: 'あなたの冒険を一望できます：番号付きの停車地、描かれたルート。街全体があなたを待っています。',
        de: 'Ein Blick auf Ihr gesamtes Abenteuer: nummerierte Stopps, eingezeichnete Route. Die ganze Stadt wartet auf Sie.',
        zh: '纵览您的完整冒险：编号停靠点、绘制路线。整座城市，静候您的到来。',
        pl: 'Rzut oka na całą przygodę: ponumerowane przystanki, wytyczona trasa. Całe miasto czeka na was.',
        pt: 'Uma visão geral da sua aventura completa: paragens numeradas, rota traçada. A cidade inteira à sua espera.',
        ru: 'Взгляд на всё ваше приключение: пронумерованные остановки, проложенный маршрут. Весь город ждёт вас.',
        uk: 'Погляд на всю вашу пригоду: пронумеровані зупинки, прокладений маршрут. Усе місто чекає на вас.',
    },
    // 4 — Grid de todos los botones
    {
        es: 'Estos son los botones que harán posible su aventura. Los iremos descubriendo uno a uno.',
        en: 'These are the buttons that will make your adventure possible. We will discover them one by one.',
        fr: 'Voici les boutons qui rendront votre aventure possible. Nous les découvrirons un par un.',
        it: 'Questi sono i pulsanti che renderanno possibile la vostra avventura. Li scopriremo uno per uno.',
        nl: 'Dit zijn de knoppen die uw avontuur mogelijk maken. We ontdekken ze één voor één.',
        ja: 'これらのボタンがあなたの冒険を可能にします。一つずつご確認いきましょう。',
        de: 'Das sind die Schaltflächen, die Ihr Abenteuer möglich machen. Wir werden sie eine nach der anderen entdecken.',
        zh: '这些按钮将使您的冒险成为可能。我们将逐一了解它们。',
        pl: 'To są przyciski, które umożliwią waszą przygodę. Będziemy je odkrywać jeden po drugim.',
        pt: 'Estes são os botões que tornarão a sua aventura possível. Vamo-los descobrir um a um.',
        ru: 'Это кнопки, которые сделают ваше приключение возможным. Мы будем открывать их одну за другой.',
        uk: 'Це кнопки, які зроблять вашу пригоду можливою. Ми відкриватимемо їх одну за одною.',
    },
    // 5 — Botón mapa digital completo (b1)
    {
        es: 'Este botón le mostrará el trazado completo de su aventura, así como los puntos relevantes a visitar.',
        en: 'This button will show you the complete route of your adventure, as well as the relevant points to visit.',
        fr: 'Ce bouton vous montrera le tracé complet de votre aventure, ainsi que les points pertinents à visiter.',
        it: 'Questo pulsante vi mostrerà il tracciato completo della vostra avventura, nonché i punti rilevanti da visitare.',
        nl: 'Deze knop toont u de volledige route van uw avontuur, evenals de relevante punten om te bezoeken.',
        ja: 'このボタンを押すと、冒険の完全なルートと訪問すべき重要なポイントが表示されます。',
        de: 'Diese Schaltfläche zeigt Ihnen den vollständigen Streckenverlauf Ihres Abenteuers sowie die relevanten Sehenswürdigkeiten.',
        zh: '此按钮将为您显示冒险的完整路线以及需要参观的相关地点。',
        pl: 'Ten przycisk pokaże wam pełny przebieg trasy waszej przygody, a także istotne punkty do odwiedzenia.',
        pt: 'Este botão mostrar-lhe-á o traçado completo da sua aventura, bem como os pontos relevantes a visitar.',
        ru: 'Эта кнопка покажет вам полный маршрут вашего приключения, а также важные точки для посещения.',
        uk: 'Ця кнопка покаже вам повний маршрут вашої пригоди, а також відповідні місця для відвідування.',
    },
    // 6 — Botón mapa vintage (b2)
    {
        es: 'Este botón le mostrará el mismo mapa, pero con alma de época. Un estilo vintage que le transportará siglos atrás. ¿cuál prefiere?',
        en: 'This button will show you the same map, but with a timeless soul. A vintage style that will take you centuries back. Which do you prefer?',
        fr: 'Ce bouton vous montrera la même carte, mais avec une âme d\'époque. Un style vintage qui vous transportera des siècles en arrière. Lequel préférez-vous ?',
        it: 'Questo pulsante vi mostrerà la stessa mappa, ma con un\'anima d\'epoca. Uno stile vintage che vi trasporterà indietro di secoli. Quale preferite?',
        nl: 'Deze knop toont u dezelfde kaart, maar met een tijdloze ziel. Een vintage stijl die u eeuwen terug in de tijd brengt. Welke verkiest u?',
        ja: 'このボタンを押すと同じ地図が表示されますが、時代の魂を宿しています。ヴィンテージスタイルが何世紀も前へとあなたを誘います。どちらがお好みですか？',
        de: 'Diese Schaltfläche zeigt Ihnen dieselbe Karte, aber mit einer zeitlosen Seele. Ein Vintage-Stil, der Sie Jahrhunderte zurückversetzt. Welchen bevorzugen Sie?',
        zh: '此按钮将为您显示同样的地图，却有着岁月的灵魂。复古风格将带您穿越数百年。您更喜欢哪一个？',
        pl: 'Ten przycisk pokaże wam tę samą mapę, ale z duszą epoki. Styl vintage, który przeniesie was o wieki wstecz. Który wolelibyście?',
        pt: 'Este botão mostrar-lhe-á o mesmo mapa, mas com alma de época. Um estilo vintage que o transportará séculos atrás. Qual prefere?',
        ru: 'Эта кнопка покажет вам ту же карту, но с душой эпохи. Винтажный стиль перенесёт вас на несколько веков назад. Что вы предпочитаете?',
        uk: 'Ця кнопка покаже вам ту саму карту, але з душею епохи. Вінтажний стиль перенесе вас на кілька століть назад. Що ви надаєте перевагу?',
    },
    // 7 — Botón avanzar (b-av)
    {
        es: 'De parada en parada irá descubriendo maravillosos tesoros que le ofrece la ciudad, la aventura avanza con usted. Este botón se activa o desactiva automáticamente, siempre al ritmo que necesite.',
        en: 'Stop by stop, you will discover the wonderful treasures the city has to offer, as the adventure moves with you. This button activates or deactivates automatically, always at the pace you need.',
        fr: 'Arrêt après arrêt, vous découvrirez de merveilleux trésors qu\'offre la ville, l\'aventure avance avec vous. Ce bouton s\'active ou se désactive automatiquement, toujours au rythme dont vous avez besoin.',
        it: 'Tappa dopo tappa scoprirete i meravigliosi tesori che la città ha da offrire, l\'avventura avanza con voi. Questo pulsante si attiva o si disattiva automaticamente, sempre al ritmo di cui avete bisogno.',
        nl: 'Halte na halte ontdekt u de prachtige schatten die de stad te bieden heeft, terwijl het avontuur met u meebeweegt. Deze knop activeert of deactiveert automatisch, altijd op het tempo dat u nodig heeft.',
        ja: '停車地から停車地へと、街が誇る素晴らしい宝を発見しながら、冒険はあなたと共に進みます。このボタンは自動的に有効または無効になり、常に必要なペースに合わせてくれます。',
        de: 'Stopp für Stopp werden Sie die wunderbaren Schätze entdecken, die die Stadt zu bieten hat, während das Abenteuer mit Ihnen voranschreitet. Diese Schaltfläche aktiviert oder deaktiviert sich automatisch, immer in dem Tempo, das Sie benötigen.',
        zh: '一站接一站，您将发现这座城市所提供的美妙宝藏，冒险与您同行。此按钮会自动启用或禁用，始终按您所需的节奏。',
        pl: 'Przystanek po przystanku będziecie odkrywać wspaniałe skarby, które oferuje miasto, a przygoda postępuje razem z wami. Ten przycisk aktywuje się lub dezaktywuje automatycznie, zawsze we właściwym rytmie.',
        pt: 'Paragem a paragem, irá descobrindo os maravilhosos tesouros que a cidade tem para oferecer, enquanto a aventura avança consigo. Este botão ativa-se ou desativa-se automaticamente, sempre ao ritmo de que necessita.',
        ru: 'Остановка за остановкой вы будете открывать для себя удивительные сокровища, которые предлагает город, а приключение движется вместе с вами. Эта кнопка включается или выключается автоматически, всегда в нужном вам темпе.',
        uk: 'Зупинка за зупинкою ви відкриватимете чудові скарби, які пропонує місто, а пригода рухається разом з вами. Ця кнопка вмикається або вимикається автоматично, завжди в потрібному вам темпі.',
    },
    // 8 — Botón imagen próxima parada (b4)
    {
        es: '¿Llegando a una nueva parada? Pulse este botón y un vistazo a la imagen de su próxima parada le ayudará a reconocer el lugar al instante.',
        en: 'Arriving at a new stop? Tap this button and a glance at the image of your next stop will help you recognise the place instantly.',
        fr: 'Vous approchez d\'un nouvel arrêt ? Appuyez sur ce bouton et un coup d\'œil à l\'image de votre prochain arrêt vous aidera à reconnaître le lieu instantanément.',
        it: 'State arrivando a una nuova tappa? Premete questo pulsante e uno sguardo all\'immagine della vostra prossima tappa vi aiuterà a riconoscere il posto all\'istante.',
        nl: 'Komt u bij een nieuwe halte? Tik op deze knop en een blik op de afbeelding van uw volgende halte helpt u de plek direct te herkennen.',
        ja: '新しい停車地に近づいていますか？このボタンを押すと、次の停車地の画像をひと目見るだけで、その場所をすぐに認識できます。',
        de: 'Kommen Sie zu einer neuen Haltestelle? Drücken Sie diese Schaltfläche und ein Blick auf das Bild Ihrer nächsten Haltestelle hilft Ihnen, den Ort sofort zu erkennen.',
        zh: '即将到达新的停靠点？点击此按钮，看一眼您下一个停靠点的图片，便能立即认出那个地方。',
        pl: 'Zbliżacie się do nowego przystanku? Naciśnijcie ten przycisk, a jedno spojrzenie na zdjęcie waszego następnego przystanku pomoże natychmiast rozpoznać miejsce.',
        pt: 'A chegar a uma nova paragem? Prima este botão e um olhar para a imagem da sua próxima paragem ajudá-lo-á a reconhecer o local de imediato.',
        ru: 'Подъезжаете к новой остановке? Нажмите эту кнопку, и один взгляд на изображение следующей остановки поможет вам мгновенно узнать место.',
        uk: 'Наближаєтеся до нової зупинки? Натисніть цю кнопку, і один погляд на зображення вашої наступної зупинки допоможе миттєво впізнати місце.',
    },
    // 9 — Botón vídeo / dron (b3)
    {
        es: 'Para quienes prefieran anticiparse antes de llegar: pulsando este botón, un vídeo le guiará hasta la siguiente parada, sin perderse nada. Puede volver a ver el vídeo si lo necesita para no desviarse de la ruta designada.',
        en: 'For those who prefer to get a preview before arriving: by tapping this button, a video will guide you to the next stop without missing a thing. You can watch the video again if you need it to stay on the designated route.',
        fr: 'Pour ceux qui préfèrent anticiper avant d\'arriver : en appuyant sur ce bouton, une vidéo vous guidera jusqu\'au prochain arrêt, sans rien manquer. Vous pouvez revoir la vidéo si nécessaire pour ne pas vous écarter de l\'itinéraire désigné.',
        it: 'Per chi preferisce anticipare prima di arrivare: premendo questo pulsante, un video vi guiderà fino alla prossima tappa, senza perdersi nulla. Potete rivedere il video se necessario per non deviare dal percorso designato.',
        nl: 'Voor wie liever vooruitloopt voor aankomst: door op deze knop te drukken begeleidt een video u naar de volgende halte, zonder iets te missen. U kunt de video opnieuw bekijken als u de aangewezen route wilt volgen.',
        ja: '到着前に先を知りたい方へ：このボタンを押すと、次の停車地まで何も見逃さずにビデオが案内します。指定されたルートから外れないよう、必要であれば再度ビデオをご覧になれます。',
        de: 'Für alle, die sich lieber vorbereiten, bevor sie ankommen: durch Drücken dieser Schaltfläche führt Sie ein Video zur nächsten Haltestelle, ohne etwas zu verpassen. Sie können das Video erneut ansehen, wenn Sie es benötigen, um nicht von der vorgegebenen Route abzuweichen.',
        zh: '对于喜欢提前了解的您：按下此按钮，一段视频将引导您前往下一个停靠点，不遗漏任何细节。如果需要，您可以重新观看视频，以便不偏离指定路线。',
        pl: 'Dla tych, którzy wolą przygotować się przed dotarciem: naciskając ten przycisk, film poprowadzi was do następnego przystanku, bez pominięcia czegokolwiek. Możecie obejrzeć film ponownie, jeśli potrzebujecie, aby nie zbaczać z wyznaczonej trasy.',
        pt: 'Para quem preferir antecipar-se antes de chegar: ao premir este botão, um vídeo irá guiá-lo até à próxima paragem, sem perder nada. Pode rever o vídeo se precisar para não se desviar da rota designada.',
        ru: 'Для тех, кто предпочитает подготовиться заранее: нажав эту кнопку, видео проведёт вас к следующей остановке, не упустив ничего. Вы можете просмотреть видео повторно, если нужно, чтобы не отклоняться от указанного маршрута.',
        uk: 'Для тих, хто вважає за краще підготуватися наперед: натиснувши цю кнопку, відео проведе вас до наступної зупинки, не пропустивши нічого. Ви можете переглянути відео ще раз, якщо потрібно, щоб не відхилятися від вказаного маршруту.',
    },
    // 10 — Botón audio principal
    {
        es: 'En Busca del Tesoro es una experiencia audioguiada, interactiva y didáctica, ideal para descubrir la ciudad mientras juega. Este botón le permitirá escuchar las narraciones en el idioma que elija.',
        en: 'En Busca del Tesoro is an audio-guided, interactive and educational experience, ideal for discovering the city while you play. This button will allow you to listen to the narrations in the language of your choice.',
        fr: 'En Busca del Tesoro est une expérience audioguide, interactive et didactique, idéale pour découvrir la ville en jouant. Ce bouton vous permettra d\'écouter les narrations dans la langue de votre choix.',
        it: 'En Busca del Tesoro è un\'esperienza audioguida, interattiva e didattica, ideale per scoprire la città mentre si gioca. Questo pulsante vi permetterà di ascoltare le narrazioni nella lingua di vostra scelta.',
        nl: 'En Busca del Tesoro is een audiobegeleide, interactieve en educatieve ervaring, ideaal om de stad te ontdekken terwijl u speelt. Met deze knop kunt u de vertellingen beluisteren in de taal van uw keuze.',
        ja: '「En Busca del Tesoro」は、遊びながら街を発見するのに理想的な、音声ガイド付きのインタラクティブで教育的な体験です。このボタンで、お好みの言語でナレーションをお聴きいただけます。',
        de: 'En Busca del Tesoro ist ein audiogeführtes, interaktives und lehrreiches Erlebnis, ideal um die Stadt beim Spielen zu entdecken. Mit dieser Schaltfläche können Sie die Erzählungen in der Sprache Ihrer Wahl anhören.',
        zh: '《En Busca del Tesoro》是一项有声导览的互动教育体验，非常适合在游戏中发现这座城市。此按钮让您可以用自己选择的语言收听旁白。',
        pl: 'En Busca del Tesoro to interaktywne i dydaktyczne doświadczenie z przewodnikiem audio, idealne do odkrywania miasta podczas zabawy. Ten przycisk pozwoli wam słuchać narracji w wybranym języku.',
        pt: 'En Busca del Tesoro é uma experiência audioguiada, interativa e didática, ideal para descobrir a cidade enquanto joga. Este botão permitir-lhe-á ouvir as narrações no idioma da sua escolha.',
        ru: 'En Busca del Tesoro — это аудиогид, интерактивный и познавательный опыт, идеальный для открытия города во время игры. Эта кнопка позволит вам слушать рассказы на выбранном языке.',
        uk: 'En Busca del Tesoro — це аудіогід, інтерактивний та навчальний досвід, ідеальний для відкриття міста під час гри. Ця кнопка дозволить вам слухати розповіді обраною мовою.',
    },
    // 11 — Reto puzzle
    {
        es: 'Cuando este botón se habilite, la diversión irá un paso más allá. Puzles, acertijos y pruebas le esperan.',
        en: 'When this button becomes available, the fun will go one step further. Puzzles, riddles and challenges await you.',
        fr: 'Quand ce bouton sera disponible, le plaisir ira un cran plus loin. Puzzles, énigmes et épreuves vous attendent.',
        it: 'Quando questo pulsante sarà disponibile, il divertimento andrà un passo più in là. Puzzle, enigmi e prove vi aspettano.',
        nl: 'Wanneer deze knop beschikbaar wordt, gaat het plezier een stap verder. Puzzels, raadsels en proeven wachten op u.',
        ja: 'このボタンが使えるようになると、楽しさがもう一段上がります。パズル、なぞなぞ、そして試練があなたを待っています。',
        de: 'Wenn diese Schaltfläche verfügbar wird, macht der Spaß einen Schritt weiter. Puzzles, Rätsel und Aufgaben warten auf Sie.',
        zh: '当此按钮可用时，乐趣将更进一步。拼图、谜语和挑战等待着您。',
        pl: 'Gdy ten przycisk stanie się dostępny, zabawa pójdzie o krok dalej. Puzzle, zagadki i próby czekają na was.',
        pt: 'Quando este botão ficar disponível, a diversão irá um passo mais longe. Puzzles, adivinhas e provas esperam por si.',
        ru: 'Когда эта кнопка станет доступна, веселье выйдет на новый уровень. Головоломки, загадки и испытания ждут вас.',
        uk: 'Коли ця кнопка стане доступною, розваги підуть на крок далі. Пазли, загадки та випробування чекають на вас.',
    },
    // 12 — Reto preguntas MCQ
    {
        es: '¿Y si las preguntas no fueran tan simples? Algunas son de opción múltiple y pueden tener más de una respuesta correcta. ¡Lea con atención antes de responder y observe su entorno!',
        en: 'What if the questions were not so simple? Some are multiple choice and may have more than one correct answer. Read carefully before answering and observe your surroundings!',
        fr: 'Et si les questions n\'étaient pas si simples ? Certaines sont à choix multiples et peuvent avoir plus d\'une bonne réponse. Lisez attentivement avant de répondre et observez votre environnement !',
        it: 'E se le domande non fossero così semplici? Alcune sono a opzione multipla e possono avere più di una risposta corretta. Leggete attentamente prima di rispondere e osservate l\'ambiente intorno a voi!',
        nl: 'Wat als de vragen niet zo eenvoudig zijn? Sommige zijn meerkeuze en kunnen meer dan één correct antwoord hebben. Lees zorgvuldig voordat u antwoordt en observeer uw omgeving!',
        ja: 'もし質問がそれほど簡単でなかったら？複数選択式で、正しい答えが複数ある場合もあります。答える前によく読み、周囲をよく観察しましょう！',
        de: 'Was, wenn die Fragen nicht so einfach wären? Manche sind Multiple-Choice und können mehr als eine richtige Antwort haben. Lesen Sie sorgfältig, bevor Sie antworten, und beobachten Sie Ihre Umgebung!',
        zh: '如果问题没那么简单呢？有些是多选题，可能有不止一个正确答案。回答前请仔细阅读，并观察周围环境！',
        pl: 'A gdyby pytania nie były takie proste? Niektóre są wielokrotnego wyboru i mogą mieć więcej niż jedną poprawną odpowiedź. Czytajcie uważnie przed odpowiedzią i obserwujcie otoczenie!',
        pt: 'E se as perguntas não fossem assim tão simples? Algumas são de opção múltipla e podem ter mais do que uma resposta correta. Leia com atenção antes de responder e observe o que o rodeia!',
        ru: 'А что, если вопросы окажутся не такими простыми? Некоторые из них с множественным выбором и могут иметь несколько правильных ответов. Читайте внимательно перед ответом и наблюдайте за своим окружением!',
        uk: 'А що, якщо запитання виявляться не такими простими? Деякі є множинним вибором і можуть мати більше однієї правильної відповіді. Читайте уважно перед відповіддю та спостерігайте за своїм оточенням!',
    },
    // 13 — Pausa / cámara / lugar recomendado
    {
        es: 'Valencia merece ser saboreada. Fotografíe, descanse, explore el lugar recomendado… Su aventura no tiene prisa. Tampoco usted. Le invitamos a recorrer sus calles, resolver enigmas y descubrir su patrimonio de una forma amena. Hagamos de la historia una experiencia divertida.',
        en: 'Valencia deserves to be savoured. Take photos, rest, explore the recommended spot… Your adventure is in no hurry. Neither are you. We invite you to wander its streets, solve mysteries and discover its heritage in an enjoyable way. Let us make history a fun experience.',
        fr: 'Valence mérite d\'être savourée. Photographiez, reposez-vous, explorez l\'endroit recommandé… Votre aventure n\'est pas pressée. Vous non plus. Nous vous invitons à parcourir ses rues, résoudre des énigmes et découvrir son patrimoine d\'une façon agréable. Faisons de l\'histoire une expérience amusante.',
        it: 'Valencia merita di essere assaporata. Fotografate, riposatevi, esplorate il posto consigliato… La vostra avventura non ha fretta. Neanche voi. Vi invitiamo a percorrere le sue strade, risolvere enigmi e scoprire il suo patrimonio in modo piacevole. Facciamo della storia un\'esperienza divertente.',
        nl: 'Valencia verdient het om te worden geproefd. Fotografeer, rust uit, verken de aanbevolen plek… Uw avontuur heeft geen haast. U ook niet. Wij nodigen u uit om door de straten te wandelen, raadsels op te lossen en het erfgoed op een aangename manier te ontdekken. Laten we van geschiedenis een leuke ervaring maken.',
        ja: 'バレンシアは味わう価値があります。写真を撮り、休息し、おすすめの場所を探索してください…あなたの冒険は急ぎません。あなたも同じです。街の通りを歩き、謎を解き、その文化遺産を楽しく発見されることをお勧めします。歴史を楽しい体験にしましょう。',
        de: 'Valencia verdient es, ausgekostet zu werden. Fotografieren Sie, ruhen Sie sich aus, erkunden Sie den empfohlenen Ort… Ihr Abenteuer hat es nicht eilig. Sie auch nicht. Wir laden Sie ein, durch die Straßen zu schlendern, Rätsel zu lösen und das Kulturerbe auf eine angenehme Weise zu entdecken. Machen wir aus der Geschichte ein unterhaltsames Erlebnis.',
        zh: '瓦伦西亚值得细细品味。拍照、休息、探索推荐的地方……您的冒险不着急，您也不必着急。我们邀请您漫步于街道之间，解开谜题，以轻松愉快的方式发现这座城市的文化遗产。让我们把历史变成一次有趣的体验。',
        pl: 'Walencja zasługuje na to, żeby ją smakować. Fotografujcie, odpoczywajcie, odkrywajcie polecane miejsce… Wasza przygoda się nie spieszy. Wy też nie. Zapraszamy do spacerowania jej ulicami, rozwiązywania zagadek i odkrywania jej dziedzictwa w przyjemny sposób. Sprawmy, żeby historia stała się zabawnym przeżyciem.',
        pt: 'Valência merece ser saboreada. Tire fotos, descanse, explore o local recomendado… A sua aventura não tem pressa. Nem você. Convidamo-lo a percorrer as suas ruas, resolver enigmas e descobrir o seu património de forma agradável. Façamos da história uma experiência divertida.',
        ru: 'Валенсия заслуживает того, чтобы её смаковали. Фотографируйте, отдыхайте, исследуйте рекомендованное место… Ваше приключение не торопится. И вы тоже. Приглашаем вас прогуляться по её улицам, разгадать загадки и открыть её наследие увлекательным образом. Давайте сделаем историю интересным опытом.',
        uk: 'Валенсія заслуговує на те, щоб нею насолоджуватися. Фотографуйте, відпочивайте, досліджуйте рекомендоване місце… Ваша пригода не поспішає. І ви теж. Запрошуємо вас прогулятися її вулицями, розгадати загадки та відкрити її спадщину в приємний спосіб. Зробімо з історії веселий досвід.',
    },
    // 14 — Fuera de ruta / botón ubicación (b6)
    {
        es: '¿Se ha despistado? No pasa nada. Si se aleja de la ruta, este botón se activará solo para devolverle al camino.',
        en: 'Lost your bearings? No worries. If you stray from the route, this button will activate on its own to guide you back on track.',
        fr: 'Vous vous êtes perdu ? Ce n\'est pas grave. Si vous vous éloignez de l\'itinéraire, ce bouton s\'activera seul pour vous remettre sur la bonne voie.',
        it: 'Vi siete persi? Non preoccupatevi. Se vi allontanate dal percorso, questo pulsante si attiverà da solo per riportarvi sulla strada giusta.',
        nl: 'De weg kwijtgeraakt? Geen probleem. Als u van de route afdwaalt, zal deze knop zichzelf activeren om u terug op weg te helpen.',
        ja: '迷ってしまいましたか？大丈夫です。ルートから外れると、このボタンが自動的に有効になり、道に戻るよう案内します。',
        de: 'Den Weg verloren? Kein Problem. Wenn Sie von der Route abweichen, aktiviert sich diese Schaltfläche von selbst, um Sie zurückzuführen.',
        zh: '迷路了？没关系。如果您偏离路线，此按钮将自动启用，带您重回正轨。',
        pl: 'Zgubiliście się? Nic się nie stało. Jeśli odejdziecie od trasy, ten przycisk aktywuje się sam, by prowadzić was z powrotem na właściwą drogę.',
        pt: 'Perdeu-se? Não há problema. Se se afastar da rota, este botão ativar-se-á sozinho para o guiar de volta ao caminho.',
        ru: 'Заблудились? Ничего страшного. Если вы отклонитесь от маршрута, эта кнопка активируется сама, чтобы вернуть вас на путь.',
        uk: 'Загубилися? Нічого страшного. Якщо ви відхилитеся від маршруту, ця кнопка активується сама, щоб повернути вас на шлях.',
    },
    // 15 — Caballero regresa caminando (escena visual, sin bocadillo)
    null,
    // 16 — GPS error / caballero durmiendo / descanso largo
    {
        es: 'Las grandes aventuras también tienen sus pausas. Si necesita descansar y continuar más tarde, este botón le llevará de vuelta al punto exacto donde lo dejó.',
        en: 'Great adventures also have their pauses. If you need to rest and continue later, this button will take you back to the exact point where you left off.',
        fr: 'Les grandes aventures ont aussi leurs pauses. Si vous avez besoin de vous reposer et de continuer plus tard, ce bouton vous ramènera exactement là où vous vous étiez arrêté.',
        it: 'Anche le grandi avventure hanno le loro pause. Se avete bisogno di riposarvi e continuare più tardi, questo pulsante vi riporterà esattamente al punto in cui vi eravate fermati.',
        nl: 'Grote avonturen kennen ook hun pauzes. Als u wilt rusten en later verder wilt gaan, brengt deze knop u terug naar precies het punt waar u was gebleven.',
        ja: '大きな冒険にも休憩があります。休んで後で続けたい場合、このボタンがやめた地点へ正確に戻してくれます。',
        de: 'Auch große Abenteuer haben ihre Pausen. Wenn Sie sich ausruhen und später weitermachen möchten, bringt diese Schaltfläche Sie genau dorthin zurück, wo Sie aufgehört haben.',
        zh: '伟大的冒险也有它的暂停。如果您需要休息，稍后再继续，此按钮将带您返回到您离开的确切位置。',
        pl: 'Wielkie przygody też mają swoje przerwy. Jeśli potrzebujecie odpocząć i kontynuować później, ten przycisk zabierze was dokładnie do punktu, w którym skończyliście.',
        pt: 'As grandes aventuras também têm as suas pausas. Se precisar de descansar e continuar mais tarde, este botão levará de volta ao ponto exato onde ficou.',
        ru: 'Великие приключения тоже имеют свои паузы. Если вам нужно отдохнуть и продолжить позже, эта кнопка вернёт вас именно туда, где вы остановились.',
        uk: 'Великі пригоди теж мають свої паузи. Якщо вам потрібно відпочити і продовжити пізніше, ця кнопка поверне вас саме до того місця, де ви зупинилися.',
    },
    // 17 — Botón temporizador
    {
        es: 'Cada aventura tiene un tiempo estimado de finalización. Aquí puede controlar el tiempo transcurrido en todo momento.',
        en: 'Each adventure has an estimated completion time. Here you can check the elapsed time whenever you wish.',
        fr: 'Chaque aventure a un temps estimé de réalisation. Ici, vous pouvez vérifier le temps écoulé quand vous le souhaitez.',
        it: 'Ogni avventura ha un tempo stimato di completamento. Qui potete controllare il tempo trascorso quando volete.',
        nl: 'Elk avontuur heeft een geschatte voltooiingstijd. Hier kunt u de verstreken tijd controleren wanneer u maar wilt.',
        ja: '各冒険には推定完了時間があります。ここでいつでも経過時間を確認できます。',
        de: 'Jedes Abenteuer hat eine geschätzte Abschlusszeit. Hier können Sie die verstrichene Zeit jederzeit überprüfen.',
        zh: '每项冒险都有预计完成时间。您可以随时在这里查看已用时间。',
        pl: 'Każda przygoda ma szacowany czas ukończenia. Tutaj możecie sprawdzić upłynięty czas, kiedy tylko chcecie.',
        pt: 'Cada aventura tem um tempo estimado de conclusão. Aqui pode verificar o tempo decorrido sempre que quiser.',
        ru: 'Каждое приключение имеет расчётное время завершения. Здесь вы можете проверить прошедшее время в любой момент.',
        uk: 'Кожна пригода має розрахунковий час завершення. Тут ви можете перевірити минулий час будь-коли.',
    },
    // 18 — Asistente / preguntas frecuentes
    {
        es: '¿Alguna pregunta? Tenemos respuestas. Pulse aquí para acceder a nuestro listado de preguntas frecuentes.',
        en: 'Any questions? We have answers. Tap here to access our list of frequently asked questions.',
        fr: 'Des questions ? Nous avons des réponses. Appuyez ici pour accéder à notre liste de questions fréquentes.',
        it: 'Domande? Abbiamo le risposte. Premete qui per accedere al nostro elenco di domande frequenti.',
        nl: 'Vragen? Wij hebben antwoorden. Druk hier om toegang te krijgen tot onze lijst met veelgestelde vragen.',
        ja: 'ご質問はありますか？回答があります。こちらをタップして、よくある質問の一覧にアクセスしてください。',
        de: 'Fragen? Wir haben Antworten. Drücken Sie hier, um auf unsere Liste häufig gestellter Fragen zuzugreifen.',
        zh: '有任何问题？我们有答案。点击此处访问我们的常见问题列表。',
        pl: 'Macie pytania? Mamy odpowiedzi. Naciśnijcie tutaj, aby uzyskać dostęp do naszej listy często zadawanych pytań.',
        pt: 'Alguma pergunta? Temos respostas. Prima aqui para aceder à nossa lista de perguntas frequentes.',
        ru: 'Есть вопросы? У нас есть ответы. Нажмите здесь для доступа к списку часто задаваемых вопросов.',
        uk: 'Є запитання? Ми маємо відповіді. Натисніть тут, щоб отримати доступ до списку поширених запитань.',
    },
    // 19 — Pantalla final
    {
        es: 'Todo preparado. Valencia le espera con sus monumentos, sus secretos y sus retos. ¡Que comience la aventura!',
        en: 'All set. Valencia awaits you with its monuments, its secrets and its challenges. Let the adventure begin!',
        fr: 'Tout est prêt. Valence vous attend avec ses monuments, ses secrets et ses défis. Que l\'aventure commence !',
        it: 'Tutto pronto. Valencia vi aspetta con i suoi monumenti, i suoi segreti e le sue sfide. Che l\'avventura abbia inizio!',
        nl: 'Alles klaar. Valencia wacht op u met zijn monumenten, zijn geheimen en zijn uitdagingen. Laat het avontuur beginnen!',
        ja: '準備完了です。バレンシアがその名所、秘密、そして挑戦とともにあなたを待っています。冒険を始めましょう！',
        de: 'Alles bereit. Valencia wartet mit seinen Denkmälern, Geheimnissen und Herausforderungen auf Sie. Das Abenteuer beginnt!',
        zh: '一切就绪。瓦伦西亚以其名胜古迹、秘密与挑战等待着您。让冒险开始吧！',
        pl: 'Wszystko gotowe. Walencja czeka na was ze swoimi zabytkami, tajemnicami i wyzwaniami. Niech przygoda się rozpocznie!',
        pt: 'Tudo pronto. Valência está à sua espera com os seus monumentos, os seus segredos e os seus desafios. Que a aventura comece!',
        ru: 'Всё готово. Валенсия ждёт вас со своими памятниками, секретами и испытаниями. Пусть приключение начнётся!',
        uk: 'Все готово. Валенсія чекає на вас зі своїми пам\'ятками, таємницями та випробуваннями. Нехай пригода розпочнеться!',
    },
];

export const TRADUCCIONES_SW_UPDATE = {
    es: { label: '🔄 Nueva versión disponible', boton: 'Actualizar' },
    en: { label: '🔄 New version available',    boton: 'Update' },
    fr: { label: '🔄 Nouvelle version disponible', boton: 'Mettre à jour' },
    it: { label: '🔄 Nuova versione disponibile',   boton: 'Aggiorna' },
    nl: { label: '🔄 Nieuwe versie beschikbaar',    boton: 'Bijwerken' },
    de: { label: '🔄 Neue Version verfügbar',       boton: 'Aktualisieren' },
    ja: { label: '🔄 新しいバージョンが利用可能です', boton: '更新' },
    zh: { label: '🔄 新版本可用',                   boton: '更新' },
    pl: { label: '🔄 Nowa wersja dostępna',         boton: 'Zaktualizuj' },
    pt: { label: '🔄 Nova versão disponível',       boton: 'Atualizar' },
    ru: { label: '🔄 Доступна новая версия',        boton: 'Обновить' },
    uk: { label: '🔄 Доступна нова версія',         boton: 'Оновити' },
};

export const PLACEHOLDER_RESPUESTA_TEXTO = {
    es: 'Escriba su respuesta aquí...',
    en: 'Write your answer here...',
    fr: 'Écrivez votre réponse ici...',
    it: 'Scrivi qui la tua risposta...',
    nl: 'Schrijf hier je antwoord...',
    de: 'Schreiben Sie hier Ihre Antwort...',
    ja: 'ここに回答を入力してください...',
    zh: '请在此输入您的答案...',
    pl: 'Wpisz tutaj swoją odpowiedź...',
    pt: 'Escreva a sua resposta aqui...',
    ru: 'Напишите ваш ответ здесь...',
    uk: 'Напишіть свою відповідь тут...'
};
