/**
 * traducciones-ui.js - Textos de interfaz traducidos a los 12 idiomas
 *
 * Centraliza bloques de traducción que antes estaban duplicados/dispersos
 * como constantes inline en codigo-padre.html, retos-hijo4.html,
 * chat-hijo6.html, En-busca-del-tesoro.html y video-intro.html.
 */

export const TRADUCCIONES_REANUDACION = {
    es: {
        titulo: '¡Aventura en curso!',
        info: 'Tienes una aventura activa:',
        idioma: 'Idioma',
        progreso: 'Progreso',
        parada: 'parada',
        de: 'de',
        continuar: 'Continuar mi aventura',
        elegirOtra: 'Elegir otra aventura',
        autoContinuar: 'Continuando automáticamente en',
        segundos: 's',
        advertenciaTitulo: '⚠️ Atención',
        advertenciaTexto1: 'Perderás todo el progreso de tu aventura actual:',
        advertenciaTexto2: 'Además, necesitarás adquirir una nueva aventura.',
        volver: 'Volver a mi aventura',
        confirmarOtra: 'Sí, elegir otra aventura'
    },
    en: {
        titulo: 'Adventure in progress!',
        info: 'You have an active adventure:',
        idioma: 'Language',
        progreso: 'Progress',
        parada: 'stop',
        de: 'of',
        continuar: 'Continue my adventure',
        elegirOtra: 'Choose another adventure',
        autoContinuar: 'Auto-continuing in',
        segundos: 's',
        advertenciaTitulo: '⚠️ Warning',
        advertenciaTexto1: 'You will lose all progress in your current adventure:',
        advertenciaTexto2: 'You will also need to purchase a new adventure.',
        volver: 'Return to my adventure',
        confirmarOtra: 'Yes, choose another adventure'
    },
    fr: {
        titulo: 'Aventure en cours !',
        info: 'Vous avez une aventure active :',
        idioma: 'Langue',
        progreso: 'Progression',
        parada: 'arrêt',
        de: 'sur',
        continuar: 'Continuer mon aventure',
        elegirOtra: 'Choisir une autre aventure',
        autoContinuar: 'Continuation automatique dans',
        segundos: 's',
        advertenciaTitulo: '⚠️ Attention',
        advertenciaTexto1: 'Vous perdrez toute la progression de votre aventure actuelle :',
        advertenciaTexto2: 'De plus, vous devrez acheter une nouvelle aventure.',
        volver: 'Retourner à mon aventure',
        confirmarOtra: 'Oui, choisir une autre aventure'
    },
    it: {
        titulo: 'Avventura in corso!',
        info: 'Hai un\'avventura attiva:',
        idioma: 'Lingua',
        progreso: 'Progresso',
        parada: 'tappa',
        de: 'di',
        continuar: 'Continua la mia avventura',
        elegirOtra: 'Scegli un\'altra avventura',
        autoContinuar: 'Continuazione automatica tra',
        segundos: 's',
        advertenciaTitulo: '⚠️ Attenzione',
        advertenciaTexto1: 'Perderai tutto il progresso della tua avventura attuale:',
        advertenciaTexto2: 'Inoltre, dovrai acquistare una nuova avventura.',
        volver: 'Torna alla mia avventura',
        confirmarOtra: 'Sì, scegli un\'altra avventura'
    },
    nl: {
        titulo: 'Avontuur bezig!',
        info: 'Je hebt een actief avontuur:',
        idioma: 'Taal',
        progreso: 'Voortgang',
        parada: 'halte',
        de: 'van',
        continuar: 'Mijn avontuur voortzetten',
        elegirOtra: 'Kies een ander avontuur',
        autoContinuar: 'Automatisch verder over',
        segundos: 's',
        advertenciaTitulo: '⚠️ Let op',
        advertenciaTexto1: 'Je verliest alle voortgang van je huidige avontuur:',
        advertenciaTexto2: 'Bovendien moet je een nieuw avontuur aanschaffen.',
        volver: 'Terug naar mijn avontuur',
        confirmarOtra: 'Ja, kies een ander avontuur'
    },
    ja: {
        titulo: '冒険が進行中です！',
        info: 'アクティブな冒険があります：',
        idioma: '言語',
        progreso: '進捗',
        parada: 'ストップ',
        de: '/',
        continuar: '冒険を続ける',
        elegirOtra: '別の冒険を選ぶ',
        autoContinuar: '自動的に続行します',
        segundos: '秒',
        advertenciaTitulo: '⚠️ 注意',
        advertenciaTexto1: '現在の冒険のすべての進捗を失います：',
        advertenciaTexto2: 'また、新しい冒険を購入する必要があります。',
        volver: '冒険に戻る',
        confirmarOtra: 'はい、別の冒険を選びます'
    },
    ru: {
        titulo: 'Приключение в процессе!',
        info: 'У вас есть активное приключение:',
        idioma: 'Язык',
        progreso: 'Прогресс',
        parada: 'остановка',
        de: 'из',
        continuar: 'Продолжить приключение',
        elegirOtra: 'Выбрать другое приключение',
        autoContinuar: 'Автоматическое продолжение через',
        segundos: 'с',
        advertenciaTitulo: '⚠️ Внимание',
        advertenciaTexto1: 'Вы потеряете весь прогресс текущего приключения:',
        advertenciaTexto2: 'Кроме того, вам нужно будет приобрести новое приключение.',
        volver: 'Вернуться к приключению',
        confirmarOtra: 'Да, выбрать другое приключение'
    },
    zh: {
        titulo: '冒险进行中！',
        info: '您有一个进行中的冒险：',
        idioma: '语言',
        progreso: '进度',
        parada: '站点',
        de: '/',
        continuar: '继续我的冒险',
        elegirOtra: '选择其他冒险',
        autoContinuar: '自动继续，倒计时',
        segundos: '秒',
        advertenciaTitulo: '⚠️ 注意',
        advertenciaTexto1: '您将失去当前冒险的所有进度：',
        advertenciaTexto2: '此外，您还需要购买新的冒险。',
        volver: '返回我的冒险',
        confirmarOtra: '是，选择其他冒险'
    },
    pl: {
        titulo: 'Przygoda w toku!',
        info: 'Masz aktywną przygodę:',
        idioma: 'Język',
        progreso: 'Postęp',
        parada: 'przystanek',
        de: 'z',
        continuar: 'Kontynuuj moją przygodę',
        elegirOtra: 'Wybierz inną przygodę',
        autoContinuar: 'Automatyczne kontynuowanie za',
        segundos: 's',
        advertenciaTitulo: '⚠️ Uwaga',
        advertenciaTexto1: 'Stracisz cały postęp swojej obecnej przygody:',
        advertenciaTexto2: 'Ponadto będziesz musiał zakupić nową przygodę.',
        volver: 'Wróć do mojej przygody',
        confirmarOtra: 'Tak, wybierz inną przygodę'
    },
    uk: {
        titulo: 'Пригода в процесі!',
        info: 'У вас є активна пригода:',
        idioma: 'Мова',
        progreso: 'Прогрес',
        parada: 'зупинка',
        de: 'з',
        continuar: 'Продовжити пригоду',
        elegirOtra: 'Вибрати іншу пригоду',
        autoContinuar: 'Автоматичне продовження через',
        segundos: 'с',
        advertenciaTitulo: '⚠️ Увага',
        advertenciaTexto1: 'Ви втратите весь прогрес поточної пригоди:',
        advertenciaTexto2: 'Крім того, вам потрібно буде придбати нову пригоду.',
        volver: 'Повернутися до пригоди',
        confirmarOtra: 'Так, вибрати іншу пригоду'
    },
    pt: {
        titulo: 'Aventura em curso!',
        info: 'Tem uma aventura ativa:',
        idioma: 'Idioma',
        progreso: 'Progresso',
        parada: 'paragem',
        de: 'de',
        continuar: 'Continuar a minha aventura',
        elegirOtra: 'Escolher outra aventura',
        autoContinuar: 'Continuação automática em',
        segundos: 's',
        advertenciaTitulo: '⚠️ Atenção',
        advertenciaTexto1: 'Perderá todo o progresso da sua aventura atual:',
        advertenciaTexto2: 'Além disso, precisará adquirir uma nova aventura.',
        volver: 'Voltar à minha aventura',
        confirmarOtra: 'Sim, escolher outra aventura'
    },
    de: {
        titulo: 'Abenteuer läuft!',
        info: 'Sie haben ein aktives Abenteuer:',
        idioma: 'Sprache',
        progreso: 'Fortschritt',
        parada: 'Halt',
        de: 'von',
        continuar: 'Mein Abenteuer fortsetzen',
        elegirOtra: 'Ein anderes Abenteuer wählen',
        autoContinuar: 'Automatische Fortsetzung in',
        segundos: 's',
        advertenciaTitulo: '⚠️ Achtung',
        advertenciaTexto1: 'Sie verlieren den gesamten Fortschritt Ihres aktuellen Abenteuers:',
        advertenciaTexto2: 'Außerdem müssen Sie ein neues Abenteuer erwerben.',
        volver: 'Zurück zu meinem Abenteuer',
        confirmarOtra: 'Ja, ein anderes Abenteuer wählen'
    }
};

export const TRADUCCIONES_FINALIZACION = {
    es: { titulo: '¡Felicidades!', completado: 'Has completado', pregunta: '¿Qué deseas hacer ahora?', btn_otra: 'Hacer otra aventura', btn_terminar: 'Terminar esta experiencia' },
    en: { titulo: 'Congratulations!', completado: 'You have completed', pregunta: 'What would you like to do now?', btn_otra: 'Start another adventure', btn_terminar: 'End this experience' },
    fr: { titulo: 'Félicitations !', completado: 'Vous avez terminé', pregunta: 'Que souhaitez-vous faire maintenant ?', btn_otra: 'Faire une autre aventure', btn_terminar: 'Terminer cette expérience' },
    it: { titulo: 'Congratulazioni!', completado: 'Hai completato', pregunta: 'Cosa desideri fare adesso?', btn_otra: "Fare un'altra avventura", btn_terminar: 'Terminare questa esperienza' },
    nl: { titulo: 'Gefeliciteerd!', completado: 'Je hebt voltooid', pregunta: 'Wat wil je nu doen?', btn_otra: 'Een ander avontuur beginnen', btn_terminar: 'Deze ervaring beëindigen' },
    de: { titulo: 'Herzlichen Glückwunsch!', completado: 'Sie haben abgeschlossen', pregunta: 'Was möchten Sie jetzt tun?', btn_otra: 'Ein anderes Abenteuer beginnen', btn_terminar: 'Dieses Erlebnis beenden' },
    ja: { titulo: 'おめでとうございます！', completado: '完了しました', pregunta: '次に何をしますか？', btn_otra: '別のアドベンチャーを始める', btn_terminar: 'この体験を終了する' },
    zh: { titulo: '恭喜！', completado: '您已完成', pregunta: '您现在想做什么？', btn_otra: '开始另一个冒险', btn_terminar: '结束此体验' },
    pl: { titulo: 'Gratulacje!', completado: 'Ukończyłeś', pregunta: 'Co chcesz teraz zrobić?', btn_otra: 'Rozpocząć inną przygodę', btn_terminar: 'Zakończyć to doświadczenie' },
    pt: { titulo: 'Parabéns!', completado: 'Você completou', pregunta: 'O que deseja fazer agora?', btn_otra: 'Fazer outra aventura', btn_terminar: 'Terminar esta experiência' },
    ru: { titulo: 'Поздравляем!', completado: 'Вы завершили', pregunta: 'Что вы хотите сделать сейчас?', btn_otra: 'Начать другое приключение', btn_terminar: 'Завершить этот опыт' },
    uk: { titulo: 'Вітаємо!', completado: 'Ви завершили', pregunta: 'Що ви хочете зробити тепер?', btn_otra: 'Розпочати іншу пригоду', btn_terminar: 'Завершити цей досвід' }
};

export const TRADUCCIONES_TIEMPO_AGOTADO = {
    es: { titulo: '¡Tiempo agotado!', cuerpo: 'El tiempo máximo para completar esta aventura ha terminado. Gracias por participar.' },
    en: { titulo: "Time's up!", cuerpo: 'The maximum time to complete this adventure has ended. Thank you for participating.' },
    fr: { titulo: 'Temps écoulé !', cuerpo: 'Le temps maximum pour terminer cette aventure est terminé. Merci d\'avoir participé.' },
    it: { titulo: 'Tempo scaduto!', cuerpo: 'Il tempo massimo per completare questa avventura è terminato. Grazie per aver partecipato.' },
    nl: { titulo: 'Tijd verstreken!', cuerpo: 'De maximale tijd om dit avontuur te voltooien is verstreken. Bedankt voor je deelname.' },
    de: { titulo: 'Zeit abgelaufen!', cuerpo: 'Die maximale Zeit für dieses Abenteuer ist abgelaufen. Danke fürs Mitmachen.' },
    ja: { titulo: '時間切れです！', cuerpo: 'この冒険を完了するための制限時間が終了しました。ご参加ありがとうございました。' },
    zh: { titulo: '时间到！', cuerpo: '完成此冒险的最长时间已结束。感谢您的参与。' },
    pl: { titulo: 'Czas minął!', cuerpo: 'Maksymalny czas na ukończenie tej przygody dobiegł końca. Dziękujemy za udział.' },
    pt: { titulo: 'Tempo esgotado!', cuerpo: 'O tempo máximo para completar esta aventura terminou. Obrigado por participar.' },
    ru: { titulo: 'Время истекло!', cuerpo: 'Максимальное время для прохождения этого приключения истекло. Спасибо за участие.' },
    uk: { titulo: 'Час вийшов!', cuerpo: 'Максимальний час для проходження цієї пригоди закінчився. Дякуємо за участь.' }
};

export const TRADUCCIONES_DESPEDIDA = {
    es: '¡Hasta pronto! Gracias por explorar Valencia con nosotros.',
    en: 'Goodbye! Thank you for exploring Valencia with us.',
    fr: 'Au revoir ! Merci d\'avoir exploré Valence avec nous.',
    it: 'Arrivederci! Grazie per aver esplorato Valencia con noi.',
    nl: 'Tot ziens! Bedankt voor het verkennen van Valencia met ons.',
    de: 'Auf Wiedersehen! Danke, dass Sie Valencia mit uns erkundet haben.',
    ja: 'またね！バレンシアを一緒に探検してくれてありがとう。',
    zh: '再见！感谢您与我们一起探索瓦伦西亚。',
    pl: 'Do widzenia! Dziękujemy za eksplorację Walencji z nami.',
    pt: 'Até logo! Obrigado por explorar Valência connosco.',
    ru: 'До свидания! Спасибо, что исследовали Валенсию вместе с нами.',
    uk: 'До побачення! Дякуємо, що досліджували Валенсію разом з нами.'
};

export const MSG_RETOS_COMPLETOS = {
    es: '¡Has completado todos los retos!',
    en: "You've completed all the challenges!",
    fr: 'Vous avez terminé tous les défis !',
    it: 'Hai completato tutte le sfide!',
    nl: 'Je hebt alle uitdagingen voltooid!',
    ja: 'すべてのチャレンジをクリアしました！',
    de: 'Du hast alle Aufgaben abgeschlossen!',
    zh: '你已完成所有挑战！',
    pl: 'Ukończono wszystkie wyzwania!',
    pt: 'Completaste todos os desafios!',
    ru: 'Вы завершили все задания!',
    uk: 'Ви завершили всі завдання!'
};

export const TITULOS_CHAT = {
    es: 'Soporte', en: 'Support', fr: 'Assistance',
    it: 'Supporto', nl: 'Ondersteuning', ja: 'サポート',
    de: 'Hilfe', zh: '帮助', pl: 'Pomoc',
    pt: 'Suporte', ru: 'Помощь', uk: 'Допомога'
};

// Un objeto por pantalla de video-intro.html, en el mismo orden que run().
// El índice 15 es null (escena visual sin bocadillo).
export const JAIME_SCENES = [
    // 0 — Logos / bienvenida
    {
        es: 'Soy Jaime I de Aragón, el Rey Conquistador. Permítame ser su guía antes de que la aventura dé comienzo.',
        en: 'I am James I of Aragon, the Conqueror King. Allow me to be your guide before the adventure begins.',
        fr: 'Je suis Jacques Ier d\'Aragon, le Roi Conquérant. Permettez-moi d\'être votre guide avant que l\'aventure commence.',
        it: 'Sono Giacomo I d\'Aragona, il Re Conquistatore. Permettetemi di essere la vostra guida prima che l\'avventura abbia inizio.',
        nl: 'Ik ben Jacobus I van Aragon, de Veroveraar. Sta mij toe uw gids te zijn voordat het avontuur begint.',
        ja: '私はアラゴンのハイメ1世、征服王です。冒険が始まる前に、どうかあなたのガイドをさせてください。',
        de: 'Ich bin Jakob I. von Aragón, der Erobererkönig. Gestatten Sie mir, Ihr Führer zu sein, bevor das Abenteuer beginnt.',
        zh: '我是阿拉贡的哈梅一世，征服者之王。请允许我在冒险开始之前担任您的向导。',
        pl: 'Jestem Jakubem I Aragońskim, Królem Zdobywcą. Pozwólcie, że będę waszym przewodnikiem, zanim przygoda się rozpocznie.',
        pt: 'Sou Jaime I de Aragão, o Rei Conquistador. Permita-me ser o seu guia antes que a aventura comece.',
        ru: 'Я Хайме I Арагонский, Король-Завоеватель. Позвольте мне стать вашим гидом, прежде чем приключение начнётся.',
        uk: 'Я Хайме I Арагонський, Король-Завойовник. Дозвольте мені стати вашим гідом, перш ніж пригода розпочнеться.',
    },
    // 1 — GPS / internet (reubicada como segunda pantalla)
    {
        es: 'Una pequeña cosa antes de partir: active el GPS, asegúrese de tener conexión a internet y conceda los permisos que le solicite su dispositivo.',
        en: 'One small thing before you set off: enable GPS, make sure you have an internet connection and grant the permissions your device requests.',
        fr: 'Une petite chose avant de partir : activez le GPS, assurez-vous d\'avoir une connexion internet et accordez les autorisations demandées par votre appareil.',
        it: 'Una piccola cosa prima di partire: attivate il GPS, assicuratevi di avere una connessione internet e concedete i permessi richiesti dal vostro dispositivo.',
        nl: 'Eén ding voor het vertrek: schakel GPS in, zorg voor een internetverbinding en verleen de toestemmingen die uw apparaat vraagt.',
        ja: '出発前にひとつ：GPSを有効にし、インターネット接続を確認し、デバイスが要求する権限を許可してください。',
        de: 'Eine kurze Sache vor dem Aufbruch: Aktivieren Sie das GPS, stellen Sie sicher, dass Sie eine Internetverbindung haben, und gewähren Sie die Berechtigungen, die Ihr Gerät anfordert.',
        zh: '出发前的小事：请开启GPS，确保有网络连接，并授予设备所需的权限。',
        pl: 'Jedna mała rzecz przed wyruszeniem: włączcie GPS, upewnijcie się, że macie połączenie z internetem i przyznajcie uprawnienia, których wymaga urządzenie.',
        pt: 'Uma pequena coisa antes de partir: ative o GPS, certifique-se de ter ligação à internet e conceda as permissões que o seu dispositivo solicitar.',
        ru: 'Одна небольшая вещь перед отправлением: включите GPS, убедитесь в наличии интернет-соединения и предоставьте разрешения, которые запрашивает ваше устройство.',
        uk: 'Одна невелика річ перед відправленням: увімкніть GPS, переконайтеся, що є підключення до інтернету, та надайте дозволи, які запитує ваш пристрій.',
    },
    // 2 — Selección de aventura
    {
        es: 'Tenemos el gusto de poder ofrecerle varias aventuras. Cada una tiene su distancia, duración y transporte recomendado. Elija la que más le guste.',
        en: 'We are delighted to offer you several adventures. Each one has its own distance, duration and recommended transport. Choose the one you like most.',
        fr: 'Nous avons le plaisir de vous proposer plusieurs aventures. Chacune a sa propre distance, durée et transport recommandé. Choisissez celle qui vous plaît le plus.',
        it: 'Abbiamo il piacere di offrirvi diverse avventure. Ognuna ha la propria distanza, durata e trasporto consigliato. Scegliete quella che preferite.',
        nl: 'Het is ons een genoegen u verschillende avonturen aan te bieden. Elk heeft zijn eigen afstand, duur en aanbevolen vervoer. Kies het avontuur dat u het meest aanspreekt.',
        ja: 'いくつかの冒険をご用意しております。それぞれ独自の距離、所要時間、おすすめの移動手段があります。お好みのものをお選びください。',
        de: 'Wir freuen uns, Ihnen mehrere Abenteuer anbieten zu können. Jedes hat seine eigene Distanz, Dauer und empfohlenes Verkehrsmittel. Wählen Sie das, was Ihnen am besten gefällt.',
        zh: '我们荣幸地为您提供多种冒险选择。每项冒险都有各自的距离、时长和推荐交通方式。请选择您最喜欢的一项。',
        pl: 'Mamy przyjemność zaoferować wam kilka przygód. Każda ma własną odległość, czas trwania i zalecany środek transportu. Wybierzcie tę, która najbardziej wam odpowiada.',
        pt: 'Temos o prazer de lhe oferecer várias aventuras. Cada uma tem a sua distância, duração e transporte recomendado. Escolha a que mais lhe agradar.',
        ru: 'Мы рады предложить вам несколько приключений. Каждое имеет свою дистанцию, продолжительность и рекомендуемый транспорт. Выберите то, которое вам больше всего нравится.',
        uk: 'Ми раді запропонувати вам кілька пригод. Кожна має свою відстань, тривалість та рекомендований транспорт. Оберіть ту, яка вам найбільше до вподоби.',
    },
    // 3 — Mapa vintage de la aventura
    {
        es: 'Un vistazo a su aventura al completo: paradas numeradas, ruta trazada. La ciudad entera, esperándole.',
        en: 'A glimpse of your full adventure: numbered stops, mapped route. The whole city, waiting for you.',
        fr: 'Un aperçu complet de votre aventure : arrêts numérotés, itinéraire tracé. La ville entière vous attend.',
        it: 'Uno sguardo alla vostra avventura completa: tappe numerate, percorso tracciato. L\'intera città vi aspetta.',
        nl: 'Een blik op uw volledige avontuur: genummerde haltes, uitgestippelde route. De hele stad wacht op u.',
        ja: 'あなたの冒険を一望できます：番号付きの停車地、描かれたルート。街全体があなたを待っています。',
        de: 'Ein Blick auf Ihr gesamtes Abenteuer: nummerierte Stopps, eingezeichnete Route. Die ganze Stadt wartet auf Sie.',
        zh: '纵览您的完整冒险：编号停靠点、绘制路线。整座城市，静候您的到来。',
        pl: 'Rzut oka na całą przygodę: ponumerowane przystanki, wytyczona trasa. Całe miasto czeka na was.',
        pt: 'Uma visão geral da sua aventura completa: paragens numeradas, rota traçada. A cidade inteira à sua espera.',
        ru: 'Взгляд на всё ваше приключение: пронумерованные остановки, проложенный маршрут. Весь город ждёт вас.',
        uk: 'Погляд на всю вашу пригоду: пронумеровані зупинки, прокладений маршрут. Усе місто чекає на вас.',
    },
    // 4 — Grid de todos los botones
    {
        es: 'Estos son los botones que harán posible su aventura. Los iremos descubriendo uno a uno.',
        en: 'These are the buttons that will make your adventure possible. We will discover them one by one.',
        fr: 'Voici les boutons qui rendront votre aventure possible. Nous les découvrirons un par un.',
        it: 'Questi sono i pulsanti che renderanno possibile la vostra avventura. Li scopriremo uno per uno.',
        nl: 'Dit zijn de knoppen die uw avontuur mogelijk maken. We ontdekken ze één voor één.',
        ja: 'これらのボタンがあなたの冒険を可能にします。一つずつご確認いきましょう。',
        de: 'Das sind die Schaltflächen, die Ihr Abenteuer möglich machen. Wir werden sie eine nach der anderen entdecken.',
        zh: '这些按钮将使您的冒险成为可能。我们将逐一了解它们。',
        pl: 'To są przyciski, które umożliwią waszą przygodę. Będziemy je odkrywać jeden po drugim.',
        pt: 'Estes são os botões que tornarão a sua aventura possível. Vamo-los descobrir um a um.',
        ru: 'Это кнопки, которые сделают ваше приключение возможным. Мы будем открывать их одну за другой.',
        uk: 'Це кнопки, які зроблять вашу пригоду можливою. Ми відкриватимемо їх одну за одною.',
    },
    // 5 — Botón mapa digital completo (b1)
    {
        es: 'Su ruta completa, de un solo toque. Paradas marcadas, camino claro.',
        en: 'Your full route, at a single tap. Marked stops, clear path.',
        fr: 'Votre itinéraire complet, en un seul toucher. Arrêts marqués, chemin bien défini.',
        it: 'Il vostro percorso completo, con un solo tocco. Tappe indicate, strada chiara.',
        nl: 'Uw volledige route, met één tik. Gemarkeerde haltes, duidelijk pad.',
        ja: 'ワンタッチでルート全体を表示。停車地も明確にマークされています。',
        de: 'Ihre vollständige Route auf einen Tipp. Markierte Stopps, klarer Weg.',
        zh: '一键查看完整路线。停靠点清晰标注，路径一目了然。',
        pl: 'Cała trasa jednym dotknięciem. Oznaczone przystanki, wyraźna droga.',
        pt: 'A sua rota completa, com um único toque. Paragens marcadas, caminho claro.',
        ru: 'Весь маршрут одним касанием. Остановки отмечены, путь понятен.',
        uk: 'Весь маршрут одним дотиком. Зупинки позначені, шлях зрозумілий.',
    },
    // 6 — Botón mapa vintage (b2)
    {
        es: 'El mismo mapa, pero con alma de época. Un estilo vintage que le transportará siglos atrás.',
        en: 'The same map, but with a timeless soul. A vintage style that will take you centuries back.',
        fr: 'La même carte, mais avec une âme d\'époque. Un style vintage qui vous transportera des siècles en arrière.',
        it: 'La stessa mappa, ma con un\'anima d\'epoca. Uno stile vintage che vi trasporterà indietro di secoli.',
        nl: 'Dezelfde kaart, maar met een tijdloze ziel. Een vintage stijl die u eeuwen terug in de tijd brengt.',
        ja: '同じ地図ですが、時代の魂を宿しています。ヴィンテージスタイルが何世紀も前へとあなたを誘います。',
        de: 'Dieselbe Karte, aber mit einer zeitlosen Seele. Ein Vintage-Stil, der Sie Jahrhunderte zurückversetzt.',
        zh: '同样的地图，却有着岁月的灵魂。复古风格将带您穿越数百年。',
        pl: 'Ta sama mapa, ale z duszą epoki. Styl vintage, który przeniesie was o wieki wstecz.',
        pt: 'O mesmo mapa, mas com alma de época. Um estilo vintage que o transportará séculos atrás.',
        ru: 'Та же карта, но с душой эпохи. Винтажный стиль перенесёт вас на несколько веков назад.',
        uk: 'Та сама карта, але з душею епохи. Вінтажний стиль перенесе вас на кілька століть назад.',
    },
    // 7 — Botón avanzar (b-av)
    {
        es: 'De parada en parada, la aventura avanza con usted. Este botón se activa o desactiva solo, siempre al ritmo que necesite.',
        en: 'Stop by stop, the adventure moves with you. This button activates or deactivates on its own, always at the pace you need.',
        fr: 'Arrêt après arrêt, l\'aventure avance avec vous. Ce bouton s\'active ou se désactive seul, toujours au rythme dont vous avez besoin.',
        it: 'Tappa dopo tappa, l\'avventura avanza con voi. Questo pulsante si attiva o si disattiva da solo, sempre al ritmo di cui avete bisogno.',
        nl: 'Halte na halte, het avontuur beweegt met u mee. Deze knop activeert of deactiveert zichzelf, altijd op het tempo dat u nodig heeft.',
        ja: '停車地から停車地へ、冒険はあなたと共に進みます。このボタンは必要に応じて自動的に有効または無効になります。',
        de: 'Stopp für Stopp schreitet das Abenteuer mit Ihnen voran. Diese Schaltfläche aktiviert oder deaktiviert sich selbst, immer in dem Tempo, das Sie benötigen.',
        zh: '一站接一站，冒险与您同行。此按钮会自动启用或禁用，始终按您所需的节奏。',
        pl: 'Przystanek po przystanku, przygoda postępuje razem z wami. Ten przycisk aktywuje się lub dezaktywuje sam, zawsze we właściwym rytmie.',
        pt: 'Paragem a paragem, a aventura avança consigo. Este botão ativa-se ou desativa-se sozinho, sempre ao ritmo de que necessita.',
        ru: 'Остановка за остановкой, приключение движется вместе с вами. Эта кнопка включается или выключается сама, всегда в нужном вам темпе.',
        uk: 'Зупинка за зупинкою, пригода рухається разом з вами. Ця кнопка вмикається або вимикається самостійно, завжди в потрібному вам темпі.',
    },
    // 8 — Botón imagen próxima parada (b4)
    {
        es: '¿Llegando a una nueva parada? Un vistazo a esta imagen le bastará para reconocer el lugar al instante.',
        en: 'Arriving at a new stop? One glance at this image will be enough to recognise the place instantly.',
        fr: 'Vous approchez d\'un nouvel arrêt ? Un coup d\'œil à cette image suffira pour reconnaître le lieu instantanément.',
        it: 'State arrivando a una nuova tappa? Uno sguardo a questa immagine basterà per riconoscere il posto all\'istante.',
        nl: 'Komt u bij een nieuwe halte? Eén blik op deze afbeelding is genoeg om de plek direct te herkennen.',
        ja: '新しい停車地に近づいていますか？この画像を一目見るだけで、すぐにその場所がわかります。',
        de: 'Kommen Sie zu einer neuen Haltestelle? Ein Blick auf dieses Bild reicht aus, um den Ort sofort zu erkennen.',
        zh: '即将到达新的停靠点？看一眼这张图片，您便能立即认出那个地方。',
        pl: 'Zbliżacie się do nowego przystanku? Jedno spojrzenie na ten obraz wystarczy, by natychmiast rozpoznać miejsce.',
        pt: 'A chegar a uma nova paragem? Um olhar para esta imagem chegará para reconhecer o local de imediato.',
        ru: 'Подъезжаете к новой остановке? Одного взгляда на это изображение будет достаточно, чтобы сразу узнать место.',
        uk: 'Наближаєтеся до нової зупинки? Одного погляду на це зображення вистачить, щоб відразу впізнати місце.',
    },
    // 9 — Botón vídeo / dron (b3)
    {
        es: 'Para quienes prefieren ver antes de llegar: un vídeo que le guía hasta la siguiente parada, sin perderse nada.',
        en: 'For those who prefer to see before they arrive: a video that guides you to the next stop, without missing a thing.',
        fr: 'Pour ceux qui préfèrent voir avant d\'arriver : une vidéo qui vous guide jusqu\'au prochain arrêt, sans rien manquer.',
        it: 'Per chi preferisce vedere prima di arrivare: un video che vi guida fino alla prossima tappa, senza perdersi nulla.',
        nl: 'Voor wie liever ziet voor ze aankomen: een video die u naar de volgende halte leidt, zonder iets te missen.',
        ja: '到着前に確認したい方へ：次の停車地まで何も見逃さずにご案内するビデオです。',
        de: 'Für alle, die lieber sehen, bevor sie ankommen: ein Video, das Sie zur nächsten Haltestelle führt, ohne etwas zu verpassen.',
        zh: '对于喜欢提前了解的您：一段视频将引导您前往下一个停靠点，不遗漏任何细节。',
        pl: 'Dla tych, którzy wolą zobaczyć, zanim dotrą na miejsce: film prowadzący do następnego przystanku, bez pominięcia czegokolwiek.',
        pt: 'Para quem prefere ver antes de chegar: um vídeo que o guia até à próxima paragem, sem perder nada.',
        ru: 'Для тех, кто предпочитает видеть заранее: видео, которое проведёт вас к следующей остановке, ничего не упустив.',
        uk: 'Для тих, хто вважає за краще побачити перед прибуттям: відео, яке проведе вас до наступної зупинки, не пропустивши нічого.',
    },
    // 10 — Botón audio principal
    {
        es: 'Su aventura habla. Audioguiada y geolocalizada, cada parada tiene su propia historia. Escúchela cuantas veces quiera, sin prisas.',
        en: 'Your adventure speaks. Audio-guided and geolocated, each stop has its own story. Listen to it as many times as you like, at your own pace.',
        fr: 'Votre aventure parle. Audioguide et géolocalisée, chaque arrêt a sa propre histoire. Écoutez-la autant de fois que vous le souhaitez, sans vous presser.',
        it: 'La vostra avventura parla. Audioguida e geolocalizzata, ogni tappa ha la sua storia. Ascoltatela tutte le volte che volete, senza fretta.',
        nl: 'Uw avontuur spreekt. Audiogeleid en geogelokaliseerd, elke halte heeft zijn eigen verhaal. Luister er zo vaak als u wilt naar, zonder haast.',
        ja: 'あなたの冒険が語りかけます。音声ガイドと位置情報機能を搭載し、各停車地に独自のストーリーがあります。急がずに、何度でもお聴きください。',
        de: 'Ihr Abenteuer spricht. Audiogeführt und geolocated hat jede Haltestelle ihre eigene Geschichte. Hören Sie sie so oft wie Sie möchten, ohne Eile.',
        zh: '您的冒险开口说话了。有声导览与定位功能结合，每个停靠点都有自己的故事。请随时聆听，不必着急。',
        pl: 'Wasza przygoda przemawia. Przewodnik audio i geolokalizacja sprawiają, że każdy przystanek ma swoją historię. Słuchajcie jej tyle razy, ile chcecie, bez pośpiechu.',
        pt: 'A sua aventura fala. Audioguiada e geolocalizada, cada paragem tem a sua própria história. Ouça-a quantas vezes quiser, sem pressa.',
        ru: 'Ваше приключение говорит. Аудиогид и геолокация — у каждой остановки своя история. Слушайте её столько раз, сколько захотите, не торопясь.',
        uk: 'Ваша пригода говорить. Аудіогід та геолокація — кожна зупинка має свою власну історію. Слухайте її скільки завгодно разів, не поспішаючи.',
    },
    // 11 — Reto puzzle
    {
        es: 'Cuando este botón se habilite, la aventura se complica… ¡en el buen sentido! Puzzles, acertijos y pruebas le esperan.',
        en: 'When this button becomes available, the adventure gets more interesting… in the best way! Puzzles, riddles and challenges await you.',
        fr: 'Quand ce bouton sera disponible, l\'aventure se complique… dans le bon sens ! Puzzles, énigmes et épreuves vous attendent.',
        it: 'Quando questo pulsante sarà disponibile, l\'avventura si complica… nel senso buono! Puzzle, enigmi e prove vi aspettano.',
        nl: 'Wanneer deze knop beschikbaar wordt, wordt het avontuur uitdagender… op de goede manier! Puzzels, raadsels en proeven wachten op u.',
        ja: 'このボタンが使えるようになると、冒険はより面白くなります…良い意味で！パズル、なぞなぞ、そして試練があなたを待っています。',
        de: 'Wenn diese Schaltfläche verfügbar wird, wird das Abenteuer anspruchsvoller… im besten Sinne! Puzzles, Rätsel und Aufgaben warten auf Sie.',
        zh: '当此按钮可用时，冒险变得更有趣……是好的那种！拼图、谜语和挑战等待着您。',
        pl: 'Gdy ten przycisk stanie się dostępny, przygoda się komplikuje… w dobrym sensie! Czekają na was puzzle, zagadki i próby.',
        pt: 'Quando este botão ficar disponível, a aventura complica-se… no bom sentido! Puzzles, adivinhas e provas esperam por si.',
        ru: 'Когда эта кнопка станет доступна, приключение усложняется… в лучшем смысле! Головоломки, загадки и испытания ждут вас.',
        uk: 'Коли ця кнопка стане доступною, пригода ускладнюється… в найкращому сенсі! Пазли, загадки та випробування чекають на вас.',
    },
    // 12 — Reto preguntas MCQ
    {
        es: '¿Y si las preguntas no fueran tan simples? Opción múltiple con trampa incluida: puede haber más de una respuesta correcta.',
        en: 'What if the questions were not so simple? Multiple choice with a twist: there may be more than one correct answer.',
        fr: 'Et si les questions n\'étaient pas si simples ? Choix multiples avec une surprise : il peut y avoir plus d\'une bonne réponse.',
        it: 'E se le domande non fossero così semplici? Opzione multipla con sorpresa inclusa: può esserci più di una risposta corretta.',
        nl: 'Wat als de vragen niet zo eenvoudig zijn? Meerkeuze met een addertje onder het gras: er kan meer dan één correct antwoord zijn.',
        ja: 'もし質問がそれほど簡単でなかったら？仕掛けのある複数選択：正しい答えが複数ある場合があります。',
        de: 'Was, wenn die Fragen nicht so einfach wären? Multiple Choice mit Überraschung: Es könnte mehr als eine richtige Antwort geben.',
        zh: '如果问题没那么简单呢？附带陷阱的多选题：可能有不止一个正确答案。',
        pl: 'A gdyby pytania nie były takie proste? Wielokrotny wybór z niespodzianką: może być więcej niż jedna poprawna odpowiedź.',
        pt: 'E se as perguntas não fossem assim tão simples? Opção múltipla com armadilha incluída: pode haver mais do que uma resposta correta.',
        ru: 'А что, если вопросы окажутся не такими простыми? Множественный выбор с сюрпризом: правильных ответов может быть несколько.',
        uk: 'А що, якщо запитання виявляться не такими простими? Множинний вибір із сюрпризом: правильних відповідей може бути кілька.',
    },
    // 13 — Pausa / cámara / lugar recomendado
    {
        es: 'Valencia merece ser saboreada. Fotografíe, descanse, explore el lugar recomendado… Su aventura no tiene prisa. Tampoco usted.',
        en: 'Valencia deserves to be savoured. Take photos, rest, explore the recommended spot… Your adventure is in no hurry. Neither are you.',
        fr: 'Valence mérite d\'être savourée. Photographiez, reposez-vous, explorez l\'endroit recommandé… Votre aventure n\'est pas pressée. Vous non plus.',
        it: 'Valencia merita di essere assaporata. Fotografate, riposatevi, esplorate il posto consigliato… La vostra avventura non ha fretta. Neanche voi.',
        nl: 'Valencia verdient het om te worden geproefd. Fotografeer, rust uit, verken de aanbevolen plek… Uw avontuur heeft geen haast. U ook niet.',
        ja: 'バレンシアは味わう価値があります。写真を撮り、休息し、おすすめの場所を探索してください…あなたの冒険は急ぎません。あなたも同じです。',
        de: 'Valencia verdient es, ausgekostet zu werden. Fotografieren Sie, ruhen Sie sich aus, erkunden Sie den empfohlenen Ort… Ihr Abenteuer hat es nicht eilig. Sie auch nicht.',
        zh: '瓦伦西亚值得细细品味。拍照、休息、探索推荐的地方……您的冒险不着急，您也不必着急。',
        pl: 'Walencja zasługuje na to, żeby ją smakować. Fotografujcie, odpoczywajcie, odkrywajcie polecane miejsce… Wasza przygoda się nie spieszy. Wy też nie.',
        pt: 'Valência merece ser saboreada. Tire fotos, descanse, explore o local recomendado… A sua aventura não tem pressa. Nem você.',
        ru: 'Валенсия заслуживает того, чтобы её смаковали. Фотографируйте, отдыхайте, исследуйте рекомендованное место… Ваше приключение не торопится. И вы тоже.',
        uk: 'Валенсія заслуговує на те, щоб нею насолоджуватися. Фотографуйте, відпочивайте, досліджуйте рекомендоване місце… Ваша пригода не поспішає. І ви теж.',
    },
    // 14 — Fuera de ruta / botón ubicación (b6)
    {
        es: '¿Se ha despistado? No pasa nada. Si se aleja de la ruta, este botón se activará solo para devolverle al camino.',
        en: 'Lost your bearings? No worries. If you stray from the route, this button will activate on its own to guide you back on track.',
        fr: 'Vous vous êtes perdu ? Ce n\'est pas grave. Si vous vous éloignez de l\'itinéraire, ce bouton s\'activera seul pour vous remettre sur la bonne voie.',
        it: 'Vi siete persi? Non preoccupatevi. Se vi allontanate dal percorso, questo pulsante si attiverà da solo per riportarvi sulla strada giusta.',
        nl: 'De weg kwijtgeraakt? Geen probleem. Als u van de route afdwaalt, zal deze knop zichzelf activeren om u terug op weg te helpen.',
        ja: '迷ってしまいましたか？大丈夫です。ルートから外れると、このボタンが自動的に有効になり、道に戻るよう案内します。',
        de: 'Den Weg verloren? Kein Problem. Wenn Sie von der Route abweichen, aktiviert sich diese Schaltfläche von selbst, um Sie zurückzuführen.',
        zh: '迷路了？没关系。如果您偏离路线，此按钮将自动启用，带您重回正轨。',
        pl: 'Zgubiliście się? Nic się nie stało. Jeśli odejdziecie od trasy, ten przycisk aktywuje się sam, by prowadzić was z powrotem na właściwą drogę.',
        pt: 'Perdeu-se? Não há problema. Se se afastar da rota, este botão ativar-se-á sozinho para o guiar de volta ao caminho.',
        ru: 'Заблудились? Ничего страшного. Если вы отклонитесь от маршрута, эта кнопка активируется сама, чтобы вернуть вас на путь.',
        uk: 'Загубилися? Нічого страшного. Якщо ви відхилитеся від маршруту, ця кнопка активується сама, щоб повернути вас на шлях.',
    },
    // 15 — Caballero regresa caminando (escena visual, sin bocadillo)
    null,
    // 16 — GPS error / caballero durmiendo / descanso largo
    {
        es: 'Las grandes aventuras también tienen sus pausas. Si necesita descansar y continuar más tarde, este botón le llevará de vuelta al punto exacto donde lo dejó.',
        en: 'Great adventures also have their pauses. If you need to rest and continue later, this button will take you back to the exact point where you left off.',
        fr: 'Les grandes aventures ont aussi leurs pauses. Si vous avez besoin de vous reposer et de continuer plus tard, ce bouton vous ramènera exactement là où vous vous étiez arrêté.',
        it: 'Anche le grandi avventure hanno le loro pause. Se avete bisogno di riposarvi e continuare più tardi, questo pulsante vi riporterà esattamente al punto in cui vi eravate fermati.',
        nl: 'Grote avonturen kennen ook hun pauzes. Als u wilt rusten en later verder wilt gaan, brengt deze knop u terug naar precies het punt waar u was gebleven.',
        ja: '大きな冒険にも休憩があります。休んで後で続けたい場合、このボタンがやめた地点へ正確に戻してくれます。',
        de: 'Auch große Abenteuer haben ihre Pausen. Wenn Sie sich ausruhen und später weitermachen möchten, bringt diese Schaltfläche Sie genau dorthin zurück, wo Sie aufgehört haben.',
        zh: '伟大的冒险也有它的暂停。如果您需要休息，稍后再继续，此按钮将带您返回到您离开的确切位置。',
        pl: 'Wielkie przygody też mają swoje przerwy. Jeśli potrzebujecie odpocząć i kontynuować później, ten przycisk zabierze was dokładnie do punktu, w którym skończyliście.',
        pt: 'As grandes aventuras também têm as suas pausas. Se precisar de descansar e continuar mais tarde, este botão levará de volta ao ponto exato onde ficou.',
        ru: 'Великие приключения тоже имеют свои паузы. Если вам нужно отдохнуть и продолжить позже, эта кнопка вернёт вас именно туда, где вы остановились.',
        uk: 'Великі пригоди теж мають свої паузи. Якщо вам потрібно відпочити і продовжити пізніше, ця кнопка поверне вас саме до того місця, де ви зупинилися.',
    },
    // 17 — Botón temporizador
    {
        es: 'Cada aventura tiene un tiempo estimado de finalización. Aquí puede controlar el tiempo transcurrido en todo momento.',
        en: 'Each adventure has an estimated completion time. Here you can check the elapsed time whenever you wish.',
        fr: 'Chaque aventure a un temps estimé de réalisation. Ici, vous pouvez vérifier le temps écoulé quand vous le souhaitez.',
        it: 'Ogni avventura ha un tempo stimato di completamento. Qui potete controllare il tempo trascorso quando volete.',
        nl: 'Elk avontuur heeft een geschatte voltooiingstijd. Hier kunt u de verstreken tijd controleren wanneer u maar wilt.',
        ja: '各冒険には推定完了時間があります。ここでいつでも経過時間を確認できます。',
        de: 'Jedes Abenteuer hat eine geschätzte Abschlusszeit. Hier können Sie die verstrichene Zeit jederzeit überprüfen.',
        zh: '每项冒险都有预计完成时间。您可以随时在这里查看已用时间。',
        pl: 'Każda przygoda ma szacowany czas ukończenia. Tutaj możecie sprawdzić upłynięty czas, kiedy tylko chcecie.',
        pt: 'Cada aventura tem um tempo estimado de conclusão. Aqui pode verificar o tempo decorrido sempre que quiser.',
        ru: 'Каждое приключение имеет расчётное время завершения. Здесь вы можете проверить прошедшее время в любой момент.',
        uk: 'Кожна пригода має розрахунковий час завершення. Тут ви можете перевірити минулий час будь-коли.',
    },
    // 18 — Asistente / preguntas frecuentes
    {
        es: '¿Alguna pregunta? Tenemos respuestas. Pulse aquí para acceder a nuestro listado de preguntas frecuentes.',
        en: 'Any questions? We have answers. Tap here to access our list of frequently asked questions.',
        fr: 'Des questions ? Nous avons des réponses. Appuyez ici pour accéder à notre liste de questions fréquentes.',
        it: 'Domande? Abbiamo le risposte. Premete qui per accedere al nostro elenco di domande frequenti.',
        nl: 'Vragen? Wij hebben antwoorden. Druk hier om toegang te krijgen tot onze lijst met veelgestelde vragen.',
        ja: 'ご質問はありますか？回答があります。こちらをタップして、よくある質問の一覧にアクセスしてください。',
        de: 'Fragen? Wir haben Antworten. Drücken Sie hier, um auf unsere Liste häufig gestellter Fragen zuzugreifen.',
        zh: '有任何问题？我们有答案。点击此处访问我们的常见问题列表。',
        pl: 'Macie pytania? Mamy odpowiedzi. Naciśnijcie tutaj, aby uzyskać dostęp do naszej listy często zadawanych pytań.',
        pt: 'Alguma pergunta? Temos respostas. Prima aqui para aceder à nossa lista de perguntas frequentes.',
        ru: 'Есть вопросы? У нас есть ответы. Нажмите здесь для доступа к списку часто задаваемых вопросов.',
        uk: 'Є запитання? Ми маємо відповіді. Натисніть тут, щоб отримати доступ до списку поширених запитань.',
    },
    // 19 — Pantalla final
    {
        es: 'Todo preparado. Valencia le espera con sus monumentos, sus secretos y sus retos. ¡Que comience la aventura!',
        en: 'All set. Valencia awaits you with its monuments, its secrets and its challenges. Let the adventure begin!',
        fr: 'Tout est prêt. Valence vous attend avec ses monuments, ses secrets et ses défis. Que l\'aventure commence !',
        it: 'Tutto pronto. Valencia vi aspetta con i suoi monumenti, i suoi segreti e le sue sfide. Che l\'avventura abbia inizio!',
        nl: 'Alles klaar. Valencia wacht op u met zijn monumenten, zijn geheimen en zijn uitdagingen. Laat het avontuur beginnen!',
        ja: '準備完了です。バレンシアがその名所、秘密、そして挑戦とともにあなたを待っています。冒険を始めましょう！',
        de: 'Alles bereit. Valencia wartet mit seinen Denkmälern, Geheimnissen und Herausforderungen auf Sie. Das Abenteuer beginnt!',
        zh: '一切就绪。瓦伦西亚以其名胜古迹、秘密与挑战等待着您。让冒险开始吧！',
        pl: 'Wszystko gotowe. Walencja czeka na was ze swoimi zabytkami, tajemnicami i wyzwaniami. Niech przygoda się rozpocznie!',
        pt: 'Tudo pronto. Valência está à sua espera com os seus monumentos, os seus segredos e os seus desafios. Que a aventura comece!',
        ru: 'Всё готово. Валенсия ждёт вас со своими памятниками, секретами и испытаниями. Пусть приключение начнётся!',
        uk: 'Все готово. Валенсія чекає на вас зі своїми пам\'ятками, таємницями та випробуваннями. Нехай пригода розпочнеться!',
    },
];

export const PLACEHOLDER_RESPUESTA_TEXTO = {
    es: 'Escriba su respuesta aquí...',
    en: 'Write your answer here...',
    fr: 'Écrivez votre réponse ici...',
    it: 'Scrivi qui la tua risposta...',
    nl: 'Schrijf hier je antwoord...',
    de: 'Schreiben Sie hier Ihre Antwort...',
    ja: 'ここに回答を入力してください...',
    zh: '请在此输入您的答案...',
    pl: 'Wpisz tutaj swoją odpowiedź...',
    pt: 'Escreva a sua resposta aqui...',
    ru: 'Напишите ваш ответ здесь...',
    uk: 'Напишіть свою відповідь тут...'
};
