import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "151": "<p>Una volta deciso di riprendere la sua avventura, si posizioni di nuovo al centro di questa piazza guardando la facciata ad archi ciechi della chiesa.</p>",
  "152": "<p>Oggi quel pannello ceramico all'altezza del primo piano illustra il miracolo.</p>",
  "153": "<p>Il giorno 18 si celebra \"La nit del foc\" (notte del fuoco): uno spettacolo pirotecnico straordinario che apre la strada all'ultimo giorno in cui i monumenti falleros saranno esposti.</p>\n\n<p>Il giorno 19, giorno della \"cremà\" (momento in cui bruciano i monumenti falleros), coincide sempre con la festività di San Giuseppe, Patrono di Valencia.</p>",
  "154": `<p>La <strong>Lonja de la Seda</strong> è, per eccellenza, il monumento del Siglo de Oro valenciano e si trova a pochi passi dalla plaza redonda.</p>\n\n<p>Il monumento fu costruito tra il 1482 e il 1497 per ospitare il Wall Street della Valencia del XV secolo. Questo centro finanziario era necessario in quanto la famosa Via della Seta attraversava la città arricchendola nel suo percorso.</p>\n\n<p>${LOGO} le fornirà informazioni dettagliate su quest'area nella sua Avventura numero 1.</p>`,
  "155": "<p>Il suo prossimo obiettivo è il monumento del Siglo de Oro valenciano. Un Wall Street del XV secolo.</p>\n\n<p>La <strong>Lonja</strong> fu costruita tra il 1482 e il 1497 e fu dichiarata Patrimonio dell'Umanità nel 1996. Sulla sua mappa corrisponde al numero <mark>16</mark>.</p>",
  "156": "<p>Segua la sua mappa e continui fino alla fine della strada, dove si apre una piazza conosciuta come <strong>Plaza de la Virgen</strong>. Una delle più iconiche della città.</p>",
  "157": "<p>Spicca, nella sua parte più alta, una banderuola dedicata a questo santo famoso per il suo martirio, uno dei più antichi documentati.</p>",
  "158": "<p>Si avvicini, se vuole, alla <strong>Chiesa di San Lorenzo</strong> che corrisponde sulla sua mappa al numero <mark>4</mark>.</p>",
  "159": "<p>Continui, se vuole, fino alla fine della strada, dove si apre la famosa <strong>Plaza de la Virgen</strong>.</p>",
  "160": "<p>La sua avventura continua in questo stesso punto, con la fontana e la piazza di fronte a lei.</p>",
  "161": "<p>Ricordi di posizionarsi con la fontana e la piazza di fronte a lei.</p>",
  "162": "<p>La sua avventura continua dietro l'angolo, da dove si può vedere la facciata principale del <strong>Miguelete</strong> e anche la porta Barocca della <strong>Cattedrale di Valencia</strong>; la terza ad essere costruita.</p>",
  "163": "<p>A questo punto della sua avventura avrà già avuto il piacere di vedere le nostre regine in abito di gala. I vestiti da Fallera mantengono viva l'artigianato della seta su telai manuali.</p>",
  "164": "<p>In questa avventura commenteremo brevemente ogni parte. La prima cosa che colpisce sono le acconciature tradizionali delle falleras. Senza dubbio, la più nota delle acconciature di Spagna.</p>\n\n<p>Lo chignon da fallera risale al XVIII secolo. Le donne raccoglievano i capelli in una coda e li dividevano in otto ciocche che venivano \"intrecciate\" a forma di otto attorno a uno o due aghi spessi. Per finire, due trecce circondavano la raccolta centrale.</p>\n\n<p>Gli aghi che tengono lo chignon sono composti da due parti: la spada e il cannone, in valenciano \"Espasa\" e \"Canó\".</p>\n\n<p>Per completare l'acconciatura si aggiungono due chignons laterali all'altezza delle orecchie, fissati con due forcine.</p>",
  "165": "<p>L'acconciatura tipica da fallera è completata da un pettine posteriore realizzato a mano in ottone argentato o dorato e due repliche del pettine principale che si collocano nei chignons laterali.</p>",
  "166": "<p>Il vestito da fallera, quello delle regine e protagoniste di queste feste popolari, è composto da:</p>\n\n<p>La Gonna: Normalmente con motivi floreali, è confezionata in seta e fili d'oro e d'argento. Per il vestito si utilizzano dai 10 ai 15 metri di seta di diversi colori.</p>\n\n<p>Il Corpetto: Parte superiore del vestito, realizzato nello stesso tessuto della gonna, accompagnato da mantellina. Lo stile della manica varia a seconda dell'ispirazione del secolo del vestito.</p>\n\n<p>La mantellina: in materiali come tulle e seta, è ricamata con filo d'oro o d'argento formando splendidi disegni; si compone di due parti: quella superiore, che si porta sul corpetto, e il grembiule.</p>\n\n<p>La Camicia e Le sottogonne: Di solito sono coordinate. Sono la biancheria intima, accompagnata da una crinolina per dare volume alla gonna.</p>\n\n<p>Come ogni abito da gala, è completato da orecchini d'oro o d'argento e \"La Joia\", che è il decoro centrale che si pone nella parte superiore del corpetto.</p>",
  "167": "<p>Il Fallero, al contrario, ha diversi costumi. Parleremo di quello che consideriamo più tradizionale: il costume da Saragüell, riconoscibile per il fazzoletto che copre la testa chiamato Mocador.</p>\n\n<p>Il costume da Saragüell è composto da:</p>\n\n<p>Camicia: normalmente bianca. Jupetí o gilet: con motivi simili ai vestiti da fallera. Faixi: fascia che cinge la vita. Manta: tessuto a righe che si pone sulla spalla. Calces: normalmente bianchi. Espardenyes: calzature realizzate in sparto e cotone tipiche della regione.</p>\n\n<p>Come avrà potuto constatare, la maggior parte delle persone in questo periodo indossa il tipico Blusón fallero e Pañuelo al collo:</p>\n\n<p>Nel XVIII secolo emerse una tendenza di camicie ampie, sia nel tronco che nelle maniche; aperte sul davanti e che di solito si allungavano poco oltre la vita, chiamate blusones. I blusones nel corso del tempo hanno subito numerose variazioni e hanno quasi rischiato di estinguersi, ma a Valencia si conserva la tradizione di indossarli durante le Fallas, poiché proteggono i vestiti che indossiamo sotto da ustioni accidentali e fungono da grembiule. Il fazzoletto, a sua volta, serve a coprire il collo e il viso nei luoghi con molto fumo.</p>",
  "168": "<p>Il suo prossimo obiettivo si trova al termine della piazza alla sua destra.</p>",
  "169": "<p>Ha finito di attraversare la piazza?</p>",
  "170": "<p>Si posizioni con la Plaza de la Reina alle spalle e Santa Catalina alla sua destra; proprio di fronte si apre la Calle de San Vicente Mártir, che mantiene il suo tracciato imperturbabile dal IV secolo dopo Cristo. <i>Alla ricerca del tesoro</i> percorrerà una delle strade più antiche di Valencia.</p>\n\n<p>Pochi metri più avanti si aprono due piazze: una a sinistra e una a destra; inizieremo dalla piazza di sinistra. Troverà il prossimo indizio nella famosa <strong>Plaza del Ayuntamiento</strong>.</p>",
  "171": "<p>La <strong>Plaza del Ayuntamiento</strong> si trasforma ogni anno in uno spazio in cui dall'1 al 19 marzo alle due del pomeriggio ha luogo uno spettacolo per i sensi: un appuntamento immancabile in cui i presenti godono della sinfonia del rumore; si sentono i masclets, si vede il fuoco e il fumo e si annusa la polvere da sparo, ma soprattutto si sente la vibrazione che sale dalle gambe e percorre tutto il corpo.</p>",
  "172": "<p>Al centro della piazza si apre uno spazio libero protetto da una recinzione di grande altezza, che garantisce lo spazio per la Mascletà: uno sparo pirotecnico che forma una composizione ritmica e molto rumorosa.</p>\n\n<p>Al contrario dei fuochi d'artificio che cercano la stimolazione visiva, la Mascletà vuole sorprendere lo spettatore con un'armonia musicale generata attraverso una successione di esplosioni ritmiche.</p>",
  "173": "<p>La Mascletà prende il nome dai famosi Masclets (petardi di grande potenza sonora). La denominazione \"Masclet\" deriva dall'aggettivo \"mascle\", che in valenciano significa maschio e anche valoroso.</p>\n\n<p>I \"mascles\" della fine del XVIII secolo si tiravano petardi ai piedi e scommettevano per vedere chi resisteva di più con i petardi che esplodevano e li fermavano con i piedi. Chi ne resisteva di più era il \"més mascle\" (il più valoroso) e da lì il nome di questo evento pirotecnico.</p>\n\n<p>Col tempo iniziarono a legare i masclets con corde e a unirli tra loro tramite micce, in modo che potessero essere sparati tutti di seguito. Nei \"Trams de Tro\" (tratti di tuono) era molto comune che gli uomini corressero sotto i Masclets come se accompagnassero il fuoco, partecipando e mantenendo quella fama di \"mascles\" (valorosi) che li precedeva.</p>",
  "174": "<p>La prima Mascletà fu inserita nel programma ufficiale nell'anno 1945. In quello stesso anno si effettuò anche la prima offerta di fiori in modo ufficiale.</p>",
  "175": "<p>In questo breve evento è fondamentale che la forza delle esplosioni aumenti progressivamente con un finale apoteosico, avendo come obiettivo stimolare il corpo attraverso i ritmi dei Masclets.</p>",
  "176": "<p>Una Mascletà comprende solitamente almeno queste parti:</p>",
  "177": "<p>Inizio: insieme di effetti sia sonori che visivi con cui inizia lo spettacolo.</p>",
  "178": "<p>Il corpo: è la parte centrale della Mascletà, deve crescere in intensità e volume sonoro.</p>",
  "179": "<p>Parte aerea: scarica di tuoni aerei di maggiore intensità, accompagnata da colori.</p>",
  "180": "<p>Terratrèmol (terremoto): parte in cui i Masclets di maggiore potenza esplodono ad alta velocità.</p>",
  "181": "<p>Le Fallas, feste del fuoco per eccellenza, cariche di colore e dettagli spettacolari, sono rimaste barocche da secoli.</p>\n\n<p>Dopo aver approfondito lo studio del controllo della chimica dei componenti esplosivi, Valencia ha continuato a sperimentare un miglioramento continuo fino a evolversi nella Mascletà attuale.</p>\n\n<p>Per motivi di sicurezza, attualmente il limite di polvere da sparo è stabilito in 120 chilogrammi per Mascletà.</p>\n\n<p>I valenciani distinguono l'armonia musicale e criticano ogni Mascletà applaudendo o fischiando l'artista.</p>",
  "182": "<p>È vero che i valenciani sono originali e che questo è un lavoro che richiede un intero anno di realizzazione.</p>",
  "183": "<p>Come nasce il monumento nel nostro secolo?</p>",
  "184": "<p>Ogni anno, in ogni casal fallero si concepisce un'idea iniziale di come sarà il proprio monumento fallero. A seguito, l'idea viene riassunta in uno schizzo o disegno che deve essere approvato affinché l'artista realizzi una miniatura in 3D in argilla.</p>\n\n<p>Da quel momento, la falla inizia a svilupparsi come qualcosa di vivente che richiede cura e totale dedizione. Nel laboratorio, la realizzazione del monumento fallero basata sul modello iniziale viene sezionata come un puzzle; si avvia la modellazione dei \"Ninots\", che sono le figure singole che completano l'insieme e che dovranno essere assemblate con totale precisione nel loro posto corrispondente al momento della \"Plantà\".</p>\n\n<p>Una giuria selezionerà, tra tutte le partecipanti, le migliori Fallas e queste verranno premiate.</p>\n\n<p>Ogni anno una figura e soltanto una si salverà dal fuoco; a questa si dà il nome di \"Ninot indultat\" (il modello graziato).</p>\n\n<p>Nel museo fallero è possibile vedere i Ninots che sono stati salvati, nonché l'evoluzione della nostra festività.</p>",
  "185": "<p>Le Fallas del XXI secolo riproducono scene di fatti sociali censurabili, ironia, critica sociale e satira in cui si caricaturizza la vita sociale e politica, sempre con senso dell'umorismo.</p>\n\n<p>La popolarità di queste feste è molto diffusa, essendo celebrate oggi in più di 88 comuni della Comunità Valenciana.</p>",
  "186": "<p>È un buon momento per continuare la sua Avventura? Ricordi che il tasto pausa può usarlo a suo piacimento e premerlo quando lo riterrà opportuno. Poi prema semplicemente avvia e continui a risolvere le nostre sfide mentre scopre la città.</p>",
  "187": "<p>Si posizioni con la fontana alle spalle e la piazza di fronte per continuare <i>alla ricerca del tesoro</i>.</p>",
  "188": "<p>Lasciando l'<strong>Edificio del Ayuntamiento</strong> alle spalle, dall'altro lato della piazza, emerge un edificio che spicca per la sua grande torre.</p>\n\n<p>Si avvicini, se vuole, all'edificio che corrisponde sulla sua mappa al numero <mark>13</mark>.</p>",
  "189": "<p>Osservi la sua mappa del tesoro. Come indica, la sua Avventura continua nell'altra piazza storica che abbiamo menzionato in precedenza.</p>\n\n<p>Per arrivare lì, si posizioni con l'<strong>Edificio del Ayuntamiento</strong> alla sua sinistra e torni fino alla famosa Calle San Vicente Mártir. A soli 150 metri, proprio nella piazza successiva, monumenti di epoche diverse si fondono nel presente diventando parte della nostra vita.</p>\n\n<p>La sua caccia al tesoro la conduce a iniziare dall'edificio monumentale sulla sinistra.</p>\n\n<p>Il <strong>Mercado Central</strong> corrisponde al numero <mark>15</mark> sulla sua mappa.</p>\n\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "190": `<p>Se si trova in orario di visita, ${LOGO} la invita a premere pausa ed entrare a scoprire la gastronomia locale che offre questo meraviglioso spazio. Questo è un posto perfetto per scattare alcune foto della sua Avventura, riprendendola da questo stesso punto, quando lo riterrà opportuno.</p>`,
  "191": "<p>La parola falla deriva dal valenciano medievale, poiché era la parola che denominava le torce che venivano poste in cima alle torri di guardia, lungo i cammini o per illuminare una festa. In seguito la parola Falla fu utilizzata per riferirsi ai falò e all'illuminazione che venivano accesi alla vigilia delle feste corrispondenti.</p>",
  "192": "<p>A questo punto è possibile che abbia già sentito qualcuna delle più di 300 bande musicali che le commissioni falleras assumono per accompagnarle a qualsiasi evento fallero.</p>\n\n<p>La cultura musicale è molto radicata poiché è un elemento molto importante per le feste popolari. Nelle Fallas non si sentono solo bande musicali; ci sono anche gruppi formati da dulzainas e tamboriles, strumenti a fiato e a percussione che si distinguono sulle altre bande.</p>",
  "193": "<p>Le dulzainas e i tamboriles, o come ci piace chiamarli in valenciano Dolçaina i Tabalet, sono strumenti tradizionali che fanno parte della colonna sonora delle nostre audioguide.</p>",
  "194": "<p>Al calar della notte la musica è anch'essa importante, poiché si celebrano feste danzanti con musica dal vivo e le tipiche \"discomóviles\", che si possono ascoltare in diversi quartieri della città e sono aperte a chiunque voglia godersele.</p>",
  "195": "<p>E se pensa che sia ora di andare a dormire, fatelo dopo aver gustato dei bunyols de carabassa con la cioccolata mentre osservate il curioso modo che hanno i falleros di svegliare gli altri vicini lanciando per terra dei petardi che esplodono al momento dell'impatto con il suolo.</p>",
  "196": "<p>C'è chi continua a credere che le vere origini di questa celebrazione (le Fallas) risiedano negli antichi rituali quando si celebrava l'equinozio di primavera, momento dell'anno in cui il giorno dura le stesse ore della notte.</p>\n\n<p>Il 21 marzo è una data segnalata da diverse culture millenarie come quella di un grande potere energetico. Data che segna il ritorno di Persefone dall'Ade, ossia del fiorire e della vita.</p>\n\n<p>Come tante altre feste pagane, la Chiesa Cattolica, ritenendosi incapace di eradicarla, la convertì al Cristianesimo celebrando il giorno di San Giuseppe. Anche così, durante il XIX secolo ci furono occasioni in cui le Fallas furono proibite per il loro carattere satirico diretto verso le autorità del momento.</p>",
  "197": "<p>Si posizioni con la porta di accesso alla <strong>Lonja</strong> di fronte a lei.</p>",
  "198": "<p>Lasciando questa piazza alla sua destra, la mappa del Tesoro le indica di continuare per la strada che ha di fronte. Non metta in pausa questa audioguida e osservi alla sua destra mentre percorre la strada.</p>",
  "199": "<p>Segua la sua mappa del tesoro; durante il tragitto, alla sua destra, emerge la prima fontana pubblica di acqua potabile che ci fu in città.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "200": `<p>Benvenuti! Da ${LOGO}, vi diamo il benvenuto. Innanzitutto vogliamo ringraziarvi per aver scelto questa avventura, in cui vi imbarcherete attraverso il tempo, dall'epoca romana alla Valencia del XXI secolo, una città moderna, piena di luce e colore. <i>alla ricerca del tesoro</i> è un'attività all'aperto, autogestita, interattiva e didattica, ideale da godere individualmente o in gruppo. Vi incoraggiamo anche a scoprire la cultura e la gastronomia valenciana al vostro ritmo, semplicemente premendo il tasto pausa.</p>`,
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
