import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "659": `<p>Admire o Palácio de Justiça.</p>\n\n<p>A sua atual denominação é a de Tribunal Superior de Justiça da Comunitat Valenciana.</p>\n\n<p>O grandioso edifício que vemos hoje em dia data de 1758, último ano do reinado de Carlos terceiro.</p>\n\n<p>O edifício ocupa um grande quarteirão retangular, as suas fachadas estão compostas por muros de tijolo à vista entre pilastras de pedra e varandas retas e curvas no primeiro piso.</p>\n\n<p>Em cima, a cornija com balaústres, adornos de tochas e hornacinas vazias mostra o gosto barroco.</p>\n\n<p>As obras foram iniciadas pelo académico valenciano Felipe Rubio Mulet, mas este faleceu antes de a ver acabada, foi o seu cunhado quem acabou a obra em 1802.</p>\n\n<p>Inicialmente, este edifício foi construído como Alfândega.</p>\n\n<p>Era o local por onde se canalizava todo o comércio proveniente do mar e fazia de Valencia um dos centros económicos do séc. XVIII.</p>\n\n<p>Embora este espaço remonte ainda mais atrás no tempo, antigas crónicas de 1626 já mencionam uma primeira alfândega que estava situada neste mesmo local, junto às muralhas da cidade e da antiga porta da cidade chamada "Puerta de la Mar".</p>`,
  "660": `<p>Com o edifício às suas costas, observe o traçado do seu mapa do tesouro que lhe indica que continue a ciclovia em direção a um imponente edifício branco de construção mais moderna que fica à mão esquerda.</p>\n\n<p>Conhecido popularmente como "Centro Cultural Bancaja": este centro compõe-se de dois edifícios que foram reestruturados no seu interior durante os anos 80 para a função que agora cumpre.</p>\n\n<p>Centre a sua atenção no edifício mais monumental que precede o branco.</p>`,
  "661": `<p>Desde a sua reabilitação, juntamente com a do edifício anexo, dedica-se inteiramente a fins culturais e escritórios próprios da Entidade.</p>\n\n<p>Construído entre 1932 e 1934 sobre o solar de um antigo palácio de estilo castiço e influências neobarrocas; o edifício consta de três corpos e terraço.</p>\n\n<p>A porta de entrada com verga reta, que faz chanfro, está decorada com guirlandas de flores e frutos finamente talhados e realizados em pedra.</p>\n\n<p>As fachadas são de pedra na zona inferior e superior, enquanto que na central predomina a terracota de cor vermelha; materiais resistentes à passagem do tempo e de manutenção muito baixa, os quais, por sua vez, têm boas propriedades de isolamento acústico.</p>\n\n<p>Nos anos 1936 a 37, enquanto Valencia foi capital da República Espanhola, o edifício utilizou-se como Ministério de Propaganda.</p>`,
  "662": "<p>Nesta fachada há um relógio. Que horas marca?</p>",
  "663": "<p>O edifício anexo, que se caracteriza pela sua cor branca, pode ver-se na totalidade continuando a sua fachada até dobrar a esquina; dirija-se a esse ponto para continuar com a sua Aventura.</p>",
  "664": `<p>Construído em 1891, acolhe as diferentes dependências do Centro Cultural e as exposições que periodicamente realiza.</p>\n\n<p>Um duplo acesso monumental permite recrear-se nas exposições da fundação.</p>\n\n<p>Rematam o edifício uma cúpula esmaltada com escamas azuis em cada canto.</p>\n\n<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e visite este centro cultural ao seu próprio ritmo.</p>\n\n<p>Pode retomar a sua aventura uma vez o entender conveniente. Simplesmente, prima o botão correspondente e continue à procura do tesouro.</p>`,
  "665": `<p>Situe-se, se faz favor, a olhar para o edifício Fundação Bancaja e tome a rua que sai à sua mão direita.</p>\n\n<p>No final da rua encontra-se a Plaza de San Vicente Ferrer.</p>`,
  "666": "<p>Nas Fallas ouvem-se petardos a todas as horas, se o ruído lhe parecer muito forte abra a boca e não tape os ouvidos, é pior.</p>",
  "667": "<p>Na praça onde se encontra, uma fonte ergueu-se em 1853. Esta é outra dessas 8 fontes públicas que era recetora da recente chegada da água potável à cidade.</p>",
  "667-B": `<p>Na praça onde se encontra, uma fonte ergueu-se em 1853; tempos em que as fontes públicas eram as recetoras da recente chegada da água potável à cidade.</p>\n\n<p>O abastecimento de água potável, ainda, não estava generalizado nas habitações e havia que recolhê-la nas fontes públicas para uso pessoal.</p>`,
  "668": "<p>O que sustém a figura com a sua mão? Um escudo, uma harpa, uma jarra ou talvez uma espada?</p>",
  "669": `<p>Atrás da fonte podemos admirar a Igreja de Santo Tomás e São Filipe Neri.</p>\n\n<p>Este Templo foi construído entre 1727 e 1736 em tijolo pintado a vermelho.</p>\n\n<p>O primeiro corpo eleva-se sobre um socalco de pedra que se articula em oito grandes pilastras.</p>\n\n<p>No centro abre-se uma porta com verga reta realizada em pedra.</p>\n\n<p>Sobre a portada, duas imagens femininas representam a Virgindade, adornada com as flores da pureza; e a Oração.</p>\n\n<p>Por isso sustém o incensário do culto divino.</p>\n\n<p>Um alto-relevo em que aparece representada a aparição da Virgem a São Filipe Neri e o escudo da monarquia espanhola sobre o lintel da porta são dois exemplos de alto-relevo que este templo oferece.</p>\n\n<p>Destaca também o seu campanário de planta quadrada, com 45 metros de altura e 106 degraus. Esta igreja foi Declarada Monumento Histórico Artístico Nacional em 1982.</p>`,
  "670": `<p>Admirando este templo de culto, apenas uns pequenos passos na rua à sua esquerda ergue-se outro monumento a destacar nesta aventura.</p>\n\n<p>No seu mapa corresponde ao número <mark>83</mark>.</p>\n\n<p>Não pause esta audioguia e dirija-se ao ponto indicado.</p>`,
  "670-B": `<p>Admirando este templo de culto, apenas uns pequenos passos na rua à sua esquerda ergue-se outro monumento a destacar nesta aventura.</p>\n\n<p>No seu mapa corresponde ao número <mark>30</mark>.</p>\n\n<p>Não pause esta audioguia e dirija-se ao ponto indicado.</p>`,
  "671": `<p>Vai agora adentr-ar-se no Reino árabe de Valencia.</p>\n\n<p>Desde o "Barrio del Mercat" até ao famoso "Barrio del Carmen" numerosos achados arqueológicos testemunham a importância alcançada pela cidade.</p>\n\n<p>Com a reconquista de Valencia por Jaime primeiro em 1238, colocou-se fim a cinco séculos de cultura muçulmana; mesmo assim, esta deixou uma sólida marca no território valenciano.</p>`,
  "672": `<p>O séc. XIII foi, para Valencia, o tempo de transição entre o Românico e o gótico, também entre o islâmico e o cristão.</p>\n\n<p>A Igreja de São João do Hospital conserva reminiscências dessas transformações.</p>\n\n<p>O conjunto histórico possui marcadas influências árabes na planta retangular que eram próprias do mudéjar.</p>\n\n<p>Uma ampliação, desta vez de estilo gótico, realizou-se no ano 1316.</p>\n\n<p>A capela hospitalar funerária foi provavelmente a primeira manifestação da arte ogival na Valencia do séc. XIII.</p>\n\n<p>A Igreja de São João do Hospital foi declarada monumento Artístico Nacional em 1943.</p>\n\n<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e visite este complexo histórico ao seu próprio ritmo.</p>\n\n<p>Pode retomar a sua aventura uma vez o entender conveniente. Simplesmente prima o botão correspondente e continue à procura do tesouro.</p>`,
  "673": `<p>A origem do Palácio remonta ao séc. XIII. Este edifício sofreu contínuas reformas, sendo a mais importante a realizada no séc. XVIII; na qual se modifica o seu interior e a sua fachada.</p>\n\n<p>Em 1936, no início da Guerra Civil Espanhola, o edifício foi incendiado sucessivas vezes pelo que ficou destruído à exceção de parte da capela que se manteve a arder três dias seguidos.</p>\n\n<p>Nestes incêndios perderam-se cerca de 13.000 volumes escritos e o Museu Diocesano com todas as obras de arte que se encontravam no seu interior. O atual edifício, de estilo eclético, foi reconstruído entre 1941 e 1946.</p>`,
  "674": `<p>No lado oposto da praça, encontra-se o Palácio do Marquês de Campo. Pode vê-lo?</p>\n\n<p>No seu mapa corresponde ao número <mark>85</mark>.</p>\n\n<p>O edifício remonta ao séc. XVIII, mas no séc. XIX; o Marquês de Campo procedeu a uma completa remodelação.</p>\n\n<p>Anos depois e após passar por várias mãos, o Ayuntamiento declarou o Palácio Monumento Histórico Artístico de caráter local.</p>\n\n<p>O facto ocorrido em 1973 aumentou o seu estatuto em 1982 quando obteve a categoria de Monumento Histórico Artístico de caráter provincial.</p>\n\n<p>Em 1989, após uma custosa e dedicada reabilitação, o Palácio foi posto em uso como Sede do Museu da Cidade.</p>\n\n<p>Atualmente o museu alberga importantes coleções que até então se encontravam dispersas por distintos edifícios.</p>\n\n<p>Estas ajudam-nos a entender melhor a história Valenciana desde a fundação romana até meados do séc. XIV.</p>\n\n<p>Além disso, o museu também é usado como sala de exposições temporárias; repartidos pelo museu pode contemplar-se uma importante coleção de arte valenciana do séc. XX.</p>\n\n<p>No piso superior expõe-se uma coleção de pesos e medidas.</p>`,
  "675": `<p>À esquerda do Museu, uma entrada discreta dá passagem a um ponto de interesse nesta Aventura.</p>\n\n<p>No seu mapa corresponde ao número <mark>86</mark>.</p>\n\n<p>Neste local encontrava-se uma das prisões onde foi encerrado São Vicente Mártir no séc. IV d.C. que morreu sem renunciar à sua fé após ser torturado no ano 304 pelos romanos.</p>\n\n<p>O interior alberga uma capela funerária em excecional estado de conservação de época Visigótica, falamos dos séc. VI e VII d.C.</p>\n\n<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre nestes tesouros históricos para conhecer melhor a história da cidade.</p>\n\n<p>Pode retomar a sua aventura uma vez o entender conveniente, simplesmente prima o botão correspondente e continue à procura do tesouro.</p>\n\n<p>A sua aventura continua neste mesmo ponto.</p>`,
  "676": `<p>Continue pela estreita rua, ao sair dela mesmo em frente ergue-se o edifício do Almudín, número <mark>87</mark> no seu mapa.</p>\n\n<p>Almudín deriva da palavra Árabe "Almud" que é o nome de uma medida de peso, semelhante a dizer Onça ou Grama.</p>`,
  "677": `<p>A que poderia ter sido destinado o edifício?</p>\n\n<p>Armazém de grão, talho municipal ou talvez venda de especiarias?</p>`,
  "678": `<p>Desde 1307 e erguido sobre um antigo castelo fortificado muçulmano, este edifício foi armazém e comércio de trigo e grão de Valencia; pelo que podemos fazer uma ideia da importância que representava um edifício destas características na Valencia da idade média.</p>\n\n<p>Para isso criou-se uma complexa rede de funcionários que se encarregavam de tão importante tarefa.</p>\n\n<p>Imagine, por sua vez, que a ausência de grão e farinha e portanto de pão podia ser fonte de saques e revoltas de consequências imprevisíveis.</p>\n\n<p>Daí a necessidade de ter um local ventilado, mas de difícil acesso; repare na altura das janelas e nas suas dimensões.</p>\n\n<p>Atualmente o edifício de propriedade está dedicado a Sala Municipal de Exposições temporárias.</p>`,
  "679": `<p>Bravo! Está prestes a finalizar a sua aventura.</p>\n\n<p>Observe o seu mapa que lhe indica que saia de novo para a Plaza de la Virgen. Esta, deverá ficar à sua esquerda. Situe-se, com a Fonte de Neptuno às suas costas a observar a rua que tem em frente.</p>\n\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "680": `<p>Chegou ao ponto sugerido? Ótimo! Não pause esta audioguia.</p>\n\n<p>Abra o seu mapa e observará que o incita a voltar ao ponto de partida. Sim, ao número <mark>1</mark>!</p>\n\n<p>Bravo! Essa será a sua última paragem e com isso terá percorrido 34 quilómetros de tesouros arquitetónicos históricos e também recentes sem sair da cidade de Valencia!...bem...quase.</p>\n\n<p>Siga o curso da rua na qual numerosos estabelecimentos o tentarão a degustar a gastronomia local, o seu objetivo está no final da rua, virando à esquerda.</p>`,
  "681": `<p>Teremos prazer em aportar dois últimos breves detalhes que se situam à esquerda e à direita no transcurso do caminho.</p>\n\n<p>No seu mapa correspondem aos números <mark>88</mark> e <mark>89</mark> respetivamente.</p>`,
  "682": `<p>Aproximadamente a meio do comprimento da via, à esquerda, ergue-se a Igreja de São Lourenço, número <mark>88</mark> no seu mapa.</p>\n\n<p>As origens da Igreja de São Lourenço remontam à própria reconquista de Valencia em 1238. Tal como a Igreja de Santa Catalina, mencionada nesta Aventura.</p>\n\n<p>Lembre-se de que, após a reconquista e posterior mudança de religião da cidade, Jaime Primeiro, estruturou o espaço urbano.</p>`,
  "682-B": `<p>Aproximadamente a meio do comprimento da via, à direita, ergue-se a Igreja de São Lourenço.</p>\n\n<p>As origens da Igreja de São Lourenço remontam à própria reconquista de Valencia em 1238.</p>\n\n<p>Após a reconquista e posterior mudança de religião da cidade, Jaime Primeiro, estruturou o espaço urbano.</p>`,
  "683": "<p>O que porta São Lourenço na mão? Uma Pomba, uma colher ou talvez é uma Grelha?</p>",
  "684": "<p>Observe no canto superior um pequeno balcão-miradouro coberto por cúpula, que permite a vista de ambos os lados das ruas onde se situam as portadas da igreja. Curioso, não é verdade?</p>",
  "685": `<p>Uns passos mais adiante, à direita da rua, ergue-se um edifício construído em estilo gótico. Foi residência do Papa Rodrigo Borgia nas suas numerosas visitas a Valencia.</p>\n\n<p>Les Corts Valencianes correspondem no seu mapa ao número <mark>89</mark>. Pode vê-lo? Hoje em dia dedica-se a atividades governamentais.</p>\n\n<p>Parabéns! Vai pelo bom caminho!</p>`,
  "686": `<p>O palácio foi construído no séc. XV, a sua característica principal é a sua ampla fachada. Na Baixa Idade Média o renome de um apelido ou família também se media pela envergadura do seu palácio. Esta fachada tão extensa fazia presumir um poder e uma nobreza superior.</p>\n\n<p>Apesar do luxo do Palácio, não era a residência habitual dos seus proprietários que tinham a sua residência permanente em Gandia, uma localidade próxima de Valencia.</p>`,
  "687": `<p>A cada 1 de março a cidade tinge-se com a cor das flores e da pólvora para receber a primavera e mais de um milhão de visitantes.</p>\n\n<p>Desde 1954 e desde estas mesmas torres, cada ano marca-se o arranque das celebrações falleras. A esperada "Cridà" é o chamamento à festa das falleras maiores de Valencia para quem deseje participar.</p>`,
  "688": `<p>Dirija-se ao centro da ponte e observe à esquerda e à direita.</p>\n\n<p>À sua esquerda está o caminho por onde veio, e à sua direita mais de três quilómetros de jardim que desemboca na famosa Ciudad de las Artes y de las Ciencias.</p>\n\n<p>A imagem futurista que simboliza a nova Valencia; um conjunto único, de vanguarda arquitetónica a nível mundial onde milhões de visitantes acorrem cada ano para desfrutar da sua cultura, da sua natureza, da sua arte e da sua ciência.</p>\n\n<p>${LOGO} proporcionará-lhe informação detalhada sobre essa área na sua Aventura número 3.</p>`,
  "689": "<p>A aventura que vai explorar percorre boa parte do traçado da antiga muralha cristã de Valencia.</p>",
  "690": `<p>Atualmente a Oferta das flores inicia-se no dia 17 até à madrugada do 19 de março chegando a superar os cento e trinta mil Falleras e Falleros deixando a Plaza de la Virgen repleta de flores.</p>\n\n<p>${LOGO} proporcionará-lhe informação detalhada sobre esta festividade na sua Aventura Especial Fallas.</p>`,
  "691": `<p>Bravo, acaba de chegar à metade da sua aventura! Continue pela famosa Calle Hospital. Como indica o seu mapa, continue até ao final da rua e vire à mão esquerda. O nosso famoso Mercado Central emerge à sua direita, no seu mapa corresponde ao número <mark>15</mark>.</p>\n\n<p>Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "692": `<p>Temos preparada uma curiosidade; a olhar para o edifício do Ayuntamiento, à esquerda ergue-se outro edifício monumental. Destaca sobre a fachada, na sua parte superior, a estátua do grande leão do Assic realizado em bronze. Símbolo da entidade seguradora que ocupava o edifício antigamente.</p>`,
  "693": `<p>Mesmo à esquerda deste edifício ergue-se outro não menos monumental.</p>\n\n<p>Edifício modernista de princípios do séc. XX. Destaca pelos seus três grandes janelões em chanfro.</p>\n\n<p>A carpintaria exterior é de madeira, com contraventanas de estilo americano nos vãos, varandas de ferro forjado, à exceção da varanda central do piso principal, que foi construída com alvenaria.</p>\n\n<p>O edifício está rematado com pináculos de inspiração gótica e ameias de inspiração modernista.</p>\n\n<p>Na sua parte superior mostra o rótulo de "LA EQUITATIVA" que era uma antiga companhia de seguros, hoje desaparecida, que tinha a sua sede neste edifício.</p>\n\n<p>Sobre o rótulo destaca a deusa da justiça.</p>`,
  "693-B": "<p>O que porta a figura na mão? É uma balança, um livro ou talvez uma pena?</p>",
  "693-C": `<p>Mesmo à esquerda deste edifício ergue-se outro não menos monumental. No seu mapa corresponde ao número <mark>14</mark>.</p>\n\n<p>Este é um edifício modernista de princípios do séc. XX. Destaca pelos seus três grandes janelões em chanfro.</p>\n\n<p>A carpintaria exterior é de madeira, com contraventanas de estilo americano nos vãos, varandas de ferro forjado, à exceção da varanda central do piso principal, que foi construída com alvenaria.</p>\n\n<p>O edifício está rematado com pináculos de inspiração gótica e ameias de inspiração modernista.</p>\n\n<p>Na sua parte superior mostra o rótulo de "LA EQUITATIVA" que era uma antiga companhia de seguros, hoje desaparecida, que tinha a sua sede neste edifício.</p>\n\n<p>Sobre o rótulo a deusa da justiça.</p>`,
  "694": `<p>No transcurso, deverá atravessar a famosa Plaza de la Reina, uma recente restauração atualizou uma das praças mais conhecidas do centro histórico, eliminando o tráfego e reformando o parque de estacionamento subterrâneo. Após 18 meses de restauração, a céntrica Plaza de la Reina renasce com uma pedonalização de mais de 12.000 metros quadrados, oferecendo umas maravilhosas vistas da Catedral de Valencia.</p>\n\n<p>Observe com atenção enquanto caminha, poderá ver a pedra calcária utilizada na praça, a mesma com que foi construída a Catedral. A pedra calcária emprega-se tradicionalmente em Valencia porque não absorve o calor tanto como o granito, pelo que ajuda nos dias quentes de verão.</p>`,
  "695": `<p>A sua aventura continua a dobrar a esquina, de onde se pode ver a face principal do miguelete e também a porta Barroca da Catedral de Valencia; a terceira a ser construída. No seu mapa corresponde ao número <mark>13</mark>.</p>\n\n<p>Pause esta audioguia se o considerar necessário, uma vez que chegue ao seu destino, situe-se num local no qual possa ver a porta barroca na sua totalidade. Obrigado.</p>`,
  "696": "<p>Não se coloque demasiado perto da Mascletà, poderia sujar-se com os papelitos de cores provenientes dos petardos que explodem. Coloque-se de costas ao vento, desta forma evitará o fumo e os papelitos.</p>",
  "697": "<p>A reciclagem é fundamental na era em que vivemos, por favor use os contentores apropriados para isso.</p>",
  "698": "<p>As Fallas são uma tradição na qual se envolvem todo tipo de culturas, crenças religiosas, políticas e sexuais. O respeito é fundamental para conseguir que a sua estância durante a festa seja digna de recordar.</p>",
  "699": `<p>Utilize o botão de pausa a seu próprio gosto. Quando o decidir, simplesmente continue a resolver os nossos desafios enquanto descobre a cidade. O seu próximo objetivo fica ao final da praça à sua mão direita. No seu mapa corresponde ao número <mark>10</mark>.</p>`,
  "700": "<p>Já se encontra no edifício dos Correios? Lembre-se, que corresponde no seu mapa ao número 14.</p>",
  "701": "<p>Já se encontra em frente do Mercado Central? Sim? Ótimo! Continuamos?</p>",
  "702": `<p>Já se encontra no ponto indicado com o número <mark>11</mark> no seu mapa? Ótimo! Continuemos à procura do tesouro!</p>`,
  "703": "<p>Ótimo! Continuemos com a procura do tesouro! Observe à sua volta e poderá ver umas ruínas que se destacam entre a ornamentação botânica do jardim do Turia. Pode vê-las? Sim? Perfeito, porque a próxima história esperamos que o surpreenda.</p>",
  "704": `<p>Já se encontra no ponto indicado com o número <mark>6</mark> no seu mapa?</p>`,
  "704-B": `<p>Já se encontra no ponto indicado com o número <mark>3</mark> no seu mapa?</p>`,
  "705": `<p>Já se encontra no ponto indicado com o número <mark>24</mark> no seu mapa?</p>`,
  "706": `<p>Já se encontra no ponto indicado com o número <mark>76</mark> no seu mapa?</p>`,
  "707": "<p>De que é feita a Orxata? De chufa, de arroz ou de cevada?</p>",
  "708": "<p>No decorrer da sua Aventura poderá terminar de descobrir o majestoso Parque de Cabecera, passando pelo antigo moinho do sol, lembre-se de que antigamente os moinhos eram edifícios indispensáveis para moer o grão e com isso produzir a farinha necessária para poder elaborar, entre outros, confeitaria e padaria.</p>",
  "709": `<p>O Molí del Sol, construído em 1880, foi o primeiro dos 18 moinhos da acequia de Rascanya e o último hidráulico edificado na horta valenciana, aproveitando o desnível do terreno para moer trigo e arroz. Após o enterramento da acequia na década de 1980, o edifício ficou em desuso até à sua restauração no atual Parque de Cabecera, ponto exato onde hoje nasce a Rota Verde do Parque Fluvial do Turia. Este caminho ciclopedonal estende-se uns 30 km para oeste por pistas florestais, seguindo o curso natural do rio Turia.</p>`,
  "710": "<p>O Museu de História de Valencia é provavelmente um dos melhores lugares para continuar a aprender sobre esta cultura mediterrânica em que se encontra hoje.</p>",
  "711": "<p>O próximo ponto de interesse na sua aventura é um local muito especial no qual a água tem grande importância. O centro de exposições e museu Na Turia atua como um ponto de encontro cidadão para promover a sustentabilidade urbana, servir de centro formativo e oferecer recursos educativos sobre ecologia e meio ambiente.</p>",
  "712": `<p>No seu mapa corresponde ao número <mark>68</mark>.</p>`,
  "713": `<p>NaTuria é um espaço educativo e ambiental cujo objetivo é aproximar a natureza à cidadania e fomentar hábitos sustentáveis na vida quotidiana mediante exposições, cursos, oficinas e visitas guiadas centradas em sustentabilidade, reciclagem, biodiversidade e qualidade de vida urbana; no seu entorno próximo encontra-se uma pequena presa ou açude que retém água do antigo leito do rio e faz parte do projeto paisagístico do parque, recriando um ambiente aquático que evoca o antigo Turia com vegetação de ribeira, fauna associada como aves e anfíbios, e zonas de passeio e observação, onde além disso se situa o Moinho do Tell, um antigo moinho harineiro restaurado integrado nas atividades do próprio NaTuria, no qual se explica a sua história, a vida sustentável tradicional e a relação histórica de Valencia com a água, de modo que este conjunto funciona principalmente como um elemento educativo e simbólico que recorda o vínculo da cidade com o seu rio e promove a aprendizagem sobre a gestão sustentável da água.</p>`,
  "VIV1": `<p>${LOGO} recomenda-lhe que siga o curso do seu mapa e percorra o passeio.</p>\n\n<p>A meio do passeio, à mão direita situam-se as ruínas do que seria no seu dia a Torre da Rainha do já extinto palácio.</p>`,
  "VIV2": `<p>A seguir, verá um grande montículo de terra.</p>\n\n<p>Este é um ponto perfeito para tirar umas magníficas fotografias das vistas que o jardim oferece.</p>\n\n<p>O montículo recebe o nome de Elio, Capitão General dos Reinos de Valencia e Múrcia no séc. XIX.</p>\n\n<p>Curiosamente, Elio foi decapitado anos mais tarde neste mesmo local.</p>\n\n<p>Este montículo foi criado com as ruínas do palácio, no qual se plantaram árvores e flores. Foi no monte Elio que se iniciaram os jardins de viveiros da cidade.</p>\n\n<p>Estes pontos correspondem aos números <mark>2</mark> e <mark>3</mark> respetivamente.</p>`,
  "VIV3": `<p>Um pouco mais adiante, à mão esquerda no passeio, podemos observar a casa do jardineiro maior que corresponde ao número <mark>4</mark> no seu mapa.</p>\n\n<p>Hoje em dia cumpre a função de escritórios dos jardins.</p>\n\n<p>Continue até ao final do passeio das palmeiras e encontrará um divertido circuito urbano no qual os mais pequenos aprendem, enquanto brincam, a interpretar os sinais de trânsito.</p>\n\n<p>No seu mapa corresponde ao número <mark>5</mark>.</p>\n\n<p>${LOGO} incita-o a pausar e percorrer este circuito ao seu próprio ritmo, este é um local perfeito para obter umas fotos da sua Aventura retomando-a desde este mesmo ponto, uma vez o entender conveniente.</p>`,
  "VIV4": `<p>Situe-se a olhar para o circuito, vire à sua esquerda e adentre-se na rua Jardineros Mayores.</p>\n\n<p>No seu mapa, corresponde ao número <mark>6</mark>.</p>\n\n<p>O traçado é uma zona pavimentada e bordeada por exemplares de Jacarandas, naturais do Brasil, e Podocarpus procedentes da China.</p>\n\n<p>Esta área usa-se em diversos eventos, como, por exemplo, a feira do livro.</p>\n\n<p>Continue este caminho até ao final e verá que se abre uma esplanada.</p>\n\n<p>À esquerda pode ver-se um modelo típico da arquitetura rural valenciana. A conhecida Alqueria de Canet corresponde ao número <mark>7</mark> no seu mapa. Em frente da alqueria encontra-se um museu, no seu mapa corresponde ao número <mark>8</mark>.</p>`,
  "VIV5": "<p>A que está dedicado o museu? Às ciências naturais? Talvez à arquitetura? Ou talvez à história?</p>",
  "VIV6": `<p>Nos anos 70, este edifício era conhecido como "o restaurante de Viveros", hoje em dia alberga no seu interior, entre outras, uma coleção doada em 1889 por Dom José Rodrigo Botet, engenheiro valenciano, que reuniu grande número de restos paleontológicos encontrados nas suas escavações do continente americano.</p>\n\n<p>Destacam o enorme urso das cavernas (o megaterio) da Patagónia argentina, pegadas petrificadas de dinossauros, restos fósseis, esqueletos, tatus couraçados, conchas do mar e numerosos insetos.</p>\n\n<p>Tudo complementado com painéis explicativos, zonas didáticas e audiovisuais.</p>`,
  "VIV7": `<p>O mapa destes jardins leva-o a afastar-se deste ponto para voltar mais tarde.</p>\n\n<p>Por agora, dirija-se à direita onde o aguarda uma zona que lembra os jardins de Versalhes.</p>\n\n<p>No seu mapa corresponde ao número <mark>9</mark>.</p>`,
  "VIV8": "<p>Uma grande lanterna, de das únicas que existem na cidade, permite-nos vislumbrar o nosso próximo objetivo.</p>",
  "VIV9": `<p>Uns metros mais adiante, na Rosaleda, emerge uma grande fonte circular proveniente da Plaza de la Reina rodeada por cerca de seis mil rosas de distintas espécies, além de outras espécies ornamentais.</p>\n\n<p>A rosaleda, que foi plantada em 1974 e reformada em 2010, corresponde no seu mapa ao número <mark>10</mark>.</p>`,
  "VIV10": `<p>Saindo pela parte oposta da rosaleda ficam os viveiros que se encarregariam de fornecer as espécies botânicas e flora à cidade.</p>\n\n<p>${LOGO} encoraja-o a pausar e explorar esta área botânica ao seu próprio ritmo, podendo continuar a sua procura desde o museu que corresponde ao número <mark>8</mark> no seu mapa.</p>\n\n<p>Lembre-se de que o botão de pausa pode usá-lo a seu próprio gosto e premê-lo quando o entender conveniente. Depois simplesmente prima início e continue a resolver os nossos desafios enquanto descobre a cidade.</p>\n\n<p>Os Jardines del Real oferecem uma ampla gama de esculturas: O Repouso, A Dama de Elche, As Quatro Falsas Estações, Despertar e A Fonte de Neptuno, são alguns exemplares que poderá encontrar no seu percurso.</p>`,
  "VIV11": `<p>Situe-se, se faz favor, entre a alqueria e o museu; números <mark>7</mark> e <mark>8</mark> respetivamente.</p>\n\n<p>Com a Alqueria à sua mão esquerda e o Museu à sua direita, observe que à frente se abre uma praça destinada a eventos musicais; tais como concertos e danças típicas. No final deste espaço, um tímido lago apresenta-se à sua direita.</p>\n\n<p>Este é o conhecido lago dos cisnes, onde aves migratórias, tais como cegonhas e patos, descansam neste habitat protegido para repor as forças antes de empreender o seu voo. No seu mapa corresponde ao número <mark>11</mark>.</p>`,
  "VIV11-B": `<p>No final deste espaço, um tímido lago apresenta-se à sua direita. Dirija-se ao lago dos cisnes. No seu mapa corresponde ao número <mark>11</mark>.</p>`,
  "VIV11-C": "<p>Este é o conhecido lago dos cisnes, onde aves migratórias, tais como cegonhas e patos, descansam neste habitat protegido para repor as forças antes de empreender o seu voo.</p>",
  "VIV12": `<p>Que figura decora a fonte? É um pato? Uma cegonha? Ou talvez um Peixe?</p>\n\n<p>Prima a pausa e vá ao local indicado para completar o seu desafio.</p>`,
  "VIV13": `<p>Seguindo a forma do jardim, uma escultura dedicada à água dá as boas-vindas a um dos cantos mais discretos do parque. No seu mapa corresponde ao número <mark>12</mark>.</p>`,
  "VIV14": `<p>Uma criança é muito mais do que um elemento decorativo: é uma obra simbólica que representa a relação humana com a água. Situada num ambiente historicamente ligado à rega e à horta, recorda a importância essencial da água como base da vida, sem a qual não existiriam nem a agricultura nem as cidades. A composição reforça esta mensagem: a água simboliza a origem da vida, a mãe o cuidado e a proteção, e a criança a continuidade e o futuro.</p>`,
  "VIV15": `<p>Atrás da fonte abre-se uma portada de estilo barroco dedicada a São Julião.</p>\n\n<p>Este espaço íntimo esconde duas portadas aos antigos jardins do palácio que Condes e Duques tinham desde a sua morada.</p>\n\n<p>Hoje em dia é um canto romântico e tranquilo no qual poder relaxar e desfrutar de paz e sossego numa cidade em constante movimento.</p>\n\n<p>No seu mapa corresponde ao número <mark>12</mark>.</p>\n\n<p>Com a portada e a fonte às suas costas, aventure-se na zona dos Ficus, árvores de grande envergadura naturais da Austrália.</p>\n\n<p>${LOGO} encoraja-o a explorar esta área tranquilamente.</p>\n\n<p>Retome esta aventura desde a saída dos Jardines del Real, utilizando a mesma porta pela qual entrou. No seu mapa corresponde ao número <mark>1</mark>.</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
