import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "379": `<p>Portanto, prestando um pouco de atenção, poderá encontrar:</p>\n<p>O barqueiro que rema a contracorrente: Um homem com rosto triste manejando um pequeno bote de madeira escapa a contracorrente de um monstro.</p>`,
  "380": "<p>Já o viu? Então, o nosso homem foge dessa criatura monstruosa chamada tentação?</p>",
  "381": `<p>Uma árvore morta: símbolo do Pecado, vê-se entre as duas folhas da porta e cumpre a função de parteluz.</p>\n<p>Observe na copa da árvore como 4 homens nus se açoitam entre si.</p>\n<p>Já os viu todos? Parabéns!</p>`,
  "382": `<p>A <strong>Fuente del Negrito</strong> foi inaugurada em 1850.</p>\n<p>Naqueles tempos, as fontes públicas eram as recetoras da recente chegada da água potável à cidade.</p>\n<p>O abastecimento de água potável, ainda, não estava generalizado nas habitações e havia que recolhê-la nas fontes públicas para uso pessoal.</p>`,
  "383": "<p>Preste agora atenção a algumas das suas gárgulas, afaste-se um pouco para as ver no alto do edifício:</p>",
  "384": "<p>À direita um anjo que mostra o seu pénis e se dispõe a introduzi-lo num jarro que sustém com a outra mão. Algo estranho e inusual, não lhe parece?</p>",
  "385": `<p>No centro O barbudo e o leão:</p>\n<p>Cena original e contraditória na qual o manso é precisamente o leão e não o ancião barbudo.</p>\n<p>Na realidade, as evidências levam-nos aqui à história de Sansão vencendo um leão, um paralelismo da vida de Jesus lutando contra o Demônio.</p>`,
  "386": `<p>Aqui vai um desafio extra!</p>\n<p>Procure o fornicador da <strong>Lonja</strong>!</p>\n<p>Numa das suas janelas, encontrará um homem fornicando com o muro do edifício civil mais importante da época.</p>\n<p>Não se avista a sua cabeça, mas sim os seus genitais, e muito claramente.</p>\n<p>Isso, ou está a fazer as suas necessidades.</p>`,
  "387": "<p>Já o viu? Bravo! Essa era difícil!</p>",
  "388": `<p>Observe o mapa com cautela. Desde a sua perspetiva, leva-o a rodear a <strong>Lonja</strong> a dobrar a esquina.</p>\n<p>O Pátio das Laranjeiras, que dá passagem a uma escada de pedra descoberta que conduz ao piso principal do Pavilhão do Consulado, amplo local onde antigamente celebravam as suas sessões os juízes ou cônsules de comércio e articula as três zonas do edifício.</p>`,
  "389": "<p>É bom momento para começar a sua aventura? Sim, Não</p>",
  "390": `<p>Observe a gárgula da torre.</p>\n<p>À esquerda encontra-se uma mulher completamente nua que toca o seu sexo com as duas mãos.</p>`,
  "391": `<p>Uma figura desprovida de sensualidade e erotismo que recria o ato da masturbação (pecaminoso segundo a moral da época).</p>\n<p>Voltamos à luxúria, tema mais que predominante nas esculturas que decoram o edifício.</p>\n<p>Provavelmente seja a figura mais reconhecida, famosa e surpreendente à primeira vista da <strong>Lonja de la Seda</strong> de Valencia.</p>\n<p>Desde o séc. XV, a <strong>Lonja</strong> e as suas virtuosas figuras carregadas de obscenidade observam a rua desta cidade de Valencia.</p>\n<p>Estátuas que ganham vida nos muros de um edifício que já não está no séc. XV, mas sim no séc. XXI e cujos passantes ao olhá-las param e perguntam: O que nos querem dizer?</p>`,
  "392": `<p>Mais adiante, seguindo o edifício, encontrará a porta de acesso ao monumento.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre neste monumento para conhecer melhor a história da cidade e os seus costumes.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente.</p>`,
  "393": `<p>Situe-se com a porta de acesso à <strong>Lonja</strong> às suas costas e dirija-se à sua direita até chegar à antiga porta que dá acesso ao edifício, é a última que lhe falta ver.</p>\n<p>Uma vez aí, observe atentamente a entrada enquanto ouve a próxima história.</p>`,
  "394": `<p>Os Santos "Canonizados", oficialmente, pela Igreja Católica são cerca de 10.000.</p>\n<p>Um processo longo que pode demorar muito tempo devido à complexidade que representa.</p>\n<p>O postulante deve ser servo de Deus, para isso a sua vida deve ser exemplar e virtuosa.</p>\n<p>Uma instituição especializada recolhe os principais aspetos da sua vida e compila-os em virtudes e escritos da pessoa.</p>\n<p>Se as suas façanhas foram heroicas, o Santo Padre declara-o "Pessoa venerável".</p>\n<p>Após realizar o primeiro dos seus milagres, a referida pessoa será beatificada.</p>\n<p>Para se tornar Santo, o postulante devia ter realizado, pelo menos, 3 milagres nos quais se demonstrasse a sua intercessão.</p>`,
  "395": `<p>Se se encontrar em horário de visita, ${LOGO} recomenda-lhe que prima a pausa e visite este monumento ao seu próprio ritmo para conhecer um pouco mais da história da cidade.</p>`,
  "396": `<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre neste espaço para conhecer melhor a história da cidade.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente, simplesmente prima o botão correspondente e continue <i>à procura do tesouro</i>.</p>\n<p>A sua aventura continua neste mesmo ponto.</p>`,
  "397": `<p>Desde a sua nova perspetiva, com a porta do monumento em frente, vire à sua esquerda e poderá ver uma praça diáfana.</p>\n<p>Aproxime-se, se faz favor, à praça diáfana que tem à sua esquerda.</p>`,
  "398": `<p>Este é o local onde se encontrava originariamente a <strong>Lonja de Valencia</strong>.</p>\n<p>Existem dados da sua existência desde 1344.</p>\n<p>Na antiga <strong>Lonja</strong> comercializava-se com azeite e especiarias e manteve-se de pé até ao séc. XIX.</p>\n<p>Mas devido à crescente imigração, os comerciantes do séc. XV viram-se obrigados a construir um edifício maior no qual poder albergar uma maior capacidade para o inesperado aumento de atividade comercial que se produziu na cidade durante o seu século de ouro.</p>`,
  "399": "<p>Encontra-se, neste momento, no local onde, segundo conta a tradição, se realizou um dos milagres mais conhecidos de Valencia.</p>",
  "400": `<p>Em 1358 Vicente Ferrer estava pregando às portas da antiga <strong>Lonja de Valencia</strong>.</p>\n<p>O sermão que Vicente Ferrer oferecia naquele dia recordava às pessoas de bem a necessidade de ajudar os que sofriam e morriam por pobreza e inanição e que era necessária a sua caridade.</p>\n<p>O então teólogo da <strong>Catedral de Valencia</strong>, para o demonstrar, tirou um lenço e lançou-o ao ar enquanto dizia a essa multidão que seguissem o lenço.</p>\n<p>Aí, onde o lenço parasse, encontrariam pessoas realmente necessitadas da sua caridade.</p>`,
  "401": "<p>O lenço voou até um ponto concreto e a multidão pôde comprovar que nessa casa se encontrava uma família a ponto de falecer na mais absoluta miséria e as pessoas compassivas socorreram a família.</p>",
  "401-B": "<p>O lenço voou até este ponto, e a multidão pôde comprovar que nessa casa se encontrava uma família a ponto de falecer na mais absoluta miséria e as pessoas, compassivas, socorreram a família.</p>",
  "402": "<p>Desta forma se interpretou o conhecido milagre do Mocaoret, que em valenciano significa lencinho, que realizaria o futuro Santo da Comunitat Valenciana.</p>",
  "403": `<p>Nesta aventura percorrerá parte do voo desse lenço que o conduzirá à famosa <strong>Plaza Redonda</strong>.</p>\n<p>Abra e observe o seu mapa que lhe indica que deixe esta praça à sua esquerda e entre na rua situada em frente a si.</p>\n<p>Preste atenção ao mapa, o seu próximo objetivo é a famosa <strong>Plaza Redonda</strong> que se situa na quarta rua à esquerda e depois a primeira à direita.</p>\n<p>Repito? Claro, com muito prazer!</p>\n<p>Quarta rua à esquerda e depois a primeira à direita.</p>`,
  "404": "<p>Nas Fallas tudo é festa: o estrondo da mascletà, os casales, os pasacalles, a oferta das flores e as bandas de música percorrem os mais de 700 monumentos falleros.</p>",
  "405": `<p>O antigo Mercado de carne e peixe, a <strong>Plaza Redonda</strong>, é o óculus de Valencia, um olho mirando ao céu.</p>\n<p>Corresponde hoje em dia ao número <mark>36</mark> no seu mapa.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido. Obrigado.</p>`,
  "405-B": `<p>À direita desta fachada de arcos cegos da igreja encontra-se a famosa <strong>Plaza Redonda</strong>.</p>\n<p>A <strong>Plaza Redonda</strong> é o óculus de Valencia, um olho mirando ao céu.</p>\n<p>O antigo Mercado de carne e peixe corresponde hoje em dia ao número <mark>16</mark> no seu mapa.</p>`,
  "406": `<p>Desde a sua reabilitação em 2012, a <strong>Plaza Redonda</strong> tem a aparência de uma praça moderna sem perder o seu toque histórico.</p>\n<p>Nesta praça mantém-se viva uma grande tradição valenciana.</p>\n<p>Ainda, na atualidade, podem ver-se oficinas de renda de bilros; uma técnica têxtil que consiste em encaixar os fios sobre um padrão para formar o bordado.</p>\n<p>Técnica que precisa de habilidades como a atenção, concentração, destreza e, sobretudo, a psicomotricidade nos dedos.</p>\n<p>No interior da praça, ainda, podem ver-se lojas especializadas em rendas e bordados feitos à mão. Também, poderá gozar de magníficos souvenirs, todos eles de estilo valenciano, e bares para degustar as nossas típicas tapas.</p>\n<p>${LOGO} recomenda-lhe que prima a pausa e visite esta praça ao seu próprio ritmo.</p>`,
  "407": `<p>Uma vez que decida continuar a sua aventura, desafiamo-lo a encontrar a porta de saída correta.</p>\n<p>Atreve-se?</p>\n<p>Uma das múltiplas saídas possíveis conduz-o a uma praça com vários pontos de interesse na sua Procura do Tesouro.</p>\n<p>O seu próximo objetivo é a Plaza de Santa Catalina, indicada no seu mapa com o número <mark>37</mark>.</p>`,
  "408": "<p>Temos preparada uma curiosidade para si! Valencia está repleta de tesouros arquitetónicos e históricos que vamos desvelando em cada uma das nossas Aventuras.</p>",
  "409": `<p>Desde o centro da praça pode ver-se um dos edifícios mais estreitos da Europa. Pode vê-lo?</p>\n<p>Imagina? O primeiro andar uma sala de jantar, o segundo a cozinha e assim sucessivamente.</p>`,
  "410": "<p>Quanto mede a entrada?</p>",
  "411": `<p>Esta Procura do Tesouro incita-o a aproximar-se a Santa Catalina; desde o centro da praça, poderá contemplar a igreja na sua totalidade.</p>\n<p>Como pode comprovar, a igreja fica parcialmente envolta pelas casas adjacentes e parece bastante tosca por fora.</p>`,
  "412": `<p>As origens da <strong>Iglesia de Santa Catalina</strong> Mártir remontam à própria reconquista de Valencia em 1238.</p>\n<p>Após a reconquista e posterior mudança de religião da cidade, Jaime Primeiro tratará de estruturar o espaço urbano.</p>\n<p>Para isso, concede a propriedade de todas as mesquitas e cemitérios muçulmanos ao arcebispado que, por sua vez, cristianiza estes templos renomeando-os como paróquias dedicadas a Santas e Santos da nova religião que se instauraria nestas terras.</p>\n<p>Em maio de 1239, apenas 1 ano após a reconquista, a Paróquia de Santa Catalina passou a ser uma das dez Paróquias fundacionais da cidade.</p>\n<p>Acrescentaremos também que o facto da tomada das mesquitas não era apenas um instrumento de cristianização e controlo eclesiástico da vida vizinal, mas também um instrumento de organização administrativa e política; de facto, o ayuntamiento estava formado, em parte, pelas diferentes paróquias da cidade.</p>`,
  "413": `<p>Com os anos, começaram a construir-se paróquias de planta cristã no lugar que ocupavam as antigas mesquitas.</p>\n<p>A <strong>Iglesia de Santa Catalina</strong> ficou terminada em 1371. Mas, em 1740, sofreu uma reforma que durou 15 anos e que suporia uma renovação quase total do templo.</p>`,
  "414": `<p>Conta a lenda urbana que no contrato entre o arquiteto e a igreja não se especificou a construção de uma escada para subir à torre pelo que o arquiteto construiu a torre sem acesso aos seus níveis superiores.</p>\n<p>Hoje em dia pode aceder-se à torre mediante uma escada em caracol que permite o acesso à balaustrada.</p>\n<p>Se se encontrar em horário de visita, ${LOGO} recomenda-lhe que prima a pausa e passeie no interior deste templo, assim como visite a sua torre.</p>\n<p>A sua aventura continua desde este mesmo ponto em que se encontra.</p>`,
  "415": "<p>O caminho requer que lhe preste uma atenção especial, pois dar-lhe-á acesso a uma história oculta no seu mapa do tesouro. Será capaz de encontrá-la? Uma gigantesca concha talhada em pedra que fica à sua direita e encostada ao muro de contenção dentro do próprio jardim, desvela parte da história trágica da cidade.</p>",
  "416": `<p>Centre a sua atenção na fachada que tem diante de si agora mesmo. Nela abrem-se três arcos cegos.</p>\n<p>Dois deles são lisos; o terceiro foi deixado sem reboco.</p>\n<p>O que se pode ver nesse arco? Pode ver um rosto? Há talvez um torso? E uma gárgula?</p>`,
  "417": `<p>Até 1520, nesta fachada, situava-se o serviço encarregado da vigilância dos mercados e da higiene pública; além do controlo das pesas e medidas da cidade, dado que, a escassos metros, se encontravam as carnicerías e peixarias da cidade.</p>\n<p>Antigamente, esta era a zona comercial e mercantil onde se alojavam a maioria das guildas mais importantes da cidade.</p>`,
  "418": `<p>O seu mapa do tesouro leva-o a bordear a igreja em direção à torre.</p>\n<p>No seu mapa corresponde ao número <mark>38</mark>.</p>\n<p>Não pause esta audioguia e dirija-se ao ponto indicado.</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
