import { readFileSync, writeFileSync } from 'fs';
const FILE = 'js/parrafos-textos/parrafos-texto-frances.json';
const existing = JSON.parse(readFileSync(FILE, 'utf8'));
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const batch = {
  "1": "<p>Les Fallas ont été déclarées Patrimoine Immatériel de l'Humanité par l'Unesco en 2016.</p>",
  "2": "<p>Suivez la carte pour contourner le monument. Face à sa façade principale, en traversant la route, vous trouverez le <strong>Pont de Serranos</strong> indiqué sur votre carte sous le numéro <mark>1</mark>.</p>",
  "2-B": "<p>En arrivant au Palau, continuez jusqu'aux Tours par lesquelles les monarques et les nobles accédaient au Royaume de Valence. Sur votre carte, elles correspondent au numéro <mark>1</mark>.</p>",
  "2-C": "<p>Revenez sur le tracé des murailles avec la voie aménagée et continuez jusqu'aux Tours par lesquelles les monarques et les nobles accédaient au Royaume de Valence, correspondant au numéro <mark>1</mark> sur votre carte.</p>",
  "2-D": "<p>En laissant ce bâtiment à votre droite, vous pouvez voir la <strong>Calle de los Serranos</strong> qui sépare et délimite les quartiers de « La Seu » ou Quartier de la Cathédrale, à droite, et le célèbre quartier d'« El Carmen » à gauche.</p>\n<p>Continuez jusqu'aux Tours par lesquelles les monarques et les nobles accédaient au Royaume de Valence, correspondant au numéro <mark>1</mark> sur votre carte.</p>",
  "2-E": "<p>Une fois le pont traversé, tournez à droite et continuez jusqu'aux Tours par lesquelles les monarques et les nobles accédaient au Royaume de Valence, correspondant au numéro <mark>1</mark> sur votre carte.</p>",
  "2-F": "<p>Êtes-vous déjà dans la <strong>Calle de los Serranos</strong> ? Tournez à droite et continuez jusqu'aux Tours par lesquelles les monarques et les nobles accédaient au Royaume de Valence. Sur votre carte, elles correspondent au numéro <mark>1</mark>.</p>",
  "2-G": "<p>Vous y êtes presque ! Continuez jusqu'au bout de la rue, puis tournez à gauche. De là, on peut déjà apercevoir les Tours. Sur votre carte, elles correspondent au numéro <mark>1</mark>.</p>",
  "3": "<p>Dirigez-vous vers votre prochain point d'intérêt, correspondant au numéro <mark>13</mark> sur votre carte.</p>",
  "3-B": "<p>Il correspond au numéro <mark>13</mark> sur votre carte.</p>",
  "3-C": "<p>Il correspond au numéro <mark>13</mark> sur votre carte.</p>",
  "3-D": "<p>À quelques pas seulement sur cette promenade piétonne, sur votre gauche, se distingue un bâtiment qui rappelle d'anciens palais islamiques, correspondant au numéro <mark>13</mark> sur votre carte.</p>\n<p>Mettez en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "3-E": "<p>En tournant le dos à la <strong>Gare du Nord</strong>, sortez de l'enceinte et prenez la voie aménagée sur votre gauche. Cette voie réservée aux véhicules de mobilité personnelle longe le tracé de l'ancienne muraille de Valence. Après plusieurs rues, vous verrez sur votre droite une zone verdoyante avec des colonnes et des palmiers. N'oubliez pas de respecter le code de la route !</p>\n<p>Mettez en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "4": `<p>Ses collections comprennent environ 10 500 œuvres illustrant les principales manifestations artistiques de l'art du XXe siècle.</p>\n<p>Il existe un projet futur prévoyant l'ajout d'un revêtement métallique enveloppant entièrement le bâtiment et l'ajout d'une galerie à l'arrière.</p>\n<p>Si vous êtes là pendant les heures d'ouverture, ${LOGO} vous recommande de mettre en pause et d'entrer dans ce musée pour profiter de ses expositions.</p>\n<p>Vous pouvez reprendre votre aventure quand vous le souhaitez. Appuyez simplement sur le bouton correspondant et continuez <i>en quête du trésor</i>.</p>`,
  "5": "<p>Suivez la carte pour contourner le monument.</p>\n<p>Face à sa façade principale, en traversant la route, vous trouverez le <strong>Pont de Serranos</strong> indiqué sur votre carte sous le numéro <mark>2</mark>.</p>",
  "5-B": "<p>Le prochain objectif de votre Aventure correspond au numéro <mark>2</mark> sur votre carte.</p>",
  "6": "<p>Il correspond au numéro <mark>3</mark> sur votre carte.</p>",
  "6-B": "<p>Il correspond au numéro <mark>3</mark> sur votre carte.</p>",
  "6-C": "<p>En sortant de la place, prenez la rue à gauche et suivez-la jusqu'au bout. Là, vous retrouverez un monument déjà visité dans cette Aventure.</p>\n<p>Le <strong>Palais de la Generalitat</strong>, qui correspond au numéro <mark>3</mark> sur votre carte.</p>",
  "7": "<p>Il correspond au numéro <mark>4</mark> sur votre carte.</p>",
  "7-B": "<p>Sur votre carte, ils sont indiqués respectivement sous les numéros <mark>4</mark> et <mark>6</mark>.</p>",
  "7-C": "<p>Prenez comme repère le <strong>Pont du Real</strong> indiqué sur votre carte sous le numéro <mark>4</mark> et continuez jusqu'au pont suivant, le <strong>Pont de l'Exposition</strong> qui correspond au numéro <mark>5</mark> sur votre carte. N'oubliez pas de mettre en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "8": "<p>Il correspond au numéro <mark>5</mark> sur votre carte.</p>",
  "8-B": "<p>Il correspond au numéro <mark>5</mark> sur votre carte.</p>",
  "8-C": "<p>En levant les yeux, vous contemplerez la façade nord de la <strong>Cathédrale de Valence</strong>.</p>\n<p>Sur votre carte, elle correspond au numéro <mark>5</mark>.</p>",
  "9": `<p>${LOGO} vous recommande de mettre en pause et de visiter cette zone à votre propre rythme.</p>`,
  "9-B": `<p>${LOGO} vous recommande de mettre en pause et de visiter cette zone à votre propre rythme.</p>`,
  "10": "<p>Il correspond au numéro <mark>6</mark> sur votre carte.</p>",
  "10-B": "<p>Il correspond au numéro <mark>6</mark> sur votre carte.</p>",
  "10-C": "<p>Votre prochain point d'intérêt dans cette Aventure correspond au numéro <mark>6</mark> sur votre carte.</p>",
  "11": "<p>Dirigez-vous jusqu'au point 7. Montez jusqu'au centre du pont en suivant la piste cyclable.</p>",
  "11-B": "<p>Il correspond au numéro <mark>7</mark> sur votre carte.</p>",
  "11-C": "<p>Maintenant que vous êtes un peu plus proche, vous pouvez résoudre votre prochain défi.</p>",
  "11-D": "<p>Sur votre carte, il est indiqué sous le numéro <mark>7</mark>.</p>",
  "11-E": `<p>Dépliez votre carte et observez attentivement votre itinéraire.</p>\n<p>Dans cette Aventure, ${LOGO} vous propose de traverser le pont qui se trouve devant vous et de trouver l'accès au célèbre <strong>Jardin du Turia</strong> de Valence.</p>\n<p>Sur votre carte, il correspond au numéro <mark>7</mark>.</p>\n<p>Cet accès se trouve du côté opposé et à gauche du pont, à quelques mètres seulement en longeant le mur de l'ancien lit de la rivière.</p>\n<p>Une fois en bas, suivez votre carte ; votre prochain objectif correspond au numéro <mark>9</mark>.</p>`,
  "12": "<p>Il correspond au numéro <mark>8</mark> sur votre carte.</p>",
  "12-B": "<p>Il correspond au numéro <mark>8</mark> sur votre carte.</p>",
  "12-C": "<p>Êtes-vous sur la <strong>Plaza del Tossal</strong> ? Oui ? Parfait ! Sur votre carte, elle correspond au numéro <mark>8</mark>.</p>",
  "12-D": "<p>Prenez comme repère le <strong>Pont du Real</strong> indiqué sur votre carte sous le numéro <mark>8</mark> et continuez jusqu'au pont suivant, qui correspond au numéro <mark>9</mark> sur votre carte. Le <strong>Pont de l'Exposition</strong>.</p>\n<p>Mettez en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place, merci.</p>",
  "13": "<p>Il correspond au numéro <mark>9</mark> sur votre carte.</p>",
  "13-B": "<p>Êtes-vous déjà au point indiqué sous le numéro <mark>9</mark> de votre carte ? Parfait !</p>",
  "13-C": "<p>Il correspond au numéro <mark>9</mark> sur votre carte.</p>",
  "14": "<p>Dirigez-vous vers le point numéro <mark>10</mark> sur votre carte.</p>",
  "14-B": "<p>Il correspond au numéro <mark>10</mark> sur votre carte.</p>",
  "14-C": "<p>Il correspond au numéro <mark>10</mark> sur votre carte.</p>",
  "15": "<p>Il correspond au numéro <mark>11</mark> sur votre carte.</p>",
  "15-B": "<p>En sortant de ce tracé irrégulier, portez votre attention sur votre droite. Votre prochain objectif dans cette chasse au trésor est la célèbre <strong>Plaza de la Virgen</strong>.</p>\n<p>Sur votre carte, elle correspond au numéro <mark>11</mark>.</p>",
  "15-C": "<p>Face à la mairie, prenez le chemin à votre gauche et suivez la carte jusqu'au bout de l'avenue, puis tournez à gauche. De l'autre côté de l'avenue se dresse la <strong>Gare du Nord</strong>, un bâtiment monumental de style moderniste inauguré en 1917, correspondant au numéro <mark>11</mark> sur votre carte.</p>\n<p>Mettez en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "15-D": "<p>Il correspond au numéro <mark>11</mark> sur votre carte.</p>",
  "16": "<p>Depuis le point 11 sur votre carte, on peut entrevoir l'un des sites les plus emblématiques de Valence.</p>",
  "17": "<p>Du numéro <mark>12</mark> au <mark>19</mark> se trouvent les monuments qui composent la <strong>Cité des Arts et des Sciences</strong>, et les numéros <mark>13</mark> et <mark>15</mark> correspondent aux ponts qui complètent la zone.</p>",
  "17-B": "<p>Du numéro <mark>18</mark> au <mark>25</mark> se trouvent les monuments qui composent la <strong>Cité des Arts et des Sciences</strong>, et les numéros <mark>19</mark> et <mark>21</mark> correspondent aux ponts qui complètent la zone.</p>",
  "18": "<p>Ils correspondent aux numéros <mark>15</mark> et <mark>18</mark> sur votre carte.</p>",
  "18-B": "<p>Ils correspondent aux numéros <mark>21</mark> et <mark>24</mark> sur votre carte.</p>",
  "19": "<p>Il correspond au numéro <mark>12</mark> sur votre carte.</p>",
  "20": "<p>Il correspond au numéro <mark>12</mark> sur votre carte.</p>",
  "20-B": "<p>Dirigez-vous jusqu'au point 12. Montez jusqu'au centre du pont en suivant la piste cyclable.</p>\n<p>N'oubliez pas de mettre en pause lorsque vous êtes en haut du pont ; continuez jusqu'à la moitié de sa longueur et appuyez à nouveau sur le bouton continuer.</p>",
  "20-C": "<p>Immédiatement après la Gare Ferroviaire, se dresse la <strong>Plaza de Toros</strong>, correspondant au numéro <mark>12</mark> sur votre carte.</p>",
  "21": "<p>Il correspond au numéro <mark>14</mark> sur votre carte.</p>",
  "21-B": "<p>Au bout de la promenade, un trésor architectural apparaît sur votre droite, correspondant au numéro <mark>14</mark> sur votre carte.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "21-C": "<p>En tournant le dos au portail baroque de la Cathédrale, face à vous s'ouvre une place qui vous invite à poursuivre votre chasse au trésor.</p>\n<p>Suivez le tracé de votre carte qui vous mène à traverser la place.</p>\n<p>Une fois la place traversée, sur votre droite, se dresse votre prochain objectif. Une élancée tour baroque se profile discrètement à droite.</p>\n<p>Sur votre carte, elle correspond au numéro <mark>14</mark>. Pouvez-vous la voir ?</p>",
  "21-D": "<p>En tournant le dos au portail baroque de la Cathédrale, face à vous s'ouvre une place qui vous invite à poursuivre votre chasse au trésor.</p>\n<p>Suivez le tracé de votre carte qui vous mène à traverser la place.</p>\n<p>Une fois la place traversée, sur votre droite, se dresse votre prochain objectif. Une élancée tour baroque se profile discrètement à droite.</p>\n<p>Sur votre carte, elle correspond au numéro <mark>10</mark>. Pouvez-vous la voir ?</p>\n<p>Ne mettez pas l'audioguide en pause et dirigez-vous vers le point indiqué, merci.</p>",
  "22": "<p>Il correspond au numéro <mark>15</mark> sur votre carte.</p>",
  "22-B": "<p>Il correspond au numéro <mark>15</mark> sur votre carte.</p>",
  "22-C": "<p>Concentrez votre attention sur l'ensemble du <strong>Bioparc</strong>, numéro <mark>15</mark> sur votre carte.</p>",
  "22-D": "<p>Comme l'indique votre carte, continuez jusqu'au bout de la rue et tournez à gauche. Notre célèbre <strong>Marché Central</strong> apparaît sur votre droite, correspondant au numéro <mark>15</mark> sur votre carte.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "22-E": "<p>Dirigez-vous vers le point numéro <mark>15</mark> sur votre carte.</p>",
  "23": `<p>${LOGO} vous recommande de mettre en pause et de visiter ce monument à votre propre rythme. N'oubliez pas qu'il n'y a pas de précipitation ; quand vous vous sentez prêt, appuyez simplement sur continuer et poursuivez votre Aventure <i>À la recherche du trésor valencien</i>.</p>`,
  "23-B": "<p>Le <strong>Palais du Marqués de Dos Aguas</strong> correspond au numéro <mark>16</mark> sur votre carte.</p>",
  "23-C": "<p>Il correspond au numéro <mark>16</mark> sur votre carte.</p>",
  "23-D": "<p>Il correspond au numéro <mark>16</mark> sur votre carte.</p>",
  "24": `<p>${LOGO} vous recommande de mettre en pause et de visiter ce monument à votre propre rythme.</p>`,
  "24-B": "<p>Utilisez le bouton pause à votre convenance ; quand vous vous sentez prêt, continuez simplement à résoudre nos défis tout en découvrant la ville.</p>\n<p>Votre Aventure se poursuit, comme l'indique votre carte, sur votre gauche en revenant sur le tracé des murailles originelles. Plus précisément, vers l'une des entrées de Valence correspondant au numéro <mark>17</mark> sur votre carte.</p>",
  "24-C": "<p>En laissant la <strong>Lonja</strong> à votre gauche et le <strong>Marché central</strong> derrière vous, dirigez-vous, comme l'indique votre carte, vers le prochain point d'intérêt de cette Aventure, le numéro <mark>17</mark>.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "24-D": "<p>Il correspond au numéro <mark>17</mark> sur votre carte.</p>",
  "24-E": "<p>En admirant la façade à arcatures aveugles de l'<strong>Église Santa Catalina</strong>, la troisième entrée monumentale de ce temple date de 1785 et se trouve au coin de la rue. C'est aussi votre prochaine direction dans cette Aventure.</p>\n<p>Faites bien attention ! Votre carte vous indique de contourner ce monument et de prendre la première rue qui s'ouvre à votre droite.</p>\n<p>Au bout de cette courte et étroite ruelle, au niveau du premier étage, se trouve votre prochain point d'intérêt.</p>\n<p>Sur votre carte, il correspond au numéro <mark>17</mark>.</p>\n<p>N'oubliez pas de mettre en pause, puis visualisez le point indiqué et appuyez sur le bouton continuer une fois sur place.</p>",
  "24-F": "<p>Il correspond au numéro <mark>17</mark> sur votre carte.</p>",
  "25": "<p>En suivant le lit de l'ancienne rivière, à environ 50 mètres se trouve l'esplanade d'où sont tirés les feux d'artifice.</p>\n<p>Si vous avez eu l'occasion de nous rendre visite pendant cette fête, vous aurez pu constater que les Valenciens aiment la poudre à canon.</p>",
  "26": `<p>${LOGO} vous conseille de mettre en pause et de visiter ce complexe historique à votre propre rythme.</p>\n<p>Vous pouvez reprendre votre aventure quand vous le souhaitez.</p>`,
  "26-B": `<p>${LOGO} vous conseille de mettre en pause et de visiter ce complexe historique à votre propre rythme.</p>\n<p>Vous pouvez reprendre votre aventure quand vous le souhaitez.</p>`,
  "27": "<p>Il correspond au numéro <mark>18</mark> sur votre carte.</p>",
  "27-B": "<p>Il correspond au numéro <mark>18</mark> sur votre carte.</p>",
  "27-C": "<p>Votre aventure se poursuit avec le bâtiment correspondant au numéro <mark>18</mark> sur votre carte.</p>",
  "27-D": "<p>Votre Aventure se poursuit, comme l'indique votre carte, en suivant le tracé des murailles.</p>\n<p>Quelques mètres plus loin, 3 points consécutifs vous attendent dans votre Aventure.</p>\n<p>Sur votre carte, ils correspondent aux numéros <mark>18</mark>, <mark>19</mark> et <mark>20</mark> successivement.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "28": "<p>Il correspond au numéro <mark>19</mark> sur votre carte.</p>",
  "28-B": "<p>Il correspond au numéro <mark>19</mark> sur votre carte.</p>",
  "29": `<p>${LOGO} vous conseille de mettre en pause et de visiter ce complexe historique à votre propre rythme.</p>\n<p>Vous pouvez reprendre votre aventure quand vous le souhaitez.</p>`,
  "30": "<p>Une fois que vous décidez de continuer <i>en quête du trésor</i>, dirigez-vous par la partie gauche de l'ancien lit jusqu'au numéro <mark>6</mark> sur votre carte.</p>",
  "30-B": "<p>Une fois que vous décidez de continuer <i>en quête du trésor</i>, dirigez-vous par la partie gauche de l'ancien lit jusqu'au numéro <mark>11</mark> sur votre carte.</p>",
  "31": "<p>Il correspond au numéro <mark>20</mark> sur votre carte.</p>",
  "32": "<p>Il correspond au numéro <mark>21</mark> sur votre carte.</p>",
  "32-B": "<p>Il correspond au numéro <mark>21</mark> sur votre carte.</p>",
  "32-C": "<p>Suivez votre carte au trésor et en chemin, sur votre droite, se dresse la première fontaine d'eau potable publique de la ville.</p>\n<p>Surnommée la <strong>Fuente del Negrito</strong>, elle correspond au numéro <mark>21</mark> sur votre carte. C'est l'une de vos dernières étapes dans cette aventure.</p>\n<p>Mettez en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "33": "<p>Il correspond au numéro <mark>22</mark> sur votre carte.</p>",
  "33-B": "<p>Continuez jusqu'au bout de la rue où croise la <strong>Calle Caballeros</strong>, correspondant au numéro <mark>22</mark> sur votre carte. Une fois là, tournez à droite et vous verrez l'emblématique <strong>Palais de la Generalitat</strong>, indiqué sous le numéro <mark>23</mark> sur votre carte.</p>\n<p>Mettez en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "33-C": "<p>Sur votre carte, ils sont indiqués respectivement sous les numéros <mark>22</mark> et <mark>24</mark>.</p>",
  "34": "<p>Il correspond au numéro <mark>23</mark> sur votre carte.</p>",
  "34-B": "<p>Il correspond au numéro <mark>23</mark> sur votre carte.</p>",
  "35": "<p>Il correspond au numéro <mark>24</mark> sur votre carte.</p>",
  "35-B": "<p>Prenez les escaliers ou la rampe permettant de monter à ce belvédère, correspondant au numéro <mark>24</mark> sur votre carte.</p>",
  "36": "<p>Sur votre carte, il est indiqué sous le numéro <mark>25</mark>.</p>",
  "37": "<p>Il correspond au numéro <mark>26</mark> sur votre carte.</p>",
  "38": "<p>Êtes-vous déjà au point indiqué sous le numéro <mark>27</mark> de votre carte ? Parfait !</p>",
  "39": "<p>Il correspond au numéro <mark>27</mark> sur votre carte.</p>\n<p>Mettez en pause et approchez-vous du <strong>Palais de Justice</strong> pour le contempler dans son intégralité.</p>",
  "40": "<p>Il correspond au numéro <mark>28</mark> sur votre carte.</p>",
  "40-B": "<p>Cet espace correspond au numéro <mark>28</mark> sur votre carte.</p>",
  "41": "<p>Il correspond au numéro <mark>29</mark> sur votre carte.</p>",
  "42": "<p>Il correspond au numéro <mark>30</mark> sur votre carte.</p>",
  "43": "<p>Le <strong>Palais du Marqués de Dos Aguas</strong> correspond au numéro <mark>31</mark> sur votre carte.</p>",
  "43-B": "<p>Il correspond au numéro <mark>31</mark> sur votre carte.</p>",
  "44": "<p>Il correspond au numéro <mark>32</mark> sur votre carte.</p>",
  "44-B": "<p>Dirigez-vous vers la porte de style roman de la <strong>Cathédrale</strong>, correspondant au numéro <mark>32</mark> sur votre carte ; en chemin, regardez vers le haut sur votre gauche.</p>\n<p>Une tour octogonale de la fin du XVe siècle se dresse derrière la cathédrale.</p>",
  "45": "<p>Votre aventure se poursuit avec le bâtiment correspondant au numéro <mark>33</mark> sur votre carte.</p>",
  "45-B": "<p>En admirant la porte la plus ancienne de la <strong>Cathédrale de Valence</strong>, portez votre attention sur sa façade nord. Vous pourrez la contempler dans toute sa splendeur depuis la <strong>Plaza de la Almoina</strong> qui se trouve à votre droite.</p>\n<p>Dirigez-vous vers le centre de la place. Sur votre carte, elle correspond au numéro <mark>33</mark>.</p>",
  "45-C": "<p>Votre aventure se poursuit en ce même endroit, correspondant au numéro <mark>33</mark> sur votre carte.</p>",
  "45-D": "<p>Placez-vous au centre de la place indiquée par le numéro <mark>33</mark> sur votre carte ; de là, vous pouvez voir une partie de la coupole de la basilique, d'environ 19 mètres de diamètre et à plan ovale.</p>",
  "45-E": "<p>Il correspond au numéro <mark>33</mark> sur votre carte.</p>",
  "45-F": "<p>Il correspond au numéro <mark>33</mark> sur votre carte.</p>",
  "46": "<p>Il correspond au numéro <mark>34</mark> sur votre carte.</p>",
  "46-B": "<p>Il correspond au numéro <mark>34</mark> sur votre carte.</p>",
  "47": "<p>Il correspond au numéro <mark>35</mark> sur votre carte.</p>",
  "47-B": "<p>Il correspond au numéro <mark>35</mark> sur votre carte. Ce sera votre dernière étape.</p>",
  "48": "<p>Il correspond au numéro <mark>39</mark> sur votre carte.</p>",
  "48-B": "<p>Avec la <strong>Tour de Santa Catalina</strong> en face, regardez, s'il vous plaît, sur votre droite. Concentrez votre attention au fond de la place ; votre prochain objectif est le célèbre <strong>Micalet</strong> qui se dresse au-dessus de la Cathédrale. Ce belvédère élancé correspond au numéro <mark>39</mark> sur votre carte. Pouvez-vous le voir ?</p>",
  "49": "<p>Suivez le tracé de votre carte qui vous indique de longer la <strong>Cathédrale</strong> avec la façade sur votre gauche. Autrement dit, avec le portail baroque de la cathédrale en face, tournez à droite et continuez jusqu'à la porte romane du temple.</p>\n<p>Sur votre carte, elle correspond au numéro <mark>40</mark>.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "49-B": "<p>Concentrez à nouveau votre attention sur la <strong>Cathédrale de Valence</strong>, numéro <mark>40</mark> sur votre carte.</p>",
  "50": "<p>Il correspond au numéro <mark>41</mark> sur votre carte.</p>"
};
const merged = { ...existing, ...batch };
writeFileSync(FILE, JSON.stringify(merged, null, 2), 'utf8');
console.log('Total entradas:', Object.keys(merged).length);
