import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "670": "<p>Bewonder dit gebedsgebouw van dichtbij; enkele kleine stappen verderop in de straat aan uw linkerkant verrijst een ander monument dat in dit avontuur het vermelden waard is.</p>\n\n<p>Dit correspondeert met nummer <mark>83</mark> op uw kaart.</p>\n\n<p>Pauzeer deze audiogids niet en begeef u naar het aangegeven punt.</p>",
  "670-B": "<p>Bewonder dit gebedsgebouw van dichtbij; enkele kleine stappen verderop in de straat aan uw linkerkant verrijst een ander monument dat in dit avontuur het vermelden waard is.</p>\n\n<p>Dit correspondeert met nummer <mark>30</mark> op uw kaart.</p>\n\n<p>Pauzeer deze audiogids niet en begeef u naar het aangegeven punt.</p>",
  "671": "<p>U staat op het punt het Arabische Koninkrijk Valencia te betreden.</p>\n\n<p>Vanaf de \"Barrio del Mercat\" tot de beroemde \"Barrio del Carmen\" getuigen talrijke archeologische vondsten van het belang dat de stad had bereikt.</p>\n\n<p>Met de herovering van Valencia door Jaime I in 1238 werd een einde gemaakt aan vijf eeuwen moslimcultuur; desondanks liet deze een diepe stempel achter op het Valenciaanse grondgebied.</p>",
  "672": `<p>De 13e eeuw was, voor Valencia, de overgangsperiode tussen het Romaans en de gotiek, ook tussen het islamitische en het christelijke.</p>\n\n<p>De Iglesia de San Juan del Hospital bewaart reminiscenties aan die transformaties.</p>\n\n<p>Het historische complex bezit duidelijke Arabische invloeden in de rechthoekige plattegrond die typisch was voor de mudéjar-stijl.</p>\n\n<p>Een uitbreiding, ditmaal in gotische stijl, werd uitgevoerd in het jaar 1316.</p>\n\n<p>De funeraire ziekenhuiskapel was waarschijnlijk de eerste manifestatie van de spitsboogkunst in het Valencia van de 13e eeuw.</p>\n\n<p>De Iglesia de San Juan del Hospital werd in 1943 verklaard tot Nationaal Artistiek Monument.</p>\n\n<p>Als u hier bent tijdens de openingstijden, raadt ${LOGO} u aan op pauze te drukken en dit historische complex op uw eigen tempo te bezoeken.</p>\n\n<p>U kunt uw avontuur hervatten wanneer u dat wenselijk acht. Druk eenvoudigweg op de betreffende knop en ga verder <i>op zoek naar de schat</i>.</p>`,
  "673": "<p>De oorsprong van het Paleis gaat terug tot de 13e eeuw. Dit gebouw onderging voortdurende verbouwingen, waarvan de belangrijkste in de 18e eeuw werd uitgevoerd; waarbij het interieur en de gevel werden gewijzigd.</p>\n\n<p>In 1936, bij het begin van de Spaanse Burgeroorlog, werd het gebouw herhaaldelijk in brand gestoken waardoor het werd verwoest, behalve een deel van de kapel die drie dagen achtereen bleef branden.</p>\n\n<p>Bij deze branden gingen bijna 13.000 geschreven banden verloren en het Diocesaan Museum met alle kunstwerken die zich daarin bevonden. Het huidige gebouw, in eclectische stijl, werd herbouwd tussen 1941 en 1946.</p>",
  "674": "<p>Aan de overkant van het plein bevindt zich het Palacio del Marqués de Campo. Kunt u het zien?</p>\n\n<p>Dit correspondeert met nummer <mark>85</mark> op uw kaart.</p>\n\n<p>Het gebouw gaat terug tot de 18e eeuw, maar in de 19e eeuw voerde de Markies van Campo een volledige renovatie uit.</p>\n\n<p>Jaren later en na verschillende eigenaars te hebben gehad, verklaarde de Gemeenteraad het Paleis tot Historisch-Artistiek Monument van lokaal belang.</p>\n\n<p>Dit feit uit 1973 verbeterde zijn status in 1982 toen het de categorie Historisch-Artistiek Monument van provinciaal belang verkreeg.</p>\n\n<p>In 1989, na een kostbare en toegewijde restauratie, werd het Paleis in gebruik genomen als Zetel van het Stadsmuseum.</p>\n\n<p>Tegenwoordig herbergt het museum belangrijke collecties die tot dan toe verspreid waren over verschillende gebouwen.</p>\n\n<p>Deze helpen ons meer te begrijpen over de Valenciaanse geschiedenis van de Romeinse stichting tot het midden van de 14e eeuw.</p>\n\n<p>Tevens wordt het museum ook gebruikt als zaal voor tijdelijke tentoonstellingen; verspreid door het museum is een belangrijke collectie Valenciaanse kunst uit de 20e eeuw te bewonderen.</p>\n\n<p>Op de bovenste verdieping wordt een collectie van maten en gewichten tentoongesteld.</p>",
  "675": `<p>Links van het Museum geeft een discrete ingang toegang tot een interessant punt in dit Avontuur.</p>\n\n<p>Dit correspondeert met nummer <mark>86</mark> op uw kaart.</p>\n\n<p>Op deze plek bevond zich een van de gevangenissen waar de Heilige Vincent Martelaar in de 4e eeuw na Christus werd opgesloten en die in 304 stierf zonder zijn geloof op te geven nadat hij door de Romeinen was gemarteld.</p>\n\n<p>Het interieur herbergt een funeraire kapel in uitzonderlijke staat van bewaring uit de Visigotische periode, dat wil zeggen de 6e en 7e eeuw na Christus.</p>\n\n<p>Als u hier bent tijdens de openingstijden, beveelt ${LOGO} u aan op pauze te drukken en deze historische schatten te betreden om de geschiedenis van de stad beter te leren kennen.</p>\n\n<p>U kunt uw avontuur hervatten wanneer u dat wenselijk acht; druk eenvoudigweg op de betreffende knop en ga verder <i>op zoek naar de schat</i>.</p>\n\n<p>Uw avontuur gaat verder op dit zelfde punt.</p>`,
  "676": "<p>Ga verder door de smalle straat; wanneer u die verlaat, verrijst er precies tegenover het gebouw van de Almudín, nummer <mark>87</mark> op uw kaart.</p>\n\n<p>Almudín is afgeleid van het Arabische woord \"Almud\", de naam van een gewichtsmaat, vergelijkbaar met een ons of een gram.</p>",
  "677": "<p>Waarvoor zou het gebouw bestemd kunnen zijn geweest?</p>\n\n<p>Graanopslag, gemeentelijke slagerij of misschien specerijenhandel?</p>",
  "678": "<p>Vanaf 1307 en gebouwd op een oud versterkt moslimkasteel, is dit gebouw een opslagplaats en handelplaats voor tarwe en graan van Valencia geweest; zodat wij ons een idee kunnen vormen van het belang dat een gebouw met deze kenmerken vertegenwoordigde in het middeleeuwse Valencia.</p>\n\n<p>Daartoe werd een complex netwerk van functionarissen gecreëerd die verantwoordelijk waren voor deze belangrijke taak.</p>\n\n<p>Stelt u zich tevens voor dat het ontbreken van graan en meel, en dus van brood, een bron van plunderingen en opstanden kon zijn met onvoorspelbare gevolgen.</p>\n\n<p>Vandaar de noodzaak om een geventileerde maar moeilijk toegankelijke plaats te hebben; let op de hoogte van de ramen en hun afmetingen.</p>\n\n<p>Tegenwoordig is het gebouw, eigendom van de gemeente, ingericht als tijdelijke Stedelijke Tentoonstellingszaal.</p>",
  "679": "<p>Bravo! U staat op het punt uw avontuur te voltooien.</p>\n\n<p>Bekijk uw kaart die aangeeft dat u weer naar de Plaza de la Virgen gaat. Die zou aan uw linkerkant moeten liggen. Stel u op met de Fontein van Neptunus achter u en kijk naar de straat die voor u ligt.</p>\n\n<p>Vergeet niet op pauze te drukken, ga daarna naar het aangegeven punt en druk opnieuw op de knop doorgaan zodra u op de voorgestelde plek aankomt.</p>",
  "680": "<p>Bent u op het voorgestelde punt aangekomen? Goed! Pauzeer deze audiogids niet.</p>\n\n<p>Vouw uw kaart open en u zult zien dat die u aanzet terug te keren naar het startpunt. Ja, naar nummer <mark>1</mark>!</p>\n\n<p>Bravo! Dat is uw laatste stop en daarmee hebt u 34 kilometer van historische en recente architectonische schatten afgelegd zonder Valencia te verlaten!... nou ja... bijna.</p>\n\n<p>Volg de loop van de straat waar talrijke etablissementen u zullen verleiden de lokale gastronomie te proeven; uw doel ligt aan het einde van de straat, door naar links te draaien.</p>",
  "681": "<p>Wij zouden graag twee laatste korte bijzonderheden met u delen die zich links en rechts bevinden in de loop van de weg.</p>\n\n<p>Op uw kaart komen ze overeen met de nummers <mark>88</mark> en <mark>89</mark> respectievelijk.</p>",
  "682": "<p>Ongeveer halverwege de straat, aan de linkerkant, verrijst de Iglesia de San Lorenzo, nummer <mark>88</mark> op uw kaart.</p>\n\n<p>De oorsprong van de Iglesia de San Lorenzo gaat terug tot de herovering zelf van Valencia in 1238. Net als de Iglesia de Santa Catalina, die in dit Avontuur werd vermeld.</p>\n\n<p>Bedenk dat, na de herovering en de daaropvolgende godsdienstverandering van de stad, Jaime I de stedelijke ruimte structureerde.</p>",
  "682-B": "<p>Ongeveer halverwege de straat, aan de rechterkant, verrijst de Iglesia de San Lorenzo.</p>\n\n<p>De oorsprong van de Iglesia de San Lorenzo gaat terug tot de herovering zelf van Valencia in 1238.</p>\n\n<p>Na de herovering en de daaropvolgende godsdienstverandering van de stad, structureerde Jaime I de stedelijke ruimte.</p>",
  "683": "<p>Wat draagt Sint Laurentius in zijn hand? Een duif, een lepel of misschien een rooster?</p>",
  "684": "<p>Merk op de bovenste hoek een kleine balkontoren overdekt door een koepel, die het uitzicht biedt op beide kanten van de straten waar de portalen van de kerk zich bevinden. Eigenaardig, nietwaar?</p>",
  "685": "<p>Enkele stappen verderop, aan de rechterkant van de straat, verrijst een gebouw in gotische stijl. Het was de residentie van Paus Rodrigo Borgia tijdens zijn talrijke bezoeken aan Valencia.</p>\n\n<p>Les Corts Valencianes komen overeen met nummer <mark>89</mark> op uw kaart. Kunt u het zien? Tegenwoordig is het gewijd aan bestuurlijke activiteiten.</p>\n\n<p>Gefeliciteerd! U bent op de goede weg!</p>",
  "686": "<p>Het paleis werd gebouwd in de 15e eeuw; zijn voornaamste kenmerk is zijn uitgestrekte gevel. In de Late Middeleeuwen werd de faam van een familienaam of familie ook gemeten aan de hand van de omvang van zijn paleis. Deze zo uitgebreide gevel deed een superieure macht en adel vermoeden.</p>\n\n<p>Ondanks de weelde van het Paleis was het niet de gebruikelijke verblijfplaats van zijn eigenaren, die hun vaste woonplaats hadden in Gandía, een plaats in de buurt van Valencia.</p>",
  "687": "<p>Elke 1 maart kleurt de stad zich in de tinten van bloemen en buskruit om de lente te verwelkomen en meer dan een miljoen bezoekers.</p>\n\n<p>Vanaf 1954 en van deze zelfde torens klinkt elk jaar het startschot van de Fallas-festiviteiten. De langverwachte \"Cridà\" is de uitnodiging tot het feest door de Fallas-koninginnen van Valencia voor wie wenst deel te nemen.</p>",
  "688": `<p>Begeef u naar het midden van de brug en kijk links en rechts.</p>\n\n<p>Aan uw linkerkant ligt de weg waarlangs u gekomen bent, en aan uw rechterkant meer dan drie kilometer tuin die uitmondt in de beroemde Ciudad de las Artes y de las Ciencias.</p>\n\n<p>Het futuristische beeld dat het nieuwe Valencia symboliseert; een uniek geheel van architectonische avant-garde op wereldniveau waar miljoenen bezoekers elk jaar naartoe komen om te genieten van cultuur, natuur, kunst en wetenschap.</p>\n\n<p>${LOGO} zal u gedetailleerde informatie geven over dat gebied in Avontuur nummer 3.</p>`,
  "689": "<p>Het avontuur dat u gaat verkennen volgt een groot deel van de route van de oude christelijke stadsmuur van Valencia.</p>",
  "690": `<p>Tegenwoordig begint de Bloemenhulde (Ofrenda de las flores) op de 17e tot de vroege ochtend van 19 maart en overstijgt honderddertigduizend Falleras en Falleros, waarbij de Plaza de la Virgen vol bloemen komt te staan.</p>\n\n<p>${LOGO} zal u gedetailleerde informatie geven over dit feest in uw Speciale Avontuur Fallas.</p>`,
  "691": "<p>Bravo, u bent zojuist op de helft van uw avontuur aangekomen! Ga verder over de beroemde calle del hospital. Zoals uw kaart aangeeft, ga verder tot het einde van de straat en sla linksaf. Onze beroemde Mercado Central opent zich aan uw rechterkant; op uw kaart komt dit overeen met nummer <mark>15</mark>.</p>\n\n<p>Vergeet niet op pauze te drukken, ga daarna naar het aangegeven punt en druk opnieuw op de knop doorgaan zodra u op de voorgestelde plek aankomt.</p>",
  "692": "<p>Wij hebben een curiositeit voor u klaarliggen: links van het gebouw van het Gemeentehuis verrijst een ander monumentaal gebouw. Boven op de gevel, in zijn bovenste deel, valt het enorme leeuwenstandbeeld van de Assic op, gemaakt in brons. Een symbool van de verzekeringsmaatschappij die het gebouw vroeger in gebruik had.</p>",
  "693": "<p>Precies links van dit gebouw verrijst een ander niet minder monumentaal gebouw.</p>\n\n<p>Een modernistisch gebouw uit het begin van de 20e eeuw. Het valt op door zijn drie grote ramen op de afgeschuinde hoek.</p>\n\n<p>Het buitenwerk is van hout, met luiken in Amerikaanse stijl in de openingen, smeedijzeren balkons, behalve het centrale balkon van de hoofdverdieping, dat in metselwerk werd gebouwd.</p>\n\n<p>Het gebouw is afgesloten met gothisch geïnspireerde pinakels en modernistisch geïnspireerde kantelen.</p>\n\n<p>In zijn bovenste deel staat het opschrift \"LA EQUITATIVA\", een voormalige verzekeringsmaatschappij die inmiddels verdwenen is en haar hoofdkantoor in dit gebouw had.</p>\n\n<p>Boven het opschrift staat de godin van de rechtvaardigheid.</p>",
  "693-B": "<p>Wat draagt het beeld in zijn hand? Is het een weegschaal, een boek of misschien een pen?</p>",
  "693-C": "<p>Precies links van dit gebouw verrijst een ander niet minder monumentaal gebouw. Dit correspondeert met nummer <mark>14</mark> op uw kaart.</p>\n\n<p>Dit is een modernistisch gebouw uit het begin van de 20e eeuw. Het valt op door zijn drie grote ramen op de afgeschuinde hoek.</p>\n\n<p>Het buitenwerk is van hout, met luiken in Amerikaanse stijl in de openingen, smeedijzeren balkons, behalve het centrale balkon van de hoofdverdieping, dat in metselwerk werd gebouwd.</p>\n\n<p>Het gebouw is afgesloten met gothisch geïnspireerde pinakels en modernistisch geïnspireerde kantelen.</p>\n\n<p>In zijn bovenste deel staat het opschrift \"LA EQUITATIVA\", een voormalige verzekeringsmaatschappij die inmiddels verdwenen is en haar hoofdkantoor in dit gebouw had.</p>\n\n<p>Boven het opschrift de godin van de rechtvaardigheid.</p>",
  "694": "<p>In de loop van uw tocht moet u de beroemde Plaza de la Reina oversteken; een recente restauratie heeft een van de bekendste pleinen van de historische kern gemoderniseerd, het verkeer verwijderd en de ondergrondse parkeerplaats vernieuwd. Na 18 maanden restauratie herrijst de centrale Plaza de la Reina met meer dan 12.000 vierkante meter voetgangersgebied en biedt prachtige uitzichten op de Kathedraal van Valencia.</p>\n\n<p>Kijk goed terwijl u loopt; u kunt de kalksteen zien die op het plein is gebruikt, dezelfde waarmee de Kathedraal is gebouwd. Kalksteen wordt traditioneel in Valencia gebruikt omdat het de warmte minder absorbeert dan graniet, wat op hete zomerdagen verkoeling biedt.</p>",
  "695": "<p>Uw avontuur gaat verder om de hoek, vanwaar u de voorkant van de Miguelete kunt zien en ook de Barokke deur van de Kathedraal van Valencia; de derde die werd gebouwd. Op uw kaart correspondeert dit met nummer <mark>13</mark>.</p>\n\n<p>Pauzeer deze audiogids indien u dat nodig acht; eenmaal u uw bestemming bereikt heeft, plaatst u zich op een plek vanwaar u de barokke deur in zijn geheel kunt zien. Dank u.</p>",
  "696": "<p>Sta niet te dicht bij de Mascletà; u kunt vlekken oplopen van de gekleurde papiertjes afkomstig van de exploderende vuurwerkstukken. Ga met uw rug naar de wind staan; zo vermijdt u de rook en de papiertjes.</p>",
  "697": "<p>Recyclen is fundamenteel in het tijdperk waarin wij leven; gebruik alstublieft de daarvoor bestemde containers.</p>",
  "698": "<p>Fallas is een traditie waarbij alle soorten culturen, religieuze, politieke en seksuele overtuigingen betrokken zijn. Respect is fundamenteel om uw verblijf tijdens het feest de moeite waard te maken om te herinneren.</p>",
  "699": "<p>Gebruik de pauzeknop naar eigen goeddunken. Wanneer u dat besluit, ga dan eenvoudigweg verder met het oplossen van onze uitdagingen terwijl u de stad ontdekt. Uw volgende doel bevindt zich aan het einde van het plein aan uw rechterkant. Op uw kaart correspondeert dit met nummer <mark>10</mark>.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
