import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "320": "<p>Het oorspronkelijke doel van dit soort spektakels was dat de adel hun waarde kon bewijzen tegenover een stier. Een van de totemberen in de Spaanse cultuur.</p>\n<p>Vóór de huidige stierengevechten werd het stierenspel te paard beoefend op een plaza van houten constructie die op deze zelfde plek stond, maar die door de Valencianen zelf werd gesloopt tijdens de Onafhankelijkheidsoorlog om te voorkomen dat de Fransen er een versterking van zouden maken.</p>",
  "321": "<p>Gezien de grote ontvangst van het stierengevecht te voet, werd besloten tot de bouw van een <strong>Plaza de Toros</strong> met een permanent karakter.</p>\n<p>De huidige <strong>Plaza de Toros</strong> werd aangevangen in 1850 en gebouwd door ploegen van gevangenen; de officiële inhuldiging vond plaats in 1861.</p>\n<p>In zijn tijd was het de grootste van Spanje met een arena van 52 meter diameter, een hoogte van bijna 17 meter en een capaciteit voor ongeveer 17.000 toeschouwers.</p>\n<p>In 1995 werd het aantal plaatsen teruggebracht tot ongeveer 12.800, het huidige aantal.</p>",
  "322": "<p>Hoeveel verdiepingen heeft dit Monument dat in 1983 werd uitgeroepen tot Nationaal Historisch-Artistiek Monument?</p>",
  "323": "<p>Het is vermeldenswaard dat in de 21e eeuw de huidige <strong>Plaza de Toros</strong> ook een multiculturele ruimte is die allerlei evenementen aanbiedt.</p>\n<p>Als weetje zeggen we dat men inderdaad kan weten of er al dan niet een stierengevecht is, en zelfs de categorie ervan.</p>\n<p>Als de vlaggen op de masten wapperen, is er een stierengevecht. Als er geen vlaggen zijn, is de arena gesloten.</p>",
  "323-B": "<p>Een gebouw uit de 19e eeuw in neoclassicistische stijl, gebouwd in baksteen.</p>\n<p>Het is vermeldenswaard dat in de 21e eeuw de huidige Plaza de Toros ook een multiculturele ruimte is die allerlei evenementen aanbiedt.</p>",
  "324": "<p>Rechts van dit 19e-eeuwse gebouw in neoclassicistische stijl, gebouwd in baksteen, doemt uw volgende doel in dit Avontuur op.</p>",
  "325": "<p>Een monumentaal gebouw in modernistische stijl, ingewijd in 1917 en uitgeroepen tot Historisch-Artistiek Monument in 1961.</p>",
  "326": "<p>Let goed op de gevel van de eerste toren! Welk citrusfruit dat van nature in Valencia voorkomt versiert de gevel? Zijn het citroenen, grapefruits of sinaasappels?</p>",
  "327": `<p>Het gebouw bestaat zelf uit twee ruimten langs de sporen en een derde die de hoofdgevel van het gebouw vormt.</p>\n<p>Terwijl u het monument bewondert, zijn er landbouwproducten te zien die de gevels versieren en een grote adelaar op de aardbol, symbool van de snelheid.</p>\n<p>${LOGO} nodigt u uit op pauze te drukken en uw avontuur voort te zetten in het interieur van het gebouw, waar u een luxueuze lobby van edelhout zult ontdekken.</p>`,
  "328": "<p>Bent u er al binnen? Let goed op; ingebed in de pilasters zijn mozaïeken te zien met de zin «Buen Viaje» (Goede Reis) in verschillende talen.</p>",
  "329": "<p>Kunt u uw taal vinden?</p>",
  "330": `<p>In het interieur van wat vroeger de cafetaria was, zijn allegorische mozaïeken te bewonderen over de Valenciaanse huerta met details zoals de <strong>Albufera</strong>, de Valenciaanse barracas, de palmboomgaarden en de beroemde <strong>Miguelete</strong>.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit historische monument op uw eigen tempo te bezoeken. U kunt uw avontuur hervatten zodra u het geschikt acht.</p>`,
  "331": "<p>Verlaat het gebouw als u zo vriendelijk wilt zijn en stel u op met de rug naar het station; vouw dan uw kaart open en bekijk hem.</p>\n<p>Naarmate u het tracé van de route volgt, kunt u zien dat het u naar de <strong>Plaza del Ayuntamiento</strong> leidt.</p>\n<p>Vanuit het midden van het plein zijn er verscheidene punten van groot belang te zien. Dit is ook een perfect punt om te genieten en prachtige foto's te maken van de architectonische schatten die de stad biedt.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>27</mark>.</p>\n<p>Om uw doel te bereiken, steek de Laan over en betreed het historische Valencia; vergeet de verkeersregels niet te respecteren.</p>\n<p>Druk op pauze, ga naar of bekijk het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "332": "<p>De gebouwen die de omgeving vormen samen met de huidige <strong>Plaza del Ayuntamiento</strong> zijn uitgeroepen tot Historisch-Artistiek Ensemble.</p>\n<p>Aan uw rechterhand op het plein zelf valt een gebouw in Neoclassicistische stijl op. Kunt u het zien?</p>",
  "333": "<p>Bravo, u heeft uw avontuur bijna voltooid!</p>",
  "334": "<p>Het monument is gebouwd op het vroegere Casa de Enseñanza, waaraan tussen 1901 en 1904 verschillende vleugels werden toegevoegd en ook belangrijke wijzigingen aan de buitenkant werden aangebracht.</p>\n<p>Tegenwoordig beslaat het een bouwblok van 6.173 vierkante meter en heeft het gevels aan vier straten.</p>",
  "335": "<p>Ga, als u zo vriendelijk wilt zijn, naar de hoofdgevel en stel u op om het in zijn geheel te kunnen zien.</p>\n<p>Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "336": "<p>Op de hoofdgevel valt een groot stenen balkon op, gebouwd tussen 1965 en 1967, dat steunt op vier zuilen.</p>",
  "337": "<p>Boven dit balkon, op de kroonlijst van de centrale toren, valt het stadswapen op dat gedragen wordt door twee naakte vrouwenfiguren: één draagt een schilderspalet in haar hand, allegorie van «Las Artes» (de Kunsten), en de andere een boek, allegorische figuur van «Las Letras» (de Letteren).</p>",
  "338": "<p>Weet u nog welk dier het stadswapen kroont? Is het een draak, een vleermuis of een paard? Kunt u het zien?</p>",
  "339": "<p>De oude legendes vertellen dat in de tijd dat Valencia een Arabische stad was, men geloofde dat als vleermuizen over de stad vlogen, die altijd van hen zou blijven.</p>\n<p>In 1238, het jaar van de Reconquista, was het precies een vleermuis die de religieuze koers van de stad veranderde. Een koers die tot op de dag van vandaag voortduurt.</p>\n<p>Tijdens het beleg van het oude «Balansiya», terwijl het leger van Koning Jaime de Eerste sliep, infiltreerde een vijandelijke groep het kamp met de bedoeling de koning te doden.</p>\n<p>Het toeval wilde dat een vleermuis die in de buurt vloog, tegen een trommel botste en de troepen wekte met het lawaai; een daad die de inval zou voorkomen en de inname van de stad zou bewerkstelligen.</p>\n<p>Na dit «wonder» brengt de koning eerbetoon aan het dier en symboliseert het bovenaan het schild.</p>\n<p>Het is zeker dat vleermuizen altijd van grote hulp zijn geweest, zoals zwaluwen en gierzwaluwen, om muggen en andere vliegende insecten te eten en zo het welzijn van de burgers te bewaren.</p>",
  "340": "<p>Richt uw aandacht op de grote deur met rechte bovenzijde die toegang geeft tot het gebouw.</p>\n<p>Ga, als u zo vriendelijk wilt zijn, naar de hoofdingang.</p>",
  "341": "<p>Eenmaal binnen is het eerste wat opvalt de grote marmeren trap die toegang geeft tot de bovenverdieping.</p>\n<p>Tijdens de burgeroorlog van 1936 tot 1939 werd deze trap gedeeltelijk verwoest; later werd hij herbouwd met het originele ontwerp van 1924.</p>\n<p>Het <strong>Ayuntamiento van Valencia</strong> herbergt in zijn interieur twee belangrijke zalen: de Glazen Zaal, ingewijd in 1929, een grote zaal met natuurlijke verlichting via gekleurde glasramen.</p>\n<p>Ook, sinds 1927, het Gemeentelijk Historisch Museum met bijzonder emblematische stukken zoals de Arabische sleutel die de hoofdingang van de stad opende, het zwaard en het schild van koning Jaime de Eerste, en het «Penó de la Conquesta», de vlag die werd gehesen op de toren van Ali Bufat van de poort van Bab al-Sakhar op 28 september 1238, wat de overgave markeerde van de islamitische stad Balansiya aan de christenen van koning Jaime de Eerste.</p>",
  "342": "<p>Aan de andere kant van het plein verschijnt een architectonische schat aan uw rechterhand.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>29</mark>.</p>\n<p>Druk op pauze, ga naar of bekijk het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "343": "<p>Het <strong>Palacio de Comunicaciones</strong>, ook bekend als het postgebouw, is sinds 1922 de instantie belast met het verzenden, ontvangen, sorteren, verwerken, overdragen of bezorgen van post, onder vele andere functies.</p>\n<p>Boven het dak steekt een toren van 30 meter hoogte uit, bekroond met een aardbol.</p>\n<p>Deze toren werd geplaatst in 2014 en is een exacte replica van de oude telecommunicatietoren die op dezelfde plek stond.</p>\n<p>Door het interieur van deze toren loopt een wenteltrap die opgang geeft naar het uitkijkpunt.</p>\n<p>Onder deze toren, op het centrale lichaam, dragen twee groepen gevleugelde wezens post- en telegraafberichten: één groep op een locomotief en de andere op een schip (allegorie voor de bescherming van de boodschappers over land en zee).</p>",
  "344": "<p>Boven de hoofdingang, in een rondboog, vertegenwoordigen allegorische figuren de vijf continenten.</p>\n<p>Wat draagt de centrale figuur? Een Kroon, een Zwaard of misschien een Fakkel?</p>",
  "345": `<p>Met de postgevels voor u, ga naar uw linkerhand, zoals uw kaart aangeeft, tot aan de <strong>Calle de las Barcas</strong>, de tweede straat aan uw rechterhand.</p>\n<p>${LOGO} raadt u aan het volgende bezienswaardigheidspunt te voet te bereiken; vergeet niet dat de verkeersregels gevolgd moeten worden, waarbij in dit geval de voetganger voorrang heeft.</p>\n<p>Zet deze audiogids niet op pauze en ga naar het aangegeven punt, dank u.</p>\n<p>Bijna! Het zijn slechts een paar meter! Vergeet niet: kijk naar het gebouw, draai links en neem de tweede straat rechts.</p>`,
  "346": `<p>Als u er bent tijdens de openingsuren, moedigt ${LOGO} u aan een pauze te nemen en een goede plek te kiezen.</p>\n<p>Het is de perfecte plek om halt te houden en prachtige foto's te maken van de architectonische schatten die de stad biedt, en te genieten van een typische drank: <strong>Agua de Valencia</strong>, een alcoholische cocktail op basis van Vodka, cava en vers sinaasappelsap. Of nog beter... u kunt ook een Orxata proeven, ons veganistische chufa-sap, altijd vergezeld van de geliefde Fartons, een staafvormige cake die u moet indopen zodat hij drenkt en dan eten. Zo genieten de Valencianen van deze verfrissende culturele drank.</p>\n<p>Vergeet niet dat er geen haast is; doe wat u wilt en druk uzelf niet; het is immers een leuke uitstap! U kunt terugkeren naar uw Avontuur wanneer u voelt dat het het juiste moment is, door gewoon op play te drukken.</p>`,
  "347": "<p>De <strong>Calle de las Barcas</strong> ontleent zijn naam aan het feit dat in deze straat een reeks ateliers stond waar kleine schepen werden gebouwd die daarna werden overgebracht naar de vissersbuurt.</p>\n<p>In zijn tijd was het vol cafeetjes en herbergen, waar prostitutie en gokken de bevolking verontruste.</p>\n<p>Met de uitbreiding van de <strong>Plaza del Ayuntamiento</strong> in 1891 werden in de buurt emblematische gebouwen gevestigd zoals die welke u hierna zult zien.</p>",
  "348": "<p>Ga door tot het einde van de straat, waar u het vroegere hoofdkantoor van de <strong>Banco de Valencia</strong> kunt zien.</p>",
  "349": "<p>Ondanks zijn klassieke snit met een afgeschuinde hoekcompositie bevat het gebouw typisch Valenciaanse elementen zoals de keramiek met bloemenmotieven op het attica en de slanke erkers naar de zijstraten.</p>\n<p>De basis van het gebouw, twee verdiepingen hoog, wordt gedefinieerd door de combinatie van marmer van twee kleuren en een reeks klassieke zuilen die het hekwerk vasthouden en gouden elementen bevatten, waarmee het beeld van bescherming wordt geboden dat de Bank nastreefde.</p>\n<p>Het vroegere hoofdkantoor van de <strong>Banco de Valencia</strong> is een essentiële architectonische schat in dit avontuur.</p>",
  "350": "<p>Hoeveel verdiepingen heeft het gebouw?</p>",
  "351": "<p>Terwijl u deze gevel bewondert, ga door met uw avontuur zoals uw kaart aangeeft, via de straat die links van u opent tot aan het volgende bezienswaardigheidspunt.</p>\n<p>Zet deze audiogids niet op pauze en ga naar de aanbevolen locatie.</p>\n<p>Vergeet de verkeersregels niet te respecteren. Dank u.</p>",
  "352": "<p>Onderweg valt er, te midden van de moderniteit van de gebouwen, een van de tien stichtende parochies van de stad op.</p>\n<p>Als weetje zeggen we dat de <strong>Iglesia de San Juan de la Cruz</strong> in een betreurenswaardige staat belandde tijdens de Spaanse Burgeroorlog van 1936 tot 1939.</p>\n<p>De tempel werd geplunderd, waarbij de plunderaars zijn kunstwerken en zijn altaarstuk verwoestten.</p>\n<p>De bezzetters maakten ook gebruik van de ruimte als opslagplaats voor zwaar wapentuig.</p>",
  "353": "<p>Zodra u bij de kerk aankomt, richt uw aandacht, als u zo vriendelijk wilt zijn, op de Salomoonse zuilen van de deur met rechte bovenzijde. Want we zullen meer informatie geven in de loop van dit Avontuur, en dit is een plek om ze in detail te bekijken.</p>\n<p>Pauzeer deze audiogids als u dat geschikt acht.</p>",
  "354": "<p>Bent u al op het bezienswaardigheidspunt? Nog niet? We hopen dat dit korte verhaal uw reis veraangenaamt.</p>\n<p>Het is vermeldenswaard dat de Markies van Rabassa de Perellós in 1496 de titel Baron van Dos Aguas verwierf voor een aanzienlijk bedrag, waarbij het Baronie in 1699 werd verheven tot Markezaat.</p>\n<p>Gedurende drie eeuwen bekleedden de familie Rabassa de Perellós hoge functies in het politiek bestuur, terwijl ze bruidsschatten en erfenissen vergaarden via huwelijksverbintenissen.</p>\n<p>Dit gebouw heeft gedurende zijn transitie opzichtige wijzigingen ondergaan als blijk van macht en afkomst.</p>\n<p>Tegenwoordig herbergt het het <strong>Nationaal Museum voor Keramiek</strong>.</p>\n<p>Ga alstublieft naar de hoofdingang die om de hoek is.</p>\n<p>Pauzeer deze audiogids als u dat geschikt acht.</p>",
  "355": "<p>Bewonder de Kathedraal van boven tot onder en u kunt drie gestapelde galerijen aanschouwen gevormd door openingen met rondbogen.</p>\n<p>Gebouwd in 1566 in een Renaissance-stijl; het betreft een tribune-uitkijkpost bekend als «Obra Nueva» bestemd voor het aanschouwen van processies en publieke evenementen vanuit de Kathedraal zelf.</p>",
  "356": "<p>De compositie van deze gevel dateert uit de 18e eeuw.</p>\n<p>Daarin zien we een afbeelding van de Virgen del Rosario waarvan twee waterstromen neerdalen samen met twee Atlanten die de twee meest waterrijke rivieren van Valencia vertegenwoordigen, de Turia en de Júcar, met een duidelijke verwijzing naar de naam van het Markezaat.</p>\n<p>Aan de voeten van de Maagd kunnen we twee knielende matrones zien, een met een hoorn des overvloeds waaruit vruchten stromen (allegorie van landbouw en welvaart) en de andere met een vaas aan haar voeten vol munten (allegorie van rechtvaardigheid en grootmoedigheid).</p>\n<p>In de 19e eeuw voerde de erfgenaam van de markiezen een tweede en spectaculaire hervorming uit, voornamelijk gebaseerd op de decoratie van het interieur.</p>\n<p>Hij wijzigde ook het exterieur van het Paleis door de rococostijl te combineren met Chinese en Franse motieven van die tijd, zoals het gebruik van traliewerk op ramen en balkons of de enorme wapenrustingen die uit de gevel steken, waarmee het zijn huidige uiterlijk kreeg.</p>",
  "357": `<p>In zijn interieur kunnen we nog steeds koetsen uit de 18e eeuw zien evenals de 19e-eeuwse salons, terwijl de tweede verdieping het keramiekmuseum herbergt.</p>\n<p>${LOGO} raadt u aan op pauze te drukken en dit historische complex op uw eigen tempo te bezoeken. U kunt uw avontuur hervatten zodra u het geschikt acht.</p>`,
  "358": "<p>Stel u op met de hoofdgevel van het Paleis aan uw linkerhand en ga door tot het einde van de straat.</p>\n<p>U zult opnieuw aankomen bij de beroemde <strong>Calle San Vicente Mártir</strong>.</p>\n<p>Het tracé van deze straat is onveranderlijk bewaard gebleven sinds de vierde eeuw na Christus.</p>\n<p>De <strong>Calle San Vicente Mártir</strong> is tegenwoordig een van de langste straten van de stad.</p>\n<p>Sla in deze straat, gewijd aan de patroonheilige van Valencia, links af en ga door met uw schattenjacht tot het einde van de straat.</p>",
  "359": "<p>Neem de <strong>Plaza del Ayuntamiento</strong>, die overeenkomt met nummer <mark>27</mark> op uw kaart, als referentie, maar sla deze keer rechtsaf.</p>",
  "359-B": "<p>Neem opnieuw hetzelfde kruispunt van eerder als referentie, maar sla deze keer rechtsaf.</p>",
  "360": "<p>Op slechts 150 meter, precies op het volgende plein, komen monumenten uit verschillende tijdperken samen en vormen deel van ons heden en ons leven.</p>\n<p>Uw schattenjacht begint bij het monumentale gebouw aan de linkerhand.</p>",
  "361": "<p>Stel u voor dat u in een ver verleden bent!</p>",
  "362": "<p>Dit monument gewijd aan de handel werd gebouwd op de plek van de openluchtmarkt die er al bestond sinds 1839, en die al die tijd de <strong>Mercado Central</strong> heette, welke op zijn beurt werd gebouwd op de oude islamitische markt of souk buiten de stadsmuren.</p>\n<p>De <strong>Mercado Central</strong> die we vandaag kunnen zien, ingewijd in 1928, bevindt zich in een gebouw in modernistische stijl met keramiek, ijzer, steen, en de brede glasramen en koepels die het interieur en exterieur versieren.</p>\n<p>Als u het hele gebouw bekijkt, valt op een van de koepels een windvaan in de vorm van een parkiet op.</p>",
  "363": "<p>De legende vertelt dat dit verwijst naar de roddels of achterklap die altijd gebruikelijk zijn geweest op markten en daarom wordt het de «Cotorra del Mercado» (Marktparkiet) genoemd.</p>",
  "364": "<p>Hoewel het een modern gebouw is, integreert de Markt zich perfect met de andere twee belangrijke monumenten op het plein: de <strong>Iglesia de San Juan del Mercado</strong> en de <strong>Lonja</strong>, beide iconische plekken van het 15e-eeuwse Valencia.</p>\n<p>Zoek het glasraam met de kleuren van de Valenciaanse Señera op de gevel van het gebouw. Weet u welke vorm het heeft? Vierhoekig, Rond of Driehoekig?</p>",
  "365": "<p>Bekend als <strong>Iglesia de San Juan del Mercado</strong>, is dit een ander duidelijk voorbeeld van een parochie gebouwd op een Arabische Moskee.</p>\n<p>Een ernstige brand in het jaar 1300 na Christus dwong tot de herbouw ervan praktisch vanuit zijn puin.</p>\n<p>Eeuwen later was een andere brand de oorzaak van een nieuwe herbouw die het zijn huidige Gotische fysionomie gaf, terwijl een deel van zijn originele Barok bewaard bleef.</p>\n<p>In 1936, tijdens de Burgeroorlog, verwoestte een derde brand de kerk en de schade werd hersteld in het eerste kwart van de 21e eeuw.</p>",
  "366": "<p>Onder haar buitendecoratie valt een groot stenen altaarstuk van de Virgen del Rosario op.</p>\n<p>Wat houdt de Maagd in haar hand? Een rozenkrans? Een kind? Of misschien een kroon?</p>",
  "367": "<p>Wat overhandigt de engel aan het kind? Is het een duif? Misschien een bol? Of zijn het misschien levensmiddelen?</p>",
  "368": "<p>Een minder bekend naam voor dit kerkgebouw is de «Iglesia de los pillos» (Kerk van de bengels), omdat dit vroeger de plek was die werd gekozen door kinderen die, wegens de omstandigheden van die tijd, zich bezighielden met kattenkwaad en kleine diefstallen pleegden bij voorbijgangers op de markt. Stel u middeleeuwse zakkenrollers voor. Zou dit een historisch beroep zijn?</p>",
  "369": "<p>Terwijl u dit gebouw bewondert, bevindt het volgende bezienswaardigheidspunt zich achter u; draai simpelweg om.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
