import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "201": "<p><i>Alla ricerca del tesoro</i>, grazie ai suoi contenuti accessibili in più lingue, è inoltre un eccellente strumento per praticare una lingua che sta imparando, o addirittura per immergersi in una nuova.</p>",
  "202": "<p>Sotto il nostro motto \"La scelta è e sarà sempre sua\", offriamo la possibilità di avanzare al ritmo che preferisce, fare pause quando ne ha bisogno o addirittura trasformare l'esperienza in una competizione amichevole per vedere chi completa l'avventura per primo. Una volta che decida che è il momento appropriato, prema il tasto Avvia e continui a completare le nostre sfide mentre scopre la città. Ogni indizio la porterà a una nuova destinazione con nuovi enigmi che riveleranno magnifici tesori storici e architettonici di Valencia.</p>",
  "203": `<p>Per arricchire ancora di più la sua esperienza, ${LOGO} la invita a entrare nei monumenti visitabili come parte dell'esperienza di questa Avventura, come musei, mercati e molti altri luoghi interessanti, alcuni gratuiti e altri con un prezzo simbolico, sebbene i biglietti d'ingresso a questi ultimi non siano inclusi con l'acquisto di questa avventura.</p>`,
  "204": "<p>Se le sembra opportuno, ci farebbe piacere iniziare questa avventura con una breve introduzione alla storia, ubicazione e gastronomia valenciana. Questo ci permetterà di avere una visione generale del percorso che ci aspetta.</p>",
  "205": "<p>Ricordi che il limite di questa avventura è di 60 ore dall'inizio.</p>",
  "206": "<p>Ricordi che il limite di questa avventura è di 150 ore dall'inizio.</p>",
  "207": "<p>Questa Avventura che sta per vivere è iniziata molto, molto tempo fa. Secoli prima dell'arrivo dei Romani, il luogo in cui ora si trova Valencia fu occupato dagli Iberi. Stiamo parlando del VI secolo prima di Cristo.</p>",
  "208": "<p>È tanto tempo fa, se ci pensa!</p>",
  "209": "<p>Vari secoli dopo, dall'anno 138 avanti Cristo, e nel corso della sua storia fu intensamente romanizzata, ricevendo il nome di \"Valentia\".</p>\n\n<p>Tuttavia, la successiva influenza musulmana fu ancora maggiore, precisamente dall'anno 711 al 1238 della nostra era. Ciò fa un totale di circa 500 anni.</p>",
  "210": "<p>Tanta fu l'influenza che la popolazione era fondamentalmente musulmana. Valencia ricevette durante questo periodo il nome di \"Balansiya\".</p>",
  "211": "<p>Non fu fino al 1238 che il Re Giacomo I d'Aragona riconquistò Valencia, cristianizzando la città e trasformandola in un regno indipendente dal regno d'Aragona.</p>\n\n<p>Al Regno di Valencia furono consegnati \"Los Fueros\", dotando il regno di una propria identità politica e giuridica.</p>",
  "212": "<p>La fine dell'autonomia della regione arrivò con Filippo V nel XVIII secolo.</p>\n\n<p>Nella Guerra di Successione il popolo valenciano appoggiò il suo nemico l'arciduca Carlo.</p>\n\n<p>Filippo V, dopo aver vinto la guerra, abolì i Fueros e unì Valencia al governo nazionale.</p>\n\n<p>Nel 1982, Valencia fu nominata Capitale della Comunità Valenciana.</p>",
  "213": "<p>Valencia, la capitale del Turia, è attualmente la terza città più popolata di Spagna. Si trova a est della Penisola Iberica, sulle rive del Río Turia e bagnata dal Mar Mediterraneo, che dona alla regione un clima temperato con inverni miti e circa 340 giorni di sole all'anno.</p>",
  "214": "<p>Cosa c'è nei dintorni della città?</p>",
  "215": "<p>Da Valencia partono una grande varietà di percorsi attrezzati per gli amanti del ciclismo e della natura. A circa dieci chilometri a sud della città si trova il parco naturale dell'<strong>Albufera</strong> di Valencia.</p>\n\n<p>L'<strong>Albufera</strong> è una delle zone umide più grandi di Spagna con una superficie di 2100 ettari, a cui si aggiungono 14.000 ettari di palude dedicati alla coltivazione del riso, che è la principale coltura della città, insieme alla chufa, all'arancia, al nespolo e al cachi.</p>",
  "219": "<p>Come può supporre, la gastronomia valenciana si inserisce nella dieta mediterranea.</p>\n\n<p>Tuttavia, ciò che caratterizza la cucina valenciana è l'uso del riso e il suo piatto stellare conosciuto in tutto il mondo, la Paella.</p>",
  "220": "<p>Sono eccezionali anche lo stufato di anguilla, l'all-i-pebre e il ricchissimo aglio e olio pronunciato all-i-oli.</p>",
  "221": "<p>Tra i dolci locali spiccano il torrone, dolce natalizio per eccellenza, l'arnadí di zucca e la famosa Orxata de Chufa che ghiacciata o liquida e accompagnata dai suoi inseparabili \"Fartons\", farà le delizie dei pomeriggi estivi.</p>",
  "222": "<p>Ora che conosce un po' la storia e la gastronomia della nostra terra, è il momento di iniziare la sua avventura. Godetevela! La sua avventura inizia nella <strong>Calle de los Serranos</strong>. Ricordi che, per avanzare nel percorso, dovrà mettere in pausa a ogni punto di interesse, osservare il luogo indicato o completare la sua sfida, e poi continuare verso la prossima destinazione suggerita e così consecutivamente. Tutto pronto per cominciare? Andiamo, buona fortuna! Dalla <strong>Calle de los Serranos</strong>, rivolga la sua attenzione alla fine della via e visualizzi le torri che sulla sua mappa sono indicate con il numero <mark>1</mark>.</p>",
  "223": "<p>Si trova già nella <strong>Calle de los Serranos</strong> visualizzando le torri? Perfetto, cominciamo! Imponenti come nessun'altra, queste torri della fine del XIV secolo sono in stile gotico valenciano.</p>\n\n<p>Questo monumento di architettura militare realizzato in blocchi di pietra da taglio fu una delle dodici porte che custodivano l'antica cinta muraria cristiana della città di Valencia. Oggi ne restano solo 2.</p>\n\n<p>Sebbene il loro uso principale fosse militare e difensivo, venivano generalmente utilizzate anche per cerimonie e ingressi ufficiali di re e ambasciatori.</p>\n\n<p>Queste torri, oggi visitabili, erano considerate (e sono ancora considerate) l'ingresso principale della città.</p>",
  "224": "<p>Per l'importanza delle sue collezioni è un chiaro riferimento degli antichi maestri valenciani.</p>\n\n<p>Nel 1683, l'architetto Juan Bautista Pérez iniziò una costruzione che avrebbe impiegato 60 anni per essere completata.</p>\n\n<p>Il suo utilizzo originale fu come collegio di chierici minori e residenza per missionari.</p>\n\n<p>Sebbene nel corso della sua storia l'edificio abbia avuto vicende molto varie, subendo diversi restauri, modifiche e utilizzi: nel 1819 fu un'accademia militare, nel 1826 la Casa della Beneficenza, nel 1835 l'edificio fu utilizzato come magazzino di materiale militare e nel 1843 fu collocato un ospedale militare.</p>\n\n<p>Dal 2017, svolgendo la funzione di <strong>Museo di Belle Arti</strong>, è diventato anche riferimento per la direzione che devono prendere i cacciatori del tesoro di questa avventura.</p>",
  "225": "<p>Continui fino al ponte successivo, il <strong>Puente de las Flores</strong>.</p>",
  "226": `<p>Come accennato nell'introduzione: <i>alla ricerca del tesoro</i> è una serie di Avventure audioguide con percorsi e distanze diverse che può fare al suo ritmo.</p>\n\n<p>${LOGO} le propone anche sfide da risolvere, in cui la inciteremo a notare certi dettagli dei monumenti che potrebbero passare inosservati.</p>\n\n<p>Ecco la prima delle sue sfide, questa è facilissima.</p>`,
  "227": "<p>In alto sulle aperture laterali troviamo due bassorilievi, opere dedicate \"Al Valore\" e \"All'Abnegazione\".</p>",
  "228": "<p>Saprebbe dirmi come si chiamano queste Torri?</p>\n\n<p>Prema pausa, poi risolva la sua sfida e prema di nuovo il tasto continua.</p>",
  "229": "<p>Lo ha indovinato? Bravo, ha appena risolto la sua prima sfida, ora avanti con la prossima!</p>",
  "230": "<p>Si diriga al centro del ponte e osservi a sinistra e a destra per capire un po' la storia del percorso che esploreremo.</p>",
  "231": "<p>È vero che anticamente le fonti di acqua potabile della città, così come l'origine dei canali irrigui per i campi, avevano base nel <strong>Río Turia</strong>. Ma dopo le catastrofiche inondazioni che ebbero luogo il 14 ottobre 1957 e la successiva deviazione del fiume verso una zona più sicura della città, insieme alla costante passione dei valenciani, lasciarono spazio al tempo libero, alla cultura e allo sport in questo spazio di 9 chilometri di lunghezza e 200 metri di larghezza.</p>",
  "232": "<p><i>Alla ricerca del tesoro</i> percorreremo un giardino di ispirazione araba tra Pini, Olmi, Palme, Cipressi, Gelsi, Salici e Aranci.</p>\n\n<p>Uno spazio verde maestoso che, pur essendo sofisticato, offre l'immagine di un terreno piuttosto rustico e naturale con un tocco contemporaneo.</p>",
  "232-B": "<p>Uno spazio verde maestoso che, pur essendo sofisticato, offre l'immagine di un terreno piuttosto rustico e naturale con un tocco contemporaneo.</p>",
  "233": "<p>In cima sventola la bandiera di Valencia: i suoi colori si compongono di rosso, giallo e... Viola, Verde o Blu?</p>",
  "234": "<p>Da uno dei lati del ponte spicca un edificio con una bella cupola blu fiancheggiato da due robuste torri. Riesce a vederlo?</p>",
  "235": "<p>Dal 1946 questo edificio ospita il <strong>Museo di Belle Arti</strong>, uno dei primi di Spagna; raccogliendo durante la sua transizione una grande ricchezza artistica nei suoi dipinti provenienti da antiche chiese e conventi.</p>",
  "236": `<p>${LOGO} le suggerisce di seguire la mappa per non deviare dalla rotta e godersi il viaggio al massimo.</p>`,
  "236-A": `<p>${LOGO} le suggerisce di seguire la mappa per non deviare dalla rotta e godersi il viaggio al massimo.</p>\n\n<p>La sua mappa del tesoro le indica di scendere nell'alveo del fiume.</p>\n\n<p>Per farlo, torni verso le torri e segua la pista ciclabile alla sua sinistra fino al punto di discesa.</p>`,
  "236-B": "<p>Continui fino al <strong>Puente de la Exposición</strong>, indicato sulla sua mappa con il numero <mark>4</mark>. Grazie.</p>",
  "236-C": "<p>La sua mappa del tesoro le indica di finire di attraversare il ponte e scendere nell'alveo del fiume.</p>\n\n<p>Per farlo, segua la mappa fino al punto di discesa. Questo si troverà alla sua sinistra, ed è indicato sulla sua mappa con il numero <mark>3</mark>.</p>\n\n<p>Una volta in basso, si diriga al centro dell'alveo di questo antico fiume e osservi intorno a sé; potrà vedere delle rovine che spiccano tra la decorazione botanica del <strong>Giardino del Turia</strong>. Tra cipressi e ulivi si possono contemplare resti del Palazzo del Real. Riesce a vederle? Sì? Perfetto, perché la prossima storia speriamo la sorprenda.</p>\n\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "237": "<p>Il <strong>Puente de la Exposición</strong>: comunemente chiamato \"Puente de la Peineta\", ricorda un oggetto a forma di pettine convesso che viene utilizzato per adornare e tenere in posto l'acconciatura delle falleras, le regine delle nostre feste popolari.</p>",
  "238": "<p>L'acconciatura tradizionale da fallera è senza dubbio la più nota delle acconciature di Spagna.</p>\n\n<p>Lo chignon da fallera risale al XVIII secolo, quando le donne raccoglievano i capelli in una coda e li dividevano in otto ciocche che venivano \"intrecciate\" a forma di otto, attorno a uno o due aghi spessi.</p>\n\n<p>Per finire, due trecce circondavano la raccolta centrale.</p>\n\n<p>L'acconciatura tipica da fallera è completata da un pettine posteriore realizzato a mano in ottone argentato o dorato.</p>\n\n<p>Per completare l'acconciatura, si aggiungevano due chignons laterali all'altezza delle orecchie, fissati con due forcine e due repliche del pettine principale.</p>",
  "239": "<p>Saprebbe dirmi come si chiamano queste feste popolari di Valencia? Sarà La Tomatina, le hogueras de San Juan oppure le Fallas?</p>",
  "240": "<p>La tradizione della polvere da sparo nasce a Valencia come conseguenza della vittoria Borbonica nella battaglia di Almansa, precisamente il 25 aprile 1707, quando Valencia fu occupata dalle truppe di Filippo V.</p>\n\n<p>Dopo, la fabbrica d'armi fu smantellata e trasferita a Toledo.</p>\n\n<p>In essa venivano custodite molte armi da fuoco di calibro medio conosciute come \"Traques\" o Trabucos.</p>\n\n<p>Per evitare una rivolta, i trabucos più vecchi furono accatastati nel cortile della fabbrica e bruciati.</p>\n\n<p>Dopo che bruciò il legno dei calci, i cannoni furono venduti come rottame.</p>\n\n<p>Molti fabbri comprarono questi resti, ma non li fusero; al contrario li conservarono e adottarono l'abitudine di piantare questi tubi nel suolo, caricarli di polvere da sparo e poi spararli per celebrare le feste popolari nei villaggi e nelle masserie.</p>",
  "241": "<p>A causa dell'aumento dei veicoli nella Valencia del XX secolo, erano necessari nuovi ponti che mettessero in comunicazione la città.</p>\n\n<p>Il <strong>Puente de las Flores</strong> fu un'eccellente proposta che non poteva passare inosservata nella Terra dei fiori, della luce e del colore.</p>",
  "242": "<p>Concentri la sua attenzione sul corso del fiume. Durante questa avventura farà un breve salto nel tempo, precisamente al XVI secolo passando sotto all'antico Puente de la Mar.</p>",
  "243": "<p>Tornerà nuovamente al XXI secolo poiché questa avventura la incita a cercare l'accesso che la porta in cima al <strong>Puente de Aragón</strong>.</p>",
  "244": "<p>Si trova al centro della lunghezza del ponte?</p>\n\n<p>In stile Razionalista, il <strong>Puente de Aragón</strong> prende il nome dalla vecchia stazione ferroviaria, oggi scomparsa, che copriva la linea Valencia-Aragona, inaugurata nell'agosto del 1933.</p>",
  "245": `<p>${LOGO} le consiglia di seguire la corsia attrezzata e cercare un posto sicuro dove potrà fermarsi per completare la prossima sfida.</p>`,
  "245-B": `<p>${LOGO} le consiglia di girare intorno alla rotonda fino al parco che si trova sul lato opposto e cercare un posto sicuro dove potrà fermarsi per completare la prossima sfida.</p>`,
  "245-C": `<p>${LOGO} le consiglia di seguire la corsia attrezzata e cercare un posto sicuro dove potrà fermarsi per completare la prossima sfida.</p>`,
  "246": "<p>Tra le sue numerose decorazioni ne spicca una in particolare che si può vedere dalla parte centrale della sua cuspide guardando verso il basso nell'alveo del Turia.</p>\n\n<p>\"La natura\" ha scolpito lo stemma di Valencia. Cosa si può vedere sopra lo stemma? Un Pipistrello o un Drago?</p>",
  "247": "<p>Da questo punto, il tracciato di questa avventura continua per il circuito urbano! Prosegua la sua avventura per la corsia adattata per veicoli di mobilità personale. La mappa indica di tornare fino al ponte del XVI secolo che abbiamo lasciato indietro. Ricorda come si chiama? È il Puente de la Mar.</p>",
  "248": "<p>Vale la pena ammirare quest'opera di Javier Goerlich, che nel 1935 progettò questa magnifica scalinata che dà accesso al ponte.</p>\n\n<p>Nel 1876 il tram della linea che andava verso il porto attraversava questo ponte finché nel 1900 il tram fu elettrificato e la linea cadde in disuso.</p>\n\n<p>26 anni dopo, nel 1926 a Valencia fu costruito un nuovo ponte che avrebbe attraversato il fiume alleviando il traffico del Puente de la Mar, diventando da quel momento un ponte pedonale.</p>\n\n<p>Per superare il dislivello furono disposte due scalinate ondulate, quattro panchine a taglio e i pinnacoli che compongono l'immagine attuale del ponte.</p>",
  "249": "<p>Saprebbe indovinare quanti gradini ha?</p>",
  "250": "<p>Prenda l'accesso più vicino di ritorno all'alveo del fiume che dovrebbe trovarsi proprio dietro di lei nel muro del fiume.</p>\n\n<p>Una volta in basso, la sua prossima sfida si trova nel monumento successivo.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
