import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "401": "<p>Il fazzoletto volò fino a un punto preciso e la moltitudine poté constatare come in quella casa si trovava una famiglia sul punto di morire nella miseria più assoluta e la gente, commossa, soccorse la famiglia.</p>",
  "401-B": "<p>Il fazzoletto volò fino a questo punto, e la moltitudine poté constatare come in quella casa si trovava una famiglia sul punto di morire nella miseria più assoluta e la gente, commossa, soccorse la famiglia.</p>",
  "402": "<p>In questo modo si interpretò il famoso miracolo del Mocaoret, che in valenciano significa fazzolettino, che avrebbe compiuto il futuro Santo della Comunità Valenciana.</p>",
  "403": "<p>In questa avventura percorrerà parte del volo di quel fazzoletto che la condurrà alla famosa <strong>Plaza Redonda</strong>.</p>\n<p>Consulti la sua mappa che le indica di lasciare questa piazza alla sua sinistra e di entrare nella strada che si trova di fronte a lei.</p>\n<p>Presti attenzione alla mappa, il suo prossimo obiettivo è la famosa <strong>Plaza Redonda</strong> che si trova nella quarta strada a sinistra e poi la prima a destra.</p>\n<p>Glielo ripeto? Ma certo, con grande piacere!</p>\n<p>Quarta strada a sinistra e poi la prima a destra.</p>",
  "404": "<p>Durante le Fallas è tutta una festa: il fragore della mascletà, i casali, le sfilate, l'offerta dei fiori e le bande musicali percorrono più di 700 monumenti falleros.</p>",
  "405": "<p>L'antico Mercato di carne e pesce, la <strong>Plaza Redonda</strong>, è l'oculus di Valencia, un occhio che guarda il cielo.</p>\n<p>Corrisponde oggi al numero <mark>36</mark> sulla sua mappa.</p>\n<p>Ricordi di premere pausa, poi vada o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "405-B": "<p>Alla destra di questa facciata con archi ciechi della chiesa si trova la famosa <strong>Plaza Redonda</strong>.</p>\n<p>La <strong>Plaza Redonda</strong> è l'oculus di Valencia, un occhio che guarda il cielo.</p>\n<p>L'antico Mercato di carne e pesce corrisponde oggi al numero <mark>16</mark> sulla sua mappa.</p>",
  "406": `<p>Dalla sua riqualificazione nel 2012, la <strong>Plaza Redonda</strong> ha l'aspetto di una piazza moderna senza perdere il suo tocco storico.</p>\n<p>In questa piazza si mantiene viva una grande tradizione valenciana.</p>\n<p>Ancora oggi si possono vedere laboratori di merletto a tombolo; una tecnica tessile che consiste nell'intrecciare i fili su un modello per formare il ricamo.</p>\n<p>Tecnica che richiede abilità come l'attenzione, la concentrazione, la destrezza e, soprattutto, la psicomotricità delle dita.</p>\n<p>All'interno della piazza si possono ancora vedere negozi specializzati in pizzi e merletti ricamati a mano. Troverà anche magnifici souvenir, tutti in stile valenciano, e bar dove degustare le nostre tipiche tapas.</p>\n<p>${LOGO} le raccomanda di premere pausa e visitare questa piazza al suo ritmo.</p>`,
  "407": "<p>Una volta deciso di continuare la sua avventura, la sfidiamo a trovare la porta d'uscita corretta.</p>\n<p>Ci prova?</p>\n<p>Una delle molteplici uscite possibili la conduce a una piazza con diversi punti di interesse nella sua caccia al Tesoro.</p>\n<p>Il suo prossimo obiettivo è la Plaza de Santa Catalina, indicata sulla sua mappa con il numero <mark>37</mark>.</p>",
  "408": "<p>Abbiamo preparato una curiosità per lei! Valencia è piena di tesori architettonici e storici che svela in ciascuna delle nostre Avventure.</p>",
  "409": "<p>Dal centro della piazza si può vedere uno degli edifici più stretti d'Europa. Riesce a vederlo?</p>\n<p>Se lo immagina? Il primo piano un soggiorno, il secondo la cucina e così via.</p>",
  "410": "<p>Quanto misura l'ingresso?</p>",
  "411": "<p>Questa caccia al Tesoro la invita ad avvicinarsi a Santa Catalina; dal centro della piazza potrà contemplare la chiesa nella sua totalità.</p>\n<p>Come può constatare, la chiesa è in parte avvolta dalle case adiacenti e sembra piuttosto rustica all'esterno.</p>",
  "412": "<p>Le origini della <strong>Iglesia de Santa Catalina</strong> Mártir risalgono alla stessa Reconquista di Valencia nel 1238.</p>\n<p>Dopo la reconquista e il successivo cambio di religione della città, Giacomo Primo cercherà di strutturare lo spazio urbano.</p>\n<p>A tal fine, cede la proprietà di tutte le moschee e cimiteri musulmani all'arcivescovado che, a sua volta, cristianizza questi templi rinominandoli come parrocchie dedicate a Sante e Santi della nuova religione che si sarebbe instaurata in queste terre.</p>\n<p>Nel maggio del 1239, solo 1 anno dopo la reconquista, la Parrocchia di Santa Catalina divenne una delle dieci Parrocchie fondazionali della città.</p>\n<p>Aggiungeremo anche che il fatto della presa delle moschee non era solo uno strumento di cristianizzazione e controllo ecclesiastico della vita di quartiere, ma anche uno strumento di organizzazione amministrativa e politica; di fatto, il municipio era composto, in parte, dalle diverse parrocchie della città.</p>",
  "413": "<p>Con gli anni, si iniziò a costruire parrocchie a pianta cristiana nel luogo che occupavano le antiche moschee.</p>\n<p>La <strong>Iglesia de Santa Catalina</strong> fu completata nel 1371. Ma nel 1740 subì una riforma che durò 15 anni e che comportò un rinnovo quasi totale del tempio.</p>",
  "414": `<p>La leggenda urbana racconta che nel contratto tra l'architetto e la chiesa non fu specificata la costruzione di una scala per salire alla torre, per cui l'architetto costruì la torre senza accesso ai piani superiori.</p>\n<p>Oggi si può accedere alla torre mediante una scala a chiocciola che consente l'accesso alla balaustrata.</p>\n<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e passeggiare all'interno di questo tempio, oltre che visitare la sua torre.</p>\n<p>La sua avventura continua dallo stesso punto in cui si trova.</p>`,
  "415": "<p>Il percorso richiede che le presti una particolare attenzione, poiché le darà accesso a una storia nascosta nella sua mappa del tesoro. Sarà in grado di trovarla? Un'enorme conchiglia scolpita nella pietra che si trova alla sua destra, addossata al muro di contenimento all'interno del giardino stesso, svela parte della storia tragica della città.</p>",
  "416": "<p>Concentri la sua attenzione sulla facciata che ha davanti adesso. In essa si aprono tre archi ciechi.</p>\n<p>Due di essi sono lisci e il terzo è stato lasciato grezzo.</p>\n<p>Cosa si può vedere in quell'arco? Riesce a vedere un volto? Forse c'è un torso? E una gargolla?</p>",
  "417": "<p>Fino al 1520, in questa facciata si trovava l'ufficio incaricato della vigilanza dei mercati e dell'igiene pubblica; oltre al controllo dei pesi e delle misure della città, poiché a pochi metri si trovavano le macellerie e le pescherie della città.</p>\n<p>Anticamente, questa era la zona commerciale e mercantile dove erano ospitate la maggior parte delle corporazioni più importanti della città.</p>",
  "418": "<p>La sua mappa del tesoro la conduce a costeggiare la chiesa in direzione della torre.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>38</mark>.</p>\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato.</p>",
  "419": "<p>Si posizioni, se non le dispiace, in un punto dal quale possa vedere la torre nella sua totalità e si prenda il suo tempo per scattare alcune fotografie di questo magnifico monumento, permettendosi allo stesso tempo di conoscerlo più in profondità.</p>\n<p>Ricordi di premere pausa, poi visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "420": "<p>Santa Catalina Mártir è una torre visitabile considerata come una delle torri barocche più originali dell'architettura spagnola.</p>\n<p>La prima pietra di questo campanile fu posta nel 1688 e fu infine completata nel 1705 nell'attuale stile barocco.</p>\n<p>Come si può apprezzare, la torre è di pianta esagonale.</p>\n<p>Si eleva su quattro piani, a cui si aggiunge il corpo delle campane e un tempietto: una costruzione superiore costituita da colonne e un tetto, simile a un tempio.</p>\n<p>In ciascuno dei suoi piani si aprono finestre riccamente decorate in stile Barocco che permettono il passaggio della luce alla scala.</p>\n<p>Nel corpo delle campane si osserva la sua maggiore ricchezza decorativa. Ammiri le colonne salomoniche nastrate in ciascuna delle sue spigole.</p>\n<p>Le colonne ricevono questo nome per la credenza dell'epoca che così fossero le colonne del Tempio di Salomone.</p>\n<p>Completano il corpo delle campane gli archi a tutto sesto che si aprono in ciascuna delle facce della torre.</p>\n<p>Come nota, riguardo alle 6 campane che si trovavano nel campanile dal 1729, diremo che erano conosciute come \"le luterane\", perché provenivano da Londra, un paese non cattolico.</p>\n<p>Purtroppo, quelle campane ebbero destini diversi.</p>",
  "421": "<p>Corona la torre un tempietto a due piani sorretto da un insieme di volute, così chiamate per la loro forma a chiocciola o spirale che reggono il corpo centrale.</p>\n<p>Qui si ripetono le colonne salomoniche nastrate. Riesce a vederle?</p>\n<p>Il tempietto è coperto da una cupola con tegole di pietra a forma di scaglie di pesce.</p>\n<p>Sulla cupola si distinguono una sfera che rappresenta il globo terrestre e una banderuola che permettono a Santa Catalina di superare i 56 metri di altezza.</p>",
  "422": "<p>Di che colore sono le tegole della cupola?</p>",
  "423": "<p>Cosa si trova in cima alla torre? Potrebbe essere una croce? Forse il sole? Forse c'è una colomba?</p>",
  "424": "<p>Non metta in pausa questa audioguida. La sua mappa del tesoro le indica di attraversare la piazza e cercare l'accesso che si trova nella parte opposta.</p>\n<p>A partire dal 2012, questa piazza e quella adiacente, che si trova alla sua mano sinistra, sono passate dall'essere una serie di rovine a due piazzette riqualificate che ospitano due spazi per mercati.</p>\n<p>In <strong>Tapinería</strong>, come è conosciuto l'insieme di piazze, impera la filosofia dell'effimero; per cui i prodotti e lo stile cambiano ogni 15 giorni.</p>",
  "425": "<p>La tradizione racconta che la torre di Santa Catalina è la fidanzata del <strong>Miguelete</strong>: \"Due innamorati che si guardano eternamente, ma la timidezza non permette loro di avvicinarsi\".</p>",
  "426": "<p>Il <strong>Miguelete</strong> è un monumento visitabile, di stile gotico valenciano che prende il nome dalla sua campana principale, la quale dal 1539 fino ad oggi continua a battere le ore.</p>\n<p>Si avvicini al monumento, come indica la sua mappa.</p>",
  "426-B": "<p>Il nostro famoso <strong>Miguelete</strong>, di stile gotico valenciano, prende il nome dalla sua campana principale, la quale dal 1539 fino ad oggi continua a battere le ore.</p>\n<p>L'iconico <strong>Miguelete</strong> svolge la funzione di campanario e belvedere essendo l'edificio più alto della città storica.</p>\n<p>Dopo aver salito i suoi 207 scalini, il <strong>Miguelete</strong> offre viste aeree a 360 gradi di tutta la città.</p>\n<p>La panoramica che offre a 51 metri di altezza permette di vedere tutta la città con il suo giardino fino alla spiaggia, passando per la <strong>Ciudad de las Artes y de las Ciencias</strong> e la bella campagna valenciana.</p>",
  "427": "<p>L'iconico <strong>Miguelete</strong> si compone di quattro corpi di uguale altezza.</p>\n<p>Questo importante punto della sua Avventura svolge la funzione di campanario e di belvedere essendo l'edificio più alto della città storica.</p>\n<p>Saprebbe determinare che geometria ha? Esagonale, Ottagonale o Quadrangolare?</p>",
  "428": "<p>In origine, la <strong>Torre del Miguelete</strong> fu progettata per essere eretta separata dalla Cattedrale, ma una riforma nel XV secolo fece sì che la stessa rimanesse unita alla torre.</p>\n<p>Quante finestre riesce a vedere?</p>",
  "429": "<p>Concentri la sua attenzione leggermente alla sua destra.</p>",
  "429-B": "<p>Concentri la sua attenzione leggermente alla sua sinistra.</p>",
  "430": "<p>Successivamente alla costruzione del <strong>Miguelete</strong>, gli fu incorporata la porta barocca della cattedrale. Oggi è la sua porta principale.</p>\n<p>Comunemente conosciuta come la \"<strong>Puerta de los Hierros</strong>\", unisce il tempio con la <strong>Torre del Miguelete</strong> e delimita lo spazio con la cancellata metallica che dà il nome al portale.</p>\n<p>Questo grandioso progetto fu concepito per rispondere alla necessità di creare un'illusione ottica, dando così una maggiore sensazione di spazio a un luogo relativamente piccolo, sostituendo le tradizionali linee rette con una curvatura concavo-convessa.</p>\n<p>Nel portale spiccano le colonne e il rosone ovale che illumina la Cattedrale e, al di sopra di esso, un altorilievo che rappresenta l'ascensione della Vergine.</p>\n<p>Corona l'attico del portale un bassorilievo con il simbolo dello Spirito Santo.</p>\n<p>Questo portale, ultimato nel 1741, è il punto d'accesso più moderno della Cattedrale.</p>\n<p>Va notato che fu costruito grazie alla donazione che una cittadina lasciò nel suo testamento.</p>",
  "431": "<p>Cosa si può vedere a più di 35 metri di altezza in cima al portale barocco? È una sfera? È una croce? Forse un pipistrello? O un cavallo?</p>",
  "432": `<p>Nel nostro secolo, la <strong>Puerta de los Hierros</strong> si divide in due: il lato sinistro che facilita l'accesso ai fedeli e dà anche accesso alla salita al <strong>Miguelete</strong>.</p>\n<p>Da qui si intravede anche l'Altare Maggiore, un retablo rinascimentale adornato con una splendente decorazione gotica.</p>\n<p>Il lato destro offre la parte museale della Cattedrale. Da qui si accede anche alle numerose cappelle, tra cui quella di San Vicente Mártir, nella quale è esposto il braccio incorrotto del Santo.</p>\n<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e visitare questo monumento al suo ritmo.</p>\n<p>Dopo aver salito i suoi 207 scalini, il <strong>Miguelete</strong> offre viste aeree a 360° di tutta la città.</p>\n<p>La panoramica che offre il <strong>Miguelete</strong> a 51 metri di altezza permette di vedere tutta la città dal suo esteso giardino fino alla <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Questo è un punto perfetto per scattare fotografie panoramiche della città.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno, semplicemente prema il tasto corrispondente e continui <i>alla ricerca del tesoro</i>.</p>\n<p>La sua avventura continua in questo stesso punto.</p>`,
  "433": "<p>Lasci la <strong>Plaza de la Virgen</strong> alla sua sinistra, continui fino alla fine della strada e poi, a destra.</p>\n<p>Si troverà nella <strong>Calle de los Serranos</strong> che separa e delimita alla mano destra i quartieri de \"La Seu\" o quartiere della Cattedrale, e alla mano sinistra il quartiere de \"El Carmen\".</p>",
  "434": "<p>La costruzione della Cattedrale impiegò 500 anni per essere completata e durante quel lungo periodo di tempo gli stili architettonici cambiarono; per questo nella <strong>Cattedrale di Valencia</strong> si fondono diversi stili architettonici.</p>\n<p>La sua facciata nord è la più antica.</p>",
  "435": "<p>Questi stili si possono vedere con totale chiarezza nelle sue tre porte: la Barocca, quella principale, che è quella che ha di fronte.</p>\n<p>Nella facciata ovest si trova il portale gotico che vedrà nel corso di questa Avventura e il lato est con il suo ingresso in stile romanico che sarà il suo prossimo obiettivo.</p>",
  "436": "<p>In particolare il noto come \"La Nit del Foc\" (Notte del Fuoco) che viene sparato la notte tra il 18 e il 19 marzo, nel quale si radunano più di un milione di persone per assistervi poiché si distingue dagli altri per essere il più lungo e spettacolare di tutti.</p>",
  "437": "<p>Si avvicini un po' di più alla porta della Cattedrale.</p>\n<p>La porta in stile romanico della cattedrale, nota anche come la porta del Palau, è un portale romanico in un tempio dalle caratteristiche gotiche.</p>\n<p>Alla sua base furono scolpite 12 rappresentazioni per ogni lato, con episodi storici della Bibbia, della Genesi e dell'Esodo.</p>\n<p>Soprannominata la porta secca, è composta da sei archi a tutto sesto con motivi geometrici; in essa si possono vedere figure di serafini, angeli, archetti e delicati fogliami finemente elaborati.</p>\n<p>Al di sopra dell'arcata si trovano le teste di sette coppie che secondo la tradizione rappresentano sette matrimoni naturali di Lérida che arrivarono portando con sé trecento fanciulle che dovevano sposarsi con i nuovi coloni e in questo modo ripopolare Valencia dopo la guerra.</p>",
  "438": "<p>Quanti archi compongono la porta?</p>",
  "439": "<p>Nella parte destra della porta, all'altezza delle ginocchia, troviamo dei segni longitudinali simili a graffi.</p>\n<p>In questa piazza dove si trova adesso, si trovava la piattaforma sulla quale il boia giustiziava i prigionieri.</p>\n<p>Antichi resoconti narrano che quei segni sono stati prodotti dal boia affilando l'ascia sempre nello stesso punto, poiché a pochi metri dalla porta si trovava il lugubre luogo delle esecuzioni, evento che ovviamente era pubblico! E al quale si permetteva alla popolazione di assistere per vedere come veniva impartita la giustizia.</p>",
  "440": "<p>Non metta in pausa questa audioguida e continui il tracciato del muro del tempio.</p>",
  "441": "<p>Ha notato che il muro della Cattedrale è arrotondato? La <strong>Cattedrale di Valencia</strong> sorge sull'antica Seo Visigota che secoli più tardi si trasformò in Moschea Maggiore.</p>\n<p>Nel XIII secolo, dopo la reconquista, la costruzione della Cattedrale si andava facendo man mano che si utilizzava la Moschea araba, ragione per cui il tempio assume una forma arrotondata, invece della tradizionale pianta a croce.</p>\n<p>Tra il 1229 e il 1245 la Corona d'Aragona conquistò il territorio che successivamente sarebbe stato conosciuto come Regno di Valencia.</p>\n<p>Grazie alle truppe del re Giacomo Primo, Valencia viene riconquistata nel 1238.</p>\n<p>In suo onore, anni dopo, un antico quadro di ceramica tradizionale Valenciana fu esposto sul muro della cattedrale.</p>\n<p>Rappresenta la celebrazione della messa che si tenne dopo la reconquista.</p>",
  "442": "<p>Quale figura scolpita si può vedere nella cornice del quadro?</p>\n<p>Un drago, un pipistrello o forse una corona? Indovini!</p>",
  "443": "<p>Proprio un passo a destra, si apre una piccola cappella protetta da una cancellata. Questo è il luogo dove si celebrò la prima messa nella Valencia conquistata dal Re Giacomo Primo.</p>",
  "444": "<p>Cosa si può vedere dentro?</p>\n<p>Un altare, una bandiera, c'è anche una spada?</p>",
  "445": "<p>Su di essa c'è una targa commemorativa. In che anno fu esposta tale targa?</p>",
  "446": "<p>Qualche passo più avanti, alla mano destra, un'altra cappella chiusa con cancellata ospita la statua di San Vicente Ferrer, Patrono di Valencia.</p>",
  "447": "<p>Nell'edificio che si trova di fronte alla Cattedrale si erge un'imponente porta nera in bronzo ad altorilievo con delle piccole finestre a grata attraverso le quali si può contemplare l'interno della <strong>Basilica di Valencia</strong>.</p>",
  "448": "<p>Il 19 marzo, giorno del padre in Spagna e dedicato a San Giuseppe, le Fallas si concludono con la Nit de la Cremà (la notte della bruciatura).</p>",
  "449": "<p>Notte nella quale, a partire dalle 22 ore in cui vengono bruciati i monumenti infantili fino all'1 di notte in cui viene bruciato il monumento della <strong>Plaza del Ayuntamiento</strong>, è tradizione girare Valencia salutando le Fallas, vedendo ardere il lavoro di un intero anno.</p>\n<p>Continui fino alle torri.</p>",
  "450": "<p>Nel 1652 iniziarono i lavori della basilica e durarono in totale 14 anni.</p>\n<p>Tra il 1652 e il 1660 furono realizzate le facciate esterne.</p>\n<p>Nel 1659 fu concordata la costruzione di un passaggio elevato che comunicasse la Basilica con la Cattedrale, conosciuto come \"arco novo\", e all'inizio del 1661 iniziò la costruzione della cupola di pianta ovale con i suoi quasi 19 metri di larghezza.</p>\n<p>Nel 1666 si completano i lavori della Basilica e quello stesso anno si dispone il trasferimento della Vergine dalla Cattedrale.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
