import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "619": "<p>Procure o acesso que permite subir ao cimo e tome algum tempo para abrir o seu mapa e descobrir esta área.</p>",
  "620": `<p>O Morro, número <mark>71</mark> no seu mapa, é um ponto magnífico a partir do qual se vê o <strong>Parque de Cabecera</strong> completo, e o famoso <strong>Bioparc</strong>, que corresponde ao número <mark>73</mark> no seu mapa.</p>`,
  "620-B": `<p>O Morro, número <mark>14</mark> no seu mapa, é um ponto magnífico a partir do qual se vê o <strong>Parque de Cabecera</strong> completo, e o famoso <strong>Bioparc</strong>, que corresponde ao número <mark>15</mark> no seu mapa.</p>`,
  "621": "<p>Este último divide-se em zonas bem diferenciadas: à direita encontra-se o acesso ao parque zoológico. Nesse ponto situam-se as bilheteiras para adquirir as entradas.</p>",
  "622": `<p>Pode ver a ponte que cruza por cima do lago? Esse é o acesso ao recinto das exibições, que fica à sua esquerda.</p>\n<p>Sente-se e prepare-se para desfrutar, porque desde este ponto elevado onde se encontra neste momento comentaremos vários pontos da sua Aventura.</p>`,
  "623": `<p>O <strong>Parque de Cabecera</strong> estende-se a 15 metros abaixo dos seus pés e recebe este nome por se encontrar na cabeceira do antigo leito do <strong>Rio Turia</strong> na sua entrada em Valencia.</p>\n<p>Realizado entre 2002 e 2014, o parque gira à volta de um lago artificial no qual se podem realizar passeios de barco.</p>\n<p>Nas águas deste lago vivem carpas, tartarugas e rãs, assim como patos e cisnes que já se habituaram à presença pacífica dos seres humanos.</p>`,
  "624": `<p>No <strong>Parque de Cabecera</strong> destacam árvores e arbustos acordes com a climatologia mediterrânica; em particular espécies associadas às margens e ao leito do <strong>Rio Turia</strong>: apreciam-se olmos, choupos, álamos e pinheiros formando pequenos bosquetes.</p>\n<p>Em contacto com a água habitam espécies de plantas anfíbias, taboais e juncos que estruturam o lago e abrigam as espécies animais que o habitam.</p>\n<p>No parque também crescem grupos bem estruturados de arbustos e ervas lenhosas como o alecrim, o tomilho e o esparto, típicos do clima semiárido mediterrânico.</p>`,
  "625": `<p>Este parque metropolitano de quase 168.000 metros quadrados está focado em recuperar a paisagem original do <strong>Rio Turia</strong>.</p>\n<p>A água brota desde o Molí del Sol e segue o antigo curso natural do rio até desembocar no lago, deixando na sua passagem ilhotas de sedimentação típicas da geografia mediterrânica.</p>\n<p>Os muros de pedra e os diferentes níveis de terreno proporcionam um ambiente íntimo com amplas vistas.</p>\n<p>Por um claro exemplo: é o local onde se encontra agora mesmo a partir do qual pode ver, ao longe, o Parque Natural da Serra de Calderona.</p>`,
  "626": `<p>Nas Fallas caminha-se muito, usar calçado confortável é imprescindível. Enquanto chega ao próximo ponto de interesse na sua Aventura, desde ${LOGO} gostaríamos de aportar estes conselhos e assim ter uma experiência plena da festa.</p>`,
  "627": `<p>O <strong>Bioparc</strong> é o novo jardim zoológico valenciano que substitui o seu predecessor desde 2008.</p>\n<p>O antigo jardim zoológico de Valencia que fechou em 2007 foi fundado em 1965 e estava situado nos famosos <strong>Jardines del Real</strong> que verá em detalhe mais adiante nesta Aventura.</p>\n<p>Ao contrário do antigo jardim zoológico no qual os animais estavam amontoados, o <strong>Bioparc</strong> dá a sensação de que o visitante se adentra no habitat do animal graças ao facto do seu desenho ocultar as barreiras entre o público e os animais criando um efeito de zooimersão.</p>\n<p>Este espaço de 100.000 metros quadrados recria a fauna africana e alberga mais de 800 animais de diversas espécies do continente africano, recriando o habitat de cada animal.</p>\n<p>O <strong>Bioparc</strong> divide-se em quatro áreas bióticas: savana seca e savana húmida, Madagáscar e as florestas de África equatorial.</p>`,
  "628": `<p>Este inovador projeto de zooimersão tem como objetivo fomentar a mudança na nossa conduta; amamos os animais e queremos que essa mudança nos motive a viver em harmonia com o planeta.</p>\n<p>Daí o seu lema: comover para conservar.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} incita-o a pausar e entrar a descobrir a biodiversidade que este maravilhoso espaço oferece.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente.</p>\n<p>Utilize o botão de pausa a seu próprio gosto, quando sentir que é o momento continue a resolver os nossos desafios enquanto descobre a cidade. Desfrute ao seu próprio ritmo por este parque de inspiração milenar.</p>\n<p>A sua Aventura continua atrás dos majestosos edifícios à sua esquerda.</p>\n<p>O <strong>Museo de Historia</strong> de Valencia é provavelmente um dos melhores lugares para continuar a aprender sobre esta cultura mediterrânica em que se encontra hoje.</p>`,
  "628-B": `<p>Se se encontrar em horas de visita, ${LOGO} incita-o a pausar e entrar a descobrir a biodiversidade que este maravilhoso espaço oferece.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente.</p>\n<p>Utilize o botão de pausa a seu próprio gosto, quando sentir que é o momento continue a resolver os nossos desafios enquanto descobre a cidade. Desfrute ao seu próprio ritmo por este parque de inspiração milenar.</p>`,
  "629": "<p>Utilize o transporte público, sobretudo o metro na semana de 15 a 19 de março, porque muitas ruas estarão cortadas. Mesmo assim, mover-se de trotinete elétrica, bicicleta ou mesmo, para quem saiba usá-los, os patins são excelentes modos de transporte.</p>",
  "630": `<p>Encontra-se diante do <strong>Museo de Historia</strong> de Valencia? Ótimo! Perfeito!</p>\n<p>O atual <strong>Museu de História</strong> está situado nos antigos depósitos de águas potáveis construídos em 1850 como parte do projeto geral de abastecimento hidráulico da cidade, sendo este um dos primeiros na Europa.</p>\n<p>A água foi canalizada rio acima, conduzida até este ponto, e daqui distribuída pelas oito fontes públicas da cidade.</p>\n<p>Lembre-se de que, naqueles tempos, as fontes públicas eram as recetoras da recente chegada da água potável à cidade.</p>`,
  "631": `<p>Escavado no subsolo e coberto com 11 abóbadas de tijolo sustidas por 250 pilastras ou colunas de tijolo, o antigo depósito garantia a acumulação de 9000 metros cúbicos de água e aproveitava o desnível natural do solo para conseguir a pressão de água necessária.</p>\n<p>Com o tempo e a crescente procura, foi necessário construir novos depósitos acumuladores de água e este ficou em desuso durante várias décadas. No final dos anos 90, foi respeitosamente restaurado para o seu uso atual.</p>`,
  "632": `<p>Com uma superfície de 2.600 metros quadrados, o Museu interativo de História dedica-se a difundir a história de Valencia desde as suas origens até ao nosso tempo.</p>\n<p>Este tesouro da cidade foi inaugurado em 2003 com uma abordagem museográfica inovadora destinada a comunicar-se com o visitante.</p>\n<p>O museu expõe numerosos artefactos arqueológicos, arquitetónicos e históricos, mas o que sem dúvida se destaca da sua exposição é o emprego das novas tecnologias audiovisuais.</p>\n<p>Nesta área pode interagir-se com o passado, escolhendo entre múltiplos cenários que recriam a vida dos habitantes e as suas tarefas quotidianas com o fim de compreender as preocupações que existiam nessa época.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e visite este centro cultural ao seu próprio ritmo.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente. Simplesmente, prima o botão correspondente e continue "<i>à procura do tesouro</i>".</p>`,
  "633": `<p>Abra e observe o seu mapa, este indica-lhe que procure de novo o leito do antigo <strong>Rio Turia</strong> e tome o carril adaptado à sua direita.</p>\n<p>Voltamos ao centro histórico, mas isto não acaba aqui! Percorra o itinerário sugerido e observará que passadas 5 pontes, aguarda o seu próximo ponto de interesse.</p>`,
  "634": `<p>Este elemento decorativo tem os seus inícios em 1592.</p>\n<p>A sua finalidade era encaminhar o rio e prevenir possíveis inundações, embora na Valencia da Idade Média, este elemento tivesse um passado bastante mais sombrio.</p>\n<p>Conta a lenda popular que este era o temido local de queima.</p>\n<p>Local em que a Santa Inquisição queimava os hereges, escravos, demonizados, bruxas e prostitutas depois de lhes ter imputado a pena máxima.</p>`,
  "635": `<p>Centre a sua atenção no pavimento da rampa que dá acesso à parte superior da ponte, ainda sobressaem uns pequenos lombas que facilitavam a vida dos cidadãos que acediam a este antigo porto fluvial.</p>\n<p>Que usos podem ter esses lombas? Parar a água? Travar as rodas dos carros e assim facilitar a carga e descarga dos animais? Ou talvez para recolher as algas e impurezas do rio?</p>`,
  "636": `<p>Abra e observe o seu mapa. A sua Aventura continua pelo caminho ajardinado até que procura o acesso que sobe de novo à cidade.</p>\n<p>Uma vez em cima, o seu próximo desafio situa-se na estátua que dá nome à ponte.</p>\n<p>A <strong>Puente de San José</strong> está situada na segunda ponte desde a sua posição.</p>\n<p>Se faz favor, situe-se em frente à estátua que se situa no centro da ponte.</p>`,
  "637": `<p>José de Nazaré, esposo de Maria Madalena e Pai Putativo de Jesus Cristo, era artesão de ofício; pelo que a Comunitat de Valencia o adota como o seu Santo Padroeiro.</p>\n<p>O 19 de março, Dia do Pai, é um dia especial em toda a Espanha por celebrar-se a homenagem a São José.</p>\n<p>Mas especialmente em Valencia, este é o dia mais mágico do ano pois é aqui que se queimam as famosas Fallas.</p>`,
  "638": `<p>A origem desta festividade remonta ao séc. XVIII.</p>\n<p>Uma antiga tradição dos carpinteiros da cidade que, na véspera da festa do seu padroeiro, queimavam nas praças públicas velhos e inúteis trastes juntamente com as ferramentas de madeira sobrantes do seu trabalho.</p>\n<p>Inicialmente, a Falla compunha-se de piras de materiais combustíveis que foram evoluindo para os monumentos que se podem ver hoje em dia.</p>\n<p>As Fallas tornaram-se numa atração turística muito importante, porque para além de estarem catalogadas como Festa de Interesse Turístico Internacional, em novembro de 2016 a UNESCO inscreveu-as na sua Lista Representativa do Património Cultural Imaterial da Humanidade.</p>`,
  "639": `<p>Retome o caminho adaptado que o leva de volta às <strong>Torres de Serranos</strong>. No seu mapa corresponde ao número <mark>1</mark>.</p>\n<p>Lembre-se de que não tem que descer de novo ao jardim, a sua Aventura continua em terreno urbano.</p>\n<p>Proceda com precaução a partir deste ponto, uma vez que se trata de um traçado urbano e deve respeitar a regulamentação de trânsito.</p>\n<p>Veja as indicações que o seu mapa do tesouro oferece e continue pela ciclovia para se adentr no pleno centro histórico à procura de pistas adicionais.</p>\n<p>Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "640": "<p>Chegou às torres? Centre a sua atenção.</p>",
  "641": `<p>Sabia que a bandeira de Valencia tem nome próprio?</p>\n<p>Como pode apreciar, a Real Senyera de Valencia é um emblema tricolor formado por franjas vermelhas e amarelas horizontais com uma franja azul na zona do mastro.</p>\n<p>Centre a sua atenção nessa área azul e poderá distinguir a coroa que lhe confere o grau de Realeza.</p>`,
  "642": `<p>Ao longo da sua história, os valencianos mediaram em pactos e envolveram-se em batalhas, levantamentos e tomadas de controlo em tempos críticos.</p>\n<p>De facto, em tempos de guerra, as cidades adjacentes deviam seguir o emblema de Valencia que era de onde partiam as ordens. Popularmente chamava-se-lhe "seguir a Senyera".</p>\n<p>Por todas estas façanhas, a bandeira de Valencia é a única de Espanha que tem grau de realeza, e por isso não se inclina perante nada nem perante ninguém.</p>`,
  "643": `<p>Um dado curioso é que, quando é transportada, a bandeira deve ir com o mastro reto em todo o momento.</p>\n\n<p>Lembre-se de que este é um ponto perfeito para tirar uma magnífica foto deste monumento declarado de interesse histórico artístico.</p>`,
  "644": `<p>O seu mapa do tesouro indica-lhe que desça ao leito do rio.</p>\n\n<p>Para isso, volte em direção às torres e siga a ciclovia à sua esquerda até ao ponto de descida.</p>\n\n<p>Uma vez em baixo, dirija-se ao centro do leito.</p>\n\n<p>Um pouco mais adiante e em direção ao Museo de Bellas Artes abre-se um portal do tempo. Entre ciprestes e oliveiras podem contemplar-se restos do Palácio do Real.</p>`,
  "645": `<p>O antigo Palácio do Real foi construído inicialmente no séc. IX como Almunia, uma quinta de recreio muçulmana em que os Sultões da Taifa de Balansiya se retiravam para descansar.</p>\n\n<p>Assim continuou durante a época de conquista cristã e foi no séc. XIV que se começou a reedificar para se tornar no palácio dos Reis da Coroa de Aragão durante a sua estância no Reino de Valencia.</p>\n\n<p>O palácio era conhecido por "o Palácio das 300 chaves" em referência ao número de habitações que chegou a ter.</p>`,
  "646": `<p>Cabe destacar que este palácio já não existe.</p>\n\n<p>De recordação, ficam-nos os gravados que o representam.</p>\n\n<p>Em 1810, o antigo palácio foi desmantelado pelos valencianos por razões estratégicas de defesa, ante a possibilidade de poder converter-se numa praça forte das tropas invasoras de Napoleão.</p>\n\n<p>Hoje em dia, ficam-nos vestígios expostos que delimitam as vias centrais de certos troços do Jardín del Turia e os famosos Jardines del Real, que no seu momento ocupavam uma pequena parte do que foram os Jardins do Palácio.</p>\n\n<p>Os Jardines del Real oferecem um passeio com exemplares centenários de palmeiras, uma enorme passarinheira que data de 1933, assim como um tanque com patos e cisnes, uma magnífica rosaleda e também numerosas esculturas e fontes monumentais.</p>\n\n<p>Ainda mais importante! Os jardins protegem parte da história de Valencia no seu interior.</p>`,
  "646-A": `<p>Cabe destacar que este palácio já não existe.</p>\n\n<p>De recordação, ficam-nos os gravados que o representam.</p>\n\n<p>Em 1810, o antigo palácio foi desmantelado pelos valencianos por razões estratégicas de defesa, ante a possibilidade de poder converter-se numa praça forte das tropas invasoras de Napoleão.</p>\n\n<p>Hoje em dia, ficam-nos vestígios expostos que delimitam as vias centrais de certos troços do Jardín del Turia e os famosos jardins de viveiros, que no seu momento ocupavam uma pequena parte do que foram os jardins do palácio.</p>`,
  "647": `<p>Esta aventura incita-o a seguir o mapa até à entrada destes jardins.</p>\n\n<p>Cumprindo a função de pulmão da cidade, o acesso mais popular aos Jardines del Real encontra-se numa passagem subterrânea que atravessa a avenida e o leva exatamente a uma das suas entradas principais.</p>`,
  "647-B": `<p>Siga o seu mapa até à entrada dos Jardins de Viveiros que fica indicada com o número <mark>4</mark> no seu mapa.</p>\n\n<p>Cumprindo a função de pulmão da cidade, o acesso mais popular a estes jardins encontrá-lo-á numa passagem subterrânea que atravessa a avenida e o leva exatamente a uma das suas entradas principais.</p>\n\n<p>Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido. Obrigado.</p>`,
  "648": `<p>Admire a sua entrada principal. Uma portada romântica de ferro forjado, que data de 1860. Rodeia o vasto recinto uma sóbria grade do mesmo material sustida por socalco e pilares de pedra.</p>`,
  "648-B": `<p>Admire a sua entrada principal, uma entrada romântica de ferro forjado que data de 1860.</p>\n\n<p>Os Jardins de Viveiros oferecem um passeio com exemplares centenários de palmeiras, uma enorme passarinheira que data de 1933, assim como um tanque com patos e cisnes, também uma magnífica rosaleda e numerosas esculturas e fontes monumentais.</p>\n\n<p>Ainda mais importante! Os jardins protegem no seu interior parte da história de Valencia.</p>`,
  "649": `<p>Esta Aventura encoraja-o a adentr-ar-se nestes jardins que a partir de 1912 se converteriam em Parque Municipal para recreação de quem o queira visitar.</p>\n\n<p>Dado que é uma zona bastante ampla, por comodidade, numerámo-la individualmente começando desde a porta de entrada aos jardins, que corresponde no seu mapa ao número <mark>1</mark>.</p>\n\n<p>Desde a entrada pode admirar-se a vegetação que se destaca pela variedade da sua arborização com exemplares de grande porte e idade.</p>\n\n<p>No Passeio das Palmeiras predominam as palmeiras canárias, washingtonias, assim como palmeiras datileiras. No seu mapa corresponde ao número <mark>1</mark>.</p>\n\n<p>Não pause esta audioguia e adentr-e-se nos antigos jardins do Real.</p>`,
  "649-B": `<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e desfrute destes Jardins ao seu próprio ritmo!</p>\n\n<p>Utilize o botão de pausa a seu próprio gosto, quando sentir que é o momento apropriado, simplesmente continue a resolver os nossos desafios enquanto descobre a cidade.</p>\n\n<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 4.</p>\n\n<p>Quando decidir continuar à procura do tesouro atravesse de novo o túnel para aceder ao leito do Jardín del Turia.</p>`,
  "650": "<p>Com a porta dos jardins às suas costas, tome o caminho da esquerda, a escassos metros, começa a ciclovia que lhe permitirá atravessar a famosa Puente del Real.</p>",
  "651": `<p>Historicamente há registo de que desde 1332, diversas passarelas ou pontes cruzavam o Turia por este mesmo local e também de que as contínuas cheias do rio as demoliam continuamente.</p>\n\n<p>Esta ponte tem várias curiosidades destacáveis, como por exemplo que as quatro esculturas que podem ver-se não são as que foram escolhidas originariamente.</p>\n\n<p>Em 1609, o barco que as transportava desde Génova foi assaltado por uns piratas que se apoderaram de toda a carga.</p>`,
  "652": `<p>Outra anedota, a mais conhecida, foi a ocorrida em 1528.</p>\n\n<p>A ponte, ainda de madeira, cedeu ao peso dos centenas de espetadores que se acumulavam para ver passar o Imperador Carlos Primeiro na sua visita a Valencia.</p>`,
  "653": `<p>A ponte que pode ver hoje em dia data de 1598.</p>\n\n<p>Após a cheia de 1590 tomou-se a decisão de construir uma base mais sólida para aguentar as fortes investidas.</p>\n\n<p>Naqueles tempos, a ponte já contava com dez arcos de treze metros de vão cada um.</p>\n\n<p>Anos mais tarde, em 1957, após outra cheia voltou a sofrer danos consideráveis, e em 1966 aumentou-se a largura da ponte, aliviando com isso a crescente atividade de tráfego da cidade.</p>`,
  "654": `<p>Atravesse a ponte e observará uma praça que se abre diante de si.</p>\n\n<p>Situada no Barrio de la Xerea, um dos mais antigos da cidade, a Plaza de Tetuán engloba vários edifícios importantes que são dignos de menção.</p>\n\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "655": `<p>O seu objetivo é o pequeno jardim que se encontra no lado oposto da praça.</p>\n\n<p>No seu mapa corresponde ao número <mark>79</mark>.</p>\n\n<p>Não pause esta audioguia e dirija-se ao seu próximo ponto de interesse.</p>`,
  "656": `<p>No transcurso para o seu próximo objetivo verá à sua esquerda o antigo Convento de Santo Domingo, um edifício de estilos gótico e barroco, que remonta à fundação da cidade uma vez que foi o próprio Rei Jaime primeiro quem colocou a primeira pedra em 1239 e no qual hoje em dia descansam os restos de vários personagens ilustres da cidade.</p>\n\n<p>Em frente, à direita, ergue-se um edifício monumental realizado em pedra branca que verá com mais detalhe no decorrer desta Aventura.</p>\n\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "657": `<p>O parque onde se encontra tem os seus inícios em 1812. Apelidado Parque da Glorieta foi o primeiro local iluminado da cidade.</p>\n\n<p>A 9 de outubro de 1844 colocaram-se vários candeeiros a gás distribuídos simetricamente pela rotunda e passeios laterais.</p>\n\n<p>Não é até 1852 que se plantam os grandes ficus que se destacam pela sua monumentalidade e as suas grandes raízes.</p>`,
  "658": `<p>Atualmente esses enormes Ficus encontram-se do outro lado do parque.</p>\n\n<p>Aproxime-se às árvores, se faz favor, para contemplar a sua majestosidade.</p>\n\n<p>Atrás da arborização situa-se o seu próximo ponto de interesse nesta aventura.</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
