import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "270": "<p>We beginnen met het prachtige <strong>Palacio de les Artes Reina Sofía</strong>; kunt u het zien? Het is volledig wit en zijn uitkragende dak valt op.</p>",
  "271": "<p>Het werd ingewijd in 2005 en is gewijd aan opera-programmering; het heeft capaciteit voor 3.500 aanwezigen.</p>\n<p>Zijn Intendanten en artistieke Directrices hebben dit lyrisch centrum weten te plaatsen onder de beste en meest gerenommeerde van het internationale podium.</p>\n<p>Door zijn 4 zalen zijn artiesten gegaan zo belangrijk als Plácido Domingo en Luciano Pavarotti.</p>",
  "272": "<p>Richt uw aandacht op het <strong>Museo Príncipe Felipe</strong>.</p>",
  "273": "<p>Kunt u het zien? Het heeft meer dan 5.000 ramen!</p>\n<p>Zoals u zult kunnen vaststellen, houden de Valencianen van de zon en daarom hebben veel van hun gebouwen grote glazen wanden, waarmee energieverbruik wordt bespaard door gebruik te maken van een natuurlijke en ecologische bron van licht en warmte.</p>",
  "274": `<p>Als u er bent tijdens de openingsuren, nodigt ${LOGO} u uit op pauze te drukken en de lokale gastronomie te ontdekken die deze prachtige ruimte biedt.</p>\n<p>U kunt uw avontuur hervatten zodra u het geschikt acht.</p>`,
  "274-B": `<p>Als u er bent tijdens de openingsuren, nodigt ${LOGO} u uit op pauze te drukken en de lokale gastronomie te ontdekken die deze prachtige ruimte biedt. U kunt uw avontuur hervatten zodra u het geschikt acht. Uw Avontuur gaat verder aan de deur tegenover de deur waar u zich momenteel bevindt.</p>`,
  "274-C": `<p>Als u er bent tijdens de openingsuren, beveelt ${LOGO} u aan op pauze te drukken en dit monument te betreden om de geschiedenis van de stad en haar gebruiken beter te leren kennen.</p>\n<p>De hoofdingang bevindt zich aan de tegenoverliggende kant van het monument.</p>\n<p>Dit is een perfect punt om een prachtige foto te maken van deze schat die Valencia ons biedt.</p>`,
  "275": "<p>Het <strong>Museo Príncipe Felipe</strong> werd ingewijd in het jaar 2000 met in totaal 26.000 vierkante meter tijdelijke en permanente tentoonstellingen.</p>\n<p>Deze ruimte, met als motto «Verboden niet aan te raken, niet te voelen en niet te denken», is een innovatief interactief wetenschapscentrum.</p>\n<p>Zijn vocatie is de interesse in wetenschappelijke en technologische kennis te bevorderen via plezier en entertainment.</p>\n<p>Met dit doel wordt groot belang gehecht aan de interactiviteit van de tentoonstellingen.</p>\n<p>Het is bovendien de zetel van verschillende sociale en culturele evenementen van de stad.</p>",
  "276": "<p>Ga verder <i>op zoek naar de schat</i> via dit geplaveide pad dat u rechtstreeks naar uw volgende doel leidt, de <strong>Puente de l'Assut de l'Or</strong>.</p>",
  "277": "<p>De naam van deze brug bestaat uit twee woorden: Azud, dat in het Arabisch «barrière» of «dam» betekent, en Or dat in het Valenciaans «Goud» is.</p>\n<p>Dus betekent l'Assut de l'Or «gouden dam».</p>\n<p>Deze brug staat echter ook bekend onder zijn bijnaam «de harpbrug».</p>",
  "278": "<p>De <strong>Puente de l'Assut de l'Or</strong> staat overeind dankzij 29 kabels die uit de voorzijde van zijn mast van 125 meter hoogte komen.</p>\n<p>Het brugdek heeft een lengte van 180 meter bij een breedte van 34 meter.</p>\n<p>Het werd volledig afgewerkt in december 2008 en is een van de hoogste bruggen van Spanje.</p>",
  "279": "<p>Dit avontuur brengt u naar de brug die een prachtig uitzicht biedt op de <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Terwijl u de brug oversteekt, let u bijzonder op aan uw linkerhand waar het <strong>Ágora</strong> uitsteekt.</p>\n<p>Nummer <mark>16</mark> op uw kaart.</p>\n<p>Net achter het Ágora bevindt zich het bekende <strong>Oceanogràfic</strong>.</p>\n<p>Dat correspondeert op uw kaart met nummer <mark>17</mark>.</p>\n<p>Eenmaal over de brug, ga, zoals uw kaart aangeeft, naar een veilige zone die een prachtig uitzicht biedt op dit gebied. De veilige zone die wij voorstellen bevindt zich links, terwijl u van de brug afdaalt.</p>\n<p>Druk op pauze, bekijk het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "280": "<p>Ga door tot het einde van de straat waar de <strong>Calle Caballeros</strong> kruist, die op uw kaart overeenkomt met nummer <mark>20</mark>.</p>\n<p>Eenmaal daar, sla rechtsaf en u ziet het emblematische gebouw van het <strong>Palacio de la Generalitat</strong>, dat op uw kaart nummer <mark>21</mark> aangeeft.</p>\n<p>Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "281": "<p>Het zelfstandig naamwoord Ágora komt uit het Grieks en betekent publiek plein van het sociale leven.</p>",
  "282": "<p>Deze ruimte, voorlopig voltooid in 2009, is een metaalconstructie met een plattegrond vergelijkbaar met een puntige ellips.</p>\n<p>Het Ágora meet ongeveer 88 meter lang bij 66 breed en 80 hoog; het is een groot overdekt plein dat het complex voorziet van een multifunctionele ruimte.</p>\n<p>Dit monument is ontworpen als een podium voor congressen, conventies, concerten of voorstellingen, met de mogelijkheid te transformeren in een tentoonstellingsruimte.</p>\n<p>Het overdekte oppervlak bedraagt ongeveer 5.000 vierkante meter.</p>\n<p>Zijn vorm doet, aldus Calatrava zelf, denken aan twee gevlochten handen; het Ágora zal bovenaan vleugels hebben die vingers nabootsen en de hoeveelheid licht filteren die naar binnen treedt.</p>\n<p>Deze grote binnenruimte is ontworpen als een overdekt openbaar plein, met een open plattegrond, op het niveau van de naastgelegen vijvers en promenades.</p>\n<p>Het gebouw is omgeven door twee meren die als aanvulling op de binnenruimte dienen.</p>\n<p>In november 2009, het jaar van de inhuldiging, vond in zijn binnenruimte de Open 500 tennis van de Valenciaansche Gemeenschap plaats.</p>",
  "283": "<p>Richt uw aandacht op het complex dat achter het Ágora ligt.</p>\n<p>Deze ruimte staat bekend als het <strong>Oceanogràfic</strong>.</p>",
  "284": "<p>Met een oppervlakte van 110.000 vierkante meter en een watervolume gelijk aan 15 olympische zwembaden kan de bezoeker haaien, beloega's, walrussen, dolfijnen, zeeleeuwen, pinguïns, zeesterren en zeeëgels observeren.</p>\n<p>Een grote verscheidenheid aan schaaldieren en vissen, evenals typische vogels afkomstig van de Albufera van Valencia, een van de grootste moerassen van Spanje gelegen op ongeveer 12 kilometer ten zuiden van de stad.</p>\n<p>Ingewijd in 2002 is het een van de grootste aquaria van Europa. Daarin zijn de belangrijkste mariene ecosystemen van de planeet vertegenwoordigd: Middellandse Zee, Moerassen, Gematigde en Tropische Zeeën, Antarctische en Arctische Oceanen, Eilanden en Rode Zee.</p>",
  "285": "<p>Laten we doorgaan met de Schattenjacht!</p>\n<p>Met het Ágora en het Oceanogràfic achter u, zoek een boomachtige constructie die voor u aan de andere kant van de weg ligt. Kunt u het zien?</p>",
  "286": "<p><strong>l'Umbracle</strong>: is een begroeide uitkijkpost waar de bekende <strong>Paseo de las Esculturas</strong> (Beeldentuin) zich bevindt.</p>\n<p>In dit gebied valt zijn centrale tuin op, beplant met inheemse mediterrane flora.</p>\n<p>De vloer van deze tuin is van teakhout vanwege zijn natuurlijke duurzaamheid in extreme klimatologische omstandigheden.</p>\n<p>Onder deze promenade bevindt zich de parkeerplaats van het complex met capaciteit voor 20 bussen en 650 voertuigen.</p>",
  "287": "<p>Vanaf dit punt begint het tweede scenario dat we u voorstellen.</p>\n<p>Uw avontuur gaat rustig verder tot het einde van de promenade, terug naar Reina Sofía.</p>\n<p>Reina Sofía correspondeert op uw kaart met nummer <mark>12</mark>.</p>\n<p>Stel u op met het monument voor u en zoek de toegang die aan de voorzijde afdaalt, waardoor u een nader uitzicht krijgt op de <strong>Ciudad de las Artes y de las Ciencias</strong>. Eenmaal beneden verschijnt l'Hemisfèric.</p>\n<p>l'Hemisfèric correspondeert op uw kaart met nummer <mark>19</mark>.</p>",
  "287-B": "<p>Vanaf dit punt begint het tweede scenario dat we u voorstellen.</p>\n<p>Uw avontuur gaat rustig verder tot het einde van de promenade, terug naar Reina Sofía dat op uw kaart correspondeert met nummer <mark>18</mark>.</p>\n<p>Stel u op met het monument voor u en zoek de toegang die aan de voorzijde afdaalt, waardoor u een nader uitzicht krijgt op de <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Eenmaal beneden verschijnt l'Hemisfèric dat op uw kaart correspondeert met nummer <mark>25</mark>.</p>",
  "288": "<p>Ga naar het emblematische <strong>Palacio de la Generalitat</strong> dat op uw kaart overeenkomt met nummer <mark>21</mark> en de laatste halte in dit avontuur is.</p>",
  "289": "<p>We nemen afscheid, maar niet zonder u een fijne Fallas te wensen en u aan te raden de vuurwerkkasteelspektakels niet te missen die van 15 tot 19 maart worden afgeschoten.</p>",
  "290": "<p>Dit is een perfect punt om prachtige foto's te maken van de <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Tot beneden! Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "291": `<p>l'Hemisfèric was het eerste gebouw dat zijn deuren opende voor het publiek in de <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Ingewijd in 1998 en met capaciteit voor 300 personen, is deze ruimte gewijd aan IMAX-cinema in 3 dimensies.</p>\n<p>Architectonisch gesproken valt het monument op door de originaliteit van zijn schuifdeuren die, dankzij een speciaal mechanisme, openen en sluiten als een echt oog.</p>\n<p>${LOGO} nodigt u uit op pauze te drukken en naar wens te genieten van dit futuristische complex met innovatieve lijnen in een omgeving van millenniumoud inspiratie.</p>\n<p>Het is onze taak bepaalde details te verschaffen die onze kijk op de <strong>Ciudad de las Artes y de las Ciencias</strong> verrijken.</p>\n<p>Merk op dat de decoratie van het complex een mozaïek van Valenciaanse keramiek is, een Arabisch erfgoed uit hun kolonisatieperiode; opnieuw keren we terug naar de Arabische cultuur wanneer we de enorme waterrijke ruimten bewonderen die de omringende monumenten vergroten en grootser maken.</p>\n<p>Zodra u besluit verder te gaan, druk gewoon op de bijbehorende knop en ga verder <i>op zoek naar de schat</i>.</p>\n<p>De omgeving van de <strong>Ciudad de las Artes y de las Ciencias</strong> is perfect om te genieten van de Valenciaanse zon en van een traditionele Valenciaanse Orxata.</p>`,
  "292": "<p>Terwijl u geniet van uw eigen tijd, probeert u deze uitdagingen op te lossen.</p>\n<p>Uit hoeveel monumenten bestaat de <strong>Ciudad de las Artes y de las Ciencias</strong>?</p>\n<p>Waarvan is de Orxata gemaakt? Van chufa, rijst of gerst?</p>",
  "293": "<p>Uw avontuur gaat verder bij de <strong>Puente de la Mar</strong>.</p>\n<p>De voetgangersbrug uit de 16e eeuw, die u al in dit avontuur heeft leren kennen.</p>",
  "294": "<p>Door de schade die de verschillende overstromingen van de <strong>Rivier de Turia</strong> aan de structuur van de Puente de la Mar toebrachten — die destijds van hout was — werd in 1425 begonnen met de bouw van een robuustere structuur, ook van hout, maar een nieuwe vloed in 1589 verwoestte die volledig.</p>\n<p>In 1591 werd Francesc Figueroa belast met de wederopbouw in steen. De werken werden voltooid in 1596.</p>\n<p>In die tijd telde de brug al tien gewelfde spitsbogen en een kapelletje dat het Kruisje van de Brug beschermde.</p>",
  "295": "<p>Wat omgeeft de voet van de brug? Water, gras of eenden?</p>",
  "296": "<p>Gefeliciteerd! U heeft alle aanwijzingen verzameld en de raadsels opgelost die het oude rivierbed u voorstelde... Tot nu toe. Maar dit Avontuur is hier nog niet voorbij!! Zoals u zult kunnen vaststellen, brengt de schatzoekerkaart u terug naar de stad. Zullen we er aan beginnen?</p>",
  "296-B": "<p>Vanaf dit punt vervolgt het tracé van dit avontuur langs een stedelijk circuit!</p>\n<p>Ga voorzichtig; vergeet niet dat de verkeersregels moeten worden nageleefd.</p>\n<p>Bekijk de aanwijzingen op uw schatzoekerkaart en ga verder via het ingerichte rijstrook <i>op zoek naar de schat</i>.</p>\n<p>Aan de linkerkant van de tuin biedt een toegang u de mogelijkheid op te gaan en dit werk te oversteken, gesierd met 27.500 veelkleurige bloemen.</p>",
  "296-C": "<p>Gefeliciteerd! U heeft alle aanwijzingen verzameld en de raadsels opgelost die het oude rivierbed u voorstelde... Maar dit Avontuur is hier nog niet voorbij!!</p>\n<p>Zoals u zult kunnen vaststellen, brengt de schatzoekerkaart u terug naar de stad. Zullen we er aan beginnen?</p>",
  "297": "<p>Ga naar de volgende brug, de <strong>Puente de las Flores</strong>, ingewijd in 2002 en gesierd met 27.500 veelkleurige bloemen die variëren naar gelang het seizoen.</p>\n<p>Aan de rechterkant van de tuin biedt een toegang u de mogelijkheid op te gaan en dit werk van Santiago Calatrava te oversteken.</p>",
  "298": "<p>De brug mondt uit in een cilindrische structuur gebouwd in baksteen, veel ouder dan de brug.</p>\n<p>Deze structuur werd voornamelijk gebruikt om de watercisterns te vullen van de vrachtwagens die instonden voor de straatreiniging.</p>",
  "299": "<p>Ga vanaf dit punt voorzichtig; het gaat om een stedelijk tracé en de verkeersregels moeten worden nageleefd.</p>\n<p>Bekijk de aanwijzingen op uw schatzoekerkaart en ga verder via het fietspad om door het historisch centrum te trekken op zoek naar meer aanwijzingen.</p>\n<p>Aan het einde van de laan, bij de rotonde, wacht uw volgende doel.</p>",
  "300": "<p>De <strong>Puerta de la Mar</strong> werd heropgebouwd in 1946.</p>\n<p>Dit is een replica van de oude stadspoort die tot 1868 op deze zelfde plek stond.</p>\n<p>De toegangspoort werd in 1868 tegelijk met de stadsmuren afgebroken. Het monument dat u vandaag kunt zien, is een eerbetoon aan de Gevallenen tijdens de Spaanse Burgeroorlog van 1936 tot 1939.</p>\n<p>Het monument bestaat uit drie openingen; één centraal met een rondboog en twee zijdelingse met rechte bovenzijden.</p>\n<p>In de centrale boog is een groot marmeren kruis te zien.</p>",
  "301": "<p>Op het hoogste gedeelte van het centrale lichaam dat het geheel vormt, vinden we een groot schild van de stad Valencia.</p>\n<p>De decoratie wordt aangevuld door een geheel van militaire parafernalia-elementen op elke hoek.</p>",
  "302": "<p>Weet u nog welk dier het schild van Valencia kroont? Is het een geit, een vleermuis, een draak of misschien een leeuw?</p>",
  "303": "<p>Vouw uw kaart open en merk dat uw schatzoekerkaart u aangeeft door te gaan via het ingerichte rijstrook tot aan het volgende bezienswaardigheidspunt in dit Avontuur. Vergeet de verkeersregels niet te respecteren!</p>\n<p>De <strong>Calle Colón</strong>, die links van u opent, is bij uitstek een van de winkelstraten en biedt alle soorten mogelijkheden voor shopliefhebbers.</p>\n<p>In deze straat, die tegenwoordig de plaats volgt die de muur van het 15e-eeuwse Valencia innam, bieden talrijke winkels allerlei diensten aan en veraangenamen het leven van de voorbijgangers met etalages en terrassen.</p>\n<p>Ga door, zoals uw kaart aangeeft, naar uw volgende bezienswaardigheidspunt.</p>\n<p>Richt tijdens uw tocht uw aandacht aan uw linkerhand.</p>",
  "304": "<p>Ontworpen in 1901 is het <strong>Casa de los Dragones</strong> gelegen in een van de straten van de eerste stadsuitbreiding van Valencia.</p>\n<p>De bijzondere decoratie van de gevels valt op: let op de locomotief, of de enorme draak die een schild draagt, en besteed ook aandacht aan het minutieus ontworpen smeedwerk.</p>",
  "305": "<p>Wat is er te zien op de locomotief? Is het een ster, een schild, of misschien een datum?</p>",
  "306": "<p>Laat dit gebouw links van u en richt uw aandacht op het volgende plein.</p>\n<p>Uw avontuur brengt u naar een van de meest iconische moderne plekken van Valencia.</p>",
  "307": "<p>Dit is een perfect punt om prachtige foto's te maken van de architectonische schatten die de stad biedt en te genieten van een bijzondere cocktail als het <strong>Agua de Valencia</strong>, of de traditionele Orxata; een verfrissende natuurlijke drank die de dorst lest, vergezeld van de onafscheidelijke zachte bolletjes genaamd Fartons.</p>",
  "308": "<p>De <strong>Mercado de Colón</strong> werd ook gebouwd in een van de bouwblokken van de eerste Ensanche.</p>\n<p>Het was bestemd om dit deel van de stad te bedienen, omdat de grote <strong>Mercado Central</strong>, die u verderop in dit Avontuur zult bezoeken, vrij ver weg lag.</p>\n<p>De <strong>Mercado de Colón</strong> werd gebouwd tussen 1914 en 1917.</p>\n<p>Hoewel de officiële inhuldiging plaatsvond op Kerstavond 1916.</p>",
  "309": "<p>Zoek de meest monumentale gevel; deze onderscheidt zich door traditionele Valenciaanse decoratieve elementen: groenten en tuinproducten, boerderijdieren en zeeprodukten.</p>\n<p>Besteed speciale aandacht aan de scène in het mozaïek, in het Valenciaans bekend als <strong>Trencadís</strong>.</p>\n<p>De Valenciaanse architectuur wordt gekenmerkt door een reeks decoratieve elementen zoals Valenciaanse keramiek, mozaïeken genaamd Trencadís, en reliëfs.</p>",
  "310": "<p>Welke elementen zijn te zien in deze scène? Een Fallero en een Fallera? Zijn er sinaasappelbomen? Of druiven?</p>",
  "311": "<p>Onder deze scène versierd een ander kenmerkend element van de markten de spitsboog.</p>",
  "312": "<p>Wat kan het zijn? Misschien broden? Kunt u ook krabben zien? En appels?</p>",
  "313": "<p>Richt uw aandacht op de zuilen, de uitstekende balken, de schilden op de torens... Hoeveel dieren kunt u tellen? Onder hen merkt u dat er koeien en varkens zijn...</p>",
  "314": `<p>Uw Avontuur gaat verder aan de andere gevel van dit monument. Precies aan de tegenoverliggende kant van het gebouw.</p>\n<p>${LOGO} nodigt u uit op pauze te drukken en de lokale gastronomie te ontdekken die deze prachtige ruimte biedt.</p>\n<p>U kunt uw avontuur hervatten zodra u het geschikt acht.</p>`,
  "315": "<p>De gevel van het monument wordt gevormd door een grote spitsboog van 16 meter hoogte. Het timpaan van de boog is bedekt met geglazuurde tegels.</p>",
  "316": "<p>Op de koepel van de boog steekt een groot stadsschild gebouwd in steen uit. Het schild van Valencia wordt gekroond door de mythische vleermuis. Kunt u het zien?</p>",
  "317": "<p>Bekijk uw kaart die u terug leidt naar het tracé van de muren.</p>\n<p>Laat de laatste gevel van de markt aan uw linkerhand en zoek de toegang tot uw volgende doel dat u terugbrengt naar de middeleeuwse tijd.</p>",
  "318": "<p>In het Valencia van de 14e eeuw onderscheidde de stad haar culturen in omuurde wijken met specifieke wetgeving die hun rechten en bewegingen beperkte.</p>\n<p>Hoewel het een katholieke stad was, leefden in Valencia ook moslims en joden samen die, met hun culturen, deel bijdroegen aan de fundamenten van het Valencia van de 21e eeuw.</p>\n<p>Deze «Ruïnes» die u nu kunt zien, zijn concreet de poort van de jodenbuurt.</p>\n<p>Een van de twaalf poorten die de christelijke stadsmuur van Valencia had.</p>\n<p>De ruïnes van de oude stadsmuur kwamen tevoorschijn tijdens de werkzaamheden aan de metrolijn en men besloot het erfgoed zichtbaar te laten als illustratief deel van de werken.</p>",
  "319": "<p>Ga, zoals uw kaart aangeeft, verder via het ingerichte rijstrook tot aan uw volgende punt met uitdagingen te lossen.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
