import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "220": "<p>Uitzonderlijk zijn ook de stoofpot van paling, de all-i-pebre, en de heerlijke knoflookaïoli, uitgesproken als all-i-oli.</p>",
  "221": "<p>Onder het lokale gebak valt de turrón op, bij uitstek het kerstgebak, de arnadí van pompoen, en de beroemde Orxata de Chufa die, gefrappeerd of vloeibaar en vergezeld van de onafscheidelijke «Fartons», de zomermiddagen zal verwennen.</p>",
  "222": "<p>Nu u al een beetje weet over de geschiedenis en gastronomie van onze streek, is het moment aangebroken om uw avontuur te beginnen. Geniet ervan! Uw avontuur begint in de <strong>Calle de los Serranos</strong>. Vergeet niet dat u, om vooruit te komen in de route, bij elk bezienswaardigheidspunt moet stoppen, de aangegeven plek bekijken of uw uitdaging voltooien, en vervolgens naar de volgende voorgestelde bestemming gaan, enzovoort. Alles klaar om te beginnen? Daar gaan we, succes! Richt vanuit de <strong>Calle de los Serranos</strong> uw aandacht naar het einde van de straat en zie de torens die op uw kaart zijn aangegeven met nummer <mark>1</mark>.</p>",
  "223": "<p>Bevindt u zich al in de <strong>Calle de los Serranos</strong> met de torens in het zicht? Uitstekend, laten we beginnen! Indrukwekkend als ze zijn, zijn deze torens uit het einde van de 14e eeuw in Valenciaans gotische stijl.</p>\n<p>Dit monument van militaire architectuur, opgetrokken uit gehouwen stenen, was een van de twaalf poorten die de oude christelijke stadsmuur van Valencia bewaakten. Tegenwoordig zijn er nog maar 2.</p>\n<p>Hoewel hun hoofdgebruik militair en defensief was, werden ze ook gebruikt voor ceremonies en officiële intochten van koningen en ambassadeurs.</p>\n<p>Deze torens, tegenwoordig bezochbaar, werden (en worden nog steeds) beschouwd als de hoofdingang van de stad.</p>",
  "224": "<p>Vanwege het belang van zijn collecties is het een duidelijke referentie voor oude Valenciaanse meesters.</p>\n<p>In 1683 begon architect Juan Bautista Pérez een bouw die 60 jaar in beslag zou nemen.</p>\n<p>Het oorspronkelijke gebruik was een college voor mindere geestelijken en een woonplaats voor missionarissen.</p>\n<p>Hoewel het gebouw tijdens zijn geschiedenis een zeer gevarieerd verloop kende met verschillende restauraties, wijzigingen en gebruiken: in 1819 was het een militaire academie, in 1826 het Casa de la Beneficencia, in 1835 werd het gebruikt als opslagplaats voor militaire uitrusting en in 1843 was er een militair hospitaal gevestigd.</p>\n<p>Sinds 2017, in de functie van <strong>Museum voor Schone Kunsten</strong>, is het ook een referentie geworden voor de richting die de schatzoekers van dit avontuur moeten nemen.</p>",
  "225": "<p>Ga door tot de volgende brug, de <strong>Puente de las Flores</strong>.</p>",
  "226": `<p>Zoals we in de inleiding vermeldden: <i>Op zoek naar de schat</i> is een reeks audiogeleide Avonturen met verschillende routes en afstanden die u op uw eigen tempo kunt beleven.</p>\n<p>${LOGO} stelt u ook uitdagingen voor; daarin moedigen we u aan bepaalde details van de monumenten op te merken die anders onopgemerkt zouden blijven.</p>\n<p>Hier is de eerste van uw uitdagingen, en deze is gemakkelijk.</p>`,
  "227": "<p>Bovenaan de zijopeningen vinden we twee reliëfs, gewijd aan «Al Valor» en aan «La Abnegación».</p>",
  "228": "<p>Weet u mij te zeggen hoe deze Torens heten?</p>\n<p>Druk op pauze, los vervolgens uw uitdaging op en druk opnieuw op de doorgaan-knop.</p>",
  "229": "<p>Heeft u het geraden? Bravo, u heeft zojuist uw eerste uitdaging opgelost, naar de volgende!</p>",
  "230": "<p>Ga naar het midden van de brug en kijk links en rechts om een beetje inzicht te krijgen in de geschiedenis van de route die we gaan verkennen.</p>",
  "231": "<p>Het is zeker dat vroeger de bronnen van drinkwater van de stad, evenals de oorsprong van de irrigatiekanalen voor de velden, hun basis hadden in de <strong>Rivier de Turia</strong>. Maar na de catastrofale overstromingen van 14 oktober 1957 en de latere omleiding van de rivier naar een veiligere plek in de stad, maakten de Valencianen, met hun kenmerkende passie, ruimte voor vrije tijd, cultuur en sport in deze ruimte van 9 kilometer lang en 200 meter breed.</p>",
  "232": "<p><i>Op zoek naar de schat</i> doorkruisen we een tuin van Arabische inspiratie tussen Dennen, Iepen, Palmbomen, Cipressen, Moerbeibomen, Wilgen en Sinaasappelbomen.</p>\n<p>Een majestueuze groene ruimte die, hoewel verfijnd, het beeld biedt van een eerder rustiek en natuurlijk terrein met een modern tintje.</p>",
  "232-B": "<p>Een majestueuze groene ruimte die, hoewel verfijnd, het beeld biedt van een eerder rustiek en natuurlijk terrein met een modern tintje.</p>",
  "233": "<p>Op de top wappert de vlag van Valencia: haar kleuren bestaan uit rood, geel en... Violet, Groen of Blauw?</p>",
  "234": "<p>Aan een kant van de brug valt een gebouw op met een prachtige blauwe koepel, geflankeerd door twee robuuste torens. Kunt u het zien?</p>",
  "235": "<p>Sinds 1946 herbergt dit gebouw het <strong>Museum voor Schone Kunsten</strong>, een van de eerste van Spanje; gedurende zijn transitie een grote artistieke rijkdom bewarend in zijn schilderijen afkomstig van oude kerken en kloosters.</p>",
  "236": `<p>${LOGO} raadt u aan de kaart te volgen om niet van koers te raken en ten volle van de reis te genieten.</p>`,
  "236-A": `<p>${LOGO} raadt u aan de kaart te volgen om niet van koers te raken en ten volle van de reis te genieten.</p>\n<p>Uw schatzoekerkaart geeft aan dat u naar het rivierbedding moet afdalen.</p>\n<p>Ga daarvoor terug naar de torens en volg het fietspad links van u tot aan het afdaalpunt.</p>`,
  "236-B": "<p>Ga door tot de <strong>Puente de la Exposición</strong>, aangegeven op uw kaart met nummer <mark>4</mark>. Dank u.</p>",
  "236-C": "<p>Uw schatzoekerkaart geeft aan de brug te voltooien en af te dalen naar het rivierbedding.</p>\n<p>Volg daarvoor de kaart tot het afdaalpunt. Dit bevindt zich aan uw linkerhand en is op uw kaart aangegeven met nummer <mark>3</mark>.</p>\n<p>Eenmaal beneden, ga naar het midden van het bed van deze oude rivier en kijk om u heen; u kunt ruïnes zien die uitsteken tussen de botanische decoratie van de <strong>Jardín del Turia</strong>. Tussen cipressen en olijfbomen zijn resten van het Palacio del Real te bewonderen. Kunt u ze zien? Ja? Perfect, want de volgende geschiedenis hoopt ons u te verrassen.</p>\n<p>Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "237": "<p>De <strong>Puente de la Exposición</strong>: gewoonlijk «Puente de la Peineta» (Kambrugbrug) genoemd, verwijst naar een object in de vorm van een convexe kam die wordt gebruikt om de kapsels van de falleras, de koninginnen van onze volksvieringen, te versieren en vast te houden.</p>",
  "238": "<p>Het traditionele fallera-kapsel is ongetwijfeld het bekendste kapsel van Spanje.</p>\n<p>Het fallera-kapsel gaat terug tot de 18e eeuw, een tijd waarin vrouwen hun haar in een paardenstaart trokken en het verdeelden in acht lokken die in de vorm van een acht werden «gevlochten» rondom een of twee dikke naalden.</p>\n<p>Ter afronding omringden twee vlechten het centrale opgestoken haar.</p>\n<p>Het typische fallera-kapsel wordt afgerond met een achterste kam die met de hand is gemaakt in verzilverd of verguld messing.</p>\n<p>Ter voltooiing van het kapsel werden twee haarrolletjes ter hoogte van de oren toegevoegd, vastgehouden met twee haarspelden en twee replica's van de hoofdkam.</p>",
  "239": "<p>Weet u mij te zeggen hoe deze volksvieringen van Valencia heten? Zou het La Tomatina zijn, de Sint-Jansvuren of misschien de Fallas?</p>",
  "240": "<p>De buskruittraditie is geboren in Valencia als gevolg van de Bourbonistische overwinning in de Slag bij Almansa, concreet op 25 april 1707, toen Valencia werd bezet door de troepen van Felipe V.</p>\n<p>Daarna werd de wapenfabriek ontmanteld en overgebracht naar Toledo.</p>\n<p>Er werden grote hoeveelheden vuurwapens van middelgroot kaliber bewaard, bekend als «Traques» of Trabucos.</p>\n<p>Om een opstand te voorkomen werden de oudste trabucos opgestapeld op het fabrieksplein en verbrand.</p>\n<p>Nadat het hout van de kolfstukken was verbrand, werden de lopen als schroot verkocht.</p>\n<p>Vele smeden kochten deze resten, maar smolten ze niet; ze bewaarden ze en namen de gewoonte aan deze buizen in de grond te steken, ze met buskruit te laden en vervolgens af te vuren om de volksvieringen in de dorpen en alquerías te vieren.</p>",
  "241": "<p>Door de toename van voertuigen in het Valencia van de 20e eeuw waren nieuwe bruggen nodig die de stad verbonden.</p>\n<p>De <strong>Puente de las Flores</strong> was een uitstekend voorstel dat niet onopgemerkt kon blijven in het Land van de bloemen, het licht en de kleur.</p>",
  "242": "<p>Richt uw aandacht op de loop van de rivier. Tijdens dit avontuur maakt u een korte tijdsprong, meer bepaald naar de 16e eeuw bij het passeren onder de oude <strong>Puente de la Mar</strong>.</p>",
  "243": "<p>U keert opnieuw terug naar de 21e eeuw, aangezien dit avontuur u aanspoort de toegang te zoeken die u naar de bovenkant van de <strong>Puente de Aragón</strong> leidt.</p>",
  "244": "<p>Bevindt u zich in het midden van de brug?</p>\n<p>In rationalistische stijl ontleent de <strong>Puente de Aragón</strong> zijn naam aan het voormalig treinstation, nu verdwenen, dat de lijn Valencia-Aragón bediende en werd ingewijd in augustus 1933.</p>",
  "245": `<p>${LOGO} raadt u aan het ingerichte rijstrook te volgen en een veilige plek te zoeken waar u kunt stoppen om de volgende uitdaging te voltooien.</p>`,
  "245-B": `<p>${LOGO} raadt u aan de rotonde te omrijden tot aan het park aan de overkant en een veilige plek te zoeken waar u kunt stoppen om de volgende uitdaging te voltooien.</p>`,
  "245-C": `<p>${LOGO} raadt u aan het ingerichte rijstrook te volgen en een veilige plek te zoeken waar u kunt stoppen om de volgende uitdaging te voltooien.</p>`,
  "246": "<p>Onder zijn talrijke versieringen valt er één in het bijzonder op die zichtbaar is vanuit het centrale gedeelte van de top, kijkend naar beneden op het bed van de Turia.</p>\n<p>«De natuur» heeft het schild van Valencia geboetseerd. Wat is er te zien bovenop het schild? Een Vleermuis of een Draak?</p>",
  "247": "<p>Vanaf dit punt vervolgt het tracé van dit avontuur langs een stedelijk circuit! Vervolg uw avontuur via het rijstrook voor persoonlijke voertuigen. De kaart geeft aan terug te keren naar de 16e-eeuwse brug die we achter ons hebben gelaten. Weet u nog hoe die heet? Het is de <strong>Puente de la Mar</strong>.</p>",
  "248": "<p>Het is de moeite waard om dit werk van Javier Goerlich te bewonderen, die in 1935 deze prachtige trap ontwierp die toegang geeft tot de brug.</p>\n<p>In 1876 oversteekte de tram van de lijn richting de haven deze brug totdat de tram in 1900 werd geëlektrificeerd en de lijn in onbruik raakte.</p>\n<p>26 jaar later, in 1926, werd in Valencia een nieuwe brug gebouwd die de rivier oversteekt en daarmee het verkeer op de Puente de la Mar verlichte; sindsdien is het een voetgangersbrug.</p>\n<p>Om de helling te overbruggen werden twee golvende trappen, vier bankjes op de afgeschuinde hoeken en de pinakels aangelegd die het huidige beeld van de brug bepalen.</p>",
  "249": "<p>Weet u hoeveel treden de brug heeft?</p>",
  "250": "<p>Neem de dichtstbijzijnde toegang terug naar het rivierbedding, die zich vlak achter u in de riviermuur zou moeten bevinden.</p>\n<p>Eenmaal beneden, wacht uw volgende uitdaging bij het volgende monument.</p>",
  "251": "<p><i>Op zoek naar de schat</i> betreden we het domein van de vegetatie, het licht, het water en de muziek.</p>\n<p>Om het goed te kunnen waarderen, stel u op aan de andere kant van de fontein met het gebouw voor u.</p>",
  "252": "<p>Ingewijd in 1987 in functioneel-rationalistische stijl, vervult het <strong>Palacio de la Música</strong> de functie van auditorium van Valencia.</p>\n<p>Zijn vier zalen en de glazen koepel bieden capaciteit voor ongeveer 2.500 aanwezigen en zijn geprezen door gerenommeerde musici en zangers.</p>",
  "253": "<p>Welk type bomen kunt u op dit moment aanraken? Zijn het palmbomen, olijfbomen of misschien amandelbomen? Raad eens!</p>",
  "254": "<p>Vervolg uw avontuur door de fontein te omronden om de linkerkant van de rivier opnieuw op te nemen en volg dat pad onderdoor de <strong>Puente del Ángel</strong>.</p>",
  "255": "<p>Een brug gebouwd tussen 1941 en 1948, met een lengte van 150 meter en een breedte van 31,5 meter.</p>",
  "256": "<p>De aanwijzingen leiden u naar een nieuw tijdspoort; dit opent zich verderop, aan uw rechterhand, en brengt u naar een fantastisch tijdperk van oude verhalen.</p>",
  "257": "<p>Concreet naar de reizen van <strong>Gulliver</strong>.</p>",
  "258": "<p>Kinderen en volwassenen genieten van deze uitbeelding van het verhaal van Jonathan Swift, waarin ze zich kunnen voorstellen Lilliputters te zijn die over <strong>Gulliver</strong> zelf rennen en van zijn enorme glijbanen glijden.</p>\n<p>Zijn hoed stelt een andere reis van <strong>Gulliver</strong> voor, toen hij reisde naar Brobdingnag, het Land van de Reuzen.</p>\n<p>Ga naar de hoofdingang om de volgende uitdaging op te lossen.</p>",
  "259": "<p>Weet u mij de prijs te zeggen voor toegang tot deze attractie? Het zou gratis kunnen zijn...</p>",
  "260": `<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en te genieten van de enorme glijbanen!</p>\n<p>Dit is een perfect punt om een prachtige foto te maken van deze schat die Valencia ons biedt.</p>\n<p>Gebruik de pauzeknop naar wens; wanneer u voelt dat het juiste moment is gekomen, ga dan gewoon verder en los onze uitdagingen op terwijl u de stad ontdekt.</p>`,
  "261": "<p>Uw avontuur gaat verder in een recreatiegebied met skatebanen en speeltuinen, dat enkele meters verderop ligt, langs het oude rivierbed.</p>",
  "262": "<p>Welkom bij de <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Besteed speciale aandacht aan uw kaart; dit prachtige complex bestaat uit zes grote elementen.</p>",
  "263": "<p>Dit plein, met een driehoekige plattegrond, draagt de naam <strong>Plaza del Ayuntamiento</strong> sinds 1987.</p>\n<p>Een stedelijke omgeving die verschillende verbouwingen heeft ondergaan, waaronder de sloop van het Convento de San Francisco in 1891, waardoor een directe verbinding tussen twee commerciële wijken van de stad mogelijk werd.</p>\n<p>Op het plein zelf werd ook de bloemenmarkt gevestigd, die van 1924 tot op heden de stad veraangenaamt en verrijkt.</p>\n<p>In Valencia zijn er veel fonteinen die de omgeving rondom hen verfrissen. De fontein die we vandaag kunnen zien werd gebouwd door Carlos Buigues en ingewijd in maart 1962.</p>",
  "264": "<p>Ontworpen door Santiago Calatrava en Félix Candela, is de <strong>Ciudad de las Artes y de las Ciencias</strong> een uniek ensemble van wereldwijde architectonische avant-garde gewijd aan wetenschappelijke en culturele verspreiding.</p>\n<p>De blauwe en witte kleuren en de gedurfde lijnen identificeren de 21e-eeuwse hoofdstad van de Turia.</p>\n<p>De <strong>Ciudad de las Artes y de las Ciencias</strong> is het futuristische beeld dat het nieuwe Valencia symboliseert; een moderne stad binnen de millenniumlange stad, waar miljoenen bezoekers elk jaar naartoe komen om te genieten van haar cultuur, natuur, kunst en wetenschap.</p>",
  "265": "<p>Om uw avontuur eenvoudiger en aangenamer te maken, hebben we de te bezoeken elementen in twee fasen georganiseerd. Op deze manier kunt u ze rustig verkennen, zonder haast, en van elk moment optimaal genieten. Elke fase is bedacht om een volledigere en georganiseerde ervaring te bieden, zodat u het maximale kunt halen uit alles wat ze te bieden hebben, terwijl u van elk moment van uw route geniet.</p>",
  "266": "<p>De eerste: biedt een panoramisch uitzicht op de <strong>Ciudad de las Artes y de las Ciencias</strong>. Door langs de linkerkant van de Jardín del Turia te gaan, de <strong>Puente l'Assut de l'Or</strong> over te steken en daarna op te gaan naar het uitkijkpunt dat <strong>l'Umbracle</strong> biedt.</p>",
  "267": "<p>De tweede: begint bovenaan, op het uitkijkpunt zelf, doorgaand tot het einde en afdalen via de toegang die het <strong>Palacio de las Artes Reina Sofía</strong> heeft aan de voorzijde.</p>\n<p>Bent u er klaar voor? Geniet ervan, want het is een wonder!</p>",
  "268": "<p>Neem de linkerkant van de tuin als referentie en betreed een fietspad dat loopt tussen aromatische en medicinale planten.</p>\n<p>Rozemarijn, tijm en lavendel vermengen hun geuren in een landschap van olijfbomen en oude ruïnes.</p>\n<p>Dit pad, met zijn talrijke uitkijkpunten, biedt een uitzonderlijk panorama van de <strong>Ciudad de las Artes y de las Ciencias</strong> die achteraan rechts opmerkelijk uitsteekt in de groene en begroeide omgeving.</p>",
  "269": "<p>Betreed het pad en kies een uitkijkpunt van waaruit u het gehele complex kunt zien.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
