import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "459": "<p>Exato! Uns banhos romanos. A sua missão? encontrar a marquesa onde se faziam as massagens. É verdade, ainda está de pé!</p>",
  "460": `<p>No séc. XIII, depois da reconquista cristã sobre esta mesma estrutura, levantou-se o edifício da Almoina, que deu nome ao lugar.</p>\n<p>Almoina (que em valenciano significa esmola) era uma instituição medieval de carácter beneficente que distribuía comida entre os mais desfavorecidos.</p>`,
  "461": `<p>Como pode comprovar, a estrutura arquitetónica que envolve a praça permite um contacto visual direto com o interior do museu enquanto que os espaços exteriores favorecem o diálogo num ambiente no qual os vestígios do passado são os verdadeiros protagonistas.</p>\n<p>Neste ponto encontra-se um dos melhores centros arqueológicos da Europa e contemplam-se ruínas que remontam à fundação da cidade no ano 138 antes de Cristo.</p>\n<p>Esta praça está considerada como a mais antiga da cidade. No passado, neste mesmo local, situava-se a praça maior romana que estava próxima ao foro. Ou seja, a zona central da antiga cidade de Valentia.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre neste espaço para conhecer melhor a história da cidade.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente, simplesmente prima o botão correspondente e continue <i>à procura do tesouro</i>.</p>\n<p>A sua aventura continua neste mesmo ponto.</p>`,
  "462": `<p>Para isso, concedeu a propriedade de todas as mesquitas e cemitérios muçulmanos ao arcebispado que, por sua vez, cristianizou estes templos renomeando-os como Paróquias dedicadas a Santas e Santos da nova religião que se instauraria nestas terras.</p>\n<p>Em 1245, a <strong>Iglesia de San Lorenzo</strong> foi escolhida como uma das dez Paróquias fundacionais da cidade.</p>\n<p>O templo que podemos ver hoje data de 1684, embora o campanário se tenha construído anos depois, em 1747. Infelizmente o terramoto de 1822 deslocou-o do seu eixo original. Pode vê-lo?</p>\n<p>O habitáculo superior aloja dois sinos: Santa Anna fabricada em 1718 e Domingo, de 1742.</p>\n<p>Remata o campanário um cupulino com um chamativo catavento onde podemos ver a imagem de São Lourenço.</p>`,
  "463": `<p>Situe-se, se faz favor, no centro da praça com o mercado em frente a si. À direita do famoso <strong>Mercado Central</strong>, emerge uma magnífica Igreja barroca. Pode vê-la? No seu mapa corresponde ao número <mark>16</mark>.</p>\n<p>Aproxime-se ao seu próximo objetivo, São João do Mercado.</p>`,
  "464": `<p>No centro do monumento sobressai o <strong>Cimborrio</strong> de estilo gótico.</p>\n<p>Desde o séc. XV eleva-se a uma altura de 40 metros deixando passar a luz natural e iluminando a catedral.</p>\n<p>Saberia determinar que geometria tem? Hexagonal, Octogonal ou Quadrangular?</p>`,
  "465": `<p>Seguindo o itinerário do mapa, vire-se e deixe a <strong>Basílica de la Virgen</strong> à sua esquerda e o <strong>Museo Arqueológico</strong> à sua direita, vá até ao final da rua e vire à sua mão esquerda.</p>\n<p>No trajeto, emerge a <strong>Plaza de la Virgen</strong>.</p>`,
  "465-B": `<p>Siga o seu mapa do tesouro e continue a andar até ao final da rua, onde se abre uma praça conhecida como a <strong>Plaza de la Virgen</strong>, uma das mais icónicas da cidade.</p>\n<p>No seu mapa fica indicado com o número <mark>3</mark>.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "466": `<p>A <strong>Plaza de la Virgen</strong> está rodeada pela Basílica, a Catedral e o <strong>Barrio de la Seu</strong> ou <strong>Barrio de la Catedral</strong>.</p>\n<p>Na metade norte da praça chama especialmente a atenção uma atraente Fonte Monumental talhada em bronze.</p>\n<p>Conhecida como a Fonte de Neptuno, é a representação alegórica do <strong>Rio Turia</strong>.</p>`,
  "467": `<p>Neptuno sustém na sua mão a cornucópia da abundância e está rodeado por figuras femininas com tocado de lavradores valencianas que representam as acequias principais que irrigam Valencia.</p>\n<p>Com que mão sustém Neptuno a cornucópia?</p>`,
  "468": "<p>Quantas figuras rodeiam a fonte?</p>",
  "469": "<p>A praça que se abre diante de si é um dos cenários mais queridos pelos valencianos, sobretudo durante as nossas festas populares, as Fallas.</p>",
  "470": "<p>A cada 1 de março a cidade tinge-se da cor das flores e da pólvora para receber a primavera e mais de um milhão de visitantes.</p>",
  "471": `<p>As Fallas vivem-se na rua pelo bom tempo que costuma fazer e porque a cidade se torna pedonal.</p>\n<p>As ruas apinhadas, a contemplação do monumento fallero e as paragens para refrescar são várias das razões pelas quais Valencia nas Fallas é uma festa incomparável.</p>`,
  "472": `<p>Nas Fallas tudo é festa: o estrondo da mascletà, os casales, os pasacalles e as bandas de música percorrem os mais de 700 monumentos falleros.</p>\n<p>O dia 15 de março começa a Plantà ou montagem do monumento, alguns atingindo os 25 metros de altura.</p>\n<p>Os monumentos falleros realizados em materiais combustíveis como madeira, cartão, papel ou tecidos queimam-se após alguns dias de exposição nas ruas, dando com este ato as boas-vindas à época primaveril.</p>`,
  "473": `<p>Precisamente, no centro desta praça ergue-se, cada ano, uma estrutura de madeira que serve de suporte para "tecer" com flores multicolores o manto da Padroeira de Valencia.</p>\n<p>A oferta de flores à "Mare de Deu dels Desamparats" tem os seus inícios dentro da Basílica desde que em 1941 umas hortelanas ofereceram uns ramos de flores à Virgem.</p>`,
  "474": `<p>Mas em apenas 8 anos, a Oferta obrigou os organizadores a realizá-la no exterior da Basílica.</p>\n<p>Tal era a devoção que na fachada do templo se construíram uns bastidores para depositar os ramos de flores.</p>\n<p>Anos depois incorporam-se às Ofertas as crianças e as bandas de música nos pasacalles.</p>\n<p>Tempo depois acorda-se que, na Oferta, só se poderá desfilar com trajes regionais e organizam-se novos itinerários já que, em 1964, o desfile triplicou chegando a reunir mais de vinte mil pessoas.</p>\n<p>Atualmente a Oferta das flores inicia-se no dia 17 até à madrugada do 19 de março chegando a superar os cento e trinta mil Falleras e Falleros deixando a <strong>Plaza de la Virgen</strong> repleta de flores.</p>`,
  "475": `<p>Lembre-se de que, se se encontrar em horas de visita, ${LOGO} recomenda-lhe que suba a este tesouro arquitetónico para conhecer melhor a história da cidade e os seus costumes.</p>`,
  "476": "<p>Dirija a sua atenção, desde fora, ligeiramente à direita da basílica.</p>",
  "477": `<p>Ao fundo, destaca a Porta Gótica da Catedral, a segunda a ser construída.</p>\n<p>Chamada a porta dos apóstolos pelas doze figuras esculpidas na sua portada, foi edificada no séc. XIV e está formada por dois corpos sobrepostos.</p>\n<p>No corpo inferior, pode distinguir-se a portada que se destaca do muro com arcos apontados, próprios do estilo gótico, e três arquivoltas com esculturas talhadas com anjos e santos.</p>\n<p>No tímpano da porta, pode ver-se a escultura de Santa Maria com o menino nos braços.</p>\n<p>Em ambos os lados da virgem distinguem-se anjos tocando instrumentos musicais.</p>\n<p>Não pause esta audioguia e aproxime-se, se faz favor, ao pórtico.</p>`,
  "477-B": "<p>Ao fundo, destaca a Porta Gótica da Catedral, a segunda a ser construída.</p>",
  "478": `<p>No corpo superior ressalta notavelmente o rosáceo em pedra que toma a forma do Sello de Salomão.</p>\n<p>Com um diâmetro de 6 metros e meio, cumpre a função de iluminação da catedral.</p>\n<p>O Rosáceo, que se pode ver hoje em dia, não é o original de 1462, uma vez que teve que ser substituído pelo deterioro do mesmo em 1957.</p>`,
  "479": `<p>No seu pórtico celebra-se, cada quinta-feira, o Tribunal das Águas; um julgamento rápido e de forma oral que se encarrega de solucionar os conflitos derivados do uso e aproveitamento da água de rega entre os agricultores.</p>\n<p>A origem deste tribunal, embora desconhecida, acredita-se que já existia um antecedente de época romana, mas a sua função tal e como se conhece hoje em dia produziu-se há mais de um milénio durante o reinado árabe.</p>`,
  "480": "<p>Seguindo o leito do antigo rio, a uns 200 metros, encontra-se a esplanada de onde se disparam os castelos de fogos de artifício. Como terá podido comprovar, os valencianos gostam da pólvora.</p>",
  "480-B": `<p>Dirija-se ao emblemático <strong>Palau de la Generalitat</strong> que no seu mapa corresponde ao número <mark>23</mark> e é a última paragem nesta aventura.</p>`,
  "481": `<p>O <strong>Palau de la Generalitat</strong> Valenciana está situado no <strong>Barrio de la Seu</strong> ou <strong>Barrio de la Catedral</strong> e iniciou a sua construção em 1421.</p>\n<p>Gozando de numerosas restaurações e ampliações, nas quais intervieram os principais mestres valencianos do seu tempo, o antigo ayuntamiento da cidade é de estilo gótico valenciano com intervenções renascentistas.</p>`,
  "481-B": `<p>Gozando de numerosas restaurações e ampliações, nas quais intervieram os principais mestres valencianos do seu tempo, o antigo ayuntamiento da cidade é de estilo gótico valenciano com intervenções renascentistas.</p>\n<p>O <strong>Palau de la Generalitat</strong> Valenciana, situado no <strong>Barrio de la Seu</strong> ou <strong>Barrio de la Catedral</strong>, iniciou a sua construção em 1421 e foi ampliado no séc. XVI com uma grande torre.</p>\n<p>Os canteiros encarregar-se-iam do trabalho usando pedra negra de Alcublas, mármore branco da Valldigna e pedra de Ribarroja, localidades próximas de Valencia.</p>`,
  "482": `<p>O edifício foi ampliado no séc. XVI com uma segunda grande torre de dimensões semelhantes à primeira.</p>\n<p>Para construí-la, os canteiros utilizaram pedra negra de Alcublas, mármore branco da Valldigna e pedra de Ribarroja, estas são localidades próximas de Valencia.</p>`,
  "482-B": "<p>Atualmente, alberga a sede do Governo da Comunitat Valenciana.</p>",
  "483": "<p>Qual das duas torres creem que é a mais nova, a da praça ou esta que tem em frente agora?</p>",
  "484": "<p>A resposta? A que tem diante de si!</p>",
  "485": `<p>Não pause esta audioguia. Situe-se com o monumento que acabámos de mencionar à sua mão esquerda e continue, como indica o seu mapa, pela rua que se abre à sua direita.</p>\n<p>No seu mapa corresponde ao número <mark>45</mark>.</p>`,
  "485-B": `<p>Não pause esta audioguia. Situe-se com o monumento que acabámos de mencionar à sua mão esquerda e continue, como indica o seu mapa, pela rua que se abre à sua direita, no seu mapa corresponde ao número <mark>4</mark>.</p>`,
  "486": `<p>A conhecida <strong>Calle Caballeros</strong> corresponde ao eixo este-oeste que percorria a antiga cidade romana, chamada, naqueles tempos, a via Decumanus Maximus.</p>\n<p>O Conjunto Monumental da Catedral, a construção do <strong>Palau de la Generalitat</strong> e a proximidade à Iglesia de San Nicolás incentivaram o assentamento das famílias nobres ao longo desta conhecida rua.</p>\n<p>Devido a este facto, o valor histórico e artístico da <strong>Calle Caballeros</strong> baseia-se em ser o ponto de concentração do poder da cidade.</p>\n<p>Nela situam-se numerosos palacetes onde vivia grande parte da nobreza valenciana.</p>\n<p>A <strong>Calle Caballeros</strong> mantém o seu nome desde 1412.</p>\n<p>Manter o mesmo nome durante tanto tempo é toda uma façanha para uma rua de qualquer cidade.</p>`,
  "487": `<p>Continue pela <strong>Calle Caballeros</strong> até ao próximo ponto de interesse.</p>\n<p>No seu mapa corresponde ao número <mark>46</mark>.</p>`,
  "487-B": `<p>Continue pela <strong>Calle Caballeros</strong> até ao próximo ponto de interesse.</p>\n<p>No seu mapa corresponde ao número <mark>5</mark>.</p>`,
  "488": `<p>A <strong>Iglesia de San Nicolás</strong> fica uns metros mais adiante, à sua esquerda.</p>\n<p>Preste atenção à entrada porque resulta desproporcionalmente pequena para o tamanho do interior do templo e poderia passar despercebida.</p>`,
  "489": `<p>A <strong>Iglesia de San Nicolás</strong> de Bari e San Pedro Mártir, também conhecida como "a pequena Capela Sistina de Valencia" é um templo de estrutura gótica com decoração barroca no seu interior.</p>\n<p>Inicialmente construída em 1245 sobre uma antiga mesquita árabe, a igreja sofreu uma reforma integral em 1455 dando-lhe a sua fisionomia gótica atual.</p>\n<p>Em 1693 cobriu-se a abóbada gótica com uma de estilo barroco, mais acorde com a época.</p>\n<p>Por volta do ano 1700, no seu interior, começou um ambicioso projeto que cobriria com frescos os seus mais de 2.000 metros quadrados.</p>\n<p>A <strong>Iglesia de San Nicolás</strong> foi declarada Monumento Histórico Artístico Nacional em 1981, e hoje em dia é uma das igrejas mais visitadas da cidade de Valencia.</p>`,
  "490": `<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e admire os numerosos e impressionantes detalhes dos frescos da capela.</p>\n<p>Quando decida continuar, observe o seu mapa que o leva a rodear a igreja para poder contemplar as outras fachadas, dignas também de menção.</p>\n<p>Para isso, tome a primeira rua que sai à sua mão esquerda.</p>`,
  "491": "<p>Com a porta de San Nicolás à sua esquerda, dirija-se a rodear a igreja e situe-se no centro da praça, dali poderá ver uma simples portada de estilo gótico.</p>",
  "492": "<p>O objetivo desta constante mudança é poder dar cabimento a toda a gente, por isso a cada duas semanas expõem-se estilos diferentes e periodicamente organizam-se aulas abertas de dança.</p>",
  "493": `<p>A portada foi construída no séc. XV, com arquivoltas que repousam sobre finas colunas.</p>\n<p>As arquivoltas são elementos decorativos que resolvem o problema estético que apresentam os vãos ou desníveis que pode haver num muro espesso; assim evita-se a sensação de túnel que pode chegar a gerar, e permite a entrada de mais luz no interior do recinto.</p>\n<p>O estilo gótico caracteriza-se pelos seus arcos apontados. Este, em concreto, está sobremontado por um arco conopial.</p>\n<p>Imagine que o arco se divide em quatro segmentos. O resultado seria: duas curvas côncavas e duas convexas que são características neste tipo de arcos.</p>\n<p>Mesmo abaixo do vértice deste arco conopial que mencionamos, encontra-se um curioso relevo. Centre a sua atenção... É uma representação de uma bandeja... com... com carne?</p>\n<p>Conta a lenda que estando São Nicolau de viagem parou numa taberna para jantar e o taberneiro serviu-lhe um prato de carne.</p>\n<p>Ao ir a abençoar a sua ceia, o Santo observou que a carne era humana.</p>\n<p>Nicolau denunciou o taberneiro uma vez que nas suas adegas também foram encontrados restos despedaçados de três adolescentes que o santo recompôs e ressuscitou miraculosamente.</p>`,
  "494": `<p>Centre a sua atenção sobre este arco conopial, local no qual um rosáceo gótico de 1455 ilumina a Igreja.</p>\n<p>Este rosáceo, que toma a forma da Estrela de David ou Sello Salomónico, é semelhante ao que viu na Catedral.</p>`,
  "494-B": `<p>Centre a sua atenção sobre este arco conopial, local no qual um rosáceo gótico de 1455 ilumina a Igreja.</p>\n<p>Este rosáceo, que toma a forma da estrela de David, é muito semelhante ao que verá na <strong>Catedral de Valencia</strong> no decorrer desta aventura.</p>`,
  "495": `<p>Na parte direita da porta, há uma capela fechada por uma grade.</p>\n<p>Nela, pode ver-se um painel de cerâmica que representa o "Cristo do Fossar".</p>\n<p>Recebe este nome pelo antigo cemitério que se situava mesmo debaixo dos seus pés.</p>`,
  "496": "<p>O que se pode ver neste painel cerâmico? São caveiras? É uma cruz? Há também uma pomba?</p>",
  "497": `<p>O campanário, que fica mesmo à direita, foi terminado em 1755 e foi reabilitado em 2007.</p>\n<p>Pode observar que a torre se compõe de três corpos:</p>\n<p>O primeiro, o que alcança a altura do telhado.</p>\n<p>O segundo, o que está construído em tijolo e o terceiro é o que aloja os sinos, os quais podem perceber-se através dos arcos de volta inteira.</p>`,
  "498": "<p>Quantos sinos alberga esta torre? 3, 4 ou 5?</p>",
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
