import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "301": "<p>In alto nel corpo centrale che forma il complesso troviamo un grande scudo della città di Valencia.</p>\n<p>La decorazione è completata da un insieme di elementi di parafernalia militare in ogni angolo.</p>",
  "302": "<p>Ricorda che animale corona lo scudo di Valencia? È una capra, un pipistrello, un drago o forse un leone?</p>",
  "303": "<p>Consulti la sua mappa del tesoro che le indica di continuare per la pista attrezzata fino al prossimo punto di interesse di questa Avventura. Ricordi di rispettare il codice della strada!</p>\n<p>La calle Colón, che si apre alla sua sinistra, è una delle strade commerciali per eccellenza e offre ogni tipo di possibilità per gli amanti dello shopping.</p>\n<p>In questa via che traccia oggi il luogo in cui si trovava la cinta muraria della Valencia del XV secolo, numerosi esercizi offrono ogni tipo di servizio e animano la vita dei passanti con vetrine e terrazze.</p>\n<p>Continui, come indica la sua mappa, fino al prossimo punto di interesse.</p>\n<p>Durante il percorso, concentri la sua attenzione sul lato sinistro.</p>",
  "304": "<p>Progettata nel 1901, la <strong>Casa de los Dragones</strong> si trova in una delle strade del primo quartiere di espansione di Valencia.</p>\n<p>Colpisce la peculiare decorazione delle sue facciate: si noti la locomotiva, o l'enorme drago che porta uno scudo, e presti attenzione anche alla cancelleria meticolosamente progettata.</p>",
  "305": "<p>Cosa si può vedere sulla locomotiva? Sarà una stella, uno scudo, o forse una data?</p>",
  "306": "<p>Lasciando questo edificio alla sua sinistra, concentri la sua attenzione sulla piazza successiva.</p>\n<p>La sua avventura la conduce a uno dei punti moderni più iconici di Valencia.</p>",
  "307": "<p>Questo è un punto perfetto per fermarsi a scattare magnifiche fotografie dei tesori architettonici che offre la città e gustare un cocktail particolare come l'Agua de Valencia, o la tradizionale Orxata; una rinfrescante bevanda naturale che calma la sete, accompagnata dagli inseparabili soffici dolci chiamati Fartons.</p>",
  "308": "<p>Anche il <strong>Mercado de Colón</strong> fu costruito in uno degli isolati del primo Ensanche.</p>\n<p>Era destinato a servire questa parte della città, poiché il grande <strong>Mercado Central</strong>, che visiterà più avanti in questa Avventura, si trovava abbastanza lontano.</p>\n<p>Il <strong>Mercado de Colón</strong> fu costruito tra il 1914 e il 1917.</p>\n<p>Sebbene la sua inaugurazione ufficiale abbia avuto luogo la vigilia di Natale del 1916.</p>",
  "309": "<p>Cerchi la sua facciata più monumentale, che si distingue per gli elementi decorativi tradizionali valenciani: prodotti dell'orto, animali da fattoria e prodotti del mare.</p>\n<p>Presti particolare attenzione alla scena del mosaico, conosciuto in valenciano con il nome di Trencadís.</p>\n<p>L'architettura valenciana si caratterizza per una serie di elementi decorativi come la ceramica valenciana, i mosaici chiamati Trencadís e i rilievi.</p>",
  "310": "<p>Quali elementi si possono vedere in questa scena? Un Fallero e una Fallera? Ci sono aranci? O uva?</p>",
  "311": "<p>Al di sotto di questa scena, un altro elemento caratteristico dei mercati decora l'arco a sesto acuto.</p>",
  "312": "<p>Di cosa si tratta? Forse pani? Riesce a vedere anche dei granchi? E mele?</p>",
  "313": "<p>Concentri la sua attenzione sulle colonne, i mensoloni, gli scudi nelle torri... Quanti animali riesce a contare? Tra questi noti che ci sono mucche, maiali...</p>",
  "314": `<p>La sua Avventura continua nell'altra portata di questo monumento. Esattamente sul lato opposto dell'edificio.</p>\n<p>Se si trova in orario di visita, ${LOGO} la invita a premere pausa e ad entrare per scoprire la gastronomia locale che offre questo meraviglioso spazio.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno.</p>`,
  "315": "<p>La facciata del monumento è formata da un grande arco a sesto acuto di 16 metri di altezza. Il timpano dell'arco è rivestito da tegole smaltate.</p>",
  "316": "<p>Nella cupola dell'arco spicca un grande scudo della città realizzato in pietra. Corona lo scudo di Valencia il mitico pipistrello. Riesce a vederlo?</p>",
  "317": "<p>Osservi la sua mappa che la conduce di nuovo al tracciato delle mura.</p>\n<p>Lasciando l'ultima facciata del mercato alla sua mano sinistra, cerchi l'accesso al suo prossimo obiettivo che la riporta all'epoca medievale.</p>",
  "318": "<p>Nella Valencia del XIV secolo, la città distingueva le sue culture nei quartieri murati con una legislazione specifica che ne limitava i diritti e i movimenti.</p>\n<p>Pur essendo una città cattolica, a Valencia convivevano anche musulmani ed ebrei che contribuirono, con le loro culture, a porre le basi della Valencia del XXI secolo.</p>\n<p>Queste \"Rovine\" che può vedere adesso sono concretamente la porta del ghetto ebraico.</p>\n<p>Una delle dodici porte che aveva la cinta muraria cristiana della città di Valencia.</p>\n<p>Le rovine dell'antica muraglia emersero durante i lavori della linea della metro e si decise di lasciare il patrimonio in vista come elemento illustrativo delle opere.</p>",
  "319": "<p>Continui, come indica la sua mappa, per la pista attrezzata fino al prossimo punto con sfide da risolvere.</p>",
  "320": "<p>L'origine di questo tipo di spettacoli era per permettere ai nobili di dimostrare il proprio valore di fronte a un toro. Uno degli animali totemici della cultura ispanica.</p>\n<p>In tempi precedenti alle attuali corride, la tauromachia si svolgeva a cavallo in una piazza di costruzione lignea situata in questo stesso luogo, ma fu demolita dagli stessi valenciani durante la Guerra d'Indipendenza per evitare che i francesi vi si attestassero.</p>",
  "321": "<p>Di fronte al grande successo della tauromachia a piedi, si decise la costruzione di una <strong>Plaza de Toros</strong> con carattere stabile.</p>\n<p>L'attuale <strong>Plaza de Toros</strong> fu avviata nel 1850 e costruita da brigate di detenuti; l'inaugurazione ufficiale avvenne nel 1861.</p>\n<p>All'epoca era la più grande di Spagna con un'arena di 52 metri di diametro, un'altezza di quasi 17 metri e una capacità per circa 17.000 spettatori.</p>\n<p>Nel 1995 il numero di posti viene ridotto a circa 12.800, quelli che ha ancora oggi.</p>",
  "322": "<p>Quanti piani ha questo Monumento dichiarato Storico Artistico Nazionale nel 1983?</p>",
  "323": "<p>Va sottolineato che nel XXI secolo l'attuale <strong>Plaza de Toros</strong> è anche uno spazio multiculturale che offre eventi di ogni tipo.</p>\n<p>Come curiosità, diremo che è possibile sapere se ci sarà o meno una corrida, e persino la categoria della stessa.</p>\n<p>Se le bandiere sventolano sui loro alberi, c'è corrida di tori. Se non ci sono bandiere, la piazza è chiusa.</p>",
  "323-B": "<p>Un edificio del XIX secolo in stile neoclassico, realizzato in mattoni.</p>\n\n<p>Va sottolineato che nel XXI secolo l'attuale Plaza de Toros è anche uno spazio multiculturale che offre eventi di ogni tipo.</p>",
  "324": "<p>Alla destra di questo edificio del XIX secolo in stile neoclassico, realizzato in mattoni, emerge il suo prossimo obiettivo in questa Avventura.</p>",
  "325": "<p>Un edificio monumentale in stile modernista inaugurato nel 1917 e dichiarato Monumento Storico Artistico nel 1961.</p>",
  "326": "<p>Presti attenzione alla facciata della prima torre! Quale agrume naturale di Valencia decora la facciata? Sono limoni, pompelmi o arance?</p>",
  "327": `<p>L'edificio è composto da due spazi affacciati sui binari e un terzo che forma la facciata principale dell'edificio.</p>\n<p>Ammirando il monumento, si possono vedere prodotti agricoli che decorano le sue facciate e una grande aquila sul globo terrestre, simbolo della velocità.</p>\n<p>${LOGO} la invita a premere pausa e a riprendere la sua avventura all'interno dell'edificio, nel quale scoprirà un lussuoso atrio in legno pregiato.</p>`,
  "328": "<p>È già dentro? Presti attenzione: incorniciati nelle lesene si vedono mosaici con la frase \"Buon Viaggio\" in diverse lingue.</p>",
  "329": "<p>Riesce a trovare la sua lingua?</p>",
  "330": `<p>All'interno di quello che un tempo era il bar si possono contemplare mosaici allegorici all'orto valenciano con dettagli come l'<strong>Albufera</strong>, le barrache valenciane, le palme e il famoso <strong>Miguelete</strong>.</p>\n<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo monumento storico al suo ritmo. Può riprendere la sua avventura una volta lo riterrà opportuno.</p>`,
  "331": "<p>Esca dall'edificio, se non le dispiace, e si posizioni con la stazione alle spalle, poi consulti la sua mappa.</p>\n<p>Man mano che segue il tracciato del percorso, può vedere che la conduce alla <strong>Plaza del Ayuntamiento</strong>.</p>\n<p>Dal centro della piazza si possono scorgere diversi punti di grande interesse. Questo è un altro dei punti perfetti per fermarsi e scattare magnifiche fotografie dei tesori architettonici che offre la città.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>27</mark>.</p>\n<p>Per raggiungere il suo obiettivo attraversi il viale e si addentri nella Valencia storica, ricordi di rispettare il codice della strada.</p>\n<p>Ricordi di premere pausa, poi vada o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "332": "<p>Gli edifici che formano l'ambiente insieme all'attuale <strong>Plaza del Ayuntamiento</strong> sono dichiarati Complesso Storico Artistico.</p>\n<p>Alla sua mano destra nella piazza stessa, spicca un edificio in stile Neoclassico. Riesce a vederlo?</p>",
  "333": "<p>Bravissimo, ha quasi completato la sua avventura!</p>",
  "334": "<p>Il monumento sorge sull'antica Casa de Enseñanza, alla quale furono aggiunte diverse dipendenze tra il 1901 e il 1904, subendo inoltre importanti modifiche all'esterno.</p>\n<p>Oggi occupa un isolato di 6.173 metri quadrati e ha facciate su quattro strade.</p>",
  "335": "<p>Si avvicini, se non le dispiace, alla sua facciata principale e si posizioni per poterla vedere nella sua totalità.</p>\n<p>Ricordi di premere pausa, poi vada al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "336": "<p>Nella sua facciata principale spicca un grande balcone in pietra realizzato tra il 1965 e il 1967 che si appoggia su quattro colonne.</p>",
  "337": "<p>Al di sopra di questo balcone, sulla cornice della torre centrale, spicca lo scudo municipale sorretto da due figure femminili nude: una porta una tavolozza da pittore in mano, allegoria alle \"Arti\", e l'altra un libro, figura allegorica alle \"Lettere\".</p>",
  "338": "<p>Ricorda quale animale corona lo scudo municipale? È un drago, un pipistrello o un cavallo? Riesce a vederlo?</p>",
  "339": "<p>Le antiche leggende raccontano che ai tempi in cui Valencia era una città araba, si credeva che se i pipistrelli volavano sulla città, questa sarebbe rimasta per sempre di loro proprietà.</p>\n<p>Nel 1238, anno della Reconquista, fu proprio un pipistrello a cambiare il corso religioso della città. Un corso che perdura fino ai nostri giorni.</p>\n<p>Durante l'assedio all'antica \"Balansiya\", mentre l'esercito del Re Giacomo Primo dormiva, un gruppo nemico si infiltrò nel campo con l'intenzione di uccidere il re.</p>\n<p>La buona sorte volle che un pipistrello che volava nei dintorni collidesse contro un tamburo e svegliasse le truppe con il fragore, impedendo così l'incursione e permettendo la presa della città.</p>\n<p>Dopo quel \"miracolo\" il re rende omaggio all'animale e lo simboleggia in cima allo scudo.</p>\n<p>In verità i pipistrelli sono sempre stati di grande aiuto, come le rondini o i rondoni, per mangiare zanzare e altri insetti volatori, preservando così il benessere dei cittadini.</p>",
  "340": "<p>Rivolga la sua attenzione alla grande porta architravata che consente l'accesso all'edificio.</p>\n<p>Si avvicini, se non le dispiace, alla porta principale.</p>",
  "341": "<p>Una volta dentro, la prima cosa che colpisce è la grande scalinata di marmo che dà accesso al piano superiore.</p>\n<p>Durante la guerra civile, dal 1936 al 1939, questa scalinata fu parzialmente distrutta; in seguito fu ricostruita con il progetto originale del 1924.</p>\n<p>Il <strong>Municipio di Valencia</strong> ospita al suo interno due sale importanti: la sala di cristallo inaugurata nel 1929, una grande sala con illuminazione naturale attraverso vetrate colorate.</p>\n<p>Inoltre, dal 1927, il Museo Storico Municipale con pezzi particolarmente emblematici come la chiave araba che apriva la porta principale della città, la spada e lo scudo del re Giacomo Primo, e il \"Penó de la Conquesta\", la bandiera issata nella torre di Ali Bufat della porta di Bab al-Sakhar il 28 settembre 1238, che segnava la resa della città musulmana di Balansiya ai cristiani del re Giacomo Primo.</p>",
  "342": "<p>Nella parte opposta della piazza appare un tesoro architettonico a mano destra.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>29</mark>.</p>\n<p>Ricordi di premere pausa, poi vada o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "343": "<p>Il <strong>Palacio de Comunicaciones</strong>, conosciuto anche come edificio di Correos, è dal 1922 l'ente incaricato di inviare, ricevere, ordinare, gestire, trasmettere o consegnare la posta, tra le molte altre funzioni.</p>\n<p>Sul tetto svetta una torre di 30 metri di altezza coronata da un globo terrestre.</p>\n<p>Questa torre fu collocata nel 2014 ed è una replica esatta dell'antica torre delle telecomunicazioni che si trovava nello stesso luogo.</p>\n<p>All'interno di questa torre corre una scala a chiocciola che consente di salire al belvedere.</p>\n<p>Al di sotto di questa torre, nel corpo centrale, due gruppi di esseri alati recano messaggi postali e telegrafici: un gruppo sopra una locomotiva e l'altro sopra una nave (allegoria alla protezione dei messaggeri per terra e per mare).</p>",
  "344": "<p>Sull'ingresso principale, in un arco a tutto sesto, figure allegoriche rappresentano i cinque continenti.</p>\n<p>Cosa porta la figura centrale? Una Corona, Una Spada o forse Una Torcia?</p>",
  "345": `<p>Guardando la facciata di Correos, si diriga alla sua mano sinistra, come indica la sua mappa, fino alla Calle de las Barcas, che è la seconda strada alla sua mano destra.</p>\n<p>${LOGO} le raccomanda di raggiungere il prossimo punto di interesse a piedi, ricordi che deve rispettare il codice della strada che, in questo caso, dà precedenza al pedone.</p>\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato, grazie.</p>\n<p>Coraggio, sono solo pochi metri! Ricordi: guardi l'edificio, giri a sinistra e prenda la seconda strada a destra.</p>`,
  "346": `<p>Se viene in orario di visita, ${LOGO} la incoraggia a fare una pausa e scegliere un bel posto.</p>\n<p>È il luogo perfetto per fare una sosta e scattare magnifiche fotografie dei tesori architettonici che offre la città, e gustare una bevanda tipica: Agua de Valencia, un cocktail alcolico a base di vodka, cava e succo fresco d'arancia. O meglio ancora... può anche assaporare un'Orxata, il nostro succo di chufa vegano, sempre accompagnata dai suoi amati Fartons, un dolce a forma di barra da inzuppare, lasciare che assorba il liquido e poi mangiare. Così i valenciani godono di questa rinfrescante bevanda culturale.</p>\n<p>Ricordi che non c'è fretta, faccia quello che le va e non si metta pressione; dovrebbe essere un'escursione divertente! Può tornare alla sua Avventura quando sentirà che è il momento, semplicemente premendo play.</p>`,
  "347": "<p>La Calle de las Barcas prende questo nome perché in questa strada c'era una serie di laboratori dove si fabbricavano queste piccole imbarcazioni che venivano poi trasportate nel quartiere dei pescatori.</p>\n<p>Un tempo si riempì di caffetterie e taverne, dove la prostituzione e il gioco d'azzardo allarmava la popolazione.</p>\n<p>Con l'ampliamento della <strong>Plaza del Ayuntamiento</strong> nel 1891, nella zona si insediarono edifici emblematici come quelli che vedrà in seguito.</p>",
  "348": "<p>Continui fino al termine della strada, dove potrà vedere l'antica sede centrale del <strong>Banco de Valencia</strong>.</p>",
  "349": "<p>Pur avendo un carattere classico con una composizione ad angolo smussato, l'edificio include elementi tipicamente valenciani come la sua ceramica con motivi floreali nell'attico e i suoi slanciati bow-window verso le strade laterali.</p>\n<p>La base dell'edificio, alta due piani, si definisce attraverso la combinazione di marmi di due colori e una serie di colonne classiche che reggono la cancellata e include elementi dorati, offrendo l'immagine di protezione ricercata dalla Banca.</p>\n<p>L'antica sede centrale del <strong>Banco de Valencia</strong> è un tesoro architettonico essenziale in questa avventura.</p>",
  "350": "<p>Quanti piani ha l'edificio?</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
