import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "499": `<p>O seu mapa do tesouro indica-lhe que continue bordeando a igreja para ver a última das suas portas.</p>\n<p>Uma esplêndida recriação neogótica de 1864 despede este ponto e dá passagem ao seguinte.</p>`,
  "500": `<p>Continue até ao final da rua, depois vire à sua esquerda e siga a rua até ver o próximo ponto de interesse à sua direita; aí, emerge a <strong>Fuente del Negrito</strong>.</p>\n<p>No seu mapa corresponde ao número <mark>48</mark>.</p>\n<p>Prima a pausa, depois visualize o ponto indicado, e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "500-B": `<p>Continue até ao final da rua, depois vire à sua esquerda e siga a rua até ver o próximo ponto de interesse à sua direita; aí, emerge a <strong>Fuente del Negrito</strong>.</p>\n<p>No seu mapa corresponde ao número <mark>7</mark>.</p>\n<p>Prima a pausa, depois visualize o ponto indicado, e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "501": "<p>O que sustém a figura com as suas mãos? Um escudo? É uma concha? Talvez uma jarra? Ou talvez uma espada?</p>",
  "502": `<p>Continue, como indica o seu mapa, de volta à <strong>Calle Caballeros</strong>, que corresponde ao número <mark>45</mark> no seu mapa.</p>\n<p>Uma vez na <strong>Calle Caballeros</strong>, tome o caminho que sai à sua esquerda. O seu próximo objetivo abre-se em forma de praça no final da rua.</p>`,
  "502-B": `<p>Continue, como indica o seu mapa, de volta à <strong>Calle Caballeros</strong>, que corresponde ao número <mark>4</mark> no seu mapa.</p>\n<p>Uma vez na <strong>Calle Caballeros</strong>, tome o caminho que sai à sua esquerda. O seu próximo objetivo abre-se em forma de praça no final da rua.</p>`,
  "503": `<p>Já está de volta onde começou?</p>\n<p>Parabéns! Prova superada!</p>\n<p>Esperamos de todo o coração que tenha desfrutado desta aventura tanto como nós desfrutámos ao desenhá-la para si. Como terá podido comprovar, a voz foi gerada com inteligência artificial para dar vida a cada relato e oferecer-lhe uma experiência envolvente. No entanto, a Alma e o guião das audioguias da saga <i>à procura do tesouro</i> são fruto da participação valenciana, refletindo a sua paixão, a sua essência e a sua autenticidade em cada história. Temos o prazer de acrescentar que esta fusão de tradição e tecnologia foi pensada para lhe proporcionar uma experiência dinâmica e próxima que esperamos tenha sido do seu agrado.</p>`,
  "504": `<p>No decorrer da sua Aventura, centre a sua atenção nas aldrabas ou puxadores que ainda podem ver-se nas portas destes antigos palacetes.</p>\n<p>Alguns destes antigos "campainhas" foram colocados a uma altura desproporcional para uma pessoa de estatura média.</p>`,
  "505": `<p>Porque foram colocados tão altos estes puxadores?</p>\n<p>Para as pessoas altas? Poderia ser para chamar estando em cima do cavalo? Ou talvez para não serem incomodados?</p>`,
  "506": "<p>Dirija-se, ao seu próprio ritmo, até ao seu próximo ponto de interesse.</p>",
  "507": `<p>Despedimo-nos, não sem antes recordar-lhes que dispomos de mais procuras do tesouro para continuar a jogar e descobrir Valencia. Ao finalizar a sua aventura, ${LOGO} recomenda-lhe que alivie a capacidade de armazenamento e otimize o desempenho do seu dispositivo eliminando os possíveis ficheiros descarregados. Desta forma, também contribuímos para promover uma gestão responsável dos recursos digitais. Obrigado.</p>`,
  "508": `<p>A <strong>Calle Caballeros</strong>, que acabou de deixar, corresponde ao eixo este - oeste da cidade. Lembra-se?</p>\n<p>Perfeito! Com esta referência às suas costas, a rua perpendicular, por lógica, corresponderia a um eixo norte - sul.</p>\n<p>Abra e observe o seu mapa, siga o traçado que propomos nesta Aventura.</p>`,
  "509": "<p>Que direção toma o caminho estabelecido? É para o norte? Sul? Dirige-se a este? Ou talvez a oeste?</p>",
  "510": `<p>Correto! Norte. Esta via, como poderá ver a seguir, divide-se em duas: Calle Alta e Calle Baja.</p>\n<p>O seu próximo destino transcorre pela famosa Calle Baja, mas antes falemos brevemente da praça onde se encontra.</p>\n<p>Voltamos à época árabe.</p>`,
  "511": `<p>Tossal, que significa ligeira elevação do terreno, formava parte da muralha muçulmana, que fechava a cidade.</p>\n<p>O muro exercia, por sua vez, de ponto de contenção da água de um braço do <strong>Rio Turia</strong> que, antigamente, passava por aqui.</p>\n<p>Hoje em dia, ficam restos expostos dessa muralha numa galeria subterrânea visitável que recebe o mesmo nome que a praça e se situa debaixo dos seus pés.</p>\n<p>Se se encontrar em horário de visita, ${LOGO} aconselha-lhe que prima a pausa e visite este complexo histórico ao seu próprio ritmo.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente.</p>`,
  "512": `<p>Situe-se com a <strong>Calle Caballeros</strong> atrás de si e tome o caminho que sai à sua mão direita.</p>\n<p>Como mencionámos anteriormente, observará que a via se divide.</p>\n<p>Tome a rua da direita e siga até ao seu próximo ponto de interesse que se situa numa dessas ruas estreitas que se abre à sua direita.</p>`,
  "513": `<p>O <strong>Portal de la Valldigna</strong> foi construído sobre a própria muralha árabe.</p>\n<p>Este foi um acesso ao <strong>bairro da mouraria</strong> desde o ano 1400, ano em que a porta foi retirada ficando o portal tal como se conserva hoje em dia.</p>\n<p>O arco de volta inteira, construído em cantaria, foi restaurado em 1965.</p>\n<p>Por cima do arco, pode ver-se uma reprodução do retábulo original que foi colocado neste mesmo ponto no ano 1589.</p>\n<p>O retábulo representa o rei Jaime Segundo de Aragão, chamado o Justo, no ato da fundação do Mosteiro da Valldigna que literalmente significa terras dignas.</p>`,
  "514": `<p>Se faz favor, atravesse o portal e adentre-se no bairro árabe de Valencia.</p>\n<p>Tome a primeira rua à sua esquerda. No final da rua, ainda se pode ver uma torre da muralha árabe, a chamada porta do anjo.</p>`,
  "515": `<p>No séc. XI, depois da queda do Califado de Córdoba, o Antigo Império dividiu-se em pequenas facções chamadas Taifas.</p>\n<p>Valencia, ou Balansiya como era conhecida em tempos muçulmanos, foi a capital de uma dessas Taifas. Em consequência disso, experimentou um importante crescimento urbanístico.</p>\n<p>O incremento da população e os contínuos ataques provenientes do norte de África incentivou a população a ampliar a antiga cidade e o seu perímetro defensivo.</p>\n<p>O desenho da nova muralha transformaria Valencia e estabeleceria um novo perímetro.</p>`,
  "516": `<p>Esta foi construída em betão e foi preenchida com pedras de diversos tamanhos.</p>\n<p>A muralha permitiu aos habitantes de Balansiya resistir o duro cerco por parte de Rodrigo Díaz de Vivar, mais conhecido como El Cid Campeador, no ano 1094, embora não tenha impedido a conquista.</p>\n<p>A cidade foi tomada pelos cristãos, e assim continuou até ao ano 1144, tempo em que Valencia passou, de novo, para mãos muçulmanas.</p>\n<p>Em todo este tempo, uma coisa não mudou; as muralhas com as suas torres continuavam de pé.</p>`,
  "517": `<p>Mesmo depois da reconquista cristã, em 1238 por parte de Jaime primeiro o conquistador, a muralha árabe não foi destruída, mas manteve-se como medida de proteção durante século e meio.</p>\n<p>Este perímetro, do qual ficam restos visíveis hoje em dia, tinha 7 portas principais e torres estrategicamente colocadas a cada 25 metros.</p>\n<p>A torre que pode ver agora mesmo é de planta semicircular e está realizada em alvenaria.</p>`,
  "518": `<p>O que é a alvenaria? É uma mistura de pedras e argamassa; um cimento tradicional composto de cal, areia e água, ao qual também se podia acrescentar barro e palha para aumentar a sua dureza.</p>\n<p>A alvenaria é um método de construção tosco que permite minimizar os desperdícios dos materiais empregues, e muito adequado para construções de grandes alturas.</p>`,
  "519": "<p>Quantas Portas tinha a antiga muralha árabe de Balansiya? Eram 5? Talvez 6? Ou talvez 7?</p>",
  "520": `<p>A nova cidade cristã rodeava a árabe com uma muralha de 4 quilómetros de extensão e isolava os muçulmanos convertidos num ghetto dentro das suas muralhas.</p>\n<p>Os Mudéjares ou como se lhes denominava em Valencia, Sarraïns, eram muçulmanos que em troca de um avultado tributo continuaram a viver fiéis à sua crença.</p>\n<p>Cabe destacar que na cidade de Valencia coexistiram as três religiões abraâmicas; a cristã, a árabe e a judaica.</p>\n<p>Apesar de terem crenças religiosas diferentes, era habitual a política de pactos e os reconhecimentos em prol do avanço da cidade.</p>`,
  "521": `<p>Observe o seu mapa com atenção! O seu objetivo é a conhecida <strong>Calle de los Serranos</strong>, local onde começou a sua aventura. Não pause esta audioguia.</p>\n<p>Situe-se a admirar a torre moura e tome a rua da direita, para imediatamente depois virar à esquerda e depois à direita.</p>\n<p>O caminho parece um pouco tortuoso, sabemo-lo, mas isso tem uma explicação.</p>`,
  "522": `<p>A planta das cidades islâmicas é muito complexa, quase não há distinção entre ruas principais e secundárias.</p>\n<p>A sua forma de criar o traçado urbano é: primeiro as casas e depois as ruas, ao contrário do sistema romano que fazia primeiro as ruas e depois as casas.</p>\n<p>Por isso, o traçado irregular é formado pelas casas que se vão ampliando e invadindo as ruas contíguas modificando o seu traçado, chegando mesmo a cortar ruas e criar becos sem saída.</p>`,
  "523": `<p>Uma vez na <strong>Calle de los Serranos</strong>, dirija-se às torres onde começou a sua Aventura.</p>\n<p>Durante o caminho, observe à sua esquerda e preste atenção pois o edifício é muito discreto e poderia passar despercebido.</p>\n<p>O antigo bunker de Valencia corresponde ao número <mark>52</mark> no seu mapa.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido. Obrigado.</p>`,
  "524": `<p>Este monumento, hoje em dia visitável, seria um dos primeiros refúgios civis a ser construídos durante o período da guerra civil espanhola, que aconteceu desde 1936 a 1939.</p>\n<p>Devido à evolução militar, os refúgios antiaéreos eram essenciais para manter a salvo a população dos ataques e bombardeamentos produzidos pelo inimigo.</p>\n<p>Este, em concreto, foi construído em 1937, ano em que Valencia foi capital da república espanhola.</p>\n<p>O antigo bunker de guerra podia albergar umas 400 pessoas no seu interior.</p>\n<p>Neste espaço que salvaguardou a vida de muitos valencianos, hoje em dia situa-se um museu que nos permite presenciar uma grande recopilação de artefactos da época, assim como o desenvolvimento através de fotografias que refletem como era o dia a dia entre bombardeamentos e miséria.</p>\n<p>Todos estes dados históricos e manuscritos refletem como ficaria Valencia após a perda de milhares de vidas humanas e a destruição de parte dos seus monumentos históricos ao finalizar a Guerra Civil.</p>`,
  "525": `<p>Abra o seu mapa e observará que lhe indica que tome o terceiro caminho que sai à sua Esquerda.</p>\n<p>Apenas uns metros nessa rua surge o seu próximo ponto de interesse nesta procura do tesouro. No seu mapa corresponde ao número <mark>53</mark>.</p>\n<p>${LOGO} recomenda-lhe chegar ao próximo ponto de interesse a pé, lembre-se de que deve respeitar a regulamentação de trânsito que, neste caso, o peão tem preferência. Ânimo, são apenas uns metros!</p>\n<p>Não pause esta audioguia e dirija-se ao ponto indicado, obrigado.</p>\n<p>Lembre-se, continue em direção às torres e tome o terceiro caminho que sai à sua esquerda.</p>`,
  "525-B": `<p>Desde a sua posição, vire-se e deixe as torres às suas costas. Com as torres às suas costas, observe o seu mapa, que lhe indica que tome o caminho que sai à sua direita.</p>\n<p>Apenas uns metros nessa rua surge o seu próximo ponto de interesse nesta procura do tesouro. No seu mapa corresponde ao número <mark>2</mark>.</p>\n<p>${LOGO} recomenda-lhe chegar ao próximo ponto de interesse a pé, lembre-se de que deve respeitar a regulamentação de trânsito que, neste caso, o peão tem preferência.</p>\n<p>Ânimo, são apenas uns metros!</p>\n<p>Não pause esta audioguia e dirija-se ao ponto indicado, obrigado.</p>`,
  "526": `<p>A reciclagem é uma prática essencial e devemos estender a sua relevância ao terreno virtual. Ao adotar esta abordagem inteligente, podemos contribuir para uma gestão sustentável dos ativos na nuvem, abrindo caminho para uma pegada digital mais leve e sustentável. Desde ${LOGO} damos-lhe as graças por ter adquirido esta Aventura, e esperamos vê-lo em breve para mais diversão!</p>`,
  "527": `<p>O Corpus Christi é a festa católica para celebrar a Eucaristia; nela celebra-se o sacramento do pão e do vinho e dedica-se uma recordação especial à morte e à ressurreição de Jesus.</p>\n<p>A sua principal finalidade é proclamar e aumentar a fé dos crentes.</p>\n<p>Para além do puro sentido católico, para a sociedade valenciana o Corpus Christi é uma mostra da coexistência do espírito festivo e religioso.</p>\n<p>A cidade presta culto 60 dias após o Domingo de Ressurreição na chamada Festa Grande.</p>`,
  "528": `<p>As ruas enfeitam-se com corredores florais e diversas comparsas realizam vistosas danças tradicionais e alegóricas ao som da Dolçaina i el Tabalet, instrumentos tradicionais valencianos que fazem parte da banda sonora das nossas audioguias.</p>\n<p>A dança mais famosa é a luta em que a Moma, a nossa atriz principal, se bate contra os sete pecados capitais.</p>\n<p>Reconhece-se pela sua túnica branca e um lenço branco que lhe cobre totalmente o rosto.</p>`,
  "529": `<p>Também são importantes nesta festividade os sete Momos, vestidos com máscara negra, fato amarelo e negro e um gorro característico que representa um dragão.</p>\n<p>Estes realizam uma pitoresca Dança de Bastões enquanto se rendem perante as virtudes da Moma.</p>\n<p>Nalgumas localidades atiram água desde as varandas e convidam os espetadores a participar na celebração.</p>`,
  "530": `<p>O Museu das Rocas abriga as históricas Rocas do Corpus Christi: são os carros triunfais que representam temas bíblicos que, puxados por cavalos, cada ano se destacam na procissão.</p>\n<p>Desde este museu, começa a procissão dos onze carros triunfais datados entre 1528 e 2001.</p>\n<p>As onze estruturas de madeira, em forma de barco antigo, transportam grupos escultóricos alegóricos aos Santos da própria religião.</p>`,
  "531": `<p>No interior do edifício, para além das magníficas estruturas de madeira, também se podem ver os trajes da Moma e dos Momos antes mencionados, e também o dos Gigantes e Cabeçudos que dançam à sua volta na festa.</p>\n<p>Este ponto que adquiriu a categoria de Museu em 2017, recolhe também uma recopilação de fotografias do Corpus desde o séc. XIX.</p>`,
  "532": `<p>A Casa das Rocas foi construída entre 1435 e 1447 por ordem do rei Pedro Quarto, chamado o Cerimonioso.</p>\n<p>Pela sua proximidade ao rio, sofreu numerosas inundações provenientes de cada cheia; o que deu lugar a que a casa se fosse deteriorando constantemente.</p>\n<p>Felizmente, solucionou-se após o desvio do rio que deu lugar ao bonito parque que continuaremos a observar nesta Aventura.</p>\n<p>Esta antiga casa de dois pisos era, além disso, a residência do Capelão das Rocas, que se encarregava da sua custódia.</p>\n<p>Entra-se na casa por uma porta alta com verga reta, em cuja parte superior encontramos um frontão triangular. No interior encontramos um pátio interior coberto por uma cobertura de vigas de madeira.</p>\n<p>Após a sua restauração em 1980, acrescentou-se no piso superior uma grande varanda que dá para o pátio interior.</p>\n<p>Anos depois, após a merecedíssima reforma museográfica, incluíram-se painéis explicativos, ecrãs audiovisuais e a divisão e denominação das diferentes salas.</p>`,
  "533": `<p>Observe que o seu mapa lhe indica continuar pela rua; durante o trajeto pode observar que as varandas do primeiro piso são notavelmente mais estreitas do que as dos restantes pisos superiores. Porque será? Além disso, algumas delas ainda estão decoradas com cerâmica tradicional valenciana.</p>\n<p>O seu próximo ponto de interesse é a portada de uma igreja barroca que fica à sua direita na própria rua.</p>`,
  "534": `<p>A Igreja de Nossa Senhora do Carmo, a <strong>Paróquia da Santíssima Cruz</strong>, conhecida popularmente como a "Igreja do Carmo", foi declarada Monumento Histórico Artístico Nacional em 1983.</p>\n<p>Mas esta igreja tem um passado muito mais antigo.</p>`,
  "535": `<p>A Igreja do Carmo teve os seus começos no ano 1280. Naqueles tempos situava-se neste espaço uma modesta casa com horta que regiam a Ordem dos Carmelitas. Este seria a origem do futuro Convento do Carmo.</p>\n<p>Após uma primeira ampliação, a primeira igreja foi consagrada em 1343 e desde então sofreu reformas graduais.</p>\n<p>Um claustro gótico de arcos apontados, o grande refeitório ou sala de refeições dos frades e a sala capitular são claros exemplos que permanecem do seu passado medieval.</p>\n<p>Em 1555, reformou-se a cabeceira, ou zona do altar, empregando o sistema construtivo tradicional de abóbada de cruzaria estrelada.</p>\n<p>Mais tarde, ergueu-se um segundo claustro renascentista, mas os elementos mais visíveis correspondem já à época barroca.</p>\n<p>Em 1613 começaram as obras da fachada-retábulo do templo e em 1628 levou-se a cabo uma nova reforma que durou quase 30 anos na qual se renovou o interior ao gosto barroco da época (1655).</p>\n<p>Centre a sua atenção na fachada principal.</p>\n<p>Esta extravagante fachada está considerada um dos melhores retábulos maneiristas da cidade.</p>`,
  "536": `<p>O Maneirismo é um estilo artístico empregado no final do séc. XVI que se focava na alteração da ordem nos elementos arquitetónicos e tende à irrealidade.</p>\n<p>O retábulo da fachada que tem diante de si foi realizado em duas fases.</p>\n<p>A primeira, de corte clássico, corresponde ao corpo inferior e foi realizada durante a primeira metade do séc. XVII.</p>\n<p>Observe as colunas jónicas estriadas que se elevam sobre os sócalos de pedra em ambos os lados da porta.</p>`,
  "537": `<p>A porta, por sua vez, tem um nicho em cada lado onde se resguardam as esculturas representativas de São Simão Stock, um eremita e frade Carmelita Inglês; e de São João da Cruz, Padroeiro dos poetas em língua espanhola e um dos 36 Doutores da Igreja.</p>`,
  "538": `<p>Por cima do lintel da porta ressalta o escudo da Ordem do Carmo.</p>\n<p>O que coroa o escudo? Uma coroa? Uma cruz? Ou talvez uma estrela?</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
