import { readFileSync, writeFileSync } from 'fs';
const FILE = 'js/parrafos-textos/parrafos-texto-frances.json';
const existing = JSON.parse(readFileSync(FILE, 'utf8'));
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const batch = {
  "51": "<p>Placez-vous au centre de la place indiquée par le numéro <mark>42</mark> sur votre carte ; de là, vous pouvez voir une partie de la coupole de la Basilique, d'environ 19 mètres de largeur et à plan ovale.</p>",
  "51-B": "<p>Votre aventure se poursuit en ce même endroit, correspondant au numéro <mark>42</mark> sur votre carte.</p>",
  "51-C": "<p>Placez-vous au centre de la place indiquée par le numéro <mark>4</mark> sur votre carte ; de là, vous pouvez voir une partie de la coupole de la Basilique, d'environ 19 mètres de largeur et à plan ovale.</p>",
  "51-D": "<p>Il correspond au numéro <mark>42</mark> sur votre carte.</p>",
  "52": "<p>Continuez à marcher dans la rue et, si vous n'avez pas encore cédé à la tentation, remarquez l'immeuble important qui se dresse sur votre gauche, indiqué sur votre carte sous le numéro <mark>2</mark>.</p>\n<p>Ce bâtiment s'appelle <strong>Les Corts Valencianes</strong>.</p>\n<p>Un édifice de style gothique tardif aujourd'hui destiné aux activités gouvernementales, qui fut jadis la résidence des Borgia lors de leur séjour à Valence.</p>",
  "53": "<p>Êtes-vous sur la <strong>Plaza del Tossal</strong> ? Oui ? Parfait ! Sur votre carte, elle correspond au numéro <mark>49</mark>.</p>",
  "54": `<p>Si vous êtes là pendant les heures d'ouverture, ${LOGO} vous recommande de mettre en pause, d'entrer dans cet ESPACE et de profiter de ses expositions. Vous pouvez reprendre votre aventure quand vous le souhaitez.</p>`,
  "54-B": `<p>Si vous êtes là pendant les heures d'ouverture, ${LOGO} vous recommande de mettre en pause et d'entrer dans cet espace pour profiter de ses expositions. Vous pouvez reprendre votre aventure quand vous le souhaitez.</p>`,
  "55": `<p>${LOGO} vous invite à mettre en pause cette audioguide et vous recommande de vous promener dans ce jardin à votre propre rythme.</p>`,
  "56": `<p>Si vous êtes là pendant les heures d'ouverture, ${LOGO} vous invite à mettre en pause cette audioguide et vous recommande de vous promener dans ce jardin à votre propre rythme.</p>`,
  "57": "<p>Utilisez le bouton pause à votre convenance. Quand vous sentez que le moment est venu, continuez simplement à résoudre nos défis tout en découvrant la ville.</p>",
  "58": "<p>Utilisez les boutons pause et continuer comme vous le souhaitez pour arrêter et reprendre votre aventure <i>en quête du trésor</i>, où et quand vous voulez. Vous pouvez reprendre votre Aventure quand vous le jugez opportun, en appuyant simplement sur le bouton continuer.</p>",
  "59": "<p>Il correspond au numéro <mark>43</mark> sur votre carte.</p>",
  "60": "<p>En admirant le portail gothique de la Cathédrale, votre prochain objectif se dresse à l'opposé de la place.</p>\n<p>Retournez-vous et vous verrez face à vous un palais construit en pierre de taille qui se distingue du reste du paysage urbain.</p>\n<p>Ne mettez pas l'audioguide en pause et dirigez-vous, comme l'indique votre carte, vers votre prochain point d'intérêt.</p>\n<p>Sur votre carte, il correspond au numéro <mark>44</mark>.</p>",
  "61": `<p>${LOGO} vous recommande de faire une courte pause et de regarder autour de vous.</p>`,
  "62": `<p>${LOGO} vous recommande de faire une courte pause et de regarder autour de vous.</p>`,
  "63": "<p>Il correspond au numéro <mark>47</mark> sur votre carte.</p>",
  "64": `<p>Si vous êtes là pendant les heures d'ouverture, ${LOGO} vous conseille de mettre en pause et de visiter ce centre culturel à votre propre rythme.</p>`,
  "64-B": `<p>Si vous êtes là pendant les heures d'ouverture, ${LOGO} vous conseille de mettre en pause et de visiter ce centre culturel à votre propre rythme.</p>`,
  "65": "<p>Il correspond au numéro <mark>49</mark> sur votre carte.</p>",
  "66": "<p>Il correspond au numéro <mark>50</mark> sur votre carte.</p>",
  "67": "<p>Il correspond au numéro <mark>51</mark> sur votre carte.</p>",
  "68": "<p>Sauriez-vous me dire le nom de la rue ?</p>\n<p>N'oubliez pas de mettre en pause, puis visualisez le point indiqué et résolvez votre défi ; appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "69": "<p>Le prochain objectif de votre Aventure correspond au numéro <mark>53</mark> sur votre carte.</p>",
  "70": `<p>${LOGO} vous fournira des informations détaillées sur cette fête au cours de cette Aventure.</p>`,
  "71": "<p>Il correspond au numéro <mark>54</mark> sur votre carte.</p>",
  "72": "<p>Il correspond au numéro <mark>55</mark> sur votre carte.</p>",
  "73": "<p>Il correspond au numéro <mark>56</mark> sur votre carte.</p>",
  "74": "<p>Votre prochain point d'intérêt dans cette Aventure correspond au numéro <mark>57</mark> sur votre carte.</p>",
  "75": `<p>${LOGO} vous recommande de continuer à pied à partir de ce point.</p>\n<p>Observez votre carte qui vous invite à suivre le tracé des murailles.</p>\n<p>Placez-vous avec l'entrée principale de l'IVAM en face de vous et tournez à droite. Un groupe de trois points consécutifs, sur votre gauche, vous attend à seulement deux rues de distance.</p>\n<p>Sur votre carte, ils correspondent aux numéros <mark>58</mark>, <mark>59</mark> et <mark>60</mark>.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>`,
  "76": "<p>Revenez sur le tracé original des murailles et dirigez-vous à gauche. Quelques mètres plus loin se dressent les célèbres <strong>Torres de Quart</strong>, indiquées sur votre carte sous le numéro <mark>61</mark>.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "76-B": "<p>Votre Aventure vous ramène vers les célèbres <strong>Torres de Quart</strong>. Sur votre carte, elles correspondent au numéro <mark>61</mark>.</p>\n<p>Pour ce faire, prenez le même sentier conçu pour les véhicules de mobilité personnelle et revenez en suivant le tracé de la muraille jusqu'à la porte d'accès à l'ancienne ville.</p>\n<p>Mettez en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "77": "<p>En tournant le dos aux <strong>Torres de Quart</strong>, traversez l'avenue et prenez la voie aménagée sur votre gauche, jusqu'au prochain point d'intérêt de cette Aventure. Après plusieurs rues, vous verrez sur votre gauche une zone verdoyante, indiquée sur votre carte sous le numéro <mark>62</mark>. N'oubliez pas de respecter le code de la route ! Cette voie réservée aux véhicules de mobilité personnelle longe le tracé de l'ancienne muraille de Valence.</p>\n<p>Mettez en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "78": "<p>Il correspond au numéro <mark>63</mark> sur votre carte.</p>",
  "79": "<p>Il correspond au numéro <mark>69</mark> sur votre carte.</p>",
  "80": "<p>Dirigez-vous vers votre prochain point d'intérêt, correspondant au numéro <mark>70</mark> sur votre carte. N'oubliez pas de mettre en pause, puis rendez-vous au point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "81": "<p>Avec l'entrée de Valence en face de vous, dirigez-vous sur votre gauche jusqu'au pont suivant : le <strong>Pont de Madera</strong>.</p>\n<p>Consultez votre carte pour plus d'informations.</p>\n<p>Lorsque la signalisation le permet, traversez à nouveau la route.</p>\n<p>Cette aventure vous mènera dans une charmante rue pleine de vie, où glaces, douceurs, horchatas, agua de Valencia et une large offre gastronomique vous tenteront tout au long du parcours.</p>",
  "81-B": "<p>Il correspond au numéro <mark>71</mark> sur votre carte.</p>",
  "82": "<p>Concentrez votre attention sur l'ensemble du <strong>Bioparc</strong>. Numéro <mark>73</mark> sur votre carte.</p>",
  "83": "<p>Depuis votre position, avec la <strong>Plaza de la Virgen</strong> devant vous, prenez le chemin à gauche et dans une ruelle étroite sur votre droite, vous trouverez un passage sûr vers la zone suivante.</p>\n<p>Cette voie mène à la <strong>Plaza de la Almoina</strong>, indiquée sur votre carte sous le numéro <mark>4</mark>. La rue que nous mentionnons se trouve juste entre la <strong>Basilique de la Mare de Déu</strong> et « un Musée », correspondant aux numéros <mark>6</mark> et <mark>7</mark> respectivement sur votre carte.</p>\n<p>En vous plaçant au centre de la place, vous pouvez observer comment trois époques glorieuses de la ville de Valence coexistent.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place. Merci.</p>",
  "84": "<p>Au-dessus des baies latérales, on trouve quatre bas-reliefs, œuvres dédiées « À la Valeur », « Au Dévouement » et, celles que nous pouvons voir maintenant, depuis le parc où nous nous trouvons, « À la Paix » et « À la Gloire ».</p>",
  "85": "<p>En suivant la carte vers la façade est de la Cathédrale, dirigez-vous vers le Palais de style éclectique en briques rouges situé au fond de la place.</p>\n<p>Votre objectif est le <strong>Palais Archiépiscopal</strong> ou numéro <mark>8</mark> sur votre carte.</p>\n<p>N'oubliez pas de mettre en pause, puis rendez-vous ou visualisez le point indiqué et appuyez à nouveau sur le bouton continuer une fois sur place.</p>",
  "86": "<p>Dirigez-vous vers la porte de style roman de la Cathédrale et regardez vers le haut sur votre gauche.</p>\n<p>Une tour octogonale de la fin du XVe siècle se dresse derrière la cathédrale.</p>",
  "87": "<p>Attention au prochain tronçon d'obstacles urbains !</p>\n<p>Respectez le code de la route et attendez que les feux passent au vert pour traverser les rues.</p>",
  "88": `<p>En admirant ces bâtiments, la rue qui se trouve à votre gauche trace aujourd'hui l'emplacement de la muraille de Valence du XIXe siècle. La <strong>rue Colón</strong> est l'une des artères commerciales par excellence ; on y trouve de nombreux commerces proposant toutes sortes de services et animant la vie des passants avec leurs vitrines et leurs terrasses.</p>\n<p>${LOGO} vous fournira des informations détaillées sur cette zone dans votre Aventure numéro 5.</p>`,
  "89": "<p>Pour continuer cette chasse au trésor, traversez à nouveau la rue Colón.</p>\n<p>En suivant l'itinéraire indiqué sur la carte, une voie piétonne pleine de loisirs vous mènera directement au prochain point d'intérêt de cette aventure.</p>",
  "90": "<p>Il correspond au numéro <mark>74</mark> sur votre carte.</p>",
  "91": "<p>Il correspond au numéro <mark>75</mark> sur votre carte.</p>",
  "92": "<p>Sur votre carte, il est indiqué sous le numéro <mark>76</mark>.</p>",
  "93": "<p>Sur votre carte, il est indiqué sous le numéro <mark>77</mark>.</p>",
  "94": "<p>Il correspond au numéro <mark>78</mark> sur votre carte.</p>",
  "95": "<p>Il correspond au numéro <mark>80</mark> sur votre carte. Mettez en pause et approchez-vous du <strong>Palais de Justice</strong> pour le contempler dans son intégralité.</p>",
  "96": "<p>Cet espace correspond au numéro <mark>81</mark> sur votre carte.</p>",
  "97": "<p>Il correspond au numéro <mark>82</mark> sur votre carte.</p>",
  "98": "<p>Il correspond au numéro <mark>84</mark> sur votre carte.</p>",
  "99": "<p>Sauriez-vous me dire quel commerce abrite ce bâtiment ?</p>",
  "100": "<p>Félicitations, vous venez d'atteindre la moitié du parcours, reposez-vous ou continuez pour l'autre moitié !</p>",
  "100-B": "<p>Félicitations, vous venez d'atteindre la moitié du parcours, reposez-vous ou continuez pour l'autre moitié !</p>"
};
const merged = { ...existing, ...batch };
writeFileSync(FILE, JSON.stringify(merged, null, 2), 'utf8');
console.log('Total entradas:', Object.keys(merged).length);
