import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "419": `<p>Situe-se, se faz favor, num ponto no qual possa ver a torre na sua totalidade e desfrute do seu tempo para tirar umas fotos deste magnífico monumento; ao mesmo tempo permita-se conhecê-lo com mais profundidade.</p>\n<p>Prima a pausa, depois visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "420": `<p>Santa Catalina Mártir é uma torre visitável considerada como uma das torres barrocas mais originais da arquitetura espanhola.</p>\n<p>A primeira pedra deste campanário foi colocada em 1688 e foi finalmente terminada em 1705 no seu atual estilo barroco.</p>\n<p>Como pode apreciar-se, a torre é de planta hexagonal.</p>\n<p>Eleva-se em quatro pisos, aos quais há que somar o corpo dos sinos e um templete: que é a construção superior constituída por colunas e um teto, semelhante a um templo.</p>\n<p>Em cada um dos seus pisos abrem-se umas janelas ricamente decoradas em estilo Barroco que permitem a passagem da luz para a escada.</p>\n<p>No corpo dos sinos observa-se a sua maior riqueza decorativa. Admire as colunas salomónicas encintadas em cada uma das suas arestas.</p>\n<p>As colunas recebem este nome pela crença da época, segundo a qual assim foram as colunas do Templo de Salomão.</p>\n<p>Completam o corpo dos sinos os arcos de volta inteira que se abrem em cada uma das faces da torre.</p>\n<p>Como aporte, sobre os 6 sinos que se ubicavam no campanário desde 1729, diremos que eram conhecidos como "as luteranas", porque procediam de Londres, um país não católico.</p>\n<p>Lamentavelmente, esses sinos tiveram finais diversos.</p>`,
  "421": `<p>Remata a torre um templete de dois pisos sustido por um conjunto de volutas, assim chamadas pela sua forma de caracol ou espiral que sustentam o corpo central.</p>\n<p>Aqui repetem-se de novo as colunas salomónicas encintadas. Pode vê-las?</p>\n<p>O templete cobre-se com uma cúpula com telhas de pedra em forma de escamas de peixe.</p>\n<p>Sobre a cúpula, distinguem-se uma bola que representa o globo terrestre e um catavento que permitem a Santa Catalina superar os 56 metros de altura.</p>`,
  "422": "<p>De que cor são as telhas da cúpula?</p>",
  "423": "<p>O que há no ponto mais alto da torre? Pode ser uma cruz? Talvez o sol? Talvez há uma pomba?</p>",
  "424": `<p>Não pause esta audioguia. O seu mapa do tesouro indica-lhe que atravesse a praça e procure o acesso que fica na sua parte oposta.</p>\n<p>A partir do ano 2012, esta praça e a contígua, que fica à sua mão esquerda, passariam de ser uma sucessão de ruínas a duas pracelinhas reabilitadas que acolhem dois espaços para a realização de mercados.</p>\n<p>Em <strong>Tapinería</strong>, como se conhece o conjunto de praças, impera a filosofia do efémero; pelo que o género e o estilo muda a cada 15 dias.</p>`,
  "425": `<p>Conta a tradição que a torre de Santa Catalina é a noiva do <strong>Miguelete</strong>: "Dois amantes que se olham eternamente, mas a timidez não lhes permite aproximar-se".</p>`,
  "426": `<p>O <strong>Miguelete</strong> é um monumento visitável, de estilo gótico valenciano que toma o seu nome do seu sino principal, o qual desde 1539 até hoje em dia continua a tocar as horas.</p>\n<p>Aproxime-se ao monumento, tal como o indica o seu mapa.</p>`,
  "426-B": `<p>O nosso famoso <strong>Miguelete</strong>, de estilo gótico valenciano, toma o seu nome do seu sino principal, o qual desde 1539 até hoje em dia continua a tocar as horas.</p>\n<p>O icónico <strong>Miguelete</strong> cumpre a função de campanário e miradouro por ser o edifício mais alto da cidade histórica.</p>\n<p>Após subir os seus 207 degraus, o <strong>Miguelete</strong> oferece umas vistas aéreas de 360 graus de toda a cidade.</p>\n<p>A panorâmica que oferece a 51 metros de altura permite ver toda a cidade com o seu jardim até à praia, passando pela <strong>ciudad de las artes y de las ciencias</strong> e pela bela horta valenciana.</p>`,
  "427": `<p>O icónico <strong>Miguelete</strong> compõe-se de quatro corpos de igual altura.</p>\n<p>Este importante ponto da sua Aventura cumpre a função de campanário e de miradouro por ser o edifício mais alto da cidade histórica.</p>\n<p>Saberia determinar que geometria tem? Hexagonal, Octogonal ou Quadrangular?</p>`,
  "428": `<p>Na sua origem, a <strong>Torre do Miguelete</strong> foi desenhada para se erguer separada da Catedral, mas uma reforma no séc. XV fez com que ficasse unida à torre.</p>\n<p>Quantas janelas pode ver?</p>`,
  "429": "<p>Centre a sua atenção ligeiramente à sua direita.</p>",
  "429-B": "<p>Centre a sua atenção ligeiramente à sua esquerda.</p>",
  "430": `<p>Posteriormente à construção do <strong>Miguelete</strong>, incorporou-se-lhe a porta barroca da catedral. Hoje em dia é a sua porta principal.</p>\n<p>Comummente conhecida como a "<strong>Puerta de los Hierros</strong>", une o templo com a <strong>Torre do Miguelete</strong> e cinge o espaço com a grade metálica que dá o nome à portada.</p>\n<p>Este grandioso desenho foi projetado para cobrir a necessidade de produzir a ilusão ótica, dando assim maior sensação de espaço a um lugar relativamente pequeno, mudando as tradicionais linhas retas pela de uma curvatura côncava-convexa.</p>\n<p>Na portada destacam as colunas e o rosáceo oval que ilumina a Catedral e por cima deste, um alto-relevo que representa a ascensão da virgem.</p>\n<p>Coroa o ático da portada um baixo-relevo com o símbolo do Espírito Santo.</p>\n<p>Esta portada finalizada em 1741 é o ponto de acesso mais moderno da Catedral.</p>\n<p>Cabe destacar que foi construída graças à doação que uma cidadã deixou no seu testamento.</p>`,
  "431": "<p>O que se pode ver a mais de 35 metros de altura no alto da portada barroca? É uma esfera? É uma cruz? Talvez um morcego? Ou um cavalo?</p>",
  "432": `<p>No nosso século, a <strong>Puerta de los Hierros</strong> divide-se em dois: o lado esquerdo que facilita o acesso aos fiéis e também acede à subida ao <strong>Miguelete</strong>.</p>\n<p>Desde aqui, vislumbra-se também o Altar-Mor, um retábulo renascentista adornado com uma resplandecente decoração gótica.</p>\n<p>O lado direito oferece a parte museológica da Catedral. Desde aqui acede-se também às numerosas capelas, entre elas a de San Vicente Mártir, na qual se expõe o braço incorrupto do Santo.</p>\n<p>Se se encontrar em horário de visita, ${LOGO} recomenda-lhe que prima a pausa e visite este monumento ao seu próprio ritmo.</p>\n<p>Após subir os seus 207 degraus, o <strong>Miguelete</strong> oferece umas vistas aéreas de 360° de toda a cidade.</p>\n<p>A panorâmica que o <strong>Miguelete</strong> oferece a 51 metros de altura permite ver toda a cidade desde o seu extenso jardim até à <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Este é um ponto perfeito para tirar fotos panorâmicas da cidade.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente, simplesmente prima o botão correspondente e continue <i>à procura do tesouro</i>.</p>\n<p>A sua aventura continua neste mesmo ponto.</p>`,
  "433": `<p>Deixe a <strong>Plaza de la Virgen</strong> à sua esquerda, continue até ao final da rua e de seguida vire à direita.</p>\n<p>Encontrar-se-á na <strong>Calle de los Serranos</strong> que separa e delimita à mão direita os bairros de "La Seu" ou <strong>bairro da Catedral</strong>, e à mão esquerda o bairro de "El Carmen".</p>`,
  "434": `<p>A construção da Catedral demorou 500 anos a ser finalizada e durante esse extenso período de tempo, os estilos arquitetónicos mudaram; por isso na <strong>Catedral de Valencia</strong> fundem-se vários estilos arquitetónicos.</p>\n<p>A sua face norte é a sua fachada mais antiga.</p>`,
  "435": `<p>Estes estilos podem ver-se com total clareza nas suas três portas: a Barroca, a principal, que é a que tem em frente a si.</p>\n<p>Na face oeste situa-se o portal gótico que verá no decorrer desta Aventura e o lado este com a sua entrada de arte românico que será o seu próximo objetivo.</p>`,
  "436": `<p>Especialmente o conhecido como "La Nit del Foc" (Noite do Fogo) que se dispara na noite de 18 para 19 de março, no qual se congregam mais de um milhão de pessoas para presenciá-lo uma vez que se distingue do resto por ser o mais longo e espetacular de todos.</p>`,
  "437": `<p>Aproxime-se um pouco mais à porta da Catedral.</p>\n<p>A porta de estilo românico da catedral, também conhecida como a porta do Palau, é uma portada românica num templo de características góticas.</p>\n<p>Na sua base foram talhadas 12 representações em cada lado, com passagens históricas da Bíblia, do Génesis e do Êxodo.</p>\n<p>Apelidada a porta seca, esta compõe-se de seis arcos de volta inteira com motivos geométricos; nela podem ver-se figuras de serafins, anjos, arquinhos e delicadas folhagens sumamente elaboradas.</p>\n<p>Por cima da arcada encontram-se as cabeças de sete casais que segundo a tradição representam sete matrimónios naturais de Lleida que chegaram trazendo com eles trezentas donzelas que deviam casar-se com os novos colonos e desta forma repovoar Valencia após a guerra.</p>`,
  "438": "<p>Quantos Arcos compõem a porta?</p>",
  "439": `<p>Na parte direita da porta, à altura dos joelhos, encontramos umas marcas longitudinais como arranhões.</p>\n<p>Nesta praça onde se encontra agora mesmo, situava-se a plataforma sobre a qual o carrasco executava os prisioneiros.</p>\n<p>Antigos relatos contam que essas são as marcas produzidas pelo carrasco ao afiar o machado sempre no mesmo ponto, uma vez que, a escassos metros da porta se encontrava o funesto local de execução, acontecimento que era, claro, público! E ao qual se permitia ao povo acorrer e ver como se impartia justiça.</p>`,
  "440": "<p>Não pause esta audioguia e continue o traçado da parede do templo.</p>",
  "441": `<p>Reparou que o muro da Catedral é arredondado? A <strong>Catedral de Valencia</strong> ergue-se sobre a antiga Sé Visigótica que séculos mais tarde se converteu em Mesquita Maior.</p>\n<p>No séc. XIII, após a reconquista, a construção da Catedral foi acontecendo à medida que se aproveitava a Mesquita árabe, razão pela qual o templo adquire uma forma arredondada, em vez da tradicional planta de cruz.</p>\n<p>Entre 1229 e 1245 a Coroa de Aragão conquistou o território que posteriormente seria conhecido como Reino de Valencia.</p>\n<p>Graças às tropas do rei Dom Jaime primeiro, Valencia é reconquistada em 1238.</p>\n<p>Em sua honra, anos depois, um antigo quadro de cerâmica tradicional valenciana ficou exposto no muro da catedral.</p>\n<p>Representa a celebração da missa que se celebrou após a reconquista.</p>`,
  "442": `<p>Que figura esculpida se pode ver no enquadramento do quadro?</p>\n<p>Um dragão, um morcego ou talvez uma coroa? Adivinha!</p>`,
  "443": "<p>Mesmo um passo à direita, abre-se uma pequena capela protegida por grades. Este é o local onde se realizou a primeira missa na Valencia conquistada pelo Rei Jaime primeiro.</p>",
  "444": `<p>O que se pode ver dentro?</p>\n<p>Um altar, uma bandeira, há também uma espada?</p>`,
  "445": "<p>Sobre esta há uma placa comemorativa. Em que ano foi exposta essa placa?</p>",
  "446": "<p>Uns passos mais adiante, à mão direita, outra capela fechada com grades alberga a estátua de São Vicente Ferrer, Padroeiro de Valencia.</p>",
  "447": "<p>No edifício que fica em frente à Catedral, ergue-se uma imponente porta negra de bronze em alto-relevo com umas pequenas janelas gradeadas através das quais pode contemplar o interior da <strong>Basílica de Valencia</strong>.</p>",
  "448": "<p>A 19 de março, dia do pai em Espanha e dedicado a São José, as Fallas finalizam com a Nit de la Cremà (a noite da queima).</p>",
  "449": `<p>Noite na qual, a partir das 22 horas que se queimam os monumentos infantis até à 1 da manhã que se queima o monumento da <strong>Plaza del Ayuntamiento</strong>, é tradição percorrer Valencia despedindo as Fallas, vendo arder o trabalho de um ano inteiro.</p>\n<p>Continue até às torres.</p>`,
  "450": `<p>Em 1652, começaram as obras da basílica e duraram um total de 14 anos.</p>\n<p>Entre 1652 e 1660 realizaram-se as fachadas exteriores.</p>\n<p>Em 1659 acordou-se a construção de uma passagem elevada que comunicasse a Basílica com a Catedral, é conhecida como "arco novo" e no início de 1661 começou-se a construção da cúpula de planta oval com os seus quase 19 metros de largura.</p>\n<p>Em 1666 finalizam-se as obras da Basílica e nesse mesmo ano dispõe-se a transferência da Virgem desde a Catedral.</p>`,
  "451": `<p>A <strong>Basílica de Valencia</strong> acolhe, no seu interior, a imagem da nossa Padroeira, a Mãe de todos os valencianos: a <strong>Virgem dos Desamparados</strong>, conhecida carinhosamente em Valencia como a Xeperudeta que significa corcundinha no idioma Valenciano.</p>\n<p>A Virgem toma este nome devido à sua ligeira inclinação para a frente, o que é interpretado como sinal de desgaste físico pelo esforço e constância do apoio e ajuda das milhares de preces recebidas pelos valencianos.</p>\n<p>As preces começaram em consequência da epidemia de peste que em 1647 causou cerca de 18.000 vítimas. A devoção, cada vez mais fervorosa do povo valenciano pela Virgem, criou a necessidade de edificar um espaço adequado para que a sua imagem pudesse estar exposta ao povo em condições adequadas a tal devoção.</p>`,
  "452": `<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e visite este monumento histórico ao seu próprio ritmo.</p>\n<p>Poderá admirar os Frescos do famoso pintor Palomino, que se expõem nesta Basílica desde 1701.</p>\n<p>Também pode dedicar-lhe umas palavras à virgem. Reza a tradição de pedir um desejo que não seja para si mesmo.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente, simplesmente prima o botão correspondente e continue <i>à procura do tesouro</i>.</p>`,
  "453": `<p>Bravo! Já quase terminou a sua aventura!!</p>\n<p>Veja o mapa com cautela, a disposição da calçada obriga-o a seguir uma via única para depois virar à mão direita, e assim obter uma magnífica vista da <strong>Catedral de Valencia</strong>.</p>\n<p>A caminho da Porta Românica, à sua esquerda situa-se o <strong>Palacio Arzobispal</strong>.</p>`,
  "454": "<p>Na parte oposta à Basílica, a ornamentação de uma casa senhorial revela que pode ser importante nesta procura do tesouro.</p>",
  "455": `<p>Valencia é a cidade espanhola com maior volume de obras modernistas devido ao importante crescimento da cidade no final do séc. XIX, que supôs a construção do alargamento e a destruição das muralhas medievais em 1865.</p>\n<p>O aparecimento do Modernismo foi um movimento de rutura com os estilos que tinham chegado até esse momento com a intenção de encontrar um mais moderno, juvenil e funcional baseado no uso de novos materiais como o ferro, o vidro e os azulejos derivados da evolução industrial.</p>\n<p>Caracterizou-se por uma certa exaltação da horta, as falleras, as laranjas e os pescadores, entre outros.</p>\n<p>Isto demonstra-se nas obras repletas de mosaicos de cores, esculturas e decorações florais.</p>\n<p>Este movimento foi impulsado por uma nova classe: a burguesia, que queria reivindicar-se através da arte.</p>\n<p>Fugiam da tradição, das construções robustas, buscavam o movimento... e o detalhe fundamental era a ornamentação e a natureza.</p>\n<p>Em Valencia, além disso, desenvolveu-se uma corrente com características próprias, conhecida como Modernismo Valenciano.</p>`,
  "455-B": "<p>A fachada modernista do edifício tem gravados com motivos florais e pilastras que imitam troncos. Podem apreciar-se diferentes varandas: umas de pedra e outras de ferro forjado.</p>",
  "455-C": `<p>Na parte inferior encontra-se a Capela de San Valero, aqui situava-se a prisão onde esteve preso o bispo Valero antes de ser desterrado no séc. IV depois de Cristo.</p>\n<p>Construída inicialmente em 1719 e reconstruída completamente em 1907, abre-se ao exterior através de uma porta com verga reta de estilo barroco com pilastras toscanas.</p>\n<p>No lintel da porta pode ver-se um óculo, um pouco acima da imagem do bispo.</p>`,
  "455-D": `<p>Olhando a imagem de São Valero, que artefacto nos poderia dizer que esteve preso?</p>\n<p>As correntes, o livro ou talvez o seu rosto triste?</p>`,
  "456": `<p>Em que ano foi edificada esta casa?</p>\n<p>Pista! Olhe na parte superior da fachada.</p>`,
  "457": `<p>Uma elevação artificial, à mão esquerda desta casa, convida a continuar <i>à procura do tesouro</i>.</p>\n<p>Vamos a cima!</p>\n<p>Este é um ponto perfeito para tirar fotos panorâmicas destes monumentos declarados de interesse histórico artístico.</p>`,
  "458": `<p>Nas imediações abriu-se um portal do tempo!</p>\n<p>O que se pode ver através?</p>\n<p>Uma <strong>Plaza de Toros</strong>, uns Banhos Romanos ou talvez uma Estação de Metro?</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
