import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "700": "<p>Bevindt u zich al voor het gebouw van het Postkantoor? Bedenk dat dit op uw kaart overeenkomt met nummer 14.</p>",
  "701": "<p>Staat u al tegenover de Mercado Central? Ja? Goed! Gaan we verder?</p>",
  "702": "<p>Bevindt u zich al op het punt aangegeven met nummer <mark>11</mark> op uw kaart? Goed! Laten we verder gaan <i>op zoek naar de schat</i>!</p>",
  "703": "<p>Geweldig! Laten we de schat blijven zoeken! Kijk om u heen en u kunt ruïnes zien die opvallen tussen de botanische beplanting van de Jardín del Turia. Kunt u ze zien? Ja? Perfect, want de volgende geschiedenis zal u naar wij hopen verrassen.</p>",
  "704": "<p>Bevindt u zich al op het punt aangegeven met nummer <mark>6</mark> op uw kaart?</p>",
  "704-B": "<p>Bevindt u zich al op het punt aangegeven met nummer <mark>3</mark> op uw kaart?</p>",
  "705": "<p>Bevindt u zich al op het punt aangegeven met nummer <mark>24</mark> op uw kaart?</p>",
  "706": "<p>Bevindt u zich al op het punt aangegeven met nummer <mark>76</mark> op uw kaart?</p>",
  "707": "<p>Waarvan is Orxata gemaakt? Van chufa (aardamandel), van rijst of van gerst?</p>",
  "708": "<p>In de loop van uw Avontuur kunt u het majestueuze Parque de Cabecera volledig ontdekken, langs de oude Molí del Sol; bedenk dat molens vroeger onmisbare gebouwen waren om graan te malen en daarmee de benodigde bloem te produceren om onder andere gebak en brood te maken.</p>",
  "709": "<p>De Molí del Sol, gebouwd in 1880, was de eerste van de 18 molens van de acequia de Rascanya en de laatste hydraulische molen gebouwd in de Valenciaanse huerta, waarbij het hoogteverschil van het terrein werd benut om tarwe en rijst te malen. Na het dempen van de acequia in de jaren tachtig raakte het gebouw in onbruik totdat het werd gerestaureerd in het huidige Parque de Cabecera, de exacte plek waar tegenwoordig de Groene Route van het Turia Rivierpark begint. Dit fiets- en wandelpad strekt zich ongeveer 30 km naar het westen uit over bospaadjes, de natuurlijke loop van de Río Turia volgend.</p>",
  "710": "<p>Het Geschiedenismuseum van Valencia is waarschijnlijk een van de beste plaatsen om meer te leren over de mediterrane cultuur waarin u zich vandaag bevindt.</p>",
  "711": "<p>Het volgende interessante punt in uw avontuur is een zeer bijzondere plek waar water van groot belang is. Het tentoonstellingscentrum en museum NaTuria fungeert als een ontmoetingspunt voor burgers om stedelijke duurzaamheid te bevorderen, als opleidingscentrum te dienen en educatieve middelen aan te bieden over ecologie en het milieu.</p>",
  "712": "<p>Dit correspondeert met nummer <mark>68</mark> op uw kaart.</p>",
  "713": "<p>NaTuria is een educatieve en omgevingsruimte waarvan het doel is de natuur dichter bij de burgers te brengen en duurzame gewoonten in het dagelijks leven te bevorderen via tentoonstellingen, cursussen, workshops en rondleidingen gericht op duurzaamheid, recycling, biodiversiteit en stedelijke levenskwaliteit; in de nabije omgeving bevindt zich een kleine dam of azud die water vasthoudt van het oude rivierbed en deel uitmaakt van het landschapsproject van het park, waarbij een waterrijke omgeving wordt nagebootst die de oude Turia oproept met oeverbegroeiing, bijbehorende fauna zoals vogels en amfibieën, en wandel- en observatiegebieden, waar ook de Molino del Tell staat, een gerestaureerde oude meelmolen die is geïntegreerd in de activiteiten van NaTuria zelf, waarin zijn geschiedenis, het traditionele duurzame leven en de historische relatie van Valencia met het water worden uitgelegd, zodat dit geheel — de dam en de waterrijke omgeving — hoofdzakelijk fungeert als een educatief en symbolisch element dat de band van de stad met haar rivier herinnert en het leren over duurzaam waterbeheer bevordert.</p>",
  "VIV1": `<p>${LOGO} beveelt u aan de route op uw kaart te volgen en de promenade te bewandelen.</p>\n\n<p>Halverwege de promenade, aan de rechterkant, bevinden zich de ruïnes van wat ooit de Koninginnetoren was van het inmiddels verdwenen paleis.</p>`,
  "VIV2": "<p>Vervolgens ziet u een grote aardeheuvel.</p>\n\n<p>Dit is een perfect punt om prachtige foto's te maken van het uitzicht dat de tuin biedt.</p>\n\n<p>De heuvel draagt de naam Elio, Kapitein-Generaal van de Koninkrijken Valencia en Murcia in de 19e eeuw.</p>\n\n<p>Merkwaardig genoeg werd Elio enkele jaren later op deze zelfde plek onthoofd.</p>\n\n<p>Deze heuvel werd gecreëerd met de ruïnes van het paleis, waarop bomen en bloemen werden geplant. Het was op de heuvel Elio dat de kwekerijen van de stad ontstonden.</p>\n\n<p>Deze punten komen overeen met de nummers <mark>2</mark> en <mark>3</mark> respectievelijk.</p>",
  "VIV3": `<p>Iets verderop, aan de linkerkant van de promenade, kunnen we het huis van de hoofdtuinman zien dat overeenkomt met nummer <mark>4</mark> op uw kaart.</p>\n\n<p>Tegenwoordig fungeert het als kantoren van de tuinen.</p>\n\n<p>Ga verder tot het einde van de Palmenlaan en u vindt een leuk stadsrondje waar de kleinsten, spelenderwijs, leren de verkeersborden te interpreteren.</p>\n\n<p>Dit correspondeert met nummer <mark>5</mark> op uw kaart.</p>\n\n<p>${LOGO} nodigt u uit op pauze te drukken en dit rondje op uw eigen tempo te doorlopen; dit is een perfect punt om foto's te maken van uw Avontuur en het te hervatten vanaf dit zelfde punt, wanneer u dat wenselijk acht.</p>`,
  "VIV4": "<p>Stel u op kijkend naar het rondje, draai naar uw linkerkant en begeef u in de calle Jardineros Mayores.</p>\n\n<p>Op uw kaart correspondeert dit met nummer <mark>6</mark>.</p>\n\n<p>Het traject is een geplaveide zone omzoomd door jacaranda's, afkomstig uit Brazilië, en Podocarpus uit China.</p>\n\n<p>Dit gebied wordt gebruikt voor diverse evenementen, zoals bijvoorbeeld de boekenbeurs.</p>\n\n<p>Ga verder over dit pad tot het einde en u zult zien dat er een esplanade opent.</p>\n\n<p>Aan de linkerkant is een typisch voorbeeld te zien van de Valenciaanse landelijke architectuur. De bekende Alquería de Canet correspondeert met nummer <mark>7</mark> op uw kaart. Tegenover de alquería bevindt zich een museum; op uw kaart correspondeert dit met nummer <mark>8</mark>.</p>",
  "VIV5": "<p>Waaraan is het museum gewijd? Aan de natuurwetenschappen? Misschien aan de architectuur? Of misschien aan de geschiedenis?</p>",
  "VIV6": "<p>In de jaren zeventig was dit gebouw bekend als \"het restaurant van Viveros\"; tegenwoordig herbergt het, onder andere, een collectie geschonken in 1889 door Don José Rodrigo Botet, een Valenciaanse ingenieur, die een groot aantal paleontologische resten verzamelde gevonden bij zijn opgravingen op het Amerikaanse continent.</p>\n\n<p>Opvallend zijn de enorme holenbeer (de megatherium) uit de Argentijnse Patagonië, versteende dinosaurusafdrukken, fossiele resten, skeletten, gepantserde gordeldieren, schelpen en talrijke insecten.</p>\n\n<p>Dit alles aangevuld met verklarende panelen, educatieve zones en audiovisueel materiaal.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
