import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "470": "<p>Elke 1 maart kleurt de stad in de kleuren van bloemen en kruit om de lente en meer dan een miljoen bezoekers te verwelkomen.</p>",
  "471": "<p>De Fallas worden op straat beleefd dankzij het doorgaans mooie weer en omdat de stad voetgangersgebied wordt.</p>\n<p>De volle straten, het aanschouwen van het fallero-monument en de stops om te verfrissen zijn enkele van de redenen waarom Valencia tijdens de Fallas een onvergelijkbaar feest is.</p>",
  "472": "<p>Tijdens de Fallas is alles feest: het gebulder van de mascletà, de casales, de pasacalles en de muziekkorpsen trekken langs meer dan 700 fallero-monumenten.</p>\n<p>Op 15 maart begint de Plantà of het assembleren van het monument, waarbij sommige de 25 meter hoogte bereiken.</p>\n<p>De fallero-monumenten gemaakt van brandbare materialen zoals hout, karton, papier of stof worden verbrand na enkele dagen tentoongesteld te zijn in de straten, waarmee dit gebaar de lente verwelkomt.</p>",
  "473": "<p>Precies in het midden van dit plein wordt elk jaar een houten structuur opgericht die als steun dient om met veelkleurige bloemen de mantel van de Patrones van Valencia te «weven».</p>\n<p>De bloemenhulde aan de «Mare de Déu dels Desamparats» heeft haar oorsprong in de Basílica, nadat in 1941 enkele tuinvrouwen bloemenboeketten aan de Maagd aanboden.</p>",
  "474": "<p>Maar binnen slechts 8 jaar dwong de Ofrenda de organisatoren haar buiten de Basílica te houden.</p>\n<p>Zo groot was de devotie dat op de gevel van het kerkgebouw raamwerken werden gebouwd om de bloemenboeketten neer te leggen.</p>\n<p>Jaren later werden kinderen en muziekkorpsen in de pasacalles opgenomen in de Ofrendas.</p>\n<p>Later werd overeengekomen dat bij de Ofrenda alleen in regionale klederdracht zou mogen worden deelgenomen en er werden nieuwe routes georganiseerd omdat in 1964 de optocht verdrievoudigde en meer dan twintigduizend mensen bijeenbracht.</p>\n<p>Tegenwoordig begint de Ofrenda de las flores op de 17e tot in de vroege ochtend van 19 maart en bereikt meer dan honderddertigduizend Falleras en Falleros, waarbij de <strong>Plaza de la Virgen</strong> vol bloemen staat.</p>",
  "475": `<p>Vergeet niet dat, als u er bent tijdens de openingsuren, ${LOGO} u aanraadt dit architectonische juweel te beklimmen om de geschiedenis van de stad en haar gebruiken beter te leren kennen.</p>`,
  "476": "<p>Richt uw aandacht, van buitenaf, enigszins naar rechts van de basiliek.</p>",
  "477": "<p>Op de achtergrond springt de Gotische Deur van de Kathedraal in het oog, de tweede die werd gebouwd.</p>\n<p>Genaamd de Poort der Apostelen vanwege de twaalf gebeeldhouwde figuren op het portaal, werd ze gebouwd in de 14e eeuw en bestaat uit twee opeengestapelde bouwlagen.</p>\n<p>In de onderste bouwlaag is het portaal te onderscheiden dat uit de muur steekt met spitsbogen, kenmerkend voor de gotische stijl, en drie archivoltenbogen met gebeeldhouwde figuren van engelen en heiligen.</p>\n<p>In het timpaan van de deur is de sculptuur te zien van de Heilige Maria met het kind in haar armen.</p>\n<p>Aan beide zijden van de Maagd zijn engelen te onderscheiden die muziekinstrumenten bespelen.</p>\n<p>Pauzeer deze audiogids niet en nader, als u zo vriendelijk wilt zijn, het portiek.</p>",
  "477-B": "<p>Op de achtergrond springt de Gotische Deur van de Kathedraal in het oog, de tweede die werd gebouwd.</p>",
  "478": "<p>In de bovenste bouwlaag springt het stenen roosvenster in het oog dat de vorm aanneemt van het Zegel van Salomo.</p>\n<p>Met een diameter van 6,5 meter vervult het de functie van verlichting van de kathedraal.</p>\n<p>Het roosvenster dat men tegenwoordig kan zien is niet het origineel van 1462, aangezien het in 1957 moest worden vervangen vanwege de aantasting ervan.</p>",
  "479": "<p>In zijn portiek wordt elke donderdag het Tribunal de las Aguas gehouden; een snel mondeling gerechtelijk oordeel dat verantwoordelijk is voor het oplossen van conflicten over het gebruik en de benutting van irrigatiewater tussen de boeren.</p>\n<p>De oorsprong van dit tribunaal is onbekend, maar men gelooft dat er al een voorganger bestond uit de Romeinse tijd; zijn functie zoals die tegenwoordig bekend is, ontstond echter meer dan een millennium geleden tijdens het Arabische bewind.</p>",
  "480": "<p>Langs het bed van de oude rivier, op ongeveer 200 meter, bevindt zich het plein vanwaar de vuurwerkkastelen worden afgeschoten. Zoals u heeft kunnen vaststellen, houden de Valencianen van kruit.</p>",
  "480-B": "<p>Ga naar het emblematische <strong>Palacio de la Generalitat</strong> dat op uw kaart nummer <mark>23</mark> correspondeert en de laatste halte is van dit avontuur.</p>",
  "481": "<p>Het <strong>Palacio de la Generalitat</strong> Valenciana is gelegen in de <strong>Barrio de la Seu</strong> of <strong>Barrio de la Catedral</strong> en begon zijn constructie in 1421.</p>\n<p>Met talrijke restauraties en uitbreidingen, waarbij de voornaamste Valenciaanse meesters van hun tijd betrokken waren, is het voormalige stadhuis van de stad in Valenciaanse gotische stijl met Renaissance-ingrepen.</p>",
  "481-B": "<p>Met talrijke restauraties en uitbreidingen, waarbij de voornaamste Valenciaanse meesters van hun tijd betrokken waren, is het voormalige stadhuis van de stad in Valenciaanse gotische stijl met Renaissance-ingrepen.</p>\n<p>Het <strong>Palacio de la Generalitat</strong> Valenciana, gelegen in de <strong>Barrio de la Seu</strong> of <strong>Barrio de la Catedral</strong>, begon zijn constructie in 1421 en werd in de 16e eeuw uitgebreid met een grote toren.</p>\n<p>De steenhouwers voerden het werk uit met zwarte steen uit Alcublas, wit marmer uit Valldigna en steen uit Ribarroja, plaatsen in de buurt van Valencia.</p>",
  "482": "<p>Het gebouw werd in de 16e eeuw uitgebreid met een tweede grote toren van vergelijkbare afmetingen als de eerste.</p>\n<p>Om hem te bouwen gebruikten de steenhouwers zwarte steen uit Alcublas, wit marmer uit Valldigna en steen uit Ribarroja, plaatsen in de buurt van Valencia.</p>",
  "482-B": "<p>Tegenwoordig herbergt het de zetel van de Regering van de Comunitat Valenciana.</p>",
  "483": "<p>Welke van de twee torens denkt u dat de nieuwste is: die aan het plein of die welke nu voor u staat?</p>",
  "484": "<p>Het antwoord? De toren die voor u staat!</p>",
  "485": "<p>Pauzeer deze audiogids niet. Stel u op met het monument dat we zojuist noemden aan uw linkerhand en ga verder, zoals uw kaart aangeeft, via de straat die aan uw rechterzijde opent.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>45</mark>.</p>",
  "485-B": "<p>Pauzeer deze audiogids niet. Stel u op met het monument dat we zojuist noemden aan uw linkerhand en ga verder, zoals uw kaart aangeeft, via de straat die aan uw rechterzijde opent; op uw kaart correspondeert dit met nummer <mark>4</mark>.</p>",
  "486": "<p>De bekende <strong>Calle Caballeros</strong> correspondeert aan de oost-westas die de oude Romeinse stad doorkruiste, in die tijd de via Decumanus Maximus genaamd.</p>\n<p>Het Monumentale Complex van de Kathedraal, de bouw van het <strong>Palacio de la Generalitat</strong> en de nabijheid van de Iglesia de San Nicolás, stimuleerden de vestiging van adellijke families langs deze bekende straat.</p>\n<p>Om die reden berust de historische en artistieke waarde van de <strong>Calle Caballeros</strong> op het zijn van het concentratiepunt van de macht van de stad.</p>\n<p>Langs haar bevinden zich talrijke paleisjes waar een groot deel van de Valenciaanse adel woonde.</p>\n<p>De <strong>Calle Caballeros</strong> draagt haar naam al sinds 1412.</p>\n<p>Dezelfde naam zo lang te dragen is een hele prestatie voor een straat in welke stad dan ook.</p>",
  "487": "<p>Ga verder langs de <strong>Calle Caballeros</strong> naar het volgende bezienswaardige punt.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>46</mark>.</p>",
  "487-B": "<p>Ga verder langs de <strong>Calle Caballeros</strong> naar het volgende bezienswaardige punt.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>5</mark>.</p>",
  "488": "<p>De <strong>Iglesia de San Nicolás</strong> bevindt zich enkele meters verder, aan uw linkerzijde.</p>\n<p>Let op de ingang want die is onevenredig klein in vergelijking met het interieur van het kerkgebouw en kan gemakkelijk over het hoofd worden gezien.</p>",
  "489": "<p>De <strong>Iglesia de San Nicolás</strong> de Bari y San Pedro Mártir, ook bekend als «de kleine Sixtijnse Kapel van Valencia», is een kerkgebouw met gotische structuur en barokke decoratie in het interieur.</p>\n<p>Aanvankelijk gebouwd in 1245 op een oude Arabische moskee, onderging de kerk een integrale verbouwing in 1455 die haar huidige gotische fysionomie gaf.</p>\n<p>In 1693 werd het gotische gewelf bedekt met een in Barokke stijl, meer in overeenstemming met die tijd.</p>\n<p>Rond het jaar 1700 werd in het interieur een ambitieus project gestart dat de meer dan 2.000 vierkante meter zou bedekken met fresco's.</p>\n<p>De <strong>Iglesia de San Nicolás</strong> werd in 1981 uitgeroepen tot Nationaal Historisch-Artistiek Monument en is tegenwoordig een van de meest bezochte kerken van de stad Valencia.</p>",
  "490": `<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en de talrijke en indrukwekkende details van de fresco's van de kapel te bewonderen.</p>\n<p>Wanneer u besluit door te gaan, bekijk de kaart die u leidt om de kerk heen te lopen om de andere gevels te aanschouwen, ook vermeldenswaard.</p>\n<p>Neem daarvoor de eerste straat aan uw linkerhand.</p>`,
  "491": "<p>Met de deur van San Nicolás aan uw linkerzijde, loop om de kerk heen en stel u op in het midden van het plein; van daaruit kunt u een eenvoudig portaal in gotische stijl zien.</p>",
  "492": "<p>Het doel van deze constante verandering is iedereen te kunnen ontvangen; daarom worden elke twee weken verschillende stijlen getoond en worden er regelmatig open danslessen georganiseerd.</p>",
  "493": "<p>Het portaal werd gebouwd in de 15e eeuw, met archivoltenbogen die rusten op slanke zuilen.</p>\n<p>De archivoltenbogen zijn decoratieve elementen die het esthetische probleem oplossen van de openingen of niveauverschillen in een dikke muur; zo wordt het tunnelgevoel vermeden en wordt meer licht de binnenruimte binnengelaten.</p>\n<p>De gotische stijl wordt gekenmerkt door zijn spitsbogen. Deze in het bijzonder is bekroond door een kielboograis.</p>\n<p>Stel u voor dat de boog in vier segmenten wordt verdeeld. Het resultaat zou zijn: twee concave en twee convexe curven die kenmerkend zijn voor dit type bogen.</p>\n<p>Precies onder het toppunt van deze kielboograis bevindt zich een merkwaardig reliëf. Richt uw aandacht... Is het een afbeelding van een schaal... met... vlees?</p>\n<p>De legende vertelt dat de heilige Nicolaas tijdens een reis stopte in een herberg om te dineren en de herbergier hem een schotel vlees serveerde.</p>\n<p>Toen hij zijn maaltijd wilde zegenen, merkte de Heilige op dat het vlees mensenvlees was.</p>\n<p>Nicolaas stelde de herbergier aan de kaak, want in zijn kelder werden ook de verminkte overblijfselen gevonden van drie jongeren die de heilige wonderbaarlijk in elkaar zette en tot leven wekte.</p>",
  "494": "<p>Richt uw aandacht op deze kielboograis, de plek waar een gotisch roosvenster van 1455 de kerk verlicht.</p>\n<p>Dit roosvenster, dat de vorm aanneemt van de Davidster of het Zegel van Salomo, is vergelijkbaar met wat u in de Kathedraal heeft gezien.</p>",
  "494-B": "<p>Richt uw aandacht op deze kielboograis, de plek waar een gotisch roosvenster van 1455 de kerk verlicht.</p>\n<p>Dit roosvenster, dat de vorm aanneemt van de Davidster, is zeer vergelijkbaar met dat wat u in de loop van dit avontuur zult zien in de <strong>Kathedraal van Valencia</strong>.</p>",
  "495": "<p>Aan de rechterkant van de deur bevindt zich een kapel afgesloten door een hekwerk.</p>\n<p>Daarin is een keramisch paneel te zien dat het «Cristo de Fossar» voorstelt.</p>\n<p>Het ontvangt deze naam van het oude kerkhof dat zich precies onder zijn voeten bevond.</p>",
  "496": "<p>Wat is er te zien op dit keramisch paneel? Zijn het doodshoofdjes? Is het een kruis? Is er ook een duif?</p>",
  "497": "<p>De klokkentoren, die precies aan de rechterzijde staat, werd voltooid in 1755 en gerestaureerd in 2007.</p>\n<p>U kunt zien dat de toren bestaat uit drie geledingen:</p>\n<p>De eerste, die de hoogte van het dak bereikt.</p>\n<p>De tweede, die in baksteen is gebouwd, en de derde is die welke de klokken herbergt, die te zien zijn door de rondbogen.</p>",
  "498": "<p>Hoeveel klokken herbergt deze toren? 3, 4 of 5?</p>",
  "499": "<p>Uw schatkaart geeft aan om langs de kerk te blijven lopen om de laatste van haar ingangen te zien.</p>\n<p>Een prachtige neogotische recreatie uit 1864 sluit dit punt af en geeft toegang tot het volgende.</p>",
  "500": "<p>Ga door tot het einde van de straat, sla dan links af en volg de straat tot u het volgende bezienswaardige punt aan uw rechterzijde ziet; daar doemt de <strong>Fuente del Negrito</strong> op.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>48</mark>.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "500-B": "<p>Ga door tot het einde van de straat, sla dan links af en volg de straat tot u het volgende bezienswaardige punt aan uw rechterzijde ziet; daar doemt de <strong>Fuente del Negrito</strong> op.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>7</mark>.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "501": "<p>Wat houdt de figuur in zijn handen? Een schild? Is het een schelp? Misschien een kruik? Of wellicht een zwaard?</p>",
  "502": "<p>Ga verder, zoals uw kaart aangeeft, terug naar de <strong>Calle Caballeros</strong>, die nummer <mark>45</mark> op uw kaart correspondeert.</p>\n<p>Eenmaal op de <strong>Calle Caballeros</strong>, neem het pad aan uw linkerzijde. Uw volgende bestemming opent zich als een plein aan het einde van de straat.</p>",
  "502-B": "<p>Ga verder, zoals uw kaart aangeeft, terug naar de <strong>Calle Caballeros</strong>, die nummer <mark>4</mark> op uw kaart correspondeert.</p>\n<p>Eenmaal op de <strong>Calle Caballeros</strong>, neem het pad aan uw linkerzijde. Uw volgende bestemming opent zich als een plein aan het einde van de straat.</p>",
  "503": "<p>Bent u al terug waar u begon?</p>\n<p>Gefeliciteerd! Proef geslaagd!</p>\n<p>We hopen van harte dat u genoten heeft van dit avontuur, net zoals wij ervan genoten hebben het voor u te ontwerpen. Zoals u heeft kunnen vaststellen, is de stem gegenereerd met kunstmatige intelligentie om elk verhaal tot leven te brengen en u een meeslepende ervaring te bieden. Toch zijn de ziel en het script van de audiogidsen uit de saga <i>op zoek naar de schat</i> het resultaat van Valenciaanse inbreng, die hun passie, hun essentie en hun authenticiteit in elk verhaal weerspiegelt. We voegen er met genoegen aan toe dat deze fusie van traditie en technologie is bedacht om u een dynamische en persoonlijke ervaring te bieden die we hopen naar uw zin is geweest.</p>",
  "504": "<p>In de loop van uw Avontuur, richt uw aandacht op de kloppers of deurknoppen die nog steeds te zien zijn op de deuren van deze oude paleisjes.</p>\n<p>Sommige van deze oude «bellen» werden op een onevenredig grote hoogte geplaatst voor een persoon van gemiddelde lengte.</p>",
  "505": "<p>Waarom werden deze kloppers zo hoog geplaatst?</p>\n<p>Voor grote mensen? Zou het kunnen zijn om aan te kloppen terwijl men te paard zit? Of misschien om niet gestoord te worden?</p>",
  "506": "<p>Ga op uw eigen tempo naar uw volgende bezienswaardige punt.</p>",
  "507": `<p>Wij nemen afscheid, maar herinneren u er eerst aan dat wij meer schattenjachten beschikbaar hebben om Valencia te blijven spelen en ontdekken. ${LOGO} raadt u aan de opslagcapaciteit te verlichten en de prestaties van uw apparaat te optimaliseren door de eventueel gedownloade bestanden te verwijderen. Op deze manier dragen we ook bij aan het bevorderen van een verantwoord beheer van digitale hulpbronnen. Dank u.</p>`,
  "508": "<p>De <strong>Calle Caballeros</strong>, die u zojuist heeft verlaten, correspondeert aan de oost-westas van de stad. Herinnert u het zich?</p>\n<p>Perfect! Met deze referentie in uw rug zou de loodrechte straat, logischerwijs, overeenkomen met een noord-zuidas.</p>\n<p>Vouw uw kaart open en bekijk hem; volg de route die we in dit Avontuur voorstellen.</p>",
  "509": "<p>In welke richting gaat het vastgestelde pad? Is het naar het noorden? Het zuiden? Gaat het naar het oosten? Of misschien naar het westen?</p>",
  "510": "<p>Correct! Noord. Deze weg, zoals u zo dadelijk zult zien, verdeelt zich in twee: Calle Alta en Calle Baja.</p>\n<p>Uw volgende bestemming loopt langs de beroemde Calle Baja, maar laten we eerst kort spreken over het plein waar u zich bevindt.</p>\n<p>We keren terug naar de Arabische tijd.</p>",
  "511": `<p>Tossal, wat «lichte verhoging van het terrein» betekent, maakte deel uit van de moslimmuur die de stad omsloot.</p>\n<p>De muur fungeerde tevens als afdammingspunt voor het water van een arm van de <strong>Río Turia</strong> die vroeger hier doorheen liep.</p>\n<p>Tegenwoordig zijn er overblijfselen van die muur tentoongesteld in een bezoekbare ondergrondse galerij die dezelfde naam draagt als het plein en zich onder uw voeten bevindt.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit historische complex op eigen tempo te bezoeken.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht.</p>`,
  "512": "<p>Stel u op met de <strong>Calle Caballeros</strong> achter u en neem het pad aan uw rechterhand.</p>\n<p>Zoals we eerder vermeldden, ziet u dat de weg zich verdeelt.</p>\n<p>Neem de straat rechts en volg die tot uw volgende bezienswaardige punt dat gelegen is in een van die smalle straten die aan uw rechterzijde opent.</p>",
  "513": "<p>Het <strong>Portal de la Valldigna</strong> werd gebouwd op de Arabische muur zelf.</p>\n<p>Het was een toegang tot de Moorse wijk vanaf het jaar 1400, het jaar waarin de deur werd weggehaald, zodat het portaal bewaard bleef zoals het vandaag te zien is.</p>\n<p>De rondboog, gebouwd in gehouwen steen, werd gerestaureerd in 1965.</p>\n<p>Boven de boog is een reproductie te zien van het originele altaarstuk dat in 1589 op deze plek werd geplaatst.</p>\n<p>Het altaarstuk schetst Koning Jaime Tweede van Aragón, de Rechtvaardige genaamd, in de handeling van de stichting van het Klooster van Valldigna, wat letterlijk «waardige landen» betekent.</p>",
  "514": "<p>Als u zo vriendelijk wilt zijn, kruis het portaal over en betreed de Arabische wijk van Valencia.</p>\n<p>Neem de eerste straat aan uw linkerzijde. Aan het einde van de straat is nog steeds een toren van de Arabische muur te zien, de zogenoemde Poort van de Engel.</p>",
  "515": "<p>In de 11e eeuw, na de val van het Kalifaat van Córdoba, verdeelde het Oude Rijk zich in kleine facties die Taifas werden genoemd.</p>\n<p>Valencia, of Balansiya zoals het in moslimtijden bekend stond, was de hoofdstad van een van die Taifas. Als gevolg daarvan kende het een belangrijke stedelijke groei.</p>\n<p>De bevolkingstoename en de voortdurende aanvallen uit Noord-Afrika spoorden de bevolking aan de oude stad en haar defensieve perimeter uit te breiden.</p>\n<p>Het ontwerp van de nieuwe stadsmuur zou Valencia transformeren en een nieuwe perimeter vestigen.</p>",
  "516": "<p>Deze werd gebouwd van beton en gevuld met stenen van verschillende groottes.</p>\n<p>De muur stelde de inwoners van Balansiya in staat het zware beleg door Rodrigo Díaz de Vivar, beter bekend als El Cid Campeador, in het jaar 1094 te weerstaan, hoewel het de verovering niet kon verhinderen.</p>\n<p>De stad werd ingenomen door de christenen en bleef zo tot het jaar 1144, waarna Valencia opnieuw in moslimhanden overging.</p>\n<p>Al die tijd veranderde er één ding niet; de muren met hun torens bleven overeind staan.</p>",
  "517": "<p>Zelfs na de christelijke Reconquista in 1238 door Jaime Eerste de Veroveraar werd de Arabische stadsmuur niet vernield, maar bleef hij als beschermingsmaatregel anderhalve eeuw overeind staan.</p>\n<p>Deze perimeter, waarvan vandaag nog zichtbare overblijfselen bestaan, had 7 hoofdpoorten en torens die strategisch werden geplaatst om de 25 meter.</p>\n<p>De toren die u nu kunt zien heeft een halfcirkelvormige plattegrond en is uitgevoerd in breuksteen.</p>",
  "518": "<p>Wat is breuksteen? Het is een mengsel van stenen en specie; een traditioneel cement samengesteld uit kalk, zand en water, waaraan ook klei en stro konden worden toegevoegd om de hardheid te vergroten.</p>\n<p>Breuksteen is een eenvoudig bouwsysteem dat afval van de gebruikte materialen minimaliseert en zeer geschikt is voor constructies van grote hoogte.</p>",
  "519": "<p>Hoeveel poorten had de oude Arabische stadsmuur van Balansiya? Waren het er 5? Misschien 6? Of wellicht 7?</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
