import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "651": "<p>Storicamente è attestato che dal 1332, diverse passerelle o ponti attraversavano il Turia in questo stesso luogo e che le continue piene del fiume li demolivano continuamente.</p>\n\n<p>Questo ponte ha diverse curiosità degne di nota, come ad esempio il fatto che le quattro sculture visibili non sono quelle scelte originariamente.</p>\n\n<p>Nel 1609, la nave che le trasportava da Genova fu assalita da dei pirati che si impossessarono dell'intero carico.</p>",
  "652": "<p>Un altro aneddoto, il più clamoroso, fu quello del 1528.</p>\n\n<p>Il ponte, ancora in legno, cedette sotto il peso delle centinaia di spettatori che si accalcavano per vedere passare l'Imperatore Carlo I durante la sua visita a Valencia.</p>",
  "653": "<p>Il ponte che si può vedere oggi risale al 1598.</p>\n\n<p>Dopo l'alluvione del 1590 si prese la decisione di costruire una base più solida per resistere alle forti esondazioni.</p>\n\n<p>In quei tempi, il ponte contava già dieci archi di tredici metri di luce ciascuno.</p>\n\n<p>Anni dopo, nel 1957, a seguito di un'altra alluvione subì nuovamente danni considerevoli, e nel 1966 si aumentò la larghezza del ponte, alleviando così il crescente traffico della città.</p>",
  "654": "<p>Attraversi il ponte e osserverà una piazza che si apre davanti a Lei.</p>\n\n<p>Ubicata nel Quartiere della Xerea, uno dei più antichi della città, la Plaza de Tetuán comprende diversi edifici importanti degni di menzione.</p>\n\n<p>Ricordi di premere pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "655": "<p>Il suo obiettivo è il piccolo giardino che si trova sul lato opposto della piazza.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>79</mark>.</p>\n\n<p>Non metta in pausa questa audioguida e si diriga al suo prossimo punto di interesse.</p>",
  "656": "<p>Nel corso del cammino verso il suo prossimo obiettivo vedrà alla sua sinistra l'antico Convento di Santo Domingo, un edificio di stile gotico e barocco che risale alla fondazione della città, poiché fu lo stesso Re Giacomo I a posarne la prima pietra nel 1239 e nel quale riposano oggi i resti di diversi personaggi illustri della città.</p>\n\n<p>Di fronte, a destra, si erge un edificio monumentale realizzato in pietra bianca che vedrà con maggiori dettagli nel corso di questa Avventura.</p>\n\n<p>Ricordi di premere pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "657": "<p>Il parco in cui si trova ha le sue origini nel 1812. Soprannominato Parco della Glorieta, fu il primo luogo illuminato della città.</p>\n\n<p>Il 9 ottobre 1844 furono collocati diversi lampioni a gas distribuiti simmetricamente lungo la rotonda e i marciapiedi laterali.</p>\n\n<p>Non è fino al 1852 che vengono piantati i grandi ficus che si distinguono per la loro monumentalità e le loro grandi radici.</p>",
  "658": "<p>Attualmente quegli enormi Ficus si trovano dall'altro lato del parco.</p>\n\n<p>Si avvicini agli alberi, se è così gentile, per contemplarne la maestosità.</p>\n\n<p>Dietro il boschetto si trova il suo prossimo punto di interesse in questa avventura.</p>",
  "659": `<p>Ammiri il Palazzo di Giustizia.</p>\n\n<p>La sua attuale denominazione è quella di Tribunale Superiore di Giustizia della Comunità Valenciana.</p>\n\n<p>Il grandioso edificio che vediamo oggi risale al 1758, ultimo anno del regno di Carlo III.</p>\n\n<p>L'edificio occupa un grande isolato rettangolare, le sue facciate sono composte da muri di mattoni a vista tra lesene in pietra e balconi retti e curvi al primo piano.</p>\n\n<p>In alto, la cornice con balaustre, ornamenti a torce e nicchie vuote mostra il gusto barocco.</p>\n\n<p>I lavori furono avviati dall'accademico valenciano Felipe Rubio Mulet, ma questi morì prima di poterli vedere ultimati; fu suo cognato a completare l'opera nel 1802.</p>\n\n<p>Inizialmente, questo edificio fu costruito come Dogana.</p>\n\n<p>Era il luogo attraverso cui si incanalava tutto il commercio proveniente dal mare e rendeva Valencia uno dei centri economici del XVIII secolo.</p>\n\n<p>Sebbene questo spazio risalga ancora più indietro nel tempo, antiche cronache del 1626 menzionano già una prima dogana che si trovava in questo stesso luogo, accanto alle mura della città e all'antica porta della città chiamata "Puerta de la Mar".</p>`,
  "660": `<p>Con l'edificio alle spalle, osservi il tracciato della sua mappa del tesoro che le indica di continuare la pista ciclabile verso un imponente edificio bianco di costruzione più moderna che rimane a mano sinistra.</p>\n\n<p>Conosciuto popolarmente come "Centro Cultural Bancaja": questo centro è composto da due edifici che furono ristrutturati al loro interno negli anni '80 per la funzione che ora svolgono.</p>\n\n<p>Concentri la sua attenzione sull'edificio più monumentale che precede quello bianco.</p>`,
  "661": "<p>Dalla sua riabilitazione, insieme a quella dell'edificio annesso, è dedicato integralmente a fini culturali e agli uffici propri dell'Ente.</p>\n\n<p>Costruito tra il 1932 e il 1934 sul sito di un antico palazzo in stile castigliano con influenze neo-barocche; l'edificio è composto da tre corpi e una terrazza.</p>\n\n<p>La porta d'ingresso architravata, che forma uno smusso, è decorata con ghirlande di fiori e frutti finemente scolpiti in pietra.</p>\n\n<p>Le facciate sono in pietra nella zona inferiore e superiore, mentre nella parte centrale predomina la terracotta di colore rosso; materiali resistenti al passare del tempo e di manutenzione molto bassa, che a loro volta hanno buone proprietà di isolamento acustico.</p>\n\n<p>Negli anni dal 1936 al 37, mentre Valencia fu capitale della Repubblica Spagnola, l'edificio fu utilizzato come Ministero della Propaganda.</p>",
  "662": "<p>Su questa facciata c'è un orologio. Che ora segna?</p>",
  "663": "<p>L'edificio annesso, che si caratterizza per il suo colore bianco, può essere visto nella sua totalità continuando la sua facciata fino all'angolo; si diriga a quel punto per continuare la sua Avventura.</p>",
  "664": `<p>Costruito nel 1891, ospita le varie dipendenze del Centro Culturale e le mostre che periodicamente organizza.</p>\n\n<p>Un doppio accesso monumentale permette di godere delle mostre della fondazione.</p>\n\n<p>L'edificio è coronato da una cupola smaltata con squame blu in ogni angolo.</p>\n\n<p>Se si trova in orario di visita, ${LOGO} Le consiglia di premere pausa e visitare questo centro culturale al proprio ritmo.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno. Prema semplicemente il pulsante corrispondente e continui alla ricerca del tesoro.</p>`,
  "665": "<p>Si posizioni, se è così gentile, con lo sguardo rivolto all'edificio Fundación Bancaja e prenda la via che esce alla sua mano destra.</p>\n\n<p>In fondo alla via si trova la Plaza de San Vicente Ferrer.</p>",
  "666": "<p>Durante le Fallas si sentono petardi a tutte le ore, se il rumore le sembra troppo forte, apra la bocca e non si tappi le orecchie: è peggio.</p>",
  "667": "<p>Nella piazza in cui si trova, una fontana fu eretta nel 1853. Questa è un'altra di quelle 8 fontane pubbliche che erano recettrici del recente arrivo dell'acqua potabile in città.</p>",
  "667-B": "<p>Nella piazza in cui si trova, una fontana fu eretta nel 1853; tempi in cui le fontane pubbliche erano le recettrici del recente arrivo dell'acqua potabile in città.</p>\n\n<p>La distribuzione dell'acqua potabile non era ancora generalizzata nelle abitazioni e bisognava raccoglierla alle fontane pubbliche per uso personale.</p>",
  "668": "<p>Cosa sorregge la figura con la sua mano? Uno scudo, un'arpa, una brocca o forse una spada?</p>",
  "669": "<p>Dietro la fontana possiamo ammirare la Chiesa di Santo Tomás e San Felipe Neri.</p>\n\n<p>Questo Tempio fu costruito tra il 1727 e il 1736 in mattoni dipinti di rosso.</p>\n\n<p>Il primo corpo si erge su un basamento in pietra che si articola in otto grandi lesene.</p>\n\n<p>Al centro si apre una porta architravata realizzata in pietra.</p>\n\n<p>Sopra il portale, due immagini femminili rappresentano la Verginità, adornata con i fiori della purezza; e la Preghiera.</p>\n\n<p>Ecco perché sorregge il turibolo del culto divino.</p>\n\n<p>Un altorilievo in cui è rappresentata l'apparizione della Vergine a San Filippo Neri e lo stemma della monarchia spagnola sull'architrave della porta sono due esempi di altorilievo che offre questo tempio.</p>\n\n<p>Spicca anche il suo campanile a pianta quadrata, con 45 metri di altezza e 106 gradini. Questa chiesa fu Dichiarata Monumento Storico-Artistico Nazionale nel 1982.</p>",
  "670": "<p>Ammirando questo tempio di culto, appena pochi passi nella via alla sua sinistra si erge un altro monumento da segnalare in questa avventura.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>83</mark>.</p>\n\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato.</p>",
  "670-B": "<p>Ammirando questo tempio di culto, appena pochi passi nella via alla sua sinistra si erge un altro monumento da segnalare in questa avventura.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>30</mark>.</p>\n\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato.</p>",
  "671": `<p>Sta per addentrarsi nel regno arabo di Valencia.</p>\n\n<p>Dal "Barrio del Mercat" al famoso "Barrio del Carmen" numerosi ritrovamenti archeologici testimoniano l'importanza raggiunta dalla città.</p>\n\n<p>Con la reconquista di Valencia da parte di Giacomo I nel 1238, si pose fine a cinque secoli di cultura musulmana; tuttavia, questa lasciò un'impronta solida nel territorio valenciano.</p>`,
  "672": `<p>Il XIII secolo fu, per Valencia, il periodo di transizione tra il Romanico e il gotico, anche tra l'islamico e il cristiano.</p>\n\n<p>La Chiesa di San Juan del Hospital conserva reminiscenze di queste trasformazioni.</p>\n\n<p>Il complesso storico possiede marcate influenze arabe nella pianta rettangolare che erano proprie del mudéjar.</p>\n\n<p>Un ampliamento, questa volta in stile gotico, fu realizzato nell'anno 1316.</p>\n\n<p>La cappella ospedaliera funeraria fu probabilmente la prima manifestazione dell'arte ogivale nella Valencia del XIII secolo.</p>\n\n<p>La Chiesa di San Juan del Hospital fu dichiarata Monumento Artistico Nazionale nel 1943.</p>\n\n<p>Se si trova in orario di visita, ${LOGO} Le consiglia di premere pausa e visitare questo complesso storico al proprio ritmo.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno. Prema semplicemente il pulsante corrispondente e continui alla ricerca del tesoro.</p>`,
  "673": "<p>L'origine del Palazzo risale al XIII secolo. Questo edificio subì continue riforme, la più importante delle quali fu quella realizzata nel XVIII secolo, in cui si modificò l'interno e la facciata.</p>\n\n<p>Nel 1936, all'inizio della Guerra Civile Spagnola, l'edificio fu incendiato più volte, rimanendo distrutto ad eccezione di parte della cappella, che rimase in fiamme per tre giorni consecutivi.</p>\n\n<p>In questi incendi andarono persi circa 13.000 volumi scritti e il Museo Diocesano con tutte le opere d'arte al suo interno. L'attuale edificio, di stile eclettico, fu ricostruito tra il 1941 e il 1946.</p>",
  "674": "<p>Sul lato opposto della piazza si trova il Palazzo del Marchese di Campo. Riesce a vederlo?</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>85</mark>.</p>\n\n<p>L'edificio risale al XVIII secolo, ma nel XIX secolo il Marchese di Campo procedette a una completa ristrutturazione.</p>\n\n<p>Anni dopo, e dopo essere passato per diverse mani, il Comune dichiarò il Palazzo Monumento Storico-Artistico di carattere locale.</p>\n\n<p>L'avvenimento del 1973 ne elevò il rango nel 1982, quando ottenne la categoria di Monumento Storico-Artistico di carattere provinciale.</p>\n\n<p>Nel 1989, dopo una costosa e dedicata riqualificazione, il Palazzo fu messo in uso come Sede del Museo della Città.</p>\n\n<p>Attualmente il museo ospita importanti collezioni che fino ad allora erano disperse in diversi edifici.</p>\n\n<p>Queste ci aiutano a capire meglio la storia valenciana dalla fondazione romana fino alla metà del XIV secolo.</p>\n\n<p>Inoltre, il museo viene anche utilizzato come sala per mostre temporanee; distribuita per il museo si può contemplare un'importante collezione di arte valenciana del XX secolo.</p>\n\n<p>Al piano superiore è esposta una collezione di pesi e misure.</p>",
  "675": `<p>Alla sinistra del Museo, un ingresso discreto dà accesso a un punto di interesse in questa Avventura.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>86</mark>.</p>\n\n<p>In questo luogo si trovava una delle prigioni in cui fu rinchiuso San Vincenzo Martire nel IV sec. d.C., morto senza rinunciare alla sua fede dopo essere stato torturato nell'anno 304 dai romani.</p>\n\n<p>L'interno ospita una cappella funeraria in eccezionale stato di conservazione dell'epoca visigota, parliamo dei secoli VI e VII d.C.</p>\n\n<p>Se si trova in orario di visita, ${LOGO} Le raccomanda di premere pausa ed entrare in questi tesori storici per conoscere meglio la storia della città.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno, prema semplicemente il pulsante corrispondente e continui alla ricerca del tesoro.</p>\n\n<p>La sua avventura continua in questo stesso punto.</p>`,
  "676": `<p>Continui per la stretta via; all'uscita da essa, proprio di fronte si erge l'edificio dell'Almudín, numero <mark>87</mark> sulla sua mappa.</p>\n\n<p>Almudín deriva dalla parola araba "Almud" che è il nome di una misura di peso, simile a dire Oncia o Grammo.</p>`,
  "677": "<p>A quale scopo potrebbe essere stato destinato l'edificio?</p>\n\n<p>Magazzino del grano, macelleria municipale o forse vendita di spezie?</p>",
  "678": "<p>Dal 1307 e costruito su un antico castello musulmano fortificato, questo edificio è stato deposito e commercio di grano di Valencia; per cui possiamo farci un'idea dell'importanza che rappresentava un edificio di queste caratteristiche nella Valencia medievale.</p>\n\n<p>A tal fine fu creata una complessa rete di funzionari incaricati di un compito così importante.</p>\n\n<p>Immagini, a sua volta, che la mancanza di grano e farina e quindi di pane poteva essere fonte di saccheggi e rivolte dalle conseguenze imprevedibili.</p>\n\n<p>Da qui la necessità di avere un luogo arieggiato, ma di difficile accesso; osservi l'altezza delle finestre e le loro dimensioni.</p>\n\n<p>Attualmente l'edificio è dedicato a Sala Municipale di Esposizioni Temporanee.</p>",
  "679": "<p>Bravo! Sta per concludere la sua avventura.</p>\n\n<p>Osservi la sua mappa che le indica di uscire nuovamente in Plaza de la Virgen. Questa dovrebbe rimanere alla sua sinistra. Si posizioni con la Fontana di Nettuno alle spalle, guardando la via che ha di fronte.</p>\n\n<p>Ricordi di premere pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "680": "<p>È arrivato al punto suggerito? Bene! Non metta in pausa questa audioguida.</p>\n\n<p>Apra la sua mappa e osserverà che la incita a tornare al punto di partenza. Sì, al numero <mark>1</mark>!</p>\n\n<p>Bravo! Quella sarà la sua ultima tappa e con ciò avrà percorso 34 chilometri di tesori architettonici storici e recenti senza uscire dalla città di Valencia!...beh...quasi.</p>\n\n<p>Segua il corso della via in cui numerosi locali la tenteranno a degustare la gastronomia locale, il suo obiettivo è alla fine della via, girando a sinistra.</p>",
  "681": "<p>Ci farebbe piacere fornire due ultimi brevi dettagli che si trovano a sinistra e a destra nel corso del cammino.</p>\n\n<p>Sulla sua mappa corrispondono ai numeri <mark>88</mark> e <mark>89</mark> rispettivamente.</p>",
  "682": "<p>Circa a metà lunghezza della via, a sinistra, si erge la Chiesa di San Lorenzo, numero <mark>88</mark> sulla sua mappa.</p>\n\n<p>Le origini della Chiesa di San Lorenzo risalgono alla reconquista di Valencia stessa nel 1238. Come la Chiesa di Santa Catalina, menzionata in questa Avventura.</p>\n\n<p>Ricordi che, dopo la reconquista e il conseguente cambio di religione della città, Giacomo I strutturò lo spazio urbano.</p>",
  "682-B": "<p>Circa a metà lunghezza della via, a destra, si erge la Chiesa di San Lorenzo.</p>\n\n<p>Le origini della Chiesa di San Lorenzo risalgono alla reconquista di Valencia nel 1238.</p>\n\n<p>Dopo la reconquista e il conseguente cambio di religione della città, Giacomo I strutturò lo spazio urbano.</p>",
  "683": "<p>Cosa porta San Lorenzo in mano? Una Colomba, un cucchiaio o forse una Graticola?</p>",
  "684": "<p>Osservi nell'angolo superiore un piccolo balcone-belvedere coperto da cupola, che permette la visuale su entrambi i lati delle vie dove si trovano i portali della chiesa. Curioso, vero?</p>",
  "685": "<p>Qualche passo più avanti, a destra della via, si erge un edificio costruito in stile gotico. Fu residenza di Papa Rodrigo Borgia nelle sue numerose visite a Valencia.</p>\n\n<p>Les Corts Valencianes corrispondono sulla sua mappa al numero <mark>89</mark>. Riesce a vederlo? Oggi è dedicato ad attività governative.</p>\n\n<p>Congratulazioni! Sta andando nella giusta direzione!</p>",
  "686": "<p>Il palazzo fu costruito nel XV secolo, la sua caratteristica principale è la sua ampia facciata. Nel Basso Medioevo il prestigio di un cognome o di una famiglia si misurava anche dalla grandiosità del suo palazzo. Questa facciata così estesa lasciava presupporre un potere e una nobiltà superiori.</p>\n\n<p>Nonostante il lusso del Palazzo, non era la dimora abituale dei suoi proprietari, che avevano la residenza permanente a Gandía, una località vicina a Valencia.</p>",
  "687": "<p>Ogni 1 marzo la città si tinge con il colore dei fiori e della polvere da sparo per accogliere la primavera e più di un milione di visitatori.</p>\n\n<p>Dal 1954 e da queste stesse torri, ogni anno si dà il via alle celebrazioni fallere. L'attesa \"Cridà\" è la chiamata alla festa delle falleres mayores di Valencia per chi desideri partecipare.</p>",
  "688": `<p>Si diriga al centro del ponte e osservi a sinistra e a destra.</p>\n\n<p>Alla sua sinistra c'è il percorso da dove è venuta, e alla sua destra più di tre chilometri di giardino che sfocia nella famosa Città delle Arti e delle Scienze.</p>\n\n<p>Il panorama futuristico che simboleggia la nuova Valencia; un complesso unico, d'avanguardia architettonica a livello mondiale dove milioni di visitatori si recano ogni anno per godere della sua cultura, della sua natura, della sua arte e della sua scienza.</p>\n\n<p>${LOGO} Le fornirà informazioni dettagliate su quest'area nella sua Avventura numero 3.</p>`,
  "689": "<p>L'avventura che sta per esplorare percorre buona parte del tracciato dell'antica cinta muraria cristiana di Valencia.</p>",
  "690": `<p>Attualmente l'Offerta dei fiori inizia il giorno 17 fino all'alba del 19 marzo, superando i centotrentamila Falleres e Fallers che lasciano la Plaza de la Virgen ricolma di fiori.</p>\n\n<p>${LOGO} Le fornirà informazioni dettagliate su questa festività nella sua Avventura Speciale Fallas.</p>`,
  "691": "<p>Bravo, è appena arrivato alla metà della sua avventura! Continui per la famosa Calle del Hospital. Come indica la sua mappa, continui fino alla fine della via e giri a sinistra. Il nostro famoso Mercato Centrale emerge alla sua destra, sulla sua mappa corrisponde al numero <mark>15</mark>.</p>\n\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "692": "<p>Le abbiamo preparato una curiosità: guardando l'edificio del Municipio, a sinistra si erge un altro edificio monumentale. Sulla facciata, nella sua parte superiore, spicca la statua del grande leone dell'Assic realizzata in bronzo. Simbolo dell'ente assicurativo che occupava l'edificio anticamente.</p>",
  "693": `<p>Proprio alla sinistra di questo edificio se ne erge un altro non meno monumentale.</p>\n\n<p>Edificio modernista di inizio XX secolo. Si distingue per i suoi tre grandi finestroni in corrispondenza dello smusso.</p>\n\n<p>La falegnameria esterna è in legno, con persiane di stile americano nelle aperture, balconi in ferro battuto, ad eccezione del balcone centrale del piano principale, costruito in muratura.</p>\n\n<p>L'edificio è coronato da pinnacoli di ispirazione gotica e merlature di ispirazione modernista.</p>\n\n<p>Nella sua parte superiore mostra l'insegna "LA EQUITATIVA", un'antica compagnia assicurativa oggi scomparsa, che aveva la sua sede in questo edificio.</p>\n\n<p>Sopra l'insegna spicca la dea della giustizia.</p>`,
  "693-B": "<p>Cosa porta la figura in mano? È una bilancia, un libro o forse una penna?</p>",
  "693-C": `<p>Proprio alla sinistra di questo edificio se ne erge un altro non meno monumentale. Sulla sua mappa corrisponde al numero <mark>14</mark>.</p>\n\n<p>Questo è un edificio modernista di inizio XX secolo. Si distingue per i suoi tre grandi finestroni in corrispondenza dello smusso.</p>\n\n<p>La falegnameria esterna è in legno, con persiane di stile americano nelle aperture, balconi in ferro battuto, ad eccezione del balcone centrale del piano principale, costruito in muratura.</p>\n\n<p>L'edificio è coronato da pinnacoli di ispirazione gotica e merlature di ispirazione modernista.</p>\n\n<p>Nella sua parte superiore mostra l'insegna "LA EQUITATIVA", un'antica compagnia assicurativa oggi scomparsa, che aveva la sua sede in questo edificio.</p>\n\n<p>Sopra l'insegna la dea della giustizia.</p>`,
  "694": "<p>Nel corso del percorso, dovrà attraversare la famosa Plaza de la Reina, un recente restauro ha rinnovato una delle piazze più conosciute del centro storico, eliminando il traffico e riformando il parcheggio sotterraneo. Dopo 18 mesi di restauro, la centrale Plaza de la Reina rinasce con una pedonalizzazione di oltre 12.000 metri quadrati, offrendo viste meravigliose della Cattedrale di Valencia.</p>\n\n<p>Osservi attentamente mentre cammina, potrà vedere la pietra calcarea utilizzata nella piazza, la stessa con cui fu costruita la Cattedrale. La pietra calcarea è impiegata tradizionalmente a Valencia perché non assorbe il calore quanto il granito, il che aiuta nelle calde giornate estive.</p>",
  "695": "<p>La sua avventura continua dietro l'angolo, da dove si può vedere la faccia principale del Miguelete e anche la porta Barocca della Cattedrale di Valencia; la terza a essere costruita. Sulla sua mappa corrisponde al numero <mark>13</mark>.</p>\n\n<p>Metta in pausa questa audioguida se lo ritiene necessario, una volta giunto a destinazione si posizioni in un luogo da cui possa vedere la porta barocca nella sua totalità. Grazie.</p>",
  "696": "<p>Non si avvicini troppo alla Mascletà, potrebbe sporcarsi con i coriandoli colorati provenienti dai petardi che esplodono. Si metta con le spalle al vento, in questo modo eviterà il fumo e i coriandoli.</p>",
  "697": "<p>Il riciclaggio è fondamentale nell'era in cui viviamo, per favore utilizzi i contenitori appropriati.</p>",
  "698": "<p>Le Fallas è una tradizione in cui si coinvolgono tutti i tipi di culture, credenze religiose, politiche e sessuali. Il rispetto è fondamentale per fare sì che la sua permanenza durante la festa sia degna di essere ricordata.</p>",
  "699": "<p>Utilizzi il pulsante di pausa a suo piacimento. Quando lo deciderà, semplicemente continui a risolvere le nostre sfide mentre scopre la città. Il suo prossimo obiettivo si trova alla fine della piazza alla sua mano destra. Sulla sua mappa corrisponde al numero <mark>10</mark>.</p>",
  "700": "<p>Si trova già all'edificio delle Poste? Ricordi che corrisponde sulla sua mappa al numero 14.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
