import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "339": `<p>As antigas lendas contam que nos tempos em que Valencia era uma cidade árabe, acreditava-se que se os morcegos voassem sobre a cidade, esta continuaria sempre a ser da sua propriedade.</p>\n<p>Em 1238, ano da Reconquista, foi precisamente um morcego que mudou o curso religioso da cidade. Um curso que perdura até aos nossos dias.</p>\n<p>Durante o cerco à antiga "Balansiya", enquanto o exército do Rei Jaime Primeiro dormia, um grupo inimigo infiltrou-se no acampamento com a intenção de matar o rei.</p>\n<p>A boa fortuna quis que um morcego que voava pelos arredores colidisse com um tambor e acordasse as tropas com o estrondo, ato que evitaria a incursão e conseguiria a tomada da cidade.</p>\n<p>Após esse "milagre" o rei presta homenagem ao animal e simboliza-o no topo do escudo.</p>\n<p>O certo é que os morcegos sempre foram de grande ajuda, como as andorinhas ou os andorinhões, para comer mosquitos e outros insetos voadores, preservando assim o bem-estar dos cidadãos.</p>`,
  "340": `<p>Dirija a sua atenção para a grande porta com verga reta que permite o acesso ao edifício.</p>\n<p>Aproxime-se, se faz favor, à porta principal.</p>`,
  "341": `<p>Uma vez dentro, o primeiro que chama a atenção é a grande escadaria de mármore que dá acesso ao piso superior.</p>\n<p>Durante a guerra civil, de 1936 a 39, esta escadaria foi parcialmente destruída; mais tarde foi reconstruída com o desenho original de 1924.</p>\n<p>O <strong>ayuntamiento de Valencia</strong> alberga no seu interior duas salas importantes: o salão de vidro inaugurado em 1929, uma grande sala com iluminação natural através de vitrais coloridos.</p>\n<p>Também, desde 1927 o Museu Histórico Municipal com peças especialmente emblemáticas tais como a chave árabe que abria a porta principal da cidade, a espada e o escudo do rei Jaime primeiro, e o "Penó de la Conquesta", bandeira que foi içada na torre de Ali Bufat da porta de Bab al-Sakhar a 28 de setembro de 1238, a qual marcava a rendição da cidade muçulmana de Balansiya aos cristãos do rei Jaime primeiro.</p>`,
  "342": `<p>Na parte oposta da praça, aparece um tesouro arquitetónico à mão direita.</p>\n<p>No seu mapa corresponde ao número <mark>29</mark>.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "343": `<p>O <strong>Palácio de Comunicações</strong>, conhecido também como o edifício dos Correios, é desde 1922 o ente encarregado de enviar, receber, ordenar, gerir, transmitir ou entregar o correio, entre muitas outras funções.</p>\n<p>Sobre o telhado sobressai uma torre de 30 metros de altura rematada com um globo terrestre.</p>\n<p>Esta torre foi colocada em 2014 e é uma réplica exata da antiga torre de telecomunicações que se situava no mesmo lugar.</p>\n<p>Pelo interior desta torre percorre uma escada em caracol que permite a subida ao miradouro.</p>\n<p>Por baixo desta torre, no corpo central, dois grupos de seres alados transportam mensagens postais e telegráficas; um dos grupos sobre uma locomotiva e o outro grupo sobre um barco (alegoria à proteção dos mensageiros por terra e mar).</p>`,
  "344": `<p>Sobre a entrada principal, num arco de volta inteira, figuras alegóricas representam os cinco continentes.</p>\n<p>O que porta a figura central? Uma Coroa, Uma Espada ou talvez Uma Tocha?</p>`,
  "345": `<p>Olhando para a fachada dos correios dirija-se à sua mão esquerda, como indica o seu mapa, até à Calle de las Barcas, que é a segunda rua à sua mão direita.</p>\n<p>${LOGO} recomenda-lhe chegar ao próximo ponto de interesse a pé, lembre-se de que deve respeitar a regulamentação de trânsito que, neste caso, o peão tem preferência.</p>\n<p>Não pause esta audioguia e dirija-se ao ponto indicado, obrigado.</p>\n<p>Ânimo, são apenas uns metros! Lembre-se: veja o edifício, vire à sua esquerda e tome a segunda rua à sua direita.</p>`,
  "346": `<p>Se vier em horário de visita, ${LOGO} encoraja-o a fazer uma pausa e escolher um bom local.</p>\n<p>É o lugar perfeito para fazer uma paragem e tirar umas magníficas fotos dos tesouros arquitetónicos que a cidade oferece, e desfrutar de uma bebida típica: Água de Valencia, um cóctel alcoólico à base de Vodka, cava e sumo fresco de laranja. Ou ainda melhor... pode também degustar uma Orxata, o nosso sumo de chufa vegano, sempre acompanhada dos seus queridos Fartons, um bizcocho em forma de barra que há que molhar para que embeba e depois comer. Assim desfrutam os valencianos desta refrescante bebida cultural.</p>\n<p>Lembre-se de que não há pressa, faça o que lhe apetecer e não se pressione; supõe-se que é uma excursão divertida! Pode voltar à sua Aventura quando sentir que é o momento, simplesmente premindo play.</p>`,
  "347": `<p>A Calle de las Barcas recebe este nome porque nesta rua havia uma sucessão de oficinas onde se fabricavam estas pequenas embarcações que posteriormente eram transferidas para o bairro de pescadores.</p>\n<p>Em tempos encheu-se de cafés e tabernas, onde a prostituição e o jogo alarmeavam a população.</p>\n<p>Com o alargamento da <strong>Plaza del Ayuntamiento</strong> em 1891, instalaram-se na zona edifícios emblemáticos como os que verá a seguir.</p>`,
  "348": "<p>Continue até ao final da rua, onde poderá ver a antiga sede central do <strong>Banco de Valencia</strong>.</p>",
  "349": `<p>Apesar de ter um corte clássico com uma composição de chanfro, o edifício inclui elementos típicos valencianos como é a sua cerâmica com motivos florais no sótão e os seus esbeltos miradouros para as ruas laterais.</p>\n<p>A base do edifício, de dois andares de altura, define-se mediante a combinação de mármores de duas cores e uma série de colunas clássicas que suportam a gradeamento e inclui elementos dourados, oferecendo a imagem de proteção buscada pelo Banco.</p>\n<p>A antiga sede central do <strong>Banco de Valencia</strong> é um tesouro arquitetónico essencial nesta aventura.</p>`,
  "350": "<p>Quantos andares tem o edifício?</p>",
  "351": `<p>Admirando esta fachada, continue com a sua aventura tal como indica o seu mapa, na rua que se abre à sua esquerda até ao próximo ponto de interesse.</p>\n<p>Não pause esta audioguia e dirija-se ao local recomendado.</p>\n<p>Lembre-se de respeitar a regulamentação de trânsito. Obrigado.</p>`,
  "352": `<p>No caminho, entre a modernidade dos edifícios, destaca uma das dez paróquias fundacionais da cidade.</p>\n<p>Como curiosidade diremos que a Igreja de São João da Cruz ficou em estado lamentável durante a Guerra Civil Espanhola ocorrida entre 1936 e 1939.</p>\n<p>O templo foi saqueado destruindo, à passagem dos saqueadores, as suas obras de arte e o seu retábulo.</p>\n<p>Os ocupantes também aproveitaram o espaço como armazém de balística pesada.</p>`,
  "353": `<p>Uma vez que chegue à igreja centre a sua atenção, se faz favor, nas colunas de estilo Salomónico da porta com verga reta. Pois ofereceremos mais informação ao longo desta Aventura, e este é um local para as ver em detalhe.</p>\n<p>Pause esta audioguia se o considerar conveniente.</p>`,
  "354": `<p>Já chegou ao ponto de interesse? Ainda não? Esperamos que esta breve história lhe torne a viagem mais agradável.</p>\n<p>Cabe destacar que no ano 1496 o Marquês de Rabassa de Perellós adquiriu o título de Barão de Dois Rios por uma quantia avultada, sendo o Baronato elevado a Marquesado em 1699.</p>\n<p>Durante três séculos a família Rabassa de Perellós ocupou altos cargos na governação política, enquanto acumulava dotes e heranças através de alianças matrimoniais.</p>\n<p>Este edifício sofreu, durante a sua transição, ostentosas modificações como mostra de poder e linhagem.</p>\n<p>Hoje em dia alberga o Museu Nacional de Cerâmica.</p>\n<p>Por favor, situe-se frente à Porta principal de entrada que fica a dobrar a esquina.</p>\n<p>Pause esta audioguia se o considerar conveniente.</p>`,
  "355": `<p>Admire a Catedral de cima abaixo e poderá contemplar três galerias sobrepostas formadas por vãos com arcos de volta inteira.</p>\n<p>Realizadas em 1566 com um estilo Renascentista; trata-se de uma tribuna-miradouro conhecida como "Obra Nova" destinada à contemplação de procissões e atos públicos desde a própria Catedral.</p>`,
  "356": `<p>A composição desta portada data do séc. XVIII.</p>\n<p>Nela observamos uma imagem da Virgem do Rosário de que descem dois caudais de água junto a dois atlantes que representam os dois rios mais caudalosos de Valencia, o Turia e o Júcar fazendo clara referência ao nome do marquesado.</p>\n<p>Aos pés da Virgem podemos observar duas matronas ajoelhadas, uma com uma cornucópia da qual se derramam frutos (Alegoria de agricultura e prosperidade) e outra com um jarro aos seus pés repleto de moedas (Alegoria de justiça e magnanimidade).</p>\n<p>É no séc. XIX, quando o herdeiro dos marqueses realiza uma segunda e espetacular reforma baseada principalmente na decoração do interior.</p>\n<p>Embora também modifique o exterior do Palácio combinando o estilo rococó com motivos chineses e afrancesados da época como são: o uso de grades em janelas e varandas ou as enormes armaduras que sobressaem da fachada, dando-lhe o seu aspeto atual.</p>`,
  "357": `<p>No seu interior ainda podemos observar carruagens do séc. XVIII assim como os salões do século XIX, enquanto que o segundo andar alberga o museu de cerâmica.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e visite este complexo histórico ao seu próprio ritmo. Pode retomar a sua aventura uma vez o entender conveniente.</p>`,
  "358": `<p>Situe-se com a fachada principal do Palácio à sua mão esquerda e continue até ao final da rua.</p>\n<p>Chegará de novo à famosa Calle San Vicente Mártir.</p>\n<p>O traçado desta via mantém-se imperturbável desde o século quatro depois de Cristo.</p>\n<p>A Calle San Vicente Mártir é hoje em dia uma das vias mais longas da cidade.</p>\n<p>Nesta rua dedicada ao Santo Padroeiro de Valencia, vire à esquerda e continue a sua procura do tesouro até ao final da rua.</p>`,
  "359": `<p>Tome como referência a <strong>Plaza del Ayuntamiento</strong> que corresponde ao número <mark>27</mark> do seu mapa, mas desta vez vire à direita.</p>`,
  "359-B": "<p>Tome como referência, de novo, a mesma bifurcação de antes, mas desta vez vire à direita.</p>",
  "360": `<p>A apenas 150 metros, mesmo na praça seguinte, monumentos de épocas diferentes fundem-se no presente fazendo parte das nossas vidas.</p>\n<p>A sua procura do tesouro leva-o a começar pelo edifício monumental da esquerda.</p>`,
  "361": "<p>Imagine que está numa época passada!</p>",
  "362": `<p>Este monumento dedicado ao comércio foi edificado no local que ocupava o mercado ao ar livre que existia desde 1839, chamando-se já desde esses tempos o <strong>Mercado Central</strong>, que por sua vez se ergueu sobre o antigo mercado ou souk muçulmano situado fora das suas muralhas.</p>\n<p>O <strong>Mercado Central</strong> que podemos ver hoje em dia, inaugurado em 1928, está situado num edifício de estilo modernista, no qual a cerâmica, o ferro, a pedra e as amplas vidreiras e cúpulas adornam interior e exterior.</p>\n<p>Olhando para a totalidade do edifício, destaca numa das suas cúpulas um catavento com forma de papagaio.</p>`,
  "363": `<p>Conta a lenda que faz alusão às fofocas que sempre foram habituais nos mercados e por isso é apelidada "a <strong>Cotorra del Mercado</strong>".</p>`,
  "364": `<p>Sendo um edifício de estilo moderno, o Mercado integra-se perfeitamente com os outros dois monumentos importantes da praça: a Igreja de São João do Mercado e a <strong>Lonja</strong>, ambos pontos icónicos da Valencia do séc. XV.</p>\n<p>Procure o vitral com as cores da Senyera valenciana na fachada do edifício. Saberia determinar que forma tem? Quadrangular, Redonda ou Triangular?</p>`,
  "365": `<p>Conhecida como Igreja de São João do Mercado, é outro claro exemplo de paróquia erguida sobre uma Mesquita Árabe.</p>\n<p>Um incêndio grave no ano 1300 depois de Cristo obrigou a reconstruí-la praticamente desde os seus escombros.</p>\n<p>Séculos mais tarde, outro incêndio foi a causa de uma nova reconstrução dando-lhe a sua fisionomia Gótica atual, permitindo manter parte do seu Barroco original.</p>\n<p>Em 1936, durante a Guerra Civil, um terceiro incêndio assolou a igreja e os seus efeitos foram reparados no primeiro quarto do séc. XXI.</p>`,
  "366": `<p>Entre a sua ornamentação exterior destaca um grande retábulo de pedra da Virgem do Rosário.</p>\n<p>O que sustém a Virgem na sua mão? Um rosário? Uma criança? Talvez uma coroa?</p>`,
  "367": "<p>O que entrega o anjo à criança? É uma pomba? Talvez um orbe? Ou talvez sejam alimentos?</p>",
  "368": `<p>Um nome menos conhecido para este templo é a "Igreja dos malandros", porque antigamente este era o local escolhido pelas crianças que, devido às circunstâncias da época, se dedicavam a fazer traquinices e cometiam pequenos furtos a transeuntes do mercado. Imagine carteiristas da idade média. Será esta uma profissão histórica?</p>`,
  "369": "<p>Admirando este edifício, o próximo ponto de interesse fica às suas costas, simplesmente vire-se.</p>",
  "370": `<p>A <strong>Lonja de la Seda</strong> é o monumento do Século de Ouro valenciano.</p>\n<p>Em tempos, a <strong>Lonja de Valencia</strong> foi uma Wall Street do séc. XV.</p>\n<p>O monumento foi construído entre 1482 e 1497 e foi declarado Património da Humanidade em 1996.</p>\n<p>Este edifício financeiro começou como <strong>Lonja de la Seda</strong> uma vez que a famosa "Rota da Seda", uma rota comercial que começava em África e terminava na China ou na Índia, passava por Valencia.</p>\n<p>Como aporte diremos que na famosa rota se comercializava também com outros materiais tais como especiarias, porcelana, ferro ou chá, mas para além do seu propósito comercial, a Rota da Seda era também um espaço de troca de ideias e conhecimentos.</p>\n<p>A superfície do monumento adapta-se a um solar retangular e supera os 2.000 metros quadrados.</p>\n<p>A sua face sul mira para a Plaza del Mercado onde se encontra agora mesmo.</p>\n<p>A fachada este dá para a rua de Pere Compte, mestre construtor do monumento.</p>\n<p>A face oeste mira para a rua dos Cordellats onde se pode vislumbrar o pátio das laranjeiras.</p>`,
  "371": "<p>E finalmente, a face norte para a rua da <strong>Lonja</strong> e a sua próxima direção nesta aventura.</p>",
  "372": "<p>Desde a sua posição distinguem-se quatro partes: À direita a Sala de Contratação ou Salão Columnário onde se levavam a cabo as transações.</p>",
  "373": "<p>No centro a Torre de três corpos utilizados para capela (o piso de baixo) e para prisão (os dois pisos superiores) na qual eram retidos os ladrões e mercadores e comerciantes pouco honestos até que as autoridades vinham responsabilizar-se deles.</p>",
  "374": "<p>À sua esquerda a Sala do Consulado do Mar (1498-1548) construída a posteriori com o fim de se ocupar e julgar os assuntos marítimos e mercantis, sendo este o primeiro tribunal mercantil que se fundou em Espanha.</p>",
  "375": `<p>Propomos-lhe, desde este ponto, fazer juntos uma visita no tempo à <strong>Lonja de Valencia</strong> através das suas esculturas.</p>\n<p>Esta atividade consiste em aperceber-se da expressividade e originalidade dos seus pórticos e gárgulas talhadas pelos canteiros do séc. XV:</p>`,
  "376": `<p>A imagem de uns anjos sustendo um escudo, num dos ângulos exteriores do monumento, sinal heráldico e celestial muito distante das demais figuras, é provavelmente o mais inocente que encontrará nos muros da <strong>Lonja</strong> de la Seda.</p>`,
  "377": `<p>Situe-se ante o que foi o pórtico principal de entrada, chamado a Porta dos Pecados, fica à direita da fachada que tem diante de si agora mesmo.</p>\n<p>Requer que lhe preste uma atenção especial e saiba ler "nas entrelinhas" as suas numerosas mensagens sobre a escuridão do pecado e portanto do mal.</p>\n<p>Nesta portada é fácil encontrar centenas de figuras demoníacas; monstros, criaturas devoradas pelo mal, feitiços, humanos assustados pela luxúria e os pecados capitais, evidências do erotismo com um marcado acento perverso e lascivo; portanto, cenas que nos levam ao obscurantismo predominante nesta construção civil.</p>`,
  "378": `<p>No séc. XV, muitos comerciantes, assim como a maioria dos cidadãos de classe baixa, não sabiam ler nem escrever; de modo que interpretavam as figuras como guia para prevenir o pecado.</p>\n<p>Não há que esquecer que, na Capital do Turia, se situava um dos maiores bordéis de toda a Europa. Por isso, em sinal de proteção, coroam a porta a Virgem com o menino.</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
