import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "520": "<p>De nieuwe christelijke stad omringde de Arabische met een muur van 4 kilometer en isoleerde de bekeerde moslims in een getto binnen haar muren.</p>\n<p>De Mudéjares, of zoals ze in Valencia werden genoemd, Sarraïns, waren moslims die in ruil voor een hoge belasting trouw aan hun geloof bleven leven.</p>\n<p>Het is vermeldenswaard dat in de stad Valencia de drie Abrahamitische godsdiensten naast elkaar bestonden: de christelijke, de islamitische en de joodse.</p>\n<p>Ondanks de verschillende religieuze overtuigingen was het gebruikelijk een beleid van akkoorden en erkenningen te voeren ten behoeve van de vooruitgang van de stad.</p>",
  "521": "<p>Bekijk uw kaart goed! Uw doel is de bekende <strong>Calle de los Serranos</strong>, de plek waar uw avontuur begon. Pauzeer deze audiogids niet.</p>\n<p>Stel u op terwijl u de Moorse toren bewondert en neem de straat rechts, om dan onmiddellijk links af te slaan en vervolgens rechts.</p>\n<p>De route lijkt een beetje kronkelig, dat weten we, maar dat heeft een verklaring.</p>",
  "522": "<p>De plattegrond van islamitische steden is zeer complex; er is nauwelijks onderscheid tussen hoofd- en zijstraten.</p>\n<p>Hun manier van stedelijke planning is: eerst de huizen en dan de straten, in tegenstelling tot het Romeinse systeem dat eerst de straten en dan de huizen aanlegde.</p>\n<p>Dientengevolge wordt het onregelmatige straatpatroon gevormd door huizen die zich uitbreiden en de aangrenzende straten bezetten, het tracé wijzigen, zelfs straten afsnijden en doodlopende steegjes creëren.</p>",
  "523": "<p>Eenmaal op de <strong>Calle de los Serranos</strong>, ga naar de torens waar uw Avontuur begon.</p>\n<p>Let onderweg aan uw linkerzijde goed op, want het gebouw is zeer bescheiden en kan gemakkelijk over het hoofd worden gezien.</p>\n<p>De oude bunker van Valencia correspondeert met nummer <mark>52</mark> op uw kaart.</p>\n<p>Druk op pauze, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "524": "<p>Dit monument, tegenwoordig te bezoeken, was een van de eerste burgerlijke schuilplaatsen die werden gebouwd tijdens de Spaanse Burgeroorlog, die plaatsvond van 1936 tot 1939.</p>\n<p>Door de militaire ontwikkeling waren luchtbeschermingsbunkers essentieel om de bevolking te beschermen tegen de aanvallen en bombardementen van de vijand.</p>\n<p>Deze in het bijzonder werd gebouwd in 1937, het jaar waarin Valencia de hoofdstad was van de Spaanse republiek.</p>\n<p>De oude oorlogsbunker kon ongeveer 400 mensen in zijn interieur herbergen.</p>\n<p>In deze ruimte die het leven van veel Valencianen redde, bevindt zich tegenwoordig een museum dat ons een grote collectie artefacten uit die tijd laat zien, alsook de ontwikkeling via foto's die laten zien hoe het dagelijkse leven eruitzag tussen bombardementen en ellende.</p>\n<p>Al deze historische gegevens en manuscripten weerspiegelen hoe Valencia er na het verlies van duizenden levens en de verwoesting van een deel van haar historische monumenten uitzag aan het einde van de Burgeroorlog.</p>",
  "525": `<p>Vouw uw kaart open en u ziet dat hij aangeeft het derde pad te nemen dat aan uw linkerzijde vertrekt.</p>\n<p>Slechts enkele meters in die straat verschijnt uw volgende bezienswaardige punt in deze Schattenjacht. Op uw kaart correspondeert dit met nummer <mark>53</mark>.</p>\n<p>${LOGO} raadt u aan het volgende bezienswaardige punt te voet te bereiken; vergeet niet dat u de verkeersregels moet respecteren waarbij de voetganger in dit geval voorrang heeft. Kom op, het zijn maar een paar meter!</p>\n<p>Pauzeer deze audiogids niet en ga naar het aangegeven punt. Dank u.</p>\n<p>Vergeet niet: ga verder naar de torens en neem het derde pad dat aan uw linkerzijde vertrekt.</p>`,
  "525-B": `<p>Draai vanuit uw positie om en laat de torens achter u. Met de torens in uw rug, bekijk uw kaart, die aangeeft het pad te nemen dat aan uw rechterzijde vertrekt.</p>\n<p>Slechts enkele meters in die straat verschijnt uw volgende bezienswaardige punt in deze Schattenjacht. Op uw kaart correspondeert dit met nummer <mark>2</mark>.</p>\n<p>${LOGO} raadt u aan het volgende bezienswaardige punt te voet te bereiken; vergeet niet dat u de verkeersregels moet respecteren waarbij de voetganger in dit geval voorrang heeft.</p>\n<p>Kom op, het zijn maar een paar meter!</p>\n<p>Pauzeer deze audiogids niet en ga naar het aangegeven punt. Dank u.</p>`,
  "526": `<p>Recycling is een essentiële praktijk en we moeten het belang ervan uitbreiden naar het virtuele domein. Door deze intelligente aanpak te omarmen, kunnen we bijdragen aan een duurzaam beheer van cloudmiddelen, de weg vrijmakend voor een lichtere en duurzamere digitale voetafdruk. Vanuit ${LOGO} danken we u voor het aanschaffen van dit Avontuur en verwelkomen we u spoedig voor meer plezier!</p>`,
  "527": "<p>Het Corpus Christi is het katholieke feest ter viering van de Eucharistie; daarin wordt het sacrament van het brood en de wijn gevierd en wordt een bijzondere herinnering gewijd aan de dood en de verrijzenis van Jezus.</p>\n<p>Het voornaamste doel is het geloof van de gelovigen te proclameren en te versterken.</p>\n<p>Buiten de puur katholieke betekenis is het Corpus Christi voor de Valenciaanse samenleving een blijk van de coëxistentie van de feeststemming en de religieuze geest.</p>\n<p>De stad brengt hulde 60 dagen na Paaszondag in de zogenoemde Fiesta Grande.</p>",
  "528": "<p>De straten worden versierd met bloemenpaden en verschillende comparsas voeren kleurrijke traditionele en allegorische dansen uit op de klanken van de Dolçaina en de Tabalet, traditionele Valenciaanse instrumenten die deel uitmaken van de geluidsband van onze audiogidsen.</p>\n<p>De beroemdste dans is de strijd waarbij de Moma, onze hoofdactrice, het opneemt tegen de zeven hoofdzonden.</p>\n<p>Ze is herkenbaar aan haar witte tuniek en een witte sjaal die haar gezicht volledig bedekt.</p>",
  "529": "<p>Ook belangrijk tijdens dit feest zijn de zeven Momos, gekleed met een zwart masker, een geel-zwart kostuum en een kenmerkende muts die een draak voorstelt.</p>\n<p>Zij voeren een pittoreske Stokdans uit terwijl ze zich buigen voor de deugden van de Moma.</p>\n<p>In sommige plaatsen gooien mensen water van de balkons en nodigen de toeschouwers uit deel te nemen aan de viering.</p>",
  "530": "<p>Het Museo de las Rocas herbergt de historische Rocas del Corpus Christi: dit zijn de triomfwagens die bijbelse thema's verbeelden die, door paarden getrokken, elk jaar de processie sieren.</p>\n<p>Vanuit dit museum begint de processie van de elf triomfwagens gedateerd tussen 1528 en 2001.</p>\n<p>De elf houten structuren, in de vorm van een oud schip, vervoeren allegorische beeldhouwgroepen gewijd aan de Heiligen van de godsdienst.</p>",
  "531": "<p>In het interieur van het gebouw zijn, naast de prachtige houten structuren, ook de kostuums te zien van de eerder genoemde Moma en Momos, en ook die van de Reuzen en Dikkoppen die ronddansen tijdens het feest.</p>\n<p>Dit punt dat in 2017 de status van Museum verkreeg, bevat ook een verzameling foto's van het Corpus vanaf de 19e eeuw.</p>",
  "532": "<p>De Casa de las Rocas werd gebouwd tussen 1435 en 1447 op bevel van Koning Pedro Vierde, de Plechtige genaamd.</p>\n<p>Door de nabijheid van de rivier heeft het talrijke overstromingen geleden bij elke rivieroverschrijding; dit zorgde ervoor dat het huis voortdurend achteruitging.</p>\n<p>Gelukkig werd dit opgelost na de omleiding van de rivier die het prachtige park opleverde dat we in dit Avontuur zullen blijven bewonderen.</p>\n<p>Dit oude herenhuis van twee verdiepingen was bovendien de woning van de Kapelaan van de Rocas, die verantwoordelijk was voor het bewaken ervan.</p>\n<p>Het huis wordt betreden via een hoge overluifelde deur, waarvan het bovenste deel een driehoekig fronton heeft. In het interieur is een binnenplaats te vinden gedekt door een dakconstructie van houten balken.</p>\n<p>Na de restauratie in 1980 werd op de bovenste verdieping een groot balkon toegevoegd dat uitkijkt op de binnenplaats.</p>\n<p>Jaren later werden na de welverdiende museografische renovatie verklarende panelen, audiovisuele schermen en de indeling en benaming van de verschillende zalen opgenomen.</p>",
  "533": "<p>Merk op dat uw kaart aangeeft de straat te blijven volgen; onderweg kunt u zien dat de balkons van de eerste verdieping merkbaar smaller zijn dan die van de overige bovenverdiepingen. Waarom zou dat zijn? Bovendien zijn sommige nog steeds versierd met traditioneel Valenciaans keramiek.</p>\n<p>Uw volgende bezienswaardige punt is het portaal van een Barokke kerk dat aan uw rechterzijde in de straat zelf staat.</p>",
  "534": "<p>De <strong>Parroquia de la Santísima Cruz</strong>, populair bekend als de «Iglesia del Carmen», werd in 1983 uitgeroepen tot Nationaal Historisch-Artistiek Monument.</p>\n<p>Maar deze kerk heeft een veel ouder verleden.</p>",
  "535": "<p>De Iglesia del Carmen had haar beginnen in het jaar 1280. In die tijd stond op deze plek een bescheiden huis met tuin dat de Karmelieten Orde bestuurde. Dit zou de oorsprong zijn van het toekomstige Karmelietenklooster.</p>\n<p>Na een eerste uitbreiding werd de eerste kerk gewijd in 1343 en heeft sindsdien geleidelijke verbouwingen ondergaan.</p>\n<p>Een gotische kloostergang met spitsbogen, de grote refter of eetzaal van de monniken en de kapittelzaal zijn duidelijke voorbeelden die bewaard zijn gebleven van het middeleeuwse verleden.</p>\n<p>In 1555 werd het koorhoofd, of de altaarzone, verbouwd met het traditionele bouwsysteem van het stergewelf.</p>\n<p>Later werd een tweede Renaissance-kloostergang gebouwd, maar de meest zichtbare elementen behoren al tot de Barokke periode.</p>\n<p>In 1613 begonnen de bouwwerkzaamheden van het facade-altaarstuk van het kerkgebouw en in 1628 werd een nieuwe verbouwing uitgevoerd die bijna 30 jaar duurde waarbij het interieur werd vernieuwd naar de barokke smaak van die tijd (1655).</p>\n<p>Richt uw aandacht op de hoofdgevel.</p>\n<p>Deze extravagante gevel wordt beschouwd als een van de beste maniëristische altaarstukken van de stad.</p>",
  "536": "<p>Het Maniërisme is een artistieke stijl die aan het einde van de 16e eeuw werd toegepast en zich richtte op de verstoring van de orde in de architecturale elementen, neigende naar onwerkelijkheid.</p>\n<p>Het altaarstuk van de gevel die voor u staat werd in twee fasen uitgevoerd.</p>\n<p>De eerste, van klassieke snit, correspondeert aan het onderste lichaam en werd uitgevoerd tijdens de eerste helft van de 17e eeuw.</p>\n<p>Observeer de gegroefde Ionische zuilen die aan beide zijden van de deur opstijgen boven de stenen sokkels.</p>",
  "537": "<p>De deur heeft op haar beurt aan elke zijde een nis waar de beelden zijn ondergebracht van San Simón Stock, een Engelse kluizenaar en Karmelietenbroeder, en van San Juan de la Cruz, Patroon van de dichters in de Spaanse taal en een van de 36 Kerkvaders.</p>",
  "538": "<p>Boven het bovendorpel van de deur springt het wapen van de Karmelieten Orde in het oog.</p>\n<p>Wat bekroont het wapen? Een kroon? Een kruis? Of misschien een ster?</p>",
  "539": "<p>De tweede fase die de twee bovenste lichamen omvat, veel rijker versierd dan het onderste, werd gebouwd in de 18e eeuw.</p>\n<p>Merk op dat in het tweede lichaam drie nissen zijn geopend met drie vrouwenfiguren; deze stellen de Heilige Teresa van Jezus voor, een van de stichtende nonnen van de Discalced Carmelites Orde, en de Heilige Maria Magdalena de' Pazzi, een Toscaanse adelsvrouw en Karmelietennon.</p>",
  "540": "<p>De derde nis, de meest versierde, herbergt de Virgen del Carmen, die dit kerkgebouw zijn naam geeft.</p>\n<p>Wat draagt de Maagd in haar armen? Een hart? Een duif? Of draagt ze misschien het kind Jezus?</p>",
  "541": "<p>Hoger, in het derde lichaam, opent zich een opening geflankeerd door twee Salomonskolommen.</p>\n<p>De zuilen kregen deze naam naar de toenmalige overtuiging dat de zuilen van de Tempel van Salomo er zo uitzagen.</p>\n<p>Het beeld stelt de heilige Jozef voor met het kind in zijn armen; net als de drie beelden onderaan dateert het ook uit de 18e eeuw.</p>",
  "542": "<p>Uw avontuur gaat enkele meters verder in dezelfde straat; we blijven u dan ook aanraden het volgende bezienswaardige punt te voet te bereiken.</p>\n<p>Gelieve deze audiogids niet te stoppen en ga naar uw volgende bestemming.</p>",
  "543": "<p>Het Karmelietenklooster heeft zijn oorsprong in 1281, na de dood van Koning Jaime Eerste, toen de Geschoeide Karmelieten zich in Valencia vestigden.</p>",
  "544": "<p>Bevorderd door Pater Arnaldo de Bascher, vestigden de Karmelieten zich in de <strong>Barrio de Roteros</strong>, dat in die tijd buiten de muren van de oude Arabische stadsmuren lag.</p>",
  "544-B": "<p>Bevorderd door Pater Arnaldo de Bascher, vestigden de Karmelieten zich in de <strong>Barrio de Roteros</strong>, dat in die tijd buiten de muren van de oude Arabische stadsmuren lag, waarover uitgebreider wordt gesproken in ons Avontuur nummer 2.</p>",
  "545": "<p>Als u uw aandacht op de gevel richt, kunt u nog steeds een keramisch paneel zien dat dateert van 1779 waarop de Heilige Teresa van Jezus is afgebeeld.</p>\n<p>Zoals u kunt zien, draagt de Heilige het habijt van de Karmelieten Orde.</p>\n<p>Maar deze Heilige draagt geen kroon; in plaats daarvan draagt ze een baret, aangezien ze Kerklerares is.</p>",
  "546": "<p>Wat draagt de Heilige Teresa in haar handen? Een veer en een boek? Misschien een zwaard? Of wellicht een waterkruik?</p>",
  "547": "<p>Het oude klooster, tegenwoordig te bezoeken, kreeg de naam Real Monasterio de la Madre de Dios del Carmen. Het is georganiseerd rondom twee kloostergangen: de oudste in gotische stijl uit de 14e en 15e eeuw en de tweede, uit de Renaissance-periode, de 16e en 17e eeuw.</p>\n<p>In het interieur van de gotische kloostergang staan aan elk van de vier vlakken vier spitsbogen gedekt door een kruisribgewelf.</p>\n<p>Als aanvulling: als u uw aandacht richt op het einde van de bogen, op de consoles van de zuilen, ziet u in steen uitgehakte details; zoals heraldische schilden vastgehouden door engelen, maar ook monsterlijke dieren.</p>\n<p>In het interieur van de kloostergang, aan de rechterzijde, is nog steeds op de muur geschilderd de kosten van de renovatie van de kloostergang van 1670; de tijd waarin de biechtstoelen werden afgeschaft.</p>",
  "548": "<p>In 1839 hield het klooster op als zodanig te functioneren. Vanaf 1848 werden de zetels van de School voor Schone Kunsten en de School voor Kunstambachten gevestigd.</p>\n<p>De ruimte diende tevens als opslagplaats en tentoonstellingsruimte voor verschillende kunstenaars van die tijd. Deze werken creëerden de eerste zetel van het <strong>Museo de Bellas Artes</strong> van Valencia.</p>\n<p>Het gebouw werd in 1983 uitgeroepen tot Nationaal Historisch-Artistiek erfgoed. In 1989 begon een restauratie waarbij de ruimte kon worden aangepast om een tijdelijke tentoonstellingsruimte onder het <strong>Museo de Bellas Artes</strong> te huisvesten, maar die werkzaamheden duurden meer dan 10 jaar; concreet tot het jaar 2011.</p>",
  "549": `<p>Tijdens de restauratiewerkzaamheden kwamen talrijke archeologische resten tevoorschijn in de ondergrond van het klooster.</p>\n<p>Een van de opvallendste zijn de overblijfselen van een islamitische woning, die zichtbaar blijft dankzij een glazen paneel dat dit door de stadsgeschiedenis aangeboden juweel laat zien.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en te genieten van deze tentoonstellingsruimte.</p>`,
  "550": "<p>Hoeveel kost de toegang tot dit museum?</p>",
  "551": "<p>Uw Avontuur gaat enkele meters verder; het is een merkwaardige halte want dit is werkelijk een Valenciaans cultureel juweel.</p>\n<p>Volg de loop van de straat. Aan het einde, aan uw linkerhand, bevindt zich het beroemde <strong>Casa de los Gatos</strong>.</p>",
  "552": "<p>Op de gevel springt een typische recreatie van een Valenciaans huis in het oog dat dient als ingang voor het toevluchtsoord dat de katten van de buurt herbergt.</p>\n<p>Vroeger hielden de katten de stad vrij van ratten die allerlei ziekten overbrengen.</p>\n<p>Tegenwoordig zijn er in Valencia kattenkolonies verspreid over de hele stad. In de loop van dit Avontuur passeert u er enkele, maar uit respect voor het welzijn en de rust van de dieren noemen we er alleen deze.</p>\n<p>Druk op pauze, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "553": "<p>Merkwaardig, nietwaar? Een recreatie van een typisch Valenciaans huis dat dient als ingang voor de katten van de <strong>Barrio del Carmen</strong>.</p>\n<p>Het <strong>Casa de los Gatos</strong> werd in 2003 officieel herbouwd; desondanks is bekend dat de katten dit perceel al sinds 1904 bezetten.</p>\n<p>Richt uw aandacht op de kleine keramische plaquette aan de rechterzijde van de deur.</p>",
  "554": "<p>Hoeveel katten zijn er afgebeeld op het paneel?</p>",
  "555": "<p>In het oude islamitische Balansiya werden katten vereerd.</p>\n<p>De overlevering vertelt dat zelfs Mohammed een stuk van zijn tuniek afsneed om zijn poes die naast hem in slaap was gevallen niet wakker te maken.</p>\n<p>Zo groot was de verering dat ze als pure wezens werden beschouwd.</p>\n<p>Deze afbeelding verwijst naar de 4 katten die de verovering door Rodrigo Díaz de Vivar, beter bekend als El Cid Campeador, overleefden.</p>\n<p>Oude volksverhalen vertellen dat de vernietiging van de katten te wijten was aan de christelijke overtuiging dat de kat een wezen uit de andere wereld was, duivels, en ook drager van ongeluk.</p>\n<p>Maar we kunnen niet anders dan denken dat in tijden van hongersnood en vooral na een beleg, mensen aten wat ze konden om te overleven.</p>\n<p>De tekst op het paneel luidt: «Ter herdenking van de vier katten die in de <strong>Barrio del Carmen</strong> leefden in het jaar 1094. Nooit werd de ene miauw luider gehoord dan de andere».</p>",
  "556": "<p>De beeldhouwer Alfonso Yuste Navarro, auteur van de recreatie van deze gevel van drie verdiepingen in typisch Valenciaanse architectuur, heeft alle details opgenomen: het heraldische wapen in het bovendorpel van de deur en het bord van de brandverzekeraar, onder andere.</p>\n<p>Het huis heeft een toegang tot een oude schuur aangebouwd, die in werkelijkheid een plantenbak is.</p>",
  "557": "<p>Richt uw aandacht, als u zo vriendelijk wilt zijn, op de twee keramische panelen die aan uw rechterzijde staan, iets boven uw hoofdhoogte.</p>",
  "558": "<p>Het laagste geeft het niveau aan dat het water bereikte bij de overstroming van 1957.</p>\n<p>Welke hoogte geeft dit paneel aan?</p>",
  "559": "<p>Het bovenste paneel geeft de geschatte zeespiegel in toekomstige jaren aan, vanwege de voortdurende evolutie van de klimaatverandering. Welk jaar geeft het bovenste paneel aan?</p>",
  "560": "<p>Bravo, u heeft zojuist het midden van uw avontuur bereikt!</p>",
  "561": `<p>Bekijk de route op uw kaart. Aan het einde van de straat waar u zich bevindt, neem de eerste links en onmiddellijk daarna de eerste rechts.</p>\n<p>Vanaf dat moment raadt ${LOGO} u aan gebruik te maken van uw persoonlijk vervoermiddel met te allen tijde respect voor de verkeerstekens.</p>`,
  "562": "<p>Observeer het tracé van de straat waar u zich bevindt en probeer de versterkte stad te stellen... De muren strekten zich uit aan de linker- en rechterzijde van elke verdedigingstoren.</p>\n<p>De muur werd begonnen in 1356 en heeft een perimeter van ongeveer 4 kilometer. In de 19e eeuw moest de stadsmuur vanwege de stadsuitbreiding worden gesloopt om de gezondheid te verbeteren, want hij verstikte de bevolking en verhinderde de bouw van de nieuwe en noodzakelijke uitbreidingswijken.</p>\n<p>Concreet werd de sloop uitgevoerd op 20 februari 1865.</p>\n<p>Ondanks de jaren is het tracé vandaag nog waarneembaar.</p>\n<p>In de inleiding van dit Avontuur vermeldden we dat in Valencia nog 2 van de torens te zien zijn die de toegangen tot de stad verdedigden.</p>\n<p>De eerste is het vertrekpunt van uw avontuur. De tweede bevindt zich langs het tracé van de oude stadsmuur in de tegenovergestelde richting.</p>",
  "562-B": `<p>De beroemde <strong>Torres de Quart</strong>, naast toegangspoort tot de stad, dienden in hun geschiedenis voor verschillende doeleinden: in 1562 waren ze een krutopslag en in 1626 werd een van de torens bestemd als gevangenis voor prostituees. ${LOGO} zal u gedetailleerde informatie geven over dat gebied in Avontuur nummer 5.</p>`,
  "563": "<p>Aan uw linkerzijde doemt het <strong>Instituto Valenciano de Arte Moderno</strong> (IVAM) op, opgericht eind 1986, met twee ruimtes voor zijn tentoonstellingen. Op uw kaart correspondeert dit met nummer <mark>57</mark>.</p>",
  "563-B": "<p>Aan uw rechterzijde doemt het <strong>Instituto Valenciano de Arte Moderno</strong> (IVAM) op, opgericht eind 1986, met twee ruimtes voor zijn tentoonstellingen. Op uw kaart correspondeert dit met nummer <mark>21</mark>.</p>",
  "563-C": `<p>Aan uw linkerzijde doemt het <strong>Instituto Valenciano de Arte Moderno</strong> (IVAM) op, opgericht eind 1986, met twee ruimtes voor zijn tentoonstellingen.</p>\n<p>De collectie bestaat uit ongeveer 10.500 werken die de basale artistieke uitingen van de kunst van de 20e eeuw illustreren.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit museum te betreden en te genieten van de tentoonstellingen.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht. Druk simpelweg op de bijbehorende knop en ga verder <i>op zoek naar de schat</i>.</p>`,
  "564": "<p>Keer terug naar het originele tracé van de stadsmuren en ga naar uw rechterzijde. Enkele meters verder doemt het laatste bezienswaardige punt in dit Avontuur op.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "565": "<p>Hoewel het Prehistoriemuseum tegenwoordig meer dan 80 jaar oud is, werd zijn huidige locatie in 1982 gerealiseerd.</p>\n<p>Daarvoor werd het oude Casa de la Beneficencia gebruikt, waarbij het Valenciaans Etnologisch Museum in dezelfde ruimte werd opgenomen.</p>\n<p>In 1995 werden de huidige zalen voor Prehistorie, Iberische Cultuur en de Romeinse Wereld voor het publiek geopend. In het museum worden ook educatieve workshops georganiseerd; het museum beperkt zich dus niet tot zijn zalen, maar strekt zich ook uit tot de archeologische opgravingen die in uitvoering zijn.</p>",
  "566": `<p>Aangezien Etnologie de wetenschap is die volkeren en hun culturen in al hun aspecten en relaties bestudeert, verzamelt het Valenciaans Etnologisch Museum studies die de relatie tussen mensen en hun omgeving definiëren.</p>\n<p>Zoals, bij voorbeeld: het bewonen van de huiselijke ruimte, het samenleven in ontmoetingsruimtes, en de werkomgeving op de werkplek.</p>\n<p>Het Museum ontwikkelt ook onderzoeksprogramma's, biedt de diensten van een gespecialiseerde bibliotheek aan en werkt samen met tal van gemeenten bij het herstel en de verspreiding van het lokale erfgoed.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit monument te betreden om de geschiedenis van de stad en haar gebruiken beter te leren kennen.</p>`,
  "567": "<p>Slechts een paar stappen verder is een prachtig wit gebouw uw volgende bezienswaardige punt in uw Schattenjacht.</p>",
  "568": "<p>Dit gebouw werd gebouwd in 1882 om de weeskinderen van de stad op te vangen.</p>\n<p>Op de neogotische gevel springt een groot balkon van steen in het oog met een groot boogvenster en daarboven een groot wapenschild.</p>",
  "569": "<p>Wat bekroont het wapenschild? Is het een kroon? Misschien een vleermuis? Of wellicht een draak?</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
