import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "579": `<p>Na <strong>Calle del Hospital</strong>, uma fonte discreta dá-nos as boas-vindas.</p>\n<p>Que forma tem a fonte?</p>\n<p>É uma concha? Talvez um peixe? Ou talvez uma pessoa?</p>`,
  "580": `<p>A Ermida de Santa Lúcia situada à sua direita indica-lhe que vai na direção correta.</p>\n<p>O antigo templo foi terminado em 1511.</p>\n<p>Em que ano começaram as obras? Olhe para a fachada!</p>`,
  "581": `<p>Curioso, não é verdade? O campanário tem um único muro no qual se abrem os espaços para colocar os sinos.</p>\n<p>Este elemento arquitetónico conhecido como espadana foi obra de Luis Peseto.</p>\n<p>Hoje em dia, os seus dois sinos repicam com sons atuais e alegram a vida dos transeuntes.</p>`,
  "582": `<p>A fachada que pode ver hoje em dia foi realizada por dois mestres de obras diferentes entre 1860 e 1865.</p>\n<p>Sebastián Monleón Estellés recebeu a encomenda de uma fachada com três portas. Sob a espadana brilha numa hornacina um busto em bronze de Santa Lúcia.</p>\n<p>Pelas mãos de José Esteve duas esculturas modernas enriquecem a fachada, a da esquerda simboliza a virtude e a da direita o martírio.</p>`,
  "583": `<p>Como últimas aportações, mencionaremos também que a ermida foi declarada Monumento Histórico-Artístico Nacional em 1963 e em 2007 Bem de Interesse Cultural.</p>\n<p>Saberia dizer-me o ano da sua última reabilitação?</p>\n<p>De certeza que já o viu!</p>`,
  "584": `<p>Preste especial atenção!</p>\n<p>O seu próximo objetivo não é o jardim, ainda.</p>\n<p>Continue até ao Colegio del Arte Mayor de la Seda.</p>`,
  "585": `<p>A "Rota da Seda" foi uma rede de rotas comerciais desde o séc. II antes de Cristo.</p>\n<p>Estendeu-se pelo continente asiático e afirmou-se na Europa no séc. XV nos reinos hispânicos e no Mediterrâneo ocidental, pelo que a indústria da seda é uma atividade que já em tempos dos muçulmanos tinha muita importância e gozava de grande prestígio em todo o Al-Ândalus.</p>\n<p>Dada a sua localização, a cidade de Valencia na época do Al-Ândalus já era célebre pela sua sericultura.</p>\n<p>No séc. XIV já havia sedeiros locais, maioritariamente judeus, mas foi dos séc. XV ao XVIII que a liderança de Valencia como centro principal das sedas espanholas era indiscutível; de facto, o cultivo da amoreira precedeu o da laranjeira em toda a região.</p>\n<p>A indústria da seda foi uma das mais potentes da cidade chegando a contar mais de 3.000 teares.</p>\n<p>Hoje em dia, os vestidos de Fallera mantêm viva a artesania da seda em teares manuais.</p>\n<p>Para o traje empregam-se de 10 a 15m de seda de mais de 20 cores, além de fio de prata e ouro.</p>`,
  "586": `<p>Com uma fachada de 29 metros, o edifício que pode ver agora foi adquirido pelos sedeiros valencianos em 1492. Sofreu diversas transformações ao longo dos séculos, sendo a última das mais importantes porque passou de estilo gótico a barroco.</p>\n<p>Em que ano se realizaram essas obras? Foi em 1756, talvez em 1492, ou em 1982?</p>\n<p>Precisa de uma Pista? Olhe para a fachada do edifício.</p>`,
  "587": `<p>No interior deste edifício situa-se o Museu da Seda; com exposições de tecidos clássicos valencianos dos séc. XVII e XVIII nos seus salões de pavimento de cerâmica tradicional.</p>\n<p>Também uma coleção composta por inumeráveis documentos que foram sendo guardados ao longo de cinco séculos, sendo este o museu com o arquivo gremial mais importante da Europa.</p>`,
  "588": `<p>${LOGO} recomenda-lhe que entre no parque do hospital que deixou para trás e o percorra ao seu próprio ritmo, ouvindo as notáveis pegadas da sua história.</p>\n<p>Não pause esta audioguia e dirija-se, se faz favor, ao ponto indicado. Obrigado.</p>`,
  "589": `<p>Contam antigas lendas que um frade valenciano, chamado Joan Gilabert Jofré, presenciou o apedrejamento de um cidadão com deficiência mental que foi deixado à sua sorte nas mãos de uns rapazes, e interpôs-se salvando-lhe a vida com este gesto.</p>\n<p>Após esse ato, declarado milagroso, propõem-se novas medidas que controlariam e estudiariam as pessoas num estado similar, criando, sem o saber, o primeiro hospital mental da Europa.</p>`,
  "590": `<p>No final do séc. XV realizou-se uma ampliação para acolher doentes não dementes.</p>\n<p>O parque onde está a entrar tem os seus inícios em 1512, tempo em que Fernando o Católico decretou a integração de todos os pequenos hospitais de Valencia num só, ficando este espaço como Hospital Provincial. Um hospital bem dotado, bem gerido, com grande prestígio e instalações adequadas.</p>\n<p>Para isso, construíram-se duas enfermarias com planta cruciforme.</p>\n<p>Esta disposição em forma de cruz está muito bem desenhada, uma vez que desde a torre central se podia controlar ao mesmo tempo as quatro alas do hospital.</p>`,
  "591": `<p>Anos mais tarde, em 1875, construíram-se novos edifícios e instalou-se a faculdade de medicina que se manteve neste local até 1948.</p>\n<p>Em 1960 abriu um novo hospital em Valencia com capacidade para albergar as necessidades da população.</p>\n<p>A partir de então, o antigo hospital provincial ficou em desuso e os interesses urbanísticos entraram em ação.</p>`,
  "592": `<p>Muitos edifícios como a igreja e um dos edifícios em forma de cruz não puderam salvar-se da demolição.</p>\n<p>A declaração do conjunto como Monumento Histórico Artístico Nacional em novembro de 1963 conseguiu salvar uma parte deste grande centro hospitalar, ficando de pé o espaço que hoje ocupa a biblioteca, a capela e diversos restos espalhados nos jardins que formam o espaço.</p>`,
  "592-B": `<p>Em 2009 decide-se reordenar esses jardins usando os elementos que ficavam espalhados, assim cria-se em 2012 este jardim arqueológico que podemos ver hoje em dia.</p>\n<p>O espaço alberga restos encontrados nas escavações provenientes do antigo hospital renascentista e outros elementos de interesse, como podem ser: restos da fachada da antiga Faculdade de Medicina, a Ermida de Santa Lúcia e o Museu valenciano da Ilustração (Muvim). No subsolo do museu conservam-se restos da antiga muralha cristã da cidade que foi demolida em 1865.</p>\n<p>${LOGO} incita-o a pausar esta audioguia e recomenda passear por este jardim ao seu próprio ritmo.</p>\n<p>Utilize o botão de pausa a seu próprio gosto. Quando sentir que é o momento adequado, simplesmente continue a resolver os nossos desafios enquanto descobre a cidade.</p>\n<p>A sua aventura continua desde a porta principal de acesso à biblioteca.</p>`,
  "593": `<p>Esta Aventura mistura a tradição Fallera e a história de Valencia. O objetivo é conhecer a origem, a tradição e a trajetória desta festividade que Valencia distingue o mês de março de todos os outros.</p>\n<p>Durante o seu percurso descobrirá vários pontos icónicos que são imprescindíveis para que as Fallas sejam possíveis tal e como as conhecemos hoje em dia.</p>`,
  "594": `<p>Orientadas para Oeste, as <strong>Torres de Quart</strong>, para além de entrada à cidade, serviram para vários propósitos no seu percurso, como, por exemplo: em 1562 como armazém de pólvora, ou em 1626 uma das suas torres foi destinada a prisão para prostitutas.</p>`,
  "595": `<p>Abra e observe o seu mapa.</p>\n<p>Com a entrada de Valencia às suas costas, do outro lado da avenida, abre-se o antigo caminho que conduzia às torres.</p>\n<p>Quando tiver atravessado a avenida, tome a segunda rua à sua direita.</p>\n<p>Esta Aventura leva-o a descobrir um dos tesouros botânicos da cidade. A entrada situa-se a dobrar a esquina.</p>\n<p>Lembre-se, é a segunda rua à direita!</p>\n<p>No seu mapa corresponde ao número <mark>64</mark>.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "596": `<p>O atual Jardim Botânico tem as suas origens não muito longe daqui num antigo horto de plantas medicinais onde se ministrava o ensino da botânica.</p>\n<p>Fundado em 1567, o Jardim Botânico da Universidade de Valencia é o mais antigo da Europa.</p>\n<p>Séculos mais tarde, com o apoio de diversas entidades, a Universidade de Valencia comprou o terreno onde se situa o centro de ensino.</p>\n<p>Cabe destacar que o próprio Jardim Botânico é irrigado pela acequia de Rovella, que proporciona ao subsolo os nutrientes necessários para a vida que alberga no seu interior.</p>\n<p>Felizmente, o catedrático de Medicina José Pizcueta melhorou as instalações durante os quase 40 anos que esteve a cargo da sua supervisão.</p>\n<p>Com o objetivo de realizar experiências de climatização construíram-se várias instalações como uma estufa de madeira, uma zona sombreada para proteger as plantas do sol ou mesmo várias estufas com diferentes temperaturas e humidades que favoreceram o crescimento de espécies importadas de todos os continentes.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} incita-o a pausar e entrar a descobrir a biodiversidade que este maravilhoso espaço oferece.</p>\n<p>No seu interior podem ver-se mais de 3.000 espécies vegetais diferentes, algumas das quais são as mais antigas da Europa, coexistindo num microclima fresco no pleno coração de Valencia.</p>\n<p>A sua Aventura continua desde a entrada do Jardim Botânico.</p>`,
  "597": "<p>Bravo! Esta zona ficou livre de pistas e está prestes a finalizar a sua Aventura! Não pause esta audioguia e dirija-se ao ponto indicado.</p>",
  "597-B": "<p>Bravo! Esta zona ficou livre de pistas e está prestes a finalizar a sua Aventura! Não pause esta audioguia e dirija-se ao ponto indicado.</p>",
  "598": `<p>Observe o seu mapa, e note que a sua aventura o leva de volta ao antigo leito do rio. Com a entrada principal do jardim botânico em frente a si, vire à sua esquerda e dobre a esquina, para seguir a parede do próprio jardim botânico até ao final da rua. Uma vez aí, atravesse a avenida e desça até ao Parque do Turia.</p>\n<p>Preste especial atenção pelo caminho, porque à sua esquerda aparecerá um dos jardins mais discretos da cidade. No seu mapa está indicado com o número <mark>65</mark>.</p>\n<p>Esse Jardim está inspirado na lenda de Hércules que, na sua última façanha, teve que roubar as maçãs de ouro do Jardim das Hespérides.</p>\n<p>Prima a pausa e dirija-se ao ponto 65 do seu mapa. Quando chegar, prima o botão correspondente para retomar a sua aventura. Obrigado.</p>`,
  "599": `<p>Conta a fábula grega que as Hespérides eram as ninfas encarregadas de cuidar o jardim das maçãs de ouro que a Deusa Gea (ou Gaia) (mãe terra) entregou como presente de casamento a Hera e Zeus.</p>\n<p>O célebre Hércules, por sua parte, conhecido pela sua grande força, conseguiu muitas façanhas, assim como vários atos criminosos.</p>\n<p>Depois de um deles, Hércules teve que realizar doze trabalhos por uma penitência imposta. O último dos seus trabalhos foi roubar as referidas maçãs após matar o dragão de cem cabeças que Gea tinha colocado sob custódia.</p>\n<p>Após derrotar o dragão Ladão; as Hespérides, assustadas, transformaram-se em choupos, salgueiros e olmos.</p>`,
  "600": `<p>Este discreto jardim adapta o antigo mito grego às espécies arbóreas nascentes que temos no nosso ambiente. Neste caso, o objeto precioso são as laranjas valencianas.</p>\n<p>O jardim inaugurado no ano 2000 com uma superfície de 4.700 metros quadrados inclui uma coleção de cítricos composta por mais de 50 variedades diferentes.</p>\n<p>Também no interior encontram-se três esculturas de bronze: a Deusa Vénus, o próprio Hércules e a metamorfose da ninfa em árvore.</p>\n<p>Se se encontrar em horário de visita, ${LOGO} incita-o a pausar esta audioguia e recomenda passear por este jardim ao seu próprio ritmo.</p>\n<p>Utilize o botão de pausa a seu próprio gosto. Quando o decidir, simplesmente continue a resolver os nossos desafios enquanto descobre a cidade.</p>`,
  "601": `<p>Está pronto para continuar a sua aventura? Ótimo! Volte ao muro do jardim botânico e vire à esquerda, depois continue até ao final da rua.</p>\n<p>Centre a sua atenção do outro lado da avenida e localize o ponto de acesso de descida que permite voltar ao antigo rio de Valencia. Deverá estar mesmo em frente a si, do outro lado da avenida. Pode vê-lo? Ótimo, porque tem que chegar a esse ponto.</p>\n<p>Para isso, respeitando sempre as normas de circulação, deve chegar até ao semáforo à sua esquerda. Atravessar a avenida, e seguir o muro do rio até ao ponto de descida.</p>\n<p>Uma vez em baixo do rio, dirija-se à sua esquerda. O seu objetivo é o famoso <strong>Parque de Cabecera</strong> que se encontra no final do <strong>Jardín del Turia</strong>, no caminho descobriremos locais interessantes dignos de menção.</p>\n<p>O primeiro é o <strong>Estádio de Atletismo</strong>.</p>\n<p>No seu mapa corresponde ao número <mark>66</mark>.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido. Obrigado.</p>`,
  "602": `<p>Um dos elementos que enriquece o <strong>Jardín del Turia</strong> é o leque de possibilidades para os amantes do desporto. Campos de futebol, basquetebol, basebol, atletismo ou râguebi convidam a manter-se ativo.</p>\n<p>Também as suas pistas de patinagem e as suas numerosas ciclovias animam a vida dos valencianos e dos seus visitantes.</p>\n<p>É como uma grande concentração de eventos desportivos usando um espaço natural, num ambiente público.</p>\n<p>O antigo leito do <strong>Rio Turia</strong> oxigena a cidade e mantém-na em movimento.</p>`,
  "603": `<p>Valencia é hoje em dia uma cidade bem comunicada e adaptada às necessidades dos seus habitantes.</p>\n<p>Uma dessas necessidades é aproveitar as horas de luz natural para exercitar o corpo e libertar as tensões acumuladas.</p>\n<p>Desde o ano 1991, ano da sua inauguração, no espaço que se abre diante de si pratica-se atletismo desde o nível de iniciação até ao alto rendimento.</p>\n<p>Este complexo desportivo compõe-se de: uma pista de atletismo de 400 metros, um campo de futebol sete ou hóquei em campo, várias salas de musculação e atividades físicas, além das instalações necessárias para um adequado aquecimento muscular, duches e balneários.</p>\n<p>Situada no <strong>Barrio de la Petxina</strong>, do qual faremos uma especial menção no decorrer desta aventura, o estádio do Turia é utilizado por bombeiros, polícias e outros coletivos para melhorar o seu rendimento físico.</p>`,
  "604": `<p>O seu mapa do tesouro incita-o a continuar o trajeto do rio ao seu próprio ritmo.</p>\n<p>No transcurso passará por baixo da Puente de Campanar, indicada com o número <mark>67</mark>.</p>\n<p>Uma ponte funcional que, embora tenha os seus inícios em 1937, foi reconstruída em betão em 1958 após a grande cheia do Turia.</p>\n<p>O seu próximo objetivo nesta Aventura é uma plataforma elevada que lhe proporcionará umas vistas magníficas do espaço onde se encontra.</p>\n<p>No seu mapa corresponde ao número <mark>68</mark>.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido. Obrigado.</p>`,
  "604-B": `<p>O seu mapa do tesouro incita-o a continuar o trajeto do rio ao seu próprio ritmo.</p>\n<p>No transcurso passará por baixo da Puente de Campanar, indicada com o número <mark>10</mark>.</p>\n<p>Uma ponte funcional que, embora tenha os seus inícios em 1937, foi reconstruída em betão em 1958 após a grande cheia do Turia.</p>\n<p>O seu próximo objetivo nesta Aventura é uma plataforma elevada que lhe proporcionará umas vistas magníficas do espaço onde se encontra. No seu mapa corresponde ao número <mark>11</mark>.</p>\n<p>Prima a pausa, depois vá ou visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "605": `<p>Bravo! Já recolheu todas as pistas e resolveu os enigmas que o antigo leito lhe propunha...</p>\n<p>A nossa Aventura número 3 propõe-lhe numerosos enigmas adicionais que o conduzirá até à famosa <strong>Ciudad de las Artes y de las Ciencias</strong>, a imagem futurista que simboliza a nova Valencia.</p>\n<p>A <strong>Ciudad de las Artes y de las Ciencias</strong> é um conjunto de vanguarda arquitetónico a nível mundial, onde milhões de visitantes acorrem cada ano para desfrutar da sua cultura, da sua natureza e da sua ciência.</p>`,
  "606": `<p>${LOGO} recomenda-lhe fazer uma breve pausa e olhar à sua volta.</p>\n<p>Como terá podido comprovar, em várias ocasiões, referimo-nos a este espaço como "o rio" e é que, para os valencianos, este continua a ser o seu nome popular.</p>`,
  "607": `<p>Enquanto chega ao próximo ponto de interesse na sua Aventura, desde ${LOGO} gostaríamos de enriquecer a sua estância com estas recomendações básicas e assim ter uma experiência plena da festa.</p>`,
  "608": `<p>30 anos depois do infeliz incidente, o leito deste rio começaria a ter um novo uso no coração de Valencia.</p>\n<p>Em primeira instância e a pedido governamental, o antigo leito ia ser destinado a albergar grandes autoestradas e edifícios, além de suprimir a falta de estacionamento público que a cidade sofre.</p>`,
  "609": `<p>Mas os valencianos, ao grito de "o rio é nosso e queremo-lo verde" conseguiram mudar os planos iniciais, num dos maiores jardins urbanos da Europa. Um ambiente de ar puro, rodeado de boas vibrações.</p>`,
  "610": "<p>Saberia dizer-me o nome deste antigo rio?</p>",
  "611": `<p>Nesta Aventura, o seu próximo objetivo mistura elementos arquitetónicos históricos com arquitetura atual e, como sempre, o desporto está presente.</p>\n<p>Dirija-se, se faz favor, à próxima ponte.</p>`,
  "612": `<p>A <strong>Ponte Amarela</strong> é um dos locais escolhidos em Valencia para praticar um estilo desportivo emergente, o Parkour; também conhecido como a arte do deslocamento.</p>\n<p>Esta modalidade inclui no seu treino: escalada, salto, corrida e equilíbrio.</p>`,
  "613": `<p><i>Parcours</i>, que significa percurso em francês, é uma disciplina física baseada em deslocar-se de um ponto a outro do ambiente da maneira mais simples e eficiente possível, adaptando-se às exigências do mesmo usando apenas o seu corpo.</p>`,
  "614": `<p>O praticante de Parkour chama-se <i>traceur</i> ou <i>traceuse</i> consoante seja homem ou mulher quem o pratica, traduzem-se como traçador ou traçadora, referindo-se ao ato de traçar o percurso.</p>`,
  "615": `<p>A sua prática implica o respeito à cidadania e ao ambiente. O seu objetivo é não pôr em perigo a vida do praticante ou a do seu ambiente, por isso o Parkour não é considerado uma atividade física de risco.</p>\n<p>Além disso, não se trata de uma prática competitiva, pelo que não pode ser considerado um desporto em Espanha uma vez que o desporto implica uma competição.</p>`,
  "616": `<p>A conhecida <strong>Puente 9 de Octubre</strong> é uma obra do famoso arquiteto valenciano Santiago Calatrava.</p>\n<p>No ano 1989, ano da inauguração da ponte, o arquiteto ainda não era reconhecido, mas já deixava entrever o traço característico do seu estilo.</p>`,
  "616-B": `<p>A nossa Aventura número 3 propõe-lhe numerosos enigmas adicionais que o conduzirá até à famosa <strong>Ciudad de las Artes y de las Ciencias</strong>, a imagem futurista que simboliza a nova Valencia.</p>\n<p>A <strong>Ciudad de las Artes y de las Ciencias</strong> é um conjunto de vanguarda arquitetónico a nível mundial, onde milhões de visitantes acorrem cada ano para desfrutar da sua cultura, da sua natureza e da sua ciência.</p>`,
  "617": `<p>A <strong>Puente 9 de Octubre</strong> é a linha limítrofe da cidade de Valencia e a entrada a um dos tesouros botânicos que oferece, hoje em dia, o antigo leito do rio.</p>\n<p>Está prestes a adentr-ar-se no <strong>Parque de Cabecera</strong>, situado na extremidade oeste da cidade.</p>\n<p>O <strong>Parque de Cabecera</strong> é um dos pulmões de Valencia de onde partem diversas rotas ciclistas.</p>`,
  "618": `<p>Tome o caminho ciclista que fica à direita do leito e adentre-se no parque. Uns metros mais adiante, à sua direita, ergue-se uma pequena montanha conhecida como "el Morró".</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
