import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "601": "<p>È pronto per continuare la sua avventura? Bene! Torni al muro del giardino botanico e giri a sinistra, poi continui fino alla fine della via.</p>\n<p>Concentri la sua attenzione dall'altro lato del viale e individui il punto di accesso che permette di scendere e tornare all'antico fiume di Valencia. Dovrebbe essere proprio di fronte a Lei, dall'altro lato del viale. Riesce a vederlo? Bene, perché deve raggiungere quel punto.</p>\n<p>Per farlo, rispettando sempre le norme di circolazione, raggiunga il semaforo alla sua sinistra. Attraversi il viale e segua il muro del fiume fino al punto di discesa.</p>\n<p>Una volta sotto il livello del fiume, si diriga a sinistra. Il suo obiettivo è il famoso <strong>Parco di Cabecera</strong> che si trova alla fine del <strong>Giardino del Turia</strong>; lungo il percorso scopriremo luoghi interessanti degni di menzione.</p>\n<p>Il primo è lo <strong>Stadio di Atletica</strong>.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>66</mark>.</p>\n<p>Prema pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito. Grazie.</p>",
  "602": "<p>Uno degli elementi che arricchisce il <strong>Giardino del Turia</strong> è la varietà di possibilità per gli amanti dello sport. Campi di calcio, basket, baseball, atletica o rugby invitano a mantenersi in forma.</p>\n<p>Anche le sue piste di pattinaggio e i numerosi percorsi ciclabili animano la vita dei valenciani e dei loro visitatori.</p>\n<p>È come una grande concentrazione di eventi sportivi che sfrutta uno spazio naturale, in un contesto pubblico.</p>\n<p>Il vecchio alveo del <strong>Río Turia</strong> ossigena la città e la mantiene in movimento.</p>",
  "603": "<p>Valencia è oggi una città ben collegata e adattata alle esigenze dei suoi abitanti.</p>\n<p>Una di queste esigenze è sfruttare le ore di luce naturale per esercitare il corpo e liberare le tensioni accumulate.</p>\n<p>Dal 1991, anno della sua inaugurazione, nello spazio che si apre davanti a Lei si pratica l'atletica dal livello di iniziazione fino all'alto rendimento.</p>\n<p>Questo complesso sportivo è composto da: una pista di atletica di 400 metri, un campo di calcio a sette o hockey su prato, varie sale di muscolazione e attività fisiche, oltre alle strutture necessarie per un adeguato riscaldamento muscolare, docce e spogliatoi.</p>\n<p>Situato nel <strong>Quartiere della Petxina</strong>, del quale faremo una menzione speciale nel corso di questa avventura, lo stadio del Turia è utilizzato da pompieri, poliziotti e altri gruppi per migliorare le proprie prestazioni fisiche.</p>",
  "604": "<p>La sua mappa del tesoro la incita a continuare il percorso del fiume al proprio ritmo.</p>\n<p>Nel corso del percorso passerà sotto il Puente de Campanar, indicato con il numero <mark>67</mark>.</p>\n<p>Un ponte funzionale che, sebbene abbia le sue origini nel 1937, fu ricostruito in calcestruzzo nel 1958 dopo la grande alluvione del Turia.</p>\n<p>Il suo prossimo obiettivo in questa Avventura è una piattaforma sopraelevata che le offrirà delle viste magnifiche dello spazio in cui si trova.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>68</mark>.</p>\n<p>Prema pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito. Grazie.</p>",
  "604-B": "<p>La sua mappa del tesoro la incita a continuare il percorso del fiume al proprio ritmo.</p>\n<p>Nel corso del percorso passerà sotto il Puente de Campanar, indicato con il numero <mark>10</mark>.</p>\n<p>Un ponte funzionale che, sebbene abbia le sue origini nel 1937, fu ricostruito in calcestruzzo nel 1958 dopo la grande alluvione del Turia.</p>\n<p>Il suo prossimo obiettivo in questa Avventura è una piattaforma sopraelevata che le offrirà delle viste magnifiche dello spazio in cui si trova. Sulla sua mappa corrisponde al numero <mark>11</mark>.</p>\n<p>Prema pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "605": "<p>Bravo! Ha già raccolto tutti gli indizi e risolto gli enigmi proposti dal vecchio alveo...</p>\n<p>La nostra Avventura numero 3 le propone numerosi enigmi aggiuntivi che la condurranno fino alla famosa <strong>Città delle Arti e delle Scienze</strong>, il panorama futuristico che simboleggia la nuova Valencia.</p>\n<p>La <strong>Città delle Arti e delle Scienze</strong> è un complesso architettonico d'avanguardia a livello mondiale, dove milioni di visitatori si recano ogni anno per godere della sua cultura, della sua natura e della sua scienza.</p>",
  "606": `<p>${LOGO} Le raccomanda di fare una breve pausa e guardarsi intorno.</p>\n<p>Come avrà potuto constatare, in varie occasioni ci siamo riferiti a questo spazio come "il fiume" e in effetti, per i valenciani, questo rimane il suo nome popolare.</p>`,
  "607": `<p>Mentre si avvicina al prossimo punto di interesse nella sua Avventura, da ${LOGO} vorremmo arricchire la sua permanenza con queste raccomandazioni di base e così vivere appieno l'esperienza della festa.</p>`,
  "608": "<p>30 anni dopo lo sfortunato incidente, l'alveo di questo fiume avrebbe iniziato ad avere un nuovo utilizzo nel cuore di Valencia.</p>\n<p>In prima istanza e su richiesta governativa, il vecchio alveo sarebbe stato destinato ad accogliere grandi autostrade ed edifici, oltre a compensare la mancanza di parcheggi pubblici di cui soffre la città.</p>",
  "609": `<p>Ma i valenciani, al grido di "il fiume è nostro e lo vogliamo verde" riuscirono a cambiare i piani iniziali, creando uno dei più grandi giardini urbani d'Europa. Un ambiente di aria pura, circondato di buone vibrazioni.</p>`,
  "610": "<p>Saprebbe dirmi il nome di questo antico fiume?</p>",
  "611": "<p>In questa Avventura, il suo prossimo obiettivo mescola elementi architettonici storici con l'architettura attuale e, come sempre, lo sport è presente.</p>\n<p>Si diriga, se è così gentile, al prossimo ponte.</p>",
  "612": "<p>Il <strong>Ponte Giallo</strong> è uno dei luoghi scelti a Valencia per praticare uno stile sportivo emergente, il Parkour; noto anche come l'arte dello spostamento.</p>\n<p>Questa disciplina include nel suo allenamento: scalata, salto, corsa ed equilibrio.</p>",
  "613": "<p><i>Parcours</i>, che significa percorso in francese, è una disciplina fisica basata sullo spostarsi da un punto all'altro dell'ambiente nel modo più semplice ed efficiente possibile, adattandosi alle sue esigenze usando solo il proprio corpo.</p>",
  "614": "<p>Il praticante di Parkour si chiama <i>traceur</i> o <i>traceuse</i> a seconda che sia un uomo o una donna a praticarlo; si traducono come tracciatore o tracciatrice, riferendosi all'atto di tracciare il percorso.</p>",
  "615": "<p>La sua pratica implica il rispetto nei confronti della cittadinanza e dell'ambiente. Il suo obiettivo è non mettere in pericolo la vita del praticante o delle persone intorno a lui, per questo il Parkour non è considerato un'attività fisica rischiosa.</p>\n<p>Inoltre, non si tratta di una pratica competitiva, per cui non può essere considerato uno sport in Spagna poiché lo sport implica una competizione.</p>",
  "616": "<p>Il noto <strong>Ponte del 9 Ottobre</strong> è un'opera del famoso architetto valenciano Santiago Calatrava.</p>\n<p>Nel 1989, anno dell'inaugurazione del ponte, l'architetto non era ancora riconosciuto, ma lasciava già intravedere il tratto caratteristico del suo stile.</p>",
  "616-B": "<p>La nostra Avventura numero 3 le propone numerosi enigmi aggiuntivi che la condurranno fino alla famosa <strong>Città delle Arti e delle Scienze</strong>, il panorama futuristico che simboleggia la nuova Valencia.</p>\n<p>La <strong>Città delle Arti e delle Scienze</strong> è un complesso architettonico d'avanguardia a livello mondiale, dove milioni di visitatori si recano ogni anno per godere della sua cultura, della sua natura e della sua scienza.</p>",
  "617": "<p>Il <strong>Ponte del 9 Ottobre</strong> è il confine della città di Valencia e l'ingresso a uno dei tesori botanici che offre, oggi, l'antico alveo del fiume.</p>\n<p>Sta per addentrarsi nel <strong>Parco di Cabecera</strong>, situato nell'estremità ovest della città.</p>\n<p>Il <strong>Parco di Cabecera</strong> è uno dei polmoni di Valencia da cui partono diversi percorsi ciclabili.</p>",
  "618": `<p>Prenda il percorso ciclabile che si trova a destra dell'alveo e si addentri nel parco. Pochi metri più avanti, alla sua destra, si erge una piccola collina conosciuta come "el Morró".</p>`,
  "619": "<p>Cerchi l'accesso che permette di salire alla vetta e si prenda un po' di tempo per aprire la sua mappa e scoprire quest'area.</p>",
  "620": "<p>El Morro, numero <mark>71</mark> sulla sua mappa, è un punto magnifico da cui si vede il <strong>Parco di Cabecera</strong> completo e il famoso <strong>Bioparc</strong>, che corrisponde al numero <mark>73</mark> sulla sua mappa.</p>",
  "620-B": "<p>El Morro, numero <mark>14</mark> sulla sua mappa, è un punto magnifico da cui si vede il <strong>Parco di Cabecera</strong> completo e il famoso <strong>Bioparc</strong>, che corrisponde al numero <mark>15</mark> sulla sua mappa.</p>",
  "621": "<p>Quest'ultimo si divide in zone ben differenziate: a destra si trova l'accesso al parco zoologico. In quel punto si trovano le biglietterie per acquistare i biglietti d'ingresso.</p>",
  "622": "<p>Riesce a vedere il ponte che attraversa sopra il lago? Quello è l'accesso al recinto delle esibizioni, che si trova alla sua sinistra.</p>\n<p>Si accomodi e si prepari a godere, perché da questo punto sopraelevato in cui si trova in questo momento commenteremo diversi punti della sua Avventura.</p>",
  "623": "<p>Il <strong>Parco di Cabecera</strong> si estende a 15 metri sotto i suoi piedi e riceve questo nome per trovarsi alla testata del vecchio alveo del <strong>Río Turia</strong> nel suo ingresso a Valencia.</p>\n<p>Realizzato tra il 2002 e il 2014, il parco si sviluppa attorno a un lago artificiale nel quale si possono fare gite in barca.</p>\n<p>Nelle acque di questo lago vivono carpe, tartarughe e rane, oltre ad anatre e cigni che si sono già abituati alla pacifica presenza degli esseri umani.</p>",
  "624": "<p>Nel <strong>Parco di Cabecera</strong> spiccano alberi e arbusti adatti alla climatologia mediterranea; in particolare specie associate alle rive e all'alveo del <strong>Río Turia</strong>: si notano olmi, pioppi e pini che formano piccoli boschi.</p>\n<p>A contatto con l'acqua abitano specie di piante anfibie, tipha e giunchi che strutturano il lago e riparano le specie animali che lo abitano.</p>\n<p>Nel parco crescono anche gruppi ben strutturati di arbusti e piante erbacee legnose come il rosmarino, il timo e la sparto, tipici del clima semiarido mediterraneo.</p>",
  "625": "<p>Questo parco metropolitano di quasi 168.000 metri quadrati è incentrato sul recupero del paesaggio originale del <strong>Río Turia</strong>.</p>\n<p>L'acqua sgorga dal Molí del Sol e segue l'antico corso naturale del fiume fino a sfociare nel lago, lasciando lungo il percorso isolotti di sedimentazione tipici della geografia mediterranea.</p>\n<p>I muri di pietra e i diversi livelli del terreno offrono un ambiente intimo con ampie vedute.</p>\n<p>Un chiaro esempio: è il luogo in cui si trova Lei in questo momento, da cui può vedere, in lontananza, il Parco Naturale della Sierra de Calderona.</p>",
  "626": `<p>Durante le Fallas si cammina molto, portare calzature comode è indispensabile. Mentre si avvicina al prossimo punto di interesse nella sua Avventura, da ${LOGO} vorremmo condividere questi consigli e così vivere appieno l'esperienza della festa.</p>`,
  "627": "<p><strong>Bioparc</strong> è il nuovo zoo valenciano che ha sostituito il suo predecessore dal 2008.</p>\n<p>Il vecchio zoo di Valencia, chiuso nel 2007, fu fondato nel 1965 e si trovava nei famosi <strong>Giardini del Real</strong> che vedrà in dettaglio più avanti in questa Avventura.</p>\n<p>Al contrario del vecchio zoo in cui gli animali erano sovraffollati, <strong>Bioparc</strong> dà la sensazione che il visitatore si addentri nell'habitat dell'animale grazie al fatto che il suo design nasconde le barriere tra il pubblico e gli animali, creando un effetto di zoimmersione.</p>\n<p>Questo spazio di 100.000 metri quadrati ricrea la fauna africana e ospita più di 800 animali di diverse specie del continente africano, riproducendo l'habitat di ogni animale.</p>\n<p><strong>Bioparc</strong> si divide in quattro aree biotiche: savana secca e savana umida, Madagascar e le foreste dell'Africa equatoriale.</p>",
  "628": `<p>Questo innovativo progetto di zoimmersione ha l'obiettivo di promuovere un cambiamento nel nostro comportamento; amiamo gli animali e vogliamo che quel cambiamento ci motivi a vivere in armonia con il pianeta.</p>\n<p>Da qui il suo motto: commuovere per conservare.</p>\n<p>Se si trova in orario di visita, ${LOGO} La incita a premere pausa ed entrare a scoprire la biodiversità che offre questo meraviglioso spazio.</p>\n<p>Può riprendere la sua avventura quando lo riterrà opportuno.</p>\n<p>Utilizzi il pulsante di pausa a suo piacimento, quando sentirà che è il momento continui a risolvere le nostre sfide mentre scopre la città. Goda a suo ritmo di questo parco di ispirazione millenaria.</p>\n<p>La sua Avventura continua dietro i maestosi edifici alla sua sinistra.</p>\n<p>Il <strong>Museo di Storia</strong> di Valencia è probabilmente uno dei migliori luoghi per continuare ad apprendere su questa cultura mediterranea in cui si trova oggi.</p>`,
  "628-B": `<p>Se si trova in orario di visita, ${LOGO} La incita a premere pausa ed entrare a scoprire la biodiversità che offre questo meraviglioso spazio.</p>\n<p>Può riprendere la sua avventura quando lo riterrà opportuno.</p>\n<p>Utilizzi il pulsante di pausa a suo piacimento, quando sentirà che è il momento continui a risolvere le nostre sfide mentre scopre la città. Goda a suo ritmo di questo parco di ispirazione millenaria.</p>`,
  "629": "<p>Utilizzi i mezzi pubblici, soprattutto la metropolitana nella settimana dal 15 al 19 marzo, perché molte vie saranno chiuse. Anche così, spostarsi in monopattino elettrico, in bici o persino, per chi sa usarli, i pattini sono ottimi mezzi di trasporto.</p>",
  "630": "<p>Si trova di fronte al <strong>Museo di Storia</strong> di Valencia? Bene! Perfetto!</p>\n<p>L'attuale <strong>Museo di storia</strong> si trova negli antichi serbatoi d'acqua potabile costruiti nel 1850 come parte del progetto generale di approvvigionamento idrico della città, essendo questo uno dei primi in Europa.</p>\n<p>L'acqua veniva canalizzata a monte, condotta fino a questo punto e da qui distribuita alle otto fontane pubbliche della città.</p>\n<p>Ricordi che, in quei tempi, le fontane pubbliche erano i ricettori del recente arrivo dell'acqua potabile in città.</p>",
  "631": "<p>Scavato nel sottosuolo e coperto con 11 volte in mattoni sorretto da 250 pilastri o colonne in mattoni, l'antico serbatoio garantiva l'accumulo di 9000 metri cubi d'acqua e sfruttava il dislivello naturale del suolo per ottenere la pressione idrica necessaria.</p>\n<p>Con il passare del tempo e la crescente domanda, fu necessario costruire nuovi serbatoi accumulatori d'acqua e questo cadde in disuso per diversi decenni. Alla fine degli anni '90 fu rispettosamente restaurato per l'uso attuale.</p>",
  "632": `<p>Con una superficie di 2.600 metri quadrati, il Museo interattivo di Storia si dedica alla diffusione della storia di Valencia dalle sue origini ai nostri giorni.</p>\n<p>Questo tesoro della città fu inaugurato nel 2003 con un approccio museografico innovativo pensato per comunicare con il visitatore.</p>\n<p>Il museo espone numerosi manufatti archeologici, architettonici e storici, ma ciò che senza dubbio risalta nella sua esposizione è l'uso delle nuove tecnologie audiovisive.</p>\n<p>In quest'area è possibile interagire con il passato, scegliendo tra molteplici scenari che ricreano la vita degli abitanti e le loro attività quotidiane, al fine di comprendere le preoccupazioni e le ansie di quell'epoca.</p>\n<p>Se si trova in orario di visita, ${LOGO} Le consiglia di premere pausa e visitare questo centro culturale al proprio ritmo.</p>\n<p>Può riprendere la sua avventura quando lo riterrà opportuno. Prema semplicemente il pulsante corrispondente e continui "<i>alla ricerca del tesoro</i>".</p>`,
  "633": "<p>Apra e osservi la sua mappa: questa le indica di cercare di nuovo l'alveo dell'antico <strong>Río Turia</strong> e prendere il percorso condizionato alla sua destra.</p>\n<p>Torniamo al centro storico, ma questo non finisce qui! Percorra l'itinerario suggerito e osserverà che, passati 5 ponti, l'attende il suo prossimo punto di interesse.</p>",
  "634": "<p>Questo elemento decorativo ha le sue origini nel 1592.</p>\n<p>Il suo scopo era incanalare il fiume e prevenire possibili inondazioni, sebbene nella Valencia medievale, questo elemento avesse un passato assai più oscuro.</p>\n<p>La leggenda popolare racconta che questo era il temuto rogo.</p>\n<p>Luogo in cui la Santa Inquisizione bruciava gli eretici, gli schiavi, i demoniaci, le streghe e le prostitute dopo averli condannati alla pena massima.</p>",
  "635": "<p>Concentri la sua attenzione sul pavimento della rampa che dà accesso alla parte superiore del ponte; spiccano ancora alcuni piccoli dossi che facilitavano la vita ai cittadini che accedevano a quest'antico porto fluviale.</p>\n<p>Quale uso possono avere quei dossi? Fermare l'acqua? Bloccare le ruote dei carri e facilitare così il carico e lo scarico dagli animali? O forse per raccogliere le alghe e i detriti del fiume?</p>",
  "636": "<p>Apra e osservi la sua mappa. La sua Avventura continua lungo il sentiero alberato finché non trova l'accesso che risale verso la città.</p>\n<p>Una volta su, il suo prossimo reto si trova nella statua che dà il nome al ponte.</p>\n<p>Il <strong>Puente de San José</strong> si trova al secondo ponte dalla sua posizione,</p>\n<p>Se è così gentile, si posizioni di fronte alla statua che si trova al centro del ponte.</p>",
  "637": "<p>José de Nazaret, sposo di Maria e Padre Putativo di Gesù Cristo, era artigiano di mestiere; per questo la Comunità di Valencia lo adottò come suo Santo Patrono.</p>\n<p>Il 19 marzo, Giorno del Padre, è un giorno speciale in tutta la Spagna poiché si celebra il tributo a San Giuseppe.</p>\n<p>Ma specialmente a Valencia, questo è il giorno più magico dell'anno, poiché è qui che vengono bruciate le famose Fallas.</p>",
  "638": "<p>L'origine di questa festività risale al XVIII secolo.</p>\n<p>Un'antica tradizione dei falegnami della città che, alla vigilia della festa del loro patrono, bruciavano nelle piazze pubbliche vecchi e inutili oggetti insieme ai residui di legno avanzati dal loro lavoro.</p>\n<p>Inizialmente, la Falla era composta da pire di materiali combustibili che si sono evolute fino ai monumenti che si possono vedere oggi.</p>\n<p>Le Fallas sono diventate un'attrazione turistica molto importante, perché oltre ad essere catalogate come Festa di Interesse Turistico Internazionale, nel novembre del 2016 l'UNESCO le ha iscritte nella sua Lista Rappresentativa del Patrimonio Culturale Immateriale dell'Umanità.</p>",
  "639": "<p>Riprenda il sentiero attrezzato che la riporta alle <strong>Torres de Serranos</strong>. Sulla sua mappa corrisponde al numero <mark>1</mark>.</p>\n<p>Ricordi che non deve scendere di nuovo al giardino, la sua Avventura continua in terreno urbano.</p>\n<p>Proceda con cautela da questo punto in poi, poiché si tratta di un tracciato urbano e si deve rispettare la normativa stradale.</p>\n<p>Guardi le indicazioni della sua mappa del tesoro e continui sulla pista ciclabile per addentrarsi nel pieno centro storico in cerca di ulteriori indizi.</p>\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "640": "<p>È arrivato alle torri? Concentri la sua attenzione.</p>",
  "641": "<p>Sapeva che la bandiera di Valencia ha un nome proprio?</p>\n<p>Come può apprezzare, la Real Senyera di Valencia è uno stemma tricolore formato da bande rosse e gialle orizzontali con una banda blu nella zona dell'asta.</p>\n<p>Concentri la sua attenzione su quell'area blu e potrà distinguere la corona che le conferisce il grado di Regalità.</p>",
  "642": `<p>Nel corso della sua storia, i valenciani hanno mediato in patti e si sono coinvolti in battaglie, insurrezioni e prese di controllo in momenti critici.</p>\n<p>In tempi di guerra, le città limitrofe dovevano seguire lo stendardo di Valencia dal quale partivano gli ordini. Popolarmente si chiamava "seguire la Senyera".</p>\n<p>Per tutte queste imprese, la bandiera di Valencia è l'unica in Spagna ad avere grado di regalità, e per questo non si inchina davanti a niente né a nessuno.</p>`,
  "643": "<p>Una curiosità è che, quando viene trasportata, la bandiera deve avere il pennone sempre in posizione verticale.</p>\n\n<p>Ricordi che questo è un punto perfetto per scattare una magnifica foto di questo monumento dichiarato di interesse storico artistico.</p>",
  "644": "<p>La sua mappa del tesoro le indica di scendere all'alveo del fiume.</p>\n\n<p>Per farlo, torni verso le torri e segua la pista ciclabile alla sua sinistra fino al punto di discesa.</p>\n\n<p>Una volta in basso, si diriga al centro dell'alveo.</p>\n\n<p>Un po' più avanti, in direzione del Museo di Belle Arti, si apre un portale del tempo. Tra cipressi e ulivi si possono contemplare resti del Palazzo del Real.</p>",
  "645": `<p>L'antico Palazzo del Real fu costruito inizialmente nel IX secolo come Almunia, una tenuta di svago musulmana in cui i Sultani della Taifa di Balansiya si ritiravano per riposarsi.</p>\n\n<p>Così continuò durante il periodo della conquista cristiana e fu nel XIV secolo che si cominciò a ricostruirlo per diventare il palazzo dei Re della Corona d'Aragona durante il loro soggiorno nel Regno di Valencia.</p>\n\n<p>Il palazzo era noto come "il Palazzo delle 300 chiavi" in riferimento al numero di stanze che arrivò ad avere.</p>`,
  "646": "<p>Vale la pena notare che questo palazzo non esiste più.</p>\n\n<p>Come ricordo, ci rimangono le incisioni che lo rappresentano.</p>\n\n<p>Nel 1810, l'antico palazzo fu smantellato dai valenciani per ragioni strategiche di difesa, di fronte alla possibilità che potesse diventare una piazzaforte delle truppe invasori di Napoleone.</p>\n\n<p>Oggi ci rimangono vestigia esposte che delimitano le corsie centrali di certi tratti del Giardino del Turia e i famosi Giardini del Real, che a suo tempo occupavano una piccola parte di quelli che erano i Giardini del Palazzo.</p>\n\n<p>I Giardini del Real offrono una passeggiata con esemplari centenari di palme, un'enorme voliera che risale al 1933, oltre a un laghetto con anatre e cigni, un magnifico roseto e anche numerose sculture e fontane monumentali.</p>\n\n<p>Ancora più importante! I giardini proteggono al loro interno parte della storia di Valencia.</p>",
  "646-A": "<p>Vale la pena notare che questo palazzo non esiste più.</p>\n\n<p>Come ricordo, ci rimangono le incisioni che lo rappresentano.</p>\n\n<p>Nel 1810, l'antico palazzo fu smantellato dai valenciani per ragioni strategiche di difesa, di fronte alla possibilità che potesse diventare una piazzaforte delle truppe invasori di Napoleone.</p>\n\n<p>Oggi ci rimangono vestigia esposte che delimitano le corsie centrali di certi tratti del Giardino del Turia e i famosi giardini di vivai, che a suo tempo occupavano una piccola parte di quelli che erano i giardini del palazzo.</p>",
  "647": "<p>Questa avventura la incita a seguire la mappa fino all'ingresso di questi giardini.</p>\n\n<p>Svolgendo la funzione di polmone della città, l'accesso più popolare ai Giardini del Real si trova in un passaggio sotterraneo che attraversa il viale e la porta esattamente a uno dei suoi ingressi principali.</p>",
  "647-B": "<p>Segua la sua mappa fino all'ingresso dei Giardini di Viveros indicato con il numero <mark>4</mark> sulla sua mappa.</p>\n\n<p>Svolgendo la funzione di polmone della città, l'accesso più popolare a questi giardini lo troverà in un sottopassaggio che attraversa il viale e la porta esattamente a uno dei suoi ingressi principali.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito. Grazie.</p>",
  "648": "<p>Ammiri il suo ingresso principale. Un portale romantico in ferro battuto, che risale al 1860. Circonda il vasto recinto una sobria cancellata dello stesso materiale sorretta da zoccolo e pilastri in pietra.</p>",
  "648-B": "<p>Ammiri il suo ingresso principale, un ingresso romantico in ferro battuto che risale al 1860.</p>\n\n<p>I Giardini di Viveros offrono una passeggiata con esemplari centenari di palme, un'enorme voliera che risale al 1933, oltre a un laghetto con anatre e cigni, come anche un magnifico roseto e numerose sculture e fontane monumentali.</p>\n\n<p>Ancora più importante! I giardini proteggono al loro interno parte della storia di Valencia.</p>",
  "649": "<p>Questa Avventura la invita ad addentrarsi in questi giardini che a partire dal 1912 sarebbero diventati Parco Municipale per il svago di chiunque voglia visitarli.</p>\n\n<p>Dato che si tratta di una zona piuttosto ampia, per comodità, l'abbiamo numerata individualmente a partire dall'ingresso ai giardini, che corrisponde sulla sua mappa al numero <mark>1</mark>.</p>\n\n<p>Dall'ingresso si può ammirare la vegetazione che si distingue per la varietà del suo alberato con esemplari di grande statura e età.</p>\n\n<p>Nel Viale delle Palme predominano le palme delle Canarie, le Washingtonie, nonché le palme da dattero. Sulla sua mappa corrisponde al numero <mark>1</mark>.</p>\n\n<p>Non metta in pausa questa audioguida e si addentri negli antichi giardini del Real.</p>",
  "649-B": `<p>Se si trova in orario di visita, ${LOGO} Le consiglia di premere pausa e di godersi questi Giardini al proprio ritmo!</p>\n\n<p>Utilizzi il pulsante di pausa a suo piacimento, quando sentirà che è il momento appropriato, semplicemente continui a risolvere le nostre sfide mentre scopre la città.</p>\n\n<p>${LOGO} Le fornirà informazioni dettagliate su quest'area nella sua Avventura numero 4.</p>\n\n<p>Quando deciderà di continuare alla ricerca del tesoro attraversi di nuovo il tunnel per accedere all'alveo del Giardino del Turia.</p>`,
  "650": "<p>Con l'ingresso dei giardini alle spalle, prenda il sentiero a sinistra; a pochi metri inizia la pista ciclabile che le permetterà di attraversare il famoso ponte del Real.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
