import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "136": "<p>Já chegou ao ponto sugerido? Pause esta audioguia se o considerar necessário. Ânimo, faltam apenas uns metros!</p>",
  "137": `<p>Observe as torres, centre a sua atenção na grande varanda ameada. Desde 1954, neste mesmo ponto cada ano marca-se o arranque das celebrações falleras. "La Cridà" é o chamamento à festa das falleras maiores de Valencia a quem queira participar.</p>`,
  "138": "<p>São muitos monumentos, não é verdade? As Fallas como monumento: o que são?</p>",
  "139": `<p>O monumento fallero é uma escultura artística com figuras geralmente de grandes dimensões chamadas Ninots, as quais rodeiam uma ou mais figuras centrais. A falla é realizada em materiais combustíveis (cartão, madeira, papel, tecidos). Os monumentos são instalados nas ruas para que, após alguns dias de exposição, possam ser queimados na totalidade.</p>\n<p>No dia 15 de março começa a Plantà (montagem do monumento) atingindo alguns os 25 metros de altura. A partir do dia 16 às oito da manhã as fallas ficam terminadas e expostas para concorrer ao primeiro prémio.</p>`,
  "140": `<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 1.</p>`,
  "141": `<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 2.</p>`,
  "142": `<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 3.</p>`,
  "143": `<p>Se não se encontrar em horário de abertura, poderá sempre fazer uma pausa num ponto a partir do qual poderá contemplar a totalidade da praça e simplesmente desfrutar do áudio da sua Aventura.</p>\n<p>Nesta clareira urbana desvela-se um fragmento de vários tesouros arquitetónicos que a cidade oferece, reunidos numa única praça.</p>\n<p>Prima a pausa e prima de novo o botão continuar uma vez o entender conveniente.</p>`,
  "144": `<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 5.</p>`,
  "145": `<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura Especial Fallas.</p>`,
  "146": `<p>Centre a sua atenção no edifício que tem uma cúpula oval de cor azul.</p>\n<p>Esta é a conhecida <strong>Basílica de Valencia</strong>.</p>`,
  "147": `<p>A <strong>Catedral de Valencia</strong> ergue-se sobre a antiga Sé Visigótica que séculos mais tarde se converteu em Mesquita Maior, razão pela qual na sua fachada norte, que é a mais antiga, o templo adquire uma forma arredondada em vez da tradicional planta de cruz.</p>\n<p>No séc. XIII, a construção da Catedral foi acontecendo à medida que se aproveitava a Mesquita árabe situada neste mesmo local.</p>`,
  "148": `<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 3.</p>`,
  "149": `<p>A construção da Catedral demorou 500 anos a ser finalizada e durante esse extenso período de tempo, os estilos arquitetónicos mudaram; por isso na <strong>Catedral de Valencia</strong> fundem-se vários estilos arquitetónicos.</p>\n<p>Estes estilos podem ver-se com total clareza nas suas três portas: Barroca a principal que verá a seguir nesta Aventura, Gótica a que tem diante de si agora mesmo e Românica na sua face este, sobre a qual ofereceremos mais informação na nossa Aventura número 1.</p>\n<p>Nessa mesma Aventura detalha-se também a praça que fica atrás da Catedral, que foi, casualmente, o quilómetro zero da Valencia Romana.</p>`,
  "150": `<p>Centre a sua atenção ao fundo da praça, o seu próximo objetivo é o famoso <strong>Miguelete</strong>. Uma grande torre que sobressai por detrás da Catedral. Mas antes falemos do pórtico da Catedral.</p>`,
  "151": "<p>Uma vez que decida continuar a sua aventura, situe-se de volta ao centro desta praça olhando para a fachada de arcos cegos da igreja.</p>",
  "152": "<p>Hoje em dia, esse painel cerâmico à altura do primeiro andar ilustra o milagre.</p>",
  "153": `<p>No dia 18 celebra-se "La nit del foc" (noite do fogo): um espetáculo pirotécnico assombroso que dá passagem ao último dia no qual os monumentos falleros estarão expostos.</p>\n<p>O dia 19, dia da "cremà" (momento em que ardem os monumentos falleros), coincide sempre com a festividade de São José, Padroeiro de Valencia.</p>`,
  "154": `<p>A <strong>Lonja de la Seda</strong> é, por excelência, o monumento do Século de Ouro valenciano e situa-se a escassos metros da praça redonda.</p>\n<p>O monumento foi construído entre 1482 e 1497 para albergar a Wall Street da Valencia do séc. XV. Este centro financeiro era necessário uma vez que a famosa Rota da Seda atravessava a cidade enriquecendo-a à sua passagem.</p>\n<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 1.</p>`,
  "155": `<p>O seu próximo objetivo é o monumento do Século de Ouro valenciano. Uma Wall Street do séc. XV.</p>\n<p>A <strong>Lonja</strong> foi construída entre 1482 e 1497 e foi declarada Património da Humanidade em 1996. No seu mapa corresponde ao número <mark>16</mark>.</p>`,
  "156": `<p>Siga o seu mapa e continue até ao final da rua, onde se abre uma praça conhecida como a <strong>Plaza de la Virgen</strong>. Uma das mais icónicas da cidade.</p>`,
  "157": "<p>Destaca, na sua parte mais alta, um catavento dedicado a este santo famoso pelo seu martírio, um dos mais antigos que estão documentados.</p>",
  "158": `<p>Aproxime-se, se faz favor, à <strong>Iglesia de San Lorenzo</strong> que corresponde no seu mapa ao número <mark>4</mark>.</p>`,
  "159": `<p>Continue, se faz favor, até ao final da rua, na qual se abre a famosa <strong>Plaza de la Virgen</strong>.</p>`,
  "160": "<p>A sua aventura continua neste mesmo ponto, com a fonte e a praça à sua frente.</p>",
  "161": "<p>Lembre-se de que deve situar-se com a fonte e a praça à sua frente.</p>",
  "162": `<p>A sua aventura continua a dobrar a esquina, de onde se pode ver a face principal do <strong>Miguelete</strong> e também a porta Barroca da <strong>Catedral de Valencia</strong>; a terceira a ser construída.</p>`,
  "163": "<p>A estas alturas da sua aventura, já terá tido o prazer de ver as nossas rainhas vestidas de gala. Os vestidos de Fallera mantêm viva a artesania da seda em teares manuais.</p>",
  "164": `<p>Nesta aventura comentaremos brevemente cada parte. O primeiro que chama a atenção são os penteados tradicionais das falleras. Sem dúvida, o mais conhecido dos penteados de Espanha.</p>\n<p>O coque de fallera remonta ao séc. XVIII. As mulheres recogiam o cabelo em rabo de cavalo e separavam-no em oito mechas que se "trançavam" em forma de oito, à volta de uma ou duas agulhas grossas. Para finalizar, duas tranças rodeavam o penteado central.</p>\n<p>As agulhas que seguram o coque compõem-se de duas partes: a espada e o cano, em valenciano "Espasa" e "Canó".</p>\n<p>Para completar o penteado, acrescentam-se dois rolos à altura das orelhas que se prendem com dois ganchos.</p>`,
  "165": "<p>O penteado típico de fallera remata-se com um pente traseiro feito à mão em latão prateado ou dourado e duas réplicas do pente principal que se colocam nos rolos laterais.</p>",
  "166": `<p>O traje de fallera, as rainhas e protagonistas nestas festas populares compõe-se de:</p>\n<p>A Saia: Normalmente com motivos florais, é confecionada a base de seda e fios de ouro e prata. Para o traje empregam-se de 10 a 15 metros de seda de diferentes cores.</p>\n<p>O Corpete: Parte superior do traje, fabricado no mesmo tecido que a saia e que é acompanhado de manteletas. O estilo da manga muda dependendo da inspiração do século do traje.</p>\n<p>As manteletas: de materiais como tule, seda, vão bordadas a fio de ouro ou de prata formando preciosos desenhos, compõem-se de duas partes: a superior, que é a que se usa no corpete, e o avental.</p>\n<p>A Camisa e as Anáguas: Costumam ir a conjunto. São a roupa interior, acompanhada de uma estrutura para dar volume à saia.</p>\n<p>Como todo o vestido de gala, complementa-se com brincos de ouro ou prata e "La Joia", que é o remate central que se coloca na parte superior do corpete.</p>`,
  "167": `<p>O Fallero, por sua vez, tem vários trajes diferentes. Falaremos do que consideramos mais tradicional, o traje de Saragüell, reconhecível pelo lenço que cobre a cabeça chamado Mocador.</p>\n<p>O traje de Saragüell compõe-se de:</p>\n<p>Camisa: normalmente branca. Jupetí ou colete: Com motivos semelhantes aos trajes de fallera. Faixi: faixa que rodeia a cintura. Manta: tecido às riscas colocado sobre o ombro. Calces: Normalmente brancas. Espardenyes: Calçado realizado em esparto e algodão típico da região.</p>\n<p>Como terá podido verificar, a maioria das pessoas nestas datas usa o típico Blusón fallero e lenço ao pescoço:</p>\n<p>No séc. XVIII surgiu uma tendência de camisas largas, tanto no tronco como nas mangas; abertas à frente e que costumavam chegar até pouco acima da cintura, chamadas blusones. Os blusones, ao longo do tempo sofreram numerosas variações e quase chegaram a extinguir-se, mas em Valencia conserva-se a tradição de os usar nas Fallas, uma vez que protegem a roupa de baixo de queimaduras acidentais e servem de guarda-pó. O lenço, por sua vez, serve para cobrir o pescoço e o rosto em lugares com muito fumo.</p>`,
  "168": "<p>O seu próximo objetivo fica ao final da praça à sua mão direita.</p>",
  "169": "<p>Já terminou de atravessar a praça?</p>",
  "170": `<p>Situe-se com a Plaza de la Reina às suas costas e Santa Catalina à sua direita, mesmo em frente abre-se a Calle de San Vicente Mártir, que mantém o seu traçado imperturbável desde o século quatro depois de Cristo. <i>À procura do tesouro</i> percorrerá uma das ruas mais antigas de Valencia.</p>\n<p>Uns metros mais adiante abrem-se duas praças: uma à esquerda e uma à direita; começaremos pela praça da esquerda. Encontrará a próxima pista na famosa <strong>Plaza del Ayuntamiento</strong>.</p>`,
  "171": `<p>A <strong>Plaza del Ayuntamiento</strong> transforma-se cada ano num espaço no qual de 1 a 19 de março às duas da tarde tem lugar um espetáculo para os sentidos: um encontro obrigatório no qual os presentes desfrutam da sinfonia do ruído; ouvem-se os masclets, vê-se o fogo e o fumo e cheira-se a pólvora, mas sobretudo sente-se a vibração que sobe pelas pernas e percorre todo o corpo.</p>`,
  "172": `<p>No centro da praça abre-se um espaço diáfano protegido por uma vedação de grande altura, que assegura o espaço para a Mascletà: um disparo pirotécnico que constitui uma composição rítmica e muito ruidosa.</p>\n<p>Ao contrário dos fogos de artifício que procuram a estimulação visual, a Mascletà procura surpreender o espetador com uma harmonia musical gerada através de uma sucessão de explosões rítmicas.</p>`,
  "173": `<p>A Mascletà recebe o seu nome dos famosos Masclets (petardos de grande potência sonora). A denominação "Masclet" deriva do qualificativo "mascle", que em valenciano significa varão e também corajoso.</p>\n<p>Os "mascles" do final do séc. XVIII atiravam petardos aos pés e apostavam para ver quem aguentava mais com os petardos a explodir e parando-os com os pés. O que mais petardos aguentava era o "més mascle" (o mais corajoso) e daí o nome deste evento pirotécnico.</p>\n<p>Com o tempo começaram a amarrar os masclets com cordas e a uni-los entre si através de mechas, para que pudessem ser disparados todos seguidos. Nos "Trams de Tro" (troços de trovoada) era muito comum que os homens corressem debaixo dos Masclets como se acompanhassem o fogo sendo participantes e mantendo essa fama de "mascles" (corajosos) que os precedia.</p>`,
  "174": "<p>A primeira Mascletà incorporou-se ao programa oficial no ano 1945. Nesse mesmo ano, também se realizou a primeira oferta de flores de forma oficial.</p>",
  "175": "<p>Neste breve evento é fundamental que a força das explosões vá de menos para mais com um final apoteótico, tendo como objetivo estimular o corpo através dos ritmos dos Masclets.</p>",
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
