import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "1": "<p>Le Fallas sono state dichiarate Patrimonio Immateriale dell'Umanità dall'Unesco nel 2016.</p>",
  "2": "<p>Si diriga, seguendo la mappa, a girare intorno al monumento. Dal fronte, attraversando la strada, si trova il <strong>Puente de Serranos</strong> indicato sulla sua mappa con il numero <mark>1</mark>.</p>",
  "2-B": "<p>Arrivati al Palau, continui fino alle Torri attraverso le quali monarchi e nobili accedevano al Regno di Valencia. Sulla sua mappa corrisponde al numero <mark>1</mark>.</p>",
  "2-C": "<p>Torni al tracciato delle mura con la corsia abilitata e continui fino alle Torri attraverso le quali monarchi e nobili accedevano al Regno di Valencia, che sulla sua mappa corrispondono al numero <mark>1</mark>.</p>",
  "2-D": "<p>Lasciando questo edificio alla sua destra, si può vedere la <strong>Calle de los Serranos</strong> che separa e delimita i quartieri di \"La Seu\" o <strong>Barrio de la Catedral</strong>, alla sua destra, e il famoso quartiere di \"El Carmen\" alla sua sinistra.</p>\n\n<p>Continui fino alle Torri attraverso le quali monarchi e nobili accedevano al Regno di Valencia, che sulla sua mappa corrispondono al numero <mark>1</mark>.</p>",
  "2-E": "<p>Una volta attraversato il ponte, giri a destra e continui fino alle Torri attraverso le quali monarchi e nobili accedevano al Regno di Valencia, che sulla sua mappa corrispondono al numero <mark>1</mark>.</p>",
  "2-F": "<p>Si trova già in <strong>Calle de los Serranos</strong>? Giri a destra e continui fino alle Torri attraverso le quali monarchi e nobili accedevano al Regno di Valencia. Sulla sua mappa corrispondono al numero <mark>1</mark>.</p>",
  "2-G": "<p>Ci siamo quasi! Continui fino alla fine della strada, giri a sinistra. Da lì si intravedono già le Torri. Sulla sua mappa corrispondono al numero <mark>1</mark>.</p>",
  "3": "<p>Si diriga al suo prossimo punto di interesse, sulla sua mappa corrisponde al numero <mark>13</mark>.</p>",
  "3-B": "<p>Sulla sua mappa corrisponde al numero <mark>13</mark>.</p>",
  "3-C": "<p>Corrisponde al numero <mark>13</mark> sulla sua mappa.</p>",
  "3-D": "<p>Appena qualche passo in questo viale pedonale, alla sua sinistra, spicca un edificio che ricorda gli antichi palazzi musulmani, sulla sua mappa corrisponde al numero <mark>13</mark>.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "3-E": "<p>Con la <strong>Estación del Norte</strong> alle spalle, esca dal recinto e imbocchi la corsia attrezzata che parte alla sua sinistra.</p>\n\n<p>Questa corsia per veicoli di mobilità personale percorre il tracciato dell'antica cinta muraria di Valencia. Superati diversi incroci, vedrà alla sua destra un'area verde con colonne e palme. Ricordi di rispettare le norme del codice della strada!</p>\n\n<p>Prema pausa, poi si rechi o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "4": `<p>Le sue collezioni comprendono circa 10.500 opere che illustrano le principali manifestazioni artistiche del XX secolo.</p>\n\n<p>Esiste un progetto futuro che prevede l'ampliamento con una pelle metallica che avvolgerebbe completamente l'edificio e aggiungerebbe una galleria nella parte posteriore.</p>\n\n<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa ed entrare in questo museo per godersi le esposizioni.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno. Semplicemente prema il tasto corrispondente e continui <i>alla ricerca del tesoro</i>.</p>`,
  "5": "<p>Si diriga, seguendo la mappa, a girare intorno al monumento.</p>\n\n<p>Dal fronte, attraversando la strada, si trova il <strong>Puente de Serranos</strong> indicato sulla sua mappa con il numero <mark>2</mark>.</p>",
  "5-B": "<p>Il prossimo obiettivo della sua Avventura corrisponde sulla sua mappa al numero <mark>2</mark>.</p>",
  "6": "<p>Sulla sua mappa corrisponde al numero <mark>3</mark>.</p>",
  "6-B": "<p>Sulla sua mappa corrisponde al numero <mark>3</mark>.</p>",
  "6-C": "<p>Uscendo dalla piazza, imbocchi la strada che parte alla sua sinistra e la segua fino alla fine. Lì tornerà a un monumento già incontrato in questa Avventura.</p>\n\n<p>Il <strong>Palazzo della Generalitat</strong> che corrisponde al numero <mark>3</mark> della sua mappa.</p>",
  "7": "<p>Sulla sua mappa corrisponde al numero <mark>4</mark>.</p>",
  "7-B": "<p>Sulla sua mappa è indicato con i numeri <mark>4</mark> e <mark>6</mark> rispettivamente.</p>",
  "7-C": "<p>Prenda come riferimento il <strong>Puente del Real</strong> indicato sulla sua mappa con il numero <mark>4</mark> e continui fino al ponte successivo, il <strong>Puente de la Exposición</strong> che corrisponde al numero <mark>5</mark> sulla sua mappa. Ricordi di premere pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "8": "<p>Sulla sua mappa corrisponde al numero <mark>5</mark>.</p>",
  "8-B": "<p>Corrisponde al numero <mark>5</mark> sulla sua mappa.</p>",
  "8-C": "<p>Alzando lo sguardo contemplerà la facciata nord della <strong>Cattedrale di Valencia</strong>.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>5</mark>.</p>",
  "9": `<p>${LOGO} le consiglia di premere pausa e visitare quest'area al suo ritmo.</p>`,
  "9-B": `<p>${LOGO} le consiglia di premere pausa e visitare quest'area al suo ritmo.</p>`,
  "10": "<p>Sulla sua mappa corrisponde al numero <mark>6</mark>.</p>",
  "10-B": "<p>Sulla sua mappa corrisponde al numero <mark>6</mark>.</p>",
  "10-C": "<p>Il suo prossimo punto di interesse in questa Avventura corrisponde al numero <mark>6</mark> sulla sua mappa.</p>",
  "11": "<p>Si diriga al punto 7. Salga fino al centro del ponte seguendo la pista ciclabile.</p>",
  "11-B": "<p>Sulla sua mappa corrisponde al numero <mark>7</mark>.</p>",
  "11-C": "<p>Ora che si trova un po' più vicino, può risolvere la sua prossima sfida.</p>",
  "11-D": "<p>Sulla sua mappa è indicato con il numero <mark>7</mark>.</p>",
  "11-E": `<p>Apra la sua mappa e osservi con attenzione il percorso.</p>\n\n<p>In questa Avventura ${LOGO} le propone di attraversare il ponte che ha davanti e cercare l'accesso che permette di entrare nel famoso <strong>Giardino del Turia</strong> di Valencia.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>7</mark>.</p>\n\n<p>Detto accesso si trova sul lato opposto e a sinistra del ponte, a pochi metri seguendo il muro dell'antico fiume.</p>\n\n<p>Una volta in basso, segua il tracciato della sua mappa; il suo prossimo obiettivo corrisponde al numero <mark>9</mark>.</p>`,
  "12": "<p>Sulla sua mappa corrisponde al numero <mark>8</mark>.</p>",
  "12-B": "<p>Sulla sua mappa corrisponde al numero <mark>8</mark>.</p>",
  "12-C": "<p>Si trova nella <strong>Plaza del Tossal</strong>? Sì? Bene! Sulla sua mappa corrisponde al numero <mark>8</mark>.</p>",
  "12-D": "<p>Prenda come riferimento il <strong>Puente del Real</strong> indicato sulla sua mappa con il numero <mark>8</mark> e continui fino al ponte successivo, che sulla sua mappa corrisponde al numero <mark>9</mark>. Il <strong>Puente de la Exposición</strong>.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito, grazie.</p>",
  "13": "<p>Sulla sua mappa corrisponde al numero <mark>9</mark>.</p>",
  "13-B": "<p>Si trova già nel punto indicato con il numero <mark>9</mark> sulla sua mappa? Bene!</p>",
  "13-C": "<p>Sulla sua mappa corrisponde al numero <mark>9</mark>.</p>",
  "14": "<p>Si diriga al punto numero <mark>10</mark> sulla sua mappa.</p>",
  "14-B": "<p>Sulla sua mappa corrisponde al numero <mark>10</mark>.</p>",
  "14-C": "<p>Sulla sua mappa corrisponde al numero <mark>10</mark>.</p>",
  "15": "<p>Sulla sua mappa corrisponde al numero <mark>11</mark>.</p>",
  "15-B": "<p>Uscendo da questo tessuto urbano irregolare, concentri la sua attenzione alla sua destra. Il suo prossimo obiettivo in questa caccia al tesoro è la famosa <strong>Plaza de la Virgen</strong>.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>11</mark>.</p>",
  "15-C": "<p>Con il municipio di fronte, imbocchi il percorso che si trova alla sua sinistra e segua la mappa fino alla fine del viale, per poi immettersi a sinistra.</p>\n\n<p>Dall'altro lato del viale emerge la <strong>Estación del Norte</strong>, un edificio monumentale in stile modernista inaugurato nel 1917 che sulla sua mappa corrisponde al numero <mark>11</mark>.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "15-D": "<p>Sulla sua mappa corrisponde al numero <mark>11</mark>.</p>",
  "16": "<p>Dal punto 11 sulla sua mappa si può intravedere uno dei luoghi più iconici di Valencia.</p>",
  "17": "<p>Dal numero <mark>12</mark> al <mark>19</mark> si trovano i monumenti che compongono la <strong>Città delle Arti e delle Scienze</strong>, e i numeri <mark>13</mark> e <mark>15</mark> corrispondono ai ponti che completano l'area.</p>",
  "17-B": "<p>Dal numero <mark>18</mark> al <mark>25</mark> si trovano i monumenti che compongono la <strong>Città delle Arti e delle Scienze</strong>, e i numeri <mark>19</mark> e <mark>21</mark> corrispondono ai ponti che completano l'area.</p>",
  "18": "<p>Corrispondono ai numeri <mark>15</mark> e <mark>18</mark> sulla sua mappa.</p>",
  "18-B": "<p>Corrispondono ai numeri <mark>21</mark> e <mark>24</mark> sulla sua mappa.</p>",
  "19": "<p>Sulla sua mappa corrisponde al numero <mark>12</mark>.</p>",
  "20": "<p>Corrisponde al numero <mark>12</mark> sulla sua mappa.</p>",
  "20-B": "<p>Si diriga al punto 12. Salga fino al centro del ponte seguendo la pista ciclabile.</p>\n\n<p>Ricordi di premere pausa quando arriva in cima al ponte; continui fino a metà della sua lunghezza e prema di nuovo il tasto continua.</p>",
  "20-C": "<p>Subito dopo la Stazione Ferroviaria, emerge la <strong>Plaza de Toros</strong>, sulla sua mappa corrisponde al numero <mark>12</mark>.</p>",
  "21": "<p>Corrisponde al numero <mark>14</mark> sulla sua mappa.</p>",
  "21-B": "<p>Al termine del viale, un tesoro architettonico appare alla sua destra e sulla sua mappa corrisponde al numero <mark>14</mark>.</p>\n\n<p>Ricordi di premere pausa, poi si rechi o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "21-C": "<p>Lasciando il portale Barocco della Cattedrale alle spalle, di fronte si apre una piazza che permette di proseguire nella caccia al Tesoro.</p>\n\n<p>Segua il tracciato della sua mappa che la conduce ad attraversare la piazza.</p>\n\n<p>Attraversata la Piazza, alla sua destra, emerge il suo prossimo obiettivo. Un'elegante torre barocca si intravede modestamente a destra.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>14</mark>. Riesce a vederla?</p>",
  "21-D": "<p>Lasciando il portale Barocco della Cattedrale alle spalle, di fronte si apre una piazza che permette di proseguire nella caccia al Tesoro.</p>\n\n<p>Segua il tracciato della sua mappa che la conduce ad attraversare la piazza.</p>\n\n<p>Attraversata la Piazza, alla sua destra, emerge il suo prossimo obiettivo. Un'elegante torre barocca si intravede modestamente a destra.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>10</mark>. Riesce a vederla?</p>\n\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato, grazie.</p>",
  "22": "<p>Sulla sua mappa corrisponde al numero <mark>15</mark>.</p>",
  "22-B": "<p>Sulla sua mappa corrisponde al numero <mark>15</mark>.</p>",
  "22-C": "<p>Concentri la sua attenzione sul complesso del <strong>Bioparc</strong>, numero <mark>15</mark> sulla sua mappa.</p>",
  "22-D": "<p>Come indica la sua mappa, continui fino alla fine della strada e giri a sinistra. Il nostro famoso <strong>Mercado Central</strong> emerge alla sua destra, sulla sua mappa corrisponde al numero <mark>15</mark>.</p>\n\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "22-E": "<p>Si diriga al punto numero <mark>15</mark> sulla sua mappa.</p>",
  "23": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo monumento al suo ritmo.</p>\n\n<p>Ricordi che non c'è fretta, quando si sentirà pronto prema semplicemente continua e prosegua nella sua Avventura <i>Alla ricerca del tesoro</i> valenciano.</p>`,
  "23-B": "<p>Il Palazzo del Marchese di Dos Aguas corrisponde sulla sua mappa al numero <mark>16</mark>.</p>",
  "23-C": "<p>Corrisponde al numero <mark>16</mark> sulla sua mappa.</p>",
  "23-D": "<p>Sulla sua mappa corrisponde al numero <mark>16</mark>.</p>",
  "24": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo monumento al suo ritmo.</p>`,
  "24-B": "<p>Usi il tasto pausa a suo piacimento; quando si sentirà pronto, continui semplicemente a risolvere le nostre sfide mentre scopre la città.</p>\n\n<p>La sua Avventura continua, come indica la sua mappa, alla sua sinistra tornando al tracciato delle mura originali. In particolare verso uno degli ingressi di Valencia che sulla sua mappa corrisponde al numero <mark>17</mark>.</p>",
  "24-C": "<p>Lasciando la <strong>Lonja</strong> alla sua sinistra e il <strong>Mercado Central</strong> alle spalle, si diriga, come indica la sua mappa, al prossimo punto di interesse in questa Avventura, il numero <mark>17</mark>.</p>\n\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "24-D": "<p>Sulla sua mappa corrisponde al numero <mark>17</mark>.</p>",
  "24-E": "<p>Guardando la facciata ad archi ciechi della <strong>Chiesa di Santa Catalina</strong>, il terzo ingresso monumentale a questo tempio risale al 1785 e si trova dietro l'angolo. Questa è anche la sua prossima direzione in questa Avventura.</p>\n\n<p>Presti molta attenzione! La sua mappa le indica di girare intorno a questo monumento e prendere la prima strada che si apre alla sua destra.</p>\n\n<p>Al termine di questa corta e stretta strada, all'altezza del primo piano, si trova il suo prossimo punto di interesse.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>17</mark>.</p>\n\n<p>Ricordi di premere pausa, poi visualizzi il punto indicato e prema il tasto continua una volta nel luogo suggerito.</p>",
  "24-F": "<p>Sulla sua mappa corrisponde al numero <mark>17</mark>.</p>",
  "25": "<p>Seguendo il letto del vecchio fiume, a circa 50 metri si trova la spianata da dove vengono lanciati i fuochi d'artificio.</p>\n\n<p>Se ha avuto l'opportunità di visitarci durante questa festività, avrà potuto constatare che ai valenciani piace la polvere da sparo.</p>",
  "26": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo complesso storico al suo ritmo.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno.</p>`,
  "26-B": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo complesso storico al suo ritmo.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno.</p>`,
  "27": "<p>Sulla sua mappa corrisponde al numero <mark>18</mark>.</p>",
  "27-B": "<p>Sulla sua mappa corrisponde al numero <mark>18</mark>.</p>",
  "27-C": "<p>La sua avventura continua con l'edificio che sulla sua mappa corrisponde al numero <mark>18</mark>.</p>",
  "27-D": "<p>La sua Avventura continua, come indica la sua mappa, seguendo il tracciato delle mura.</p>\n\n<p>Pochi metri più avanti la attendono 3 punti consecutivi nella sua Avventura.</p>\n\n<p>Sulla sua mappa corrispondono ai numeri <mark>18</mark>, <mark>19</mark> e <mark>20</mark> consecutivamente.</p>\n\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "28": "<p>Sulla sua mappa corrisponde al numero <mark>19</mark>.</p>",
  "28-B": "<p>Sulla sua mappa corrisponde al numero <mark>19</mark>.</p>",
  "29": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo complesso storico al suo ritmo.</p>\n\n<p>Può riprendere la sua avventura quando lo riterrà opportuno.</p>`,
  "30": "<p>Una volta deciso di continuare <i>alla ricerca del tesoro</i>, si diriga lungo il lato sinistro del vecchio alveo fino al numero <mark>6</mark> sulla sua mappa.</p>",
  "30-B": "<p>Una volta deciso di continuare <i>alla ricerca del tesoro</i>, si diriga lungo il lato sinistro del vecchio alveo fino al numero <mark>11</mark> sulla sua mappa.</p>",
  "31": "<p>Corrisponde al numero <mark>20</mark> sulla sua mappa.</p>",
  "32": "<p>Sulla sua mappa corrisponde al numero <mark>21</mark>.</p>",
  "32-B": "<p>Sulla sua mappa corrisponde al numero <mark>21</mark>.</p>",
  "32-C": "<p>Segua la sua mappa del tesoro e durante il tragitto, alla sua destra, emerge la prima fontana pubblica di acqua potabile che ci fu in città.</p>\n\n<p>Soprannominata <strong>Fuente del Negrito</strong>, corrisponde al numero <mark>21</mark> sulla sua mappa. Questa è una delle sue ultime tappe in questa avventura.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "33": "<p>Sulla sua mappa corrisponde al numero <mark>22</mark>.</p>",
  "33-B": "<p>Continui fino alla fine della strada dove incrocia la <strong>Calle Caballeros</strong> che corrisponde sulla sua mappa al numero <mark>22</mark>.</p>\n\n<p>Una volta lì, giri a destra e vedrà l'emblematico edificio del <strong>Palazzo della Generalitat</strong> che sulla sua mappa indica il numero <mark>23</mark>.</p>\n\n<p>Prema pausa, poi si rechi al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "33-C": "<p>Sulla sua mappa è indicato con i numeri <mark>22</mark> e <mark>24</mark> rispettivamente.</p>",
  "34": "<p>Sulla sua mappa corrisponde al numero <mark>23</mark>.</p>",
  "34-B": "<p>Sulla sua mappa corrisponde al numero <mark>23</mark>.</p>",
  "35": "<p>Sulla sua mappa corrisponde al numero <mark>24</mark>.</p>",
  "35-B": "<p>Prenda le scale o la rampa che permettono di salire a questo belvedere che sulla sua mappa corrisponde al numero <mark>24</mark>.</p>",
  "36": "<p>Sulla sua mappa è indicato con il numero <mark>25</mark>.</p>",
  "37": "<p>Sulla sua mappa corrisponde al numero <mark>26</mark>.</p>",
  "38": "<p>Si trova già nel punto indicato con il numero <mark>27</mark> sulla sua mappa? Bene!</p>",
  "39": "<p>Sulla sua mappa corrisponde al numero <mark>27</mark>.</p>\n\n<p>Prema Pausa e si avvicini al <strong>Palazzo di Giustizia</strong> per contemplarlo nella sua totalità.</p>",
  "40": "<p>Sulla sua mappa corrisponde al numero <mark>28</mark>.</p>",
  "40-B": "<p>Questo spazio corrisponde sulla sua mappa al numero <mark>28</mark>.</p>",
  "41": "<p>Sulla sua mappa corrisponde al numero <mark>29</mark>.</p>",
  "42": "<p>Sulla sua mappa corrisponde al numero <mark>30</mark>.</p>",
  "43": "<p>Il Palazzo del Marchese di Dos Aguas corrisponde sulla sua mappa al numero <mark>31</mark>.</p>",
  "43-B": "<p>Sulla sua mappa corrisponde al numero <mark>31</mark>.</p>",
  "44": "<p>Sulla sua mappa corrisponde al numero <mark>32</mark>.</p>",
  "44-B": "<p>Si diriga verso il portale, in stile Romanico, della Cattedrale che sulla sua mappa corrisponde al numero <mark>32</mark>; durante il tragitto osservi verso l'alto a sinistra.</p>\n\n<p>Una torre ottagonale della fine del XV secolo svetta dietro la cattedrale.</p>",
  "45": "<p>La sua avventura continua con l'edificio che sulla sua mappa corrisponde al numero <mark>33</mark>.</p>",
  "45-B": "<p>Ammirando il portale più antico della <strong>Cattedrale di Valencia</strong>, rivolga la sua attenzione verso la facciata nord.</p>\n\n<p>Potrà contemplarla in tutto il suo splendore dalla Plaza de la Almoina che si trova alla sua destra.</p>\n\n<p>Si diriga al centro della piazza. Sulla sua mappa corrisponde al numero <mark>33</mark>.</p>",
  "45-C": "<p>La sua avventura continua in questo stesso punto, che sulla sua mappa corrisponde al numero <mark>33</mark>.</p>",
  "45-D": "<p>Si posizioni al centro della piazza che la sua mappa indica con il numero <mark>33</mark>; da lì si può vedere parte della cupola della basilica, quasi 19 metri di diametro e pianta ovale.</p>",
  "45-E": "<p>Sulla sua mappa corrisponde al numero <mark>33</mark>.</p>",
  "45-F": "<p>Sulla sua mappa corrisponde al numero <mark>33</mark>.</p>",
  "46": "<p>Sulla sua mappa corrisponde al numero <mark>34</mark>.</p>",
  "46-B": "<p>Sulla sua mappa corrisponde al numero <mark>34</mark>.</p>",
  "47": "<p>Sulla sua mappa corrisponde al numero <mark>35</mark>.</p>",
  "47-B": "<p>Sulla sua mappa corrisponde al numero <mark>35</mark>. Questa sarà la sua ultima tappa.</p>",
  "48": "<p>Sulla sua mappa corrisponde al numero <mark>39</mark>.</p>",
  "48-B": "<p>Con la Torre di Santa Catalina di fronte guardi, se vuole, alla sua destra.</p>\n\n<p>Concentri la sua attenzione in fondo alla piazza; il suo prossimo obiettivo è il famoso <strong>Miguelete</strong> che svetta sulla Cattedrale.</p>\n\n<p>Questo elegante belvedere corrisponde sulla sua mappa al numero <mark>39</mark>. Riesce a vederlo?</p>",
  "49": "<p>Segua il tracciato della sua mappa che le indica di costeggiare la Cattedrale con la facciata alla sua sinistra.</p>\n\n<p>In altre parole, con il portale barocco della cattedrale di fronte, giri a destra e continui fino a raggiungere il portale romanico del tempio.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>40</mark>.</p>\n\n<p>Ricordi di premere pausa, poi si rechi o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "49-B": "<p>Concentri nuovamente la sua attenzione sulla <strong>Cattedrale di Valencia</strong>, numero <mark>40</mark> sulla sua mappa.</p>",
  "50": "<p>Sulla sua mappa corrisponde al numero <mark>41</mark>.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
