import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "351": "<p>Ammirando questa facciata, continui la sua avventura come indica la sua mappa, nella strada che si apre alla sua sinistra fino al prossimo punto di interesse.</p>\n<p>Non metta in pausa questa audioguida e si diriga al luogo consigliato.</p>\n<p>Ricordi di rispettare il codice della strada. Grazie.</p>",
  "352": "<p>Nel percorso, tra la modernità degli edifici, spicca una delle dieci parrocchie fondazionali della città.</p>\n<p>Come curiosità aggiungeremo che la Iglesia de San Juan de la Cruz fu ridotta in uno stato pietoso durante la Guerra Civile Spagnola avvenuta tra il 1936 e il 1939.</p>\n<p>Il tempio fu saccheggiato, distruggendo al loro passaggio le sue opere d'arte e il suo retablo.</p>\n<p>Gli occupanti utilizzarono anche lo spazio come magazzino di balistica pesante.</p>",
  "353": "<p>Una volta arrivato alla chiesa, concentri la sua attenzione, se non le dispiace, sulle colonne di stile Salomonico della porta architravata. Poiché offriremo maggiori informazioni nel corso di questa Avventura, questo è un luogo per osservarle nel dettaglio.</p>\n<p>Metta in pausa questa audioguida se lo ritiene opportuno.</p>",
  "354": "<p>È già arrivato al punto di interesse? Non ancora? Speriamo che questa breve storia le allieti il viaggio.</p>\n<p>Vale la pena ricordare che nel 1496 il Marchese di Rabassa de Perellós acquistò il titolo di Barone di Dos Aguas per una considerevole somma, e il Baronato fu elevato a Marchesato nel 1699.</p>\n<p>Per tre secoli la famiglia Rabassa de Perellós occupò alti incarichi nel governo politico, accumulando doti ed eredità attraverso matrimoni.</p>\n<p>Questo edificio ha subito, nel corso della sua transizione, sontuose modifiche come dimostrazione di potere e lignaggio.</p>\n<p>Oggi ospita il Museo Nazionale della Ceramica.</p>\n<p>Si posizioni di fronte alla Porta d'ingresso principale che si trova dietro l'angolo.</p>\n<p>Metta in pausa questa audioguida se lo ritiene opportuno.</p>",
  "355": "<p>Ammiri la Cattedrale dall'alto in basso e potrà contemplare tre gallerie sovrapposte formate da aperture con archi a tutto sesto.</p>\n<p>Realizzate nel 1566 in stile Rinascimentale; si tratta di un loggiato-belvedere conosciuto come \"Obra Nueva\" destinato alla contemplazione di processioni e atti pubblici dalla stessa Cattedrale.</p>",
  "356": "<p>La composizione di questo portale risale al XVIII secolo.</p>\n<p>In esso osserviamo un'immagine della Vergine del Rosario dalla quale scendono due flussi d'acqua insieme a due atlanti che rappresentano i due fiumi più importanti di Valencia, il Turia e il Júcar, con chiaro riferimento al nome del marchesato.</p>\n<p>Ai piedi della Vergine possiamo osservare due matrone inginocchiate, una con una cornucopia da cui si riversano frutti (Allegoria dell'agricoltura e della prosperità) e l'altra con un vaso ai suoi piedi pieno di monete (Allegoria della giustizia e magnanimità).</p>\n<p>Nel XIX secolo, l'erede dei marchesi realizza una seconda e spettacolare riforma basata principalmente sulla decorazione interna.</p>\n<p>Modifica anche l'esterno del Palazzo combinando lo stile rococò con motivi cinesi e francesizzanti dell'epoca come: l'uso di grate alle finestre e ai balconi o le enormi armature che sporgono dalla facciata, conferendole l'aspetto attuale.</p>",
  "357": `<p>All'interno si possono ancora osservare carrozze del XVIII secolo così come i saloni ottocenteschi, mentre il secondo piano ospita il museo della ceramica.</p>\n<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo complesso storico al suo ritmo. Può riprendere la sua avventura una volta lo riterrà opportuno.</p>`,
  "358": "<p>Si posizioni con la facciata principale del Palazzo alla sua mano sinistra e continui fino alla fine della strada.</p>\n<p>Arriverà di nuovo alla famosa calle San Vicente Mártir.</p>\n<p>Il tracciato di questa via è rimasto immutato dal quarto secolo dopo Cristo.</p>\n<p>La calle San Vicente Mártir è oggi una delle vie più lunghe della città.</p>\n<p>In questa strada dedicata al Santo Patrono di Valencia giri a sinistra e continui la sua caccia al tesoro fino alla fine della strada.</p>",
  "359": "<p>Prendendo come riferimento la <strong>Plaza del Ayuntamiento</strong> che corrisponde al numero <mark>27</mark> della sua mappa, ma questa volta giri a destra.</p>",
  "359-B": "<p>Prenda come riferimento, di nuovo, lo stesso bivio di prima, ma questa volta giri a destra.</p>",
  "360": "<p>A soli 150 metri, proprio nella piazza successiva, monumenti di epoche diverse si fondono nel presente diventando parte delle nostre vite.</p>\n<p>La sua caccia al tesoro la conduce a iniziare dall'edificio monumentale di sinistra.</p>",
  "361": "<p>Immagini di essere in un'epoca passata!</p>",
  "362": "<p>Questo monumento dedicato al commercio fu edificato nel luogo che occupava il mercato all'aperto esistente dal 1839, già allora chiamato <strong>Mercado Central</strong>, che a sua volta sorgeva sull'antico mercato o souk musulmano ubicato fuori dalle sue mura.</p>\n<p>Il <strong>Mercado Central</strong> che possiamo vedere oggi, inaugurato nel 1928, è situato in un edificio in stile modernista nel quale la ceramica, il ferro, la pietra e le ampie vetrate e cupole decorano interno ed esterno.</p>\n<p>Guardando l'intero edificio, spicca in una delle sue cupole una banderuola a forma di pappagallo.</p>",
  "363": "<p>La leggenda racconta che è un'allusione ai pettegolezzi e alle chiacchiere che sono sempre stati abituali nei mercati e per questo viene soprannominata \"la Pappagalla del Mercato\".</p>",
  "364": "<p>Essendo un edificio in stile moderno, il Mercato si integra perfettamente con gli altri due monumenti importanti della piazza: la Iglesia de San Juan del Mercado e la <strong>Lonja</strong>, entrambi punti iconici della Valencia del XV secolo.</p>\n<p>Cerchi la vetrata con i colori della Señera valenciana sulla facciata dell'edificio. Saprebbe determinare che forma ha? Quadrangolare, Rotonda o Triangolare?</p>",
  "365": "<p>Conosciuta come Iglesia de San Juan del Mercado, è un altro chiaro esempio di parrocchia edificata su una Moschea Araba.</p>\n<p>Un grave incendio nell'anno 1300 dopo Cristo la costrinse a essere ricostruita praticamente dalle macerie.</p>\n<p>Secoli più tardi, un altro incendio fu la causa di una nuova ricostruzione conferendole la fisionomia Gotica attuale, pur mantenendo parte del suo Barocco originale.</p>\n<p>Nel 1936, durante la Guerra Civile, un terzo incendio devastò la chiesa e i suoi effetti furono riparati nel primo quarto del XXI secolo.</p>",
  "366": "<p>Tra l'ornamentazione esterna spicca un grande retablo in pietra della Vergine del Rosario.</p>\n<p>Cosa tiene la Vergine in mano? Un rosario? Un bambino? Forse una corona?</p>",
  "367": "<p>Cosa consegna l'angelo al bambino? È una colomba? Forse un orbe? O forse del cibo?</p>",
  "368": "<p>Un nome meno conosciuto per questo tempio è la \"Chiesa dei Monelli\", perché anticamente questo era il luogo scelto dai ragazzi che, a causa delle circostanze dell'epoca, si dedicavano a fare birichinate e commettevano piccoli furti ai passanti del mercato. Si immagini dei borseggiatori del Medioevo. Sarà questa una professione storica?</p>",
  "369": "<p>Ammirando questo edificio, il prossimo punto di interesse è alle sue spalle, si giri semplicemente.</p>",
  "370": "<p>La <strong>Lonja de la Seda</strong> è il monumento del Secolo d'Oro valenciano.</p>\n<p>A suo tempo, la <strong>Lonja de Valencia</strong> fu una Wall Street del XV secolo.</p>\n<p>Il monumento fu costruito tra il 1482 e il 1497 e fu dichiarato Patrimonio dell'Umanità nel 1996.</p>\n<p>Questo edificio finanziario nacque come <strong>Lonja de la Seda</strong> poiché la famosa \"Via della Seta\", una rotta commerciale che partiva dall'Africa e terminava in Cina o in India, transitava per Valencia.</p>\n<p>Come nota aggiungeremo che nella famosa rotta si commerciava anche con altri materiali come spezie, porcellana, ferro o tè, ma al di là del suo scopo commerciale, la Via della Seta era anche uno spazio di scambio di idee e conoscenze.</p>\n<p>La superficie del monumento si adatta a un lotto rettangolare e supera i 2.000 metri quadrati.</p>\n<p>Il lato sud è rivolto verso la Plaza del Mercado dove lei si trova adesso.</p>\n<p>La facciata est dà verso la calle de Pere Compte, maestro costruttore del monumento.</p>\n<p>Il lato ovest è rivolto verso la calle de los Cordellats dove si può intravedere il patio degli aranci.</p>",
  "371": "<p>E infine, il lato nord verso la calle de la <strong>Lonja</strong> e la sua prossima direzione in questa avventura.</p>",
  "372": "<p>Dalla sua posizione si distinguono quattro parti: a destra la Sala de Contratación o Salone Colonnario dove venivano effettuate le transazioni.</p>",
  "373": "<p>Al centro la Torre a tre corpi utilizzata come cappella (il piano terra) e come prigione (i due piani superiori) nella quale venivano trattenuti i ladri e i mercanti disonesti fino a quando le autorità venivano a prenderli in custodia.</p>",
  "374": "<p>Alla sua sinistra la Sala del Consolato del Mare (1498-1548) costruita successivamente con lo scopo di occuparsi e giudicare gli affari marittimi e commerciali, essendo questo il primo tribunale mercantile fondato in Spagna.</p>",
  "375": "<p>Le proponiamo, da questo punto, di fare insieme una visita nel tempo alla <strong>Lonja de Valencia</strong> attraverso le sue sculture.</p>\n<p>Questa attività consiste nel percepire l'espressività e l'originalità dei suoi portici e gargolle scolpite dai tagliatori di pietra del XV secolo:</p>",
  "376": "<p>L'immagine di alcuni angeli che reggono uno scudo, in uno degli angoli esterni del monumento, segno araldico e celestiale ben lontano dalle altre figure, è probabilmente la cosa più innocente che troverà sulle mura della <strong>Lonja de la Seda</strong>.</p>",
  "377": "<p>Si posizioni di fronte a quello che era il portico principale d'ingresso, chiamato la Porta dei Peccati, si trova a destra della facciata che ha davanti adesso.</p>\n<p>Richiede che le presti una particolare attenzione e sappia leggere \"tra le righe\" i suoi numerosi messaggi sull'oscurità del peccato e quindi del male.</p>\n<p>In questo portale è facile trovare centinaia di figure demoniache; mostri, creature divorate dal male, sortilegi, esseri umani spaventati dalla lussuria e dai peccati capitali, evidenze dell'erotismo con un marcato accento perverso e lascivo; scene che ci conducono all'oscurantismo predominante in questa costruzione civile.</p>",
  "378": "<p>Nel XV secolo, molti commercianti, così come la maggior parte dei cittadini di classe bassa, non sapevano leggere né scrivere; interpretavano quindi le figure come guida per prevenire il peccato.</p>\n<p>Non bisogna dimenticare che nella Capitale del Turia si trovava uno dei maggiori bordelli di tutta Europa. Per questo, a segno di protezione, coronano la porta la Vergine col Bambino.</p>",
  "379": "<p>Pertanto, osservando con attenzione, potrà trovare:</p>\n<p>Il barcaiolo che rema controcorrente: un uomo con il viso triste che manovra una piccola barca di legno fugge controcorrente da un mostro.</p>",
  "380": "<p>Lo ha visto? Allora, il nostro uomo fugge da quella creatura mostruosa chiamata tentazione?</p>",
  "381": "<p>Un albero morto: simbolo del Peccato, si vede tra le due ante della porta e svolge la funzione di elemento centrale.</p>\n<p>Osservi in cima all'albero come 4 uomini nudi si frustano a vicenda.</p>\n<p>Li ha visti tutti? Complimenti!</p>",
  "382": "<p>La <strong>Fuente del Negrito</strong> fu inaugurata nel 1850.</p>\n<p>A quei tempi, le fontane pubbliche erano i recettori del recente arrivo dell'acqua potabile in città.</p>\n<p>L'approvvigionamento di acqua potabile non era ancora generalizzato nelle abitazioni e bisognava raccoglierla nelle fontane pubbliche per uso personale.</p>",
  "383": "<p>Presti ora attenzione ad alcune delle sue gargolle, si allontani un po' per vederle in alto sull'edificio:</p>",
  "384": "<p>A destra un angelo che mostra il suo pene e si accinge a introdurlo in un vaso che regge con l'altra mano. Qualcosa di strano e insolito, non le pare?</p>",
  "385": "<p>Al centro il Barbuto e il Leone:</p>\n<p>Scena originale e contraddittoria nella quale il mansueto è precisamente il leone e non il vecchio barbuto.</p>\n<p>In realtà, qui le evidenze ci conducono alla storia di Sansone che sconfigge un leone, un parallelismo della vita di Gesù in lotta contro il Demonio.</p>",
  "386": "<p>Eccola un'ulteriore sfida!</p>\n<p>Cerchi il fornicatore della <strong>Lonja</strong>!</p>\n<p>In una delle sue finestre, troverà un uomo che fornica con il muro dell'edificio civile più importante dell'epoca.</p>\n<p>Non se ne vede la testa, ma sì i genitali. E molto chiaramente.</p>\n<p>Oppure sta facendo i suoi bisogni.</p>",
  "387": "<p>Lo ha visto? Bravo! Era difficile!</p>",
  "388": "<p>Osservi la mappa con cautela. Dalla sua prospettiva, la conduce a girare intorno alla <strong>Lonja</strong>, dietro l'angolo.</p>\n<p>Il Patio degli Aranci, che dà accesso a una scala di pietra scoperta che conduce al piano principale del Padiglione del Consolato, ampio locale dove un tempo si tenevano le sessioni dei giudici o consoli del commercio e che articola le tre zone dell'edificio.</p>",
  "389": "<p>È il momento giusto per iniziare la sua avventura? Sì, No</p>",
  "390": "<p>Osservi la gargolla della torre.</p>\n<p>A sinistra si trova una donna completamente nuda che tocca il proprio sesso con entrambe le mani.</p>",
  "391": "<p>Una figura priva di sensualità ed erotismo che ricrea l'atto della masturbazione (peccaminoso secondo la morale dell'epoca).</p>\n<p>Torniamo alla lussuria, tema più che predominante nelle sculture che decorano l'edificio.</p>\n<p>Probabilmente è la figura più conosciuta, famosa e sorprendente a prima vista della <strong>Lonja de la Seda</strong> di Valencia.</p>\n<p>Dal XV secolo, la <strong>Lonja</strong> e le sue virtuose figure cariche di oscenità osservano la strada di questa città di Valencia.</p>\n<p>Statue che prendono vita sulle mura di un edificio che non è più nel XV secolo, ma nel XXI, e i cui passanti, guardandole, si fermano e si chiedono: Cosa vogliono dirci?</p>",
  "392": `<p>Più avanti, seguendo l'edificio, troverà la porta d'accesso al monumento.</p>\n<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e di entrare in questo monumento per conoscere meglio la storia della città e le sue tradizioni.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno.</p>`,
  "393": "<p>Si posizioni con la porta d'accesso alla <strong>Lonja</strong> alle sue spalle e si diriga a destra fino ad arrivare all'antica porta che dà accesso all'edificio, è l'ultima che le resta da vedere.</p>\n<p>Una volta lì, osservi attentamente l'ingresso mentre ascolta la storia seguente.</p>",
  "394": "<p>I Santi \"Canonizzati\", ufficialmente, dalla chiesa cattolica sono circa 10.000.</p>\n<p>Un processo lungo che può richiedere molto tempo a causa della complessità che comporta.</p>\n<p>Il candidato deve essere servo di Dio, perciò la sua vita deve essere esemplare e virtuosa.</p>\n<p>Un'istituzione specializzata raccoglie i principali aspetti della sua vita e li organizza in virtù e scritti della persona.</p>\n<p>Se le sue gesta furono eroiche, il Santo Padre lo dichiara \"Persona venerabile\".</p>\n<p>Dopo il primo dei suoi miracoli, detta persona sarà beatificata.</p>\n<p>Per diventare Santo, il candidato doveva aver compiuto almeno 3 miracoli nei quali fosse dimostrata la sua intercessione.</p>",
  "395": `<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e visitare questo monumento al suo ritmo per conoscere un po' di più la storia della città.</p>`,
  "396": `<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e di entrare in questo spazio per conoscere meglio la storia della città.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno, semplicemente prema il tasto corrispondente e continui <i>alla ricerca del tesoro</i>.</p>\n<p>La sua avventura continua in questo stesso punto.</p>`,
  "397": "<p>Dalla sua nuova prospettiva, con la porta del monumento di fronte, giri a sinistra e potrà vedere una piazza aperta.</p>\n<p>Si avvicini, se non le dispiace, alla piazza aperta che ha alla sua sinistra.</p>",
  "398": "<p>Questo è il luogo dove originariamente si trovava la <strong>Lonja de Valencia</strong>.</p>\n<p>Si hanno notizie della sua esistenza dal 1344.</p>\n<p>Nell'antica <strong>Lonja</strong> si commerciava con olio e spezie e rimase in piedi fino al XIX secolo.</p>\n<p>Ma a causa della crescente immigrazione, i commercianti del XV secolo si videro costretti a costruire un edificio più grande nel quale poter ospitare una maggiore capacità per l'inaspettato aumento di attività commerciale avvenuto nella città durante il suo secolo d'oro.</p>",
  "399": "<p>Lei si trova, in questo momento, nel luogo dove, secondo la tradizione, si realizzò uno dei miracoli più conosciuti di Valencia.</p>",
  "400": "<p>Nel 1358 Vicente Ferrer stava predicando davanti alle porte dell'antica <strong>Lonja de Valencia</strong>.</p>\n<p>Il sermone che Vicente Ferrer offriva quel giorno ricordava alla brava gente la necessità di aiutare coloro che soffrivano e morivano di povertà e inedia, e che era necessaria la loro carità.</p>\n<p>L'allora teologo della <strong>Cattedrale di Valencia</strong>, per dimostrarlo, estrasse un fazzoletto e lo lanciò in aria dicendo alla moltitudine di seguire il fazzoletto.</p>\n<p>Lì, dove si sarebbe fermato il fazzoletto, avrebbero trovato persone veramente bisognose della loro carità.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
