import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "167": "<p>De Fallero daarentegen heeft meerdere verschillende kostuums. We spreken over het kostuum dat wij als meest traditioneel beschouwen: het Saragüell-kostuum, herkenbaar aan het hoofd bedekkende doek genaamd <strong>Mocador</strong>.</p>\n<p>Het Saragüell-kostuum bestaat uit:</p>\n<p>Hemd: gewoonlijk wit. <strong>Jupetí</strong> of vest: met motieven die lijken op de fallera-kostuums. <strong>Faixi</strong>: riem om de taille. <strong>Manta</strong>: gestreepte stof die over de schouder gedragen wordt. <strong>Calces</strong>: gewoonlijk wit. <strong>Espardenyes</strong>: schoeisel gemaakt van esparto en katoen, typisch voor de regio.</p>\n<p>Zoals u wellicht heeft opgemerkt, draagt de meeste mensen tijdens deze periode de typische fallero-bloes en de zakdoek om de nek:</p>\n<p>In de 18e eeuw ontstond een trend van losse hemden, zowel in de romp als in de mouwen; open van voren en die gewoonlijk iets langer dan de taille waren, <strong>blusones</strong> genaamd. De blusones ondergingen in de loop der tijd talrijke variaties en kwamen bijna tot uitsterven, maar in Valencia is de traditie bewaard gebleven om ze tijdens de Fallas te dragen, omdat ze de kleding eronder beschermen tegen toevallige brandwonden en als stofjas dienen. De zakdoek dient op zijn beurt om de nek en het gezicht te bedekken op plaatsen met veel rook.</p>",
  "168": "<p>Uw volgende doel bevindt zich aan het einde van het plein aan uw rechterhand.</p>",
  "169": "<p>Heeft u het plein al overgestoken?</p>",
  "170": "<p>Stel u op met het <strong>Plaza de la Reina</strong> achter u en <strong>Santa Catalina</strong> rechts van u; precies voor u opent zich de <strong>Calle de San Vicente Mártir</strong>, die zijn tracé onveranderlijk heeft bewaard sinds de vierde eeuw na Christus. <i>Op zoek naar de schat</i> loopt u door een van de oudste straten van Valencia.</p>\n<p>Enkele meters verderop openen zich twee pleinen: één links en één rechts; we beginnen met het plein links. U vindt de volgende aanwijzing op de beroemde <strong>Plaza del Ayuntamiento</strong>.</p>",
  "171": "<p>De <strong>Plaza del Ayuntamiento</strong> verandert elk jaar in een ruimte waar van 1 tot 19 maart om twee uur 's middags een spektakel voor de zintuigen plaatsvindt: een onmisbare afspraak waarbij de aanwezigen genieten van de symfonie van het lawaai; de masclets worden gehoord, het vuur en de rook gezien, het buskruit geroken, maar bovenal de trilling gevoeld die door de benen omhoog trekt en het hele lichaam doordringt.</p>",
  "172": "<p>In het midden van het plein opent zich een vrije ruimte beschermd door een hoog hek, dat de ruimte veiligstelt voor de <strong>Mascletà</strong>: een pyrotechnisch knalsalvo dat een ritmische en zeer luidruchtige compositie vormt.</p>\n<p>In tegenstelling tot vuurwerk dat visuele stimulatie beoogt, streeft de Mascletà ernaar de toeschouwer te verrassen met een muzikale harmonie gegenereerd door een opeenvolging van ritmische explosies.</p>",
  "173": "<p>De Mascletà dankt zijn naam aan de beroemde <strong>Masclets</strong> (rotjes met een enorme geluidskracht). De benaming «Masclet» is afgeleid van het woord «mascle», dat in het Valenciaans «man» en ook «moedig» betekent.</p>\n<p>Aan het einde van de 18e eeuw gooiden de «mascles» rotjes naar elkaars voeten en wedden wie er het langst uithield. Degene die de meeste rotjes doorstond was de «més mascle» (de moedigste), en daarvan is de naam van dit pyrotechnische evenement afgeleid.</p>\n<p>Met de tijd werden de masclets aan touwen vastgebonden en via lontjes met elkaar verbonden, zodat ze achter elkaar konden worden afgeschoten. In de «Trams de Tro» (trommen van de donder) was het heel gebruikelijk dat mannen onder de Masclets door renden als begeleiding van het vuur, die reputatie van «mascles» (moedigen) hooghoudend.</p>",
  "174": "<p>De eerste Mascletà werd in 1945 opgenomen in het officiële programma. In datzelfde jaar werd ook de eerste bloemenhulde op officiële wijze gebracht.</p>",
  "175": "<p>In dit korte evenement is het essentieel dat de kracht van de explosies geleidelijk toeneemt met een apotheotisch einde, met als doel het lichaam te stimuleren door de ritmes van de Masclets.</p>",
  "176": "<p>Een Mascletà bestaat gewoonlijk uit minstens de volgende delen:</p>",
  "177": "<p>Begin: geheel van zowel geluids- als visuele effecten waarmee het spektakel begint.</p>",
  "178": "<p>Het midden: dit is het centrale deel van de Mascletà, dat in intensiteit en geluidsvolume moet toenemen.</p>",
  "179": "<p>Luchtgedeelte: ontlading van luchtdonders van grotere intensiteit, vergezeld van kleuren.</p>",
  "180": "<p><strong>Terratrèmol</strong> (aardbeving): het deel waarbij de krachtigste Masclets op grote snelheid ontploffen.</p>",
  "181": "<p>De Fallas, bij uitstek de feesten van het vuur, vol kleur en spectaculaire details, zijn al eeuwen barok gebleven.</p>\n<p>Na diepgaander onderzoek naar het beheersen van de chemie van de explosieve componenten, bleef Valencia een voortdurende verbetering doormaken totdat de huidige Mascletà evolueerde.</p>\n<p>Om veiligheidsredenen is de grens momenteel vastgesteld op 120 kilogram buskruit per Mascletà.</p>\n<p>De Valencianen onderscheiden de muzikale harmonie en beoordelen elke Mascletà met applaus of uitfluitingen voor de artiest.</p>",
  "182": "<p>Het is zeker dat de Valencianen origineel zijn: dit is immers werk dat een heel jaar in beslag neemt.</p>",
  "183": "<p>Hoe ontstaat het monument in onze eeuw?</p>",
  "184": "<p>Elk jaar wordt in elke fallero Casal een eerste idee bedacht voor het fallero-monument. Vervolgens wordt het idee samengevat in een schets of tekening die moet worden goedgekeurd zodat de kunstenaar een 3D-miniatuur in klei kan maken.</p>\n<p>Vanaf dat moment begint de falla zich als een levend wezen te ontwikkelen dat zorg en volledige toewijding vereist. In het atelier wordt de realisatie van het fallero-monument op basis van het initiële maquette als een puzzel opgedeeld; het boetseren van de «Ninots» begint — de losse figuren die het geheel aanvullen en die tijdens de «Plantà» met grote precisie op hun juiste plaats moeten worden geassembleerd.</p>\n<p>Een jury zal de beste Fallas uitkiezen en deze zullen worden bekroond.</p>\n<p>Elk jaar zal één en slechts één figuur worden gered van het vuur; dit staat bekend als de «Ninot indultat» (het genade-model).</p>\n<p>In het Fallero Museum kunt u de geredde Ninots zien, evenals de evolutie van ons festival.</p>",
  "185": "<p>De Fallas van de 21e eeuw beelden scènes uit van afkeurenswaardige sociale feiten, ironie, sociale kritiek en satire waarbij het sociale en politieke leven altijd met gevoel voor humor wordt gekarikaturiseerd.</p>\n<p>De populariteit van deze feesten is wijdverbreid en ze worden tegenwoordig gevierd in meer dan 88 gemeenten van de Valenciaansche Gemeenschap.</p>",
  "186": "<p>Is het een goed moment om uw Avontuur voort te zetten? Vergeet niet dat u de pauzeknop naar wens kunt gebruiken en hem kunt indrukken wanneer u dat geschikt acht. Daarna drukt u gewoon op start en gaat u door met het oplossen van onze uitdagingen terwijl u de stad ontdekt.</p>",
  "187": "<p>Stel u op met de fontein achter u en het plein voor u om door te gaan <i>op zoek naar de schat</i>.</p>",
  "188": "<p>Met het <strong>Gebouw van het Ayuntamiento</strong> achter u, aan de andere kant van het plein, rijst een gebouw op dat opvalt door zijn grote toren.</p>\n<p>Ga, als u zo vriendelijk wilt zijn, naar het gebouw dat op uw kaart overeenkomt met nummer <mark>13</mark>.</p>",
  "189": "<p>Bekijk uw schatzoekerkaart. Zoals deze aangeeft, gaat uw Avontuur verder op het andere historische plein dat we eerder noemden.</p>\n<p>Om daar te komen, stel u op met het <strong>Gebouw van het Ayuntamiento</strong> aan uw linkerhand en ga terug tot de beroemde <strong>Calle San Vicente Mártir</strong>. Op slechts 150 meter, precies op het volgende plein, komen monumenten uit verschillende tijdperken samen en vormen deel van ons heden en ons leven.</p>\n<p>Uw schattenjacht begint bij het monumentale gebouw aan de linkerhand.</p>\n<p>De <strong>Mercado Central</strong> correspondeert op uw kaart met nummer <mark>15</mark>.</p>\n<p>Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "190": `<p>Als u er bent tijdens de openingsuren, nodigt ${LOGO} u uit op pauze te drukken en de lokale gastronomie te ontdekken die deze prachtige ruimte biedt. Dit is een perfect punt om foto's van uw Avontuur te maken, dat u van dit zelfde punt kunt hervatten zodra u het geschikt acht.</p>`,
  "191": "<p>Het woord falla is afgeleid van het middeleeuwse Valenciaans; het was het woord waarmee de fakkels werden aangeduid die bovenop wachttorens, langs de wegen of ter verlichting van een feest werden geplaatst. Later werd het woord Falla gebruikt om te verwijzen naar de vreugdevuren en de verlichting die werden aangestoken in de avond voor de bijbehorende feesten.</p>",
  "192": "<p>Op dit punt heeft u wellicht al een van de meer dan 300 muziekbandas gehoord die de fallero-commissies inhuren om hen bij de diverse fallero-evenementen te begeleiden.</p>\n<p>De muzikale cultuur is diep geworteld omdat het een zeer belangrijk element is voor de volksvieringen. Tijdens de Fallas hoort men niet alleen bands; er zijn ook groepen bestaande uit dulzainas en tamborils, blaas- en slaginstrumenten die uitsteken boven de andere bandas.</p>",
  "193": "<p>De dulzainas en tamborils, of zoals we het graag in het Valenciaans noemen <strong>Dolçaina i Tabalet</strong>, zijn traditionele instrumenten die deel uitmaken van de soundtrack van onze audiogidsen.</p>",
  "194": "<p>Als de avond valt is ook muziek belangrijk; er worden kermisfeesten met livemuziek georganiseerd en de typische «discomóviles» (mobiele disco's), te beluisteren in verschillende buurten van de stad en opengesteld voor iedereen die er van wil genieten.</p>",
  "195": "<p>En als u denkt dat het tijd is om te gaan slapen, doe dit pas na het genieten van enkele bunyols de carabassa met chocolade terwijl u de merkwaardige manier bewondert waarop de falleros hun buren wekken door rotjes op de grond te gooien die ontploffen bij het raken van de vloer.</p>",
  "196": "<p>Sommigen geloven nog steeds dat de werkelijke oorsprong van deze viering (de Fallas) ligt in de oude rituelen waarmee het lenteequinox werd gevierd, het moment van het jaar waarop de dag net zo lang duurt als de nacht.</p>\n<p>21 maart is door diverse millenniumoud culturen aangewezen als een dag met groot energetisch vermogen. Een datum die de terugkeer van Persephone uit de Hades markeert, dat wil zeggen de bloei en het leven.</p>\n<p>Omdat de Katholieke Kerk er geen raad mee wist, werd het gekerstend door de feestdag van Sint-Jozef te vieren. Zelfs zo waren er in de 19e eeuw momenten waarop de Fallas verboden waren vanwege hun satirisch karakter gericht op de autoriteiten van die tijd.</p>",
  "197": "<p>Stel u op met de toegangsdeur tot de <strong>Lonja</strong> voor u.</p>",
  "198": "<p>Laat dit plein rechts van u; de Schatkaart geeft u aan door te gaan via de straat die voor u ligt. Zet deze audiogids niet op pauze en let aan uw rechterhand terwijl u de straat doorloopt.</p>",
  "199": "<p>Volg uw schatzoekerkaart; tijdens de route verschijnt aan uw rechterhand de eerste openbare drinkwaterfontein die de stad kende.</p>\n<p>Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "200": `<p>Welkom! Vanuit ${LOGO} heten we u van harte welkom. Allereerst willen we u bedanken voor het kiezen van dit avontuur, waarbij u door de tijd reist, van de Romeinse tijd tot het Valencia van de 21e eeuw, een moderne stad vol licht en kleur. <i>Op zoek naar de schat</i> is een buitenactiviteit, zelf-geleid, interactief en educatief, ideaal voor individueel of teamgenot. We moedigen u ook aan om de Valenciaanse cultuur en gastronomie op uw eigen tempo te ontdekken door gewoon op de pauzeknop te drukken.</p>`,
  "201": "<p><i>Op zoek naar de schat</i>, dankzij de beschikbaarheid van de inhoud in meerdere talen, is ook een uitstekend hulpmiddel om een taal te oefenen die u aan het leren bent, of zelfs om u in een nieuwe taal onder te dompelen.</p>",
  "202": "<p>Onder ons motto «De keuze is en zal altijd de uwe zijn», bieden we de mogelijkheid om op het gewenste tempo vooruit te gaan, pauzes te nemen wanneer nodig of de ervaring zelfs om te vormen tot een vriendschappelijke wedstrijd om te zien wie het avontuur als eerste voltooit. Zodra u besluit dat het het juiste moment is, druk op de Start-knop en ga door met het oplossen van onze uitdagingen terwijl u de stad blijft ontdekken. Elke aanwijzing leidt u naar een nieuwe bestemming met nieuwe raadsels die prachtige historische en architectonische schatten van Valencia onthullen.</p>",
  "203": `<p>Om uw ervaring nog verder te verrijken, moedigt ${LOGO} u aan de bezochbare monumenten te betreden als onderdeel van de ervaring van dit Avontuur, zoals musea, markten en vele andere interessante plaatsen, sommige gratis en andere voor een symbolische prijs, hoewel de toegangskaartjes voor de laatste niet inbegrepen zijn bij de aankoop van dit avontuur.</p>`,
  "204": "<p>Als u dat gepast vindt, zouden we graag dit avontuur beginnen met een korte introductie over de Valenciaanse geschiedenis, ligging en gastronomie. Dit zal ons een overzicht geven van de route die ons te wachten staat.</p>",
  "205": "<p>Vergeet niet dat de tijdslimiet van dit avontuur 60 uur is vanaf het begin.</p>",
  "206": "<p>Vergeet niet dat de tijdslimiet van dit avontuur 150 uur is vanaf het begin.</p>",
  "207": "<p>Dit Avontuur dat u gaat beleven begon heel, heel lang geleden. Eeuwen voor de komst van de Romeinen werd de plek waar Valencia nu ligt bezet door de Iberiërs. We spreken over de zesde eeuw voor Christus.</p>",
  "208": "<p>Dat is heel lang geleden als u er even over nadenkt!</p>",
  "209": "<p>Verschillende eeuwen later, vanaf het jaar 138 voor Christus, werd de stad doorheen zijn geschiedenis sterk geromaniseerd en ontving de naam «Valentia».</p>\n<p>De latere Islamitische invloed was echter nog groter, meer bepaald van het jaar 711 tot 1238 na onze tijdrekening. Dit maakt een totaal van ongeveer 500 jaar.</p>",
  "210": "<p>De invloed was zo groot dat de bevolking voornamelijk Islamitisch was. Valencia ontving gedurende deze periode de naam «Balansiya».</p>",
  "211": "<p>Pas in 1238 veroverde koning Jaime I van Aragón Valencia terug, kerstende de stad en maakte haar tot een koninkrijk onafhankelijk van het Koninkrijk Aragón.</p>\n<p>Het Koninkrijk Valencia ontving «Los Fueros», waarmee het koninkrijk een eigen politieke en juridische identiteit kreeg.</p>",
  "212": "<p>Het einde van de regionale autonomie kwam met Felipe V in de 18e eeuw.</p>\n<p>In de Successieoorlog steunde het Valenciaanse volk zijn vijand aartshertog Carlos.</p>\n<p>Felipe V schafte na het winnen van de oorlog de Fueros af en voegde Valencia toe aan de nationale regering.</p>\n<p>In 1982 werd Valencia uitgeroepen tot hoofdstad van de Valenciaansche Gemeenschap.</p>",
  "213": "<p>Valencia, de hoofdstad van de Turia, is momenteel de derde meest bevolkte stad van Spanje. Ze ligt in het oosten van het Iberisch Schiereiland, aan de oever van de Rivier de Turia en wordt omspoeld door de Middellandse Zee, die de regio voorziet van een gematigd klimaat met zachte winters en zo'n 340 zonnige dagen per jaar.</p>",
  "214": "<p>Wat bevindt zich in de omgeving van de stad?</p>",
  "215": "<p>Vanuit Valencia vertrekken een groot aantal ingerichte paden voor fiets- en natuurliefhebbers. Op ongeveer tien kilometer ten zuiden van de stad bevindt zich het natuurpark van de <strong>Albufera</strong> van Valencia.</p>\n<p>De <strong>Albufera</strong> is een van de grootste moerassen van Spanje met een oppervlakte van 2100 hectare, waaraan nog 14.000 hectare moerasland moet worden toegevoegd bestemd voor rijstteelt, de belangrijkste teelt van de stad, samen met chufa, sinaasappel, mispel en kaki.</p>",
  "219": "<p>Zoals u kunt vermoeden, kadert de Valenciaanse gastronomie binnen het mediterrane dieet.</p>\n<p>Wat de Valenciaanse keuken echter kenmerkt, is het gebruik van rijst en het wereldberoemde paradepaardje: de Paella.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
