import { readFileSync, writeFileSync } from 'fs';
const FILE = 'js/parrafos-textos/parrafos-texto-frances.json';
const existing = JSON.parse(readFileSync(FILE, 'utf8'));
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const batch = {
  "701": "<p>Êtes-vous déjà en face du Marché Central ? Oui ? Bien ! Continuons ?</p>",
  "702": "<p>Êtes-vous déjà au point indiqué par le numéro <mark>11</mark> sur votre carte ? Bien ! Continuons à la recherche du trésor !</p>",
  "703": "<p>Super ! Continuons avec la chasse au trésor ! Regardez autour de vous et vous pourrez voir des ruines qui se distinguent parmi la végétation du jardin du Turia. Pouvez-vous les voir ? Oui ? Parfait, car nous espérons que l'histoire qui suit va vous surprendre.</p>",
  "704": "<p>Êtes-vous déjà au point indiqué par le numéro <mark>6</mark> sur votre carte ?</p>",
  "704-B": "<p>Êtes-vous déjà au point indiqué par le numéro <mark>3</mark> sur votre carte ?</p>",
  "705": "<p>Êtes-vous déjà au point indiqué par le numéro <mark>24</mark> sur votre carte ?</p>",
  "706": "<p>Êtes-vous déjà au point indiqué par le numéro <mark>76</mark> sur votre carte ?</p>",
  "707": "<p>De quoi est faite l'Orxata ? De chufa, de riz ou d'orge ?</p>",
  "708": "<p>Au cours de votre aventure, vous pourrez terminer de découvrir le majestueux Parc de Cabecera, en passant par l'ancien moulin du Soleil, rappelons qu'autrefois les moulins étaient des bâtiments indispensables pour moudre le grain et ainsi produire la farine nécessaire pour élaborer, entre autres, pâtisseries et boulangeries.</p>",
  "709": "<p>Le Molí del Sol, construit en 1880, fut le premier des 18 moulins de l'acequia de Rascanya et le dernier moulin hydraulique édifié dans la huerta valencienne, profitant du dénivelé du terrain pour moudre le blé et le riz. Après l'enterrement de l'acequia dans les années 1980, le bâtiment tomba en désuétude jusqu'à sa restauration dans l'actuel Parc de Cabecera, point exact où naît aujourd'hui la Route Verte du Parc Fluvial du Turia. Ce chemin cyclopédestre s'étend sur environ 30 km vers l'ouest par des pistes forestières, en suivant le cours naturel du fleuve Turia.</p>",
  "710": "<p>Le Musée d'Histoire de Valence est probablement l'un des meilleurs endroits pour continuer à apprendre sur cette culture méditerranéenne dans laquelle vous vous trouvez aujourd'hui.</p>",
  "711": "<p>Le prochain point d'intérêt de votre aventure est un endroit très spécial dans lequel l'eau a une grande importance. Le centre d'expositions et musée NaTuria agit comme un lieu de rencontre citadin pour promouvoir la durabilité urbaine, servir de centre de formation et offrir des ressources éducatives sur l'écologie et l'environnement.</p>",
  "712": "<p>Sur votre carte, il correspond au numéro <mark>68</mark>.</p>",
  "713": "<p>NaTuria est un espace éducatif et environnemental dont l'objectif est de rapprocher la nature des citoyens et de promouvoir des habitudes durables dans la vie quotidienne à travers des expositions, des cours, des ateliers et des visites guidées axées sur la durabilité, le recyclage, la biodiversité et la qualité de vie urbaine ; dans son environnement proche se trouve un petit barrage ou azud qui retient l'eau de l'ancien lit du fleuve et fait partie du projet paysager du parc, en recréant un environnement aquatique qui évoque l'ancien Turia avec une végétation de rive, une faune associée comme les oiseaux et les amphibiens, et des zones de promenade et d'observation, où se trouve également le Moulin del Tell, un ancien moulin à farine restauré intégré dans les activités de NaTuria lui-même, dans lequel sont expliquées son histoire, la vie durable traditionnelle et le rapport historique de Valence avec l'eau, de sorte que cet ensemble — le barrage et l'environnement aquatique — fonctionne principalement comme un élément éducatif et symbolique qui rappelle le lien de la ville avec son fleuve et promeut l'apprentissage sur la gestion durable de l'eau.</p>",
  "VIV1": `<p>${LOGO} vous recommande de suivre le cours de votre carte et de parcourir la promenade.</p>\n\n<p>À mi-chemin, à main droite se trouvent les ruines de ce qui fut en son temps la Tour de la Reine de l'ancien palais aujourd'hui disparu.</p>`,
  "VIV2": "<p>Ensuite, vous verrez un grand monticule de terre.</p>\n\n<p>C'est un endroit parfait pour prendre de magnifiques photographies des vues qu'offre le jardin.</p>\n\n<p>Le monticule porte le nom d'Elio, Capitaine Général des Royaumes de Valence et de Murcie au XIX<sup>e</sup> siècle.</p>\n\n<p>Curieusement, Elio fut décapité des années plus tard en ce même lieu.</p>\n\n<p>Ce monticule fut créé avec les ruines du palais, sur lequel furent plantés des arbres et des fleurs. C'est sur le mont Elio que furent créés les jardins de Viveros de la ville.</p>\n\n<p>Ces points correspondent aux numéros <mark>2</mark> et <mark>3</mark> respectivement.</p>",
  "VIV3": `<p>Un peu plus loin, à main gauche sur la promenade, nous pouvons observer la maison du jardinier en chef qui correspond au numéro <mark>4</mark> sur votre carte.</p>\n\n<p>Aujourd'hui, elle remplit la fonction de bureaux des jardins.</p>\n\n<p>Continuez jusqu'au bout de la promenade des palmiers et vous trouverez un circuit urbain amusant dans lequel les plus petits apprennent, tout en jouant, à interpréter les signaux de la route.</p>\n\n<p>Sur votre carte, il correspond au numéro <mark>5</mark>.</p>\n\n<p>${LOGO} vous invite à appuyer sur pause et à parcourir ce circuit à votre propre rythme, c'est un endroit parfait pour obtenir de belles photos de votre aventure en reprenant depuis ce même point, dès que vous le souhaitez.</p>`,
  "VIV4": "<p>Placez-vous face au circuit, tournez à votre gauche et pénétrez dans la Calle Jardineros Mayores.</p>\n\n<p>Sur votre carte, il correspond au numéro <mark>6</mark>.</p>\n\n<p>Le tracé est une zone pavée et bordée de spécimens de Jacarandas, originaires du Brésil, et de Podocarpus provenant de Chine.</p>\n\n<p>Cette zone est utilisée lors de divers événements, comme, par exemple, la foire du livre.</p>\n\n<p>Continuez ce chemin jusqu'au bout et vous verrez s'ouvrir une esplanade.</p>\n\n<p>Sur la gauche, on peut voir un modèle typique de l'architecture rurale valencienne. La célèbre Alquería de Canet correspond au numéro <mark>7</mark> sur votre carte. En face de l'alquería se trouve un musée, sur votre carte il correspond au numéro <mark>8</mark>.</p>",
  "VIV5": "<p>À quoi est dédié le musée ? Aux sciences naturelles ? Peut-être à l'architecture ? Ou peut-être à l'histoire ?</p>",
  "VIV6": "<p>Dans les années 70, ce bâtiment était connu sous le nom de « restaurant de Viveros », aujourd'hui il abrite en son sein, entre autres, une collection donnée en 1889 par Don José Rodrigo Botet, ingénieur valencien, qui rassembla un grand nombre de restes paléontologiques trouvés lors de ses fouilles sur le continent américain.</p>\n\n<p>Parmi les spécimens remarquables, on trouve l'énorme ours des cavernes (le mégathérium) de Patagonie argentine, des empreintes pétrifiées de dinosaures, des restes fossiles, des squelettes, des tatous cuirassés, des coquillages marins et de nombreux insectes.</p>\n\n<p>Le tout est complété par des panneaux explicatifs, des zones didactiques et audiovisuels.</p>",
  "VIV7": "<p>La carte de ces jardins vous invite à vous éloigner de ce point pour y revenir plus tard.</p>\n\n<p>Pour l'instant, dirigez-vous vers la droite où vous attend une zone qui rappelle les jardins de Versailles.</p>\n\n<p>Sur votre carte, il correspond au numéro <mark>9</mark>.</p>",
  "VIV8": "<p>Un grand lampadaire, l'un des rares existant dans la ville, nous laisse entrevoir notre prochain objectif.</p>",
  "VIV9": "<p>Quelques mètres plus loin, dans la Rosaleda, émerge une grande fontaine circulaire provenant de la Plaza de la Reina entourée d'environ six mille roses de différentes espèces, ainsi que d'autres espèces ornamentales.</p>\n\n<p>La rosaleda, qui fut plantée en 1974 et rénovée en 2010, correspond sur votre carte au numéro <mark>10</mark>.</p>",
  "VIV10": `<p>En sortant par le côté opposé de la rosaleda se trouvent les pépinières chargées de fournir les espèces botaniques et la flore à la ville.</p>\n\n<p>${LOGO} vous encourage à appuyer sur pause et à explorer cette zone botanique à votre propre rythme, pouvant reprendre votre chasse depuis le musée qui correspond au numéro <mark>8</mark> sur votre carte.</p>\n\n<p>N'oubliez pas que le bouton pause peut être utilisé à votre guise et être pressé quand vous le souhaitez. Ensuite, appuyez simplement sur démarrer et continuez à résoudre nos défis tout en découvrant la ville.</p>\n\n<p>Les Jardins du Real offrent une large gamme de sculptures : El Reposo, La Dama de Elche, Las Cuatro Falsas Estaciones, Despertar et La Fuente de Neptuno, sont quelques exemples que vous pourrez trouver au cours de votre parcours.</p>`,
  "VIV11": "<p>Placez-vous, si vous le voulez bien, entre l'alquería et le musée ; numéros <mark>7</mark> et <mark>8</mark> respectivement.</p>\n\n<p>Avec l'Alquería à votre main gauche et le Musée à votre droite, observez que devant vous s'ouvre une place destinée aux événements musicaux ; tels que concerts et danses typiques. Au bout de cet espace, un timide lac se présente sur votre droite.</p>\n\n<p>C'est le célèbre lac des cygnes, où des oiseaux migrateurs, tels que cigognes et canards, se reposent dans cet habitat protégé pour reprendre des forces avant de prendre leur envol. Sur votre carte, il correspond au numéro <mark>11</mark>.</p>",
  "VIV11-B": "<p>Au bout de cet espace, un timide lac se présente sur votre droite. Dirigez-vous vers le lac des cygnes. Sur votre carte, il correspond au numéro <mark>11</mark>.</p>",
  "VIV11-C": "<p>C'est le célèbre lac des cygnes, où des oiseaux migrateurs, tels que cigognes et canards, se reposent dans cet habitat protégé pour reprendre des forces avant de prendre leur envol.</p>",
  "VIV12": "<p>Quelle figure décore la fontaine ? Est-ce un canard ? Une cigogne ? Ou peut-être un poisson ?</p>\n\n<p>Appuyez sur pause et rendez-vous à l'endroit indiqué pour compléter votre défi.</p>",
  "VIV13": "<p>En suivant la forme du jardin, une sculpture dédiée à l'eau accueille l'un des recoins les plus discrets du parc. Sur votre carte, il correspond au numéro <mark>12</mark>.</p>",
  "VIV14": "<p>Un enfant, bien plus qu'un élément décoratif : c'est une œuvre symbolique qui représente la relation humaine avec l'eau. Situé dans un environnement historiquement lié à l'irrigation et à la huerta, il rappelle l'importance essentielle de l'eau comme base de la vie, sans laquelle n'existeraient ni l'agriculture ni les villes. La composition renforce ce message : l'eau symbolise l'origine de la vie, la mère les soins et la protection, et l'enfant la continuité et l'avenir.</p>",
  "VIV15": `<p>Derrière la fontaine s'ouvre un portail de style baroque dédié à Saint Julien.</p>\n\n<p>Cet espace intime cache deux portails vers les anciens jardins du palais que Comtes et Ducs avaient depuis leur demeure.</p>\n\n<p>Aujourd'hui, c'est un coin romantique et tranquille où l'on peut se détendre et profiter de la paix et de la sérénité dans une ville en constant mouvement.</p>\n\n<p>Sur votre carte, il correspond au numéro <mark>12</mark>.</p>\n\n<p>Avec le portail et la fontaine dans votre dos, aventurez-vous dans la zone des Ficus, arbres de grande envergure originaires d'Australie.</p>\n\n<p>${LOGO} vous encourage à explorer cette zone tranquillement.</p>\n\n<p>Reprenez cette aventure depuis la sortie des Jardins du Real, en utilisant la même porte par laquelle vous êtes entré. Sur votre carte, elle correspond au numéro <mark>1</mark>.</p>`
};
const merged = { ...existing, ...batch };
writeFileSync(FILE, JSON.stringify(merged, null, 2), 'utf8');
console.log('Total entradas:', Object.keys(merged).length);
