import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "551": "<p>La Sua Avventura continua pochi metri più avanti, è una tappa curiosa perché questa è davvero un tesoro culturale valenciano.</p>\n<p>Segua il corso della via. Arrivando alla fine, alla Sua sinistra, si trova la famosa <strong>Casa dei gatti</strong>.</p>",
  "552": "<p>Sulla facciata spicca una tipica riproduzione di una casa valenciana che funge da ingresso per il rifugio che ospita i gatti del quartiere.</p>\n<p>Anticamente, i felini mantenevano la città pulita dai topi, portatori di varie malattie.</p>\n<p>Oggi, a Valencia esistono colonie feline distribuite in tutta la città. Nel corso di questa Avventura ne attraverserà alcune, ma per rispetto, benessere e riposo degli animali, menzioneremo solo questa.</p>\n<p>Prema pausa, poi si rechi al punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito. Grazie.</p>",
  "553": "<p>Curioso, vero? Una riproduzione di una tipica casa valenciana che funge da portale d'ingresso per i gatti del <strong>quartiere del Carmen</strong>.</p>\n<p>La <strong>Casa dei Gatti</strong> fu ufficialmente ricostruita nel 2003, tuttavia si sa che i felini occupavano già questo sito dal 1904.</p>\n<p>Concentri la sua attenzione sulla piccola targa in ceramica situata a destra della porta.</p>",
  "554": "<p>Quanti gatti si possono vedere rappresentati nel pannello?</p>",
  "555": `<p>Nell'antica Balansiya musulmana, i gatti erano venerati.</p>\n<p>La storia racconta che persino Maometto tagliò un lembo della sua tunica per non svegliare la sua gatta che si era addormentata al suo fianco.</p>\n<p>Tale era la venerazione che erano considerati esseri puri.</p>\n<p>Questa rappresentazione allude ai 4 gatti rimasti vivi dopo la conquista di Rodrigo Díaz de Vivar, più noto come el Cid Campeador.</p>\n<p>Antiche leggende popolari raccontano che l'annientamento dei gatti fu dovuto alla credenza cristiana che il gatto fosse un animale dell'altro mondo, diabolico, nonché portatore di sfortuna.</p>\n<p>Ma non possiamo fare a meno di pensare che in tempi di carestia e specialmente dopo un assedio, la gente mangiasse quel che poteva pur di sopravvivere.</p>\n<p>La leggenda del pannello recita: "In memoria dei quattro gatti che vissero nel <strong>Quartiere del Carmen</strong> nell'anno 1094. Non si sentì mai un miao più forte di un altro".</p>`,
  "556": "<p>Lo scultore Alfonso Yuste Navarro, autore della riproduzione di questa facciata a tre piani di architettura tipicamente valenciana, ha incluso ogni tipo di dettaglio: lo scudo araldico sull'architrave della porta e l'insegna della compagnia assicurativa antincendio, tra gli altri.</p>\n<p>La casa ha addossata un ingresso a un'antica rimessa per carrozze, che in realtà è una fioriera.</p>",
  "557": "<p>Concentri la sua attenzione, se è così gentile, sui due pannelli in ceramica che si trovano alla sua destra, un po' sopra l'altezza della sua testa.</p>",
  "558": "<p>Il più basso indica il livello raggiunto dall'acqua durante l'alluvione del 1957.</p>\n<p>Quale altezza indica questo pannello?</p>",
  "559": "<p>Il pannello superiore indica la stima del livello del mare negli anni a venire, a causa della costante evoluzione del cambiamento climatico. Quale anno indica il pannello superiore?</p>",
  "560": "<p>Bravo, è appena arrivato alla metà della sua avventura!</p>",
  "561": `<p>Osservi il percorso della sua mappa. In fondo alla via in cui si trova, prenda la prima a sinistra e subito dopo la prima a destra.</p>\n<p>Da quel momento, ${LOGO} Le raccomanda di fare uso del suo veicolo di mobilità personale, rispettando in ogni momento la segnaletica stradale.</p>`,
  "562": "<p>Osservi il tracciato della via in cui si trova e cerchi di immaginare la città fortificata... Le mura si estendevano a sinistra e a destra di ogni torre difensiva.</p>\n<p>Il muro fu iniziato nel 1356 e ha un perimetro di circa 4 chilometri. Nel XIX secolo, a causa dell'espansione della città, le mura dovettero essere abbattute per migliorarne la salubrità, poiché soffocavano la popolazione e impedivano di costruire i nuovi e necessari quartieri di espansione.</p>\n<p>Concretamente, la demolizione fu effettuata il 20 febbraio 1865.</p>\n<p>Nonostante gli anni, il suo tracciato è ancora oggi percepibile.</p>\n<p>Nell'introduzione di questa Avventura, avevamo menzionato che a Valencia si possono ancora vedere 2 delle torri che difendevano gli accessi alla città.</p>\n<p>La prima è il punto di partenza della sua avventura. La seconda si trova seguendo il tracciato dell'antica cinta muraria in direzione opposta.</p>",
  "562-B": `<p>Le famose <strong>Torres de Quart</strong>, oltre che ingresso alla città, servirono a vari scopi nel corso della loro storia: nel 1562 come deposito di polvere da sparo e nel 1626 una delle torri fu destinata a prigione per prostitute. ${LOGO} Le fornirà informazioni dettagliate su quest'area nella sua Avventura numero 5.</p>`,
  "563": "<p>Proprio alla sua sinistra sorge l'<strong>Istituto Valenciano di Arte Moderna</strong> (IVAM) creato alla fine del 1986, che dispone di due spazi per le sue mostre. Sulla sua mappa corrisponde al numero <mark>57</mark>.</p>",
  "563-B": "<p>Proprio alla sua destra sorge l'<strong>Istituto Valenciano di Arte Moderna</strong> (IVAM) creato alla fine del 1986, che dispone di due spazi per le sue mostre. Sulla sua mappa corrisponde al numero <mark>21</mark>.</p>",
  "563-C": `<p>Proprio alla sua sinistra sorge l'<strong>Istituto Valenciano di Arte Moderna</strong> (IVAM) creato alla fine del 1986, che dispone di due spazi per le sue mostre.</p>\n<p>Le sue collezioni comprendono circa 10.500 opere che illustrano le manifestazioni artistiche fondamentali dell'arte del XX secolo.</p>\n<p>Se si trova in orario di visita, ${LOGO} Le consiglia di premere pausa ed entrare in questo museo per godere delle sue mostre.</p>\n<p>Può riprendere la sua avventura quando lo riterrà opportuno. Prema semplicemente il pulsante corrispondente e continui <i>alla ricerca del tesoro</i>.</p>`,
  "564": "<p>Ritorni al tracciato originale delle mura e si diriga a destra. Pochi metri più avanti emerge l'ultimo punto di interesse in questa Avventura.</p>\n<p>Ricordi di premere pausa, poi si rechi al punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "565": "<p>Sebbene il Museo della Preistoria abbia oggi più di 80 anni, la sua attuale ubicazione risale al 1982.</p>\n<p>A tale scopo fu utilizzata l'antica Casa della Beneficenza, includendo nello stesso spazio il Museo Etnologico valenciano.</p>\n<p>Nel 1995 furono aperte al pubblico le attuali Sale della Preistoria, della Cultura Iberica e del Mondo Romano. Il museo organizza anche laboratori didattici, pertanto non si limita alle sue sale, ma si estende anche ai siti archeologici attualmente in fase di scavo.</p>",
  "566": `<p>Essendo l'Etnologia la scienza che studia i popoli e le loro culture in tutti i loro aspetti e relazioni, il Museo Valenciano di Etnologia raccoglie studi che definiscono il rapporto tra le persone e l'ambiente in cui agiscono.</p>\n<p>Come, ad esempio: l'abitare nello spazio domestico, il convivere negli spazi di incontro e lo spazio lavorativo nei luoghi di lavoro.</p>\n<p>Il Museo sviluppa anche programmi di ricerca, offre i servizi di una biblioteca specializzata e collabora con numerosi comuni nel recupero e nella diffusione del patrimonio locale.</p>\n<p>Se si trova in orario di visita, ${LOGO} Le consiglia di premere pausa ed entrare in questo monumento per conoscere meglio la storia della città e le sue tradizioni.</p>`,
  "567": "<p>Appena qualche passo avanti, un magnifico edificio di colore bianco è il suo prossimo punto di interesse nella ricerca del tesoro.</p>",
  "568": "<p>Questo edificio fu costruito nel 1882 per accogliere i bambini orfani della città.</p>\n \n<p>Nella facciata in stile neogotico spicca un grande balcone in pietra con un'ampia finestra ad arco e al di sopra un grande stemma.</p>",
  "569": "<p>Cosa corona lo stemma? È una corona? Forse un pipistrello? O forse un drago?</p>",
  "570": "<p>Nel corso di questa avventura, la sua mappa la porterà a salire e attraversare questo ponte, adattato per la sua sicurezza con pista ciclabile e zone pedonali, per scoprire alcuni dei tesori architettonici che offre la storica città di Valencia. Ma non ancora per il momento, la sua avventura si svolge nell'alveo di questo antico fiume trasformato in giardino.</p>",
  "571": "<p>Le <strong>Torres de Quart</strong> sono una delle porte più conosciute della cinta muraria medievale cristiana di Valencia.</p>\n<p>Nel 1442, anno del loro completamento, le torri cilindriche erano considerate le più adatte a resistere all'uso dell'artiglieria.</p>\n<p>Le <strong>Torres de Quart</strong> furono edificate in stile gotico, sebbene per la loro funzionalità difensiva, la decorazione non sia un elemento caratteristico di questo monumento.</p>",
  "572": "<p>Nell'anno 1808, Valencia si impose contro le truppe invasori di Napoleone in un movimento patriottico, respingendo il nemico e costringendolo a ritirarsi più volte.</p>\n<p>Nel XIX secolo il monumento veniva utilizzato come prigione, questa volta militare.</p>\n<p>Il fatto che le <strong>Torres de Quart</strong> fossero in uso come prigione è ciò che le salvò dalla demolizione delle mura di Valencia nel 1865.</p>\n<p>Nel 2007 fu effettuata una pulitura totale del complesso e furono aperte al pubblico.</p>",
  "573": "<p>Come può constatare, ancora oggi si possono vedere i segni degli impatti di palla di cannone e le perforazioni di proiettili di fucile dell'artiglieria francese durante la guerra d'indipendenza.</p>\n<p>Quante perforazioni di proiettili riesce a contare?</p>",
  "574": "<p>Non si affatichi, sono state conteggiate circa 132 impronte di cannone e oltre 1.000 perforazioni di fucile.</p>",
  "575": `<p>Ammirando la facciata principale, concentri la sua attenzione sul lato sinistro, dove si può ancora contemplare un tratto di mura e la famosa statua del "Palleter". Il Palleter fu un venditore di fiammiferi che, secondo la tradizione, il 23 maggio 1808 dichiarò guerra a Napoleone Bonaparte.</p>`,
  "576": "<p>Questa Avventura la riporta al XV secolo, periodo in cui Valencia si distinse ancora una volta.</p>\n<p>Nel 1409 fu creata un'istituzione per la cura dei malati psichici; il recinto dell'attuale Biblioteca Pubblica fu il primo ospedale psichiatrico d'Europa.</p>",
  "577": `<p>Prima di arrivare, una via piena di negozi alla sua sinistra potrebbe attirare la sua attenzione.</p>\n<p>La calle Colón offre ogni tipo di possibilità per gli amanti dello shopping.</p>\n<p>In fondo alla via, la <strong>Stazione del Nord</strong> (ferroviaria) e la <strong>Plaza de Toros</strong> spiccano in questo viale che traccia oggi il luogo occupato dalle mura di Valencia nel XIV secolo.</p>\n<p>${LOGO} Le fornirà informazioni dettagliate su quest'area nella sua Avventura numero 5.</p>`,
  "578": "<p>La sua Avventura la conduce, di nuovo, nell'antica Valencia.</p>\n<p>Ha appena attraversato sotto il scomparso Portal de Torrent, conosciuto popolarmente come La Porta degli Innocenti.</p>\n<p>Durante questa Avventura, percorrerà la famosa Calle Hospital che si trova di fronte a Lei in questo momento.</p>\n<p>Non metta in pausa questa audioguida e osservi alla sua destra mentre percorre la via.</p>",
  "579": "<p>Nella <strong>Calle del Hospital</strong>, una discreta fontana ci dà il benvenuto.</p>\n<p>Che forma ha la fontana?</p>\n<p>È una conchiglia? Forse un pesce? O forse una persona?</p>",
  "580": "<p>L'Eremo di Santa Lucía situato alla sua destra le indica che sta andando nella direzione giusta.</p>\n<p>L'antico tempio fu completato nel 1511.</p>\n<p>In quale anno iniziarono i lavori? Guardi sulla facciata!</p>",
  "581": "<p>Curioso, vero? Il campanile ha un solo muro in cui si aprono gli spazi per collocare le campane.</p>\n<p>Questo elemento architettonico noto come espadaña fu opera di Luis Peseto.</p>\n<p>Oggi le sue due campane suonano con melodie moderne e rallegrano la vita dei passanti.</p>",
  "582": "<p>La facciata che si può vedere oggi fu realizzata da due diversi maestri muratori tra il 1860 e il 1865.</p>\n<p>Sebastián Monleón Estellés ricevette l'incarico di una facciata con tre porte. Sotto l'espadaña brilla in una nicchia un busto in bronzo di Santa Lucía.</p>\n<p>Grazie a José Esteve due sculture moderne arricchiscono la facciata: quella di sinistra simboleggia la virtù e quella di destra il martirio.</p>",
  "583": "<p>Come ultime note, menzioniamo anche che l'eremo fu dichiarato Monumento Storico-Artistico Nazionale nel 1963 e nel 2007 Bene di Interesse Culturale.</p>\n<p>Saprebbe dirmi l'anno del suo ultimo restauro?</p>\n<p>Sono sicuro che lo ha già visto!</p>",
  "584": "<p>Faccia particolare attenzione!</p>\n<p>Il suo prossimo obiettivo non è ancora il giardino.</p>\n<p>Continui fino al Colegio del Arte Mayor de la Seda.</p>",
  "585": "<p>La «Ruta della Seta» fu una rete di rotte commerciali dal II secolo avanti Cristo.</p>\n<p>Si estese attraverso il continente asiatico e si consolidò in Europa nel XV secolo nei regni ispanici e nel Mediterraneo occidentale; pertanto, l'industria della seta è un'attività che già ai tempi dei musulmani aveva grande importanza e godeva di grande prestigio in tutto Al-Andalus.</p>\n<p>Data la sua posizione, la città di Valencia nell'epoca di Al-Ándalus era già celebre per le sue manifatture seriche.</p>\n<p>Nel XIV secolo esistevano già setaioli locali, prevalentemente ebrei, ma fu dal XV al XVIII secolo che la leadership di Valencia come principale centro della seta spagnola era indiscutibile; di fatto, la coltivazione del gelso precedette quella dell'arancio in tutta la regione.</p>\n<p>L'industria serica fu una delle più potenti della città, arrivando a contare più di 3.000 telai.</p>\n<p>Oggi i costumi da Fallera mantengono viva l'artigianato della seta su telai manuali.</p>\n<p>Per il vestito si impiegano da 10 a 15 m di seta di più di 20 colori, oltre a filo d'argento e d'oro.</p>",
  "586": "<p>Con una facciata di 29 metri, l'edificio che può vedere ora fu acquistato dai setaioli valenciani nel 1492. Subì diverse trasformazioni nel corso dei secoli, l'ultima delle più importanti, poiché passò dallo stile gotico al barocco.</p>\n<p>In quale anno furono effettuati quei lavori? Fu nel 1756, forse nel 1492, o nel 1982?</p>\n<p>Ha bisogno di un suggerimento? Guardi la facciata dell'edificio.</p>",
  "587": "<p>All'interno di questo edificio si trova il Museo della Seta, con esposizioni di tessuti classici valenciani del XVII e XVIII secolo nelle sue sale con pavimento in ceramica tradizionale.</p>\n<p>Anche una collezione composta da innumerevoli documenti accumulati nel corso di cinque secoli, rendendo questo il museo con l'archivio corporativo più importante d'Europa.</p>",
  "588": `<p>${LOGO} Le consiglia di addentrarsi nel parco dell'ospedale che ha lasciato alle spalle e di percorrerlo al proprio ritmo, ascoltando le notevoli tracce della sua storia.</p>\n<p>Non metta in pausa questa audioguida e si diriga, se è così gentile, al punto indicato. Grazie.</p>`,
  "589": "<p>Antiche leggende raccontano che un frate valenciano, di nome Joan Gilabert Jofré, assistette al lapidamento di un cittadino con disabilità mentale che era stato lasciato in balia di alcuni ragazzini, e si interpose salvandogli la vita con quel gesto.</p>\n<p>Dopo quell'atto, dichiarato miracoloso, furono proposte nuove misure per controllare e studiare le persone in uno stato simile, creando, senza saperlo, il primo ospedale psichiatrico d'Europa.</p>",
  "590": "<p>Alla fine del XV secolo fu effettuata un'ampliazione per accogliere malati non dementi.</p>\n<p>Il parco in cui sta entrando ha le sue origini nel 1512, periodo in cui Fernando el Católico decretò l'integrazione di tutti i piccoli ospedali di Valencia in uno solo, lasciando questo spazio come Ospedale Provinciale. Un ospedale ben dotato, ben gestito, con grande prestigio e strutture adeguate.</p>\n<p>A tale scopo furono costruite due infermerie a pianta cruciforme.</p>\n<p>Questa disposizione a forma di croce è molto ben congegnata, poiché dalla torre centrale era possibile controllare contemporaneamente le quattro ali dell'ospedale.</p>",
  "591": "<p>Anni dopo, nel 1875, furono costruiti nuovi edifici e fu insediata la facoltà di medicina, che rimase in questa sede fino al 1948.</p>\n<p>Nel 1960 fu aperto un nuovo ospedale a Valencia con capacità sufficiente per le necessità della popolazione.</p>\n<p>Da quel momento, il vecchio ospedale provinciale cadde in disuso e gli interessi urbanistici entrarono in gioco.</p>",
  "592": "<p>Molti edifici, come la chiesa e uno degli edifici a forma di croce, non poterono essere salvati dalla demolizione.</p>\n<p>La dichiarazione del complesso come Monumento Storico-Artistico Nazionale nel novembre del 1963 riuscì a salvare una parte di questo grande centro ospedaliero, lasciando in piedi lo spazio che oggi occupa la biblioteca, la cappella e vari resti sparsi nei giardini che compongono lo spazio.</p>",
  "592-B": `<p>Nel 2009 si decide di riordinare detti giardini utilizzando gli elementi rimasti sparsi, così nel 2012 viene creato questo giardino archeologico che possiamo vedere oggi.</p>\n<p>Lo spazio ospita resti trovati negli scavi provenienti dall'antico ospedale rinascimentale e altri elementi di interesse, come: resti della facciata dell'antica Facoltà di Medicina, l'Eremo di Santa Lucía e il Museo Valenciano dell'Illustrazione (Muvim). Nel sottosuolo del museo si conservano resti dell'antica cinta muraria cristiana della città, demolita nel 1865.</p>\n<p>${LOGO} La incita a mettere in pausa questa audioguida e Le consiglia di passeggiare in questo giardino al proprio ritmo.</p>\n<p>Utilizzi il pulsante di pausa a suo piacimento. Quando sentirà che è il momento giusto, semplicemente continui a risolvere le nostre sfide mentre scopre la città.</p>\n<p>La sua avventura continua dall'ingresso principale della biblioteca.</p>`,
  "593": "<p>Questa Avventura mescola la tradizione delle Fallas e la storia di Valencia. L'obiettivo è conoscere l'origine, la tradizione e la storia di questa festività che distingue a Valencia il mese di marzo da tutti gli altri.</p>\n<p>Durante il percorso scoprirà diversi punti iconici indispensabili affinché le Fallas siano possibili così come le conosciamo oggi.</p>",
  "594": "<p>Orientate verso Ovest, le <strong>Torres de Quart</strong>, oltre che ingresso alla città, hanno servito a vari scopi nel corso della loro storia, come, ad esempio: nel 1562 come deposito di polvere da sparo, o nel 1626 una delle torri fu destinata a prigione per prostitute.</p>",
  "595": "<p>Apra e osservi la sua mappa.</p>\n<p>Con l'ingresso di Valencia alle spalle, dall'altro lato del viale, si apre l'antico cammino che conduceva alle torri.</p>\n<p>Dopo aver attraversato il viale, prenda la seconda via a destra.</p>\n<p>Questa Avventura la porta a scoprire uno dei tesori botanici della città. L'ingresso si trova dietro l'angolo.</p>\n<p>Ricordi, è la seconda via a destra!</p>\n<p>Sulla sua mappa corrisponde al numero <mark>64</mark>.</p>\n<p>Ricordi di premere pausa, poi si rechi o visualizzi il punto indicato e prema nuovamente il pulsante continua una volta giunto nel luogo suggerito.</p>",
  "596": `<p>L'attuale Giardino Botanico ha origine non lontano da qui, in un antico orto di piante medicinali dove si insegnava la botanica.</p>\n<p>Fondato nel 1567, il Giardino Botanico dell'Università di Valencia è il più antico d'Europa.</p>\n<p>Secoli dopo, con il sostegno di varie istituzioni, l'Università di Valencia acquistò il terreno su cui si trova il centro di insegnamento.</p>\n<p>Vale la pena notare che il Giardino Botanico stesso è irrigato dall'acequia di Rovella, che fornisce al sottosuolo i nutrienti necessari per la vita che ospita al suo interno.</p>\n<p>Fortunatamente, il professore di Medicina José Pizcueta migliorò le strutture durante i quasi 40 anni in cui fu responsabile della sua supervisione.</p>\n<p>Con l'obiettivo di effettuare esperimenti di climatizzazione furono costruite diverse strutture come una serra in legno, una zona ombreggiata per proteggere le piante dal sole o persino diverse serre con temperature e umidità differenti che favorirono la crescita di specie importate da tutti i continenti.</p>\n<p>Se si trova in orario di visita, ${LOGO} La incita a premere pausa ed entrare a scoprire la biodiversità che offre questo meraviglioso spazio.</p>\n<p>Al suo interno si possono vedere più di 3.000 specie vegetali diverse, alcune delle quali tra le più antiche d'Europa, che convivono in un microclima fresco nel cuore di Valencia.</p>\n<p>La sua Avventura continua dall'ingresso del Giardino Botanico.</p>`,
  "597": "<p>Bravo! Quest'area è libera da indizi e sta per concludere la sua Avventura! Non metta in pausa questa audioguida e si diriga al punto indicato.</p>",
  "597-B": "<p>Bravo! Quest'area è libera da indizi e sta per concludere la sua Avventura! Non metta in pausa questa audio guida e si diriga al punto indicato.</p>",
  "598": "<p>Osservi la sua mappa e noti che la sua avventura la riporta all'antico alveo del fiume. Con l'ingresso principale del giardino botanico di fronte a Lei, giri a sinistra e giri l'angolo, per seguire la parete del giardino botanico fino alla fine della via. Una volta lì, attraversi il viale e scenda fino al Parco del Turia.</p>\n<p>Presti particolare attenzione lungo il percorso, perché alla sua sinistra apparirà uno dei giardini più discreti della città. Sulla sua mappa è indicato con il numero <mark>65</mark>.</p>\n<p>Questo giardino è ispirato alla leggenda di Ercole che, nella sua ultima impresa, dovette rubare le mele d'oro dal Giardino delle Esperidi.</p>\n<p>Prema pausa e si diriga al punto 65 della sua mappa. Quando sarà lì, prema il pulsante corrispondente per riprendere la sua avventura. Grazie.</p>",
  "599": "<p>La favola greca racconta che le Esperidi erano le ninfe incaricate di custodire il giardino delle mele d'oro che la Dea Gea (o Gaia) (Madre Terra) donò come regalo di nozze a Era e Zeus.</p>\n<p>Il celebre Ercole, noto per la sua grande forza, compì molte imprese, così come diversi atti criminali.</p>\n<p>Dopo uno di essi, Ercole dovette compiere dodici fatiche come penitenza imposta. L'ultima delle sue fatiche fu rubare dette mele dopo aver ucciso il drago dai cento capi che Gea aveva posto a guardia.</p>\n<p>Dopo aver sconfitto il drago Ladone, le Esperidi, spaventate, si trasformarono in pioppi, salici e olmi.</p>",
  "600": `<p>Questo discreto giardino adatta l'antico mito greco alle specie arboree nascenti del nostro territorio. In questo caso, l'oggetto prezioso sono le arance valenciane.</p>\n<p>Il giardino inaugurato nel 2000 con una superficie di 4.700 metri quadrati include una collezione di agrumi composta da più di 50 varietà diverse.</p>\n<p>All'interno si trovano anche tre sculture in bronzo: la Dea Venere, lo stesso Ercole e la metamorfosi della ninfa in albero.</p>\n<p>Se si trova in orario di visita, ${LOGO} La incita a mettere in pausa questa audioguida e Le consiglia di passeggiare in questo giardino al proprio ritmo.</p>\n<p>Utilizzi il pulsante di pausa a suo piacimento. Quando lo deciderà, semplicemente continui a risolvere le nostre sfide mentre scopre la città.</p>`,
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
