import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "539": `<p>A segunda fase que corresponde aos dois corpos superiores, muito mais carregados que o corpo inferior, foi construída no séc. XVIII.</p>\n<p>Observe que no segundo corpo se abrem três hornacinas com três figuras femininas, estas representam Santa Teresa de Jesus, uma das monjas fundadoras da Ordem dos Carmelitas Descalços e Santa Madalena de Pazzi, uma nobre toscana e monja Carmelita.</p>`,
  "540": `<p>A terceira hornacina, a mais ornamentada, abriga a Virgem do Carmo, que dá nome a este templo.</p>\n<p>O que porta a Virgem nos braços? Um coração? Uma Pomba? Ou talvez porta o menino Jesus?</p>`,
  "541": `<p>Mais acima, no terceiro corpo, abre-se um vão ladeado por duas colunas salomónicas.</p>\n<p>As colunas recebem este nome pela crença da época, segundo a qual assim foram as colunas do Templo de Salomão.</p>\n<p>A escultura corresponde a São José com o menino nos braços, assim como as três esculturas de baixo também está datada no séc. XVIII.</p>`,
  "542": `<p>A sua aventura continua uns metros mais adiante nesta mesma rua, pelo que continuamos a recomendar chegar ao próximo ponto de interesse a pé.</p>\n<p>Por favor, não pare esta audioguia e dirija-se ao seu próximo objetivo.</p>`,
  "543": "<p>O Convento do Carmo tem as suas origens em 1281, depois da morte do rei Jaime primeiro, quando os Carmelitas Calçados se estabeleceram em Valencia.</p>",
  "544": `<p>Promovidos por Frei Arnaldo de Bascher, os carmelitas estabeleceram-se no <strong>Barrio de Roteros</strong>, que naquela época ficava extramuros das antigas muralhas árabes da cidade.</p>`,
  "544-B": `<p>Promovidos por Frei Arnaldo de Bascher, os carmelitas estabeleceram-se no <strong>Barrio de Roteros</strong>, que naquela época ficava extramuros das antigas muralhas árabes de que se fala mais em profundidade na nossa Aventura número 2.</p>`,
  "545": `<p>Se centrar a sua atenção na fachada, ainda pode ver um painel cerâmico que data de 1779 e no qual se representa Santa Teresa de Jesus.</p>\n<p>Como pode comprovar, a Santa cobre-se com o hábito da Ordem do Carmo.</p>\n<p>Mas esta Santa não porta coroa, em seu lugar cobre-se com uma birreta; dado que é Doutora da Igreja.</p>`,
  "546": "<p>O que porta Santa Teresa nas suas mãos? Uma Pena e um livro? Talvez uma espada? Ou talvez uma jarra de água?</p>",
  "547": `<p>O antigo convento, hoje em dia visitável, tomou o nome de Real Mosteiro da Mãe de Deus do Carmo. Articula-se à volta de dois claustros: o mais antigo de estilo gótico dos séc. XIV e XV e o segundo, de época renascentista, séc. XVI e XVII.</p>\n<p>No interior do claustro gótico erguem-se em cada uma das suas faces quatro arcos apontados cobertos com abóbada de cruzaria.</p>\n<p>Como detalhe aportaremos que, se centrar a sua atenção no final dos arcos, na mísola das colunas, verá detalhes talhados em pedra; tais como escudos heráldicos sustidos por anjos, assim como animais monstruosos.</p>\n<p>No interior do claustro, à direita, ainda pode ver pintado na parede o custo da renovação do claustro de 1670; tempo em que se suprimiram os confessionários.</p>`,
  "548": `<p>Em 1839, o convento deixou de exercer como tal. A partir de 1848, instauraram-se as sedes da Escola de Belas Artes e da Escola de Artes e Ofícios Artísticos.</p>\n<p>O espaço, por sua vez, servia também de armazém e sala de exposições de vários artistas da época. Essas obras criaram a primeira sede do <strong>Museo de Bellas Artes</strong> de Valencia.</p>\n<p>O edifício foi declarado Histórico Artístico Nacional em 1983. Em 1989, começou uma restauração na qual se poderia adaptar o espaço para albergar uma sala de exposições temporárias dependente do <strong>Museo de Bellas Artes</strong>, mas essas obras prolongaram-se mais de 10 anos; concretamente até o ano 2011.</p>`,
  "549": `<p>Durante as obras de restauração aparecem numerosos restos arqueológicos no subsolo do convento.</p>\n<p>Um dos mais chamativos são os restos de uma habitação islâmica, que fica visível, graças a um painel de vidro que permite ver este tesouro que nos oferece a história da cidade.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e desfrute desta sala de exposições.</p>`,
  "550": "<p>Quanto custa a entrada a este museu?</p>",
  "551": `<p>A sua Aventura continua uns metros mais adiante, é uma paragem curiosa porque este é realmente um tesouro cultural valenciano.</p>\n<p>Siga o curso da rua. Chegando ao final, à sua mão esquerda, encontra-se a famosa <strong>Casa dos Gatos</strong>.</p>`,
  "552": `<p>Na fachada ressalta uma recriação típica de casa valenciana que serve de entrada para o refúgio que abriga os gatos do bairro.</p>\n<p>Antigamente, os felinos mantinham a cidade limpa de ratos que são portadores de diversas doenças.</p>\n<p>Hoje em dia, em Valencia existem colónias felinas repartidas por toda a cidade. Durante o transcurso desta Aventura passará por algumas, mas pelo respeito, bem-estar e descanso dos animais, mencionaremos apenas esta.</p>\n<p>Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido. Obrigado.</p>`,
  "553": `<p>Curioso, não é verdade? Uma recriação de uma casa típica valenciana que serve de porta de entrada aos gatos do <strong>bairro do Carmen</strong>.</p>\n<p>A <strong>Casa dos Gatos</strong> foi reconstruída de forma oficial em 2003, no entanto, sabe-se que os felinos já ocupavam este solar desde 1904.</p>\n<p>Centre a sua atenção na pequena placa de cerâmica situada à direita da porta.</p>`,
  "554": "<p>Quantos gatos podem ver-se representados no painel?</p>",
  "555": `<p>Na antiga Balansiya muçulmana, os gatos eram venerados.</p>\n<p>Conta a história que até Maomé cortou um pedaço da sua túnica para não acordar a sua gata que tinha adormecido ao seu lado.</p>\n<p>Tal era a veneração que eram considerados seres puros.</p>\n<p>Esta representação faz alusão aos 4 gatos que ficaram vivos após a conquista de Rodrigo Diaz de Vivar, mais conhecido como o Cid Campeador.</p>\n<p>Antigas lendas populares contam que a aniquilação dos gatos se deveu à crença cristã de que o gato era um animal do outro mundo, diabólico, assim como portador de mau agouro.</p>\n<p>Mas não podemos deixar de pensar que em época de fome e especialmente após um cerco, as pessoas comiam o que podiam para sobreviver.</p>\n<p>A lenda do painel diz: "Em memória dos quatro gatos que viveram no <strong>Barrio del Carmen</strong> no ano 1094. Nunca se lhes ouviu um miau mais alto do que outro".</p>`,
  "556": `<p>O escultor Alfonso Yuste Navarro, autor da recriação desta fachada de três alturas de arquitetura típica valenciana, incluiu todo o luxo de detalhes: o escudo heráldico no lintel da porta e o cartaz da seguradora de incêndios, entre outros.</p>\n<p>A casa tem adossada uma entrada a uma antiga cocheira, que é na realidade uma jardineira.</p>`,
  "557": "<p>Centre a sua atenção, se faz favor, nos dois painéis cerâmicos que estão à sua direita, um pouco acima da altura da sua cabeça.</p>",
  "558": `<p>O mais baixo indica o nível que alcançou a água na cheia de 1957.</p>\n<p>Que altura marca este painel?</p>`,
  "559": "<p>O painel superior indica a estimativa do nível da água do mar em anos vindouros, devido à constante evolução das alterações climáticas. Que ano indica o painel superior?</p>",
  "560": "<p>Bravo, acaba de chegar à metade da sua aventura!</p>",
  "561": `<p>Observe o percurso do seu mapa. No final da rua onde se encontra, tome a primeira à esquerda e imediatamente a primeira à direita.</p>\n<p>A partir desse momento, ${LOGO} recomenda-lhe que faça uso do seu veículo de mobilidade pessoal respeitando em todo o momento a sinalização vial.</p>`,
  "562": `<p>Observe o traçado da rua onde se encontra e tente imaginar a cidade fortificada... Os muros estendiam-se à esquerda e à direita de cada torre defensiva.</p>\n<p>O muro iniciou-se em 1356 e tem uns 4 Quilómetros de perímetro. No séc. XIX, devido à expansão da cidade, a muralha teve que ser demolida para melhorar a sua salubridade uma vez que asfixiava a população e impedia a construção dos novos e necessários alargamentos.</p>\n<p>Concretamente, a demolição levou-se a cabo a 20 de fevereiro de 1865.</p>\n<p>Apesar dos anos, o seu traçado é hoje percetível.</p>\n<p>Na introdução desta Aventura, mencionávamos que em Valencia ainda podem ver-se 2 das torres que defendiam os acessos à cidade.</p>\n<p>A primeira é o ponto de partida da sua aventura. A segunda situa-se seguindo o traçado da antiga muralha em direção oposta.</p>`,
  "562-B": `<p>As famosas <strong>Torres de Quart</strong>, para além de entrada à cidade, serviram para vários propósitos no seu percurso: em 1562 foi armazém de pólvora e em 1626 uma das suas torres foi destinada a prisão para prostitutas. ${LOGO} proporcionará-lhe informação detalhada sobre essa área na sua Aventura número 5.</p>`,
  "563": `<p>Mesmo à sua esquerda, emerge o <strong>Instituto Valenciano de Arte Moderno</strong> (IVAM) criado no final de 1986, e que conta com dois espaços para as suas exposições. No seu mapa corresponde ao número <mark>57</mark>.</p>`,
  "563-B": `<p>Mesmo à sua direita, emerge o <strong>Instituto Valenciano de Arte Moderno</strong> (IVAM) criado no final de 1986, e que conta com dois espaços para as suas exposições. No seu mapa corresponde ao número <mark>21</mark>.</p>`,
  "563-C": `<p>Mesmo à sua esquerda, emerge o <strong>Instituto Valenciano de Arte Moderno</strong> (IVAM) criado no final de 1986, e que conta com dois espaços para as suas exposições.</p>\n<p>Os seus fundos constam de umas 10.500 obras que ilustram as manifestações artísticas básicas da arte do séc. XX.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre neste museu e desfrute das suas exposições.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente. Simplesmente, prima o botão correspondente e continue <i>à procura do tesouro</i>.</p>`,
  "564": `<p>Volte ao traçado original das muralhas e dirija-se à sua direita. Uns metros mais adiante emerge o último ponto de interesse nesta Aventura.</p>\n<p>Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "565": `<p>Apesar de o Museu de Pré-história ter mais de 80 anos na atualidade, a sua localização atual foi realizada em 1982.</p>\n<p>Para isso foi utilizada a antiga Casa da Beneficência, incluindo no mesmo espaço o Museu Etnológico valenciano.</p>\n<p>Em 1995 abriram ao público as atuais Salas de Pré-história, Cultura Ibérica e Mundo Romano. No museu realizam-se também oficinas didáticas, pelo que o museu não se limita às suas salas, mas também se estende aos sítios arqueológicos que estão em curso de escavação.</p>`,
  "566": `<p>Sendo a Etnologia a ciência que estuda os povos e as suas culturas em todos os seus aspetos e relações, o Museu valenciano de Etnologia recolhe estudos que definem a relação entre as pessoas e o meio sobre o qual atuam.</p>\n<p>Como, por exemplo: o habitar no espaço doméstico, o conviver nos espaços para o encontro, e o espaço laboral nos locais de trabalho.</p>\n<p>O Museu desenvolve, também, programas de investigação, oferece os serviços de uma biblioteca especializada e colabora com numerosos ayuntamientos na recuperação e difusão do património local.</p>\n<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre neste monumento para conhecer melhor a história da cidade e os seus costumes.</p>`,
  "567": "<p>Apenas uns passos adiante, um magnífico edifício de cor branca é o seu próximo ponto de interesse na sua procura do tesouro.</p>",
  "568": `<p>Este edifício foi construído em 1882 para acolher as crianças órfãs da cidade.</p>\n<p>Na fachada de estilo neogótico destaca uma grande varanda realizada em pedra com um grande janelão de arco e por cima do mesmo um grande escudo.</p>`,
  "569": "<p>O que coroa o escudo? É uma coroa? Talvez um morcego? Ou talvez um dragão?</p>",
  "570": "<p>No decorrer desta aventura, o seu mapa levá-lo-á a subir e atravessar esta ponte, adaptada para a sua segurança com ciclovia e zonas pedonais, para descobrir alguns dos tesouros arquitetónicos que oferece a cidade histórica de Valencia. Mas ainda não por agora, a sua aventura transcorre no leito deste antigo rio convertido em jardim.</p>",
  "571": `<p>As <strong>Torres de Quart</strong> são uma das mais conhecidas portas da muralha medieval cristã de Valencia.</p>\n<p>Em 1442, ano da sua finalização, as torres cilíndricas consideravam-se as mais convenientes para resistir o uso da artilharia.</p>\n<p>As <strong>Torres de Quart</strong> foram edificadas em estilo gótico, embora pela sua funcionalidade defensiva, a decoração não seja um elemento pelo qual se possa caracterizar este monumento.</p>`,
  "572": `<p>No ano 1808, Valencia impôs-se contra as tropas invasoras de Napoleão num movimento patriótico, rejeitando o inimigo e obrigando-o a retirar-se sucessivas vezes.</p>\n<p>No séc. XIX o monumento utilizava-se como prisão, desta vez militar.</p>\n<p>O facto de as <strong>Torres de Quart</strong> estarem em uso como prisão é o que as livrou da demolição das muralhas de Valencia em 1865.</p>\n<p>Em 2007 realizou-se uma limpeza total do conjunto e abriram ao público.</p>`,
  "573": `<p>Como pode comprovar, hoje em dia ainda podem ver-se as marcas dos impactos de bala de canhão e as perfurações de projéteis de fuzil da artilharia francesa durante a guerra da independência.</p>\n<p>Quantas perfurações de projéteis pode contabilizar?</p>`,
  "574": "<p>Não se esforce, foram contabilizadas umas 132 marcas de canhão e mais de 1.000 perfurações de fuzil.</p>",
  "575": `<p>Admirando a Fachada principal, centre a sua atenção no seu lateral esquerdo, onde ainda se pode contemplar um tramo da muralha e a famosa estátua do "Palleter". O Palleter foi um vendedor de fósforos que segundo conta a tradição, a 23 de maio de 1808, declarou a guerra a Napoleão Bonaparte.</p>`,
  "576": `<p>Esta Aventura leva-o de volta ao séc. XV, tempos em que Valencia se destacou uma vez mais.</p>\n<p>Em 1409 criou-se uma instituição onde poder tratar doentes psíquicos; o recinto da atual Biblioteca Pública, o seu próximo objetivo, foi o primeiro hospital psiquiátrico da Europa.</p>`,
  "577": `<p>Antes de chegar, uma rua repleta de estabelecimentos comerciais à sua mão esquerda pode chamar a sua atenção.</p>\n<p>A Calle Colón oferece todo tipo de possibilidades para os amantes das compras.</p>\n<p>No final da rua, a <strong>Estación del Norte</strong> (ferroviária) e a <strong>Plaza de Toros</strong> sobressaem nesta via que traça hoje em dia o local que ocupava a muralha de Valencia no séc. XIV.</p>\n<p>${LOGO} proporcionará-lhe informação detalhada sobre esta área na sua Aventura número 5.</p>`,
  "578": `<p>A sua Aventura conduz-o, de novo, à Valencia antiga.</p>\n<p>Acabou de passar por baixo do desaparecido Portal de Torrent, conhecido popularmente como A Porta dos Inocentes.</p>\n<p>Durante esta Aventura, percorrerá a famosa Calle Hospital que está em frente a si neste momento.</p>\n<p>Não pause esta audioguia e observe à sua direita enquanto percorre a rua.</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
