import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "117": "<p>Wat is er te zien in de opening van de centrale boog?</p>",
  "118": "<p>De stoelen langs de straten op de routes van de optochten zijn te huur. Als u er vrije vindt, kunt u erop gaan zitten. Vergeet niet dat het een groot gebaar van respect is om uw zitplaats af te staan aan mensen met minder lichamelijke capaciteit dan u.</p>",
  "119": "<p>Zet deze audiogids niet op pauze en ga, zoals uw kaart aangeeft, naar uw volgende bezienswaardigheidspunt.</p>",
  "120": "<p>Zet deze audiogids niet op pauze en ga, zoals uw kaart aangeeft, naar uw volgende bezienswaardigheidspunt.</p>",
  "121": "<p>Zet deze audiogids niet op pauze en ga, als u zo vriendelijk wilt zijn, naar de overkant van het gebouw. Dank u.</p>",
  "122": "<p>Zet deze audiogids niet op pauze.</p>",
  "123": "<p>Zet deze audiogids niet op pauze.</p>",
  "124": "<p>Een gebouw uit de 19e eeuw in neoclassicistische stijl, gebouwd in baksteen.</p>\n<p>Het is vermeldenswaard dat in de 21e eeuw de huidige <strong>Plaza de Toros</strong> ook een multiculturele ruimte is die allerlei evenementen aanbiedt.</p>",
  "125": "<p>Volg de kaart tussen de Kathedraal en het <strong>Palacio Arzobispal</strong>.</p>\n<p>Steek het plein voor u over en laat de Kathedraal achter u.</p>\n<p>Volg de kaart om de <strong>Calle San Vicente Mártir</strong> te bereiken, maar let goed op!</p>\n<p>Aan het einde van de straat van de patroonheilige geeft de kaart aan om de weg links te nemen.</p>\n<p>U vindt de aanwijzing op de <strong>Plaza del Ayuntamiento</strong>.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>9</mark>.</p>\n<p>Dit is een perfect punt om prachtige foto's te maken van de architectonische schatten die de stad biedt.</p>\n<p>Druk op pauze, ga naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "126": "<p>Dit is een perfect punt om een prachtige foto te maken van dit monument dat is uitgeroepen tot historisch-artistiek erfgoed.</p>",
  "126-B": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 1.</p>`,
  "127": "<p>Dit is een perfect punt om een prachtige foto te maken van dit monument dat is uitgeroepen tot historisch-artistiek erfgoed.</p>",
  "128": "<p>Populair bekend als de <strong>Puente Amarillo</strong> (Gele Brug), dit is een loopbrug die beide zijden van de stad met elkaar verbindt. Aan de voet ervan zijn nog steeds de zogenoemde «saltos y rápidos» zichtbaar. Dit zijn de enorme driehoekige stenen die het water in goede banen leidden en vertraagden, om te voorkomen dat het te hard tegen de muur sloeg.</p>",
  "129": "<p>Valencia tijdens de Fallas!</p>",
  "129-B": "<p>Valencia tijdens de Fallas!</p>",
  "130": "<p>Maak verantwoord gebruik van het straatmeubilair en respecteer de publieke evenementen; er zijn aangewezen plaatsen om de verschillende optochten en pasacalles te oversteken. Respecteer altijd de aangeduide veiligheidsperimeters.</p>",
  "131": "<p>Om dit festival te begrijpen is het nodig enkele begrippen te verduidelijken die het begrip vergemakkelijken. Er wordt onderscheid gemaakt tussen:</p>",
  "132": "<p>Las Fallas als feest van Valencia (van 1 tot 19 maart).</p>",
  "133": "<p>Falla als non-profitvereniging van buurtbewoners die het jaar door bijeenkomt in lokalen die «Casals» worden genoemd. Ze genereren inkomsten via de verkoop van loterijbiljetten, lidmaatschapsgelden, overheidssubsidies en prijzen voor de beste fallero-monumenten.</p>",
  "134": "<p>Falla als fallero-monument dat van 15 tot 19 maart tentoongesteld wordt; er wordt onderscheid gemaakt tussen grote en kindergroepen. De fallas worden per sectie ingedeeld. De speciale sectie is de belangrijkste van allemaal, aangezien die de fallero-commissies groepeert die de duurste monumenten van de stad optrekken en strijden om de prijs voor de beste falla. Er worden ook andere prijzen uitgereikt, zoals de prijs voor vindingrijkheid en humor en de straatverlichting.</p>",
  "135": "<p>Als u zo vriendelijk wilt zijn, stel u op op een punt van waaruit u de torens in hun geheel kunt zien, gezien vanaf de voorzijde. Dank u.</p>",
  "136": "<p>Bent u al op de voorgestelde locatie? Pauzeer deze audiogids als u dat nodig acht. Bijna! U heeft nog maar een paar meter te gaan!</p>",
  "137": "<p>Bekijk de torens en richt uw aandacht op het grote gekanteld balkon. Sinds 1954 wordt op dit punt elk jaar het startschot gegeven voor de Fallas-vieringen. «La Cridà» is de uitnodiging voor het feest van de grote falleras van Valencia aan iedereen die wil deelnemen.</p>",
  "138": "<p>Dat zijn nogal wat monumenten, nietwaar? De Fallas als monument: wat zijn ze eigenlijk?</p>",
  "139": "<p>Het fallero-monument is een artistieke sculptuur met over het algemeen grote figuren, de <strong>Ninots</strong> genaamd, die een of meer centrale figuren omringen. De falla is gemaakt van brandbare materialen (karton, hout, papier, stoffen). De monumenten worden in de straten geplaatst om, na enkele dagen tentoongesteld te zijn, volledig te worden verbrand.</p>\n<p>Op 15 maart begint de <strong>Plantà</strong> (het assembleren van het monument), waarbij sommige de hoogte van 25 meter bereiken. Vanaf de 16e om acht uur 's ochtends zijn de fallas klaar en tentoongesteld om te dingen naar de eerste prijs.</p>",
  "140": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 1.</p>`,
  "141": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 2.</p>`,
  "142": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 3.</p>`,
  "143": "<p>Als u er buiten de openingsuren bent, kunt u altijd stoppen op een punt van waaruit u het gehele plein kunt overzien en gewoon genieten van de audio van uw Avontuur.</p>\n<p>In deze open stedelijke ruimte onthult zich een fragment van de vele architectonische schatten die de stad te bieden heeft, samengekomen op één plein.</p>\n<p>Druk op pauze en druk opnieuw op de doorgaan-knop zodra u het geschikt acht.</p>",
  "144": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 5.</p>`,
  "145": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in het Speciale Fallas-Avontuur.</p>`,
  "146": "<p>Richt uw aandacht op het gebouw met een ovale koepel in blauwe kleur.</p>\n<p>Dit is de bekende <strong>Basílica de Valencia</strong>.</p>",
  "147": "<p>De <strong>Kathedraal van Valencia</strong> is gebouwd op de vroegere Visigotische Seo die eeuwen later een Grote Moskee werd; daarom neemt de tempel aan zijn noordzijde, de oudste gevel, een ronde vorm aan in plaats van de traditionele kruisvorm.</p>\n<p>In de 13e eeuw werd de bouw van de Kathedraal geleidelijk voortgezet terwijl gebruik werd gemaakt van de Arabische moskee die op dezelfde plek stond.</p>",
  "148": `<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 3.</p>`,
  "149": "<p>De bouw van de Kathedraal duurde 500 jaar om voltooid te worden en gedurende die lange periode veranderden de architecturale stijlen; daarom zijn in de <strong>Kathedraal van Valencia</strong> meerdere architecturale stijlen samengesmolten.</p>\n<p>Deze stijlen zijn duidelijk zichtbaar in de drie ingangen: de Barokke hoofdingang die u verderop in dit Avontuur zult zien, de Gotische die momenteel voor u staat en de Romaanse aan de oostzijde, waarover we meer informatie geven in Avontuur nummer 1.</p>\n<p>In datzelfde Avontuur wordt ook het plein achter de Kathedraal beschreven, dat toevalligerwijs het nulpunt was van het Romeinse Valencia.</p>",
  "150": "<p>Richt uw aandacht op de achtergrond van het plein; uw volgende doel is de beroemde <strong>Miguelete</strong>, een grote toren die uitsteekt boven de Kathedraal. Maar laten we eerst spreken over het portiek van de Kathedraal.</p>",
  "151": "<p>Zodra u besluit uw avontuur voort te zetten, ga terug naar het midden van dit plein en kijk naar de gevel met blinde bogen van de kerk.</p>",
  "152": "<p>Tegenwoordig illustreert dat keramische paneel op de hoogte van de eerste verdieping het wonder.</p>",
  "153": "<p>Op de 18e wordt «La nit del foc» (de nacht van het vuur) gevierd: een verbluffend vuurwerkspektakel dat de weg opent voor de laatste dag waarop de fallero-monumenten tentoongesteld zullen zijn.</p>\n<p>De 19e, de dag van de «cremà» (het moment waarop de fallero-monumenten worden verbrand), valt altijd samen met het feest van Sint-Jozef, patroonheilige van Valencia.</p>",
  "154": `<p>De <strong>Lonja de la Seda</strong> is bij uitstek het monument van de Valenciaanse Gouden Eeuw en bevindt zich op slechts enkele meters van het ronde plein.</p>\n<p>Het monument werd gebouwd tussen 1482 en 1497 om de Wall Street van het Valencia van de 15e eeuw te huisvesten. Dit financiële centrum was noodzakelijk omdat de beroemde Zijderoute door de stad liep en haar verrijkte.</p>\n<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 1.</p>`,
  "155": "<p>Uw volgende doel is het monument van de Valenciaanse Gouden Eeuw. Een Wall Street van de 15e eeuw.</p>\n<p>De <strong>Lonja</strong> werd gebouwd tussen 1482 en 1497 en werd in 1996 uitgeroepen tot Werelderfgoed. Op uw kaart correspondeert dit met nummer <mark>16</mark>.</p>",
  "156": "<p>Volg uw kaart en ga door tot het einde van de straat, waar het plein bekend als de <strong>Plaza de la Virgen</strong> zich opent. Een van de meest iconische pleinen van de stad.</p>",
  "157": "<p>Aan de top steekt een windvaan uit die gewijd is aan deze heilige, beroemd om zijn martyrium, een van de oudste die zijn gedocumenteerd.</p>",
  "158": "<p>Ga, als u zo vriendelijk wilt zijn, naar de <strong>Iglesia de San Lorenzo</strong> die op uw kaart overeenkomt met nummer <mark>4</mark>.</p>",
  "159": "<p>Ga, als u zo vriendelijk wilt zijn, door tot het einde van de straat, waar de beroemde <strong>Plaza de la Virgen</strong> zich opent.</p>",
  "160": "<p>Uw avontuur gaat verder op dit zelfde punt, met de fontein en het plein voor u.</p>",
  "161": "<p>Vergeet niet dat u zich moet opstellen met de fontein en het plein voor u.</p>",
  "162": "<p>Uw avontuur gaat verder om de hoek, vanwaar de hoofdgevel van de <strong>Miguelete</strong> en ook de Barokke ingang van de <strong>Kathedraal van Valencia</strong> zichtbaar zijn; de derde die werd gebouwd.</p>",
  "163": "<p>Op dit punt in uw avontuur heeft u vast al het genoegen gehad onze koninginnen in galakleding te zien. De Fallera-jurken houden de zijdeambacht op handweefgetouwen levend.</p>",
  "164": "<p>In dit avontuur bespreken we elk onderdeel kort. Het eerste wat opvalt zijn de traditionele kapsels van de falleras. Ongetwijfeld de bekendste kapsels van Spanje.</p>\n<p>Het fallera-kapsel gaat terug tot de 18e eeuw. De vrouwen trokken hun haar in een paardenstaart en verdeelden het in acht lokken die in de vorm van een acht werden «gevlochten» rondom een of twee dikke naalden. Ter afronding omringden twee vlechten het centrale opgestoken haar.</p>\n<p>De naalden die het kapsel vasthouden bestaan uit twee delen: de spada en de buis, in het Valenciaans «Espasa» en «Canó».</p>\n<p>Ter voltooiing van het kapsel worden twee haarrolletjes ter hoogte van de oren toegevoegd, vastgehouden met twee haarspelden.</p>",
  "165": "<p>Het typische fallera-kapsel wordt afgerond met een achterste kam die met de hand is gemaakt in verzilverd of verguld messing, en twee replica's van de hoofdkam die in de zijdelingse haarrolletjes worden geplaatst.</p>",
  "166": "<p>Het fallera-kostuum, gedragen door de koninginnen en protagonisten van deze volksvieringen, bestaat uit:</p>\n<p>De rok: gewoonlijk met bloemmotieven, gemaakt van zijde en goud- en zilverdraden. Voor het kostuum worden 10 tot 15 meter zijde van verschillende kleuren gebruikt.</p>\n<p>Het lijfje: het bovendeel van het kostuum, gemaakt van dezelfde stof als de rok, vergezeld van schouderomslagen. De mouwstijl varieert afhankelijk van de inspiratie van de eeuw van het kostuum.</p>\n<p>De schouderomslagen: van materialen als tule en zijde, geborduurd met goud- of zilverdraad in prachtige patronen; ze bestaan uit twee delen: het bovenste, gedragen op het lijfje, en het voorschoot.</p>\n<p>Het hemd en de onderrokken: gewoonlijk bijpassend. Dit is het ondergoed, aangevuld met een hoepel om de rok volume te geven.</p>\n<p>Zoals elk galakostuum wordt aangevuld met gouden of zilveren oorbellen en «La Joia», de centrale versiering die bovenaan het lijfje wordt geplaatst.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
