import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "251": "<p><i>Alla ricerca del tesoro</i> si addentrerà nei regni della vegetazione, della luce, dell'acqua e della musica.</p>\n<p>Per apprezzarla al meglio, si posizioni dall'altro lato della fontana con l'edificio di fronte.</p>",
  "252": "<p>Inaugurato nel 1987 in stile funzionale-razionalista, il <strong>Palacio de la Música</strong> svolge la funzione di auditorium di Valencia.</p>\n<p>Le sue quattro sale e la cupola di cristallo ospitano circa 2.500 spettatori ed è stato elogiato da prestigiosi musicisti e cantanti.</p>",
  "253": "<p>Che tipo di alberi può toccare adesso? Sono palme, ulivi o forse mandorli? Indovini!</p>",
  "254": "<p>Continui la sua avventura girando intorno alla fontana per riprendere il lato sinistro del fiume e segua quel sentiero passando sotto il <strong>Puente del Ángel</strong>.</p>",
  "255": "<p>Un ponte realizzato tra il 1941 e il 1948, della lunghezza di 150 metri e 31 metri e mezzo di larghezza.</p>",
  "256": "<p>Gli indizi la conducono a un nuovo portale del tempo che si apre più avanti, a mano destra e la trasporterà in un'epoca fantastica di antichi racconti.</p>",
  "257": "<p>Concretamente ai viaggi di <strong>Gulliver</strong>.</p>",
  "258": "<p>Grandi e piccini godono di questa ricostruzione del racconto di Jonathan Swift, nella quale possono immaginare di essere dei Lillipuziani che corrono sopra lo stesso <strong>Gulliver</strong> e si lanciano dai suoi enormi scivoli.</p>\n<p>Il suo cappello ricrea un altro dei viaggi di <strong>Gulliver</strong> quando viaggiò a Brobdingnag, il Paese dei Giganti.</p>\n<p>Si diriga all'ingresso principale per risolvere la prossima sfida.</p>",
  "259": "<p>Saprebbe dirmi il prezzo per accedere a questa attrazione? Potrebbe essere gratuita...</p>",
  "260": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e godersi i suoi enormi scivoli!</p>\n<p>Questo è un punto perfetto per scattare una magnifica fotografia di questo tesoro che ci offre Valencia.</p>\n<p>Usi il tasto pausa a suo piacimento, quando sentirà che è il momento, continui semplicemente e risolva le nostre sfide mentre scopre la città.</p>`,
  "261": "<p>La sua avventura continua in un'area ricreativa con piste di pattinaggio e parchi giochi per bambini, situata qualche metro più avanti, seguendo l'antico alveo.</p>",
  "262": "<p>Le diamo il benvenuto alla <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Presti una particolare attenzione alla sua mappa; questo magnifico complesso è composto da sei grandi elementi.</p>",
  "263": "<p>Questa piazza, di pianta triangolare, prende il nome di <strong>Plaza del Ayuntamiento</strong> dal 1987.</p>\n<p>Un contesto urbano che ha subito diverse trasformazioni, tra cui la demolizione del Convento de San Francisco nel 1891, che consentì un passaggio diretto tra due quartieri commerciali della città.</p>\n<p>Anche nella piazza stessa fu istituito il mercato dei fiori, che dal 1924 fino ai giorni nostri anima e arricchisce la città.</p>\n<p>A Valencia ci sono molte fontane che rinfrescano l'ambiente circostante. La fontana che possiamo vedere oggi fu costruita da Carlos Buigues e inaugurata nel marzo del 1962.</p>",
  "264": "<p>Progettata da Santiago Calatrava e Félix Candela, la <strong>Ciudad de las Artes y de las Ciencias</strong> è un insieme unico di avanguardia architettonica a livello mondiale dedicato alla divulgazione scientifica e culturale.</p>\n<p>I colori blu e bianco e le sue audaci linee identificano la capitale del Turia del XXI secolo.</p>\n<p>La <strong>Ciudad de las Artes y de las Ciencias</strong> è l'immagine futuristica che simboleggia la nuova Valencia; una città moderna all'interno della città millenaria, dove milioni di visitatori affluiscono ogni anno per godere della sua cultura, della sua natura, della sua arte e della sua scienza.</p>",
  "265": "<p>Per rendere la sua avventura più semplice e piacevole, abbiamo organizzato gli elementi da visitare in due fasi. In questo modo potranno esplorarli con calma, senza fretta, e godere di ogni momento al massimo. Ogni fase è stata pensata per offrire un'esperienza più completa e organizzata, permettendo di sfruttare al meglio tutto ciò che hanno da offrire, mentre si gode ogni istante del percorso.</p>",
  "266": "<p>Il primo: offre una vista panoramica della <strong>Ciudad de las Artes y de las Ciencias</strong> percorrendo il lato sinistro del Jardín del Turia, attraversando il Puente l'Assut de l'Or e salendo poi al belvedere che offre <strong>l'Umbracle</strong>.</p>",
  "267": "<p>Il secondo: inizia in cima, nel belvedere stesso, proseguendo fino alla fine e scendendo per l'accesso che si trova nella parte frontale del Palacio de las Artes Reina Sofía.</p>\n<p>È pronto? Buon divertimento, perché è una meraviglia!</p>",
  "268": "<p>Prendendo come riferimento il lato sinistro del giardino, si addentre in un sentiero ciclabile che scorre tra piante aromatiche e medicinali.</p>\n<p>Rosmarino, timo e lavanda mescolano le loro fragranze in un paesaggio di ulivi e antiche rovine.</p>\n<p>Questo percorso, con i suoi numerosi belvedere, offre una panoramica eccezionale della <strong>Ciudad de las Artes y de las Ciencias</strong> che spicca notevolmente sullo sfondo a destra nell'ambiente verde e giardini in cui si trova.</p>",
  "269": "<p>Si addentre nel sentiero e scelga un belvedere dal quale si possa vedere l'intero complesso.</p>",
  "270": "<p>Inizieremo con il meraviglioso Palacio de les Artes Reina Sofía, lo vede? È tutto bianco e spicca il suo tetto aggettante.</p>",
  "271": "<p>Fu inaugurato nel 2005 e si dedica alla programmazione operistica, con una capacità di 3.500 spettatori.</p>\n<p>I suoi Intendenti e Direttrici artistiche hanno saputo collocare questo centro lirico tra i migliori e più prestigiosi della scena internazionale.</p>\n<p>Nelle sue 4 sale sono passati artisti di grande rilievo come Plácido Domingo e Luciano Pavarotti.</p>",
  "272": "<p>Concentri la sua attenzione sul Museo Príncipe Felipe.</p>",
  "273": "<p>Riesce a vederlo? Ha più di 5.000 finestre!</p>\n<p>Come potrà constatare, ai valenciani piace il sole e per questo molti dei loro edifici hanno grandi vetrate, consentendo così un risparmio energetico grazie a una fonte di luce e calore naturale ed ecologica.</p>",
  "274": `<p>Se si trova in orario di visita, ${LOGO} la invita a premere pausa e ad entrare per scoprire la gastronomia locale che offre questo meraviglioso spazio.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno.</p>`,
  "274-B": `<p>Se si trova in orario di visita, ${LOGO} la invita a premere pausa e ad entrare per scoprire la gastronomia locale che offre questo meraviglioso spazio. Può riprendere la sua avventura una volta lo riterrà opportuno. La sua Avventura continua dalla porta opposta a quella in cui si trova in questo momento.</p>`,
  "274-C": `<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e di entrare in questo monumento per conoscere meglio la storia della città e le sue tradizioni.</p>\n<p>L'ingresso principale si trova nella parte opposta del monumento.</p>\n<p>Questo è un punto perfetto per scattare una magnifica fotografia di questo tesoro che ci offre Valencia.</p>`,
  "275": "<p>Il Museo Príncipe Felipe fu inaugurato nell'anno 2000 con un totale di 26.000 metri quadrati di esposizioni temporanee e permanenti.</p>\n<p>Questo spazio, sotto il motto \"Vietato non toccare, non sentire e non pensare\", è un innovativo centro di scienza interattiva.</p>\n<p>La sua vocazione è promuovere l'interesse per la conoscenza scientifica e tecnologica attraverso il divertimento e l'intrattenimento.</p>\n<p>Con questo obiettivo, si concede grande importanza all'interattività delle esposizioni.</p>\n<p>È inoltre sede di diversi eventi sociali e culturali della città.</p>",
  "276": "<p>Continui <i>alla ricerca del tesoro</i> per questo percorso pavimentato che la conduce direttamente al suo prossimo obiettivo, il Puente de l'Assut de l'Or.</p>",
  "277": "<p>Il nome di questo ponte è composto da due parole: Azud, che in arabo significa barriera o diga, e Or che in Valenciano è Oro.</p>\n<p>Quindi, l'Assut de l'Or significa diga d'oro.</p>\n<p>Sebbene questo ponte sia conosciuto anche con il soprannome \"il ponte dell'arpa\".</p>",
  "278": "<p>Il Puente de l'Assut de l'Or rimane in piedi grazie a 29 cavi che partono dalla parte anteriore del suo albero di 125 metri di altezza.</p>\n<p>Il piano del ponte ha 180 metri di lunghezza per 34 metri di larghezza.</p>\n<p>È stato completato nel dicembre del 2008 ed è uno dei ponti più alti di Spagna.</p>",
  "279": "<p>Questa avventura la conduce ad attraversare il ponte che offre viste magnifiche sulla <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Mentre attraversa il ponte presti particolare attenzione alla sua sinistra dove spicca l'Ágora.</p>\n<p>Numero <mark>16</mark> sulla sua mappa.</p>\n<p>Subito dietro si trova il noto Oceanográfic.</p>\n<p>Che corrisponde al numero <mark>17</mark> sulla sua mappa.</p>\n<p>Una volta attraversato il ponte, si posizioni, come indica la sua mappa, in una zona sicura che offre viste magnifiche di quest'area. Questa zona sicura che suggeriamo si trova a sinistra, scendendo dal ponte.</p>\n<p>Ricordi di premere pausa, poi visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "280": "<p>Continui fino alla fine della strada dove attraversa la <strong>Calle Caballeros</strong> che corrisponde sulla sua mappa al numero <mark>20</mark>.</p>\n<p>Una volta lì, giri a destra e vedrà l'emblematico edificio del <strong>Palacio de la Generalitat</strong> che sulla sua mappa corrisponde al numero <mark>21</mark>.</p>\n<p>Prema pausa, poi vada al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "281": "<p>Il sostantivo Ágora viene dal greco e significa Piazza pubblica della vita sociale.</p>",
  "282": "<p>Questo spazio provvisoriamente completato nel 2009 è una struttura metallica di pianta simile a un'ellisse appuntita.</p>\n<p>L'Ágora misura circa 88 metri di lunghezza per 66 di larghezza e 80 di altezza, è una grande piazza coperta che dota il complesso di uno spazio multifunzionale.</p>\n<p>Questo monumento è concepito come un palcoscenico progettato per la celebrazione di congressi, convegni, concerti o rappresentazioni con la possibilità di trasformarsi in area espositiva.</p>\n<p>La sua area coperta è di circa 5.000 metri quadrati.</p>\n<p>La sua forma ricorda, secondo lo stesso Calatrava, due mani intrecciate, poiché l'Ágora avrà nella parte superiore delle ali che simulano delle dita capaci di filtrare la quantità di luce che entrerà al suo interno.</p>\n<p>Questo grande spazio interno è concepito come una piazza pubblica coperta, a pianta diafana, al livello dei laghi e dei viali adiacenti.</p>\n<p>L'edificio è circondato da due laghi che fungono da complemento dello spazio interno.</p>\n<p>Nel novembre del 2009, anno della sua inaugurazione, si è svolto al suo interno l'Open 500 di tennis della Comunità Valenciana.</p>",
  "283": "<p>Concentri la sua attenzione sul complesso che si trova dietro l'Ágora.</p>\n<p>Questo spazio è conosciuto come El Oceanográfic.</p>",
  "284": "<p>Con un'estensione di 110.000 metri quadrati e un volume d'acqua equivalente a 15 piscine olimpioniche, il visitatore potrà osservare squali, Belugas, trichechi, delfini, leoni marini, pinguini, stelle marine e ricci di mare.</p>\n<p>Una grande varietà di crostacei e pesci, oltre ad uccelli tipici provenienti dall'<strong>Albufera</strong> di Valencia, una delle zone umide più grandi di Spagna situata a circa 12 chilometri a sud della città.</p>\n<p>Inaugurato nel 2002, è uno dei maggiori acquari d'Europa. Al suo interno si rappresentano i principali ecosistemi marini del pianeta: Mediterraneo, Zone Umide, Mari Temperati e Tropicali, Oceani Antartico, Artico, Isole e Mar Rosso.</p>",
  "285": "<p>Continuiamo con la Caccia al Tesoro!</p>\n<p>Con l'Ágora e l'Oceanográfic alle spalle, cerchi una costruzione arborea che si troverà davanti a lei dall'altro lato della strada. Riesce a vederla?</p>",
  "286": "<p><strong>l'Umbracle</strong>: è un belvedere giardino nel quale si trova il noto Paseo de las Esculturas.</p>\n<p>In questa zona spicca il suo giardino centrale alberato con flora autoctona del Mediterraneo.</p>\n<p>Il suolo di questo giardino è in legno di teak per la sua naturale durabilità in condizioni climatiche estreme.</p>\n<p>Al di sotto di questo viale si trova il parcheggio del complesso con capacità per 20 autobus e 650 veicoli.</p>",
  "287": "<p>Da questo punto ha inizio il secondo scenario che le proponiamo.</p>\n<p>La sua avventura continua placidamente fino al termine del viale, di ritorno a Reina Sofía.</p>\n<p>Reina Sofía corrisponde al numero <mark>12</mark> sulla sua mappa.</p>\n<p>Si posizioni guardando il monumento e cerchi l'accesso che scende nella sua parte frontale ottenendo così una visuale più ravvicinata della <strong>Ciudad de las Artes y de las Ciencias</strong>. Una volta in basso, emerge l'Hemisfèric.</p>\n<p>l'Hemisfèric corrisponde sulla sua mappa al numero <mark>19</mark>.</p>",
  "287-B": "<p>Da questo punto ha inizio il secondo scenario che le proponiamo.</p>\n<p>La sua avventura continua placidamente fino al termine del viale, di ritorno a Reina Sofía che corrisponde al numero <mark>18</mark> sulla sua mappa.</p>\n<p>Si posizioni guardando il monumento e cerchi l'accesso che scende nella sua parte frontale ottenendo così una visuale più ravvicinata della <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Una volta in basso, emerge l'Hemisfèric che sulla sua mappa corrisponde al numero <mark>25</mark>.</p>",
  "288": "<p>Si diriga all'emblematico <strong>Palacio de la Generalitat</strong> che sulla sua mappa corrisponde al numero <mark>21</mark> ed è l'ultima tappa di questa avventura.</p>",
  "289": "<p>Ci congediamo, non senza prima augurarle delle buone Fallas e consigliarle di non perdersi i castelli di fuochi d'artificio che vengono lanciati dal 15 al 19 marzo.</p>",
  "290": "<p>Questo è un punto perfetto per scattare magnifiche fotografie della <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Ci vediamo in basso! Ricordi di premere pausa, poi vada al punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "291": `<p>L'Hemisfèric fu il primo edificio che aprì le sue porte al pubblico nella <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Inaugurato nel 1998 e con una capacità di 300 persone, questo spazio si dedica al cinema IMAX in 3 Dimensioni.</p>\n<p>Architettonicamente parlando, il monumento si distingue per l'originalità delle sue valvole che, grazie a un meccanismo speciale, si aprono e si chiudono come se si trattasse di un occhio reale.</p>\n<p>${LOGO} la invita a premere pausa e a godersi a suo piacimento questo complesso futuristico dalle linee innovative in un contesto di ispirazione millenaria.</p>\n<p>Ci permettiamo di aggiungere alcuni dettagli che arricchiscono la nostra visione della <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Si noti che la decorazione del complesso è un mosaico di ceramica valenciana, retaggio arabo durante il suo periodo di colonizzazione; ancora una volta torniamo alla cultura araba quando ammiriamo gli enormi spazi pieni d'acqua che magnificano e ingrandiscono i monumenti circostanti.</p>\n<p>Una volta deciso di continuare, prema semplicemente il tasto corrispondente e continui <i>alla ricerca del tesoro</i>.</p>\n<p>Il contesto della <strong>Ciudad de las Artes y de las Ciencias</strong> è perfetto per godersi il sole di Valencia e gustare un'Orxata tradizionale valenciana.</p>`,
  "292": "<p>Mentre si gode il suo tempo, cerchi di risolvere queste sfide.</p>\n<p>Di quanti monumenti si compone la <strong>Ciudad de las Artes y de las Ciencias</strong>?</p>\n<p>Di cosa è fatta l'Orxata? Di chufa, di riso o di orzo?</p>",
  "293": "<p>La sua avventura continuerà sul Puente de la Mar.</p>\n<p>Il ponte pedonale del XVI secolo che ha già conosciuto in questa avventura.</p>",
  "294": "<p>I danni causati dalle diverse piene del <strong>Río Turia</strong> sulla struttura del Puente de la Mar, che all'epoca era in legno, costrinsero nel 1425 ad avviare la costruzione di una struttura più robusta, anch'essa in legno; ma un'altra inondazione nel 1589 lo spazzò via completamente.</p>\n<p>Nel 1591, Francesc Figueroa si incaricò della sua ricostruzione in pietra. I lavori si conclusero nel 1596.</p>\n<p>All'epoca contava già dieci archi acuti a volta e una torretta che riparava la Croce del Ponte.</p>",
  "295": "<p>Cosa circonda la base del ponte? Acqua, erba o anatre?</p>",
  "296": "<p>Congratulazioni! Ha raccolto tutti gli indizi e risolto gli enigmi che le proponeva il vecchio alveo... Finora. Ma questa Avventura non finisce qui!! Come potrà constatare, la mappa del tesoro la riconduce in città. Andiamo?</p>",
  "296-B": "<p>Da questo punto il tracciato di questa avventura continua in circuito urbano!</p>\n\n<p>Segua con cautela e ricordi che deve rispettare il codice della strada.</p>\n\n<p>Guardi le indicazioni della sua mappa del tesoro e continui per la pista attrezzata <i>alla ricerca del tesoro</i>.</p>\n\n<p>Dalla parte sinistra del giardino, un accesso le permette di salire e attraversare questa opera adornata con 27.500 fiori multicolori.</p>",
  "296-C": "<p>Congratulazioni! Ha raccolto tutti gli indizi e risolto gli enigmi che le proponeva il vecchio alveo… Ma questa Avventura non finisce qui!!</p>\n\n<p>Come potrà constatare, la mappa del tesoro la riconduce in città. Andiamo?</p>",
  "297": "<p>Si diriga al ponte successivo, il <strong>Puente de las Flores</strong> inaugurato nel 2002 e adornato con 27.500 fiori multicolori che variano a seconda del periodo dell'anno.</p>\n<p>Dalla parte destra del giardino, un accesso le permette di salire e attraversare questa opera di Santiago Calatrava.</p>",
  "298": "<p>Il ponte sfocia in una struttura cilindrica realizzata in mattoni, molto più antica del ponte.</p>\n<p>Questa struttura era utilizzata principalmente per riempire d'acqua le cisterne dei camion addetti alla pulizia delle strade.</p>",
  "299": "<p>Segua con cautela da questo punto, poiché è un percorso urbano e deve rispettare il codice della strada.</p>\n<p>Guardi le indicazioni della sua mappa del tesoro e continui per la pista ciclabile per addentrarsi nel pieno centro storico alla ricerca di altri indizi.</p>\n<p>Al termine del viale, nella rotonda, attende il suo prossimo obiettivo.</p>",
  "300": "<p>La <strong>Puerta de la Mar</strong> fu ricostruita nel 1946.</p>\n<p>Questa è una replica dell'antica porta d'accesso alla città che occupava questo stesso luogo fino al 1868.</p>\n<p>Il punto di accesso fu abbattuto nel 1868 insieme alle mura. Il monumento che può vedere oggi è un omaggio ai Caduti durante la Guerra Civile Spagnola tra gli anni 1936 e 1939.</p>\n<p>Il Monumento è composto da tre aperture: una centrale con arco a tutto sesto e due laterali con architrave.</p>\n<p>Nel suo arco centrale si può vedere una grande croce di marmo.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
