import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "451": "<p>La <strong>Basilica di Valencia</strong> ospita, al suo interno, l'immagine della nostra Patrona, la Madre di tutti i valenciani: la <strong>Vergine degli Abbandonati</strong>, conosciuta affettuosamente a Valencia come la Xeperudeta, che significa gobettina nel linguaggio Valenciano.</p>\n<p>La Vergine prende questo nome a causa della sua leggera inclinazione in avanti, interpretata come segno di logoramento fisico per lo sforzo e la costanza nel sostenere le migliaia di preghiere ricevute dai valenciani.</p>\n<p>Le preghiere iniziarono a seguito dell'epidemia di peste che nel 1647 causò circa 18.000 vittime. La devozione, sempre più fervente del popolo valenciano per la Vergine, creò la necessità di edificare uno spazio adeguato affinché la sua immagine potesse essere esposta al popolo in condizioni adeguate a tale devozione.</p>",
  "452": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo monumento storico al suo ritmo.</p>\n<p>Potrà ammirare gli Affreschi del famoso pittore Palomino, esposti in questa Basilica dal 1701.</p>\n<p>Può anche rivolgere alcune parole alla Vergine. È tradizione chiedere un desiderio non per sé stessi.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno, semplicemente prema il tasto corrispondente e continui <i>alla ricerca del tesoro</i>.</p>`,
  "453": "<p>Bravissimo! Ha quasi completato la sua avventura!!</p>\n<p>Osservi la mappa con attenzione, la disposizione della carreggiata la obbliga a seguire una via unica e poi girare a mano destra, ottenendo così una magnifica vista della <strong>Cattedrale di Valencia</strong>.</p>\n<p>Lungo il percorso verso la Porta Romanica, alla sua sinistra si trova il <strong>Palazzo Arcivescovile</strong>.</p>",
  "454": "<p>Nella parte opposta alla Basilica, l'ornamentazione di una villa signorile rivela che potrebbe essere importante in questa caccia al tesoro.</p>",
  "455": "<p>Valencia è la città spagnola con il maggiore volume di opere moderniste a causa dell'importante crescita della città alla fine del XIX secolo, che comportò la costruzione del quartiere di espansione e la demolizione delle mura medievali nel 1865.</p>\n<p>La comparsa del Modernismo fu un movimento di rottura con gli stili precedenti, con l'intenzione di trovarne uno più moderno, giovane e funzionale basato sull'uso di nuovi materiali come il ferro, il vetro e le piastrelle derivate dall'evoluzione industriale.</p>\n<p>Si caratterizzò per una certa esaltazione dell'orto, delle falleras, delle arance e dei pescatori, tra gli altri.</p>\n<p>Questo si dimostra nelle opere piene di mosaici colorati, sculture e decorazioni floreali.</p>\n<p>Questo movimento fu promosso da una nuova classe: la borghesia, che voleva rivendicarsi attraverso l'arte.</p>\n<p>Fuggivano dalla tradizione, dalle costruzioni robuste, cercavano il movimento... e il dettaglio fondamentale era l'ornamentazione e la natura.</p>\n<p>A Valencia, inoltre, si sviluppò una corrente con caratteristiche proprie, nota come Modernismo Valenciano.</p>",
  "455-B": "<p>La facciata modernista dell'edificio ha incisioni con motivi floreali e lesene che imitano tronchi. Si possono apprezzare diversi balconi: alcuni in pietra e altri in ferro battuto.</p>",
  "455-C": "<p>Nella parte inferiore si trova la Cappella di San Valero, dove si trovava la prigione in cui fu detenuto il vescovo Valero prima di essere esiliato nel IV secolo dopo Cristo.</p>\n<p>Costruita inizialmente nel 1719 e completamente ricostruita nel 1907, si apre all'esterno attraverso una porta architravata in stile barocco con lesene toscane.</p>\n<p>Nell'architrave della porta si può vedere un oculo, poco al di sopra dell'immagine del vescovo.</p>",
  "455-D": "<p>Guardando l'immagine di San Valero, quale oggetto potrebbe indicarci che fu prigioniero?</p>\n<p>Le catene, il libro o forse la sua espressione triste?</p>",
  "456": "<p>In che anno fu edificata questa villa?</p>\n<p>Suggerimento! Guardi nella parte superiore della facciata.</p>",
  "457": "<p>Una rialzatura artificiale, alla mano sinistra di questa villa, invita a continuare <i>alla ricerca del tesoro</i>.</p>\n<p>Su si va!</p>\n<p>Questo è un punto perfetto per scattare fotografie panoramiche di questi monumenti dichiarati di interesse storico artistico.</p>",
  "458": "<p>Nelle vicinanze si è aperto un portale del tempo!</p>\n<p>Cosa si può vedere attraverso?</p>\n<p>Una <strong>Plaza de Toros</strong>, dei Bagni Romani o forse una Stazione della Metro?</p>",
  "459": "<p>Esatto! Dei bagni romani. La sua missione? trovare il lettino dove si facevano i massaggi. È vero, è ancora in piedi!</p>",
  "460": "<p>Nel XIII secolo, dopo la reconquista cristiana su questa stessa struttura, fu eretto l'edificio dell'Almoina, che diede il nome al luogo.</p>\n<p>Almoina (che in valenciano significa elemosina) era un'istituzione medievale di carattere benefico che distribuiva cibo ai più svantaggiati.</p>",
  "461": `<p>Come può constatare, la struttura architettonica che avvolge la piazza permette un contatto visivo diretto con l'interno del museo mentre gli spazi esterni favoriscono il dialogo in un contesto nel quale i resti del passato sono i veri protagonisti.</p>\n<p>In questo punto si trova uno dei migliori centri archeologici d'Europa e si contemplano rovine che risalgono alla fondazione della città nell'anno 138 avanti Cristo.</p>\n<p>Questa piazza è considerata la più antica della città. In passato, in questo stesso luogo, si trovava la piazza maggiore romana vicina al foro. Ovvero, la zona centrale dell'antica città di Valentia.</p>\n<p>Se si trova in orario di visita, ${LOGO} le raccomanda di premere pausa e di entrare in questo spazio per conoscere meglio la storia della città.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno, semplicemente prema il tasto corrispondente e continui <i>alla ricerca del tesoro</i>.</p>\n<p>La sua avventura continua in questo stesso punto.</p>`,
  "462": "<p>A tal fine, cedette la proprietà di tutte le moschee e cimiteri musulmani all'arcivescovado che, a sua volta, cristianizzò questi templi rinominandoli come Parrocchie dedicate a Sante e Santi della nuova religione che si sarebbe instaurata in queste terre.</p>\n<p>Nel 1245, la <strong>Iglesia de San Lorenzo</strong> fu scelta come una delle dieci Parrocchie fondazionali della città.</p>\n<p>Il tempio che possiamo vedere oggi risale al 1684, sebbene il campanile sia stato costruito anni dopo, nel 1747. Purtroppo il terremoto del 1822 lo spostò dal suo asse originale. Riesce a vederlo?</p>\n<p>Il vano superiore ospita due campane: Santa Anna, fabbricata nel 1718, e Domingo, del 1742.</p>\n<p>Corona il campanile una cupoletta con una vivace banderuola dove possiamo vedere l'immagine di San Lorenzo.</p>",
  "463": "<p>Si posizioni, se non le dispiace, al centro della piazza con il mercato di fronte. Alla destra del famoso <strong>Mercado Central</strong> emerge una magnifica chiesa barroca. Riesce a vederla? Sulla sua mappa corrisponde al numero <mark>16</mark>.</p>\n<p>Si avvicini al suo prossimo obiettivo, San Juan del Mercado.</p>",
  "464": "<p>Al centro del monumento svetta il <strong>Cimborrio</strong> di stile gotico.</p>\n<p>Dal XV secolo si eleva a un'altezza di 40 metri lasciando entrare la luce naturale e illuminando la cattedrale.</p>\n<p>Saprebbe determinare che geometria ha? Esagonale, Ottagonale o Quadrangolare?</p>",
  "465": "<p>Seguendo l'itinerario della mappa, si giri e lasci la <strong>Basilica della Vergine</strong> alla sua sinistra e il <strong>Museo Archeologico</strong> alla sua destra, vada fino alla fine della strada e giri alla sua mano sinistra.</p>\n<p>Nel tragitto emerge la <strong>Plaza de la Virgen</strong>.</p>",
  "465-B": "<p>Segua la sua mappa del tesoro e continui a camminare fino alla fine della strada, dove si apre una piazza nota come la <strong>Plaza de la Virgen</strong>, una delle più iconiche della città.</p>\n<p>Sulla sua mappa è indicata con il numero <mark>3</mark>.</p>\n<p>Ricordi di premere pausa, poi vada o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
  "466": "<p>La <strong>Plaza de la Virgen</strong> è circondata dalla Basilica, dalla Cattedrale e dal <strong>Barrio de la Seu</strong> o <strong>Barrio de la Catedral</strong>.</p>\n<p>Nella metà nord della piazza attira particolarmente l'attenzione un'attraente Fontana Monumentale scolpita in bronzo.</p>\n<p>Conosciuta come la Fontana di Nettuno, è la rappresentazione allegorica del <strong>Río Turia</strong>.</p>",
  "467": "<p>Nettuno tiene in mano la cornucopia dell'abbondanza ed è circondato da figure femminili con copricapo da agricoltrici valenciane che rappresentano i principali canali d'irrigazione di Valencia.</p>\n<p>Con quale mano regge Nettuno la cornucopia?</p>",
  "468": "<p>Quante figure circondano la fontana?</p>",
  "469": "<p>La piazza che si apre davanti a lei è uno degli scenari più amati dai valenciani, soprattutto durante le nostre feste popolari, le Fallas.</p>",
  "470": "<p>Ogni 1 marzo la città si tinge del colore dei fiori e della polvere da sparo per dare il benvenuto alla primavera e a più di un milione di visitatori.</p>",
  "471": "<p>Le Fallas si vivono in strada grazie al bel tempo che di solito fa e perché la città diventa pedonale.</p>\n<p>Le strade affollate, la contemplazione del monumento fallero e le soste per rinfrescarsi sono alcune delle ragioni per cui Valencia in Fallas è una festa incomparabile.</p>",
  "472": "<p>Durante le Fallas è tutta una festa: il fragore della mascletà, i casali, le sfilate e le bande musicali percorrono più di 700 monumenti falleros.</p>\n<p>Il 15 marzo inizia la Plantà o assemblaggio del monumento, alcuni raggiungendo i 25 metri di altezza.</p>\n<p>I monumenti falleros realizzati in materiali combustibili come legno, cartone, carta o tessuti vengono bruciati dopo alcuni giorni di esposizione nelle strade, dando con questo atto il benvenuto alla stagione primaverile.</p>",
  "473": "<p>Proprio al centro di questa piazza si erige, ogni anno, una struttura in legno che serve da supporto per \"tessere\" con fiori multicolori il manto della Patrona di Valencia.</p>\n<p>L'offerta di fiori alla \"Mare de Deu dels Desamparats\" ha le sue origini all'interno della Basilica, dal momento in cui nel 1941 alcune ortolane offrirono dei mazzi di fiori alla Vergine.</p>",
  "474": "<p>Ma in soli 8 anni, l'Offerta costrinse gli organizzatori a svolgerla all'esterno della Basilica.</p>\n<p>Tale era la devozione che sulla facciata del tempio furono costruiti dei supporti per depositare i mazzi di fiori.</p>\n<p>Anni dopo si incorporano alle Offerte i bambini e le bande musicali nelle sfilate.</p>\n<p>Tempo dopo si stabilisce che, nell'Offerta, si potrà sfilare solo con costumi regionali e si organizzano nuovi itinerari poiché, nel 1964, la sfilata si triplicò arrivando a riunire più di ventimila persone.</p>\n<p>Attualmente l'Offerta dei fiori inizia il giorno 17 fino all'alba del 19 marzo, arrivando a superare le centotrentamila Falleras e Falleros che lasciano la <strong>Plaza de la Virgen</strong> piena di fiori.</p>",
  "475": `<p>Ricordi che, se si trova in orario di visita, ${LOGO} le raccomanda di salire su questo tesoro architettonico per conoscere meglio la storia della città e le sue tradizioni.</p>`,
  "476": "<p>Rivolga la sua attenzione, dall'esterno, leggermente a destra della basilica.</p>",
  "477": "<p>In fondo spicca la Porta Gotica della Cattedrale, la seconda a essere costruita.</p>\n<p>Chiamata la porta degli apostoli per le dodici figure scolpite nel suo portale, fu edificata nel XIV secolo ed è formata da due corpi sovrapposti.</p>\n<p>Nel corpo inferiore si può distinguere il portale che sporge dal muro con archi a sesto acuto, tipici dello stile gotico, e tre archetti con sculture di angeli e santi.</p>\n<p>Nel timpano della porta si può vedere la scultura di Santa Maria con il bambino in braccio.</p>\n<p>Ai lati della Vergine si distinguono angeli che suonano strumenti musicali.</p>\n<p>Non metta in pausa questa audioguida e si avvicini, se non le dispiace, al portico.</p>",
  "477-B": "<p>In fondo spicca la Porta Gotica della Cattedrale, la seconda a essere costruita.</p>",
  "478": "<p>Nel corpo superiore risalta notevolmente il rosone in pietra che assume la forma del sigillo di Salomone.</p>\n<p>Con un diametro di 6 metri e mezzo, svolge la funzione di illuminazione della cattedrale.</p>\n<p>Il Rosone che si può vedere oggi non è l'originale del 1462, poiché dovette essere sostituito per il suo deterioramento nel 1957.</p>",
  "479": "<p>Nel suo portico si celebra, ogni giovedì, il Tribunale delle Acque; un giudizio rapido e di forma orale che si occupa di risolvere i conflitti derivati dall'uso e dallo sfruttamento dell'acqua di irrigazione tra gli agricoltori.</p>\n<p>L'origine di questo tribunale, sebbene sconosciuta, si ritiene che esistesse già un antecedente in epoca romana, ma la sua funzione come è conosciuta oggi si produsse più di un millennio fa durante il regno arabo.</p>",
  "480": "<p>Seguendo il corso dell'antico fiume, a circa 200 metri, si trova la spianata da dove vengono sparati i castelli di fuochi d'artificio. Come avrà potuto constatare, ai valenciani piace la polvere da sparo.</p>",
  "480-B": "<p>Si diriga all'emblematico <strong>Palacio de la Generalitat</strong> che sulla sua mappa corrisponde al numero <mark>23</mark> ed è l'ultima tappa di questa avventura.</p>",
  "481": "<p>Il <strong>Palacio de la Generalitat</strong> Valenciana è situato nel <strong>Barrio de la Seu</strong> o <strong>Barrio de la Catedral</strong> e iniziò la sua costruzione nel 1421.</p>\n<p>Godendo di numerosi restauri e ampliamenti, ai quali parteciparono i principali maestri valenciani della loro epoca, l'antico municipio della città è di stile gotico valenciano con interventi rinascimentali.</p>",
  "481-B": "<p>Godendo di numerosi restauri e ampliamenti, ai quali parteciparono i principali maestri valenciani della loro epoca, l'antico municipio della città è di stile gotico valenciano con interventi rinascimentali.</p>\n<p>Il <strong>Palacio de la Generalitat</strong> Valenciana, situato nel <strong>Barrio de la Seu</strong> o <strong>Barrio de la Catedral</strong>, iniziò la sua costruzione nel 1421 e fu ampliato nel XVI secolo con una grande torre.</p>\n<p>I canteros si incaricarono del lavoro usando pietra nera di Alcublas, marmo bianco della Valldigna e pietra di Ribarroja, località vicine a Valencia.</p>",
  "482": "<p>L'edificio fu ampliato nel XVI secolo con una seconda grande torre di dimensioni simili alla prima.</p>\n<p>Per costruirla, i canteros utilizzarono pietra nera di Alcublas, marmo bianco della Valldigna e pietra di Ribarroja, località vicine a Valencia.</p>",
  "482-B": "<p>Attualmente, ospita la sede del Governo della Comunità Valenciana.</p>",
  "483": "<p>Quale delle due torri credono sia la più recente, quella della piazza o quella che ha davanti adesso?</p>",
  "484": "<p>La risposta? Quella che ha davanti!</p>",
  "485": "<p>Non metta in pausa questa audioguida. Si posizioni con il monumento appena menzionato alla sua mano sinistra e continui, come indica la sua mappa, per la strada che si apre alla sua destra.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>45</mark>.</p>",
  "485-B": "<p>Non metta in pausa questa audioguida. Si posizioni con il monumento appena menzionato alla sua mano sinistra e continui, come indica la sua mappa, per la strada che si apre alla sua destra, che sulla sua mappa corrisponde al numero <mark>4</mark>.</p>",
  "486": "<p>La nota <strong>Calle Caballeros</strong> corrisponde all'asse est-ovest che percorreva l'antica città romana, chiamata, in quei tempi, la via Decumanus Maximus.</p>\n<p>Il Complesso Monumentale della Cattedrale, la costruzione del <strong>Palacio de la Generalitat</strong> e la vicinanza alla Iglesia de San Nicolás incentivarono l'insediamento delle famiglie nobili lungo questa nota strada.</p>\n<p>A causa di questo fatto, il valore storico e artistico della <strong>Calle Caballeros</strong> si basa nell'essere il punto di concentrazione del potere della città.</p>\n<p>In essa si trovano numerosi palazzetti dove viveva gran parte della nobiltà Valenciana.</p>\n<p>La <strong>Calle Caballeros</strong> mantiene il suo nome dal 1412.</p>\n<p>Mantenere lo stesso nome per così tanto tempo è un'impresa notevole per una strada di qualsiasi città.</p>",
  "487": "<p>Continui per la <strong>Calle Caballeros</strong> fino al prossimo punto di interesse.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>46</mark>.</p>",
  "487-B": "<p>Continui per la <strong>Calle Caballeros</strong> fino al prossimo punto di interesse.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>5</mark>.</p>",
  "488": "<p>La <strong>Iglesia de San Nicolás</strong> si trova qualche metro più avanti, alla sua sinistra.</p>\n<p>Presti attenzione all'ingresso perché risulta sproporzionatamente piccolo rispetto alle dimensioni dell'interno del tempio e potrebbe passare inosservato.</p>",
  "489": "<p>La <strong>Iglesia de San Nicolás</strong> de Bari y San Pedro Mártir, nota anche come \"la piccola Cappella Sistina di Valencia\", è un tempio di struttura gotica con decorazione barocca al suo interno.</p>\n<p>Inizialmente costruita nel 1245 su un'antica moschea araba, la chiesa subì una riforma integrale nel 1455 conferendole la sua fisionomia gotica attuale.</p>\n<p>Nel 1693 la volta gotica fu rivestita con una di stile barocco, più consona all'epoca.</p>\n<p>Intorno all'anno 1700, al suo interno, fu avviato un ambizioso progetto che avrebbe ricoperto con affreschi oltre 2.000 metri quadrati.</p>\n<p>La <strong>Iglesia de San Nicolás</strong> fu dichiarata Monumento Storico Artistico Nazionale nel 1981 e oggi è una delle chiese più visitate della città di Valencia.</p>",
  "490": `<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e ammirare i numerosi e imponenti dettagli degli affreschi della cappella.</p>\n<p>Quando deciderà di continuare, osservi la sua mappa che la conduce a girare intorno alla chiesa per poterne contemplare le altre facciate, degne anch'esse di menzione.</p>\n<p>A tal fine, prenda la prima strada che esce alla sua mano sinistra.</p>`,
  "491": "<p>Con la porta di San Nicolás alla sua sinistra, si diriga a girare intorno alla chiesa e si posizioni al centro della piazza; da lì potrà vedere un semplice portale in stile gotico.</p>",
  "492": "<p>L'obiettivo di questo cambiamento costante è poter dare spazio a tutti, per questo ogni due settimane vengono esposti stili diversi e periodicamente si organizzano lezioni aperte di ballo.</p>",
  "493": "<p>Il portale fu costruito nel XV secolo, con archetti che poggiano su sottili colonne.</p>\n<p>Gli archetti sono elementi decorativi che risolvono il problema estetico presentato dai vani o dislivelli che possono esserci in un muro spesso; si evita così la sensazione di tunnel che può generare, e si permette l'ingresso di più luce all'interno dello spazio.</p>\n<p>Lo stile gotico si caratterizza per i suoi archi a sesto acuto. Questo, in particolare, è sormontato da un arco conopiale.</p>\n<p>Immagini che l'arco si divida in quattro segmenti. Il risultato sarebbe: due curve concave e due convesse, caratteristiche di questo tipo di archi.</p>\n<p>Proprio sotto il vertice di questo arco conopiale che menzioniamo, si trova un curioso rilievo. Concentri la sua attenzione... È una rappresentazione di un vassoio... con... della carne?</p>\n<p>La leggenda racconta che mentre San Nicola era in viaggio si fermò in una locanda per cenare e l'oste gli servì un piatto di carne.</p>\n<p>Mentre stava per benedire la sua cena, il Santo osservò che la carne era umana.</p>\n<p>Nicola denunciò l'oste poiché nelle sue cantine furono trovati anche resti smembrati di tre adolescenti che il Santo ricompose e resuscitò miracolosamente.</p>",
  "494": "<p>Concentri la sua attenzione su questo arco conopiale, luogo nel quale un rosone gotico del 1455 illumina la Chiesa.</p>\n<p>Questo rosone, che assume la forma della Stella di Davide o Sigillo Salomonico, è simile a quello che ha visto nella Cattedrale.</p>",
  "494-B": "<p>Concentri la sua attenzione su questo arco conopiale, luogo nel quale un rosone gotico del 1455 illumina la Chiesa.</p>\n<p>Questo rosone, che assume la forma della stella di Davide, è molto simile a quello che vedrà nella <strong>Cattedrale di Valencia</strong> nel corso di questa avventura.</p>",
  "495": "<p>Nella parte destra della porta, c'è una cappella chiusa da una cancellata.</p>\n<p>In essa si può vedere un pannello in ceramica che rappresenta il \"Cristo de Fossar\".</p>\n<p>Prende questo nome dall'antico cimitero che si trovava proprio sotto i suoi piedi.</p>",
  "496": "<p>Cosa si può vedere in questo pannello in ceramica? Sono teschi? È una croce? C'è anche una colomba?</p>",
  "497": "<p>Il campanile, che si trova proprio alla destra, fu completato nel 1755 e restaurato nel 2007.</p>\n<p>Può osservare che la torre si compone di tre corpi:</p>\n<p>Il primo, quello che raggiunge l'altezza del tetto.</p>\n<p>Il secondo, quello costruito in mattoni, e il terzo è quello che ospita le campane, le quali si possono percepire attraverso gli archi a tutto sesto.</p>",
  "498": "<p>Quante campane ospita questa torre? 3, 4 o 5?</p>",
  "499": "<p>La sua mappa del tesoro le indica di continuare a costeggiare la chiesa per vedere l'ultima delle sue porte.</p>\n<p>Una splendida ricostruzione neogotica del 1864 congeda questo punto e apre il passo al successivo.</p>",
  "500": "<p>Continui fino alla fine della strada, poi giri a sinistra e segua la strada fino a vedere il prossimo punto di interesse alla sua destra; lì emerge la <strong>Fuente del Negrito</strong>.</p>\n<p>Sulla sua mappa corrisponde al numero <mark>48</mark>.</p>\n<p>Ricordi di premere pausa, poi visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
