import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "620": "<p>El Morro, nummer <mark>71</mark> op uw kaart, is een prachtig uitkijkpunt vanwaar u het volledige <strong>Parque de cabecera</strong> kunt zien, en de beroemde <strong>Bioparc</strong>, die overeenkomt met nummer <mark>73</mark> op uw kaart.</p>",
  "620-B": "<p>El Morro, nummer <mark>14</mark> op uw kaart, is een prachtig uitkijkpunt vanwaar u het volledige <strong>Parque de cabecera</strong> kunt zien, en de beroemde <strong>Bioparc</strong>, die overeenkomt met nummer <mark>15</mark> op uw kaart.</p>",
  "621": "<p>Dit laatste is onderverdeeld in duidelijk afgebakende zones: aan de rechterkant bevindt zich de toegang tot de dierentuin. Daar bevinden zich de kassa's waar u toegangskaartjes kunt kopen.</p>",
  "622": "<p>Kunt u de brug zien die over het meer loopt? Dat is de toegang tot het tentoonstellingsterrein, dat aan uw linkerkant ligt.</p>\n<p>Neem plaats en maak u gereed om te genieten, want vanaf dit verhoogde punt waarop u zich nu bevindt, zullen wij verschillende punten van uw Avontuur bespreken.</p>",
  "623": "<p>Het <strong>Parque de Cabecera</strong> strekt zich 15 meter onder uw voeten uit en dankt zijn naam aan zijn ligging aan het hoofd van de oude bedding van de <strong>Río Turia</strong> bij haar intrede in Valencia.</p>\n<p>Aangelegd tussen 2002 en 2014, draait het park rond een kunstmatig meer waar men kan roeien.</p>\n<p>In de wateren van dit meer leven karpers, schildpadden en kikkers, evenals eenden en zwanen die al gewend zijn geraakt aan de vreedzame aanwezigheid van mensen.</p>",
  "624": "<p>In het <strong>Parque de Cabecera</strong> groeien bomen en struiken die passen bij het mediterrane klimaat; in het bijzonder soorten die geassocieerd worden met de oevers en de bedding van de <strong>Río Turia</strong>: iepen, populieren, espen en dennen vormen er kleine bosjes.</p>\n<p>In contact met het water leven amfibische plantensoorten, lisdodden en biezen die het meer structureren en onderdak bieden aan de diersoorten die er leven.</p>\n<p>In het park groeien ook goed gestructureerde groepen struiken en houtige kruiden zoals rozemarijn, tijm en esparto, typisch voor het semiaride mediterrane klimaat.</p>",
  "625": "<p>Dit metropolitane park van bijna 168.000 vierkante meter is gericht op het herstel van het oorspronkelijke landschap van de <strong>Río Turia</strong>.</p>\n<p>Het water ontspringt bij de Molí del Sol en volgt de oude natuurlijke loop van de rivier totdat het uitmondt in het meer, waarbij het typische sedimentatie-eilandjes achterlaat die kenmerkend zijn voor de mediterrane geografie.</p>\n<p>De stenen muren en de verschillende niveaus van het terrein creëren een intieme omgeving met weite vergezichten.</p>\n<p>Een duidelijk voorbeeld: dit is de plek waar u zich nu bevindt, van waaruit u in de verte het Nationaal Park Sierra de Calderona kunt zien.</p>",
  "626": `<p>Tijdens Fallas loopt u veel, comfortabel schoeisel is onmisbaar. Terwijl u het volgende interessante punt van uw Avontuur bereikt, wil ${LOGO} u graag deze tips meegeven voor een volledige beleving van het feest.</p>`,
  "627": "<p><strong>Bioparc</strong> is de nieuwe dierentuin van Valencia die zijn voorganger heeft vervangen sinds 2008.</p>\n<p>De vroegere dierentuin van Valencia, die in 2007 sloot, werd gesticht in 1965 en bevond zich in de beroemde <strong>Jardines del Real</strong> die u verderop in dit Avontuur in detail zult ontdekken.</p>\n<p>Anders dan in de oude dierentuin waar de dieren opeengepakt leefden, geeft <strong>Bioparc</strong> de bezoeker het gevoel dat hij de leefomgeving van het dier betreedt, dankzij een ontwerp dat de barrières tussen het publiek en de dieren verbergt en zo een zoö-onderdompelingseffect creëert.</p>\n<p>Dit ruimte van 100.000 vierkante meter herschept de Afrikaanse fauna en herbergt meer dan 800 dieren van diverse soorten van het Afrikaanse continent, waarbij het leefgebied van elk dier wordt nagebootst.</p>\n<p><strong>Bioparc</strong> is verdeeld in vier biotische gebieden: droge savanne en vochtige savanne, Madagascar en de wouden van equatoriaal Afrika.</p>",
  "628": `<p>Dit innovatieve zoö-onderdompelingsproject heeft als doel gedragsverandering te stimuleren; wij houden van dieren en wij willen dat die verandering ons motiveert om in harmonie met de planeet te leven.</p>\n<p>Vandaar hun motto: bewegen om te bewaren.</p>\n<p>Als u hier bent tijdens de openingstijden, nodigt ${LOGO} u uit om op pauze te drukken en de biodiversiteit van deze prachtige ruimte te ontdekken.</p>\n<p>U kunt uw avontuur hervatten wanneer u dat wenselijk acht.</p>\n<p>Gebruik de pauzeknop naar eigen goeddunken; wanneer u het moment juist acht, blijf dan onze uitdagingen oplossen terwijl u de stad ontdekt. Geniet op uw eigen tempo van dit park met een duizendjarige inspiratie.</p>\n<p>Uw Avontuur gaat verder achter de majestueuze gebouwen aan uw linkerkant.</p>\n<p>Het <strong>Museo de Historia</strong> van Valencia is waarschijnlijk een van de beste plaatsen om meer te leren over de mediterrane cultuur waarin u zich vandaag bevindt.</p>`,
  "628-B": `<p>Als u hier bent tijdens de openingstijden, nodigt ${LOGO} u uit om op pauze te drukken en de biodiversiteit van deze prachtige ruimte te ontdekken.</p>\n<p>U kunt uw avontuur hervatten wanneer u dat wenselijk acht.</p>\n<p>Gebruik de pauzeknop naar eigen goeddunken; wanneer u het moment juist acht, blijf dan onze uitdagingen oplossen terwijl u de stad ontdekt. Geniet op uw eigen tempo van dit park met een duizendjarige inspiratie.</p>`,
  "629": "<p>Maak gebruik van het openbaar vervoer, met name de metro in de week van 15 tot 19 maart, omdat veel straten afgesloten zullen zijn. Desondanks zijn de elektrische step, de fiets of zelfs, voor wie ze kan gebruiken, schaatsen uitstekende vervoermiddelen.</p>",
  "630": "<p>Staat u voor het <strong>Museo de Historia</strong> van Valencia? Uitstekend! Perfect!</p>\n<p>Het huidige <strong>Museo de Historia</strong> is gevestigd in de oude drinkwaterreservoirs die in 1850 werden gebouwd als onderdeel van het algemene watervoorzieningsproject voor de stad, een van de eerste in Europa.</p>\n<p>Het water werd stroomopwaarts opgevangen, naar dit punt gevoerd en van hieruit verdeeld naar de acht openbare fonteinen van de stad.</p>\n<p>Bedenk dat in die tijden de openbare fonteinen de ontvangers waren van de pas aangelegde drinkwatervoorziening van de stad.</p>",
  "631": "<p>Uitgegraven in de ondergrond en overdekt met 11 bakstenen gewelven gedragen door 250 pilasters of bakstenen zuilen, garandeerde het oude reservoir de opslag van 9.000 kubieke meter water en maakte gebruik van de natuurlijke hoogteverschillen in de bodem om de nodige waterdruk te verkrijgen.</p>\n<p>Met de tijd en de groeiende vraag was het noodzakelijk nieuwe waterreservoirs te bouwen en dit reservoir raakte enkele decennia in onbruik. Aan het einde van de jaren negentig werd het respectvol gerestaureerd voor zijn huidige gebruik.</p>",
  "632": `<p>Met een oppervlakte van 2.600 vierkante meter wijdt het interactieve Geschiedenismuseum zich aan het verspreiden van de geschiedenis van Valencia vanaf haar oorsprong tot heden.</p>\n<p>Deze schat van de stad werd in 2003 geopend met een innovatieve museografische aanpak gericht op communicatie met de bezoeker.</p>\n<p>Het museum toont talrijke archeologische, architectonische en historische artefacten, maar wat ongetwijfeld uitblinkt in de tentoonstelling is het gebruik van nieuwe audiovisuele technologieën.</p>\n<p>In dit gebied kunt u interageren met het verleden door te kiezen uit meerdere scenario's die het leven van de bewoners en hun dagelijkse bezigheden nabootsen, zodat u de zorgen en bekommeringen van die tijd kunt begrijpen.</p>\n<p>Als u hier bent tijdens de openingstijden, raadt ${LOGO} u aan op pauze te drukken en dit cultureel centrum op uw eigen tempo te bezoeken.</p>\n<p>U kunt uw avontuur hervatten wanneer u dat wenselijk acht. Druk eenvoudigweg op de betreffende knop en ga verder <i>op zoek naar de schat</i>.</p>`,
  "633": "<p>Vouw uw kaart open en bekijk die; deze geeft aan dat u de bedding van de oude <strong>Río Turia</strong> opnieuw dient op te zoeken en het fietspad aan uw rechterkant te nemen.</p>\n<p>We keren terug naar de historische kern, maar dit is nog niet het einde! Volg het voorgestelde traject en u zult zien dat na 5 bruggen uw volgende interessante punt op u wacht.</p>",
  "634": "<p>Dit decoratieve element heeft zijn oorsprong in 1592.</p>\n<p>Het doel ervan was de rivier in te dammen en mogelijke overstromingen te voorkomen, hoewel dit element in het middeleeuwse Valencia een veel duisterder verleden had.</p>\n<p>De volkslegende vertelt dat dit de gevreesde brandplaats was.</p>\n<p>De plek waar de Heilige Inquisitie ketters, slaven, bezetenen, heksen en prostituees verbrandde nadat hun de zwaarste straf was opgelegd.</p>",
  "635": "<p>Richt uw aandacht op de vloer van de oprit die toegang geeft tot het bovenste deel van de brug; er steken nog kleine drempelstenen uit die het leven van de burgers die deze oude rivierovergang betraden gemakkelijker maakten.</p>\n<p>Welk gebruik konden die drempels hebben? Om water tegen te houden? Om de wielen van karren te stoppen en zo het laden en lossen voor de dieren te vergemakkelijken? Of misschien om wier en ander vuil van de rivier op te vangen?</p>",
  "636": "<p>Vouw uw kaart open en bekijk die. Uw Avontuur gaat verder over het begroeide pad totdat u de opgang vindt die u weer naar de stad voert.</p>\n<p>Eenmaal boven bevindt uw volgende uitdaging zich bij het standbeeld dat de brug zijn naam geeft.</p>\n<p>De <strong>Puente de San José</strong> bevindt zich op de tweede brug vanaf uw positie.</p>\n<p>Wilt u zich voor het standbeeld plaatsen dat in het midden van de brug staat?</p>",
  "637": "<p>Jozef van Nazareth, echtgenoot van Maria Magdalena en pleegvader van Jezus Christus, was van beroep ambachtsman; daarom neemt de Gemeenschap Valencia hem aan als haar Beschermheilige.</p>\n<p>19 maart, Vaderdag, is een speciale dag in heel Spanje ter ere van Sint-Jozef.</p>\n<p>Maar in het bijzonder in Valencia is dit de meest magische dag van het jaar, want hier worden de beroemde Fallas verbrand.</p>",
  "638": "<p>De oorsprong van dit feest gaat terug tot de 18e eeuw.</p>\n<p>Een oude traditie van de timmerlieden van de stad die, aan de vooravond van het feest van hun patroonheilige, oude en nutteloze rommel verbrandden op de openbare pleinen, samen met de overgebleven houten gereedschappen van hun werk.</p>\n<p>Aanvankelijk bestond de Falla uit brandstapels van brandbaar materiaal dat geleidelijk evolueerde naar de monumenten die men vandaag de dag kan zien.</p>\n<p>De Fallas zijn uitgegroeid tot een zeer belangrijke toeristische attractie; naast hun catalogisering als Fiesta de Interés Turístico Internacional (Feest van Internationale Toeristische Interesse), schreef de UNESCO ze in november 2016 in op haar Representatieve Lijst van het Immaterieel Cultureel Erfgoed van de Mensheid.</p>",
  "639": "<p>Neem het geconditioneerde pad dat u terugbrengt naar de <strong>Torres de Serranos</strong>. Dit correspondeert met nummer <mark>1</mark> op uw kaart.</p>\n<p>Bedenk dat u niet meer naar de tuin hoeft af te dalen; uw Avontuur gaat verder op stedelijk terrein.</p>\n<p>Ga vanaf dit punt met voorzichtigheid te werk, omdat dit een stedelijk traject is en de verkeersregels moeten worden nageleefd.</p>\n<p>Kijk naar de aanwijzingen op uw schatkaart en ga verder over het fietspad om het historische centrum te betreden op zoek naar extra aanwijzingen.</p>\n<p>Vergeet niet op pauze te drukken, ga daarna naar het aangegeven punt en druk opnieuw op de knop doorgaan zodra u op de voorgestelde plek aankomt.</p>",
  "640": "<p>Bent u bij de torens aangekomen? Richt uw aandacht.</p>",
  "641": "<p>Wist u dat de vlag van Valencia een eigen naam heeft?</p>\n<p>Zoals u kunt zien, is de Real Senyera van Valencia een driekleurig embleem dat bestaat uit horizontale rode en gele strepen met een blauwe streep bij de mast.</p>\n<p>Richt uw aandacht op dat blauwe gebied en u kunt de kroon onderscheiden die haar de koninklijke rang verleent.</p>",
  "642": "<p>In de loop van haar geschiedenis hebben de Valencianen bemiddeld in verdragen en zijn zij betrokken geweest bij veldslagen, opstanden en machtsovernames in kritieke tijden.</p>\n<p>Tijdens oorlogen moesten de naburige steden het embleem van Valencia volgen, vanwaar de bevelen uitgingen. Dat noemde men in de volksmond \"de Senyera volgen\".</p>\n<p>Vanwege al deze heldendaden is de vlag van Valencia de enige in Spanje met een koninklijke rang, en buigt zij voor niets noch niemand.</p>",
  "643": "<p>Een interessant weetje: wanneer de vlag wordt verplaatst, moet de mast te allen tijde recht gehouden worden.</p>\n\n<p>Bedenk dat dit een perfect punt is om een prachtige foto te maken van dit monument dat is verklaard tot van historisch en artistiek belang.</p>",
  "644": "<p>Uw schatkaart geeft aan dat u naar de riviergeul moet afdalen.</p>\n\n<p>Keer daarvoor terug naar de torens en volg het fietspad aan uw linkerkant tot aan het afdaalpunt.</p>\n\n<p>Eenmaal beneden, begeef u naar het midden van de bedding.</p>\n\n<p>Iets verderop, in de richting van het Museo de Bellas Artes, opent zich een tijdportaal. Tussen cipressen en olijfbomen zijn resten van het Palacio del Real te aanschouwen.</p>",
  "645": "<p>Het oude Palacio del Real werd aanvankelijk in de 9e eeuw gebouwd als Almunia, een moslim buitenverblijf waar de sultans van de Taifa van Balansiya zich terugtrokken om te rusten.</p>\n\n<p>Dit bleef zo tijdens de christelijke verovering en het was in de 14e eeuw dat het begon te worden herbouwd om het paleis te worden van de Koningen van de Kroon van Aragón tijdens hun verblijf in het Koninkrijk Valencia.</p>\n\n<p>Het paleis stond bekend als \"het Paleis van de 300 sleutels\", verwijzend naar het aantal kamers dat het ooit had.</p>",
  "646": "<p>Het is van belang te vermelden dat dit paleis niet meer bestaat.</p>\n\n<p>Als herinnering resten ons de gravures die het afbeelden.</p>\n\n<p>In 1810 werd het oude paleis door de Valencianen ontmanteld om strategische verdedigingsredenen, uit vrees dat het een bolwerk zou kunnen worden voor de invasietroepen van Napoleon.</p>\n\n<p>Tegenwoordig resten ons blootgelegde overblijfselen die de centrale rijstroken afbakenen van bepaalde gedeelten van de Jardín del Turia en de beroemde Jardines del Real, die destijds slechts een klein deel bezetten van wat de Tuinen van het Paleis waren.</p>\n\n<p>De Jardines del Real bieden een wandeling langs eeuwenoude palmbomen, een enorme volière uit 1933, evenals een vijver met eenden en zwanen, een prachtige rozentuin en ook talrijke beeldhouwwerken en monumentale fonteinen.</p>\n\n<p>Nog belangrijker: de tuinen beschermen een deel van de geschiedenis van Valencia in hun binnenste.</p>",
  "646-A": "<p>Het is van belang te vermelden dat dit paleis niet meer bestaat.</p>\n\n<p>Als herinnering resten ons de gravures die het afbeelden.</p>\n\n<p>In 1810 werd het oude paleis door de Valencianen ontmanteld om strategische verdedigingsredenen, uit vrees dat het een bolwerk zou kunnen worden voor de invasietroepen van Napoleon.</p>\n\n<p>Tegenwoordig resten ons blootgelegde overblijfselen die de centrale rijstroken afbakenen van bepaalde gedeelten van de Jardín del Turia en de beroemde Jardines de Viveros, die destijds slechts een klein deel bezetten van wat de tuinen van het paleis waren.</p>",
  "647": "<p>Dit Avontuur nodigt u uit de kaart te volgen naar de ingang van deze tuinen.</p>\n\n<p>Als groene long van de stad bevindt de populairste toegang tot de Jardines del Real zich in een ondergrondse doorgang die de avenue kruist en u rechtstreeks naar een van de hoofdingangen leidt.</p>",
  "647-B": "<p>Volg uw kaart naar de ingang van de Jardines de Viveros, die is aangegeven met nummer <mark>4</mark> op uw kaart.</p>\n\n<p>Als groene long van de stad vindt u de populairste toegang tot deze tuinen in een ondergrondse doorgang die de avenue kruist en u rechtstreeks naar een van de hoofdingangen leidt.</p>\n\n<p>Druk op pauze, ga daarna naar het aangegeven punt en druk opnieuw op de knop doorgaan zodra u op de voorgestelde plek aankomt. Dank u.</p>",
  "648": "<p>Bewonder de hoofdingang. Een romantische poort van smeedijzer die dateert uit 1860. Het uitgestrekte terrein wordt omgeven door een sobere omheining van hetzelfde materiaal, gedragen door een sokkel en pilaren van steen.</p>",
  "648-B": "<p>Bewonder de hoofdingang, een romantische poort van smeedijzer die dateert uit 1860.</p>\n\n<p>De Jardines de Viveros bieden een wandeling langs eeuwenoude palmbomen, een enorme volière uit 1933, evenals een vijver met eenden en zwanen, een prachtige rozentuin en talrijke beeldhouwwerken en monumentale fonteinen.</p>\n\n<p>Nog belangrijker! De tuinen beschermen in hun binnenste een deel van de geschiedenis van Valencia.</p>",
  "649": "<p>Dit Avontuur moedigt u aan deze tuinen te betreden die vanaf 1912 een Gemeentelijk Park zouden worden voor de recreatie van iedereen die ze wil bezoeken.</p>\n<p>Omdat het een vrij uitgestrekt gebied is, hebben wij het voor uw gemak afzonderlijk genummerd, beginnend bij de ingang van de tuinen, die op uw kaart overeenkomt met nummer <mark>1</mark>.</p>\n<p>Vanaf de ingang kunt u de vegetatie bewonderen die opvalt door de verscheidenheid aan bomen met exemplaren van grote omvang en leeftijd.</p>\n<p>Op de Palmenlaan (Paseo de las Palmeras) overheersen Canarische palmen, washingtoniapalmiers en dadelpalmiers. Dit correspondeert met nummer <mark>1</mark> op uw kaart.</p>\n<p>Pauzeer deze audiogids niet en begeef u naar de oude Jardines del Real.</p>",
  "649-B": `<p>Als u hier bent tijdens de openingstijden, raadt ${LOGO} u aan op pauze te drukken en te genieten van deze tuinen op uw eigen tempo!</p>\n\n<p>Gebruik de pauzeknop naar eigen goeddunken; wanneer u het moment gepast acht, ga dan eenvoudigweg verder met het oplossen van onze uitdagingen terwijl u de stad ontdekt.</p>\n\n<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 4.</p>\n\n<p>Wanneer u besluit verder te gaan <i>op zoek naar de schat</i>, kruis dan opnieuw de tunnel om toegang te krijgen tot de bedding van de Jardín del Turia.</p>`,
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
