import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "370": "<p>De <strong>Lonja de la Seda</strong> is het monument van de Valenciaanse Gouden Eeuw.</p>\n<p>De <strong>Lonja de Valencia</strong> was een Wall Street van de 15e eeuw.</p>\n<p>Het monument werd gebouwd tussen 1482 en 1497 en werd in 1996 uitgeroepen tot Werelderfgoed.</p>\n<p>Dit financiële gebouw begon als <strong>Lonja de la Seda</strong> omdat de beroemde «Zijderoute», een handelsroute die begon in Afrika en eindigde in China of India, door Valencia liep.</p>\n<p>Als aanvulling vermelden we dat op de beroemde route ook andere goederen werden verhandeld zoals specerijen, porselein, ijzer of thee, maar buiten haar commerciële doel was de Zijderoute ook een ruimte voor uitwisseling van ideeën en kennis.</p>\n<p>Het monument past op een rechthoekige kavel en beslaat meer dan 2.000 vierkante meter.</p>\n<p>De zuidzijde kijkt uit op de Plaza del Mercado waar u zich nu bevindt.</p>\n<p>De oostgevel grenst aan de calle de Pere Compte, de hoofdbouwmeester van het monument.</p>\n<p>De westzijde kijkt uit op de calle de los Cordellats, vanwaar de sinaasappeltuin te zien is,</p>",
  "371": "<p>En ten slotte de noordzijde naar de calle de la <strong>Lonja</strong>, uw volgende richting in dit avontuur.</p>",
  "372": "<p>Vanuit uw positie zijn vier delen te onderscheiden: Aan de rechterzijde de Sala de Contratación of Zuilenzaal waar de transacties plaatsvonden.</p>",
  "373": "<p>In het midden de Toren met drie bouwlagen gebruikt als kapel (de begane grond) en als gevangenis (de twee bovenste verdiepingen), waar dieven en oneerlijke handelaars werden vastgehouden totdat de autoriteiten kwamen om zich over hen te ontfermen.</p>",
  "374": "<p>Aan uw linkerzijde de Sala del Consulado del Mar (1498-1548), achteraf gebouwd met als doel maritieme en handelszaken te behandelen en te berechten; dit was het eerste handelstribunaal dat in Spanje werd gesticht.</p>",
  "375": "<p>Wij stellen u voor, vanuit dit punt, samen een tijdreis te maken naar de <strong>Lonja de Valencia</strong> via haar beeldhouwwerken.</p>\n<p>Deze activiteit bestaat erin de expressiviteit en originaliteit op te merken van haar portalen en waterspuwers, gesneden door de steenhouwers van de 15e eeuw:</p>",
  "376": "<p>De afbeelding van engelen die een schild vasthouden, op een van de buitenhoeken van het monument, een heraldisch en hemels teken dat ver verwijderd is van de overige figuren, is waarschijnlijk het meest onschuldige wat u op de muren van de <strong>Lonja de la Seda</strong> zult vinden.</p>",
  "377": "<p>Stel u op voor het vroegere hoofdportaal, de zogenoemde Puerta de los Pecados, gelegen aan de rechterzijde van de gevel die nu voor u staat.</p>\n<p>Het vraagt uw bijzondere aandacht en het vermogen 'tussen de regels' te lezen, haar talrijke boodschappen over de duisternis van de zonde en dus van het kwaad.</p>\n<p>Op dit portaal is het gemakkelijk honderden demonische figuren te vinden; monsters, wezens die door het kwaad zijn verslonden, tovenarij, mensen verschrikt door wellust en de hoofdzonden, erotische taferelen met een uitgesproken pervers en wellustig karakter; kortom scènes die ons voeren naar het overheersende obscurantisme in dit burgerlijke bouwwerk.</p>",
  "378": "<p>In de 15e eeuw konden veel handelaren, evenals de meerderheid van de burgers van de lagere klasse, niet lezen of schrijven; daarom interpreteerden zij de figuren als gids om de zonde te vermijden.</p>\n<p>Men mag niet vergeten dat in de Hoofdstad van de Turia een van de grootste bordelen van heel Europa was gevestigd. Daarom bekroont, als beschermingssymbool, de Maagd met Kind het portaal.</p>",
  "379": "<p>Wanneer u goed oplet, kunt u het volgende ontdekken:</p>\n<p>De roeier die tegen de stroom in roeit: een man met een verdrietig gezicht die een klein houten bootje bestuurt en ontsnapt aan een monster door tegen de stroom in te roeien.</p>",
  "380": "<p>Heeft u hem gezien? Vlucht onze man dan voor dat monsterlijke wezen dat verleiding wordt genoemd?</p>",
  "381": "<p>Een dode boom: symbool van de Zonde, zichtbaar tussen de twee deurvleugels en fungerend als middenstijl.</p>\n<p>Observeer in de kruin van de boom hoe 4 naakte mannen elkaar geselen.</p>\n<p>Heeft u ze allemaal gezien? Gefeliciteerd!</p>",
  "382": "<p>De <strong>Fuente del Negrito</strong> werd ingehuldigd in 1850.</p>\n<p>In die tijden waren de openbare fonteinen de ontvangers van het pas aangekomen drinkwater in de stad.</p>\n<p>De drinkwatervoorziening was nog niet algemeen beschikbaar in de woningen en men moest het ophalen bij de openbare fonteinen voor persoonlijk gebruik.</p>",
  "383": "<p>Schenk nu aandacht aan enkele van zijn waterspuwers; stap een eindje achteruit om ze bovenaan het gebouw te kunnen zien:</p>",
  "384": "<p>Aan de rechterzijde een engel die zijn penis toont en op het punt staat hem in een vaas te steken die hij met de andere hand vasthoudt. Iets vreemds en ongewoons, vindt u niet?</p>",
  "385": "<p>In het midden De bebaarde man en de leeuw:</p>\n<p>Een origineel en tegenstrijdig tafereel waarbij de tamme figuur juist de leeuw is en niet de bebaarde grijsaard.</p>\n<p>In werkelijkheid leiden de aanwijzingen ons naar het verhaal van Simson die een leeuw verslaat, een parallel met het leven van Jezus die strijdt tegen de Duivel.</p>",
  "386": "<p>Hier is een extra uitdaging!</p>\n<p>Zoek de fornicator van de <strong>Lonja</strong>!</p>\n<p>In een van haar ramen vindt u een man die fornicatie bedrijft met de muur van het belangrijkste burgerlijke gebouw van die tijd.</p>\n<p>Zijn hoofd is niet te zien, maar zijn geslachtsdelen wel, en zeer duidelijk.</p>\n<p>Of hij zijn behoeften doet.</p>",
  "387": "<p>Heeft u hem gezien? Bravo! Die was moeilijk!</p>",
  "388": "<p>Bekijk de kaart zorgvuldig. Vanuit uw perspectief leidt die u om de <strong>Lonja</strong> heen, om de hoek.</p>\n<p>De Patio de los Naranjos, die toegang geeft tot een open stenen trap die leidt naar de hoofdverdieping van het Consulaatspaviljoen, een ruimte waar vroeger de handelsrechters of -consuls hun zittingen hielden en die de drie zones van het gebouw met elkaar verbindt.</p>",
  "389": "<p>Is dit een goed moment om uw avontuur te beginnen? Ja, Nee</p>",
  "390": "<p>Bekijk de waterspuwer van de toren.</p>\n<p>Aan de linkerzijde bevindt zich een volledig naakte vrouw die haar geslacht met beide handen aanraakt.</p>",
  "391": "<p>Een figuur zonder sensualiteit en erotiek die de handeling van masturbatie uitbeeldt (zondig volgens de moraal van die tijd).</p>\n<p>We keren terug naar de wellust, het meest overheersende thema in de sculpturen die het gebouw versieren.</p>\n<p>Het is waarschijnlijk de meest herkenbare, beroemde en op het eerste gezicht verrassende figuur van de <strong>Lonja de la Seda</strong> van Valencia.</p>\n<p>Sinds de 15e eeuw aanschouwen de <strong>Lonja</strong> en haar ogenschijnlijk deugdzame maar met obsceniteit geladen figuren de straten van deze stad Valencia.</p>\n<p>Standbeelden die tot leven komen op de muren van een gebouw dat niet langer in de 15e eeuw staat maar in de 21e, en waarvan de voorbijgangers bij het zien ervan stilstaan en zich afvragen: Wat willen ze ons zeggen?</p>",
  "392": `<p>Verderop, langs het gebouw, vindt u de toegangsdeur tot het monument.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit monument te bezoeken om de geschiedenis van de stad en haar gebruiken beter te leren kennen.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht.</p>`,
  "393": "<p>Stel u op met de toegangsdeur van de <strong>Lonja</strong> in uw rug en ga naar rechts tot u de oude deur bereikt die toegang geeft tot het gebouw; dit is de laatste die u nog te zien heeft.</p>\n<p>Eenmaal daar, bekijk de ingang aandachtig terwijl u het volgende verhaal beluistert.</p>",
  "394": "<p>De officieel door de katholieke kerk «heilig verklaarde» heiligen zijn er ongeveer 10.000.</p>\n<p>Een lang proces dat veel tijd in beslag kan nemen vanwege de complexiteit ervan.</p>\n<p>De postulant moet een dienaar van God zijn; daartoe moet zijn leven voorbeeldig en deugdzaam zijn.</p>\n<p>Een gespecialiseerde instelling verzamelt de voornaamste aspecten van zijn leven en stelt deze samen als deugden en geschriften van de persoon.</p>\n<p>Als zijn daden heldhaftig waren, verklaart de Heilige Vader hem tot «Eerbiedwaardige Persoon».</p>\n<p>Na het verrichten van het eerste wonder zal de persoon worden zaligverklaard.</p>\n<p>Om heilig verklaard te worden, moest de postulant ten minste 3 wonderen hebben verricht waaruit zijn voorspraak bleek.</p>",
  "395": `<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit monument op eigen tempo te bezoeken om wat meer te weten te komen over de geschiedenis van de stad.</p>`,
  "396": `<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en deze ruimte binnen te gaan om de geschiedenis van de stad beter te leren kennen.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht; druk simpelweg op de bijbehorende knop en ga verder <i>op zoek naar de schat</i>.</p>\n<p>Uw avontuur gaat verder op dit zelfde punt.</p>`,
  "397": "<p>Vanuit uw nieuwe perspectief, met de deur van het monument recht voor u, draai naar links en u ziet een open plein.</p>\n<p>Ga, als u zo vriendelijk wilt zijn, naar het open plein aan uw linkerzijde.</p>",
  "398": "<p>Dit is de plek waar de oorspronkelijke <strong>Lonja de Valencia</strong> stond.</p>\n<p>Er zijn gegevens over haar bestaan vanaf 1344.</p>\n<p>In de oude <strong>Lonja</strong> werd gehandeld in olie en specerijen en zij bleef tot de 19e eeuw in gebruik.</p>\n<p>Maar door de toenemende immigratie werden de handelaren van de 15e eeuw gedwongen een groter gebouw te bouwen om de onverwachte toename van commerciële activiteit op te vangen die de stad tijdens haar Gouden Eeuw beleefde.</p>",
  "399": "<p>U bevindt zich nu op de plek waar, volgens de overlevering, een van de bekendste wonderen van Valencia plaatsvond.</p>",
  "400": "<p>In 1358 predikte Vicente Ferrer voor de deuren van de oude <strong>Lonja de Valencia</strong>.</p>\n<p>De preek die Vicente Ferrer die dag hield, herinnerde de goede mensen aan de noodzaak om degenen te helpen die leden en stierven van armoede en honger, en dat liefdadigheid vereist was.</p>\n<p>De toenmalige theoloog van de <strong>Kathedraal van Valencia</strong> haalde, om dat te bewijzen, een zakdoek tevoorschijn en wierp hem in de lucht terwijl hij de menigte zei de zakdoek te volgen.</p>\n<p>Waar de zakdoek neerkwam, zouden zij mensen vinden die werkelijk nood hadden aan hun liefdadigheid.</p>",
  "401": "<p>De zakdoek vloog tot een bepaald punt en de menigte kon vaststellen dat in dat huis een familie op het punt stond te sterven in de diepste armoede; het meelevende volk schoot de familie te hulp.</p>",
  "401-B": "<p>De zakdoek vloog tot dit punt, en de menigte kon vaststellen dat in dat huis een familie op het punt stond te sterven in de diepste armoede; het meelevende volk schoot de familie te hulp.</p>",
  "402": "<p>Op deze manier werd het bekende wonder van de Mocaoret geïnterpreteerd — wat in het Valenciaans «zakdoekje» betekent — dat de toekomstige Heilige van de Comunitat Valenciana zou hebben verricht.</p>",
  "403": "<p>In dit avontuur volgt u een deel van de vlucht van die zakdoek, die u naar de beroemde <strong>Plaza Redonda</strong> zal leiden.</p>\n<p>Vouw uw kaart open en bekijk hem: hij geeft aan dit plein aan uw linkerzijde te laten en de straat tegenover u in te slaan.</p>\n<p>Let op de kaart: uw volgende bestemming is de beroemde <strong>Plaza Redonda</strong>, gelegen in de vierde straat links en vervolgens de eerste rechts.</p>\n<p>Wilt u dat ik het herhaal? Natuurlijk, met plezier!</p>\n<p>Vierde straat links en vervolgens de eerste rechts.</p>",
  "404": "<p>Tijdens de Fallas is alles feest: het gebulder van de mascletà, de casales, de pasacalles, de bloemenhulde en de muziekkorpsen trekken langs meer dan 700 fallero-monumenten.</p>",
  "405": "<p>De voormalige vlees- en vismarkt, de <strong>Plaza Redonda</strong>, is het oculus van Valencia, een oog dat naar de hemel kijkt.</p>\n<p>Het correspondeert tegenwoordig met nummer <mark>36</mark> op uw kaart.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "405-B": "<p>Aan de rechterzijde van deze gevel met blinde bogen van de kerk bevindt zich de beroemde <strong>Plaza Redonda</strong>.</p>\n<p>De <strong>Plaza Redonda</strong> is het oculus van Valencia, een oog dat naar de hemel kijkt.</p>\n<p>De voormalige vlees- en vismarkt correspondeert tegenwoordig met nummer <mark>16</mark> op uw kaart.</p>",
  "406": `<p>Sinds de renovatie in 2012 heeft de <strong>Plaza Redonda</strong> het uiterlijk van een modern plein zonder zijn historische karakter te verliezen.</p>\n<p>Op dit plein wordt een grote Valenciaanse traditie levend gehouden.</p>\n<p>Nog steeds zijn er ateliers voor kloskantwerk te zien; een textieltechniek waarbij de draden over een patroon worden gevlochten om het borduursel te vormen.</p>\n<p>Een techniek die vaardigheden vereist zoals aandacht, concentratie, behendigheid en vooral fijne motoriek in de vingers.</p>\n<p>In het interieur van het plein zijn nog steeds winkels te vinden die gespecialiseerd zijn in kant en handgeborduurde kanten. Ook vindt u er prachtige souvenirs, allemaal in Valenciaanse stijl, en bars om onze typische tapas te proeven.</p>\n<p>${LOGO} raadt u aan op pauze te drukken en dit plein op eigen tempo te bezoeken.</p>`,
  "407": "<p>Zodra u besluit uw avontuur voort te zetten, daagt u het erop aan de juiste uitgang te vinden.</p>\n<p>Durft u het aan?</p>\n<p>Een van de meerdere mogelijke uitgangen leidt u naar een plein met verschillende bezienswaardige punten in uw Schattenjacht.</p>\n<p>Uw volgende bestemming is de Plaza de Santa Catalina, aangegeven op uw kaart met nummer <mark>37</mark>.</p>",
  "408": "<p>Wij hebben een bijzonderheid voor u klaar! Valencia is bezaaid met architectonische en historische schatten die we in elk van onze Avonturen onthullen.</p>",
  "409": "<p>Vanuit het midden van het plein kunt u een van de smalste gebouwen van Europa zien. Kunt u het zien?</p>\n<p>Stelt u zich voor: de eerste verdieping een eetkamer, de tweede de keuken, enzovoort.</p>",
  "410": "<p>Hoe breed is de ingang?</p>",
  "411": "<p>Deze Schattenjacht nodigt u uit de Santa Catalina te naderen; vanuit het midden van het plein kunt u de kerk in haar geheel aanschouwen.</p>\n<p>Zoals u kunt zien, wordt de kerk gedeeltelijk omringd door de aangrenzende huizen en ziet ze er van buiten vrij ruw uit.</p>",
  "412": "<p>De oorsprong van de <strong>Iglesia de Santa Catalina</strong> Mártir gaat terug tot de Reconquista van Valencia in 1238.</p>\n<p>Na de herovering en de daaropvolgende verandering van godsdienst in de stad, trachtte Jaime Eerste de stedelijke ruimte te structureren.</p>\n<p>Daartoe schonk hij het eigendom van alle moskeeën en islamitische begraafplaatsen aan het aartsbisdom, dat op zijn beurt deze tempels christianiseerde door ze te hernoemen als parochies gewijd aan heiligen van de nieuwe godsdienst die in deze landen zou worden ingevoerd.</p>\n<p>In mei 1239, slechts 1 jaar na de Reconquista, werd de Parroquia de Santa Catalina een van de tien stichtende parochies van de stad.</p>\n<p>We voegen hier ook aan toe dat het innemen van de moskeeën niet alleen een instrument van christianisering en kerkelijk toezicht op het buurtleven was, maar ook een instrument van administratieve en politieke organisatie; de gemeenteraad bestond inderdaad gedeeltelijk uit de verschillende parochies van de stad.</p>",
  "413": "<p>In de loop der jaren begon men parochies met christelijke plattegrond te bouwen op de plek van de vroegere moskeeën.</p>\n<p>De <strong>Iglesia de Santa Catalina</strong> werd voltooid in 1371. Maar in 1740 onderging ze een verbouwing die 15 jaar duurde en nagenoeg een totale vernieuwing van het kerkgebouw inhield.</p>",
  "414": `<p>Volgens de stadslegende werd in het contract tussen de architect en de kerk geen trap vermeld om de toren te beklimmen, waardoor de architect de toren bouwde zonder toegang tot de bovenste niveaus.</p>\n<p>Tegenwoordig is de toren toegankelijk via een wenteltrap die toegang geeft tot de balustrade.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en in het interieur van dit kerkgebouw te wandelen en ook de toren te bezoeken.</p>\n<p>Uw avontuur gaat verder vanaf dit zelfde punt waar u zich bevindt.</p>`,
  "415": "<p>De route vraagt uw bijzondere aandacht, want ze leidt u naar een verborgen verhaal op uw schatkaart. Zult u het kunnen ontdekken? Een reusachtige schelp uitgehouwen in steen, gelegen aan uw rechterzijde en aangebouwd tegen de steunmuur van de tuin zelf, onthult een deel van de tragische geschiedenis van de stad.</p>",
  "416": "<p>Richt uw aandacht op de gevel die nu voor u staat. Daarin zijn drie blinde bogen geopend.</p>\n<p>Twee ervan zijn glad; de derde werd onafgewerkt gelaten.</p>\n<p>Wat is er in die boog te zien? Kunt u een gezicht zien? Is er misschien een torso? En een waterspuwer?</p>",
  "417": "<p>Tot 1520 was op deze gevel het kantoor gevestigd dat verantwoordelijk was voor het toezicht op de markten en de openbare hygiëne; alsook voor de controle van de gewichten en maten van de stad, aangezien de slagerijen en viswinkels van de stad zich op slechts enkele meters bevonden.</p>\n<p>Vroeger was dit de commerciële en handelswijk waar de meeste belangrijkste gilden van de stad waren gevestigd.</p>",
  "418": "<p>Uw schatkaart leidt u om de kerk heen in de richting van de toren.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>38</mark>.</p>\n<p>Pauzeer deze audiogids niet en ga naar het aangegeven punt.</p>",
  "419": "<p>Stel u op, als u zo vriendelijk wilt zijn, op een punt vanwaar u de toren in zijn geheel kunt zien en neem de tijd om foto's te maken van dit prachtige monument; maak ook van de gelegenheid gebruik het van dichterbij te leren kennen.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
