import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "420": "<p>Santa Catalina Mártir is een te bezoeken toren die wordt beschouwd als een van de meest originele Barokke torens in de Spaanse architectuur.</p>\n<p>De eerste steen van deze klokkentoren werd gelegd in 1688 en hij werd uiteindelijk voltooid in 1705 in zijn huidige Barokke stijl.</p>\n<p>Zoals te zien is, heeft de toren een zeshoekige plattegrond.</p>\n<p>Hij verheft zich in vier verdiepingen, waaraan het klokkenhuis en een tempeltje moeten worden toegevoegd: dat is de bovenste constructie bestaande uit zuilen en een dak, vergelijkbaar met een tempel.</p>\n<p>Op elk van zijn verdiepingen zijn rijk gedecoreerde ramen in Barokke stijl die licht doorlaten naar de trap.</p>\n<p>In het klokkenhuis is de rijkste decoratie te bewonderen. Bewonder de Salomonskolommen die aan elk van hun ribben zijn omwonden.</p>\n<p>De zuilen kregen deze naam naar de toenmalige overtuiging dat de zuilen van de Tempel van Salomo er zo uitzagen.</p>\n<p>Het klokkenhuis wordt voltooid door de rondbogen die zich openen in elk van de vlakken van de toren.</p>\n<p>Als aanvulling: de 6 klokken die vanaf 1729 in de klokkentoren hingen, werden «las luteranas» (de lutheranen) genoemd omdat ze afkomstig waren uit Londen, een niet-katholiek land.</p>\n<p>Helaas kenden die klokken uiteenlopende lotgevallen.</p>",
  "421": "<p>De toren wordt bekroond door een tempeltje van twee verdiepingen dat wordt ondersteund door een reeks voluuten, zo genoemd vanwege hun slakken- of spiraaalvorm, die het centrale lichaam vasthouden.</p>\n<p>Hier herhalen zich de omwonden Salomonskolommen. Kunt u ze zien?</p>\n<p>Het tempeltje wordt gedekt door een koepel met stenen tegels in de vorm van visschubben.</p>\n<p>Boven op de koepel onderscheidt men een bol die de aardbol voorstelt en een windvaan, waardoor Santa Catalina een hoogte van meer dan 56 meter bereikt.</p>",
  "422": "<p>Welke kleur hebben de dakpannen van de koepel?</p>",
  "423": "<p>Wat bevindt zich helemaal bovenaan de toren? Kan het een kruis zijn? Misschien de zon? Of is er wellicht een duif?</p>",
  "424": "<p>Pauzeer deze audiogids niet. Uw schatkaart geeft aan de plaza over te steken en de toegang aan de tegenovergestelde zijde te zoeken.</p>\n<p>Vanaf 2012 veranderden dit plein en het aangrenzende, aan uw linkerhand, van een reeks ruïnes in twee gerenoveerde pleintjes die twee marktruimtes huisvesten.</p>\n<p>In <strong>Tapinería</strong>, zoals het geheel van pleinen bekend staat, heerst de filosofie van het vluchtige; waardoor het assortiment en de stijl elke 15 dagen verandert.</p>",
  "425": "<p>Volgens de traditie is de toren van Santa Catalina de verloofde van de <strong>Miguelete</strong>: «Twee geliefden die elkaar eeuwig aanstaren, maar de verlegenheid laat hen niet toe elkaar te naderen».</p>",
  "426": "<p>De <strong>Miguelete</strong> is een te bezoeken monument in Valenciaanse gotische stijl dat zijn naam ontleent aan zijn hoofdklok, die vanaf 1539 tot op heden de uren blijft luiden.</p>\n<p>Nader het monument, zoals uw kaart aangeeft.</p>",
  "426-B": "<p>Onze beroemde <strong>Miguelete</strong>, in Valenciaanse gotische stijl, ontleent zijn naam aan zijn hoofdklok, die vanaf 1539 tot op heden de uren blijft luiden.</p>\n<p>De iconische <strong>Miguelete</strong> fungeert als klokkentoren en uitkijkpunt omdat het het hoogste gebouw van de historische stad is.</p>\n<p>Na het beklimmen van de 207 treden biedt de <strong>Miguelete</strong> een 360 graden luchtpanorama van de hele stad.</p>\n<p>Het panorama dat hij biedt op 51 meter hoogte maakt het mogelijk de hele stad te zien met zijn tuin tot aan het strand, langs de <strong>stad van de kunsten en wetenschappen</strong> en de prachtige Valenciaanse huertas.</p>",
  "427": "<p>De iconische <strong>Miguelete</strong> bestaat uit vier bouwlagen van gelijke hoogte.</p>\n<p>Dit belangrijke punt van uw Avontuur fungeert als klokkentoren en uitkijkpunt omdat het het hoogste gebouw van de historische stad is.</p>\n<p>Kunt u de geometrie ervan bepalen? Zeshoekig, achthoekig of vierhoekig?</p>",
  "428": "<p>Oorspronkelijk was de <strong>Torre del Miguelete</strong> ontworpen om apart van de Kathedraal te worden gebouwd, maar een verbouwing in de 15e eeuw zorgde ervoor dat ze met de toren werd verbonden.</p>\n<p>Hoeveel ramen kunt u zien?</p>",
  "429": "<p>Richt uw aandacht enigszins naar rechts.</p>",
  "429-B": "<p>Richt uw aandacht enigszins naar links.</p>",
  "430": "<p>Na de bouw van de <strong>Miguelete</strong> werd de barokke deur van de kathedraal toegevoegd. Tegenwoordig is dit de hoofdingang.</p>\n<p>Gewoonlijk bekend als de «<strong>Puerta de los Hierros</strong>», verbindt ze het kerkgebouw met de <strong>Torre del Miguelete</strong> en sluit de ruimte af met het metalen hek dat het portaal zijn naam geeft.</p>\n<p>Dit grandioze ontwerp was bedoeld om een optische illusie te creëren, waardoor een relatief kleine ruimte groter aanvoelt door de traditionele rechte lijnen te vervangen door een concaaf-convexe curve.</p>\n<p>Op het portaal vallen de zuilen en het ovale roosvenster op dat de Kathedraal verlicht; daarboven een hoogreliëf dat de hemelvaart van de Maagd voorstelt.</p>\n<p>Het fronton van het portaal wordt bekroond door een bas-reliëf met het symbool van de Heilige Geest.</p>\n<p>Dit portaal, voltooid in 1741, is het meest moderne toegangspunt van de Kathedraal.</p>\n<p>Het is vermeldenswaard dat het werd gebouwd dankzij een schenking die een burgeresse in haar testament had opgenomen.</p>",
  "431": "<p>Wat is er te zien op meer dan 35 meter hoogte bovenaan het Barokke portaal? Is het een bol? Is het een kruis? Misschien een vleermuis? Of een paard?</p>",
  "432": `<p>In onze eeuw is de <strong>Puerta de los Hierros</strong> verdeeld in twee: de linkerzijde die de gelovigen toegang biedt en ook de klim naar de <strong>Miguelete</strong> mogelijk maakt.</p>\n<p>Van hieruit is ook het Hoofdaltaar te zien, een Renaissance-altaarstuk versierd met een schitterend gotisch decor.</p>\n<p>De rechterzijde biedt toegang tot het museumgedeelte van de Kathedraal. Van hieruit zijn ook de talrijke kapellen toegankelijk, waaronder die van San Vicente Mártir, waar de onbedorven arm van de Heilige wordt tentoongesteld.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit monument op eigen tempo te bezoeken.</p>\n<p>Na het beklimmen van de 207 treden biedt de <strong>Miguelete</strong> een 360° luchtpanorama van de hele stad.</p>\n<p>Het panorama dat de <strong>Miguelete</strong> biedt op 51 meter hoogte maakt het mogelijk de hele stad te zien, van zijn uitgestrekte tuin tot de <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Dit is een perfect punt voor panoramische foto's van de stad.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht; druk simpelweg op de bijbehorende knop en ga verder <i>op zoek naar de schat</i>.</p>\n<p>Uw avontuur gaat verder op dit zelfde punt.</p>`,
  "433": "<p>Laat de <strong>Plaza de la Virgen</strong> aan uw linkerzijde, ga door tot het einde van de straat en sla vervolgens rechts af.</p>\n<p>U bevindt u dan op de <strong>Calle de los Serranos</strong> die aan de rechterkant de wijk «La Seu» of de <strong>Kathedraalwijk</strong> scheidt en begrenst, en aan de linkerkant de wijk «El Carmen».</p>",
  "434": "<p>De bouw van de Kathedraal duurde 500 jaar om voltooid te worden en gedurende die lange periode veranderden de architecturale stijlen; daarom zijn in de <strong>Kathedraal van Valencia</strong> meerdere architecturale stijlen samengesmolten.</p>\n<p>De noordzijde is haar oudste gevel.</p>",
  "435": "<p>Deze stijlen zijn duidelijk zichtbaar in haar drie ingangen: de Barokke, de hoofdingang, die nu voor u staat.</p>\n<p>Op de westzijde bevindt zich het gotische portaal dat u in de loop van dit Avontuur zult zien, en aan de oostzijde de Romaanse ingang die uw volgende bestemming is.</p>",
  "436": "<p>Vooral het bekende «La Nit del Foc» (de Nacht van het Vuur) dat wordt afgeschoten in de nacht van 18 op 19 maart, waarbij meer dan een miljoen mensen samenkomen om het bij te wonen omdat het zich van de rest onderscheidt door het langste en meest spectaculaire te zijn.</p>",
  "437": "<p>Nader de ingang van de Kathedraal een beetje meer.</p>\n<p>De Romaanse ingang van de kathedraal, ook bekend als de Puerta del Palau, is een Romaans portaal in een kerkgebouw met gotische kenmerken.</p>\n<p>Aan de basis zijn aan elke zijde 12 voorstellingen uitgehakt met historische passages uit de Bijbel, het Genesis en het Exodus.</p>\n<p>Bijgenaamd de droge deur, bestaat ze uit zes rondbogen met geometrische motieven; erin zijn figuren te zien van serafijnen, engelen, kleine bogen en zeer fijn bewerkte loofversieringen.</p>\n<p>Boven de arcaden zijn de koppen van zeven koppels te vinden die volgens de overlevering zeven echte echtparen uit Lérida vertegenwoordigen, die meekwamen met driehonderd jonkvrouwen die zouden trouwen met de nieuwe kolonisten om Valencia na de oorlog te herbevolken.</p>",
  "438": "<p>Uit hoeveel bogen bestaat de deur?</p>",
  "439": "<p>Aan de rechterkant van de deur, ter hoogte van de knieën, bevinden zich langwerpige krassen.</p>\n<p>Op dit plein waar u zich nu bevindt, stond het platform waarop de beul de gevangenen executeerde.</p>\n<p>Oude verhalen vertellen dat dit de krassen zijn die de beul achterliet door zijn bijl altijd op dezelfde plek te slijpen, omdat slechts enkele meters van de deur de onheilspellende executieplaats zich bevond — een gebeurtenis die uiteraard openbaar was! — en het volk er naartoe mocht gaan om te zien hoe gerechtigheid werd gedaan.</p>",
  "440": "<p>Pauzeer deze audiogids niet en volg de omtrek van de tempelmuur.</p>",
  "441": "<p>Heeft u opgemerkt dat de muur van de Kathedraal afgerond is? De <strong>Kathedraal van Valencia</strong> is gebouwd op de vroegere Visigotische Seo die eeuwen later een Grote Moskee werd.</p>\n<p>In de 13e eeuw werd na de herovering de bouw van de Kathedraal geleidelijk voortgezet met gebruik van de Arabische moskee, waardoor het kerkgebouw een afgeronde vorm aanneemt in plaats van de traditionele kruisvorm.</p>\n<p>Tussen 1229 en 1245 veroverde de Kroon van Aragón het gebied dat later bekend zou worden als het Koninkrijk Valencia.</p>\n<p>Dankzij de troepen van koning Don Jaime Eerste werd Valencia in 1238 heroverd.</p>\n<p>Ter ere hiervan werd jaren later een oud paneel van traditioneel Valenciaans keramiek op de muur van de kathedraal geplaatst.</p>\n<p>Het stelt de viering voor van de mis die na de Reconquista werd gehouden.</p>",
  "442": "<p>Welke gebeeldhouwde figuur is te zien in de lijst van het paneel?</p>\n<p>Een draak, een vleermuis of misschien een kroon? Raad eens!</p>",
  "443": "<p>Precies één stap naar rechts opent zich een kleine kapel beschermd door een hek. Dit is de plek waar de eerste mis werd gevierd in het door Koning Jaime Eerste veroverde Valencia.</p>",
  "444": "<p>Wat is er binnen te zien?</p>\n<p>Een altaar, een vlag, is er ook een zwaard?</p>",
  "445": "<p>Daarboven hangt een gedenkplaat. In welk jaar werd die plaat geplaatst?</p>",
  "446": "<p>Enkele stappen verder, aan uw rechterhand, herbergt een andere kapel met hekwerk het standbeeld van San Vicente Ferrer, Patroon van Valencia.</p>",
  "447": "<p>In het gebouw dat tegenover de Kathedraal staat, verheft zich een imposante zwarte bronzen deur in hoogreliëf met kleine getraliede raampjes waardoor u het interieur van de <strong>Basílica de Valencia</strong> kunt aanschouwen.</p>",
  "448": "<p>Op 19 maart, Vaderdag in Spanje en gewijd aan de heilige Jozef, eindigen de Fallas met de Nit de la Cremà (de nacht van de verbranding).</p>",
  "449": "<p>In die nacht, vanaf 22 uur wanneer de kindermonumenten worden verbrand tot 1 uur 's nachts wanneer het monument van de <strong>Plaza del Ayuntamiento</strong> brandt, is het traditie om door Valencia te trekken en afscheid te nemen van de Fallas terwijl het werk van een heel jaar in vlammen opgaat.</p>\n<p>Ga verder naar de torens.</p>",
  "450": "<p>In 1652 begonnen de bouwwerkzaamheden van de basiliek en duurden in totaal 14 jaar.</p>\n<p>Tussen 1652 en 1660 werden de buitengevels gerealiseerd.</p>\n<p>In 1659 werd de bouw overeengekomen van een verhoogde doorgang die de Basílica met de Kathedraal verbindt, bekend als «arco novo», en begin 1661 begon de bouw van de ovale koepel met een breedte van bijna 19 meter.</p>\n<p>In 1666 werden de bouwwerkzaamheden van de Basílica voltooid en datzelfde jaar werd de overbrenging van de Maagd vanuit de Kathedraal geregeld.</p>",
  "451": "<p>De <strong>Basílica de Valencia</strong> herbergt in haar interieur het beeld van onze Patrones, de Moeder van alle Valencianen: de <strong>Virgen de los Desamparados</strong>, liefkozend in Valencia bekend als la Xeperudeta, wat in het Valenciaans «kleine gebochelde» betekent.</p>\n<p>De Maagd dankt deze naam aan haar lichte vooroverbuiging, wat wordt geïnterpreteerd als teken van lichamelijke slijtage door de inspanning en standvastigheid van de steun en hulp bij de duizenden gebeden die de Valencianen haar hebben gericht.</p>\n<p>De gebeden begonnen als gevolg van de pestepidemie die in 1647 bijna 18.000 slachtoffers maakte. De steeds vurigere devotie van het Valenciaanse volk voor de Maagd schiep de noodzaak een passende ruimte te bouwen zodat haar beeld voor het volk kon worden tentoongesteld in omstandigheden die bij die devotie passen.</p>",
  "452": `<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en dit historische monument op eigen tempo te bezoeken.</p>\n<p>U kunt de fresco's bewonderen van de beroemde schilder Palomino, die sinds 1701 in deze Basílica worden tentoongesteld.</p>\n<p>U kunt ook een paar woorden richten tot de Maagd. De traditie zegt dat men een wens mag doen die niet voor zichzelf bestemd is.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht; druk simpelweg op de bijbehorende knop en ga verder <i>op zoek naar de schat</i>.</p>`,
  "453": "<p>Bravo! Uw avontuur loopt bijna ten einde!</p>\n<p>Bekijk de kaart zorgvuldig; de indeling van de weg verplicht u één enkel traject te volgen en dan rechtsaf te slaan, en zo een prachtig uitzicht te krijgen op de <strong>Kathedraal van Valencia</strong>.</p>\n<p>Op weg naar de Romaanse Ingang bevindt zich aan uw linkerzijde het <strong>Palacio Arzobispal</strong>.</p>",
  "454": "<p>Aan de tegenovergestelde zijde van de Basílica onthult de ornamentatie van een herenhuis dat het belangrijk kan zijn in deze Schattenjacht.</p>",
  "455": "<p>Valencia is de Spaanse stad met het grootste aantal modernistische werken dankzij de belangrijke stadsgroei aan het einde van de 19e eeuw, die de aanleg van de uitbreidingswijk en de sloop van de middeleeuwse stadsmuren in 1865 met zich meebracht.</p>\n<p>Het modernisme was een breukbeweging met de stijlen van dat moment, met de bedoeling een modernere, jeugdige en functionele stijl te vinden gebaseerd op het gebruik van nieuwe materialen zoals ijzer, glas en tegels voortgekomen uit de industriële ontwikkeling.</p>\n<p>Het werd gekenmerkt door een zekere verheerlijking van de huerta, de falleras, de sinaasappels en de vissers, onder andere.</p>\n<p>Dit blijkt uit de werken vol kleurrijke mozaïeken, sculpturen en bloemversieringen.</p>\n<p>Deze beweging werd gestimuleerd door een nieuwe klasse: de burgerij, die zich via de kunst wilde doen gelden.</p>\n<p>Zij vluchtten weg van de traditie, van robuuste constructies; zij zochten beweging... en het fundamentele detail was de ornamentatie en de natuur.</p>\n<p>In Valencia ontwikkelde zich bovendien een stroming met eigen kenmerken, bekend als het Valenciaans Modernisme.</p>",
  "455-B": "<p>De modernistische gevel van het gebouw heeft gravures met floraal motieven en pilasters die boomstammen imiteren. Er zijn verschillende balkons te zien: sommige van steen en andere van smeedijzer.</p>",
  "455-C": "<p>In het onderste gedeelte bevindt zich de Capilla de San Valero; hier was de gevangenis waar bisschop Valero gevangen zat voordat hij in de 4e eeuw na Christus werd verbannen.</p>\n<p>Aanvankelijk gebouwd in 1719 en volledig herbouwd in 1907, opent ze zich naar buiten via een overluifelde deur in Barokke stijl met Toscaanse pilasters.</p>\n<p>In het bovendorpel van de deur is een oculus te zien, iets boven het beeld van de bisschop.</p>",
  "455-D": "<p>Kijkend naar het beeld van San Valero, welk voorwerp zou ons kunnen vertellen dat hij gevangen zat?</p>\n<p>De ketens, het boek of misschien zijn verdrietig gezicht?</p>",
  "456": "<p>In welk jaar werd dit gebouw opgericht?</p>\n<p>Tip! Kijk bovenaan de gevel.</p>",
  "457": "<p>Een kunstmatige hoogte, aan uw linkerhand van dit gebouw, nodigt uit om verder te gaan <i>op zoek naar de schat</i>.</p>\n<p>Naar boven!</p>\n<p>Dit is een perfect punt voor panoramische foto's van deze tot historisch-artistiek erfgoed verklaarde monumenten.</p>",
  "458": "<p>In de omgeving heeft zich een tijdpoort geopend!</p>\n<p>Wat is er doorheen te zien?</p>\n<p>Een <strong>Plaza de Toros</strong>, Romeinse Baden of misschien een Metrostation?</p>",
  "459": "<p>Precies! Romeinse Baden. Uw opdracht? Zoek de massagetafel. Het is waar, die staat er nog!</p>",
  "460": "<p>In de 13e eeuw, na de christelijke Reconquista, werd op dezelfde structuur het gebouw van de Almoina opgericht, dat zijn naam gaf aan de plek.</p>\n<p>Almoina (wat in het Valenciaans aalmoes betekent) was een middeleeuwse liefdadigheidsinstelling die voedsel uitdeelde aan de meest behoeftigen.</p>",
  "461": `<p>Zoals u kunt zien, maakt de architectonische structuur rondom het plein direct visueel contact met het interieur van het museum mogelijk, terwijl de buitenruimtes het dialoog bevorderen in een omgeving waar de overblijfselen van het verleden de echte hoofdpersonen zijn.</p>\n<p>Op dit punt bevindt zich een van de beste archeologische centra van Europa en zijn ruïnes te zien die teruggaan tot de stichting van de stad in het jaar 138 voor Christus.</p>\n<p>Dit plein wordt beschouwd als het oudste van de stad. In het verleden bevond zich hier het Romeinse hoofdplein dat grensde aan het forum; met andere woorden, de centrale zone van het oude Valentia.</p>\n<p>Als u er bent tijdens de openingsuren, raadt ${LOGO} u aan op pauze te drukken en deze ruimte binnen te gaan om de geschiedenis van de stad beter te leren kennen.</p>\n<p>U kunt uw avontuur hervatten zodra u dat geraden acht; druk simpelweg op de bijbehorende knop en ga verder <i>op zoek naar de schat</i>.</p>\n<p>Uw avontuur gaat verder op dit zelfde punt.</p>`,
  "462": "<p>Daartoe schonk hij het eigendom van alle moskeeën en islamitische begraafplaatsen aan het aartsbisdom, dat op zijn beurt deze tempels christianiseerde door ze te hernoemen als parochies gewijd aan heiligen van de nieuwe godsdienst die in deze landen zou worden ingevoerd.</p>\n<p>In 1245 werd de <strong>Iglesia de San Lorenzo</strong> gekozen als een van de tien stichtende parochies van de stad.</p>\n<p>Het kerkgebouw dat we vandaag kunnen zien dateert van 1684, hoewel de klokkentoren jaren later werd gebouwd, in 1747. Helaas verplaatste de aardbeving van 1822 hem van zijn oorspronkelijke as. Kunt u het zien?</p>\n<p>De bovenste ruimte herbergt twee klokken: Santa Anna, gemaakt in 1718, en Domingo, van 1742.</p>\n<p>De klokkentoren wordt bekroond door een kleine koepel met een opvallende windvaan waarop het beeld van San Lorenzo is te zien.</p>",
  "463": "<p>Stel u op, als u zo vriendelijk wilt zijn, in het midden van het plein met de markt voor u. Aan de rechterzijde van de beroemde <strong>Mercado central</strong> rijst een prachtige Barokke kerk op. Kunt u die zien? Op uw kaart correspondeert dit met nummer <mark>16</mark>.</p>\n<p>Nader uw volgende bestemming: San Juan del Mercado.</p>",
  "464": "<p>In het midden van het monument steekt de gotische <strong>Cimborrio</strong> uit.</p>\n<p>Sinds de 15e eeuw verheft hij zich op een hoogte van 40 meter, waarbij hij het natuurlijk licht doorlaat en de kathedraal verlicht.</p>\n<p>Kunt u de geometrie ervan bepalen? Zeshoekig, achthoekig of vierhoekig?</p>",
  "465": "<p>Volg de route op de kaart, draai om en laat de <strong>Basílica de la Virgen</strong> aan uw linkerzijde en het <strong>Museo Arqueológico</strong> aan uw rechterzijde, ga door tot het einde van de straat en sla linksaf.</p>\n<p>Onderweg ontvouwt zich de <strong>Plaza de la Virgen</strong>.</p>",
  "465-B": "<p>Volg uw schatkaart en loop door tot het einde van de straat, waar een plein bekend als de <strong>Plaza de la Virgen</strong> zich opent, een van de meest iconische van de stad.</p>\n<p>Op uw kaart staat dit aangegeven met nummer <mark>3</mark>.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "466": "<p>De <strong>Plaza de la Virgen</strong> is omgeven door de Basílica, de Kathedraal en de <strong>Barrio de la Seu</strong> of <strong>Barrio de la Catedral</strong>.</p>\n<p>In de noordelijke helft van het plein trekt een aantrekkelijke Monumentale Fontein uitgehouwen in brons bijzonder de aandacht.</p>\n<p>Bekend als de Neptunusfontein, is het de allegorische voorstelling van de <strong>Río Turia</strong>.</p>",
  "467": "<p>Neptunus houdt in zijn hand de hoorn des overvloeds en is omringd door vrouwenfiguren in de hoofdtooi van Valenciaanse boerinnen die de belangrijkste kanalen voorstellen die Valencia bevloeien.</p>\n<p>Met welke hand houdt Neptunus de hoorn des overvloeds vast?</p>",
  "468": "<p>Hoeveel figuren omringen de fontein?</p>",
  "469": "<p>Het plein dat zich voor u opent, is een van de meest geliefde plekken voor de Valencianen, vooral tijdens onze volksvieringen, de Fallas.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
