import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "650": "<p>Met de ingang van de tuinen achter u, neem het pad aan de linkerkant; na een paar meter begint het fietspad waarmee u de beroemde Puente del Real kunt oversteken.</p>",
  "651": "<p>Historisch gezien is er bewijs dat vanaf 1332 diverse loopbruggen of bruggen de Turia op deze plek overstaken, en ook dat de voortdurende overstromingen van de rivier ze telkens weer vernietigden.</p>\n\n<p>Deze brug heeft verschillende opmerkelijke bijzonderheden; de vier beeldhouwwerken die men kan zien zijn bijvoorbeeld niet degene die oorspronkelijk werden gekozen.</p>\n\n<p>In 1609 werd het schip dat ze vanuit Genua vervoerde aangevallen door piraten die de gehele lading buitmaakten.</p>",
  "652": "<p>Een andere anekdote, de meest beruchte, vond plaats in 1528.</p>\n\n<p>De brug, die nog van hout was, bezweek onder het gewicht van de honderden toeschouwers die zich verdrongen om keizer Karel I bij zijn bezoek aan Valencia voorbij te zien komen.</p>",
  "653": "<p>De brug die u vandaag kunt zien dateert uit 1598.</p>\n\n<p>Na de overstroming van 1590 werd besloten een stevigere basis te bouwen om de hevige aanvallen te weerstaan.</p>\n\n<p>In die tijd had de brug al tien bogen van elk dertien meter overspanning.</p>\n\n<p>Jaren later, in 1957, liep zij na een nieuwe overstroming opnieuw aanzienlijke schade op, en in 1966 werd de brug verbreed, waarmee de groeiende verkeersdruk in de stad werd verlicht.</p>",
  "654": "<p>Steek de brug over en u ziet een plein dat zich voor u opent.</p>\n\n<p>Gelegen in de wijk Xerea, een van de oudste van de stad, omvat de Plaza de Tetuán verschillende belangrijke gebouwen die het vermelden waard zijn.</p>\n\n<p>Vergeet niet op pauze te drukken, ga daarna naar het aangegeven punt en druk opnieuw op de knop doorgaan zodra u op de voorgestelde plek aankomt.</p>",
  "655": "<p>Uw doel is de kleine tuin die zich aan de overkant van het plein bevindt.</p>\n\n<p>Dit correspondeert met nummer <mark>79</mark> op uw kaart.</p>\n\n<p>Pauzeer deze audiogids niet en begeef u naar uw volgende interessante punt.</p>",
  "656": "<p>Op weg naar uw volgende doel ziet u aan uw linkerkant het oude Convento de Santo Domingo, een gotisch en barok gebouw dat teruggaat tot de stichting van de stad, want het was koning Jaime I zelf die in 1239 de eerste steen legde en waar tegenwoordig de resten van verschillende beroemde figuren van de stad rusten.</p>\n\n<p>Tegenover u, aan de rechterkant, verrijst een monumentaal gebouw van witte steen dat u verderop in dit Avontuur in detail zult zien.</p>\n\n<p>Vergeet niet op pauze te drukken, ga daarna naar het aangegeven punt en druk opnieuw op de knop doorgaan zodra u op de voorgestelde plek aankomt.</p>",
  "657": "<p>Het park waar u zich bevindt heeft zijn oorsprong in 1812. Bijgenaamd Parque de la Glorieta was het de eerste verlichte plek in de stad.</p>\n\n<p>Op 9 oktober 1844 werden verscheidene gaslantaarns symmetrisch verdeeld over de rotonde en de zijpaden geplaatst.</p>\n\n<p>Pas in 1852 werden de grote vijgebomen geplant die opvallen door hun monumentaliteit en grote wortels.</p>",
  "658": "<p>Tegenwoordig bevinden die enorme vijgebomen zich aan de andere kant van het park.</p>\n\n<p>Nader de bomen, als u zo vriendelijk wilt zijn, om hun majesteit te aanschouwen.</p>\n\n<p>Achter de bomenrij bevindt zich uw volgende interessante punt in dit avontuur.</p>",
  "659": "<p>Bewonder het Palacio de Justicia.</p>\n\n<p>De huidige benaming ervan is het Tribunal Superior de Justicia de la Comunidad Valenciana (Hoog Gerechtshof van de Valenciaanse Gemeenschap).</p>\n\n<p>Het indrukwekkende gebouw dat we vandaag zien dateert uit 1758, het laatste regeringsjaar van Karel III.</p>\n\n<p>Het gebouw beslaat een groot rechthoekig bouwblok; de gevels bestaan uit zichtbare bakstenen muren tussen stenen pilasters en rechte en gebogen balkons op de eerste verdieping.</p>\n\n<p>Daarboven toont de kroonlijst met balustraden, toorsdecoraties en lege nissen de barokke smaak.</p>\n\n<p>De bouw werd begonnen door de Valenciaanse academicus Felipe Rubio Mulet, maar hij overleed voordat hij het voltoid kon zien; het was zijn zwager die het werk in 1802 afmaakte.</p>\n\n<p>Aanvankelijk werd dit gebouw gebouwd als Douanekantoor.</p>\n\n<p>Het was de plek waar alle handel vanuit de zee werd gekanaliseerd en die Valencia tot een van de economische centra van de 18e eeuw maakte.</p>\n\n<p>Hoewel deze ruimte nog verder terug in de tijd gaat: oude kronieken uit 1626 vermelden al een eerste douanekantoor dat op deze zelfde plek was gevestigd, naast de stadsmuren en de oude stadspoort die de \"Puerta de la Mar\" werd genoemd.</p>",
  "660": "<p>Met het gebouw achter u, bekijk het traject op uw schatkaart dat aangeeft verder te gaan over het fietspad naar een imposant wit gebouw van modernere constructie dat aan uw linkerkant staat.</p>\n\n<p>Bekend in de volksmond als \"Centro Cultural Bancaja\": dit centrum bestaat uit twee gebouwen waarvan het interieur in de jaren tachtig werd geherstructureerd voor de huidige functie.</p>\n\n<p>Richt uw aandacht op het meest monumentale gebouw dat voorafgaat aan het witte.</p>",
  "661": "<p>Sinds de renovatie, samen met het aangrenzende gebouw, wordt het geheel gewijd aan culturele doeleinden en kantoren van de Instelling zelf.</p>\n\n<p>Gebouwd tussen 1932 en 1934 op de grond van een oud paleis in casticistische stijl met neo-barokke invloeden; het gebouw bestaat uit drie vleugels en een terras.</p>\n\n<p>De afgedekte toegangsdeur, die een afgeschuinde hoek vormt, is versierd met guirlandes van bloemen en vruchten die fijn in steen zijn uitgehouwen.</p>\n\n<p>De gevels zijn van steen aan de onderkant en bovenkant, terwijl in het middengedeelte rode terracotta overheerst; materialen die bestand zijn tegen de tand des tijds, zeer weinig onderhoud vergen en tevens goede geluidsisolerende eigenschappen hebben.</p>\n\n<p>In de jaren 1936 tot 1937, terwijl Valencia de hoofdstad was van de Spaanse Republiek, werd het gebouw gebruikt als Ministerie van Propaganda.</p>",
  "662": "<p>Op deze gevel hangt een klok. Hoe laat is het?</p>",
  "663": "<p>Het aangrenzende gebouw, dat zich kenmerkt door zijn witte kleur, is in zijn geheel te zien door de gevel te volgen om de hoek; begeef u naar dat punt om uw Avontuur voort te zetten.</p>",
  "664": `<p>Gebouwd in 1891 herbergt het de verschillende afdelingen van het Cultureel Centrum en de tentoonstellingen die het periodiek organiseert.</p>\n\n<p>Een dubbele monumentale toegang laat de bezoeker genieten van de tentoonstellingen van de stichting.</p>\n\n<p>Het gebouw wordt bekroond door een geëmailleerde koepel met blauwe schubben op elke hoek.</p>\n\n<p>Als u hier bent tijdens de openingstijden, raadt ${LOGO} u aan op pauze te drukken en dit cultureel centrum op uw eigen tempo te bezoeken.</p>\n\n<p>U kunt uw avontuur hervatten wanneer u dat wenselijk acht. Druk eenvoudigweg op de betreffende knop en ga verder <i>op zoek naar de schat</i>.</p>`,
  "665": "<p>Stel u, als u zo vriendelijk wilt zijn, op met het gebouw Fundación Bancaja voor u en neem de straat die aan uw rechterkant uitkomt.</p>\n\n<p>Aan het einde van de straat bevindt zich de Plaza de San Vicente Ferrer.</p>",
  "666": "<p>Tijdens Fallas hoor je de hele dag vuurwerk; als het lawaai u te luid lijkt, doe dan uw mond open en stop uw oren niet dicht, dat is erger.</p>",
  "667": "<p>Op het plein waar u zich bevindt, werd in 1853 een fontein opgericht. Dit is een van die 8 openbare fonteinen die destijds ontvangers waren van de pas aangelegde drinkwatervoorziening van de stad.</p>",
  "667-B": "<p>Op het plein waar u zich bevindt, werd in 1853 een fontein opgericht; een tijd waarin de openbare fonteinen de ontvangers waren van de pas aangelegde drinkwatervoorziening van de stad.</p>\n\n<p>De drinkwatervoorziening was nog niet algemeen beschikbaar in de woningen en men moest het ophalen bij de openbare fonteinen voor persoonlijk gebruik.</p>",
  "668": "<p>Wat houdt het beeld in zijn hand? Een schild, een harp, een kruik of misschien een zwaard?</p>",
  "669": "<p>Achter de fontein kunnen wij de Kerk van Sint Thomas en Sint Filippus Neri bewonderen.</p>\n\n<p>Dit tempel werd gebouwd tussen 1727 en 1736 in rode geschilderde baksteen.</p>\n\n<p>Het eerste niveau verrijst op een stenen sokkel die wordt gearticuleerd door acht grote pilasters.</p>\n\n<p>In het midden opent zich een afgedekte poort van steen.</p>\n\n<p>Boven de poort stellen twee vrouwenfiguren de Maagdelijkheid voor, versierd met de bloemen van de reinheid, en het Gebed.</p>\n\n<p>Daarom houdt zij het wierookvat van de goddelijke eredienst vast.</p>\n\n<p>Een hoog reliëf met de verschijning van de Maagd aan Sint Filippus Neri en het wapenschild van de Spaanse monarchie boven de deuropening zijn twee voorbeelden van hoog reliëf die dit tempel biedt.</p>\n\n<p>Ook opvallend is de vierkante klokkentoren met 45 meter hoogte en 106 treden. Deze kerk werd in 1982 verklaard tot Nationaal Historisch-Artistiek Monument.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
