import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "501": "<p>Cosa regge la figura con le mani? Uno scudo? È una conchiglia? Forse una brocca? O forse una spada?</p>",
  "502": "<p>Continui, come indica la sua mappa, di ritorno verso la <strong>Calle Caballeros</strong>, che corrisponde al numero <mark>45</mark> sulla sua mappa.</p>\n<p>Una volta in <strong>Calle Caballeros</strong>, prenda il sentiero che esce alla sua sinistra. Il suo prossimo obiettivo si apre a forma di piazza al termine della strada.</p>",
  "502-B": "<p>Continui, come indica la sua mappa, di ritorno verso la <strong>Calle Caballeros</strong>, che corrisponde al numero <mark>4</mark> sulla sua mappa.</p>\n<p>Una volta in <strong>Calle Caballeros</strong>, prenda il sentiero che esce alla sua sinistra. Il suo prossimo obiettivo si apre a forma di piazza al termine della strada.</p>",
  "503": "<p>È di nuovo tornato dove ha iniziato?</p>\n<p>Complimenti! Prova superata!</p>\n<p>Speriamo di tutto cuore che abbia goduto di questa avventura quanto noi abbiamo goduto nel progettarla per lei. Come avrà potuto constatare, la voce è stata generata con intelligenza artificiale per dare vita a ogni racconto e offrirle un'esperienza coinvolgente. Tuttavia, l'Anima e la sceneggiatura delle audioguide della saga <i>Alla ricerca del tesoro</i> sono frutto della partecipazione valenciana, riflettendo la sua passione, la sua essenza e la sua autenticità in ogni storia. Siamo lieti di aggiungere che questa fusione di tradizione e tecnologia è stata pensata per offrirle un'esperienza dinamica e vicina che speriamo sia stata di suo gradimento.</p>",
  "504": "<p>Nel corso della sua Avventura, concentri la sua attenzione sui battenti o picchiotti che si possono ancora vedere sulle porte di questi antichi palazzetti.</p>\n<p>Alcuni di questi antichi \"campanelli\" furono collocati a un'altezza sproporzionata per una persona di statura media.</p>",
  "505": "<p>Perché furono messi così in alto questi picchiotti?</p>\n<p>Per le persone alte? Potrebbe essere per suonare stando a cavallo? O forse per non essere disturbati?</p>",
  "506": "<p>Si diriga, al suo ritmo, fino al suo prossimo punto di interesse.</p>",
  "507": `<p>Ci congediamo, non senza prima ricordarle che disponiamo di ulteriori cacce al tesoro per continuare a giocare e scoprire Valencia. Al termine della sua avventura, ${LOGO} le raccomanda di alleggerire la capacità di archiviazione e ottimizzare le prestazioni del suo dispositivo eliminando i possibili file scaricati. In questo modo, contribuiamo anche a promuovere una gestione responsabile delle risorse digitali. Grazie.</p>`,
  "508": "<p>La <strong>Calle Caballeros</strong>, che ha appena lasciato, corrisponde all'asse est-ovest della città. Lo ricorda?</p>\n<p>Perfetto! Con questo riferimento alle sue spalle, la strada perpendicolare, per logica, corrisponderà a un asse nord-sud.</p>\n<p>Consulti la sua mappa e segua il tracciato che proponiamo in questa Avventura.</p>",
  "509": "<p>Che direzione prende il sentiero stabilito? Va verso nord? Sud? Si dirige a est? O forse a ovest?</p>",
  "510": "<p>Giusto! Nord. Questa via, come potrà vedere in seguito, si divide in due: Calle Alta e Calle Baja.</p>\n<p>La sua prossima destinazione percorre la famosa Calle Baja, ma prima parliamo brevemente della piazza in cui si trova.</p>\n<p>Torniamo all'epoca araba.</p>",
  "511": `<p>Tossal, che significa leggero rilievo del terreno, faceva parte della cinta muraria musulmana che chiudeva la città.</p>\n<p>Il muro svolgeva, a sua volta, la funzione di punto di contenimento dell'acqua di un ramo del <strong>Río Turia</strong> che, anticamente, passava da qui.</p>\n<p>Oggi restano esposti resti di quella muraglia in una galleria sotterranea visitabile che porta lo stesso nome della piazza e si trova sotto i suoi piedi.</p>\n<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e visitare questo complesso storico al suo ritmo.</p>\n<p>Può riprendere la sua avventura una volta lo riterrà opportuno.</p>`,
  "512": "<p>Si posizioni con la <strong>Calle Caballeros</strong> alle spalle e prenda il sentiero che esce alla sua mano destra.</p>\n<p>Come menzionato in precedenza, osserverà che la via si divide.</p>\n<p>Prenda la strada di destra e segua fino al suo prossimo punto di interesse che si trova in una di quelle strade strette che si apre alla sua destra.</p>",
  "513": "<p>Il <strong>Portal de la Valldigna</strong> fu costruito sulla stessa cinta muraria araba.</p>\n<p>Questo fu un accesso al <strong>barrio de la morería</strong> dal 1400, anno in cui la porta fu rimossa lasciando il portale così come si conserva oggi.</p>\n<p>L'arco a tutto sesto, costruito in conci di pietra, fu restaurato nel 1965.</p>\n<p>Al di sopra dell'arco si può vedere una riproduzione del retablo originale che fu collocato in questo stesso punto nell'anno 1589.</p>\n<p>Il retablo raffigura il re Giacomo Secondo d'Aragona, detto il Giusto, nell'atto della fondazione del Monastero della Valldigna, che letteralmente significa terre degne.</p>",
  "514": "<p>Se non le dispiace, attraversi il portale e si addentri nel quartiere arabo di Valencia.</p>\n<p>Prenda la prima strada alla sua sinistra. Al termine della strada si può ancora vedere una torre della cinta muraria araba, la cosiddetta porta dell'angelo.</p>",
  "515": "<p>Nell'XI secolo, dopo la caduta del Califfato di Cordova, l'Antico Impero si divise in piccole fazioni chiamate Taifas.</p>\n<p>Valencia, o Balansiya come era conosciuta ai tempi musulmani, fu la capitale di una di quelle Taifas. Di conseguenza, sperimentò un'importante crescita urbanistica.</p>\n<p>L'aumento della popolazione e i continui attacchi provenienti dal nord dell'Africa incentivarono la popolazione ad ampliare l'antica città e il suo perimetro difensivo.</p>\n<p>Il progetto della nuova muraglia avrebbe trasformato Valencia e stabilito un nuovo perimetro.</p>",
  "516": "<p>Questa fu costruita in calcestruzzo e riempita di pietre di diverse dimensioni.</p>\n<p>Le mura permisero agli abitanti di Balansiya di resistere al duro assedio da parte di Rodrigo Díaz de Vivar, più noto come El Cid Campeador, nell'anno 1094, sebbene non abbiano impedito la conquista.</p>\n<p>La città fu presa dai cristiani, e così rimase fino all'anno 1144, periodo in cui Valencia passò di nuovo nelle mani musulmane.</p>\n<p>In tutto questo tempo, una cosa non cambiò; le mura con le loro torri rimasero in piedi.</p>",
  "517": "<p>Persino dopo la reconquista cristiana, nel 1238 da parte di Giacomo Primo il Conquistatore, la cinta muraria araba non fu distrutta, ma rimase come misura di protezione per un secolo e mezzo.</p>\n<p>Questo perimetro, del quale rimangono resti visibili oggi, aveva 7 porte principali e torri strategicamente collocate ogni 25 metri.</p>\n<p>La torre che può vedere adesso è di pianta semicircolare ed è realizzata in muratura irregolare.</p>",
  "518": "<p>Cos'è la muratura irregolare? È una miscela di pietre e malta; un cemento tradizionale composto di calce, sabbia e acqua, al quale si poteva aggiungere anche fango e paglia per aumentarne la durezza.</p>\n<p>La muratura irregolare è un rozzo sistema di costruzione che permette di minimizzare gli sprechi dei materiali impiegati, ed è molto adatta per costruzioni di grandi altezze.</p>",
  "519": "<p>Quante Porte aveva l'antica cinta muraria araba di Balansiya? Erano 5? Forse 6? O forse 7?</p>",
  "520": "<p>La nuova città cristiana circondava quella araba con una cinta muraria di 4 chilometri di estensione e isolava i musulmani convertiti in un ghetto all'interno delle sue mura.</p>\n<p>I Mudéjares o come venivano denominati a Valencia, Sarraïns, erano musulmani che in cambio di un consistente tributo continuavano a vivere fedeli al loro credo.</p>\n<p>Va sottolineato che nella città di Valencia convissero le tre religioni abramitiche: la cristiana, l'araba e quella ebraica.</p>\n<p>Nonostante avessero credenze religiose diverse, era abituale la politica di accordi e i riconoscimenti in vista del progresso della città.</p>",
  "521": "<p>Osservi la sua mappa con attenzione! Il suo obiettivo è la nota <strong>Calle de los Serranos</strong>, luogo dove è iniziata la sua avventura. Non metta in pausa questa audioguida.</p>\n<p>Si posizioni ammirando la torre mora e prenda la strada di destra, per poi girare immediatamente a sinistra e poi a destra.</p>\n<p>Il percorso sembra un po' tortuoso, lo sappiamo, ma questo ha una spiegazione.</p>",
  "522": "<p>La planimetria delle città islamiche è molto complessa, quasi non c'è distinzione tra strade principali e secondarie.</p>\n<p>Il loro modo di creare il tracciato urbano è: prima le case e poi le strade, al contrario del sistema romano che faceva prima le strade e poi le case.</p>\n<p>Pertanto, il tessuto irregolare è formato dalle case che si ampliano e invadono le strade adiacenti modificando il loro tracciato, chiudendo persino strade e creando vicoli ciechi.</p>",
  "523": "<p>Una volta nella <strong>Calle de los Serranos</strong>, si diriga alle torri dove è iniziata la sua Avventura.</p>\n<p>Durante il percorso, osservi alla sua sinistra e presti attenzione poiché l'edificio è molto discreto e potrebbe passare inosservato.</p>\n<p>L'antico bunker di Valencia corrisponde al numero <mark>52</mark> sulla sua mappa.</p>\n<p>Prema pausa, poi vada o visualizzi il punto indicato e prema di nuovo il tasto continua una volta nel luogo suggerito. Grazie.</p>",
  "524": "<p>Questo monumento, oggi visitabile, fu uno dei primi rifugi civili costruiti durante il periodo della guerra civile spagnola, avvenuta dal 1936 al 1939.</p>\n<p>A causa dell'evoluzione militare, i rifugi antiaerei erano essenziali per mantenere al sicuro la popolazione dagli attacchi e dai bombardamenti del nemico.</p>\n<p>Questo, in particolare, fu costruito nel 1937, anno in cui Valencia fu capitale della repubblica spagnola.</p>\n<p>L'antico bunker di guerra poteva ospitare circa 400 persone al suo interno.</p>\n<p>In questo spazio che salvaguardò la vita di molti valenciani, oggi si trova un museo che ci permette di vedere una grande raccolta di manufatti dell'epoca, oltre allo sviluppo attraverso fotografie che mostrano com'era la vita quotidiana tra bombardamenti e miseria.</p>\n<p>Tutti questi dati storici e manoscritti mostrano come sarebbe rimasta Valencia dopo la perdita di migliaia di vite umane e la distruzione di parte dei suoi monumenti storici al termine della Guerra Civile.</p>",
  "525": `<p>Consulti la sua mappa e osserverà che le indica di prendere il terzo sentiero che esce alla sua sinistra.</p>\n<p>Solo alcuni metri in quella strada emerge il suo prossimo punto di interesse in questa caccia al tesoro. Sulla sua mappa corrisponde al numero <mark>53</mark>.</p>\n<p>${LOGO} le raccomanda di raggiungere il prossimo punto di interesse a piedi, ricordi che deve rispettare il codice della strada che, in questo caso, dà precedenza al pedone. Coraggio, sono solo pochi metri!</p>\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato, grazie.</p>\n<p>Ricordi, continui verso le torri e prenda il terzo sentiero che esce alla sua sinistra.</p>`,
  "525-B": `<p>Dalla sua posizione, si giri e lasci le torri alle sue spalle. Con le torri alle spalle, osservi la sua mappa, che le indica di prendere il sentiero che esce alla sua destra.</p>\n<p>Solo alcuni metri in quella strada emerge il suo prossimo punto di interesse in questa caccia al tesoro. Sulla sua mappa corrisponde al numero <mark>2</mark>.</p>\n<p>${LOGO} le raccomanda di raggiungere il prossimo punto di interesse a piedi, ricordi che deve rispettare il codice della strada che, in questo caso, dà precedenza al pedone.</p>\n<p>Coraggio, sono solo pochi metri!</p>\n<p>Non metta in pausa questa audioguida e si diriga al punto indicato, grazie.</p>`,
  "526": `<p>Il riciclo è una pratica essenziale e dobbiamo estenderne la rilevanza al campo virtuale. Adottando questo approccio intelligente, possiamo contribuire a una gestione sostenibile degli asset nel cloud, aprendo la strada a un'impronta digitale più leggera e sostenibile. Da ${LOGO} la ringraziamo per aver acquistato questa Avventura e la aspettiamo presto per altri divertimenti!</p>`,
  "527": "<p>Il Corpus Christi è la festa cattolica per celebrare l'Eucaristia; in essa si celebra il sacramento del pane e del vino e si dedica un ricordo speciale alla morte e alla resurrezione di Gesù.</p>\n<p>Il suo principale scopo è proclamare e rafforzare la fede dei credenti.</p>\n<p>Al di là del puro senso cattolico, per la società valenciana il Corpus Christi è una manifestazione della coesistenza dello spirito festoso e religioso.</p>\n<p>La città rende culto 60 giorni dopo la Domenica di Risurrezione nella cosiddetta Fiesta Grande.</p>",
  "528": "<p>Le strade si adornano con corridoi floreali e diverse compagnie eseguono vistose danze tradizionali e allegoriche al suono della Dolçaina i el Tabalet, strumenti tradizionali valenciani che fanno parte della colonna sonora delle nostre audioguide.</p>\n<p>La danza più famosa è la lotta nella quale la Moma, la nostra attrice principale, si scontra contro i sette peccati capitali.</p>\n<p>Si riconosce per la sua tunica bianca e un fazzoletto bianco che le copre completamente il viso.</p>",
  "529": "<p>Sono anche importanti in questa celebrazione i sette Momos, vestiti con maschera nera, abito giallo e nero e un cappello caratteristico che rappresenta un drago.</p>\n<p>Questi eseguono un pittoresco Ballo di Bastoni mentre si sottomettono alle virtù della Moma.</p>\n<p>In alcune località lanciano acqua dai balconi e invitano gli spettatori a partecipare alla celebrazione.</p>",
  "530": "<p>Il Museo delle Rocas custodisce le storiche Rocas del Corpus Christi: sono i carri trionfali che rappresentano temi biblici che, trainati da cavalli, ogni anno spiccano nella processione.</p>\n<p>Da questo museo inizia la processione degli undici carri trionfali datati tra il 1528 e il 2001.</p>\n<p>Le undici strutture in legno, a forma di antica nave, trasportano gruppi scultorei allegorici ai Santi della religione stessa.</p>",
  "531": "<p>All'interno dell'edificio, oltre alle magnifiche strutture in legno, si possono anche vedere i costumi della Moma e dei Momos menzionati in precedenza, e anche quello dei Giganti e Teste Grosse che danzano attorno durante la festa.</p>\n<p>Questo punto che acquisì la categoria di Museo nel 2017 raccoglie anche una collezione di fotografie del Corpus dal XIX secolo.</p>",
  "532": "<p>La Casa de las Rocas fu costruita tra il 1435 e il 1447 per ordine del re Pietro Quarto, detto il Cerimonioso.</p>\n<p>Per la sua vicinanza al fiume, ha subito numerose inondazioni causate da ogni esondazione; il che comportò il continuo deterioramento della casa.</p>\n<p>Fortunatamente, la situazione si risolse dopo la deviazione del fiume che diede luogo al bellissimo parco che continueremo a osservare in questa Avventura.</p>\n<p>Questa antica casa a due piani era, inoltre, la residenza del Cappellano delle Rocas, che si occupava della loro custodia.</p>\n<p>Si accede alla casa da un'alta porta architravata, nella cui parte superiore troviamo un frontone triangolare. All'interno troviamo un cortile interno coperto da un soffitto a travi di legno.</p>\n<p>Dopo il restauro del 1980, al piano superiore fu aggiunto un grande balcone affacciato sul cortile interno.</p>\n<p>Anni dopo, dopo la meritissima riforma museografica, furono aggiunti pannelli esplicativi, schermi audiovisivi e la suddivisione e denominazione delle diverse sale.</p>",
  "533": "<p>Osservi che la sua mappa le indica di continuare per la strada; durante il percorso può osservare che i balconi del primo piano sono notevolmente più stretti di quelli degli altri piani superiori. Perché? Inoltre, alcuni di essi sono ancora decorati con ceramica tradizionale valenciana.</p>\n<p>Il suo prossimo punto di interesse è il portale di una chiesa barocca che si trova alla sua destra nella stessa strada.</p>",
  "534": "<p>La iglesia de Nuestra Señora del Carmen, la <strong>Parroquia de la Santísima Cruz</strong>, nota popolarmente come la \"Iglesia del Carmen\", fu dichiarata Monumento Storico Artistico Nazionale nel 1983.</p>\n<p>Ma questa chiesa ha un passato molto più antico.</p>",
  "535": "<p>La chiesa del Carmen ebbe le sue origini nell'anno 1280. A quei tempi in questo spazio si trovava una modesta casa con orto gestita dall'Ordine dei Carmelitani. Questo sarebbe stato l'origine del futuro Convento del Carmen.</p>\n<p>Dopo una prima espansione, la prima chiesa fu consacrata nel 1343 e da allora ha subito riforme graduali.</p>\n<p>Un chiostro gotico con archi a sesto acuto, il grande refettorio o sala da pranzo dei frati e la sala capitolare sono chiari esempi che rimangono del suo passato medievale.</p>\n<p>Nel 1555 fu riformata la testa, o zona dell'altare, utilizzando il sistema costruttivo tradizionale della volta a crociera stellata.</p>\n<p>Più tardi fu costruito un secondo chiostro rinascimentale, ma gli elementi più visibili appartengono già all'epoca barocca.</p>\n<p>Nel 1613 iniziarono i lavori della facciata-retablo del tempio e nel 1628 fu effettuata una nuova riforma che durò quasi 30 anni nella quale l'interno fu rinnovato al gusto barocco dell'epoca (1655).</p>\n<p>Concentri la sua attenzione sulla facciata principale.</p>\n<p>Questa stravagante facciata è considerata uno dei migliori retabli manieristi della città.</p>",
  "536": "<p>Il Manierismo è uno stile artistico impiegato alla fine del XVI secolo che si concentrava sull'alterazione dell'ordine negli elementi architettonici, tendendo all'irrealtà.</p>\n<p>Il retablo della facciata che ha davanti fu realizzato in due fasi.</p>\n<p>La prima, di taglio classico, corrisponde al corpo inferiore e fu realizzata nella prima metà del XVII secolo.</p>\n<p>Osservi le colonne ioniche scanalate che si elevano sui basamenti di pietra ai lati della porta.</p>",
  "537": "<p>La porta, a sua volta, ha un'edicola per lato dove si trovano le sculture rappresentative di San Simone Stock, un eremita e frate Carmelitano inglese; e di San Giovanni della Croce, Patrono dei poeti in lingua spagnola e uno dei 36 Dottori della Chiesa.</p>",
  "538": "<p>Sopra l'architrave della porta spicca lo scudo dell'Ordine del Carmelo.</p>\n<p>Cosa corona lo scudo? Una corona? Una croce? O forse una stella?</p>",
  "539": "<p>La seconda fase che corrisponde ai due corpi superiori, molto più ornati rispetto al corpo inferiore, fu costruita nel XVIII secolo.</p>\n<p>Osservi che nel secondo corpo si aprono tre edicole con tre figure femminili, queste rappresentano Santa Teresa di Gesù, una delle monache fondatrici dell'Ordine delle Carmelitane Scalze, e Santa Maddalena de' Pazzi, una nobile toscana e monaca Carmelitana.</p>",
  "540": "<p>La terza edicola, la più ornamentata, ospita la Vergine del Carmen, che dà il nome a questo tempio.</p>\n<p>Cosa porta la Vergine in braccio? Un cuore? Una Colomba? O forse porta il Bambino Gesù?</p>",
  "541": "<p>Più in alto, nel terzo corpo, si apre un'apertura affiancata da due colonne salomoniche.</p>\n<p>Le colonne ricevono questo nome per la credenza dell'epoca che così fossero le colonne del Tempio di Salomone.</p>\n<p>La scultura corrisponde a San Giuseppe con il bambino in braccio, così come le tre sculture di sotto è datata al XVIII secolo.</p>",
  "542": "<p>La sua avventura continua qualche metro più avanti nella stessa strada, per cui continuiamo a raccomandare di raggiungere il prossimo punto di interesse a piedi.</p>\n<p>Si prega di non fermare questa audioguida e di dirigersi al suo prossimo obiettivo.</p>",
  "543": "<p>Il Convento del Carmen ha le sue origini nel 1281, dopo la morte del re Giacomo Primo, quando i Carmelitani Calzati si stabilirono a Valencia.</p>",
  "544": "<p>Promossi da Fra Arnaldo de Bascher, i carmelitani si insediarono nel <strong>Barrio de Roteros</strong>, che all'epoca si trovava fuori dalle mura dell'antica cinta muraria araba della città.</p>",
  "544-B": "<p>Promossi da Fra Arnaldo de Bascher, i carmelitani si insediarono nel <strong>Barrio de Roteros</strong>, che all'epoca si trovava fuori dalle mura dell'antica cinta muraria araba di cui si parla più in dettaglio nella nostra Avventura numero 2.</p>",
  "545": "<p>Se concentra la sua attenzione sulla facciata, può ancora vedere un pannello in ceramica che risale al 1779 e nel quale è rappresentata Santa Teresa di Gesù.</p>\n<p>Come può constatare, la Santa indossa l'abito dell'Ordine del Carmelo.</p>\n<p>Ma questa Santa non porta corona; al suo posto si copre con un berretto dato che è Dottora della Chiesa.</p>",
  "546": "<p>Cosa porta Santa Teresa nelle mani? Una Penna e un libro? Forse una spada? O forse una brocca d'acqua?</p>",
  "547": "<p>L'antico convento, oggi visitabile, prese il nome di Real Monasterio de la Madre de Dios del Carmen. Si articola attorno a due chiostri: il più antico in stile gotico dei secoli XIV e XV e il secondo, di epoca rinascimentale, dei secoli XVI e XVII.</p>\n<p>All'interno del chiostro gotico si elevano su ciascuno dei suoi lati quattro archi a sesto acuto coperti con volta a crociera.</p>\n<p>Come dettaglio aggiungeremo che, se concentra la sua attenzione alla fine degli archi, nella mensola delle colonne, vedrà dettagli scolpiti nella pietra, come scudi araldici sorretti da angeli e animali mostruosi.</p>\n<p>All'interno del chiostro, a destra, si può ancora vedere dipinto sulla parete il costo del rinnovo del chiostro del 1670; periodo nel quale furono eliminati i confessionali.</p>",
  "548": "<p>Nel 1839, il convento cessò di esercitare come tale. A partire dal 1848, si insediarono le sedi della Scuola di Belle Arti e della Scuola di Arti e Mestieri Artistici.</p>\n<p>Lo spazio, a sua volta, serviva anche da magazzino e sala espositiva di vari artisti dell'epoca. Quelle opere crearono la prima sede del <strong>Museo di Belle Arti</strong> di Valencia.</p>\n<p>L'edificio fu dichiarato Storico Artistico Nazionale nel 1983. Nel 1989 iniziò un restauro nel quale si sarebbe potuto adattare lo spazio per ospitare una sala di esposizioni temporanee dipendente dal <strong>Museo di Belle Arti</strong>, ma quei lavori si prolungarono per più di 10 anni; concretamente fino all'anno 2011.</p>",
  "549": `<p>Durante i lavori di restauro emergono numerosi resti archeologici nel sottosuolo del convento.</p>\n<p>Uno dei più significativi sono i resti di un'abitazione islamica, visibile grazie a un pannello di vetro che permette di vedere questo tesoro che ci offre la storia della città.</p>\n<p>Se si trova in orario di visita, ${LOGO} le consiglia di premere pausa e godersi questa sala espositiva.</p>`,
  "550": "<p>Quanto costa il biglietto di questo museo?</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
