import { readFileSync, writeFileSync } from 'fs';

const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-portugues.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";

const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);

let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) { /* archivo nuevo */ }

const batch = {
  "259": "<p>Saberia dizer-me o preço para aceder a esta atração? Poderia ser grátis...</p>",
  "260": `<p>Se se encontrar em horas de visita, ${LOGO} aconselha-lhe que prima a pausa e desfrute dos seus enormes tobogãs!</p>\n<p>Este é um ponto perfeito para tirar uma fotografia magnífica deste tesouro que Valencia nos oferece.</p>\n<p>Utilize o botão de pausa a seu próprio gosto, quando sentir que é o momento, simplesmente continue e resolva os nossos desafios enquanto descobre a cidade.</p>`,
  "261": "<p>A sua aventura continua numa zona recreativa com pistas de patinagem e parques infantis, que se situa uns metros mais adiante, seguindo o antigo leito.</p>",
  "262": `<p>Damos-lhe as boas-vindas à <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Preste especial atenção ao seu mapa, este magnífico complexo é composto por seis grandes elementos.</p>`,
  "263": `<p>Esta praça, de planta triangular, recebe o nome de <strong>Plaza del Ayuntamiento</strong> desde 1987.</p>\n<p>Um ambiente urbano que sofreu diferentes reformas, entre elas a demolição do Convento de São Francisco em 1891, que permitiu uma passagem direta entre dois bairros comerciais da cidade.</p>\n<p>Também na própria praça foi instaurado o mercado das flores, que desde 1924 até aos nossos dias, anima e enriquece a cidade.</p>\n<p>Em Valencia há uma grande quantidade de fontes que refrescam o ambiente que as rodeia. A fonte que podemos ver hoje em dia foi construída por Carlos Buigues e inaugurada em março de 1962.</p>`,
  "264": `<p>Desenhada por Santiago Calatrava e Félix Candela, a <strong>Ciudad de las Artes y de las Ciencias</strong> é um conjunto único de vanguarda arquitetónica a nível mundial dedicado à divulgação científica e cultural.</p>\n<p>As cores azuis e brancas e as suas audazes linhas identificam a capital do Turia do séc. XXI.</p>\n<p>A <strong>Ciudad de las Artes y de las Ciencias</strong> é a imagem futurista que simboliza a nova Valencia; uma cidade moderna dentro da cidade milenar, onde milhões de visitantes acorrem cada ano para desfrutar da sua cultura, da sua natureza, da sua arte e da sua ciência.</p>`,
  "265": "<p>Para que a sua aventura resulte mais simples e agradável, organizámos os elementos a visitar em duas fases. Desta forma, poderão explorá-los com calma, sem pressa, e desfrutar de cada momento ao máximo. Cada fase foi pensada para lhes oferecer uma experiência mais completa e organizada, permitindo-lhes aproveitar ao máximo tudo o que têm para oferecer, enquanto desfrutam de cada instante do seu percurso.</p>",
  "266": `<p>O primeiro: oferece uma vista panorâmica da <strong>Ciudad de las Artes y de las Ciencias</strong>, bordeando pelo lado esquerdo do Jardín del Turia, cruzando o Puente l'Assut de l'Or e subindo depois ao miradouro que oferece <strong>l'Umbracle</strong>.</p>`,
  "267": `<p>O segundo: começa em cima; no próprio miradouro, continuando até ao final e descendo pelo acesso que o Palácio das Artes Reina Sofía tem na sua parte frontal.</p>\n<p>Está pronto? A desfrutar porque é uma maravilha!</p>`,
  "268": `<p>Tomando como referência o lado esquerdo do jardim, adentre-se numa ciclovia que percorre entre plantas aromáticas e medicinais.</p>\n<p>Alecrim, tomilho e lavanda misturam as suas fragrâncias numa paisagem de oliveiras e antigas ruínas.</p>\n<p>Este caminho, com os seus numerosos miradouros, oferece uma panorâmica excecional da <strong>Ciudad de las Artes y de las Ciencias</strong> que se destacará notavelmente ao fundo à direita no ambiente verde e ajardinado em que se encontra.</p>`,
  "269": "<p>Adentre-se no caminho e escolha um miradouro a partir do qual se possa ver o complexo inteiro.</p>",
  "270": "<p>Começaremos pelo maravilhoso Palácio das Artes Reina Sofía. Vê-o? É todo branco e sobressai o seu telhado em voo.</p>",
  "271": `<p>Foi inaugurado em 2005 e dedica-se à programação operística, tem capacidade para 3.500 assistentes.</p>\n<p>Os seus Intendentes e Diretoras artísticas conseguiram colocar este centro lírico entre os melhores e mais reputados da cena internacional.</p>\n<p>Pelas suas 4 salas passaram artistas tão importantes como Plácido Domingo e Luciano Pavarotti.</p>`,
  "272": "<p>Centre a sua atenção no Museo Príncipe Felipe.</p>",
  "273": `<p>Pode vê-lo? Tem mais de 5.000 janelas!</p>\n<p>Como poderá comprovar, os valencianos gostam do sol e por isso muitos dos seus edifícios têm grandes envidraçados, permitindo assim uma poupança de consumo energético usando uma fonte de luz e calor natural e ecológica.</p>`,
  "274": `<p>Se se encontrar em horas de visita, ${LOGO} incita-o a pausar e entrar a descobrir a gastronomia local que este maravilhoso espaço oferece.</p>\n<p>Pode retomar a sua aventura uma vez o entender conveniente.</p>`,
  "274-B": `<p>Se se encontrar em horas de visita, ${LOGO} incita-o a pausar e entrar a descobrir a gastronomia local que este maravilhoso espaço oferece. Pode retomar a sua aventura uma vez o entender conveniente. A sua Aventura continua na porta oposta à que se encontra neste momento.</p>`,
  "274-C": `<p>Se se encontrar em horas de visita, ${LOGO} recomenda-lhe que prima a pausa e entre neste monumento para conhecer melhor a história da cidade e os seus costumes.</p>\n<p>A entrada principal está situada na parte oposta do monumento.</p>\n<p>Este é um ponto perfeito para tirar uma fotografia magnífica deste tesouro que Valencia nos oferece.</p>`,
  "275": `<p>O Museo Príncipe Felipe foi inaugurado no ano 2000 com um total de 26.000 metros quadrados de exposições temporárias e permanentes.</p>\n<p>Este espaço, que sob o lema "Proibido não tocar, não sentir e não pensar", é um inovador centro de ciência interativa.</p>\n<p>A sua vocação é fomentar o interesse pelo conhecimento científico e tecnológico através da diversão e do entretenimento.</p>\n<p>Com este objetivo, concede-se grande importância à interatividade das exposições.</p>\n<p>É, além disso, sede de diferentes eventos sociais e culturais da cidade.</p>`,
  "276": `<p>Continue <i>à procura do tesouro</i> por este caminho pavimentado que o leva diretamente ao seu próximo objetivo, a Puente l'Assut de l'Or.</p>`,
  "277": `<p>O nome desta ponte compõe-se de duas palavras: Azud, que em árabe significa barreira ou presa, e Or que em Valenciano é Ouro.</p>\n<p>Assim, l'Assut de l'Or significa presa dourada.</p>\n<p>Embora esta ponte seja também conhecida pelo seu apelido "a ponte da harpa".</p>`,
  "278": `<p>A Puente l'Assut de l'Or mantém-se de pé graças a 29 cabos que saem da parte dianteira do seu mastro de 125 metros de altura.</p>\n<p>O tabuleiro da ponte tem 180 metros de comprimento por 34 metros de largura.</p>\n<p>Foi completamente terminada em dezembro de 2008 e é uma das pontes mais altas de Espanha.</p>`,
  "279": `<p>Esta aventura leva-o a atravessar a ponte que oferece umas vistas magníficas para a <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Enquanto atravessa a ponte preste especial atenção à sua esquerda onde sobressai o Ágora.</p>\n<p>Número <mark>16</mark> no seu mapa.</p>\n<p>Mesmo atrás, situa-se o conhecido Oceanogràfic.</p>\n<p>Que corresponde ao número <mark>17</mark> no seu mapa.</p>\n<p>Uma vez atravessada a ponte, situe-se, como indica o seu mapa, numa zona segura que oferece umas vistas magníficas desta área. Esta zona segura que sugerimos, está à esquerda, conforme se desce da ponte.</p>\n<p>Prima a pausa, depois visualize o ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "280": `<p>Continue até ao final da rua onde cruza a <strong>Calle Caballeros</strong> que corresponde no seu mapa ao número <mark>20</mark>.</p>\n<p>Uma vez aí, vire à mão direita e verá o emblemático edifício do <strong>Palau de la Generalitat</strong> que no seu mapa corresponde ao número <mark>21</mark>.</p>\n<p>Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "281": "<p>O substantivo Ágora vem do grego e significa Praça pública da vida social.</p>",
  "282": `<p>Este espaço provisoriamente finalizado em 2009, é uma estrutura metálica de planta semelhante a uma elipse apontada.</p>\n<p>O Ágora mede uns 88 metros de comprimento por 66 de largura e 80 de altura, é uma grande praça coberta que dota o complexo de um espaço multifuncional.</p>\n<p>Este monumento está concebido como um cenário projetado para a celebração de congressos, convenções, concertos ou representações com a possibilidade de se transformar em zona para exposições.</p>\n<p>A sua área coberta é de aproximadamente uns 5.000 metros quadrados.</p>\n<p>A sua forma recorda, segundo o próprio Calatrava, duas mãos entrelaçadas, pois o Ágora terá na sua parte superior umas asas a simular dedos que permitirão filtrar a quantidade de luz que entrará no seu interior.</p>\n<p>Este grande espaço interior concebe-se como uma praça pública coberta, de planta diáfana, ao nível dos tanques e passeios adjacentes.</p>\n<p>O edifício está rodeado por dois lagos que servem de complemento ao espaço interior.</p>\n<p>Em novembro de 2009, ano da sua inauguração, celebrou-se no seu interior o Open 500 de ténis da Comunitat Valenciana.</p>`,
  "283": `<p>Centre a sua atenção no complexo que fica atrás do Ágora.</p>\n<p>A este espaço conhece-se como O Oceanogràfic.</p>`,
  "284": `<p>Com uma extensão de 110.000 metros quadrados e um volume de água equivalente a 15 piscinas olímpicas, o visitante poderá observar tubarões, Belugas, morsas, golfinhos, leões marinhos, pinguins, estrelas e ouriços do mar.</p>\n<p>Uma grande variedade de crustáceos e peixes, assim como aves típicas provenientes da <strong>Albufera</strong> de Valencia, uma das zonas húmidas mais grandes de Espanha situada a uns 12 quilómetros a sul da cidade.</p>\n<p>Inaugurado em 2002 é um dos maiores aquários da Europa. Nele representam-se os principais ecossistemas marinhos do planeta: Mediterrâneo, Zonas Húmidas, Mares Temperados e Tropicais, Oceanos Antártico, Ártico, Ilhas e Mar Vermelho.</p>`,
  "285": `<p>Continuemos com a Procura do Tesouro!</p>\n<p>Com o Ágora e o Oceanogràfic às suas costas, procure uma construção arbórea que ficará à sua frente do outro lado da estrada. Pode vê-la?</p>`,
  "286": `<p><strong>l'Umbracle</strong>: é um miradouro ajardinado no qual se encontra o conhecido Passeio das Esculturas.</p>\n<p>Destaca nesta zona o seu jardim central arborizado com flora autóctone do Mediterrâneo.</p>\n<p>O pavimento deste jardim é de madeira de teca pela sua durabilidade natural em condições climáticas extremas.</p>\n<p>Por baixo deste passeio encontra-se o parque de estacionamento do complexo com capacidade para 20 autocarros e 650 veículos.</p>`,
  "287": `<p>Desde este ponto começa o segundo cenário que lhe propomos.</p>\n<p>A sua aventura continua tranquilamente até ao final do passeio, de volta a Reina Sofía.</p>\n<p>Reina Sofía corresponde ao número <mark>12</mark> no seu mapa.</p>\n<p>Situe-se olhando para o monumento e procure o acesso que desce na sua parte frontal obtendo assim uma visão mais próxima da <strong>Ciudad de las Artes y de las Ciencias</strong>. Uma vez em baixo, emerge l'Hemisfèric.</p>\n<p>l'Hemisfèric corresponde no seu mapa ao número <mark>19</mark>.</p>`,
  "287-B": `<p>Desde este ponto começa o segundo cenário que lhe propomos.</p>\n<p>A sua aventura continua tranquilamente até ao final do passeio, de volta a Reina Sofía que corresponde ao número <mark>18</mark> no seu mapa.</p>\n<p>Situe-se olhando para o monumento e procure o acesso que desce na sua parte frontal obtendo assim uma visão mais próxima da <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Uma vez em baixo, emerge l'Hemisfèric que no seu mapa corresponde ao número <mark>25</mark>.</p>`,
  "288": `<p>Dirija-se ao emblemático <strong>Palau de la Generalitat</strong> que no seu mapa corresponde ao número <mark>21</mark> e é a última paragem nesta aventura.</p>`,
  "289": "<p>Despedimo-nos, não sem antes desejar-lhes umas boas Fallas e aconselhar que não percam os castelos de Fogos de Artifício que se disparam de 15 a 19 de março.</p>",
  "290": `<p>Este é um ponto perfeito para tirar umas fotos magníficas da <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Vemo-nos em baixo! Prima a pausa, depois vá ao ponto indicado e prima de novo o botão continuar uma vez no local sugerido.</p>`,
  "291": `<p>l'Hemisfèric foi o primeiro edifício que abriu as suas portas ao público na <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Inaugurado em 1998 e com capacidade para 300 pessoas, este espaço dedica-se ao cinema IMAX em 3 Dimensões.</p>\n<p>Arquitetonicamente falando, o monumento destaca pela originalidade das suas comportas que, graças a um mecanismo especial, se abrem e fecham como se de um olho real se tratasse.</p>\n<p>${LOGO} incita-o a premir a pausa e a desfrutar ao seu gosto por este complexo futurístico com linhas inovadoras num ambiente de inspiração milenar.</p>\n<p>Fica da nossa parte aportar certos detalhes que enriquecem a nossa visão da <strong>Ciudad de las Artes y de las Ciencias</strong>.</p>\n<p>Note que a decoração do complexo é um mosaico de cerâmica valenciana, legado árabe durante o seu período de colonização; de novo voltamos à cultura árabe quando admiramos os enormes espaços repletos de água que magnificam e engrandecem os monumentos que rodeia.</p>\n<p>Uma vez que decida continuar, simplesmente prima o botão correspondente e continue <i>à procura do tesouro</i>.</p>\n<p>O ambiente da <strong>Ciudad de las Artes y de las Ciencias</strong> é perfeito para gozar do sol de Valencia e desfrutar de uma Orxata tradicional valenciana.</p>`,
  "292": `<p>Enquanto desfruta do seu próprio tempo, tente resolver estes desafios:</p>\n<p>De quantos monumentos se compõe a <strong>Ciudad de las Artes y de las Ciencias</strong>?</p>\n<p>De que é feita a Orxata? De chufa, de arroz ou de cevada?</p>`,
  "293": `<p>A sua aventura continuará na Puente de la Mar.</p>\n<p>A ponte pedonal do séc. XVI, que já conheceu nesta aventura.</p>`,
  "294": `<p>Devido aos danos que produziram as diversas cheias do <strong>Rio Turia</strong> sobre a estrutura da Puente de la Mar, que nessa época era de madeira, obrigaram em 1425 a iniciar a construção de uma estrutura mais robusta, também de madeira, mas outra cheia em 1589 destruiu-a totalmente.</p>\n<p>Em 1591, Francesc Figueroa encarregou-se da sua reconstrução em pedra. As obras concluíram em 1596.</p>\n<p>Nessa época, contava já com dez arcos apontados abobadados e uma pequena construção que protegia a Cruz da Ponte.</p>`,
  "295": "<p>O que rodeia a base da ponte? Água, erva ou patos?</p>",
  "296": "<p>Parabéns! Recolheu todas as pistas e resolveu os enigmas que o antigo leito lhe propunha... Até agora, mas esta Aventura não termina aqui!! Como poderá comprovar, o mapa do tesouro leva-o de novo à cidade. Vamos a isso?</p>",
  "296-B": `<p>Desde este ponto o traçado desta aventura continua por circuito urbano!</p>\n\n<p>Siga com cuidado, lembre-se de que se deve respeitar a regulamentação de trânsito.</p>\n\n<p>Veja as indicações que o seu mapa do tesouro oferece e continue pelo carril adaptado <i>à procura do tesouro</i>.</p>\n\n<p>Pelo lado esquerdo do jardim, um acesso permite-lhe subir e atravessar esta obra adornada com 27.500 flores multicolores.</p>`,
  "296-C": `<p>Parabéns! Recolheu todas as pistas e resolveu os enigmas que o antigo leito lhe propunha… mas esta Aventura não termina aqui!!</p>\n\n<p>Como poderá comprovar, o mapa do tesouro leva-o de novo à cidade. Vamos a isso?</p>`,
  "297": `<p>Dirija-se à próxima ponte, a <strong>Puente de las Flores</strong>, inaugurada em 2002 e adornada com 27.500 flores multicolores que variam segundo a época do ano.</p>\n<p>Pelo lado direito do jardim, um acesso permite-lhe subir e atravessar esta obra de Santiago Calatrava.</p>`,
  "298": `<p>A ponte desemboca numa estrutura cilíndrica realizada em tijolo, muito mais antiga que a ponte.</p>\n<p>Esta estrutura era utilizada principalmente para encher de água as cisternas dos camiões que se encarregavam da limpeza das ruas.</p>`,
};

const merged = { ...existing, ...batch };

const lines = esKeys
  .filter(k => merged[k] !== undefined)
  .map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';

writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
