import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-italiano.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "701": "<p>Si trova già di fronte al Mercato Centrale? Sì? Bene! Continuiamo?</p>",
  "702": "<p>Si trova già nel punto indicato con il numero <mark>11</mark> sulla sua mappa? Bene! Continuiamo alla ricerca del tesoro!</p>",
  "703": "<p>Ottimo! Continuiamo con la ricerca del tesoro! Osservi intorno a sé e potrà vedere alcune rovine che spiccano tra la decorazione botanica del giardino del Turia. Riesce a vederle? Sì? Perfetto, perché la storia seguente speriamo che la sorprenda.</p>",
  "704": "<p>Si trova già nel punto indicato con il numero <mark>6</mark> sulla sua mappa?</p>",
  "704-B": "<p>Si trova già nel punto indicato con il numero <mark>3</mark> sulla sua mappa?</p>",
  "705": "<p>Si trova già nel punto indicato con il numero <mark>24</mark> sulla sua mappa?</p>",
  "706": "<p>Si trova già nel punto indicato con il numero <mark>76</mark> sulla sua mappa?</p>",
  "707": "<p>Di cosa è fatta l'Orxata? Di chufa, di riso o di orzo?</p>",
  "708": "<p>Nel corso della sua Avventura potrà finire di scoprire il maestoso Parco di Cabecera, passando per l'antico mulino del sole; ricordi che anticamente i mulini erano edifici indispensabili per macinare il grano e con ciò produrre la farina necessaria per elaborare, tra l'altro, dolci e prodotti da forno.</p>",
  "709": "<p>Il Molí del Sol, costruito nel 1880, fu il primo dei 18 mulini dell'acequia di Rascanya e l'ultimo idraulico edificato nell'orto valenciano, sfruttando il dislivello del terreno per macinare grano e riso. Dopo l'interramento dell'acequia negli anni '80, l'edificio cadde in disuso fino al suo restauro nell'attuale Parco di Cabecera, punto esatto dove oggi nasce la Ruta Verde del Parco Fluviale del Turia. Questo sentiero ciclopedonale si estende per circa 30 km verso ovest su piste forestali, seguendo il corso naturale del fiume Turia.</p>",
  "710": "<p>Il Museo di Storia di Valencia è probabilmente uno dei migliori luoghi per continuare ad apprendere su questa cultura mediterranea in cui si trova oggi.</p>",
  "711": "<p>Il prossimo punto di interesse nella sua avventura è un luogo molto speciale in cui l'acqua riveste grande importanza. Il centro espositivo e museo Na Turia agisce come punto di incontro cittadino per promuovere la sostenibilità urbana, fungere da centro formativo e offrire risorse educative su ecologia e ambiente.</p>",
  "712": "<p>Sulla sua mappa corrisponde al numero <mark>68</mark>.</p>",
  "713": "<p>NaTuria è uno spazio educativo e ambientale il cui obiettivo è avvicinare la natura alla cittadinanza e promuovere abitudini sostenibili nella vita quotidiana mediante mostre, corsi, laboratori e visite guidate incentrate su sostenibilità, riciclaggio, biodiversità e qualità della vita urbana; nel suo contesto vicino si trova una piccola diga o azud che trattiene l'acqua dell'antico alveo del fiume e fa parte del progetto paesaggistico del parco, ricreando un ambiente acquatico che evoca l'antico Turia con vegetazione riparia, fauna associata come uccelli e anfibi, e zone di passeggio e osservazione, dove inoltre si trova il Molino del Tell, un antico mulino da farina restaurato integrato nelle attività dello stesso NaTuria, in cui si spiegano la sua storia, la vita sostenibile tradizionale e il rapporto storico di Valencia con l'acqua, cosicché questo insieme – la diga e l'ambiente acquatico – funziona principalmente come un elemento educativo e simbolico che ricorda il legame della città con il suo fiume e promuove l'apprendimento sulla gestione sostenibile dell'acqua.</p>",
  "VIV1": `<p>${LOGO} Le raccomanda di seguire il corso della sua mappa e percorrere il vialetto.</p>\n\n<p>A metà del vialetto, a mano destra si trovano le rovine di quella che un tempo era la Torre della Regina del già scomparso palazzo.</p>`,
  "VIV2": "<p>Subito dopo, vedrà un grande cumulo di terra.</p>\n\n<p>Questo è un punto perfetto per scattare magnifiche fotografie delle viste che offre il giardino.</p>\n\n<p>Il cumulo prende il nome di Elio, Capitano Generale dei Regni di Valencia e Murcia nel XIX secolo.</p>\n\n<p>Curiosamente, Elio fu decapitato anni dopo in questo stesso luogo.</p>\n\n<p>Questo cumulo fu creato con le rovine del palazzo, sul quale furono piantati alberi e fiori. Fu sul monte Elio che ebbero inizio i giardini di vivai della città.</p>\n\n<p>Questi punti corrispondono ai numeri <mark>2</mark> e <mark>3</mark> rispettivamente.</p>",
  "VIV3": `<p>Un po' più avanti, a mano sinistra nel vialetto, possiamo osservare la casa del giardiniere capo che corrisponde al numero <mark>4</mark> sulla sua mappa.</p>\n\n<p>Oggi svolge la funzione di uffici dei giardini.</p>\n\n<p>Continui fino alla fine del vialetto delle palme e troverà un divertente circuito urbano in cui i più piccoli imparano, giocando, a interpretare i segnali stradali.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>5</mark>.</p>\n\n<p>${LOGO} La incita a premere pausa e percorrere questo circuito al proprio ritmo; questo è un luogo perfetto per ottenere delle foto della sua Avventura, riprendendola da questo stesso punto una volta lo riterrà opportuno.</p>`,
  "VIV4": "<p>Si posizioni guardando il circuito, giri a sinistra e si addentri nella via Jardineros Mayores.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>6</mark>.</p>\n\n<p>Il tracciato è una zona pavimentata e bordeggiata da esemplari di Jacarandas, originarie del Brasile, e Podocarpus provenienti dalla Cina.</p>\n\n<p>Quest'area viene usata in diversi eventi, come, ad esempio, la fiera del libro.</p>\n\n<p>Continui questo sentiero fino alla fine e vedrà che si apre uno spiazzo.</p>\n\n<p>A sinistra si può vedere un tipico modello dell'architettura rurale valenciana. La nota Alquería de Canet corrisponde al numero <mark>7</mark> sulla sua mappa. Di fronte all'alquería si trova un museo, sulla sua mappa corrisponde al numero <mark>8</mark>.</p>",
  "VIV5": "<p>A cosa è dedicato il museo? Alle scienze naturali? Forse all'architettura? O forse alla storia?</p>",
  "VIV6": `<p>Negli anni '70, questo edificio era conosciuto come "il ristorante di Viveros", oggi ospita al suo interno, tra l'altro, una collezione donata nel 1889 da Don José Rodrigo Botet, ingegnere valenciano, che raccolse un gran numero di resti paleontologici trovati nelle sue escavazioni nel continente americano.</p>\n\n<p>Spiccano l'enorme orso delle caverne (il megaterio) della Patagonia argentina, impronte pietrificate di dinosauri, resti fossili, scheletri, armadilli corazzati, conchiglie marine e numerosi insetti.</p>\n\n<p>Il tutto completato con pannelli esplicativi, zone didattiche e audiovisivi.</p>`,
  "VIV7": "<p>La mappa di questi giardini la porta ad allontanarsi da questo punto per tornare più tardi.</p>\n\n<p>Per ora, si diriga a destra dove l'attende una zona che ricorda i giardini di Versailles.</p>\n\n<p>Sulla sua mappa corrisponde al numero <mark>9</mark>.</p>",
  "VIV8": "<p>Un grande lampione, uno dei pochi che esistono in città, ci permette di intravedere il nostro prossimo obiettivo.</p>",
  "VIV9": "<p>Pochi metri più avanti, nella Rosaleda, emerge una grande fontana circolare proveniente dalla Plaza de la Reina circondata da circa seimila rose di diverse specie, oltre ad altre specie ornamentali.</p>\n\n<p>La rosaleda, piantata nel 1974 e riformata nel 2010, corrisponde sulla sua mappa al numero <mark>10</mark>.</p>",
  "VIV10": `<p>Uscendo dalla parte opposta della rosaleda rimangono i vivai che si occupano di fornire le specie botaniche e la flora alla città.</p>\n\n<p>${LOGO} La incoraggia a premere pausa e a esplorare quest'area botanica al proprio ritmo, potendo continuare la sua ricerca dal museo che corrisponde al numero <mark>8</mark> sulla sua mappa.</p>\n\n<p>Ricordi che il pulsante di pausa può usarlo a suo piacimento e premarlo quando lo ritiene opportuno. Dopo prema semplicemente inizio e continui a risolvere le nostre sfide mentre scopre la città.</p>\n\n<p>I Giardini del Real offrono un'ampia gamma di sculture: Il Riposo, La Dama di Elche, Le Quattro False Stagioni, Risveglio e La Fontana di Nettuno, sono alcuni esemplari che potrà trovare nel suo percorso.</p>`,
  "VIV11": "<p>Si posizioni, se è così gentile, tra l'alquería e il museo; numeri <mark>7</mark> e <mark>8</mark> rispettivamente.</p>\n\n<p>Con l'Alquería alla sua mano sinistra e il Museo alla sua destra, osservi che davanti si apre una piazza destinata a eventi musicali; come concerti e balli tipici. Alla fine di questo spazio, un timido lago si presenta alla sua destra.</p>\n\n<p>Questo è il noto lago dei cigni, dove uccelli migratori, come cicogne e anatre, si riposano in questo habitat protetto per recuperare le forze prima di riprendere il volo. Sulla sua mappa corrisponde al numero <mark>11</mark>.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
console.log('Total claves ES:', esKeys.length);
const missing = esKeys.filter(k => merged[k] === undefined);
if (missing.length) console.log('Claves sin traducir:', missing);
