import { readFileSync, writeFileSync } from 'fs';
const ES_FILE = 'js/parrafos-textos/parrafos-texto-espanol.json';
const TARGET_FILE = 'js/parrafos-textos/parrafos-texto-neerlandes.json';
const LOGO = "<img src='imagenes/imagenes-aplicación/logo_alargado_3.png' alt='València be Guides' style='height:1.4em;vertical-align:baseline;position:relative;bottom:-0.2em;'>";
const rawEs = readFileSync(ES_FILE, 'utf8');
const esKeys = [...rawEs.matchAll(/^  "([^"]+)":/mg)].map(m => m[1]);
let existing = {};
try { existing = JSON.parse(readFileSync(TARGET_FILE, 'utf8')); } catch (e) {}
const batch = {
  "570": "<p>In de loop van dit avontuur zal uw kaart u naar boven leiden om deze brug over te steken, uitgerust met een fietspad en voetgangerszones voor uw veiligheid, om enkele van de architectonische schatten te ontdekken die de historische stad Valencia biedt. Maar nog niet nu; uw avontuur verloopt in het bed van deze oude rivier die is omgevormd tot een tuin.</p>",
  "571": "<p>De <strong>Torres de Quart</strong> zijn een van de bekendste poorten van de christelijke middeleeuwse stadsmuur van Valencia.</p>\n<p>In 1442, het jaar van hun voltooiing, werden de cilindrische torens beschouwd als de meest geschikte om het gebruik van artillerie te weerstaan.</p>\n<p>De <strong>Torres de Quart</strong> werden gebouwd in gotische stijl, hoewel vanwege hun defensieve functionaliteit de decoratie geen kenmerkend element van dit monument is.</p>",
  "572": "<p>In het jaar 1808 verzette Valencia zich in een patriottische beweging tegen de invaderend troepen van Napoleon, door de vijand terug te dringen en hem herhaaldelijk te dwingen zich terug te trekken.</p>\n<p>In de 19e eeuw werd het monument gebruikt als gevangenis, ditmaal militair.</p>\n<p>Het feit dat de <strong>Torres de Quart</strong> als gevangenis in gebruik waren, was wat hen behoedde voor de sloop van de stadsmuren van Valencia in 1865.</p>\n<p>In 2007 werd het geheel volledig gereinigd en opengesteld voor het publiek.</p>",
  "573": "<p>Zoals u kunt vaststellen, zijn tegenwoordig nog steeds de sporen te zien van kanonkogelinslagen en geweerkogeldoorboringen van de Franse artillerie tijdens de Onafhankelijkheidsoorlog.</p>\n<p>Hoeveel kogeldoorboringen kunt u tellen?</p>",
  "574": "<p>Doe geen moeite; er zijn ongeveer 132 kanonsporen geteld en meer dan 1.000 geweerkogeldoorboringen.</p>",
  "575": "<p>Terwijl u de hoofdgevel bewondert, richt uw aandacht op de linkerzijde, waar nog steeds een stuk van de stadsmuur en het beroemde standbeeld van de «Palleter» te zien zijn. De Palleter was een lucifersverkoper die volgens de overlevering op 23 mei 1808 de oorlog aan Napoleon Bonaparte verklaarde.</p>",
  "576": "<p>Dit Avontuur brengt u terug naar de 15e eeuw, tijden waarin Valencia wederom uitblonk.</p>\n<p>In 1409 werd een instelling opgericht waar psychiatrische patiënten konden worden behandeld; het terrein van de huidige Openbare Bibliotheek, uw volgende bestemming, was het eerste psychiatrische ziekenhuis van Europa.</p>",
  "577": `<p>Voor u aankomt, kan een straat vol winkels aan uw linkerhand uw aandacht trekken.</p>\n<p>De calle Colón biedt allerlei mogelijkheden voor de winkelliefhebbers.</p>\n<p>Aan het einde van de straat steken het <strong>Estación del Norte</strong> (treinstation) en de <strong>Plaza de Toros</strong> uit in deze boulevard die tegenwoordig de plek markeert waar de stadsmuur van Valencia in de 14e eeuw stond.</p>\n<p>${LOGO} zal u gedetailleerde informatie geven over dit gebied in Avontuur nummer 5.</p>`,
  "578": "<p>Uw Avontuur leidt u opnieuw naar het oude Valencia.</p>\n<p>U bent zojuist langs het verdwenen Portal de Torrent gegaan, populair bekend als de Poort der Onschuldigen.</p>\n<p>Tijdens dit Avontuur verkent u de beroemde Calle Hospital die nu voor u staat.</p>\n<p>Pauzeer deze audiogids niet en observeer aan uw rechterzijde terwijl u de straat doorloopt.</p>",
  "579": "<p>In de <strong>Calle del Hospital</strong> verwelkomt ons een bescheiden fontein.</p>\n<p>Welke vorm heeft de fontein?</p>\n<p>Is het een schelp? Misschien een vis? Of wellicht een persoon?</p>",
  "580": "<p>De Ermita de Santa Lucía aan uw rechterzijde vertelt u dat u in de goede richting gaat.</p>\n<p>Het oude kerkgebouw werd voltooid in 1511.</p>\n<p>In welk jaar begonnen de werkzaamheden? Kijk op de gevel!</p>",
  "581": "<p>Merkwaardig, nietwaar? De klokkentoren heeft slechts één muur waarin de ruimtes zijn geopend om de klokken te plaatsen.</p>\n<p>Dit architecturale element bekend als een ezelsrug was het werk van Luis Peseto.</p>\n<p>Tegenwoordig luiden haar twee klokken met hedendaagse klanken en veraangenamen ze het leven van de voorbijgangers.</p>",
  "582": "<p>De gevel die u tegenwoordig kunt zien werd gerealiseerd door twee verschillende bouwmeesters tussen 1860 en 1865.</p>\n<p>Sebastián Monleón Estellés ontving de opdracht voor een gevel met drie ingangen. Onder de ezelsrug pronkt in een nis een bronzen buste van Santa Lucía.</p>\n<p>Door de hand van José Esteve verrijken twee moderne sculpturen de gevel; die aan de linkerzijde symboliseert de deugd en die aan de rechterzijde het martelaarschap.</p>",
  "583": "<p>Als laatste toevoegingen vermelden we ook dat de kapel in 1963 werd uitgeroepen tot Nationaal Historisch-Artistiek Monument en in 2007 tot Cultureel Erfgoed.</p>\n<p>Kunt u mij het jaar van de laatste restauratie vertellen?</p>\n<p>U heeft het vast al gezien!</p>",
  "584": "<p>Let extra goed op!</p>\n<p>Uw volgende bestemming is de tuin nog niet.</p>\n<p>Ga verder naar het Colegio del Arte Mayor de la Seda.</p>",
  "585": "<p>De «Zijderoute» was een netwerk van handelsroutes vanaf de 2e eeuw voor Christus.</p>\n<p>Het strekte zich uit over het Aziatische continent en vestigde zich in Europa in de 15e eeuw in de Hispaanse koninkrijken en de westelijke Middellandse Zee; de zijde-industrie was dus al in moslimtijden van groot belang en genoot groot prestige in heel Al-Andalus.</p>\n<p>Gezien haar ligging was de stad Valencia in de tijd van Al-Andalus al beroemd om haar zijdehandel.</p>\n<p>In de 14e eeuw waren er al lokale zijdehandelaren, overwegend joods, maar van de 15e tot de 18e eeuw was het leiderschap van Valencia als belangrijkste centrum van de Spaanse zijdehandel onbetwistbaar; sterker nog, de teelt van de moerbei ging die van de sinaasappelboom in de hele regio vooraf.</p>\n<p>De zijde-industrie was een van de krachtigste van de stad en telde meer dan 3.000 weefgetouwen.</p>\n<p>Tegenwoordig houden de Fallera-jurken het zijdeambacht op handweefgetouwen levend.</p>\n<p>Voor het kostuum worden 10 tot 15 meter zijde in meer dan 20 kleuren gebruikt, plus zilver- en gouddraad.</p>",
  "586": "<p>Met een gevel van 29 meter werd het gebouw dat u nu ziet in 1492 verworven door de Valenciaanse zijdehandelaren. Het onderging door de eeuwen heen diverse verbouwingen, waarbij de laatste een van de belangrijkste was, omdat het van gotische naar barokke stijl overging.</p>\n<p>In welk jaar werden die werkzaamheden uitgevoerd? Was het in 1756, misschien in 1492, of in 1982?</p>\n<p>Heeft u een aanwijzing nodig? Kijk op de gevel van het gebouw.</p>",
  "587": "<p>In het interieur van dit gebouw bevindt zich het Museo de la Seda; met tentoonstellingen van klassieke Valenciaanse stoffen uit de 17e en 18e eeuw in zijn zalen met traditionele keramische vloertegels.</p>\n<p>Ook een collectie samengesteld uit talloze documenten die gedurende vijf eeuwen zijn bewaard, wat dit museum het belangrijkste gildenarchief van Europa maakt.</p>",
  "588": `<p>${LOGO} raadt u aan het ziekenhuispark dat u achter u liet te betreden en er op eigen tempo door te wandelen, terwijl u luistert naar de opmerkelijke sporen van zijn geschiedenis.</p>\n<p>Pauzeer deze audiogids niet en ga, als u zo vriendelijk wilt zijn, naar het aangegeven punt. Dank u.</p>`,
  "589": "<p>Oude verhalen vertellen dat een Valenciaanse monnik, genaamd Joan Gilabert Jofré, getuige was van de steniging van een burger met een psychische beperking die aan zijn lot werd overgelaten door een groep jongens, en ingreep door zijn leven te redden met dit gebaar.</p>\n<p>Na dat als wonderbaar verklaarde daad werden nieuwe maatregelen voorgesteld die mensen in een vergelijkbare toestand zouden controleren en bestuderen, waarmee zonder het te weten het eerste psychiatrische ziekenhuis van Europa werd gecreëerd.</p>",
  "590": "<p>Aan het einde van de 15e eeuw werd een uitbreiding gerealiseerd om niet-dementiepatiënten op te vangen.</p>\n<p>Het park dat u betreedt heeft zijn oorsprong in 1512, de tijd waarin Fernando de Katholieke de integratie van alle kleine ziekenhuizen van Valencia in één decretteerde, waarbij deze ruimte het Provinciaal Ziekenhuis werd. Een goed uitgerust, goed beheerd ziekenhuis met groot prestige en adequate installaties.</p>\n<p>Daartoe werden twee ziekenzalen met kruisvormige plattegrond gebouwd.</p>\n<p>Deze kruisvormige opzet is zeer goed ontworpen, want vanuit de centrale toren konden de vier vleugels van het ziekenhuis tegelijkertijd worden gecontroleerd.</p>",
  "591": "<p>Jaren later, in 1875, werden nieuwe gebouwen gebouwd en werd de faculteit geneeskunde geïnstalleerd die tot 1948 op deze locatie bleef.</p>\n<p>In 1960 werd een nieuw ziekenhuis in Valencia geopend met de capaciteit om aan de behoeften van de bevolking te voldoen.</p>\n<p>Vanaf dan raakte het oude provinciaal ziekenhuis in onbruik en traden de stedenbouwkundige belangen in actie.</p>",
  "592": "<p>Vele gebouwen, zoals de kerk en een van de kruisvormige gebouwen, konden niet worden gered van de sloop.</p>\n<p>De verklaring van het geheel als Nationaal Historisch-Artistiek Monument in november 1963 slaagde erin een deel van dit grote ziekenhuiscentrum te redden, waarbij de ruimte die nu de bibliotheek, de kapel en diverse verspreid liggende resten in de tuinen omvat, overeind bleef staan.</p>",
  "592-B": `<p>In 2009 werd besloten deze tuinen te herordenen met de verspreid liggende elementen; aldus werd in 2012 deze archeologische tuin gecreëerd die we vandaag kunnen zien.</p>\n<p>De ruimte herbergt resten gevonden bij de opgravingen afkomstig van het oude Renaissance-ziekenhuis en andere interessante elementen, zoals: resten van de gevel van de voormalige Faculteit Geneeskunde, de Ermita de Santa Lucía en het Valenciaans Museum van de Verlichting (Muvim). In de ondergrond van het museum zijn resten bewaard van de oude christelijke stadsmuur die in 1865 werd gesloopt.</p>\n<p>${LOGO} nodigt u uit deze audiogids te pauzeren en raadt aan door deze tuin op eigen tempo te wandelen.</p>\n<p>Gebruik de pauzeknop naar eigen goeddunken. Wanneer u het juiste moment acht, ga eenvoudigweg door met het oplossen van onze uitdagingen terwijl u de stad ontdekt.</p>\n<p>Uw avontuur gaat verder vanaf de hoofdtoegang van de bibliotheek.</p>`,
  "593": "<p>Dit Avontuur mengt de Fallero-traditie en de geschiedenis van Valencia. Het doel is de oorsprong, de traditie en de loopbaan van dit feest te leren kennen dat de maand maart in Valencia onderscheidt van alle andere.</p>\n<p>Tijdens uw route ontdekt u verschillende iconische punten die onmisbaar zijn opdat de Fallas mogelijk zouden zijn zoals we ze tegenwoordig kennen.</p>",
  "594": "<p>Gericht naar het Westen dienden de <strong>Torres de Quart</strong>, naast toegangspoort tot de stad, in hun geschiedenis voor verschillende doeleinden, zoals: in 1562 als krutopslag, of in 1626 werd een van de torens bestemd als gevangenis voor prostituees.</p>",
  "595": "<p>Vouw uw kaart open en bekijk hem.</p>\n<p>Met de ingang van Valencia achter u opent zich aan de overkant van de avenue de oude weg die naar de torens leidde.</p>\n<p>Nadat u de avenue hebt overgestoken, neemt u de tweede straat aan uw rechterzijde.</p>\n<p>Dit Avontuur leidt u naar de ontdekking van een van de botanische schatten van de stad. De ingang bevindt zich om de hoek.</p>\n<p>Vergeet niet: het is de tweede straat rechts!</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>64</mark>.</p>\n<p>Vergeet niet op pauze te drukken, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "596": `<p>De huidige Botanische Tuin is niet ver van hier ontstaan in een oude tuin met geneeskrachtige planten waar botanie werd onderwezen.</p>\n<p>Opgericht in 1567 is de Botanische Tuin van de Universiteit van Valencia de oudste van Europa.</p>\n<p>Eeuwen later kocht de Universiteit van Valencia met de steun van diverse entiteiten het terrein waarop het onderwijscentrum is gevestigd.</p>\n<p>Het is vermeldenswaard dat de Botanische Tuin zelf wordt bevloeid door de acequia de Rovella, die de ondergrond de nodige voedingsstoffen verschaft voor het leven dat hij in zijn interieur herbergt.</p>\n<p>Gelukkig verbeterde de hoogleraar Geneeskunde José Pizcueta de installaties gedurende de bijna 40 jaar dat hij verantwoordelijk was voor het toezicht.</p>\n<p>Met het oog op het uitvoeren van klimaatexperimenten werden diverse installaties gebouwd, zoals een houten kas, een beschaduwde zone om de planten tegen de zon te beschermen of zelfs meerdere kassen met verschillende temperaturen en luchtvochtigheden die de groei van soorten geïmporteerd uit alle continenten bevorderden.</p>\n<p>Als u er bent tijdens de openingsuren, nodigt ${LOGO} u uit op pauze te drukken en binnen te gaan om de biodiversiteit te ontdekken die deze prachtige ruimte biedt.</p>\n<p>In het interieur zijn meer dan 3.000 verschillende plantensoorten te zien, waarvan sommige de oudste van Europa zijn, die samenleven in een koel microklimaat in het hart van Valencia.</p>\n<p>Uw Avontuur gaat verder vanaf de ingang van de Botanische Tuin.</p>`,
  "597": "<p>Bravo! Deze zone is vrij van aanwijzingen en uw Avontuur staat op het punt te eindigen! Pauzeer deze audiogids niet en ga naar het aangegeven punt.</p>",
  "597-B": "<p>Bravo! Deze zone is vrij van aanwijzingen en uw Avontuur staat op het punt te eindigen! Pauzeer deze audiogids niet en ga naar het aangegeven punt.</p>",
  "598": "<p>Bekijk uw kaart en merk op dat uw avontuur u terugbrengt naar het oude rivierbed. Met de hoofdingang van de botanische tuin voor u, draai naar links en sla de hoek om, om de muur van de botanische tuin zelf te volgen tot het einde van de straat. Eenmaal daar, steek de avenue over en daal af naar het Parque del Turia.</p>\n<p>Let onderweg extra goed op, want aan uw linkerzijde verschijnt een van de meest bescheiden tuinen van de stad. Op uw kaart staat dit aangegeven met nummer <mark>65</mark>.</p>\n<p>Die Tuin is geïnspireerd op de legende van Hercules die in zijn laatste heldendaad de gouden appels van de Tuin van de Hesperiden moest stelen.</p>\n<p>Druk op pauze en ga naar punt <mark>65</mark> op uw kaart. Wanneer u aankomt, druk op de bijbehorende knop om uw avontuur te hervatten. Dank u.</p>",
  "599": "<p>De Griekse fabel vertelt dat de Hesperiden de nimfen waren die belast waren met de zorg voor de tuin van de gouden appels die de Godin Gea (of Gaia) (moeder aarde) als huwelijksgeschenk aan Hera en Zeus gaf.</p>\n<p>De beroemde Hercules op zijn beurt, bekend om zijn grote kracht, verrichtte vele heldendaden, alsook verschillende misdadige handelingen.</p>\n<p>Na een van hen moest Hercules twaalf werken uitvoeren als opgelegde boetedoening. De laatste van zijn werken was het stelen van die appels na het doden van de honderdkoppige draak die Gea als bewaker had aangesteld.</p>\n<p>Na het verslaan van de draak Ladon veranderden de Hesperiden, geschrokken, in populieren, wilgen en iepen.</p>",
  "600": `<p>Deze bescheiden tuin past de oude Griekse mythe aan op de inheemse boomsoorten in onze omgeving. In dit geval is het gekoesterde object de Valenciaanse sinaasappels.</p>\n<p>De tuin ingehuldigd in 2000 met een oppervlakte van 4.700 vierkante meter bevat een citrusverzameling van meer dan 50 verschillende variëteiten.</p>\n<p>In het interieur bevinden zich ook drie bronzen sculpturen: de Godin Venus, Hercules zelf en de metamorfose van de nimf in een boom.</p>\n<p>Als u er bent tijdens de openingsuren, nodigt ${LOGO} u uit deze audiogids te pauzeren en raadt aan door deze tuin op eigen tempo te wandelen.</p>\n<p>Gebruik de pauzeknop naar eigen goeddunken. Wanneer u het beslist, ga eenvoudigweg door met het oplossen van onze uitdagingen terwijl u de stad ontdekt.</p>`,
  "601": "<p>Bent u klaar om uw avontuur voort te zetten? Uitstekend! Keer terug naar de muur van de botanische tuin en draai naar links, ga dan door tot het einde van de straat.</p>\n<p>Richt uw aandacht aan de overkant van de avenue en zoek het afdalingspunt dat terugkeer naar de oude rivier van Valencia mogelijk maakt. Het zou recht voor u moeten zijn, aan de overkant van de avenue. Kunt u het zien? Goed, want u moet dat punt bereiken.</p>\n<p>Daartoe, met altijd respect voor de verkeersregels, moet u het verkeerslicht aan uw linkerzijde bereiken. De avenue oversteken en de riviermuur volgen tot het afdalingspunt.</p>\n<p>Eenmaal onder de rivier, ga naar uw linkerzijde. Uw doel is het beroemde <strong>Parque de Cabecera</strong> dat zich aan het einde van de <strong>Jardín del Turia</strong> bevindt; onderweg ontdekken we interessante en vermeldenswaardige plekken.</p>\n<p>De eerste is het <strong>Estadio de Atletismo</strong>.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>66</mark>.</p>\n<p>Druk op pauze, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "602": "<p>Een van de elementen die de <strong>Jardín del Turia</strong> verrijkt is het brede scala aan mogelijkheden voor sportliefhebbers. Voetbal-, basketbal-, honkbal-, atletiek- of rugbyvelden nodigen uit om actief te blijven.</p>\n<p>Ook zijn schaatsbanen en talrijke fietspaden veraangenamen het leven van de Valencianen en hun bezoekers.</p>\n<p>Het is als een grote concentratie van sportevenementen gebruikmakend van een natuurlijke ruimte, in een publieke omgeving.</p>\n<p>Het oude bed van de <strong>Río Turia</strong> voorziet de stad van zuurstof en houdt haar in beweging.</p>",
  "603": "<p>Valencia is tegenwoordig een goed verbonden stad die aangepast is aan de behoeften van haar bewoners.</p>\n<p>Een van die behoeften is het benutten van de uren daglicht om het lichaam te trainen en de opgebouwde spanning te verlossen.</p>\n<p>Vanaf het jaar 1991, het jaar van de inhuldiging, wordt in de ruimte die zich voor u opent atletiek beoefend van het beginnersniveau tot het toppresteren.</p>\n<p>Dit sportcomplex bestaat uit: een atletiekbaan van 400 meter, een voetbalveld voor zeven of hockeyveld, diverse kracht- en sportzalen, plus de nodige installaties voor een adequate warming-up, douches en kleedkamers.</p>\n<p>Gelegen in de <strong>Barrio de la Petxina</strong>, waarover we een speciale vermelding zullen maken in de loop van dit avontuur, wordt het Turia-stadion gebruikt door brandweerlieden, politieagenten en andere collectieven om hun fysieke prestaties te verbeteren.</p>",
  "604": "<p>Uw schatkaart nodigt u uit het riviertracé op eigen tempo voort te zetten.</p>\n<p>Onderweg passeert u onder de Puente de Campanar, aangegeven met nummer <mark>67</mark>.</p>\n<p>Een functionele brug die, hoewel ze haar oorsprong heeft in 1937, in 1958 werd herbouwd in beton na de grote overstroming van de Turia.</p>\n<p>Uw volgende bestemming in dit Avontuur is een verhoogd platform dat u prachtige uitzichten biedt op de ruimte waar u zich bevindt.</p>\n<p>Op uw kaart correspondeert dit met nummer <mark>68</mark>.</p>\n<p>Druk op pauze, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent. Dank u.</p>",
  "604-B": "<p>Uw schatkaart nodigt u uit het riviertracé op eigen tempo voort te zetten.</p>\n<p>Onderweg passeert u onder de Puente de Campanar, aangegeven met nummer <mark>10</mark>.</p>\n<p>Een functionele brug die, hoewel ze haar oorsprong heeft in 1937, in 1958 werd herbouwd in beton na de grote overstroming van de Turia.</p>\n<p>Uw volgende bestemming in dit Avontuur is een verhoogd platform dat u prachtige uitzichten biedt op de ruimte waar u zich bevindt. Op uw kaart correspondeert dit met nummer <mark>11</mark>.</p>\n<p>Druk op pauze, ga dan naar het aangegeven punt en druk opnieuw op de doorgaan-knop zodra u op de voorgestelde locatie bent.</p>",
  "605": "<p>Bravo! U heeft alle aanwijzingen verzameld en de raadsels opgelost die het oude rivierbed u voorstelde...</p>\n<p>Ons Avontuur nummer 3 stelt u talrijke extra raadsels voor die u zullen leiden naar de beroemde <strong>Ciudad de las Artes y de las Ciencias</strong>, het futuristische beeld dat het nieuwe Valencia symboliseert.</p>\n<p>De <strong>Ciudad de las Artes y de las Ciencias</strong> is een architecturaal avant-gardistisch complex op wereldniveau, waar elk jaar miljoenen bezoekers naartoe komen om te genieten van zijn cultuur, zijn natuur en zijn wetenschap.</p>",
  "606": `<p>${LOGO} raadt u aan een korte pauze te nemen en om u heen te kijken.</p>\n<p>Zoals u heeft kunnen vaststellen, hebben we in meerdere gelegenheden naar deze ruimte verwezen als «de rivier»; voor de Valencianen is dit nog steeds de populaire naam.</p>`,
  "607": `<p>Terwijl u het volgende bezienswaardige punt in uw Avontuur bereikt, wil ${LOGO} uw verblijf verrijken met deze basisaanbevelingen om een volledige feesteervaring te beleven.</p>`,
  "608": "<p>30 jaar na het ongelukkige incident begon het bed van deze rivier een nieuw gebruik te krijgen in het hart van Valencia.</p>\n<p>In eerste instantie en op overheidsverzoek was het oude rivierbed bestemd om grote snelwegen en gebouwen te huisvesten, en ook om het gebrek aan openbare parkeerplaatsen dat de stad lijdt aan te pakken.</p>",
  "609": "<p>Maar de Valencianen slaagden er met de kreet «de rivier is van ons en we willen haar groen» in de oorspronkelijke plannen te veranderen in een van de grootste stadstuinen van Europa. Een omgeving van zuivere lucht, omringd door goede vibraties.</p>",
  "610": "<p>Kunt u mij de naam van deze oude rivier vertellen?</p>",
  "611": "<p>In dit Avontuur mengt uw volgende bestemming historische architecturale elementen met hedendaagse architectuur en zoals altijd is sport aanwezig.</p>\n<p>Ga, als u zo vriendelijk wilt zijn, naar de volgende brug.</p>",
  "612": "<p>De <strong>Puente amarillo</strong> is een van de plekken in Valencia die gekozen worden om een opkomende sportstijl te beoefenen: Parkour, ook bekend als de kunst van de verplaatsing.</p>\n<p>Deze discipline omvat in zijn training: klimmen, springen, rennen en evenwicht.</p>",
  "613": "<p><i>Parcours</i>, wat in het Frans «traject» betekent, is een lichamelijke discipline gebaseerd op het verplaatsen van het ene punt naar het andere in de omgeving op de eenvoudigste en meest efficiënte manier, aangepast aan de vereisten ervan met uitsluitend gebruik van het eigen lichaam.</p>",
  "614": "<p>De beoefenaar van Parkour wordt <i>traceur</i> of <i>traceuse</i> genoemd afhankelijk of het een man of vrouw is die het beoefent; ze worden vertaald als «tracer», verwijzend naar de handeling van het traceren van het traject.</p>",
  "615": "<p>De beoefening ervan impliceert respect voor de burgers en de omgeving. Het doel is het leven van de beoefenaar of van zijn omgeving niet in gevaar te brengen; daarom wordt Parkour niet beschouwd als een risicovolle lichamelijke activiteit.</p>\n<p>Bovendien is het geen competitieve discipline, waardoor het in Spanje niet als een sport kan worden beschouwd, aangezien sport een wedstrijd impliceert.</p>",
  "616": "<p>De bekende <strong>Puente 9 de Octubre</strong> is een werk van de beroemde Valenciaanse architect Santiago Calatrava.</p>\n<p>In het jaar 1989, het jaar van de inhuldiging van de brug, was de architect nog niet bekend, maar liet hij al het kenmerkende trekje van zijn stijl doorschemeren.</p>",
  "616-B": "<p>Ons Avontuur nummer 3 stelt u talrijke extra raadsels voor die u zullen leiden naar de beroemde <strong>Ciudad de las Artes y de las Ciencias</strong>, het futuristische beeld dat het nieuwe Valencia symboliseert.</p>\n<p>De <strong>Ciudad de las Artes y de las Ciencias</strong> is een architecturaal avant-gardistisch complex op wereldniveau, waar elk jaar miljoenen bezoekers naartoe komen om te genieten van zijn cultuur, zijn natuur en zijn wetenschap.</p>",
  "617": "<p>De <strong>Puente 9 de Octubre</strong> is de grens van de stad Valencia en de toegang tot een van de botanische schatten die het oude rivierbed tegenwoordig biedt.</p>\n<p>U staat op het punt de <strong>Parque de Cabecera</strong> te betreden, gelegen aan de westelijke rand van de stad.</p>\n<p>De <strong>Parque de Cabecera</strong> is een van de longen van Valencia vanwaar diverse fietsroutes vertrekken.</p>",
  "618": "<p>Neem het fietspad dat aan de rechterzijde van het rivierbed ligt en betreed het park. Enkele meters verder, aan uw rechterzijde, rijst een kleine heuvel op die bekend staat als «el Morró».</p>",
  "619": "<p>Zoek de toegang die het beklimmen van de top mogelijk maakt en neem wat tijd om uw kaart open te vouwen en dit gebied te ontdekken.</p>",
};
const merged = { ...existing, ...batch };
const lines = esKeys.filter(k => merged[k] !== undefined).map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])}`);
const json = '{\n' + lines.join(',\n') + '\n}';
writeFileSync(TARGET_FILE, json, 'utf8');
console.log('Total entradas:', lines.length);
